[[getting-started]]
= Bắt đầu với ứng dụng WebFlux

Phần này trình bày cấu hình tối thiểu để sử dụng Spring Security cùng Spring Boot trong một ứng dụng Reactive.

[NOTE]
====
Ứng dụng hoàn chỉnh có tại {gh-samples-url}/reactive/webflux/java/hello-security[kho lưu trữ mẫu của chúng tôi].
Để thuận tiện, bạn có thể tải xuống một ứng dụng Reactive Spring Boot + Spring Security tối giản bằng cách https://start.spring.io/starter.zip?type=maven-project&language=java&packaging=jar&jvmVersion=1.8&groupId=example&artifactId=hello-security&name=hello-security&description=Hello%20Security&packageName=example.hello-security&dependencies=webflux,security[nhấp vào đây].
====

[[dependencies]]
== Cập nhật dependency

Bạn có thể thêm Spring Security vào project Spring Boot bằng cách thêm `spring-boot-starter-security`.

[tabs]
======
Maven::
+
[source,xml,role="primary"]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
----

Gradle::
+
[source,groovy,role="secondary"]
----
    implementation 'org.springframework.boot:spring-boot-starter-security'
----
======


[[servlet-hello-starting]]
== Khởi chạy Hello Spring Security Boot

Giờ đây, bạn có thể {spring-boot-reference-url}reference/using/running-your-application.html#using.running-your-application.with-the-maven-plugin[chạy ứng dụng Spring Boot] bằng cách sử dụng goal `run` của Maven Plugin.
Ví dụ sau cho biết cách thực hiện việc đó (và phần đầu của output khi thực hiện):


.Chạy ứng dụng Spring Boot
[tabs]
======
Maven::
+
[source,bash,role="primary"]
----
$ ./mvnw spring-boot:run
...
INFO 23689 --- [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 8e557245-73e2-4286-969a-ff57fe326336

...
----

Gradle::
+
[source,bash,role="secondary"]
----
$ ./gradlew bootRun
...
INFO 23689 --- [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 8e557245-73e2-4286-969a-ff57fe326336

...
----
======

[[authenticating]]
== Authentication

Bạn có thể truy cập ứng dụng tại http://localhost:8080/; URL này sẽ redirect trình duyệt tới trang đăng nhập mặc định. Bạn có thể cung cấp username mặc định là `user` cùng password được tạo ngẫu nhiên và ghi vào console. Sau đó, trình duyệt sẽ được đưa tới trang mà bạn yêu cầu ban đầu.

Để logout, bạn có thể truy cập http://localhost:8080/logout rồi xác nhận rằng bạn muốn logout.

[[auto-configuration]]
== Auto-configuration của Spring Boot

Spring Boot tự động thêm Spring Security, điều này yêu cầu mọi request phải được authenticated. Spring Boot cũng tạo một user với password được tạo ngẫu nhiên và ghi vào console; password này có thể dùng để thực hiện authentication bằng Form Login hoặc Basic Authentication.
