[[webflux-oauth2]]
= OAuth2 WebFlux

Spring Security cung cấp hỗ trợ toàn diện cho OAuth 2.0.
Phần này trình bày cách tích hợp OAuth 2.0 vào ứng dụng reactive của bạn.

[[oauth2-overview]]
== Tổng quan

Hỗ trợ OAuth 2.0 của Spring Security gồm hai nhóm tính năng chính:

* <<oauth2-resource-server>>
* <<oauth2-client>>

[NOTE]
====
<<oauth2-client-log-users-in,OAuth2 Login>> là một tính năng OAuth2 Client rất mạnh, xứng đáng có một mục riêng trong tài liệu tham khảo.
Tuy nhiên, tính năng này không tồn tại độc lập mà cần OAuth2 Client để hoạt động.
====

Các nhóm tính năng này bao quát vai trò _resource server_ và _client_ được định nghĩa trong https://tools.ietf.org/html/rfc6749#section-1.1[OAuth 2.0 Authorization Framework], còn vai trò _authorization server_ được https://docs.spring.io/spring-authorization-server/reference/index.html[Spring Authorization Server] đảm nhiệm. Đây là một dự án riêng được xây dựng trên xref:index.adoc[Spring Security].

Các vai trò _resource server_ và _client_ trong OAuth2 thường do một hoặc nhiều ứng dụng phía server đảm nhiệm.
Ngoài ra, vai trò _authorization server_ có thể do một hoặc nhiều bên thứ ba đảm nhiệm (như khi tập trung quản lý identity và/hoặc authentication trong một tổ chức) *-hoặc-* do một ứng dụng đảm nhiệm (như trường hợp của Spring Authorization Server).

Ví dụ, một kiến trúc microservices dựa trên OAuth2 điển hình có thể gồm một ứng dụng client phục vụ người dùng, một số resource server backend cung cấp REST API và một authorization server của bên thứ ba để quản lý user và authentication.
Cũng thường gặp trường hợp một ứng dụng chỉ đại diện cho một trong các vai trò này nhưng cần tích hợp với một hoặc nhiều bên thứ ba cung cấp các vai trò còn lại.

Spring Security xử lý các kịch bản này và nhiều kịch bản khác.
Các phần sau trình bày những vai trò được Spring Security cung cấp cùng các ví dụ cho những kịch bản phổ biến.

[[oauth2-resource-server]]
== OAuth2 Resource Server

[NOTE]
====
Phần này tóm tắt các tính năng của OAuth2 Resource Server kèm ví dụ.
Xem xref:reactive/oauth2/resource-server/index.adoc[OAuth 2.0 Resource Server] để đọc tài liệu tham khảo đầy đủ.
====

Bắt đầu bằng cách thêm dependency `spring-security-oauth2-resource-server` vào dự án.
Khi sử dụng Spring Boot, hãy thêm starter sau:

.OAuth2 Client với Spring Boot
[tabs]
======
Gradle::
+
[source,gradle,role="primary"]
----
implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
----

Maven::
+
[source,maven,role="secondary"]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>
----
======

[TIP]
====
Xem xref:getting-spring-security.adoc[] để biết các tùy chọn khác khi không sử dụng Spring Boot.
====

Hãy xem xét các trường hợp sử dụng sau của OAuth2 Resource Server:

* Tôi muốn <<oauth2-resource-server-access-token,bảo vệ quyền truy cập API bằng OAuth2>> (authorization server cung cấp JWT hoặc opaque access token)
* Tôi muốn <<oauth2-resource-server-custom-jwt,bảo vệ quyền truy cập API bằng JWT>> (custom token)

[[oauth2-resource-server-access-token]]
=== Bảo vệ quyền truy cập bằng OAuth2 Access Token

Việc bảo vệ quyền truy cập API bằng OAuth2 access token rất phổ biến.
Trong hầu hết trường hợp, Spring Security chỉ yêu cầu cấu hình tối thiểu để bảo mật một ứng dụng bằng OAuth2.

Spring Security hỗ trợ hai loại `Bearer` token, mỗi loại sử dụng một component khác nhau để validate:

* <<oauth2-resource-server-access-token-jwt,Hỗ trợ JWT>> sử dụng bean `ReactiveJwtDecoder` để validate signature và decode token
* <<oauth2-resource-server-access-token-opaque,Hỗ trợ opaque token>> sử dụng bean `ReactiveOpaqueTokenIntrospector` để introspect token

[[oauth2-resource-server-access-token-jwt]]
==== Hỗ trợ JWT

Ví dụ sau cấu hình bean `ReactiveJwtDecoder` bằng configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://my-auth-server.com
----

Khi sử dụng Spring Boot, chỉ cần như vậy là đủ.
Cấu hình mặc định do Spring Boot cung cấp tương đương với cấu hình sau:

.Cấu hình Resource Server với JWT
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2ResourceServer((oauth2) -> oauth2
				.jwt(Customizer.withDefaults())
			);
		return http.build();
	}

	@Bean
	public ReactiveJwtDecoder jwtDecoder() {
		return ReactiveJwtDecoders.fromIssuerLocation("https://my-auth-server.com");
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			authorizeExchange {
				authorize(anyExchange, authenticated)
			}
			oauth2ResourceServer {
				jwt { }
			}
		}
	}

	@Bean
	fun jwtDecoder(): ReactiveJwtDecoder {
		return ReactiveJwtDecoders.fromIssuerLocation("https://my-auth-server.com")
	}

}
----
=====

[[oauth2-resource-server-access-token-opaque]]
==== Hỗ trợ Opaque Token

Ví dụ sau cấu hình bean `ReactiveOpaqueTokenIntrospector` bằng configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://my-auth-server.com/oauth2/introspect
          client-id: my-client-id
          client-secret: my-client-secret
----

Khi sử dụng Spring Boot, chỉ cần như vậy là đủ.
Cấu hình mặc định do Spring Boot cung cấp tương đương với cấu hình sau:

.Cấu hình Resource Server với Opaque Token
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2ResourceServer((oauth2) -> oauth2
				.opaqueToken(Customizer.withDefaults())
			);
		return http.build();
	}

	@Bean
	public ReactiveOpaqueTokenIntrospector opaqueTokenIntrospector() {
		return new SpringReactiveOpaqueTokenIntrospector(
			"https://my-auth-server.com/oauth2/introspect", "my-client-id", "my-client-secret");
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			authorizeExchange {
				authorize(anyExchange, authenticated)
			}
			oauth2ResourceServer {
				opaqueToken { }
			}
		}
	}

	@Bean
	fun opaqueTokenIntrospector(): ReactiveOpaqueTokenIntrospector {
		return SpringReactiveOpaqueTokenIntrospector(
			"https://my-auth-server.com/oauth2/introspect", "my-client-id", "my-client-secret"
		)
	}

}
----
=====

[[oauth2-resource-server-custom-jwt]]
=== Bảo vệ quyền truy cập bằng custom JWT

Bảo vệ quyền truy cập API bằng JWT là một nhu cầu khá phổ biến, đặc biệt khi frontend được xây dựng dưới dạng single-page application.
Hỗ trợ OAuth2 Resource Server trong Spring Security có thể dùng cho bất kỳ loại `Bearer` token nào, bao gồm custom JWT.

Để bảo vệ API bằng JWT, chỉ cần một bean `ReactiveJwtDecoder`, dùng để validate signature và decode token.
Spring Security sẽ tự động sử dụng bean được cung cấp để cấu hình bảo vệ trong `SecurityWebFilterChain`.

Ví dụ sau cấu hình bean `ReactiveJwtDecoder` bằng configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:my-public-key.pub
----

[NOTE]
====
Bạn có thể cung cấp public key dưới dạng classpath resource (trong ví dụ này có tên là `my-public-key.pub`).
====

Khi sử dụng Spring Boot, chỉ cần như vậy là đủ.
Cấu hình mặc định do Spring Boot cung cấp tương đương với cấu hình sau:

.Cấu hình Resource Server với Custom JWT
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2ResourceServer((oauth2) -> oauth2
				.jwt(Customizer.withDefaults())
			);
		return http.build();
	}

	@Bean
	public ReactiveJwtDecoder jwtDecoder() {
		return NimbusReactiveJwtDecoder.withPublicKey(publicKey()).build();
	}

	private RSAPublicKey publicKey() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			authorizeExchange {
				authorize(anyExchange, authenticated)
			}
			oauth2ResourceServer {
				jwt { }
			}
		}
	}

	@Bean
	fun jwtDecoder(): ReactiveJwtDecoder {
		return NimbusReactiveJwtDecoder.withPublicKey(publicKey()).build()
	}

	private fun publicKey(): RSAPublicKey {
		// ...
	}

}
----
=====

[NOTE]
====
Spring Security không cung cấp endpoint để mint token.
Tuy nhiên, Spring Security cung cấp interface `JwtEncoder` cùng một implementation là `NimbusJwtEncoder`.
====

[[oauth2-client]]
== OAuth2 Client

[NOTE]
====
Phần này tóm tắt các tính năng của OAuth2 Client kèm ví dụ.
Xem xref:reactive/oauth2/client/index.adoc[OAuth 2.0 Client] và xref:reactive/oauth2/login/index.adoc[OAuth 2.0 Login] để đọc tài liệu tham khảo đầy đủ.
====

Bắt đầu bằng cách thêm dependency `spring-security-oauth2-client` vào dự án.
Khi sử dụng Spring Boot, hãy thêm starter sau:

.OAuth2 Client với Spring Boot
[tabs]
======
Gradle::
+
[source,gradle,role="primary"]
----
implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
----

Maven::
+
[source,maven,role="secondary"]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-oauth2-client</artifactId>
</dependency>
----
======

[TIP]
====
Xem xref:getting-spring-security.adoc[] để biết các tùy chọn khác khi không sử dụng Spring Boot.
====

Hãy xem xét các trường hợp sử dụng sau của OAuth2 Client:

* Tôi muốn <<oauth2-client-log-users-in,đăng nhập người dùng bằng OAuth 2.0 hoặc OpenID Connect 1.0>>
* Tôi muốn <<oauth2-client-access-protected-resources,lấy access token cho người dùng>> để truy cập API của bên thứ ba
* Tôi muốn <<oauth2-client-access-protected-resources-current-user,thực hiện cả hai việc>> (đăng nhập người dùng _và_ truy cập API của bên thứ ba)
* Tôi muốn <<oauth2-client-enable-extension-grant-type,bật extension grant type>>
* Tôi muốn <<oauth2-client-customize-existing-grant-type,tùy chỉnh grant type hiện có>>
* Tôi muốn <<oauth2-client-customize-request-parameters,tùy chỉnh token request parameters>>
* Tôi muốn <<oauth2-client-customize-web-client,tùy chỉnh `WebClient` mà các component OAuth2 Client sử dụng>>

[[oauth2-client-log-users-in]]
=== Đăng nhập người dùng bằng OAuth2

Việc yêu cầu người dùng đăng nhập qua OAuth2 rất phổ biến.
https://openid.net/specs/openid-connect-core-1_0.html[OpenID Connect 1.0] cung cấp một token đặc biệt gọi là `id_token`, được thiết kế để cho phép OAuth2 Client xác minh danh tính người dùng và đăng nhập người dùng.
Trong một số trường hợp, OAuth2 có thể được dùng trực tiếp để đăng nhập người dùng (như trường hợp các nhà cung cấp social login phổ biến không triển khai OpenID Connect, chẳng hạn GitHub và Facebook).

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có khả năng đăng nhập người dùng bằng OAuth2 hoặc OpenID Connect:

.Cấu hình OAuth2 Login
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			// ...
			.oauth2Login(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			// ...
			oauth2Login { }
		}
	}

}
----
=====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ReactiveClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryReactiveClientRegistrationRepository` bằng configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc-client:
            provider: my-oidc-provider
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          my-oidc-provider:
            issuer-uri: https://my-oidc-provider.com
----

Với cấu hình trên, ứng dụng hiện hỗ trợ thêm hai endpoint:

1. Login endpoint (ví dụ `/oauth2/authorization/my-oidc-client`) được dùng để bắt đầu đăng nhập và redirect đến authorization server của bên thứ ba.
2. Redirection endpoint (ví dụ `/login/oauth2/code/my-oidc-client`) được authorization server dùng để redirect về client application, đồng thời chứa parameter `code` dùng để lấy `id_token` và/hoặc `access_token` thông qua access token request.

[NOTE]
====
Sự hiện diện của scope `openid` trong cấu hình trên cho biết cần sử dụng OpenID Connect 1.0.
Điều này chỉ định Spring Security sử dụng các component dành riêng cho OIDC (chẳng hạn `OidcReactiveOAuth2UserService`) khi xử lý request.
Nếu không có scope này, Spring Security sẽ sử dụng các component dành riêng cho OAuth2 (chẳng hạn `DefaultReactiveOAuth2UserService`).
====

[[oauth2-client-access-protected-resources]]
=== Truy cập tài nguyên được bảo vệ

Request đến API của bên thứ ba được bảo vệ bởi OAuth2 là một use case cốt lõi của OAuth2 Client.
Việc này được thực hiện bằng cách authorize một client (được biểu diễn bằng class `OAuth2AuthorizedClient` trong Spring Security) và truy cập tài nguyên được bảo vệ bằng cách đặt `Bearer` token vào header `Authorization` của outbound request.

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có thể request tài nguyên được bảo vệ từ API của bên thứ ba:

.Cấu hình OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			// ...
			.oauth2Client(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			// ...
			oauth2Client { }
		}
	}

}
----
=====

[NOTE]
====
Ví dụ trên không cung cấp cách đăng nhập người dùng.
Bạn có thể sử dụng bất kỳ cơ chế login nào khác (chẳng hạn `formLogin()`).
Xem <<oauth2-client-access-protected-resources-current-user,phần tiếp theo>> để biết ví dụ kết hợp `oauth2Client()` với `oauth2Login()`.
====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ReactiveClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryReactiveClientRegistrationRepository` bằng configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth2-client:
            provider: my-auth-server
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: message.read,message.write
        provider:
          my-auth-server:
            issuer-uri: https://my-auth-server.com
----

Ngoài việc cấu hình Spring Security để hỗ trợ các tính năng OAuth2 Client, bạn cũng cần quyết định cách truy cập tài nguyên được bảo vệ và cấu hình ứng dụng tương ứng.
Spring Security cung cấp các implementation của `ReactiveOAuth2AuthorizedClientManager` để lấy access token có thể dùng để truy cập tài nguyên được bảo vệ.

[TIP]
====
Spring Security đăng ký bean `ReactiveOAuth2AuthorizedClientManager` mặc định cho bạn khi chưa có bean nào tồn tại.
====

Cách dễ nhất để sử dụng `ReactiveOAuth2AuthorizedClientManager` là thông qua `ExchangeFilterFunction`, một component intercept request thông qua `WebClient`.

Ví dụ sau sử dụng `ReactiveOAuth2AuthorizedClientManager` mặc định để cấu hình `WebClient` có thể truy cập tài nguyên được bảo vệ bằng cách đặt `Bearer` token vào header `Authorization` của mỗi request:

.Cấu hình `WebClient` với `ExchangeFilterFunction`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class WebClientConfig {

	@Bean
	public WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
		ServerOAuth2AuthorizedClientExchangeFilterFunction filter =
				new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
		return WebClient.builder()
				.filter(filter)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class WebClientConfig {

	@Bean
	fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
		val filter = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
		return WebClient.builder()
			.filter(filter)
			.build()
	}

}
----
=====

`WebClient` đã được cấu hình ở trên có thể được sử dụng như trong ví dụ sau:

[[oauth2-client-accessing-protected-resources-example]]
.Sử dụng `WebClient` để truy cập tài nguyên được bảo vệ
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.client.web.reactive.function.client.ServerOAuth2AuthorizedClientExchangeFilterFunction.clientRegistrationId;

@RestController
public class MessagesController {

	private final WebClient webClient;

	public MessagesController(WebClient webClient) {
		this.webClient = webClient;
	}

	@GetMapping("/messages")
	public Mono<ResponseEntity<List<Message>>> messages() {
		return this.webClient.get()
				.uri("http://localhost:8090/messages")
				.attributes(clientRegistrationId("my-oauth2-client"))
				.retrieve()
				.toEntityList(Message.class);
	}

	public record Message(String message) {
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.client.web.reactive.function.client.ServerOAuth2AuthorizedClientExchangeFilterFunction.clientRegistrationId

@RestController
class MessagesController(private val webClient: WebClient) {

	@GetMapping("/messages")
	fun messages(): Mono<ResponseEntity<List<Message>>> {
		return webClient.get()
			.uri("http://localhost:8090/messages")
			.attributes(clientRegistrationId("my-oauth2-client"))
			.retrieve()
			.toEntityList<Message>()
	}

	data class Message(val message: String)

}
----
=====

[[oauth2-client-access-protected-resources-current-user]]
=== Truy cập tài nguyên được bảo vệ cho người dùng hiện tại

Khi người dùng đăng nhập qua OAuth2 hoặc OpenID Connect, authorization server có thể cung cấp access token dùng trực tiếp để truy cập tài nguyên được bảo vệ.
Điều này thuận tiện vì chỉ cần cấu hình một `ClientRegistration` cho cả hai use case.

[NOTE]
====
Phần này kết hợp <<oauth2-client-log-users-in>> và <<oauth2-client-access-protected-resources>> vào một cấu hình duy nhất.
Có những kịch bản nâng cao khác, chẳng hạn cấu hình một `ClientRegistration` để login và một `ClientRegistration` khác để truy cập tài nguyên được bảo vệ.
Tất cả các kịch bản như vậy đều sử dụng cùng cấu hình cơ bản.
====

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có khả năng đăng nhập người dùng _và_ request tài nguyên được bảo vệ từ API của bên thứ ba:

.Cấu hình OAuth2 Login và OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			// ...
			.oauth2Login(Customizer.withDefaults())
			.oauth2Client(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			// ...
			oauth2Login { }
			oauth2Client { }
		}
	}

}
----
=====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ReactiveClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryReactiveClientRegistrationRepository` bằng configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-combined-client:
            provider: my-auth-server
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: openid,profile,message.read,message.write
        provider:
          my-auth-server:
            issuer-uri: https://my-auth-server.com
----

[NOTE]
====
Điểm khác biệt chính giữa các ví dụ trước (<<oauth2-client-log-users-in>>, <<oauth2-client-access-protected-resources>>) và ví dụ này là giá trị được cấu hình qua property `scope`, kết hợp các scope chuẩn `openid` và `profile` với các scope tùy chỉnh `message.read` và `message.write`.
====

Ngoài việc cấu hình Spring Security để hỗ trợ các tính năng OAuth2 Client, bạn cũng cần quyết định cách truy cập tài nguyên được bảo vệ và cấu hình ứng dụng tương ứng.
Spring Security cung cấp các implementation của `ReactiveOAuth2AuthorizedClientManager` để lấy access token có thể dùng để truy cập tài nguyên được bảo vệ.

[TIP]
====
Spring Security đăng ký bean `ReactiveOAuth2AuthorizedClientManager` mặc định cho bạn khi chưa có bean nào tồn tại.
====

Cách dễ nhất để sử dụng `ReactiveOAuth2AuthorizedClientManager` là thông qua `ExchangeFilterFunction`, một component intercept request thông qua `WebClient`.

Ví dụ sau sử dụng `ReactiveOAuth2AuthorizedClientManager` mặc định để cấu hình `WebClient` có thể truy cập tài nguyên được bảo vệ bằng cách đặt `Bearer` token vào header `Authorization` của mỗi request:

.Cấu hình `WebClient` với `ExchangeFilterFunction`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class WebClientConfig {

	@Bean
	public WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
		ServerOAuth2AuthorizedClientExchangeFilterFunction filter =
				new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
		return WebClient.builder()
				.filter(filter)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class WebClientConfig {

	@Bean
	fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
		val filter = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
		return WebClient.builder()
			.filter(filter)
			.build()
	}

}
----
=====

`WebClient` đã được cấu hình ở trên có thể được sử dụng như trong ví dụ sau:

[[oauth2-client-accessing-protected-resources-current-user-example]]
.Sử dụng `WebClient` để truy cập tài nguyên được bảo vệ (người dùng hiện tại)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@RestController
public class MessagesController {

	private final WebClient webClient;

	public MessagesController(WebClient webClient) {
		this.webClient = webClient;
	}

	@GetMapping("/messages")
	public Mono<ResponseEntity<List<Message>>> messages() {
		return this.webClient.get()
				.uri("http://localhost:8090/messages")
				.retrieve()
				.toEntityList(Message.class);
	}

	public record Message(String message) {
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RestController
class MessagesController(private val webClient: WebClient) {

	@GetMapping("/messages")
	fun messages(): Mono<ResponseEntity<List<Message>>> {
		return webClient.get()
			.uri("http://localhost:8090/messages")
			.retrieve()
			.toEntityList<Message>()
	}

	data class Message(val message: String)

}
----
=====

[NOTE]
====
Khác với <<oauth2-client-accessing-protected-resources-example,ví dụ trước>>, lưu ý rằng chúng ta không cần chỉ định `clientRegistrationId` muốn sử dụng cho Spring Security.
Đó là vì giá trị này có thể được suy ra từ người dùng hiện đã đăng nhập.
====

[[oauth2-client-enable-extension-grant-type]]
=== Bật Extension Grant Type

Một use case phổ biến là bật và/hoặc cấu hình extension grant type.
Ví dụ, Spring Security hỗ trợ các grant type `jwt-bearer` và `token-exchange`, nhưng không bật chúng theo mặc định vì chúng không thuộc core specification của OAuth 2.0.

Với Spring Security 6.3 trở lên, chúng ta chỉ cần publish bean cho một hoặc nhiều `ReactiveOAuth2AuthorizedClientProvider`, và các bean này sẽ được tự động nhận diện.
Ví dụ sau chỉ bật grant type `jwt-bearer`:

.Bật Grant Type `jwt-bearer`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AuthorizedClientProvider jwtBearer() {
		return new JwtBearerReactiveOAuth2AuthorizedClientProvider();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun jwtBearer(): ReactiveOAuth2AuthorizedClientProvider {
		return JwtBearerReactiveOAuth2AuthorizedClientProvider()
	}

}
----
=====

Spring Security sẽ tự động publish `ReactiveOAuth2AuthorizedClientManager` mặc định khi chưa có bean nào được cung cấp trước đó.

[TIP]
====
Bất kỳ bean `OAuth2AuthorizedClientProvider` tùy chỉnh nào cũng sẽ được nhận diện và áp dụng cho `ReactiveOAuth2AuthorizedClientManager` được cung cấp, sau các grant type mặc định.
====

Trong các phiên bản trước Spring Security 6.3, chúng ta phải tự publish bean này và đồng thời bảo đảm bật lại các grant type mặc định.
Để hiểu những gì được cấu hình phía sau, cấu hình có thể như sau:

.Bật Grant Type `jwt-bearer` (trước 6.3)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
			ReactiveClientRegistrationRepository clientRegistrationRepository,
			ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

		ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken()
				.clientCredentials()
				.provider(new JwtBearerReactiveOAuth2AuthorizedClientProvider())
				.build();

		DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
				clientRegistrationRepository, authorizedClientRepository);
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

		return authorizedClientManager;
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun authorizedClientManager(
		clientRegistrationRepository: ReactiveClientRegistrationRepository,
		authorizedClientRepository: ServerOAuth2AuthorizedClientRepository
	): ReactiveOAuth2AuthorizedClientManager {
		val authorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
			.authorizationCode()
			.refreshToken()
			.clientCredentials()
			.provider(JwtBearerReactiveOAuth2AuthorizedClientProvider())
			.build()

		val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
			clientRegistrationRepository, authorizedClientRepository
		)
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

		return authorizedClientManager
	}

}
----
=====

[[oauth2-client-customize-existing-grant-type]]
=== Tùy chỉnh Grant Type hiện có

Khả năng <<oauth2-client-enable-extension-grant-type,bật extension grant type>> bằng cách publish bean cũng cho phép tùy chỉnh grant type hiện có mà không cần định nghĩa lại cấu hình mặc định.
Ví dụ, nếu muốn tùy chỉnh clock skew của `ReactiveOAuth2AuthorizedClientProvider` cho grant `client_credentials`, chúng ta chỉ cần publish bean như sau:

.Tùy chỉnh Grant Type Client Credentials
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AuthorizedClientProvider clientCredentials() {
		ClientCredentialsReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
				new ClientCredentialsReactiveOAuth2AuthorizedClientProvider();
		authorizedClientProvider.setClockSkew(Duration.ofMinutes(5));

		return authorizedClientProvider;
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun clientCredentials(): ReactiveOAuth2AuthorizedClientProvider {
		val authorizedClientProvider = ClientCredentialsReactiveOAuth2AuthorizedClientProvider()
		authorizedClientProvider.setClockSkew(Duration.ofMinutes(5))
		return authorizedClientProvider
	}

}
----
=====

[[oauth2-client-customize-request-parameters]]
=== Tùy chỉnh Token Request Parameters

Việc tùy chỉnh request parameters khi lấy access token khá phổ biến.
Ví dụ, giả sử chúng ta muốn thêm custom parameter `audience` vào token request vì provider yêu cầu parameter này cho grant `authorization_code`.

Chúng ta chỉ cần publish bean kiểu `ReactiveOAuth2AccessTokenResponseClient` với generic type `OAuth2AuthorizationCodeGrantRequest`, và Spring Security sẽ sử dụng bean này để cấu hình các component OAuth2 Client.

Ví dụ sau tùy chỉnh token request parameters cho grant `authorization_code`:

.Tùy chỉnh Token Request Parameters cho Authorization Code Grant
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> authorizationCodeAccessTokenResponseClient() {
		WebClientReactiveAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.addParametersConverter(parametersConverter());

		return accessTokenResponseClient;
	}

	private static Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> parametersConverter() {
		return (grantRequest) -> {
			MultiValueMap<String, String> parameters = new LinkedMultiValueMap<>();
			parameters.set("audience", "xyz_value");

			return parameters;
		};
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun authorizationCodeAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
		accessTokenResponseClient.addParametersConverter(parametersConverter())

		return accessTokenResponseClient
	}

	private fun parametersConverter(): Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> {
		return Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> { grantRequest ->
			LinkedMultiValueMap<String, String>().also { parameters ->
				parameters["audience"] = "xyz_value"
			}
		}
	}

}
----
=====

[TIP]
====
Lưu ý rằng trong trường hợp này chúng ta không cần tùy chỉnh bean `SecurityWebFilterChain` mà có thể dùng cấu hình mặc định.
Nếu sử dụng Spring Boot mà không có tùy chỉnh bổ sung, thực tế chúng ta có thể bỏ hoàn toàn bean `SecurityWebFilterChain`.
====

Như vậy, cung cấp `ReactiveOAuth2AccessTokenResponseClient` dưới dạng bean khá thuận tiện.
Khi sử dụng trực tiếp Spring Security DSL, chúng ta cần bảo đảm tùy chỉnh này được áp dụng cho cả OAuth2 Login (nếu sử dụng tính năng này) và các component OAuth2 Client.
Để hiểu những gì được cấu hình phía sau, cấu hình khi dùng DSL sẽ có dạng như sau:

.Tùy chỉnh Token Request Parameter cho Authorization Code Grant bằng DSL
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		WebClientReactiveAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.addParametersConverter(parametersConverter());

		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login((oauth2Login) -> oauth2Login
				.authenticationManager(new DelegatingReactiveAuthenticationManager(
					new OidcAuthorizationCodeReactiveAuthenticationManager(
						accessTokenResponseClient, new OidcReactiveOAuth2UserService()
					),
					new OAuth2LoginReactiveAuthenticationManager(
						accessTokenResponseClient, new DefaultReactiveOAuth2UserService()
					)
				))
			)
			.oauth2Client((oauth2Client) -> oauth2Client
				.authenticationManager(new OAuth2AuthorizationCodeReactiveAuthenticationManager(
					accessTokenResponseClient
				))
			);

		return http.build();
	}

	private static Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> parametersConverter() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

	@Bean
	fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		val accessTokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
		accessTokenResponseClient.addParametersConverter(parametersConverter())

		return http {
			authorizeExchange {
				authorize(anyExchange, authenticated)
			}
			oauth2Login {
				authenticationManager = DelegatingReactiveAuthenticationManager(
					OidcAuthorizationCodeReactiveAuthenticationManager(
						accessTokenResponseClient, OidcReactiveOAuth2UserService()
					),
					OAuth2LoginReactiveAuthenticationManager(
						accessTokenResponseClient, DefaultReactiveOAuth2UserService()
					)
				)
			}
			oauth2Client {
				authenticationManager = OAuth2AuthorizationCodeReactiveAuthenticationManager(
					accessTokenResponseClient
				)
			}
		}
	}

	private fun parametersConverter(): Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> {
		// ...
	}

}
----
=====

Đối với các grant type khác, chúng ta có thể publish thêm các bean `ReactiveOAuth2AccessTokenResponseClient` để ghi đè cấu hình mặc định.
Ví dụ, để tùy chỉnh các token request cho grant `client_credentials`, chúng ta có thể publish bean sau:

.Tùy chỉnh Token Request Parameters cho Client Credentials Grant
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsAccessTokenResponseClient() {
		WebClientReactiveClientCredentialsTokenResponseClient accessTokenResponseClient =
				new WebClientReactiveClientCredentialsTokenResponseClient();
		accessTokenResponseClient.addParametersConverter(parametersConverter());

		return accessTokenResponseClient;
	}

	private static Converter<OAuth2ClientCredentialsGrantRequest, MultiValueMap<String, String>> parametersConverter() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun clientCredentialsAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveClientCredentialsTokenResponseClient()
		accessTokenResponseClient.addParametersConverter(parametersConverter())

		return accessTokenResponseClient
	}

	private fun parametersConverter(): Converter<OAuth2ClientCredentialsGrantRequest, MultiValueMap<String, String>> {
		// ...
	}

}
----
=====

Spring Security tự động resolve các generic type sau của bean `ReactiveOAuth2AccessTokenResponseClient`:

* `OAuth2AuthorizationCodeGrantRequest` (xem `WebClientReactiveAuthorizationCodeTokenResponseClient`)
* `OAuth2RefreshTokenGrantRequest` (xem `WebClientReactiveRefreshTokenTokenResponseClient`)
* `OAuth2ClientCredentialsGrantRequest` (xem `WebClientReactiveClientCredentialsTokenResponseClient`)
* `JwtBearerGrantRequest` (xem `WebClientReactiveJwtBearerTokenResponseClient`)
* `TokenExchangeGrantRequest` (xem `WebClientReactiveTokenExchangeTokenResponseClient`)

[TIP]
====
Publish bean có kiểu `ReactiveOAuth2AccessTokenResponseClient<JwtBearerGrantRequest>` sẽ tự động bật grant type `jwt-bearer` mà không cần <<oauth2-client-enable-extension-grant-type,cấu hình riêng>>.
====

[TIP]
====
Publish bean có kiểu `ReactiveOAuth2AccessTokenResponseClient<TokenExchangeGrantRequest>` sẽ tự động bật grant type `token-exchange` mà không cần <<oauth2-client-enable-extension-grant-type,cấu hình riêng>>.
====

[[oauth2-client-customize-web-client]]
=== Tùy chỉnh `WebClient` mà các component OAuth2 Client sử dụng

Một use case phổ biến khác là tùy chỉnh `WebClient` được dùng để lấy access token.
Chúng ta có thể cần làm vậy để tùy chỉnh HTTP client library bên dưới (thông qua `ClientHttpConnector` tùy chỉnh), nhằm cấu hình SSL hoặc áp dụng proxy settings cho mạng doanh nghiệp.

Với Spring Security 6.3 trở lên, chúng ta chỉ cần publish các bean kiểu `ReactiveOAuth2AccessTokenResponseClient`, và Spring Security sẽ tự động cấu hình và publish bean `ReactiveOAuth2AuthorizedClientManager` cho chúng ta.

Ví dụ sau tùy chỉnh `WebClient` cho tất cả grant type được hỗ trợ:

.Tùy chỉnh `WebClient` cho OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> authorizationCodeAccessTokenResponseClient() {
		WebClientReactiveAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.setWebClient(webClient());

		return accessTokenResponseClient;
	}

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> refreshTokenAccessTokenResponseClient() {
		WebClientReactiveRefreshTokenTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveRefreshTokenTokenResponseClient();
		accessTokenResponseClient.setWebClient(webClient());

		return accessTokenResponseClient;
	}

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsAccessTokenResponseClient() {
		WebClientReactiveClientCredentialsTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveClientCredentialsTokenResponseClient();
		accessTokenResponseClient.setWebClient(webClient());

		return accessTokenResponseClient;
	}

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<JwtBearerGrantRequest> jwtBearerAccessTokenResponseClient() {
		WebClientReactiveJwtBearerTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveJwtBearerTokenResponseClient();
		accessTokenResponseClient.setWebClient(webClient());

		return accessTokenResponseClient;
	}

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> tokenExchangeAccessTokenResponseClient() {
		WebClientReactiveTokenExchangeTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveTokenExchangeTokenResponseClient();
		accessTokenResponseClient.setWebClient(webClient());

		return accessTokenResponseClient;
	}

	@Bean
	public WebClient webClient() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun authorizationCodeAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
		accessTokenResponseClient.setWebClient(webClient())

		return accessTokenResponseClient
	}

	@Bean
	fun refreshTokenAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveRefreshTokenTokenResponseClient()
		accessTokenResponseClient.setWebClient(webClient())

		return accessTokenResponseClient
	}

	@Bean
	fun clientCredentialsAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveClientCredentialsTokenResponseClient()
		accessTokenResponseClient.setWebClient(webClient())

		return accessTokenResponseClient
	}

	@Bean
	fun jwtBearerAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<JwtBearerGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveJwtBearerTokenResponseClient()
		accessTokenResponseClient.setWebClient(webClient())

		return accessTokenResponseClient
	}

	@Bean
	fun tokenExchangeAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveTokenExchangeTokenResponseClient()
		accessTokenResponseClient.setWebClient(webClient())

		return accessTokenResponseClient
	}

	@Bean
	fun webClient(): WebClient {
		// ...
	}

}
----
=====

Spring Security sẽ tự động publish `ReactiveOAuth2AuthorizedClientManager` mặc định khi chưa có bean nào được cung cấp.

[TIP]
====
Lưu ý rằng trong trường hợp này chúng ta không cần tùy chỉnh bean `SecurityWebFilterChain` mà có thể dùng cấu hình mặc định.
Nếu sử dụng Spring Boot mà không có tùy chỉnh bổ sung, thực tế chúng ta có thể bỏ hoàn toàn bean `SecurityWebFilterChain`.
====

Trước Spring Security 6.3, chúng ta phải tự áp dụng tùy chỉnh này cho các component OAuth2 Client.
Mặc dù có thể publish bean kiểu `ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest>` cho grant `authorization_code`, chúng ta phải publish bean kiểu `ReactiveOAuth2AuthorizedClientManager` cho các grant type khác.
Để hiểu những gì được cấu hình phía sau, cấu hình có thể như sau:

.Tùy chỉnh `WebClient` cho OAuth2 Client (trước 6.3)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> authorizationCodeAccessTokenResponseClient() {
		WebClientReactiveAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new WebClientReactiveAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.setWebClient(webClient());

		return accessTokenResponseClient;
	}

	@Bean
	public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
			ReactiveClientRegistrationRepository clientRegistrationRepository,
			ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

		WebClientReactiveRefreshTokenTokenResponseClient refreshTokenAccessTokenResponseClient =
			new WebClientReactiveRefreshTokenTokenResponseClient();
		refreshTokenAccessTokenResponseClient.setWebClient(webClient());

		WebClientReactiveClientCredentialsTokenResponseClient clientCredentialsAccessTokenResponseClient =
			new WebClientReactiveClientCredentialsTokenResponseClient();
		clientCredentialsAccessTokenResponseClient.setWebClient(webClient());

		WebClientReactiveJwtBearerTokenResponseClient jwtBearerAccessTokenResponseClient =
			new WebClientReactiveJwtBearerTokenResponseClient();
		jwtBearerAccessTokenResponseClient.setWebClient(webClient());

		JwtBearerReactiveOAuth2AuthorizedClientProvider jwtBearerAuthorizedClientProvider =
			new JwtBearerReactiveOAuth2AuthorizedClientProvider();
		jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerAccessTokenResponseClient);

		WebClientReactiveTokenExchangeTokenResponseClient tokenExchangeAccessTokenResponseClient =
			new WebClientReactiveTokenExchangeTokenResponseClient();
		tokenExchangeAccessTokenResponseClient.setWebClient(webClient());

		TokenExchangeReactiveOAuth2AuthorizedClientProvider tokenExchangeAuthorizedClientProvider =
			new TokenExchangeReactiveOAuth2AuthorizedClientProvider();
		tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeAccessTokenResponseClient);

		ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken((refreshToken) -> refreshToken
					.accessTokenResponseClient(refreshTokenAccessTokenResponseClient)
				)
				.clientCredentials((clientCredentials) -> clientCredentials
					.accessTokenResponseClient(clientCredentialsAccessTokenResponseClient)
				)
				.provider(jwtBearerAuthorizedClientProvider)
				.provider(tokenExchangeAuthorizedClientProvider)
				.build();

		DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
				clientRegistrationRepository, authorizedClientRepository);
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

		return authorizedClientManager;
	}

	@Bean
	public WebClient webClient() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
class SecurityConfig {

	@Bean
	fun authorizationCodeAccessTokenResponseClient(): ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> {
		val accessTokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
		accessTokenResponseClient.setWebClient(webClient())

		return accessTokenResponseClient
	}

	@Bean
	fun authorizedClientManager(
		clientRegistrationRepository: ReactiveClientRegistrationRepository?,
		authorizedClientRepository: ServerOAuth2AuthorizedClientRepository?
	): ReactiveOAuth2AuthorizedClientManager {
		val refreshTokenAccessTokenResponseClient = WebClientReactiveRefreshTokenTokenResponseClient()
		refreshTokenAccessTokenResponseClient.setWebClient(webClient())

		val clientCredentialsAccessTokenResponseClient = WebClientReactiveClientCredentialsTokenResponseClient()
		clientCredentialsAccessTokenResponseClient.setWebClient(webClient())

		val jwtBearerAccessTokenResponseClient = WebClientReactiveJwtBearerTokenResponseClient()
		jwtBearerAccessTokenResponseClient.setWebClient(webClient())

		val jwtBearerAuthorizedClientProvider = JwtBearerReactiveOAuth2AuthorizedClientProvider()
		jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerAccessTokenResponseClient)

		val tokenExchangeAccessTokenResponseClient = WebClientReactiveTokenExchangeTokenResponseClient()
		tokenExchangeAccessTokenResponseClient.setWebClient(webClient())

		val tokenExchangeAuthorizedClientProvider = TokenExchangeReactiveOAuth2AuthorizedClientProvider()
		tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeAccessTokenResponseClient)

		val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
			.authorizationCode()
			.refreshToken { refreshToken ->
				refreshToken.accessTokenResponseClient(refreshTokenAccessTokenResponseClient)
			}
			.clientCredentials { clientCredentials ->
				clientCredentials.accessTokenResponseClient(clientCredentialsAccessTokenResponseClient)
			}
			.provider(jwtBearerAuthorizedClientProvider)
			.provider(tokenExchangeAuthorizedClientProvider)
			.build()

		val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
			clientRegistrationRepository, authorizedClientRepository
		)
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

		return authorizedClientManager
	}

	@Bean
	fun webClient(): WebClient {
		// ...
	}

}
----
=====


[[further-reading]]
== Đọc thêm

Các phần trước đã giới thiệu hỗ trợ OAuth2 của Spring Security cùng những ví dụ cho các kịch bản phổ biến.
Bạn có thể đọc thêm về OAuth2 Client và Resource Server trong các phần sau của tài liệu tham khảo:

* xref:reactive/oauth2/login/index.adoc[]
* xref:reactive/oauth2/client/index.adoc[]
* xref:reactive/oauth2/resource-server/index.adoc[]
