[[oauth2-client-authorization-grants]]
= [[oauth2Client-auth-grant-support]]Hỗ trợ Authorization Grant

Phần này mô tả khả năng hỗ trợ authorization grant của Spring Security.

[[oauth2-client-authorization-code]]
== [[oauth2Client-auth-code-grant]]Authorization Code

[NOTE]
====
Tham khảo OAuth 2.0 Authorization Framework để biết thêm chi tiết về https://tools.ietf.org/html/rfc6749#section-1.3.1[Authorization Code] grant.
====

[[oauth2-client-authorization-code-authorization]]
=== Nhận authorization

[NOTE]
====
Tham khảo protocol flow https://tools.ietf.org/html/rfc6749#section-4.1.1[Authorization Request/Response] cho grant Authorization Code.
====

[[oauth2-client-authorization-code-authorization-request]]
=== Bắt đầu Authorization Request

`OAuth2AuthorizationRequestRedirectWebFilter` sử dụng `ServerOAuth2AuthorizationRequestResolver` để resolve một `OAuth2AuthorizationRequest` và bắt đầu flow của Authorization Code grant bằng cách redirect user-agent của end-user đến Authorization Endpoint của Authorization Server.

Vai trò chính của `ServerOAuth2AuthorizationRequestResolver` là resolve một `OAuth2AuthorizationRequest` từ web request được cung cấp.
Implementation mặc định `DefaultServerOAuth2AuthorizationRequestResolver` khớp với path (mặc định) `+/oauth2/authorization/{registrationId}+`, trích xuất `registrationId` và dùng nó để xây dựng `OAuth2AuthorizationRequest` cho `ClientRegistration` tương ứng.

Với các property Spring Boot sau đây cho một đăng ký OAuth 2.0 Client:

[source,yaml,attrs="-attributes"]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/okta"
            scope: read, write
        provider:
          okta:
            authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

Request có base path `/oauth2/authorization/okta` sẽ bắt đầu redirect Authorization Request bởi `OAuth2AuthorizationRequestRedirectWebFilter` và cuối cùng khởi động flow của Authorization Code grant.

[NOTE]
====
`AuthorizationCodeReactiveOAuth2AuthorizedClientProvider` là một implementation của `ReactiveOAuth2AuthorizedClientProvider` cho grant Authorization Code,
đồng thời cũng bắt đầu redirect Authorization Request bởi `OAuth2AuthorizationRequestRedirectWebFilter`.
====

Nếu OAuth 2.0 Client là https://tools.ietf.org/html/rfc6749#section-2.1[Public Client], hãy cấu hình đăng ký OAuth 2.0 Client như sau:

[source,yaml,attrs="-attributes"]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/okta"
            # ...
----

Public Client được hỗ trợ thông qua https://tools.ietf.org/html/rfc7636[Proof Key for Code Exchange] (PKCE).
Nếu client chạy trong môi trường không đáng tin cậy (ví dụ ứng dụng native hoặc ứng dụng dựa trên web browser) và do đó không thể duy trì tính bí mật của các credential, PKCE sẽ tự động được sử dụng khi các điều kiện sau được thỏa mãn:

. `client-secret` bị bỏ qua (hoặc rỗng)
. `client-authentication-method` được đặt thành `none` (`ClientAuthenticationMethod.NONE`)

hoặc

. Khi `ClientRegistration.clientSettings.requireProofKey` là `true` (trong trường hợp này `ClientRegistration.authorizationGrantType` phải là `authorization_code`)

[TIP]
====
Nếu OAuth 2.0 Provider không hỗ trợ PKCE cho https://tools.ietf.org/html/rfc6749#section-2.1[Confidential Clients], bạn cần tắt tính năng này bằng cách đặt `ClientRegistration.clientSettings.requireProofKey` thành `false`.
====

[[oauth2-client-authorization-code-redirect-uri]]
[[oauth2Client-auth-code-redirect-uri]]`DefaultServerOAuth2AuthorizationRequestResolver` cũng hỗ trợ biến template `URI` cho `redirect-uri` bằng `UriComponentsBuilder`.

Cấu hình sau sử dụng tất cả biến template `URI` được hỗ trợ:

[source,yaml,attrs="-attributes"]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            # ...
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/authorized/{registrationId}"
            # ...
----

[NOTE]
====
`+{baseUrl}+` được resolve thành `+{baseScheme}://{baseHost}{basePort}{basePath}+`
====

Cấu hình `redirect-uri` bằng các biến template `URI` đặc biệt hữu ích khi OAuth 2.0 Client chạy phía sau xref:features/exploits/http.adoc#http-proxy-server[Proxy Server].
Điều này bảo đảm các header `X-Forwarded-*` được sử dụng khi mở rộng `redirect-uri`.

[[oauth2-client-authorization-code-authorization-request-resolver]]
=== Tùy chỉnh Authorization Request

Một trong những use case chính của `ServerOAuth2AuthorizationRequestResolver` là tùy chỉnh Authorization Request với các parameter bổ sung ngoài những parameter tiêu chuẩn được định nghĩa trong OAuth 2.0 Authorization Framework.

Ví dụ, OpenID Connect định nghĩa các request parameter OAuth 2.0 bổ sung cho https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest[Authorization Code Flow] bằng cách mở rộng các parameter tiêu chuẩn được định nghĩa trong https://tools.ietf.org/html/rfc6749#section-4.1.1[OAuth 2.0 Authorization Framework].
Một trong các parameter mở rộng đó là parameter `prompt`.

[NOTE]
====
Parameter `prompt` là tùy chọn. Giá trị của parameter này là danh sách các chuỗi ASCII được phân tách bằng dấu cách và phân biệt chữ hoa chữ thường, chỉ định liệu Authorization Server có yêu cầu End-User re-authentication và consent hay không. Các giá trị được định nghĩa là: `none`, `login`, `consent` và `select_account`.
====

Cấu hình mẫu sau cho biết cách cấu hình `DefaultServerOAuth2AuthorizationRequestResolver` với một `Consumer<OAuth2AuthorizationRequest.Builder>` để tùy chỉnh Authorization Request cho `oauth2Login()`, bằng cách thêm request parameter `prompt=consent`.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Autowired
	private ReactiveClientRegistrationRepository clientRegistrationRepository;

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login((oauth2) -> oauth2
				.authorizationRequestResolver(
					authorizationRequestResolver(this.clientRegistrationRepository)
				)
			);
		return http.build();
	}

	private ServerOAuth2AuthorizationRequestResolver authorizationRequestResolver(
			ReactiveClientRegistrationRepository clientRegistrationRepository) {

		DefaultServerOAuth2AuthorizationRequestResolver authorizationRequestResolver =
				new DefaultServerOAuth2AuthorizationRequestResolver(
						clientRegistrationRepository);
		authorizationRequestResolver.setAuthorizationRequestCustomizer(
				authorizationRequestCustomizer());

		return  authorizationRequestResolver;
	}

	private Consumer<OAuth2AuthorizationRequest.Builder> authorizationRequestCustomizer() {
		return customizer -> customizer
					.additionalParameters((params) -> params.put("prompt", "consent"));
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class SecurityConfig {

    @Autowired
    private lateinit var customClientRegistrationRepository: ReactiveClientRegistrationRepository

    @Bean
    fun securityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login {
                authorizationRequestResolver = authorizationRequestResolver(customClientRegistrationRepository)
            }
        }

        return http.build()
    }

    private fun authorizationRequestResolver(
            clientRegistrationRepository: ReactiveClientRegistrationRepository): ServerOAuth2AuthorizationRequestResolver {
        val authorizationRequestResolver = DefaultServerOAuth2AuthorizationRequestResolver(
                clientRegistrationRepository)
        authorizationRequestResolver.setAuthorizationRequestCustomizer(
                authorizationRequestCustomizer())
        return authorizationRequestResolver
    }

    private fun authorizationRequestCustomizer(): Consumer<OAuth2AuthorizationRequest.Builder> {
        return Consumer { customizer ->
            customizer
                .additionalParameters { params -> params["prompt"] = "consent" }
        }
    }
}
----
======

Với use case đơn giản, khi request parameter bổ sung luôn giống nhau đối với một provider cụ thể, có thể thêm parameter đó trực tiếp vào property `authorization-uri`.

Ví dụ, nếu giá trị của request parameter `prompt` luôn là `consent` đối với provider `okta`, chỉ cần cấu hình như sau:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize?prompt=consent
----

Ví dụ trước cho thấy use case phổ biến là thêm một parameter tùy chỉnh bên cạnh các parameter tiêu chuẩn.
Ngoài ra, nếu yêu cầu của bạn nâng cao hơn, bạn có thể toàn quyền xây dựng Authorization Request URI bằng cách override property `OAuth2AuthorizationRequest.authorizationRequestUri`.

[TIP]
====
`OAuth2AuthorizationRequest.Builder.build()` xây dựng `OAuth2AuthorizationRequest.authorizationRequestUri`, đại diện cho Authorization Request URI bao gồm tất cả query parameter bằng format `application/x-www-form-urlencoded`.
====

Cấu hình mẫu sau là một biến thể của `authorizationRequestCustomizer()` trong ví dụ trước và thay vào đó override property `OAuth2AuthorizationRequest.authorizationRequestUri`.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
private Consumer<OAuth2AuthorizationRequest.Builder> authorizationRequestCustomizer() {
	return customizer -> customizer
			.authorizationRequestUri((uriBuilder) -> uriBuilder
					.queryParam("prompt", "consent").build());
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
private fun authorizationRequestCustomizer(): Consumer<OAuth2AuthorizationRequest.Builder> {
    return Consumer { customizer: OAuth2AuthorizationRequest.Builder ->
        customizer
                .authorizationRequestUri { uriBuilder: UriBuilder ->
                    uriBuilder
                            .queryParam("prompt", "consent").build()
                }
    }
}
----
======

[[oauth2-client-authorization-code-authorization-request-repository]]
=== Lưu Authorization Request

`ServerAuthorizationRequestRepository` chịu trách nhiệm persistence của `OAuth2AuthorizationRequest` từ khi Authorization Request được bắt đầu cho đến khi nhận được Authorization Response (callback).

[TIP]
====
`OAuth2AuthorizationRequest` được dùng để correlate và validate Authorization Response.
====

Implementation mặc định của `ServerAuthorizationRequestRepository` là `WebSessionOAuth2ServerAuthorizationRequestRepository`, lưu `OAuth2AuthorizationRequest` trong `WebSession`.

Nếu bạn có implementation tùy chỉnh của `ServerAuthorizationRequestRepository`, bạn có thể cấu hình như trong ví dụ sau:

.Cấu hình ServerAuthorizationRequestRepository
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.oauth2Client((oauth2) -> oauth2
				.authorizationRequestRepository(this.authorizationRequestRepository())
				// ...
			);
		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    fun securityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Client {
                authorizationRequestRepository = authorizationRequestRepository()
            }
        }

        return http.build()
    }
}
----
======

[[oauth2-client-authorization-code-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Tham khảo protocol flow https://tools.ietf.org/html/rfc6749#section-4.1.3[Access Token Request/Response] cho grant Authorization Code.
====

Implementation mặc định của `ReactiveOAuth2AccessTokenResponseClient` cho grant Authorization Code là `WebClientReactiveAuthorizationCodeTokenResponseClient`, sử dụng `WebClient` để exchange authorization code lấy access token tại Token Endpoint của Authorization Server.

:section-id: authorization-code
:grant-type: Authorization Code
:class-name: WebClientReactiveAuthorizationCodeTokenResponseClient
:grant-request: OAuth2AuthorizationCodeGrantRequest
:leveloffset: +1
include::partial$reactive/oauth2/client/web-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-authorization-code-access-token-response-client-dsl]]
=== Tùy chỉnh bằng DSL

Dù bạn tùy chỉnh `{class-name}` hay cung cấp implementation riêng của `ReactiveOAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng DSL (thay cho <<oauth2-client-authorization-code-access-token-response-client-bean,cung cấp một bean>>) như trong ví dụ sau:

.Cấu hình Access Token Response bằng DSL
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.oauth2Client((oauth2) -> oauth2
				.authenticationManager(this.authorizationCodeAuthenticationManager())
				// ...
			);
		return http.build();
	}

	private ReactiveAuthenticationManager authorizationCodeAuthenticationManager() {
		WebClientReactiveAuthorizationCodeTokenResponseClient accessTokenResponseClient =
				new WebClientReactiveAuthorizationCodeTokenResponseClient();
		// ...

		return new OAuth2AuthorizationCodeReactiveAuthenticationManager(accessTokenResponseClient);
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    fun securityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Client {
                authenticationManager = authorizationCodeAuthenticationManager()
            }
        }

        return http.build()
    }

    private fun authorizationCodeAuthenticationManager(): ReactiveAuthenticationManager {
        val accessTokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
        // ...

        return OAuth2AuthorizationCodeReactiveAuthenticationManager(accessTokenResponseClient)
    }
}
----
======

[[oauth2-client-refresh-token]]
== [[oauth2Client-refresh-token-grant]]Refresh Token

[NOTE]
====
Tham khảo OAuth 2.0 Authorization Framework để biết thêm chi tiết về https://tools.ietf.org/html/rfc6749#section-1.5[Refresh Token].
====

[[oauth2-client-refresh-token-access-token]]
=== Làm mới Access Token

[NOTE]
====
Tham khảo protocol flow https://tools.ietf.org/html/rfc6749#section-6[Access Token Request/Response] cho grant Refresh Token.
====

Implementation mặc định của `ReactiveOAuth2AccessTokenResponseClient` cho grant Refresh Token là `WebClientReactiveRefreshTokenTokenResponseClient`, sử dụng `WebClient` khi refresh access token tại Token Endpoint của Authorization Server.

:section-id: refresh-token
:grant-type: Refresh Token
:class-name: WebClientReactiveRefreshTokenTokenResponseClient
:grant-request: OAuth2RefreshTokenGrantRequest
:leveloffset: +1
include::partial$reactive/oauth2/client/web-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-refresh-token-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `WebClientReactiveRefreshTokenTokenResponseClient` hay cung cấp implementation riêng của `ReactiveOAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `ReactiveOAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-refresh-token-access-token-response-client-bean,cung cấp một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Tùy chỉnh
ReactiveOAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> refreshTokenTokenResponseClient = ...

ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
		ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken((configurer) -> configurer.accessTokenResponseClient(refreshTokenTokenResponseClient))
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Tùy chỉnh
val refreshTokenTokenResponseClient: ReactiveOAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> = ...

val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
        .authorizationCode()
        .refreshToken { it.accessTokenResponseClient(refreshTokenTokenResponseClient) }
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[NOTE]
====
`ReactiveOAuth2AuthorizedClientProviderBuilder.builder().refreshToken()` cấu hình một `RefreshTokenReactiveOAuth2AuthorizedClientProvider`,
đây là một implementation của `ReactiveOAuth2AuthorizedClientProvider` cho grant Refresh Token.
====

`OAuth2RefreshToken` có thể được trả về trong Access Token Response cho grant type `authorization_code`.
Nếu `OAuth2AuthorizedClient.getRefreshToken()` khả dụng và `OAuth2AuthorizedClient.getAccessToken()` đã hết hạn, token này sẽ được `RefreshTokenReactiveOAuth2AuthorizedClientProvider` tự động refresh.

[[oauth2-client-client-credentials]]
== [[oauth2Client-client-creds-grant]]Client Credentials

[NOTE]
====
Tham khảo OAuth 2.0 Authorization Framework để biết thêm chi tiết về https://tools.ietf.org/html/rfc6749#section-1.3.4[Client Credentials] grant.
====

[[oauth2-client-client-credentials-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Tham khảo protocol flow https://tools.ietf.org/html/rfc6749#section-4.4.2[Access Token Request/Response] cho grant Client Credentials.
====

Implementation mặc định của `ReactiveOAuth2AccessTokenResponseClient` cho grant Client Credentials là `WebClientReactiveClientCredentialsTokenResponseClient`, sử dụng `WebClient` khi request access token tại Token Endpoint của Authorization Server.

:section-id: client-credentials
:grant-type: Client Credentials
:class-name: WebClientReactiveClientCredentialsTokenResponseClient
:grant-request: OAuth2ClientCredentialsGrantRequest
:leveloffset: +1
include::partial$reactive/oauth2/client/web-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-client-credentials-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `WebClientReactiveClientCredentialsTokenResponseClient` hay cung cấp implementation riêng của `ReactiveOAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `ReactiveOAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-client-credentials-access-token-response-client-bean,cung cấp một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Tùy chỉnh
ReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsTokenResponseClient = ...

ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
		ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.clientCredentials((configurer) -> configurer.accessTokenResponseClient(clientCredentialsTokenResponseClient))
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Tùy chỉnh
val clientCredentialsTokenResponseClient: ReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> = ...

val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
        .clientCredentials { it.accessTokenResponseClient(clientCredentialsTokenResponseClient) }
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[NOTE]
====
`ReactiveOAuth2AuthorizedClientProviderBuilder.builder().clientCredentials()` cấu hình một `ClientCredentialsReactiveOAuth2AuthorizedClientProvider`, đây là một implementation của `ReactiveOAuth2AuthorizedClientProvider` cho grant Client Credentials.
====

[[oauth2-client-client-credentials-authorized-client-manager]]
=== Sử dụng Access Token

Với các property Spring Boot sau đây cho một đăng ký OAuth 2.0 Client:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: client_credentials
            scope: read, write
        provider:
          okta:
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

...và `ReactiveOAuth2AuthorizedClientManager` `@Bean`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.clientCredentials()
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Bạn có thể lấy `OAuth2AccessToken` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ReactiveOAuth2AuthorizedClientManager authorizedClientManager;

	@GetMapping("/")
	public Mono<String> index(Authentication authentication, ServerWebExchange exchange) {
		OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
				.principal(authentication)
				.attribute(ServerWebExchange.class.getName(), exchange)
				.build();

		return this.authorizedClientManager.authorize(authorizeRequest)
				.map(OAuth2AuthorizedClient::getAccessToken)
				// ...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class OAuth2ClientController {

    @Autowired
    private lateinit var authorizedClientManager: ReactiveOAuth2AuthorizedClientManager

    @GetMapping("/")
    fun index(authentication: Authentication, exchange: ServerWebExchange): Mono<String> {
        val authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
                .principal(authentication)
                .attribute(ServerWebExchange::class.java.name, exchange)
                .build()

        return authorizedClientManager.authorize(authorizeRequest)
                .map { it.accessToken }
                // ...
                .thenReturn("index")
    }
}
----
======

[NOTE]
====
`ServerWebExchange` là một attribute OPTIONAL.
Nếu không được cung cấp, nó sẽ được lấy từ https://projectreactor.io/docs/core/release/reference/advancedFeatures/context.html[Reactor's Context] thông qua key `ServerWebExchange.class`.
====

[[oauth2-client-jwt-bearer]]
== JWT Bearer

[NOTE]
====
Tham khảo JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grants để biết thêm chi tiết về https://datatracker.ietf.org/doc/html/rfc7523[JWT Bearer] grant.
====

[[oauth2-client-jwt-bearer-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Tham khảo protocol flow https://datatracker.ietf.org/doc/html/rfc7523#section-2.1[Access Token Request/Response] cho grant JWT Bearer.
====

Implementation mặc định của `ReactiveOAuth2AccessTokenResponseClient` cho grant JWT Bearer là `WebClientReactiveJwtBearerTokenResponseClient`, sử dụng `WebClient` khi request access token tại Token Endpoint của Authorization Server.

:section-id: jwt-bearer
:grant-type: JWT Bearer
:class-name: WebClientReactiveJwtBearerTokenResponseClient
:grant-request: JwtBearerGrantRequest
:leveloffset: +1
include::partial$reactive/oauth2/client/web-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-jwt-bearer-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `WebClientReactiveJwtBearerTokenResponseClient` hay cung cấp implementation riêng của `ReactiveOAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `ReactiveOAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-jwt-bearer-access-token-response-client-bean,cung cấp một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Tùy chỉnh
ReactiveOAuth2AccessTokenResponseClient<JwtBearerGrantRequest> jwtBearerTokenResponseClient = ...

JwtBearerReactiveOAuth2AuthorizedClientProvider jwtBearerAuthorizedClientProvider = new JwtBearerReactiveOAuth2AuthorizedClientProvider();
jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerTokenResponseClient);

ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
		ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.provider(jwtBearerAuthorizedClientProvider)
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Tùy chỉnh
val jwtBearerTokenResponseClient: ReactiveOAuth2AccessTokenResponseClient<JwtBearerGrantRequest> = ...

val jwtBearerAuthorizedClientProvider = JwtBearerReactiveOAuth2AuthorizedClientProvider()
jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerTokenResponseClient)

val authorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
        .provider(jwtBearerAuthorizedClientProvider)
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[[oauth2-client-jwt-bearer-authorized-client-manager]]
=== Sử dụng Access Token

Với các property Spring Boot sau đây cho một đăng ký OAuth 2.0 Client:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: read
        provider:
          okta:
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

...và `@Bean` `OAuth2AuthorizedClientManager`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	JwtBearerReactiveOAuth2AuthorizedClientProvider jwtBearerAuthorizedClientProvider =
			new JwtBearerReactiveOAuth2AuthorizedClientProvider();

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.provider(jwtBearerAuthorizedClientProvider)
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val jwtBearerAuthorizedClientProvider = JwtBearerReactiveOAuth2AuthorizedClientProvider()
    val authorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .provider(jwtBearerAuthorizedClientProvider)
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Bạn có thể lấy `OAuth2AccessToken` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RestController
public class OAuth2ResourceServerController {

	@Autowired
	private ReactiveOAuth2AuthorizedClientManager authorizedClientManager;

	@GetMapping("/resource")
	public Mono<String> resource(JwtAuthenticationToken jwtAuthentication, ServerWebExchange exchange) {
		OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
				.principal(jwtAuthentication)
				.build();

		return this.authorizedClientManager.authorize(authorizeRequest)
				.map(OAuth2AuthorizedClient::getAccessToken)
				// ...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class OAuth2ResourceServerController {

    @Autowired
    private lateinit var authorizedClientManager: ReactiveOAuth2AuthorizedClientManager

    @GetMapping("/resource")
    fun resource(jwtAuthentication: JwtAuthenticationToken, exchange: ServerWebExchange): Mono<String> {
        val authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
                .principal(jwtAuthentication)
                .build()
        return authorizedClientManager.authorize(authorizeRequest)
                .map { it.accessToken }
                // ...
                .thenReturn("index")
    }
}
----
======

[NOTE]
====
`JwtBearerReactiveOAuth2AuthorizedClientProvider` mặc định resolve assertion `Jwt` thông qua `OAuth2AuthorizationContext.getPrincipal().getPrincipal()`, do đó ví dụ trước sử dụng `JwtAuthenticationToken`.
====

[TIP]
====
Nếu cần resolve assertion `Jwt` từ một nguồn khác, bạn có thể cung cấp cho `JwtBearerReactiveOAuth2AuthorizedClientProvider.setJwtAssertionResolver()` một `Function<OAuth2AuthorizationContext, Mono<Jwt>>` tùy chỉnh.
====

[[oauth2-client-token-exchange]]
== [[oauth2Client-token-exchange-grant]]Token Exchange

[NOTE]
====
Tham khảo OAuth 2.0 Token Exchange để biết thêm chi tiết về https://datatracker.ietf.org/doc/html/rfc8693[Token Exchange] grant.
====

[[oauth2-client-token-exchange-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Tham khảo protocol flow https://datatracker.ietf.org/doc/html/rfc8693#section-2[Token Exchange Request and Response] cho grant Token Exchange.
====

Implementation mặc định của `ReactiveOAuth2AccessTokenResponseClient` cho grant Token Exchange là `WebClientReactiveTokenExchangeTokenResponseClient`, sử dụng `WebClient` khi request access token tại Token Endpoint của Authorization Server.

:section-id: token-exchange
:grant-type: Token Exchange
:class-name: WebClientReactiveTokenExchangeTokenResponseClient
:grant-request: TokenExchangeGrantRequest
:leveloffset: +1
include::partial$reactive/oauth2/client/web-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-token-exchange-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `WebClientReactiveTokenExchangeTokenResponseClient` hay cung cấp implementation riêng của `ReactiveOAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `ReactiveOAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-token-exchange-access-token-response-client-bean,cung cấp một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Tùy chỉnh
ReactiveOAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> tokenExchangeTokenResponseClient = ...

TokenExchangeReactiveOAuth2AuthorizedClientProvider tokenExchangeAuthorizedClientProvider = new TokenExchangeReactiveOAuth2AuthorizedClientProvider();
tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeTokenResponseClient);

ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
		ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.provider(tokenExchangeAuthorizedClientProvider)
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Tùy chỉnh
val tokenExchangeTokenResponseClient: ReactiveOAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> = ...

val tokenExchangeAuthorizedClientProvider = TokenExchangeReactiveOAuth2AuthorizedClientProvider()
tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeTokenResponseClient)

val authorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
        .provider(tokenExchangeAuthorizedClientProvider)
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[[oauth2-client-token-exchange-authorized-client-manager]]
=== Sử dụng Access Token

Với các property Spring Boot sau đây cho một đăng ký OAuth 2.0 Client:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            scope: read
        provider:
          okta:
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

...và `@Bean` `OAuth2AuthorizedClientManager`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	TokenExchangeReactiveOAuth2AuthorizedClientProvider tokenExchangeAuthorizedClientProvider =
			new TokenExchangeReactiveOAuth2AuthorizedClientProvider();

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.provider(tokenExchangeAuthorizedClientProvider)
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val tokenExchangeAuthorizedClientProvider = TokenExchangeReactiveOAuth2AuthorizedClientProvider()
    val authorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .provider(tokenExchangeAuthorizedClientProvider)
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Bạn có thể lấy `OAuth2AccessToken` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RestController
public class OAuth2ResourceServerController {

	@Autowired
	private ReactiveOAuth2AuthorizedClientManager authorizedClientManager;

	@GetMapping("/resource")
	public Mono<String> resource(JwtAuthenticationToken jwtAuthentication) {
		OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
				.principal(jwtAuthentication)
				.build();

		return this.authorizedClientManager.authorize(authorizeRequest)
				.map(OAuth2AuthorizedClient::getAccessToken)
				// ...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class OAuth2ResourceServerController {

    @Autowired
    private lateinit var authorizedClientManager: ReactiveOAuth2AuthorizedClientManager

    @GetMapping("/resource")
    fun resource(jwtAuthentication: JwtAuthenticationToken): Mono<String> {
        val authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
                .principal(jwtAuthentication)
                .build()
        return authorizedClientManager.authorize(authorizeRequest)
                .map { it.accessToken }
                // ...
                .thenReturn("index")
    }
}
----
======

[NOTE]
====
`TokenExchangeReactiveOAuth2AuthorizedClientProvider` mặc định resolve subject token (dưới dạng một `OAuth2Token`) thông qua `OAuth2AuthorizationContext.getPrincipal().getPrincipal()`, do đó ví dụ trước sử dụng `JwtAuthenticationToken`.
Actor token không được resolve theo mặc định.
====

[TIP]
====
Nếu cần resolve subject token từ một nguồn khác, bạn có thể cung cấp cho `TokenExchangeReactiveOAuth2AuthorizedClientProvider.setSubjectTokenResolver()` một `Function<OAuth2AuthorizationContext, Mono<OAuth2Token>>` tùy chỉnh.
====

[TIP]
====
Nếu cần resolve actor token, bạn có thể cung cấp cho `TokenExchangeReactiveOAuth2AuthorizedClientProvider.setActorTokenResolver()` một `Function<OAuth2AuthorizationContext, Mono<OAuth2Token>>` tùy chỉnh.
====
