[[oauth2-client-additional-features]]
= [[oauth2Client-additional-features]]Tính năng Authorized Client

Phần này trình bày các tính năng bổ sung do Spring Security cung cấp cho OAuth2 Client.

[[oauth2-client-registered-authorized-client]]
== [[oauth2Client-registered-authorized-client]]Phân giải một Authorized Client

Annotation `@RegisteredOAuth2AuthorizedClient` cung cấp khả năng phân giải một tham số method thành một giá trị đối số có kiểu `OAuth2AuthorizedClient`.
Đây là một giải pháp thay thế thuận tiện cho việc truy cập `OAuth2AuthorizedClient` bằng `ReactiveOAuth2AuthorizedClientManager` hoặc `ReactiveOAuth2AuthorizedClientService`.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@GetMapping("/")
	public Mono<String> index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
		return Mono.just(authorizedClient.getAccessToken())
				...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {
    @GetMapping("/")
    fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): Mono<String> {
        return Mono.just(authorizedClient.accessToken)
                ...
                .thenReturn("index")
    }
}
----
======

Annotation `@RegisteredOAuth2AuthorizedClient` được xử lý bởi `OAuth2AuthorizedClientArgumentResolver`, thành phần trực tiếp sử dụng xref:reactive/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[ReactiveOAuth2AuthorizedClientManager] và do đó kế thừa các khả năng của nó.

[[oauth2-client-web-client]]
== [[oauth2Client-webclient-webflux]]Tích hợp WebClient cho các môi trường Reactive

Tính năng hỗ trợ OAuth 2.0 Client tích hợp với `WebClient` bằng `ExchangeFilterFunction`.

`ServerOAuth2AuthorizedClientExchangeFilterFunction` cung cấp một cơ chế đơn giản để yêu cầu các resource được bảo vệ bằng cách sử dụng `OAuth2AuthorizedClient` và đưa `OAuth2AccessToken` liên kết vào dưới dạng Bearer Token.
Nó trực tiếp sử dụng xref:reactive/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[ReactiveOAuth2AuthorizedClientManager] và do đó kế thừa các khả năng sau:

* Một `OAuth2AccessToken` sẽ được yêu cầu nếu client chưa được authorization.
** `authorization_code` - kích hoạt redirect của Authorization Request để bắt đầu flow
** `client_credentials` - access token được lấy trực tiếp từ Token Endpoint
* Nếu `OAuth2AccessToken` đã hết hạn, nó sẽ được refresh (hoặc renew) nếu có `ReactiveOAuth2AuthorizedClientProvider` để thực hiện authorization

Đoạn code sau minh họa cách cấu hình `WebClient` với tính năng hỗ trợ OAuth 2.0 Client:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	return WebClient.builder()
			.filter(oauth2Client)
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
    val oauth2Client = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    return WebClient.builder()
            .filter(oauth2Client)
            .build()
}
----
======

[[oauth2-client-web-client-authorized-client]]
=== Cung cấp Authorized Client

`ServerOAuth2AuthorizedClientExchangeFilterFunction` xác định client cần sử dụng (cho một request) bằng cách phân giải `OAuth2AuthorizedClient` từ `ClientRequest.attributes()` (request attributes).

Đoạn code sau minh họa cách đặt một `OAuth2AuthorizedClient` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public Mono<String> index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
	String resourceUri = ...

	return webClient
			.get()
			.uri(resourceUri)
			.attributes(oauth2AuthorizedClient(authorizedClient))   <1>
			.retrieve()
			.bodyToMono(String.class)
			...
			.thenReturn("index");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): Mono<String> {
    val resourceUri: String = ...

    return webClient
            .get()
            .uri(resourceUri)
            .attributes(oauth2AuthorizedClient(authorizedClient)) <1>
            .retrieve()
            .bodyToMono<String>()
            ...
            .thenReturn("index")
}
----
======

<1> `oauth2AuthorizedClient()` là một method `static` trong `ServerOAuth2AuthorizedClientExchangeFilterFunction`.

Đoạn code sau minh họa cách đặt `ClientRegistration.getRegistrationId()` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public Mono<String> index() {
	String resourceUri = ...

	return webClient
			.get()
			.uri(resourceUri)
			.attributes(clientRegistrationId("okta"))   <1>
			.retrieve()
			.bodyToMono(String.class)
			...
			.thenReturn("index");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(): Mono<String> {
    val resourceUri: String = ...

    return webClient
            .get()
            .uri(resourceUri)
            .attributes(clientRegistrationId("okta"))  <1>
            .retrieve()
            .bodyToMono<String>()
            ...
            .thenReturn("index")
}
----
======
<1> `clientRegistrationId()` là một method `static` trong `ServerOAuth2AuthorizedClientExchangeFilterFunction`.

[[oauth2-client-web-client-default-authorized-client]]
=== Đặt Authorized Client mặc định

Nếu cả `OAuth2AuthorizedClient` lẫn `ClientRegistration.getRegistrationId()` đều không được cung cấp dưới dạng request attribute, `ServerOAuth2AuthorizedClientExchangeFilterFunction` có thể xác định client _mặc định_ cần sử dụng tùy theo cấu hình của nó.

Nếu cấu hình `setDefaultOAuth2AuthorizedClient(true)` và user đã authentication bằng `ServerHttpSecurity.oauth2Login()`, `OAuth2AccessToken` liên kết với `OAuth2AuthenticationToken` hiện tại sẽ được sử dụng.

Đoạn code sau minh họa cấu hình cụ thể:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultOAuth2AuthorizedClient(true);
	return WebClient.builder()
			.filter(oauth2Client)
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
    val oauth2Client = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultOAuth2AuthorizedClient(true)
    return WebClient.builder()
            .filter(oauth2Client)
            .build()
}
----
======

[WARNING]
====
Bạn nên thận trọng khi sử dụng tính năng này vì tất cả HTTP request sẽ nhận access token.
====

Ngoài ra, nếu `setDefaultClientRegistrationId("okta")` được cấu hình với một `ClientRegistration` hợp lệ, `OAuth2AccessToken` liên kết với `OAuth2AuthorizedClient` sẽ được sử dụng.

Đoạn code sau minh họa cấu hình cụ thể:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultClientRegistrationId("okta");
	return WebClient.builder()
			.filter(oauth2Client)
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
    val oauth2Client = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultClientRegistrationId("okta")
    return WebClient.builder()
            .filter(oauth2Client)
            .build()
}
----
======

[WARNING]
====
Bạn nên thận trọng khi sử dụng tính năng này vì tất cả HTTP request sẽ nhận access token.
====
