[[oauth2-client-additional-features]]
= [[oauth2Client-additional-features]]Các tính năng của Authorized Client

Phần này trình bày các tính năng bổ sung mà Spring Security cung cấp cho OAuth2 Client.

[[oauth2-client-registered-authorized-client]]
== [[oauth2Client-registered-authorized-client]]Resolve một Authorized Client

Annotation `@RegisteredOAuth2AuthorizedClient` cung cấp khả năng resolve một method parameter thành một argument value có kiểu `OAuth2AuthorizedClient`.
Đây là một alternative thuận tiện cho việc access `OAuth2AuthorizedClient` bằng `ReactiveOAuth2AuthorizedClientManager` hoặc `ReactiveOAuth2AuthorizedClientService`.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@GetMapping("/")
	public Mono<String> index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
		return Mono.just(authorizedClient.getAccessToken())
				...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {
    @GetMapping("/")
    fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): Mono<String> {
        return Mono.just(authorizedClient.accessToken)
                ...
                .thenReturn("index")
    }
}
----
======

Annotation `@RegisteredOAuth2AuthorizedClient` được xử lý bởi `OAuth2AuthorizedClientArgumentResolver`, component trực tiếp sử dụng xref:reactive/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[ReactiveOAuth2AuthorizedClientManager] và do đó kế thừa các capability của nó.

[[oauth2-client-web-client]]
== [[oauth2Client-webclient-webflux]]WebClient integration cho môi trường Reactive

OAuth 2.0 Client support tích hợp với `WebClient` bằng `ExchangeFilterFunction`.

`ServerOAuth2AuthorizedClientExchangeFilterFunction` cung cấp một mechanism đơn giản để request các protected resource bằng cách sử dụng `OAuth2AuthorizedClient` và include `OAuth2AccessToken` liên kết dưới dạng Bearer Token.
Nó trực tiếp sử dụng xref:reactive/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[ReactiveOAuth2AuthorizedClientManager] và do đó kế thừa các capability sau:

* Một `OAuth2AccessToken` sẽ được request nếu client chưa được authorize.
** `authorization_code` - kích hoạt redirect của Authorization Request để initiate flow
** `client_credentials` - access token được lấy trực tiếp từ Token Endpoint
* Nếu `OAuth2AccessToken` đã expired, nó sẽ được refresh (hoặc renew) nếu có `ReactiveOAuth2AuthorizedClientProvider` để thực hiện authorization

Code sau minh họa cách configure `WebClient` với OAuth 2.0 Client support:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	return WebClient.builder()
			.filter(oauth2Client)
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
    val oauth2Client = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    return WebClient.builder()
            .filter(oauth2Client)
            .build()
}
----
======

[[oauth2-client-web-client-authorized-client]]
=== Cung cấp Authorized Client

`ServerOAuth2AuthorizedClientExchangeFilterFunction` xác định client cần sử dụng (cho một request) bằng cách resolve `OAuth2AuthorizedClient` từ `ClientRequest.attributes()` (request attributes).

Code sau minh họa cách set một `OAuth2AuthorizedClient` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public Mono<String> index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
	String resourceUri = ...

	return webClient
			.get()
			.uri(resourceUri)
			.attributes(oauth2AuthorizedClient(authorizedClient))   <1>
			.retrieve()
			.bodyToMono(String.class)
			...
			.thenReturn("index");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): Mono<String> {
    val resourceUri: String = ...

    return webClient
            .get()
            .uri(resourceUri)
            .attributes(oauth2AuthorizedClient(authorizedClient)) <1>
            .retrieve()
            .bodyToMono<String>()
            ...
            .thenReturn("index")
}
----
======

<1> `oauth2AuthorizedClient()` là một `static` method trong `ServerOAuth2AuthorizedClientExchangeFilterFunction`.

Code sau minh họa cách set `ClientRegistration.getRegistrationId()` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public Mono<String> index() {
	String resourceUri = ...

	return webClient
			.get()
			.uri(resourceUri)
			.attributes(clientRegistrationId("okta"))   <1>
			.retrieve()
			.bodyToMono(String.class)
			...
			.thenReturn("index");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(): Mono<String> {
    val resourceUri: String = ...

    return webClient
            .get()
            .uri(resourceUri)
            .attributes(clientRegistrationId("okta"))  <1>
            .retrieve()
            .bodyToMono<String>()
            ...
            .thenReturn("index")
}
----
======
<1> `clientRegistrationId()` là một `static` method trong `ServerOAuth2AuthorizedClientExchangeFilterFunction`.

[[oauth2-client-web-client-default-authorized-client]]
=== Thiết lập Authorized Client mặc định

Nếu cả `OAuth2AuthorizedClient` và `ClientRegistration.getRegistrationId()` đều không được cung cấp dưới dạng request attribute, `ServerOAuth2AuthorizedClientExchangeFilterFunction` có thể xác định client _default_ cần sử dụng tùy theo configuration của nó.

Nếu `setDefaultOAuth2AuthorizedClient(true)` được configure và user đã authenticated bằng `ServerHttpSecurity.oauth2Login()`, `OAuth2AccessToken` liên kết với `OAuth2AuthenticationToken` hiện tại sẽ được sử dụng.

Code sau minh họa configuration cụ thể:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultOAuth2AuthorizedClient(true);
	return WebClient.builder()
			.filter(oauth2Client)
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
    val oauth2Client = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultOAuth2AuthorizedClient(true)
    return WebClient.builder()
            .filter(oauth2Client)
            .build()
}
----
======

[WARNING]
====
Bạn nên thận trọng với feature này vì mọi HTTP request đều sẽ nhận access token.
====

Ngoài ra, nếu `setDefaultClientRegistrationId("okta")` được configure với một `ClientRegistration` hợp lệ, `OAuth2AccessToken` liên kết với `OAuth2AuthorizedClient` sẽ được sử dụng.

Code sau minh họa configuration cụ thể:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(ReactiveOAuth2AuthorizedClientManager authorizedClientManager) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultClientRegistrationId("okta");
	return WebClient.builder()
			.filter(oauth2Client)
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: ReactiveOAuth2AuthorizedClientManager): WebClient {
    val oauth2Client = ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultClientRegistrationId("okta")
    return WebClient.builder()
            .filter(oauth2Client)
            .build()
}
----
======

[WARNING]
====
Bạn nên thận trọng với feature này vì mọi HTTP request đều sẽ nhận access token.
====
