[[oauth2-client-authentication]]
= [[oauth2Client-client-auth-support]]Hỗ trợ Client Authentication

[[oauth2-client-authentication-client-credentials]]
== [[oauth2Client-client-credentials-auth]]Client Credentials

[[oauth2-client-authentication-client-credentials-client-secret-basic]]
=== Xác thực bằng `client_secret_basic`

Client Authentication với HTTP Basic được hỗ trợ sẵn và không cần tùy chỉnh để bật tính năng này.
Implementation mặc định được cung cấp bởi `DefaultOAuth2TokenRequestHeadersConverter`.

Với các property Spring Boot sau đây dành cho một đăng ký client OAuth 2.0:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: client-id
            client-secret: client-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            ...
----

Ví dụ sau cho thấy cách cấu hình `WebClientReactiveAuthorizationCodeTokenResponseClient` để tắt URL encoding của client credentials:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
DefaultOAuth2TokenRequestHeadersConverter<OAuth2AuthorizationCodeGrantRequest> headersConverter =
		new DefaultOAuth2TokenRequestHeadersConverter<>();
headersConverter.setEncodeClientCredentials(false);

WebClientReactiveAuthorizationCodeTokenResponseClient tokenResponseClient =
		new WebClientReactiveAuthorizationCodeTokenResponseClient();
tokenResponseClient.setHeadersConverter(headersConverter);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val headersConverter = DefaultOAuth2TokenRequestHeadersConverter<OAuth2AuthorizationCodeGrantRequest>()
headersConverter.setEncodeClientCredentials(false)

val tokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
tokenResponseClient.setHeadersConverter(headersConverter)
----
======

[[oauth2-client-authentication-client-credentials-client-secret-post]]
=== Xác thực bằng `client_secret_post`

Client Authentication trong đó client credentials được đưa vào request body được hỗ trợ sẵn và không cần tùy chỉnh để bật tính năng này.

Các property Spring Boot sau đây dành cho một đăng ký client OAuth 2.0 minh họa cấu hình này:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: client-id
            client-secret: client-secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            ...
----

[[oauth2-client-authentication-jwt-bearer]]
== [[oauth2Client-jwt-bearer-auth]]JWT Bearer

[NOTE]
====
Tham khảo JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grants để biết thêm chi tiết về https://datatracker.ietf.org/doc/html/rfc7523#section-2.2[JWT Bearer] Client Authentication.
====

Implementation mặc định cho JWT Bearer Client Authentication là `NimbusJwtClientAuthenticationParametersConverter`,
đây là một `Converter` dùng để tùy chỉnh các tham số của Token Request bằng cách thêm
một JSON Web Token (JWS) đã ký vào tham số `client_assertion`.

`java.security.PrivateKey` hoặc `javax.crypto.SecretKey` được dùng để ký JWS do resolver
`com.nimbusds.jose.jwk.JWK` liên kết với `NimbusJwtClientAuthenticationParametersConverter` cung cấp.

[[oauth2-client-authentication-jwt-bearer-private-key-jwt]]
=== Xác thực bằng `private_key_jwt`

Với các property Spring Boot sau đây dành cho một đăng ký client OAuth 2.0:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            ...
----

Ví dụ sau cho thấy cách cấu hình `WebClientReactiveAuthorizationCodeTokenResponseClient`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
Function<ClientRegistration, JWK> jwkResolver = (clientRegistration) -> {
	if (clientRegistration.getClientAuthenticationMethod().equals(ClientAuthenticationMethod.PRIVATE_KEY_JWT)) {
		// Giả sử loại key là RSA
		RSAPublicKey publicKey = ...
		RSAPrivateKey privateKey = ...
		return new RSAKey.Builder(publicKey)
				.privateKey(privateKey)
				.keyID(UUID.randomUUID().toString())
				.build();
	}
	return null;
};

WebClientReactiveAuthorizationCodeTokenResponseClient tokenResponseClient =
		new WebClientReactiveAuthorizationCodeTokenResponseClient();
tokenResponseClient.addParametersConverter(
		new NimbusJwtClientAuthenticationParametersConverter<>(jwkResolver));
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val jwkResolver: Function<ClientRegistration, JWK> =
    Function<ClientRegistration, JWK> { clientRegistration ->
        if (clientRegistration.clientAuthenticationMethod.equals(ClientAuthenticationMethod.PRIVATE_KEY_JWT)) {
            // Giả sử loại key là RSA
            var publicKey: RSAPublicKey = ...
            var privateKey: RSAPrivateKey = ...
            RSAKey.Builder(publicKey)
                    .privateKey(privateKey)
                    .keyID(UUID.randomUUID().toString())
                .build()
        }
        null
    }

val tokenResponseClient = WebClientReactiveAuthorizationCodeTokenResponseClient()
tokenResponseClient.addParametersConverter(
    NimbusJwtClientAuthenticationParametersConverter(jwkResolver)
)
----
======

[[oauth2-client-authentication-jwt-bearer-client-secret-jwt]]
=== Xác thực bằng `client_secret_jwt`

Với các property Spring Boot sau đây dành cho một đăng ký client OAuth 2.0:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            client-authentication-method: client_secret_jwt
            authorization-grant-type: client_credentials
            ...
----

Ví dụ sau cho thấy cách cấu hình `WebClientReactiveClientCredentialsTokenResponseClient`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
Function<ClientRegistration, JWK> jwkResolver = (clientRegistration) -> {
	if (clientRegistration.getClientAuthenticationMethod().equals(ClientAuthenticationMethod.CLIENT_SECRET_JWT)) {
		SecretKeySpec secretKey = new SecretKeySpec(
				clientRegistration.getClientSecret().getBytes(StandardCharsets.UTF_8),
				"HmacSHA256");
		return new OctetSequenceKey.Builder(secretKey)
				.keyID(UUID.randomUUID().toString())
				.build();
	}
	return null;
};

WebClientReactiveClientCredentialsTokenResponseClient tokenResponseClient =
		new WebClientReactiveClientCredentialsTokenResponseClient();
tokenResponseClient.addParametersConverter(
		new NimbusJwtClientAuthenticationParametersConverter<>(jwkResolver));
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val jwkResolver = Function<ClientRegistration, JWK?> { clientRegistration: ClientRegistration ->
    if (clientRegistration.clientAuthenticationMethod == ClientAuthenticationMethod.CLIENT_SECRET_JWT) {
        val secretKey = SecretKeySpec(
            clientRegistration.clientSecret.toByteArray(StandardCharsets.UTF_8),
            "HmacSHA256"
        )
        OctetSequenceKey.Builder(secretKey)
            .keyID(UUID.randomUUID().toString())
            .build()
    }
    null
}

val tokenResponseClient = WebClientReactiveClientCredentialsTokenResponseClient()
tokenResponseClient.addParametersConverter(
    NimbusJwtClientAuthenticationParametersConverter(jwkResolver)
)
----
======

[[oauth2-client-authentication-jwt-bearer-assertion]]
=== Tùy chỉnh JWT assertion

JWT được tạo bởi `NimbusJwtClientAuthenticationParametersConverter` chứa các claim `iss`, `sub`, `aud`, `jti`, `iat` và `exp` theo mặc định. Bạn có thể tùy chỉnh các header và/hoặc claim bằng cách cung cấp một `Consumer<NimbusJwtClientAuthenticationParametersConverter.JwtClientAuthenticationContext<T>>` cho `setJwtClientAssertionCustomizer()`. Ví dụ sau cho thấy cách tùy chỉnh các claim của JWT:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
Function<ClientRegistration, JWK> jwkResolver = ...

NimbusJwtClientAuthenticationParametersConverter<OAuth2ClientCredentialsGrantRequest> converter =
		new NimbusJwtClientAuthenticationParametersConverter<>(jwkResolver);
converter.setJwtClientAssertionCustomizer((context) -> {
	context.getHeaders().header("custom-header", "header-value");
	context.getClaims().claim("custom-claim", "claim-value");
});
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val jwkResolver = ...

val converter: NimbusJwtClientAuthenticationParametersConverter<OAuth2ClientCredentialsGrantRequest> =
    NimbusJwtClientAuthenticationParametersConverter(jwkResolver)
converter.setJwtClientAssertionCustomizer { context ->
    context.headers.header("custom-header", "header-value")
    context.claims.claim("custom-claim", "claim-value")
}
----
======

[[oauth2-client-authentication-public]]
== [[oauth2Client-public-auth]]Public Authentication

Public Client Authentication được hỗ trợ sẵn và không cần tùy chỉnh để bật tính năng này.

Các property Spring Boot sau đây dành cho một đăng ký client OAuth 2.0 minh họa cấu hình này:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: client-id
            client-authentication-method: none
            authorization-grant-type: authorization_code
            ...
----

[NOTE]
====
Public Client được hỗ trợ bằng https://tools.ietf.org/html/rfc7636[Proof Key for Code Exchange] (PKCE).
PKCE sẽ được tự động sử dụng khi `client-authentication-method` được đặt thành "none" (`ClientAuthenticationMethod.NONE`).
====
