[[oauth2Client-core-interface-class]]
= Các interface/class cốt lõi


[[oauth2Client-client-registration]]
== ClientRegistration

`ClientRegistration` là biểu diễn của một client đã đăng ký với một Provider OAuth 2.0 hoặc OpenID Connect 1.0.

Một client registration chứa các thông tin như client id, client secret, authorization grant type, redirect URI, scope, authorization URI, token URI và các chi tiết khác.

`ClientRegistration` và các property của nó được định nghĩa như sau:

[source,java]
----
public final class ClientRegistration {
	private String registrationId;	<1>
	private String clientId;	<2>
	private String clientSecret;	<3>
	private ClientAuthenticationMethod clientAuthenticationMethod;	<4>
	private AuthorizationGrantType authorizationGrantType;	<5>
	private String redirectUri;	<6>
	private Set<String> scopes;	<7>
	private ProviderDetails providerDetails;
	private String clientName;	<8>

	public class ProviderDetails {
		private String authorizationUri;	<9>
		private String tokenUri;	<10>
		private UserInfoEndpoint userInfoEndpoint;
		private String jwkSetUri;	<11>
		private String issuerUri;	<12>
		private Map<String, Object> configurationMetadata;  <13>

		public class UserInfoEndpoint {
			private String uri;	<14>
			private AuthenticationMethod authenticationMethod;  <15>
			private String userNameAttributeName;	<16>

		}
	}

	public static final class ClientSettings {
		private boolean requireProofKey; // <17>
	}
}
----
<1> `registrationId`: ID định danh duy nhất cho `ClientRegistration`.
<2> `clientId`: Định danh client.
<3> `clientSecret`: Client secret.
<4> `clientAuthenticationMethod`: Method được sử dụng để authentication Client với Provider.
Các giá trị được hỗ trợ là *client_secret_basic*, *client_secret_post*, *private_key_jwt*, *client_secret_jwt* và *none* https://tools.ietf.org/html/rfc6749#section-2.1[(public clients)].
<5> `authorizationGrantType`: OAuth 2.0 Authorization Framework định nghĩa bốn loại https://tools.ietf.org/html/rfc6749#section-1.3[Authorization Grant].
 Các giá trị được hỗ trợ là `authorization_code`, `client_credentials` và extension grant type `urn:ietf:params:oauth:grant-type:jwt-bearer`.
<6> `redirectUri`: Redirect URI đã đăng ký của client mà _Authorization Server_ chuyển user-agent của end-user
 đến sau khi end-user đã authentication và cấp quyền truy cập cho client.
<7> `scopes`: Các scope được client yêu cầu trong luồng Authorization Request, chẳng hạn như openid, email hoặc profile.
<8> `clientName`: Tên mô tả được sử dụng cho client.
Tên này có thể được sử dụng trong một số trường hợp, chẳng hạn khi hiển thị tên client trên login page được tự động tạo.
<9> `authorizationUri`: URI của Authorization Endpoint dành cho Authorization Server.
<10> `tokenUri`: URI của Token Endpoint dành cho Authorization Server.
<11> `jwkSetUri`: URI được sử dụng để lấy https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] Set từ Authorization Server,
 chứa các key mật mã được sử dụng để xác minh https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)] của ID Token và tùy chọn xác minh UserInfo Response.
<12> `issuerUri`: Trả về URI định danh issuer của provider OpenID Connect 1.0 hoặc OAuth 2.0 Authorization Server.
<13> `configurationMetadata`: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Thông tin cấu hình OpenID Provider].
 Thông tin này chỉ khả dụng nếu property Spring Boot `spring.security.oauth2.client.provider.[providerId].issuerUri` được cấu hình.
<14> `(userInfoEndpoint)uri`: URI của UserInfo Endpoint được sử dụng để truy cập các claim/attribute của end-user đã authentication.
<15> `(userInfoEndpoint)authenticationMethod`: Authentication method được sử dụng khi gửi access token đến UserInfo Endpoint.
Các giá trị được hỗ trợ là *header*, *form* và *query*.
<16> `userNameAttributeName`: Tên của attribute được trả về trong UserInfo Response, tham chiếu đến Name hoặc Identifier của end-user.
<17> [[oauth2Client-client-registration-requireProofKey]]`requireProofKey`: Nếu `true` hoặc nếu `clientAuthenticationMethod` là `none` thì PKCE sẽ được bật. Mặc định là `true` cho grant type `authorization_code` và `false` cho các grant type khác.

Một `ClientRegistration` ban đầu có thể được cấu hình bằng discovery https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] của Provider OpenID Connect hoặc https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] của Authorization Server.

`ClientRegistrations` cung cấp các method tiện ích để cấu hình `ClientRegistration` theo cách này, như trong ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
ClientRegistration clientRegistration =
	ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val clientRegistration = ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build()
----
======

Code trên sẽ lần lượt truy vấn `https://idp.example.com/issuer/.well-known/openid-configuration`, sau đó `https://idp.example.com/.well-known/openid-configuration/issuer` và cuối cùng là `https://idp.example.com/.well-known/oauth-authorization-server/issuer`, rồi dừng ở endpoint đầu tiên trả về response 200.

Ngoài ra, bạn có thể sử dụng `ClientRegistrations.fromOidcIssuerLocation()` để chỉ truy vấn Configuration endpoint của Provider OpenID Connect.

[[oauth2Client-client-registration-repo]]
== ReactiveClientRegistrationRepository

`ReactiveClientRegistrationRepository` đóng vai trò repository cho các `ClientRegistration` OAuth 2.0 / OpenID Connect 1.0.

[NOTE]
====
Thông tin client registration cuối cùng được lưu trữ và sở hữu bởi Authorization Server liên kết.
Repository này cho phép truy xuất một tập con của thông tin client registration chính được lưu trữ với Authorization Server.
====

Spring Boot auto-configuration liên kết từng property dưới `spring.security.oauth2.client.registration._[registrationId]_` với một instance của `ClientRegistration`, sau đó tập hợp các instance `ClientRegistration` vào một `ReactiveClientRegistrationRepository`.

[NOTE]
====
Implementation mặc định của `ReactiveClientRegistrationRepository` là `InMemoryReactiveClientRegistrationRepository`.
====

Auto-configuration cũng đăng ký `ReactiveClientRegistrationRepository` dưới dạng một `@Bean` trong `ApplicationContext` để application có thể dependency injection khi cần.

Listing sau đây minh họa một ví dụ:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ReactiveClientRegistrationRepository clientRegistrationRepository;

	@GetMapping("/")
	public Mono<String> index() {
		return this.clientRegistrationRepository.findByRegistrationId("okta")
				...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var clientRegistrationRepository: ReactiveClientRegistrationRepository

    @GetMapping("/")
    fun index(): Mono<String> {
        return this.clientRegistrationRepository.findByRegistrationId("okta")
            ...
            .thenReturn("index")
    }
}
----
======

[[oauth2Client-authorized-client]]
== OAuth2AuthorizedClient

`OAuth2AuthorizedClient` là biểu diễn của một Client đã được cấp quyền.
Một client được xem là đã được cấp quyền khi end-user (Resource Owner) đã cấp authorization cho client để truy cập các protected resource của mình.

`OAuth2AuthorizedClient` được dùng để liên kết một `OAuth2AccessToken` (và `OAuth2RefreshToken` tùy chọn) với một `ClientRegistration` (client) và resource owner, là `Principal` end-user đã cấp authorization.


[[oauth2Client-authorized-repo-service]]
== ServerOAuth2AuthorizedClientRepository / ReactiveOAuth2AuthorizedClientService

`ServerOAuth2AuthorizedClientRepository` chịu trách nhiệm lưu giữ các `OAuth2AuthorizedClient` giữa các web request.
Trong khi đó, vai trò chính của `ReactiveOAuth2AuthorizedClientService` là quản lý các `OAuth2AuthorizedClient` ở cấp application.

Từ góc nhìn developer, `ServerOAuth2AuthorizedClientRepository` hoặc `ReactiveOAuth2AuthorizedClientService` cung cấp khả năng tra cứu một `OAuth2AccessToken` liên kết với client để token này có thể được sử dụng nhằm khởi tạo protected resource request.

Listing sau đây minh họa một ví dụ:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ReactiveOAuth2AuthorizedClientService authorizedClientService;

	@GetMapping("/")
	public Mono<String> index(Authentication authentication) {
		return this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName())
				.map(OAuth2AuthorizedClient::getAccessToken)
				...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var authorizedClientService: ReactiveOAuth2AuthorizedClientService

    @GetMapping("/")
    fun index(authentication: Authentication): Mono<String> {
        return this.authorizedClientService.loadAuthorizedClient<OAuth2AuthorizedClient>("okta", authentication.name)
            .map { it.accessToken }
            ...
            .thenReturn("index")
    }
}
----
======

[NOTE]
====
Spring Boot auto-configuration đăng ký `ServerOAuth2AuthorizedClientRepository` và/hoặc `ReactiveOAuth2AuthorizedClientService` `@Bean` trong `ApplicationContext`.
Tuy nhiên, application có thể chọn override và đăng ký `ServerOAuth2AuthorizedClientRepository` hoặc `ReactiveOAuth2AuthorizedClientService` `@Bean` tùy chỉnh.
====

Implementation mặc định của `ReactiveOAuth2AuthorizedClientService` là `InMemoryReactiveOAuth2AuthorizedClientService`, lưu trữ các `OAuth2AuthorizedClient` trong memory.

Ngoài ra, implementation R2DBC `R2dbcReactiveOAuth2AuthorizedClientService` có thể được cấu hình để lưu giữ các `OAuth2AuthorizedClient` trong database.

[NOTE]
====
`R2dbcReactiveOAuth2AuthorizedClientService` phụ thuộc vào định nghĩa table được mô tả trong xref:servlet/appendix/database-schema.adoc#dbschema-oauth2-client[ Lược đồ Client OAuth 2.0].
====


[[oauth2Client-authorized-manager-provider]]
== ReactiveOAuth2AuthorizedClientManager / ReactiveOAuth2AuthorizedClientProvider

`ReactiveOAuth2AuthorizedClientManager` chịu trách nhiệm quản lý tổng thể các `OAuth2AuthorizedClient`.

Các trách nhiệm chính gồm:

* Cấp quyền (hoặc cấp quyền lại) cho một Client OAuth 2.0 bằng `ReactiveOAuth2AuthorizedClientProvider`.
* Ủy quyền việc lưu giữ một `OAuth2AuthorizedClient`, thường bằng `ReactiveOAuth2AuthorizedClientService` hoặc `ServerOAuth2AuthorizedClientRepository`.
* Ủy quyền cho `ReactiveOAuth2AuthorizationSuccessHandler` khi một Client OAuth 2.0 được cấp quyền (hoặc cấp quyền lại) thành công.
* Ủy quyền cho `ReactiveOAuth2AuthorizationFailureHandler` khi một Client OAuth 2.0 cấp quyền (hoặc cấp quyền lại) thất bại.

`ReactiveOAuth2AuthorizedClientProvider` triển khai một strategy để cấp quyền (hoặc cấp quyền lại) cho một Client OAuth 2.0.
Các implementation thường triển khai một authorization grant type, ví dụ `authorization_code`, `client_credentials`, v.v.

Implementation mặc định của `ReactiveOAuth2AuthorizedClientManager` là `DefaultReactiveOAuth2AuthorizedClientManager`, được liên kết với một `ReactiveOAuth2AuthorizedClientProvider` có thể hỗ trợ nhiều authorization grant type bằng một composite dựa trên delegation.
Có thể sử dụng `ReactiveOAuth2AuthorizedClientProviderBuilder` để cấu hình và xây dựng composite dựa trên delegation.

Code sau đây minh họa cách cấu hình và xây dựng một composite `ReactiveOAuth2AuthorizedClientProvider` hỗ trợ các authorization grant type `authorization_code`, `refresh_token` và `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Khi lần thử authorization thành công, `DefaultReactiveOAuth2AuthorizedClientManager` sẽ ủy quyền cho `ReactiveOAuth2AuthorizationSuccessHandler`, handler này (theo mặc định) sẽ lưu `OAuth2AuthorizedClient` thông qua `ServerOAuth2AuthorizedClientRepository`.
Trong trường hợp authorization lại thất bại, ví dụ refresh token không còn hợp lệ, `OAuth2AuthorizedClient` đã lưu trước đó sẽ được xóa khỏi `ServerOAuth2AuthorizedClientRepository` thông qua `RemoveAuthorizedClientReactiveOAuth2AuthorizationFailureHandler`.
Hành vi mặc định có thể được tùy chỉnh thông qua `setAuthorizationSuccessHandler(ReactiveOAuth2AuthorizationSuccessHandler)` và `setAuthorizationFailureHandler(ReactiveOAuth2AuthorizationFailureHandler)`.

`DefaultReactiveOAuth2AuthorizedClientManager` cũng được liên kết với một `contextAttributesMapper` có kiểu `Function<OAuth2AuthorizeRequest, Mono<Map<String, Object>>>`, chịu trách nhiệm ánh xạ các attribute từ `OAuth2AuthorizeRequest` sang một `Map` các attribute để liên kết với `OAuth2AuthorizationContext`.
Điều này hữu ích khi bạn cần cung cấp cho `ReactiveOAuth2AuthorizedClientProvider` các attribute bắt buộc (được hỗ trợ).

Code sau đây minh họa một ví dụ về `contextAttributesMapper`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	// Assuming the attributes are supplied as `ServerHttpRequest` parameters,
	// map the `ServerHttpRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
	authorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

	return authorizedClientManager;
}

private Function<OAuth2AuthorizeRequest, Mono<Map<String, Object>>> contextAttributesMapper() {
	return authorizeRequest -> {
		Map<String, Object> contextAttributes = Collections.emptyMap();
		ServerWebExchange exchange = authorizeRequest.getAttribute(ServerWebExchange.class.getName());
		ServerHttpRequest request = exchange.getRequest();
		String param1 = request.getQueryParams().getFirst("param1");
		String param2 = request.getQueryParams().getFirst("param2");
		if (StringUtils.hasText(param1) && StringUtils.hasText(param2)) {
			contextAttributes = new HashMap<>();
			contextAttributes.put("param1", param1);
			contextAttributes.put("param2", param2);
		}
		return Mono.just(contextAttributes);
	};
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

	// Assuming the attributes are supplied as `ServerHttpRequest` parameters,
	// map the `ServerHttpRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
    authorizedClientManager.setContextAttributesMapper(contextAttributesMapper())
    return authorizedClientManager
}

private fun contextAttributesMapper(): Function<OAuth2AuthorizeRequest, Mono<MutableMap<String, Any>>> {
    return Function { authorizeRequest ->
        var contextAttributes: MutableMap<String, Any> = mutableMapOf()
        val exchange: ServerWebExchange = authorizeRequest.getAttribute(ServerWebExchange::class.java.name)!!
        val request: ServerHttpRequest = exchange.request
        val param1: String? = request.queryParams.getFirst("param1")
        val param2: String? = request.queryParams.getFirst("param2")
        if (StringUtils.hasText(param1) && StringUtils.hasText(param2)) {
            contextAttributes = hashMapOf()
            contextAttributes["param1"] = param1!!
            contextAttributes["param2"] = param2!!
        }
        Mono.just(contextAttributes)
    }
}
----
======

`DefaultReactiveOAuth2AuthorizedClientManager` được thiết kế để sử dụng *_bên trong_* context của một `ServerWebExchange`.
Khi hoạt động *_bên ngoài_* context `ServerWebExchange`, hãy sử dụng `AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager` thay thế.

_Service application_ là một use case phổ biến để sử dụng `AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager`.
Service application thường chạy ở background, không có tương tác của user và thường chạy dưới một account cấp hệ thống thay vì account người dùng.
Một Client OAuth 2.0 được cấu hình với grant type `client_credentials` có thể được xem là một loại service application.

Code sau đây minh họa cách cấu hình một `AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager` hỗ trợ grant type `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ReactiveOAuth2AuthorizedClientService authorizedClientService) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.clientCredentials()
					.build();

	AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientService);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientService: ReactiveOAuth2AuthorizedClientService): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build()
    val authorizedClientManager = AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientService)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======
