[[oauth2Client-core-interface-class]]
= Các interface/class cốt lõi


[[oauth2Client-client-registration]]
== ClientRegistration

`ClientRegistration` biểu diễn một client đã đăng ký với một OAuth 2.0 hoặc OpenID Connect 1.0 Provider.

Một client registration chứa các thông tin như client id, client secret, authorization grant type, redirect URI, scope(s), authorization URI, token URI và các chi tiết khác.

`ClientRegistration` và các properties của nó được định nghĩa như sau:

[source,java]
----
public final class ClientRegistration {
	private String registrationId;	<1>
	private String clientId;	<2>
	private String clientSecret;	<3>
	private ClientAuthenticationMethod clientAuthenticationMethod;	<4>
	private AuthorizationGrantType authorizationGrantType;	<5>
	private String redirectUri;	<6>
	private Set<String> scopes;	<7>
	private ProviderDetails providerDetails;
	private String clientName;	<8>

	public class ProviderDetails {
		private String authorizationUri;	<9>
		private String tokenUri;	<10>
		private UserInfoEndpoint userInfoEndpoint;
		private String jwkSetUri;	<11>
		private String issuerUri;	<12>
		private Map<String, Object> configurationMetadata;  <13>

		public class UserInfoEndpoint {
			private String uri;	<14>
			private AuthenticationMethod authenticationMethod;  <15>
			private String userNameAttributeName;	<16>

		}
	}

	public static final class ClientSettings {
		private boolean requireProofKey; // <17>
	}
}
----
<1> `registrationId`: ID duy nhất xác định `ClientRegistration`.
<2> `clientId`: Client identifier.
<3> `clientSecret`: Client secret.
<4> `clientAuthenticationMethod`: Method được sử dụng để authenticate Client với Provider.
Các giá trị được hỗ trợ là *client_secret_basic*, *client_secret_post*, *private_key_jwt*, *client_secret_jwt* và *none* https://tools.ietf.org/html/rfc6749#section-2.1[(public clients)].
<5> `authorizationGrantType`: OAuth 2.0 Authorization Framework định nghĩa bốn loại https://tools.ietf.org/html/rfc6749#section-1.3[Authorization Grant].
 Các giá trị được hỗ trợ là `authorization_code`, `client_credentials` và extension grant type `urn:ietf:params:oauth:grant-type:jwt-bearer`.
<6> `redirectUri`: Redirect URI đã đăng ký của client, nơi _Authorization Server_ redirect user-agent của end-user
 sau khi end-user authenticated và authorize quyền truy cập cho client.
<7> `scopes`: Các scope mà client yêu cầu trong flow Authorization Request, chẳng hạn như openid, email hoặc profile.
<8> `clientName`: Tên mô tả được dùng cho client.
Tên này có thể được dùng trong một số trường hợp, chẳng hạn khi hiển thị tên client trên login page được tự động tạo.
<9> `authorizationUri`: URI của Authorization Endpoint dành cho Authorization Server.
<10> `tokenUri`: URI của Token Endpoint dành cho Authorization Server.
<11> `jwkSetUri`: URI được sử dụng để lấy https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] Set từ Authorization Server,
 chứa các cryptographic key được sử dụng để verify https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)] của ID Token và tùy chọn verify UserInfo Response.
<12> `issuerUri`: Trả về issuer identifier URI của OpenID Connect 1.0 Provider hoặc OAuth 2.0 Authorization Server.
<13> `configurationMetadata`: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Thông tin configuration của OpenID Provider].
 Thông tin này chỉ khả dụng nếu property của Spring Boot `spring.security.oauth2.client.provider.[providerId].issuerUri` được configure.
<14> `(userInfoEndpoint)uri`: URI của UserInfo Endpoint được sử dụng để access các claim/attribute của end-user đã authenticated.
<15> `(userInfoEndpoint)authenticationMethod`: Authentication method được sử dụng khi gửi access token đến UserInfo Endpoint.
Các giá trị được hỗ trợ là *header*, *form* và *query*.
<16> `userNameAttributeName`: Tên của attribute được trả về trong UserInfo Response, tham chiếu đến Name hoặc Identifier của end-user.
<17> [[oauth2Client-client-registration-requireProofKey]]`requireProofKey`: Nếu `true` hoặc nếu `clientAuthenticationMethod` là `none` thì PKCE sẽ được bật. Mặc định là `true` cho grant type `authorization_code` và `false` cho các grant type khác.

Một `ClientRegistration` có thể được configure ban đầu thông qua discovery https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] của một OpenID Connect Provider hoặc https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] của một Authorization Server.

`ClientRegistrations` cung cấp các method tiện ích để configure `ClientRegistration` theo cách này, như trong ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
ClientRegistration clientRegistration =
	ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val clientRegistration = ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build()
----
======

Code trên sẽ lần lượt query `https://idp.example.com/issuer/.well-known/openid-configuration`, sau đó `https://idp.example.com/.well-known/openid-configuration/issuer` và cuối cùng là `https://idp.example.com/.well-known/oauth-authorization-server/issuer`, rồi dừng ở URL đầu tiên trả về response 200.

Ngoài ra, bạn có thể sử dụng `ClientRegistrations.fromOidcIssuerLocation()` để chỉ query Configuration endpoint của OpenID Connect Provider.

[[oauth2Client-client-registration-repo]]
== ReactiveClientRegistrationRepository

`ReactiveClientRegistrationRepository` đóng vai trò repository lưu các `ClientRegistration` OAuth 2.0 / OpenID Connect 1.0.

[NOTE]
====
Thông tin client registration cuối cùng được lưu trữ và sở hữu bởi Authorization Server tương ứng.
Repository này cho phép retrieve một subset của thông tin client registration chính được lưu trữ tại Authorization Server.
====

Spring Boot auto-configuration bind từng property dưới `spring.security.oauth2.client.registration._[registrationId]_` vào một instance của `ClientRegistration`, sau đó compose các instance `ClientRegistration` vào một `ReactiveClientRegistrationRepository`.

[NOTE]
====
Implementation mặc định của `ReactiveClientRegistrationRepository` là `InMemoryReactiveClientRegistrationRepository`.
====

Auto-configuration cũng đăng ký `ReactiveClientRegistrationRepository` dưới dạng một `@Bean` trong `ApplicationContext` để application có thể inject dependency khi cần.

Ví dụ sau đây minh họa:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ReactiveClientRegistrationRepository clientRegistrationRepository;

	@GetMapping("/")
	public Mono<String> index() {
		return this.clientRegistrationRepository.findByRegistrationId("okta")
				...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var clientRegistrationRepository: ReactiveClientRegistrationRepository

    @GetMapping("/")
    fun index(): Mono<String> {
        return this.clientRegistrationRepository.findByRegistrationId("okta")
            ...
            .thenReturn("index")
    }
}
----
======

[[oauth2Client-authorized-client]]
== OAuth2AuthorizedClient

`OAuth2AuthorizedClient` biểu diễn một Authorized Client.
Một client được xem là đã được cấp quyền khi end-user (Resource Owner) đã cấp authorization cho client để access các protected resource của mình.

`OAuth2AuthorizedClient` dùng để liên kết một `OAuth2AccessToken` (và `OAuth2RefreshToken` tùy chọn) với một `ClientRegistration` (client) và resource owner, tức `Principal` end-user đã cấp authorization.


[[oauth2Client-authorized-repo-service]]
== ServerOAuth2AuthorizedClientRepository / ReactiveOAuth2AuthorizedClientService

`ServerOAuth2AuthorizedClientRepository` chịu trách nhiệm persist các `OAuth2AuthorizedClient` giữa các web request.
Trong khi đó, vai trò chính của `ReactiveOAuth2AuthorizedClientService` là quản lý các `OAuth2AuthorizedClient` ở cấp application.

Từ góc nhìn developer, `ServerOAuth2AuthorizedClientRepository` hoặc `ReactiveOAuth2AuthorizedClientService` cung cấp khả năng lookup một `OAuth2AccessToken` liên kết với client để token này có thể được dùng nhằm initiate một protected resource request.

Ví dụ sau đây minh họa:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ReactiveOAuth2AuthorizedClientService authorizedClientService;

	@GetMapping("/")
	public Mono<String> index(Authentication authentication) {
		return this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName())
				.map(OAuth2AuthorizedClient::getAccessToken)
				...
				.thenReturn("index");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var authorizedClientService: ReactiveOAuth2AuthorizedClientService

    @GetMapping("/")
    fun index(authentication: Authentication): Mono<String> {
        return this.authorizedClientService.loadAuthorizedClient<OAuth2AuthorizedClient>("okta", authentication.name)
            .map { it.accessToken }
            ...
            .thenReturn("index")
    }
}
----
======

[NOTE]
====
Spring Boot auto-configuration đăng ký `ServerOAuth2AuthorizedClientRepository` và/hoặc `ReactiveOAuth2AuthorizedClientService` dưới dạng `@Bean` trong `ApplicationContext`.
Tuy nhiên, application có thể chọn override và đăng ký một `ServerOAuth2AuthorizedClientRepository` hoặc `ReactiveOAuth2AuthorizedClientService` `@Bean` tùy chỉnh.
====

Implementation mặc định của `ReactiveOAuth2AuthorizedClientService` là `InMemoryReactiveOAuth2AuthorizedClientService`, persist các `OAuth2AuthorizedClient` trong memory.

Ngoài ra, implementation R2DBC `R2dbcReactiveOAuth2AuthorizedClientService` có thể được configure để persist các `OAuth2AuthorizedClient` trong database.

[NOTE]
====
`R2dbcReactiveOAuth2AuthorizedClientService` phụ thuộc vào table definition được mô tả trong xref:servlet/appendix/database-schema.adoc#dbschema-oauth2-client[ OAuth 2.0 Client Schema].
====


[[oauth2Client-authorized-manager-provider]]
== ReactiveOAuth2AuthorizedClientManager / ReactiveOAuth2AuthorizedClientProvider

`ReactiveOAuth2AuthorizedClientManager` chịu trách nhiệm quản lý tổng thể các `OAuth2AuthorizedClient`.

Các trách nhiệm chính gồm:

* Authorize (hoặc re-authorize) một OAuth 2.0 Client bằng `ReactiveOAuth2AuthorizedClientProvider`.
* Delegate việc persist một `OAuth2AuthorizedClient`, thường bằng `ReactiveOAuth2AuthorizedClientService` hoặc `ServerOAuth2AuthorizedClientRepository`.
* Delegate tới `ReactiveOAuth2AuthorizationSuccessHandler` khi một OAuth 2.0 Client được authorize (hoặc re-authorize) thành công.
* Delegate tới `ReactiveOAuth2AuthorizationFailureHandler` khi một OAuth 2.0 Client authorize (hoặc re-authorize) thất bại.

`ReactiveOAuth2AuthorizedClientProvider` triển khai một strategy để authorize (hoặc re-authorize) một OAuth 2.0 Client.
Các implementation thường implement một authorization grant type, ví dụ `authorization_code`, `client_credentials`, v.v.

Implementation mặc định của `ReactiveOAuth2AuthorizedClientManager` là `DefaultReactiveOAuth2AuthorizedClientManager`, được associate với một `ReactiveOAuth2AuthorizedClientProvider` có thể support nhiều authorization grant type thông qua một delegation-based composite.
Có thể sử dụng `ReactiveOAuth2AuthorizedClientProviderBuilder` để configure và build delegation-based composite.

Code sau đây minh họa cách configure và build một composite `ReactiveOAuth2AuthorizedClientProvider` hỗ trợ các authorization grant type `authorization_code`, `refresh_token` và `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Khi một authorization attempt thành công, `DefaultReactiveOAuth2AuthorizedClientManager` sẽ delegate tới `ReactiveOAuth2AuthorizationSuccessHandler`, handler này (theo mặc định) sẽ save `OAuth2AuthorizedClient` thông qua `ServerOAuth2AuthorizedClientRepository`.
Trong trường hợp re-authorization thất bại, ví dụ refresh token không còn valid, `OAuth2AuthorizedClient` đã được save trước đó sẽ bị remove khỏi `ServerOAuth2AuthorizedClientRepository` thông qua `RemoveAuthorizedClientReactiveOAuth2AuthorizationFailureHandler`.
Behavior mặc định có thể được customize thông qua `setAuthorizationSuccessHandler(ReactiveOAuth2AuthorizationSuccessHandler)` và `setAuthorizationFailureHandler(ReactiveOAuth2AuthorizationFailureHandler)`.

`DefaultReactiveOAuth2AuthorizedClientManager` cũng được associate với một `contextAttributesMapper` có kiểu `Function<OAuth2AuthorizeRequest, Mono<Map<String, Object>>>`, chịu trách nhiệm map các attribute từ `OAuth2AuthorizeRequest` sang một `Map` chứa các attribute để associate với `OAuth2AuthorizationContext`.
Điều này hữu ích khi bạn cần cung cấp cho `ReactiveOAuth2AuthorizedClientProvider` các attribute bắt buộc (được support).

Code sau đây minh họa `contextAttributesMapper`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.build();

	DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	// Assuming the attributes are supplied as `ServerHttpRequest` parameters,
	// map the `ServerHttpRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
	authorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

	return authorizedClientManager;
}

private Function<OAuth2AuthorizeRequest, Mono<Map<String, Object>>> contextAttributesMapper() {
	return authorizeRequest -> {
		Map<String, Object> contextAttributes = Collections.emptyMap();
		ServerWebExchange exchange = authorizeRequest.getAttribute(ServerWebExchange.class.getName());
		ServerHttpRequest request = exchange.getRequest();
		String param1 = request.getQueryParams().getFirst("param1");
		String param2 = request.getQueryParams().getFirst("param2");
		if (StringUtils.hasText(param1) && StringUtils.hasText(param2)) {
			contextAttributes = new HashMap<>();
			contextAttributes.put("param1", param1);
			contextAttributes.put("param2", param2);
		}
		return Mono.just(contextAttributes);
	};
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientRepository: ServerOAuth2AuthorizedClientRepository): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .build()
    val authorizedClientManager = DefaultReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

	// Assuming the attributes are supplied as `ServerHttpRequest` parameters,
	// map the `ServerHttpRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
    authorizedClientManager.setContextAttributesMapper(contextAttributesMapper())
    return authorizedClientManager
}

private fun contextAttributesMapper(): Function<OAuth2AuthorizeRequest, Mono<MutableMap<String, Any>>> {
    return Function { authorizeRequest ->
        var contextAttributes: MutableMap<String, Any> = mutableMapOf()
        val exchange: ServerWebExchange = authorizeRequest.getAttribute(ServerWebExchange::class.java.name)!!
        val request: ServerHttpRequest = exchange.request
        val param1: String? = request.queryParams.getFirst("param1")
        val param2: String? = request.queryParams.getFirst("param2")
        if (StringUtils.hasText(param1) && StringUtils.hasText(param2)) {
            contextAttributes = hashMapOf()
            contextAttributes["param1"] = param1!!
            contextAttributes["param2"] = param2!!
        }
        Mono.just(contextAttributes)
    }
}
----
======

`DefaultReactiveOAuth2AuthorizedClientManager` được thiết kế để sử dụng *_bên trong_* context của một `ServerWebExchange`.
Khi hoạt động *_bên ngoài_* context `ServerWebExchange`, hãy sử dụng `AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager` thay thế.

_Service application_ là một use case phổ biến khi sử dụng `AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager`.
Service application thường chạy ở background, không có user interaction và thường chạy dưới một system-level account thay vì user account.
Một OAuth 2.0 Client được configure với grant type `client_credentials` có thể được xem là một loại service application.

Code sau đây minh họa cách configure một `AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager` hỗ trợ grant type `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
		ReactiveClientRegistrationRepository clientRegistrationRepository,
		ReactiveOAuth2AuthorizedClientService authorizedClientService) {

	ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
					.clientCredentials()
					.build();

	AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientService);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ReactiveClientRegistrationRepository,
        authorizedClientService: ReactiveOAuth2AuthorizedClientService): ReactiveOAuth2AuthorizedClientManager {
    val authorizedClientProvider: ReactiveOAuth2AuthorizedClientProvider = ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build()
    val authorizedClientManager = AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientService)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======
