= Bearer Token của Resource Server OAuth 2.0

[[webflux-oauth2resourceserver-bearertoken-resolver]]
== Phân giải Bearer Token

Theo mặc định, Resource Server tìm bearer token trong header `Authorization`.
Tuy nhiên, bạn có thể xác minh token này.

Ví dụ, bạn có thể cần đọc bearer token từ một header tùy chỉnh.
Để làm vậy, bạn có thể kết nối một instance của `ServerBearerTokenAuthenticationConverter` vào DSL:

.Header Bearer Token tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
ServerBearerTokenAuthenticationConverter converter = new ServerBearerTokenAuthenticationConverter();
converter.setBearerTokenHeaderName(HttpHeaders.PROXY_AUTHORIZATION);
http
    .oauth2ResourceServer((oauth2) -> oauth2
        .bearerTokenConverter(converter)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val converter = ServerBearerTokenAuthenticationConverter()
converter.setBearerTokenHeaderName(HttpHeaders.PROXY_AUTHORIZATION)
return http {
    oauth2ResourceServer {
        bearerTokenConverter = converter
    }
}
----
======

== Truyền Bearer Token

Bây giờ bạn đã có một bearer token, bạn có thể truyền token đó đến các downstream service.
Điều này có thể thực hiện bằng javadoc:org.springframework.security.oauth2.server.resource.web.reactive.function.client.ServerBearerExchangeFilterFunction[]:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public WebClient rest() {
    return WebClient.builder()
            .filter(new ServerBearerExchangeFilterFunction())
            .build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun rest(): WebClient {
    return WebClient.builder()
            .filter(ServerBearerExchangeFilterFunction())
            .build()
}
----
======

Khi `WebClient` trong ví dụ trước thực hiện các request, Spring Security tra cứu `Authentication` hiện tại và trích xuất credential javadoc:org.springframework.security.oauth2.core.AbstractOAuth2Token[].
Sau đó, nó truyền token đó trong header `Authorization` -- ví dụ:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .retrieve()
        .bodyToMono(String.class)
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .retrieve()
        .bodyToMono<String>()
----
======

Ví dụ trước gọi `https://other-service.example.com/endpoint` và tự thêm header `Authorization` chứa bearer token cho bạn.

Ở những nơi bạn cần ghi đè hành vi này, bạn có thể tự cung cấp header:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .headers((headers) -> headers.setBearerAuth(overridingToken))
        .retrieve()
        .bodyToMono(String.class)
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
rest.get()
        .uri("https://other-service.example.com/endpoint")
        .headers { it.setBearerAuth(overridingToken) }
        .retrieve()
        .bodyToMono<String>()
----
======

Trong trường hợp này, filter sẽ chuyển sang phương án dự phòng và chuyển tiếp request đến phần còn lại của web filter chain.

[NOTE]
====
Không giống javadoc:org.springframework.security.oauth2.client.web.reactive.function.client.ServerOAuth2AuthorizedClientExchangeFilterFunction[filter function của OAuth 2.0 Client], filter function này không cố gắng gia hạn token nếu token đã hết hạn.
====
