= JWT của Resource Server OAuth 2.0

[[webflux-oauth2resourceserver-jwt-minimaldependencies]]
== Dependency tối thiểu cho JWT

Phần lớn hỗ trợ cho Resource Server được tập hợp trong `spring-security-oauth2-resource-server`.
Tuy nhiên, hỗ trợ giải mã và xác minh JWT nằm trong `spring-security-oauth2-jose`, nghĩa là cần cả hai để có một resource server hoạt động và hỗ trợ Bearer Token được mã hóa bằng JWT.

[[webflux-oauth2resourceserver-jwt-minimalconfiguration]]
== Cấu hình tối thiểu cho JWT

Khi sử dụng https://spring.io/projects/spring-boot[Spring Boot], việc cấu hình một ứng dụng thành Resource Server gồm hai bước cơ bản.
Trước tiên, thêm các dependency cần thiết. Tiếp theo, chỉ ra vị trí của Authorization Server.

=== Chỉ định Authorization Server

Trong một ứng dụng Spring Boot, bạn cần chỉ định authorization server sẽ sử dụng:

[source,yml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
----

Trong đó, `https://idp.example.com/issuer` là giá trị nằm trong claim `iss` của các JWT mà authorization server phát hành.
Resource Server sử dụng property này để tự cấu hình thêm, phát hiện public key của authorization server, sau đó xác thực các JWT đến.

[NOTE]
====
Để sử dụng property `issuer-uri`, một trong các endpoint `https://idp.example.com/issuer/.well-known/openid-configuration`, `https://idp.example.com/.well-known/openid-configuration/issuer` hoặc `https://idp.example.com/.well-known/oauth-authorization-server/issuer` cũng phải là endpoint được authorization server hỗ trợ.
Endpoint này được gọi là endpoint https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Cấu hình Provider] hoặc endpoint https://tools.ietf.org/html/rfc8414#section-3[Metadata của Authorization Server].
====

=== Hành vi khi khởi động

Khi sử dụng property và các dependency này, Resource Server tự động cấu hình để xác thực Bearer Token được mã hóa bằng JWT.

Resource Server thực hiện việc này thông qua một quy trình discovery có tính xác định, được khởi chạy khi có request đầu tiên chứa JWT:

. Truy cập endpoint Cấu hình Provider hoặc Metadata của Authorization Server, xử lý response để lấy property `jwks_url`.
. Cấu hình chiến lược xác thực để truy vấn `jwks_url` lấy các public key hợp lệ.
. Cấu hình chiến lược xác thực để xác thực claim `iss` của từng JWT đối chiếu với `https://idp.example.com`.

Một lợi ích của việc trì hoãn quy trình này là quá trình khởi động Resource Server không phụ thuộc vào khả dụng của authorization server.

[NOTE]
====
Việc trì hoãn này được quản lý bởi javadoc:org.springframework.security.oauth2.jwt.SupplierReactiveJwtDecoder[`SupplierReactiveJwtDecoder`].
Hãy cân nhắc bọc mọi <<webflux-oauth2resourceserver-decoder-bean,`JwtDecoder` `@Bean`>> mà bạn khai báo để duy trì hành vi này.
====

=== Hành vi khi chạy

Sau khi ứng dụng khởi động, Resource Server cố gắng xử lý mọi request chứa header `Authorization: Bearer`:

[source,html]
----
GET / HTTP/1.1
Authorization: Bearer some-token-value # Resource Server will process this
----

Miễn là scheme này được chỉ định, Resource Server cố gắng xử lý request theo đặc tả Bearer Token.

Với một JWT có định dạng đúng, Resource Server sẽ:

. Xác thực chữ ký của JWT bằng public key lấy từ endpoint `jwks_url` trong quá trình khởi động và đối chiếu với header của JWT.
. Xác thực timestamp `exp`, `nbf` và claim `iss` của JWT.
. Ánh xạ mỗi scope thành một authority với tiền tố `SCOPE_`.

[NOTE]
====
Khi authorization server cung cấp các key mới, Spring Security tự động xoay vòng các key được sử dụng để xác thực JWT.
====

Theo mặc định, `Authentication#getPrincipal` nhận được là một object `Jwt` của Spring Security, còn `Authentication#getName` ánh xạ đến property `sub` của JWT nếu property này tồn tại.

Từ đây, bạn có thể chuyển đến:

* <<webflux-oauth2resourceserver-jwt-jwkseturi,Cách cấu hình mà không ràng buộc quá trình khởi động Resource Server với khả dụng của authorization server>>
* <<webflux-oauth2resourceserver-jwt-sansboot,Cách cấu hình mà không dùng Spring Boot>>

[[webflux-oauth2resourceserver-jwt-jwkseturi]]
=== Chỉ định trực tiếp Uri của JWK Set của Authorization Server

Nếu authorization server không hỗ trợ configuration endpoint nào, hoặc nếu Resource Server phải có khả năng khởi tạo độc lập với authorization server, bạn cũng có thể cung cấp `jwk-set-uri`:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json
----

[NOTE]
====
Uri của JWK Set không được chuẩn hóa, nhưng thông thường bạn có thể tìm thấy nó trong tài liệu của authorization server.
====

Do đó, Resource Server không ping authorization server khi khởi động.
Chúng ta vẫn chỉ định `issuer-uri` để Resource Server tiếp tục xác thực claim `iss` trên các JWT đến.

[NOTE]
====
Bạn có thể cung cấp property này trực tiếp trên <<webflux-oauth2resourceserver-jwt-jwkseturi-dsl,DSL>>.
====

[[webflux-oauth2resourceserver-jwt-sansboot]]
=== Ghi đè hoặc thay thế Auto-configuration của Boot

Spring Boot tạo hai object `@Bean` thay cho Resource Server.

Bean đầu tiên là một `SecurityWebFilterChain` cấu hình ứng dụng thành Resource Server. Khi thêm `spring-security-oauth2-jose`, `SecurityWebFilterChain` này có dạng:

.SecurityWebFilterChain của Resource Server
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(OAuth2ResourceServerSpec::jwt)
	return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt { }
        }
    }
}
----
======

Nếu ứng dụng không expose bean `SecurityWebFilterChain`, Spring Boot expose bean mặc định (được hiển thị trong listing trước đó).

Để thay thế bean này, hãy expose `@Bean` trong ứng dụng:

.Thay thế SecurityWebFilterChain
[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope;

@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.pathMatchers("/message/**").access(hasScope("message:read"))
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer((oauth2) -> oauth2
			.jwt(withDefaults())
		);
	return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope

@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize("/message/**", hasScope("message:read"))
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt { }
        }
    }
}
----
======

Cấu hình trước đó yêu cầu scope `message:read` đối với mọi URL bắt đầu bằng `/messages/`.

Các method trên DSL `oauth2ResourceServer` cũng ghi đè hoặc thay thế auto-configuration.

Ví dụ, `@Bean` thứ hai mà Spring Boot tạo là một `ReactiveJwtDecoder`, dùng để giải mã token `String` thành các instance `Jwt` đã được xác thực:

.ReactiveJwtDecoder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return ReactiveJwtDecoders.fromIssuerLocation(issuerUri);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return ReactiveJwtDecoders.fromIssuerLocation(issuerUri)
}
----
======

[NOTE]
====
Việc gọi javadoc:org.springframework.security.oauth2.jwt.ReactiveJwtDecoders#fromIssuerLocation-java.lang.String-[ReactiveJwtDecoders#fromIssuerLocation] gọi endpoint Cấu hình Provider hoặc Metadata của Authorization Server để suy ra URI của JWK Set.
Nếu ứng dụng không expose bean `ReactiveJwtDecoder`, Spring Boot expose bean mặc định nêu trên.
====

Bạn có thể ghi đè cấu hình này bằng `jwkSetUri()` hoặc thay thế bằng `decoder()`.

[[webflux-oauth2resourceserver-jwt-jwkseturi-dsl]]
==== Sử dụng `jwkSetUri()`

Bạn có thể cấu hình URI của JWK Set của authorization server <<webflux-oauth2resourceserver-jwt-jwkseturi,như một configuration property>> hoặc cung cấp URI này trong DSL:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer((oauth2) -> oauth2
			.jwt((jwt) -> jwt
				.jwkSetUri("https://idp.example.com/.well-known/jwks.json")
			)
		);
	return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt {
                jwkSetUri = "https://idp.example.com/.well-known/jwks.json"
            }
        }
    }
}
----
======

Sử dụng `jwkSetUri()` được ưu tiên hơn mọi configuration property.

[[webflux-oauth2resourceserver-jwt-decoder-dsl]]
==== Sử dụng `decoder()`

`decoder()` mạnh hơn `jwkSetUri()` vì nó thay thế hoàn toàn mọi auto-configuration `JwtDecoder` của Spring Boot:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer((oauth2) -> oauth2
			.jwt((jwt) -> jwt
				.decoder(myCustomDecoder())
			)
		);
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt {
                jwtDecoder = myCustomDecoder()
            }
        }
    }
}
----
======

Điều này hữu ích khi bạn cần cấu hình sâu hơn, chẳng hạn như <<webflux-oauth2resourceserver-jwt-validation,xác thực>>.

[[webflux-oauth2resourceserver-decoder-bean]]
==== Cung cấp `ReactiveJwtDecoder` `@Bean`

Ngoài ra, expose một `ReactiveJwtDecoder` `@Bean` có tác dụng tương tự `decoder()`:
Bạn có thể tạo một decoder với `jwkSetUri` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withJwkSetUri(jwkSetUri).build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withJwkSetUri(jwkSetUri).build()
}
----
======

hoặc bạn có thể sử dụng issuer để `NimbusReactiveJwtDecoder` tra cứu `jwkSetUri` khi gọi `build()`, như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(issuer).build();
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(issuer));
    return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(issuer).build()
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(issuer))
    return jwtDecoder
}
----
======

Hoặc, nếu các giá trị mặc định phù hợp với bạn, bạn cũng có thể sử dụng `JwtDecoders`, thực hiện các thao tác trên và đồng thời cấu hình validator của decoder:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return ReactiveJwtDecoders.fromIssuerLocation(issuer);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return ReactiveJwtDecoders.fromIssuerLocation(issuer)
}
----
======

[[webflux-oauth2resourceserver-jwt-decoder-algorithm]]
== Cấu hình thuật toán đáng tin cậy

Theo mặc định, `NimbusReactiveJwtDecoder`, và do đó Resource Server, chỉ tin cậy và xác minh các token sử dụng `RS256`.

Bạn có thể tùy chỉnh hành vi này bằng <<webflux-oauth2resourceserver-jwt-boot-algorithm,Spring Boot>> hoặc sử dụng <<webflux-oauth2resourceserver-jwt-decoder-builder,builder NimbusJwtDecoder>>.

[[webflux-oauth2resourceserver-jwt-boot-algorithm]]
=== Tùy chỉnh thuật toán đáng tin cậy bằng Spring Boot

Cách đơn giản nhất để đặt thuật toán là sử dụng property:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512
          jwk-set-uri: https://idp.example.org/.well-known/jwks.json
----

[[webflux-oauth2resourceserver-jwt-decoder-builder]]
=== Tùy chỉnh thuật toán đáng tin cậy bằng Builder

Tuy nhiên, để có nhiều khả năng tùy chỉnh hơn, chúng ta có thể sử dụng một builder đi kèm `NimbusReactiveJwtDecoder`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(this.issuer)
            .jwsAlgorithm(RS512).build();
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(this.issuer));
    return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(this.issuer)
            .jwsAlgorithm(RS512).build()
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(this.issuer))
    return jwtDecoder
}
----
======

Gọi `jwsAlgorithm` nhiều hơn một lần sẽ cấu hình `NimbusReactiveJwtDecoder` tin cậy nhiều thuật toán:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(this.issuer)
            .jwsAlgorithm(RS512).jwsAlgorithm(ES512).build();
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(this.issuer));
    return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(this.issuer)
            .jwsAlgorithm(RS512).jwsAlgorithm(ES512).build()
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(this.issuer))
    return jwtDecoder
}
----
======

Ngoài ra, bạn có thể gọi `jwsAlgorithms`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(this.issuer)
            .jwsAlgorithms(algorithms -> {
                    algorithms.add(RS512);
                    algorithms.add(ES512);
            }).build();
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(this.issuer));
    return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(this.issuer)
            .jwsAlgorithms {
                it.add(RS512)
                it.add(ES512)
            }
            .build()
    jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(this.issuer))
    return jwtDecoder
}
----
======

[[webflux-oauth2resourceserver-jwt-decoder-public-key]]
=== Tin cậy một asymmetric key duy nhất

Một cách đơn giản hơn so với việc hỗ trợ Resource Server bằng endpoint JWK Set là hard-code một RSA public key.
Public key có thể được cung cấp bằng <<webflux-oauth2resourceserver-jwt-decoder-public-key-boot,Spring Boot>> hoặc <<webflux-oauth2resourceserver-jwt-decoder-public-key-builder,sử dụng Builder>>.

[[webflux-oauth2resourceserver-jwt-decoder-public-key-boot]]
==== Qua Spring Boot

Bạn có thể chỉ định một key bằng Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:my-key.pub
----

Ngoài ra, để cho phép việc tra cứu tinh vi hơn, bạn có thể post-process `RsaKeyConversionServicePostProcessor`:

.BeanFactoryPostProcessor
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
BeanFactoryPostProcessor conversionServiceCustomizer() {
    return beanFactory ->
        beanFactory.getBean(RsaKeyConversionServicePostProcessor.class)
                .setResourceLoader(new CustomResourceLoader());
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun conversionServiceCustomizer(): BeanFactoryPostProcessor {
    return BeanFactoryPostProcessor { beanFactory: ConfigurableListableBeanFactory ->
        beanFactory.getBean<RsaKeyConversionServicePostProcessor>()
                .setResourceLoader(CustomResourceLoader())
    }
}
----
======

Chỉ định vị trí của key:

[source,yaml]
----
key.location: hfds://my-key.pub
----

Sau đó autowire giá trị này:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Value("${key.location}")
RSAPublicKey key;
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Value("\${key.location}")
val key: RSAPublicKey? = null
----
======

[[webflux-oauth2resourceserver-jwt-decoder-public-key-builder]]
==== Sử dụng Builder

Để wire trực tiếp một `RSAPublicKey`, hãy sử dụng builder phù hợp của `NimbusReactiveJwtDecoder`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withPublicKey(this.key).build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withPublicKey(key).build()
}
----
======

[[webflux-oauth2resourceserver-jwt-decoder-secret-key]]
=== Tin cậy một symmetric key duy nhất

Bạn cũng có thể sử dụng một symmetric key duy nhất.
Bạn có thể nạp `SecretKey` của mình và sử dụng builder phù hợp của `NimbusReactiveJwtDecoder`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withSecretKey(this.key).build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withSecretKey(this.key).build()
}
----
======

[[webflux-oauth2resourceserver-jwt-authorization]]
=== Cấu hình authorization

JWT được phát hành từ OAuth 2.0 Authorization Server thường có một attribute `scope` hoặc `scp`, cho biết các scope (hoặc authority) đã được cấp cho nó, ví dụ:

[source,json]
----
{ ..., "scope" : "messages contacts"}
----

Trong trường hợp này, Resource Server cố gắng chuyển các scope này thành một danh sách authority được cấp, thêm tiền tố `SCOPE_` vào mỗi scope.

Điều này có nghĩa là để bảo vệ một endpoint hoặc method bằng một scope lấy từ JWT, các expression tương ứng phải bao gồm tiền tố này:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope;

@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.mvcMatchers("/contacts/**").access(hasScope("contacts"))
			.mvcMatchers("/messages/**").access(hasScope("messages"))
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(OAuth2ResourceServerSpec::jwt);
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope

@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize("/contacts/**", hasScope("contacts"))
            authorize("/messages/**", hasScope("messages"))
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt { }
        }
    }
}
----
======

Bạn có thể thực hiện tương tự với method security:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@PreAuthorize("hasAuthority('SCOPE_messages')")
public Flux<Message> getMessages(...) {}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@PreAuthorize("hasAuthority('SCOPE_messages')")
fun getMessages(): Flux<Message> { }
----
======

[[webflux-oauth2resourceserver-jwt-authorization-extraction]]
==== Trích xuất authority thủ công

Tuy nhiên, có một số trường hợp giá trị mặc định này không đủ.
Ví dụ, một số authorization server không sử dụng attribute `scope`. Thay vào đó, chúng có attribute tùy chỉnh riêng.
Trong những trường hợp khác, resource server có thể cần chuyển đổi một attribute hoặc tổ hợp các attribute thành các authority nội bộ.

Để thực hiện việc này, DSL cung cấp `jwtAuthenticationConverter()`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer((oauth2) -> oauth2
			.jwt((jwt) -> jwt
				.jwtAuthenticationConverter(grantedAuthoritiesExtractor())
			)
		);
	return http.build();
}

Converter<Jwt, Mono<AbstractAuthenticationToken>> grantedAuthoritiesExtractor() {
    JwtAuthenticationConverter jwtAuthenticationConverter =
            new JwtAuthenticationConverter();
    jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter
            (new GrantedAuthoritiesExtractor());
    return new ReactiveJwtAuthenticationConverterAdapter(jwtAuthenticationConverter);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt {
                jwtAuthenticationConverter = grantedAuthoritiesExtractor()
            }
        }
    }
}

fun grantedAuthoritiesExtractor(): Converter<Jwt, Mono<AbstractAuthenticationToken>> {
    val jwtAuthenticationConverter = JwtAuthenticationConverter()
    jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter(GrantedAuthoritiesExtractor())
    return ReactiveJwtAuthenticationConverterAdapter(jwtAuthenticationConverter)
}
----
======

`jwtAuthenticationConverter()` chịu trách nhiệm chuyển đổi một `Jwt` thành một `Authentication`.
Trong cấu hình của nó, chúng ta có thể cung cấp một converter phụ để chuyển từ `Jwt` thành một `Collection` các authority được cấp.

Converter cuối cùng đó có thể giống như `GrantedAuthoritiesExtractor` sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
static class GrantedAuthoritiesExtractor
        implements Converter<Jwt, Collection<GrantedAuthority>> {

    public Collection<GrantedAuthority> convert(Jwt jwt) {
        Collection<?> authorities = (Collection<?>)
                jwt.getClaims().getOrDefault("mycustomclaim", Collections.emptyList());

        return authorities.stream()
                .map(Object::toString)
                .map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
internal class GrantedAuthoritiesExtractor : Converter<Jwt, Collection<GrantedAuthority>> {
    override fun convert(jwt: Jwt): Collection<GrantedAuthority> {
        val authorities: List<Any> = jwt.claims
                .getOrDefault("mycustomclaim", emptyList<Any>()) as List<Any>
        return authorities
                .map { it.toString() }
                .map { SimpleGrantedAuthority(it) }
    }
}
----
======

Để linh hoạt hơn, DSL hỗ trợ thay thế hoàn toàn converter bằng bất kỳ class nào triển khai `Converter<Jwt, Mono<AbstractAuthenticationToken>>`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
static class CustomAuthenticationConverter implements Converter<Jwt, Mono<AbstractAuthenticationToken>> {
    public AbstractAuthenticationToken convert(Jwt jwt) {
        return Mono.just(jwt).map(this::doConversion);
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
internal class CustomAuthenticationConverter : Converter<Jwt, Mono<AbstractAuthenticationToken>> {
    override fun convert(jwt: Jwt): Mono<AbstractAuthenticationToken> {
        return Mono.just(jwt).map(this::doConversion)
    }
}
----
======

[[webflux-oauth2resourceserver-jwt-validation]]
=== Cấu hình validation

Khi sử dụng <<webflux-oauth2resourceserver-jwt-minimalconfiguration,cấu hình Spring Boot tối thiểu>> và chỉ định issuer URI của authorization server, theo mặc định Resource Server sẽ xác minh claim `iss` cũng như các claim timestamp `exp` và `nbf`.

Trong trường hợp cần tùy chỉnh việc validation, Resource Server cung cấp hai validator tiêu chuẩn và cũng chấp nhận các instance `OAuth2TokenValidator` tùy chỉnh.

[[webflux-oauth2resourceserver-jwt-validation-clockskew]]
==== Tùy chỉnh validation timestamp

Các instance JWT thường có một khoảng thời gian hợp lệ, trong đó thời điểm bắt đầu được chỉ ra trong claim `nbf` và thời điểm kết thúc được chỉ ra trong claim `exp`.

Tuy nhiên, mọi server đều có thể gặp clock drift, khiến token có vẻ hết hạn trên server này nhưng chưa hết hạn trên server khác.
Điều này có thể gây khó khăn trong triển khai khi số lượng server phối hợp với nhau trong một hệ thống phân tán tăng lên.

Resource Server sử dụng `JwtTimestampValidator` để xác minh khoảng thời gian hợp lệ của token, và bạn có thể cấu hình nó với `clockSkew` để giảm vấn đề clock drift:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
     NimbusReactiveJwtDecoder jwtDecoder = (NimbusReactiveJwtDecoder)
             ReactiveJwtDecoders.fromIssuerLocation(issuerUri);

     OAuth2TokenValidator<Jwt> withClockSkew = new DelegatingOAuth2TokenValidator<>(
            new JwtTimestampValidator(Duration.ofSeconds(60)),
            new IssuerValidator(issuerUri));

     jwtDecoder.setJwtValidator(withClockSkew);

     return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = ReactiveJwtDecoders.fromIssuerLocation(issuerUri) as NimbusReactiveJwtDecoder
    val withClockSkew: OAuth2TokenValidator<Jwt> = DelegatingOAuth2TokenValidator(
            JwtTimestampValidator(Duration.ofSeconds(60)),
            JwtIssuerValidator(issuerUri))
    jwtDecoder.setJwtValidator(withClockSkew)
    return jwtDecoder
}
----
======

[NOTE]
====
Theo mặc định, Resource Server cấu hình clock skew là 60 giây.
====

[[webflux-oauth2resourceserver-validation-rfc9068]]
=== Cấu hình validation RFC 9068

Nếu cần yêu cầu các token đáp ứng https://datatracker.ietf.org/doc/rfc9068/[RFC 9068], bạn có thể cấu hình validation như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
JwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(issuerUri)
            .validateTypes(false).build();
    jwtDecoder.setJwtValidator(JwtValidators.createAtJwtValidator()
            .audience("https://audience.example.org")
            .clientId("client-identifier")
            .issuer("https://issuer.example.org").build());
     return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): JwtDecoder {
    val jwtDecoder = NimbusReactiveJwtDecoder.withIssuerLocation(issuerUri)
            .validateTypes(false).build()
    jwtDecoder.setJwtValidator(JwtValidators.createAtJwtValidator()
            .audience("https://audience.example.org")
            .clientId("client-identifier")
            .issuer("https://issuer.example.org").build())
    return jwtDecoder
}
----
======

[[webflux-oauth2resourceserver-validation-custom]]
==== Cấu hình validator tùy chỉnh

Bạn có thể thêm bước kiểm tra claim `aud` bằng API `OAuth2TokenValidator`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class AudienceValidator implements OAuth2TokenValidator<Jwt> {
    OAuth2Error error = new OAuth2Error("invalid_token", "The required audience is missing", null);

    public OAuth2TokenValidatorResult validate(Jwt jwt) {
        if (jwt.getAudience().contains("messaging")) {
            return OAuth2TokenValidatorResult.success();
        } else {
            return OAuth2TokenValidatorResult.failure(error);
        }
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class AudienceValidator : OAuth2TokenValidator<Jwt> {
    var error: OAuth2Error = OAuth2Error("invalid_token", "The required audience is missing", null)
    override fun validate(jwt: Jwt): OAuth2TokenValidatorResult {
        return if (jwt.audience.contains("messaging")) {
            OAuth2TokenValidatorResult.success()
        } else {
            OAuth2TokenValidatorResult.failure(error)
        }
    }
}
----
======

Sau đó, để thêm validator vào một Resource Server, bạn có thể chỉ định instance `ReactiveJwtDecoder`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = (NimbusReactiveJwtDecoder)
            ReactiveJwtDecoders.fromIssuerLocation(issuerUri);

    OAuth2TokenValidator<Jwt> audienceValidator = new AudienceValidator();
    OAuth2TokenValidator<Jwt> withIssuer = JwtValidators.createDefaultWithIssuer(issuerUri);
    OAuth2TokenValidator<Jwt> withAudience = new DelegatingOAuth2TokenValidator<>(withIssuer, audienceValidator);

    jwtDecoder.setJwtValidator(withAudience);

    return jwtDecoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = ReactiveJwtDecoders.fromIssuerLocation(issuerUri) as NimbusReactiveJwtDecoder
    val audienceValidator: OAuth2TokenValidator<Jwt> = AudienceValidator()
    val withIssuer: OAuth2TokenValidator<Jwt> = JwtValidators.createDefaultWithIssuer(issuerUri)
    val withAudience: OAuth2TokenValidator<Jwt> = DelegatingOAuth2TokenValidator(withIssuer, audienceValidator)
    jwtDecoder.setJwtValidator(withAudience)
    return jwtDecoder
}
----
======
