= Đa tenant của OAuth 2.0 Resource Server

[[webflux-oauth2resourceserver-multitenancy]]
== Đa tenant

Một Resource Server được xem là đa tenant khi có nhiều strategy để xác minh Bearer Token, được định danh bằng một tenant identifier nào đó.

Ví dụ, Resource Server của bạn có thể chấp nhận Bearer Token từ hai Authorization Server khác nhau.
Hoặc Authorization Server của bạn có thể đại diện cho nhiều issuer.

Trong mỗi trường hợp, cần thực hiện hai việc và cách bạn chọn thực hiện chúng sẽ đi kèm với các đánh đổi:

. Phân giải tenant.
. Truyền tenant.

=== Phân giải tenant bằng claim

Một cách để phân biệt các tenant là sử dụng issuer claim. Vì issuer claim đi kèm với JWT đã ký, bạn có thể thực hiện việc này bằng `JwtIssuerReactiveAuthenticationManagerResolver`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
JwtIssuerReactiveAuthenticationManagerResolver authenticationManagerResolver = JwtIssuerReactiveAuthenticationManagerResolver
    .fromTrustedIssuers("https://idp.example.org/issuerOne", "https://idp.example.org/issuerTwo");

http
    .authorizeExchange((authorize) -> authorize
        .anyExchange().authenticated()
    )
    .oauth2ResourceServer((oauth2) -> oauth2
        .authenticationManagerResolver(authenticationManagerResolver)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val customAuthenticationManagerResolver = JwtIssuerReactiveAuthenticationManagerResolver
    .fromTrustedIssuers("https://idp.example.org/issuerOne", "https://idp.example.org/issuerTwo")

return http {
    authorizeExchange {
        authorize(anyExchange, authenticated)
    }
    oauth2ResourceServer {
        authenticationManagerResolver = customAuthenticationManagerResolver
    }
}
----
======

Điều này hữu ích vì các issuer endpoint được tải lazy.
Trên thực tế, `JwtReactiveAuthenticationManager` tương ứng chỉ được khởi tạo khi request đầu tiên với issuer tương ứng được gửi đi.
Điều này cho phép ứng dụng khởi động mà không phụ thuộc vào việc các Authorization Server đó đang hoạt động và sẵn sàng.

==== Tenant động

Bạn có thể không muốn khởi động lại ứng dụng mỗi khi thêm tenant mới.
Trong trường hợp này, bạn có thể cấu hình `JwtIssuerReactiveAuthenticationManagerResolver` với một repository chứa các instance `ReactiveAuthenticationManager`, repository này có thể được chỉnh sửa trong runtime:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
private Mono<ReactiveAuthenticationManager> addManager(
		Map<String, ReactiveAuthenticationManager> authenticationManagers, String issuer) {

	return Mono.fromCallable(() -> ReactiveJwtDecoders.fromIssuerLocation(issuer))
            .subscribeOn(Schedulers.boundedElastic())
            .map(JwtReactiveAuthenticationManager::new)
            .doOnNext((authenticationManager) -> authenticationManager.put(issuer, authenticationManager));
}

// ...

JwtIssuerReactiveAuthenticationManagerResolver authenticationManagerResolver =
        new JwtIssuerReactiveAuthenticationManagerResolver(authenticationManagers::get);

http
    .authorizeExchange((authorize) -> authorize
        .anyExchange().authenticated()
    )
    .oauth2ResourceServer((oauth2) -> oauth2
        .authenticationManagerResolver(authenticationManagerResolver)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
private fun addManager(
        authenticationManagers: MutableMap<String, ReactiveAuthenticationManager>, issuer: String): Mono<JwtReactiveAuthenticationManager> {
    return Mono.fromCallable { ReactiveJwtDecoders.fromIssuerLocation(issuer) }
            .subscribeOn(Schedulers.boundedElastic())
            .map { jwtDecoder: ReactiveJwtDecoder -> JwtReactiveAuthenticationManager(jwtDecoder) }
            .doOnNext { authenticationManager: JwtReactiveAuthenticationManager -> authenticationManagers[issuer] = authenticationManager }
}

// ...

var customAuthenticationManagerResolver = JwtIssuerReactiveAuthenticationManagerResolver(authenticationManagers::get)
return http {
    authorizeExchange {
        authorize(anyExchange, authenticated)
    }
    oauth2ResourceServer {
        authenticationManagerResolver = customAuthenticationManagerResolver
    }
}
----
======

Trong trường hợp này, bạn khởi tạo `JwtIssuerReactiveAuthenticationManagerResolver` với một strategy để lấy `ReactiveAuthenticationManager` tương ứng với issuer.
Cách tiếp cận này cho phép chúng ta thêm và xóa các phần tử khỏi repository (được thể hiện dưới dạng `Map` trong snippet trước đó) trong runtime.

[NOTE]
====
Sẽ không an toàn nếu đơn giản lấy bất kỳ issuer nào và khởi tạo một `ReactiveAuthenticationManager` từ issuer đó.
Issuer phải là giá trị mà code có thể xác minh từ một nguồn đáng tin cậy, chẳng hạn như danh sách issuer được cho phép.
====
