= Opaque Token của Resource Server OAuth 2.0

[[webflux-oauth2resourceserver-opaque-minimaldependencies]]
== Dependency tối thiểu cho Introspection
Như được mô tả trong xref:servlet/oauth2/resource-server/jwt.adoc#oauth2resourceserver-jwt-minimaldependencies[Dependency tối thiểu cho JWT], phần lớn hỗ trợ cho Resource Server được tập hợp trong `spring-security-oauth2-resource-server`.
Tuy nhiên, trừ khi bạn cung cấp một <<webflux-oauth2resourceserver-opaque-introspector-bean,`ReactiveOpaqueTokenIntrospector`>> tùy chỉnh, Resource Server sẽ chuyển sang dùng `SpringReactiveOpaqueTokenIntrospector`.
Điều này có nghĩa là chỉ cần `spring-security-oauth2-resource-server` để có một Resource Server tối thiểu hoạt động và hỗ trợ opaque Bearer Token.

[[webflux-oauth2resourceserver-opaque-minimalconfiguration]]
== Cấu hình tối thiểu cho Introspection

Thông thường, bạn có thể xác minh một opaque token bằng https://tools.ietf.org/html/rfc7662[OAuth 2.0 Introspection Endpoint] do authorization server lưu trữ.
Điều này hữu ích khi việc thu hồi token là một yêu cầu.

Khi sử dụng https://spring.io/projects/spring-boot[Spring Boot], việc cấu hình một ứng dụng thành resource server sử dụng introspection gồm hai bước:

. Thêm các dependency cần thiết.
. Chỉ ra thông tin chi tiết của introspection endpoint.

[[webflux-oauth2resourceserver-opaque-introspectionuri]]
=== Chỉ định Authorization Server

Bạn có thể chỉ định vị trí của introspection endpoint:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://idp.example.com/introspect
          client-id: client
          client-secret: secret
----

Trong đó, `https://idp.example.com/introspect` là introspection endpoint do authorization server của bạn lưu trữ, còn `client-id` và `client-secret` là các credential cần thiết để truy cập endpoint đó.

Resource Server sử dụng các property này để tự cấu hình thêm, sau đó xác thực các JWT đến.

[NOTE]
====
Nếu authorization server phản hồi rằng token hợp lệ thì token đó hợp lệ.
====

=== Hành vi khi khởi động

Khi sử dụng property và các dependency này, Resource Server tự động cấu hình để xác thực Opaque Bearer Token.

Quy trình khởi động này đơn giản hơn khá nhiều so với JWT, vì không cần discovery endpoint và cũng không thêm quy tắc xác thực nào.

=== Hành vi khi chạy

Sau khi ứng dụng khởi động, Resource Server cố gắng xử lý mọi request chứa header `Authorization: Bearer`:

[source,http]
----
GET / HTTP/1.1
Authorization: Bearer some-token-value # Resource Server will process this
----

Miễn là scheme này được chỉ định, Resource Server cố gắng xử lý request theo đặc tả Bearer Token.

Với một Opaque Token, Resource Server sẽ:

. Truy vấn introspection endpoint được cung cấp bằng credential được cung cấp và token.
. Kiểm tra response để tìm attribute `{ 'active' : true }`.
. Ánh xạ mỗi scope thành một authority với tiền tố `SCOPE_`.

Theo mặc định, `Authentication#getPrincipal` nhận được là một object javadoc:org.springframework.security.oauth2.core.OAuth2AuthenticatedPrincipal[] của Spring Security, còn `Authentication#getName` ánh xạ đến property `sub` của token nếu property này tồn tại.

Từ đây, bạn có thể chuyển đến:

* <<webflux-oauth2resourceserver-opaque-attributes>>
* <<webflux-oauth2resourceserver-opaque-authorization-extraction>>
* <<webflux-oauth2resourceserver-opaque-jwt-introspector>>

[[webflux-oauth2resourceserver-opaque-attributes]]
== Tra cứu Attribute sau Authentication

Sau khi token được authentication, một instance của `BearerTokenAuthentication` được đặt trong `SecurityContext`.

Điều này có nghĩa là nó khả dụng trong các method `@Controller` khi bạn sử dụng `@EnableWebFlux` trong cấu hình:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/foo")
public Mono<String> foo(BearerTokenAuthentication authentication) {
    return Mono.just(authentication.getTokenAttributes().get("sub") + " is the subject");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/foo")
fun foo(authentication: BearerTokenAuthentication): Mono<String> {
    return Mono.just(authentication.tokenAttributes["sub"].toString() + " is the subject")
}
----
======

Vì `BearerTokenAuthentication` chứa một `OAuth2AuthenticatedPrincipal`, điều đó cũng có nghĩa là nó khả dụng trong các method của controller:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/foo")
public Mono<String> foo(@AuthenticationPrincipal OAuth2AuthenticatedPrincipal principal) {
    return Mono.just(principal.getAttribute("sub") + " is the subject");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/foo")
fun foo(@AuthenticationPrincipal principal: OAuth2AuthenticatedPrincipal): Mono<String> {
    return Mono.just(principal.getAttribute<Any>("sub").toString() + " is the subject")
}
----
======

=== Tra cứu Attribute bằng SpEL

Bạn có thể truy cập attribute bằng Spring Expression Language (SpEL).

Ví dụ, nếu bạn sử dụng `@EnableReactiveMethodSecurity` để có thể dùng annotation `@PreAuthorize`, bạn có thể viết:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@PreAuthorize("principal?.attributes['sub'] = 'foo'")
public Mono<String> forFoosEyesOnly() {
    return Mono.just("foo");
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@PreAuthorize("principal.attributes['sub'] = 'foo'")
fun forFoosEyesOnly(): Mono<String> {
    return Mono.just("foo")
}
----
======

[[webflux-oauth2resourceserver-opaque-sansboot]]
== Ghi đè hoặc thay thế Auto-configuration của Boot

Spring Boot tạo hai instance `@Bean` cho Resource Server.

Bean đầu tiên là một `SecurityWebFilterChain` cấu hình ứng dụng thành resource server.
Khi sử dụng Opaque Token, `SecurityWebFilterChain` này có dạng:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange((authorize) -> authorize
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(ServerHttpSecurity.OAuth2ResourceServerSpec::opaqueToken)
	return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            opaqueToken { }
        }
    }
}
----
======

Nếu ứng dụng không expose bean `SecurityWebFilterChain`, Spring Boot expose bean mặc định (được hiển thị trong listing trước đó).

Bạn có thể thay thế bean này bằng cách expose bean trong ứng dụng:

.Thay thế SecurityWebFilterChain
[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope;

@Configuration
@EnableWebFluxSecurity
public class MyCustomSecurityConfiguration {
    @Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
            .authorizeExchange((authorize) -> authorize
                .pathMatchers("/messages/**").access(hasScope("message:read"))
                .anyExchange().authenticated()
            )
            .oauth2ResourceServer((oauth2) -> oauth2
                .opaqueToken((opaqueToken) -> opaqueToken
                    .introspector(myIntrospector())
                )
            );
        return http.build();
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope

@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize("/messages/**", hasScope("message:read"))
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            opaqueToken {
                introspector = myIntrospector()
            }
        }
    }
}
----
======

Ví dụ trước yêu cầu scope `message:read` cho mọi URL bắt đầu bằng `/messages/`.

Các method trên DSL `oauth2ResourceServer` cũng ghi đè hoặc thay thế auto-configuration.

Ví dụ, `@Bean` thứ hai mà Spring Boot tạo là một `ReactiveOpaqueTokenIntrospector`, dùng để giải mã token `String` thành các instance đã được xác thực của `OAuth2AuthenticatedPrincipal`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOpaqueTokenIntrospector introspector() {
    return SpringReactiveOpaqueTokenIntrospector.withIntrospectionUri(introspectionUri)
        .clientId(clientId).clientSecret(clientSecret).build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun introspector(): ReactiveOpaqueTokenIntrospector {
    return SpringReactiveOpaqueTokenIntrospector.withIntrospectionUri(introspectionUri)
        .clientId(clientId).clientSecret(clientSecret).build()
}
----
======

Nếu ứng dụng không expose bean `ReactiveOpaqueTokenIntrospector`, Spring Boot expose bean mặc định (được hiển thị trong listing trước đó).

Bạn có thể ghi đè cấu hình của nó bằng `introspectionUri()` và `introspectionClientCredentials()`, hoặc thay thế nó bằng `introspector()`.

[[webflux-oauth2resourceserver-opaque-introspectionuri-dsl]]
=== Sử dụng `introspectionUri()`

Bạn có thể cấu hình Introspection URI của authorization server <<webflux-oauth2resourceserver-opaque-introspectionuri,như một configuration property>>, hoặc cung cấp trong DSL:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class DirectlyConfiguredIntrospectionUri {
    @Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
            .authorizeExchange((authorize) -> authorize
                .anyExchange().authenticated()
            )
            .oauth2ResourceServer((oauth2) -> oauth2
                .opaqueToken((opaqueToken) -> opaqueToken
                    .introspectionUri("https://idp.example.com/introspect")
                    .introspectionClientCredentials("client", "secret")
                )
            );
        return http.build();
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            opaqueToken {
                introspectionUri = "https://idp.example.com/introspect"
                introspectionClientCredentials("client", "secret")
            }
        }
    }
}
----
======

`introspectionUri()` được ưu tiên hơn mọi configuration property.

[[webflux-oauth2resourceserver-opaque-introspector-dsl]]
=== Sử dụng `introspector()`

`introspector()` mạnh hơn `introspectionUri()`. Nó hoàn toàn thay thế mọi auto-configuration của Boot đối với `ReactiveOpaqueTokenIntrospector`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class DirectlyConfiguredIntrospector {
    @Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
            .authorizeExchange((authorize) -> authorize
                .anyExchange().authenticated()
            )
            .oauth2ResourceServer((oauth2) -> oauth2
                .opaqueToken((opaqueToken) -> opaqueToken
                    .introspector(myCustomIntrospector())
                )
            );
        return http.build();
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            opaqueToken {
                introspector = myCustomIntrospector()
            }
        }
    }
}
----
======

Điều này hữu ích khi cần cấu hình chuyên sâu hơn, chẳng hạn như <<webflux-oauth2resourceserver-opaque-authorization-extraction,ánh xạ authority>> hoặc <<webflux-oauth2resourceserver-opaque-jwt-introspector,thu hồi JWT>>.

[[webflux-oauth2resourceserver-opaque-introspector-bean]]
=== Expose `@Bean` `ReactiveOpaqueTokenIntrospector`

Hoặc việc expose `@Bean` `ReactiveOpaqueTokenIntrospector` có tác dụng tương tự như `introspector()`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOpaqueTokenIntrospector introspector() {
    return SpringReactiveOpaqueTokenIntrospector.withIntrospectionUri(introspectionUri)
        .clientId(clientId).clientSecret(clientSecret).build()
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun introspector(): ReactiveOpaqueTokenIntrospector {
    return SpringReactiveOpaqueTokenIntrospector.withIntrospectionUri(introspectionUri)
        .clientId(clientId).clientSecret(clientSecret).build()
}
----
======

[[webflux-oauth2resourceserver-opaque-authorization]]
== Cấu hình Authorization

Một OAuth 2.0 Introspection endpoint thường trả về attribute `scope`, cho biết các scope (hoặc authority) đã được cấp -- ví dụ:

[source,json]
----
{ ..., "scope" : "messages contacts"}
----

Trong trường hợp này, Resource Server cố gắng chuyển các scope này thành một danh sách authority được cấp, thêm tiền tố `SCOPE_` vào mỗi scope.

Điều này có nghĩa là để bảo vệ một endpoint hoặc method bằng scope lấy từ Opaque Token, các expression tương ứng phải bao gồm tiền tố này:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope;

@Configuration
@EnableWebFluxSecurity
public class MappedAuthorities {
    @Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
            .authorizeExchange((authorize) -> authorize
                .pathMatchers("/contacts/**").access(hasScope("contacts"))
                .pathMatchers("/messages/**").access(hasScope("messages"))
                .anyExchange().authenticated()
            )
            .oauth2ResourceServer(ServerHttpSecurity.OAuth2ResourceServerSpec::opaqueToken);
        return http.build();
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.core.authorization.OAuth2ReactiveAuthorizationManagers.hasScope

@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize("/contacts/**", hasScope("contacts"))
            authorize("/messages/**", hasScope("messages"))
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            opaqueToken { }
        }
    }
}
----
======

Bạn có thể làm điều tương tự với method security:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@PreAuthorize("hasAuthority('SCOPE_messages')")
public Flux<Message> getMessages(...) {}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@PreAuthorize("hasAuthority('SCOPE_messages')")
fun getMessages(): Flux<Message> { }
----
======

[[webflux-oauth2resourceserver-opaque-authorization-extraction]]
=== Trích xuất Authority thủ công

Theo mặc định, hỗ trợ Opaque Token trích xuất claim scope từ introspection response và phân tích nó thành các instance `GrantedAuthority` riêng lẻ.

Hãy xem ví dụ sau:

[source,json]
----
{
    "active" : true,
    "scope" : "message:read message:write"
}
----

Nếu introspection response giống như ví dụ trước, Resource Server sẽ tạo một `Authentication` với hai authority, một cho `message:read` và một cho `message:write`.

Bạn có thể tùy chỉnh hành vi bằng cách sử dụng một `ReactiveOpaqueTokenIntrospector` tùy chỉnh, xem xét tập hợp attribute và chuyển đổi theo cách riêng:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class CustomAuthoritiesOpaqueTokenIntrospector implements ReactiveOpaqueTokenIntrospector {
    private ReactiveOpaqueTokenIntrospector delegate = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build();

    public Mono<OAuth2AuthenticatedPrincipal> introspect(String token) {
        return this.delegate.introspect(token)
                .map((principal) -> principal DefaultOAuth2AuthenticatedPrincipal(
                        principal.getName(), principal.getAttributes(), extractAuthorities(principal)));
    }

    private Collection<GrantedAuthority> extractAuthorities(OAuth2AuthenticatedPrincipal principal) {
        List<String> scopes = principal.getAttribute(OAuth2IntrospectionClaimNames.SCOPE);
        return scopes.stream()
                .map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class CustomAuthoritiesOpaqueTokenIntrospector : ReactiveOpaqueTokenIntrospector {
    private val delegate: ReactiveOpaqueTokenIntrospector = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build()
    override fun introspect(token: String): Mono<OAuth2AuthenticatedPrincipal> {
        return delegate.introspect(token)
                .map { principal: OAuth2AuthenticatedPrincipal ->
                    DefaultOAuth2AuthenticatedPrincipal(
                            principal.name, principal.attributes, extractAuthorities(principal))
                }
    }

    private fun extractAuthorities(principal: OAuth2AuthenticatedPrincipal): Collection<GrantedAuthority> {
        val scopes = principal.getAttribute<List<String>>(OAuth2IntrospectionClaimNames.SCOPE)
        return scopes
                .map { SimpleGrantedAuthority(it) }
    }
}
----
======

Sau đó, bạn có thể cấu hình introspector tùy chỉnh này bằng cách expose nó dưới dạng `@Bean`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOpaqueTokenIntrospector introspector() {
    return new CustomAuthoritiesOpaqueTokenIntrospector();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun introspector(): ReactiveOpaqueTokenIntrospector {
    return CustomAuthoritiesOpaqueTokenIntrospector()
}
----
======

[[webflux-oauth2resourceserver-opaque-jwt-introspector]]
== Sử dụng Introspection với JWT

Một câu hỏi thường gặp là liệu introspection có tương thích với JWT hay không.
Hỗ trợ Opaque Token của Spring Security được thiết kế để không quan tâm đến định dạng của token. Nó sẵn sàng chuyển bất kỳ token nào đến introspection endpoint được cung cấp.

Vì vậy, giả sử bạn cần kiểm tra với authorization server trong mỗi request, phòng trường hợp JWT đã bị thu hồi.

Mặc dù bạn sử dụng định dạng JWT cho token, phương thức xác thực của bạn là introspection, nghĩa là bạn sẽ thực hiện như sau:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://idp.example.org/introspection
          client-id: client
          client-secret: secret
----

Trong trường hợp này, `Authentication` nhận được sẽ là `BearerTokenAuthentication`.
Mọi attribute trong `OAuth2AuthenticatedPrincipal` tương ứng sẽ là những gì được introspection endpoint trả về.

Tuy nhiên, giả sử vì lý do nào đó introspection endpoint chỉ trả về việc token có active hay không.
Khi đó thì sao?

Trong trường hợp này, bạn có thể tạo một `ReactiveOpaqueTokenIntrospector` tùy chỉnh vẫn truy cập endpoint, nhưng sau đó cập nhật principal được trả về để có các claim của JWT làm attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class JwtOpaqueTokenIntrospector implements ReactiveOpaqueTokenIntrospector {
	private ReactiveOpaqueTokenIntrospector delegate = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build();
	private ReactiveJwtDecoder jwtDecoder = new NimbusReactiveJwtDecoder(new ParseOnlyJWTProcessor());

	public Mono<OAuth2AuthenticatedPrincipal> introspect(String token) {
		return this.delegate.introspect(token)
				.flatMap((principal) -> principal.jwtDecoder.decode(token))
				.map((jwt) -> jwt DefaultOAuth2AuthenticatedPrincipal(jwt.getClaims(), NO_AUTHORITIES));
	}

	private static class ParseOnlyJWTProcessor implements Converter<JWT, Mono<JWTClaimsSet>> {
		public Mono<JWTClaimsSet> convert(JWT jwt) {
			try {
				return Mono.just(jwt.getJWTClaimsSet());
			} catch (Exception ex) {
				return Mono.error(ex);
			}
		}
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class JwtOpaqueTokenIntrospector : ReactiveOpaqueTokenIntrospector {
    private val delegate: ReactiveOpaqueTokenIntrospector = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build()
    private val jwtDecoder: ReactiveJwtDecoder = NimbusReactiveJwtDecoder(ParseOnlyJWTProcessor())
    override fun introspect(token: String): Mono<OAuth2AuthenticatedPrincipal> {
        return delegate.introspect(token)
                .flatMap { jwtDecoder.decode(token) }
                .map { jwt: Jwt -> DefaultOAuth2AuthenticatedPrincipal(jwt.claims, NO_AUTHORITIES) }
    }

    private class ParseOnlyJWTProcessor : Converter<JWT, Mono<JWTClaimsSet>> {
        override fun convert(jwt: JWT): Mono<JWTClaimsSet> {
            return try {
                Mono.just(jwt.jwtClaimsSet)
            } catch (e: Exception) {
                Mono.error(e)
            }
        }
    }
}
----
======

Sau đó, bạn có thể cấu hình introspector tùy chỉnh này bằng cách expose nó dưới dạng `@Bean`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveOpaqueTokenIntrospector introspector() {
    return new JwtOpaqueTokenIntropsector();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun introspector(): ReactiveOpaqueTokenIntrospector {
    return JwtOpaqueTokenIntrospector()
}
----
======

[[webflux-oauth2resourceserver-opaque-userinfo]]
== Gọi Endpoint `/userinfo`

Nói chung, Resource Server không quan tâm đến user bên dưới mà quan tâm đến các authority đã được cấp.

Tuy vậy, đôi khi việc liên kết phát biểu authorization trở lại với một user có thể hữu ích.

Nếu một ứng dụng cũng sử dụng `spring-security-oauth2-client` và đã thiết lập `ClientRegistrationRepository` phù hợp, bạn có thể thực hiện việc này bằng một `OpaqueTokenIntrospector` tùy chỉnh.
Phần triển khai trong listing tiếp theo thực hiện ba việc:

* Ủy quyền cho introspection endpoint để xác nhận tính hợp lệ của token.
* Tra cứu client registration phù hợp liên kết với endpoint `/userinfo`.
* Gọi và trả về response từ endpoint `/userinfo`.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class UserInfoOpaqueTokenIntrospector implements ReactiveOpaqueTokenIntrospector {
	private final ReactiveOpaqueTokenIntrospector delegate = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build();
	private final ReactiveOAuth2UserService<OAuth2UserRequest, OAuth2User> oauth2UserService =
			new DefaultReactiveOAuth2UserService();

	private final ReactiveClientRegistrationRepository repository;

	// ... constructor

	@Override
	public Mono<OAuth2AuthenticatedPrincipal> introspect(String token) {
		return Mono.zip(this.delegate.introspect(token), this.repository.findByRegistrationId("registration-id"))
				.map(t -> {
					OAuth2AuthenticatedPrincipal authorized = t.getT1();
					ClientRegistration clientRegistration = t.getT2();
					Instant issuedAt = authorized.getAttribute(ISSUED_AT);
					Instant expiresAt = authorized.getAttribute(OAuth2IntrospectionClaimNames.EXPIRES_AT);
					OAuth2AccessToken accessToken = new OAuth2AccessToken(BEARER, token, issuedAt, expiresAt);
					return new OAuth2UserRequest(clientRegistration, accessToken);
				})
				.flatMap(this.oauth2UserService::loadUser);
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class UserInfoOpaqueTokenIntrospector : ReactiveOpaqueTokenIntrospector {
    private val delegate: ReactiveOpaqueTokenIntrospector = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build()
    private val oauth2UserService: ReactiveOAuth2UserService<OAuth2UserRequest, OAuth2User> = DefaultReactiveOAuth2UserService()
    private val repository: ReactiveClientRegistrationRepository? = null

    // ... constructor
    override fun introspect(token: String?): Mono<OAuth2AuthenticatedPrincipal> {
        return Mono.zip<OAuth2AuthenticatedPrincipal, ClientRegistration>(delegate.introspect(token), repository!!.findByRegistrationId("registration-id"))
                .map<OAuth2UserRequest> { t: Tuple2<OAuth2AuthenticatedPrincipal, ClientRegistration> ->
                    val authorized = t.t1
                    val clientRegistration = t.t2
                    val issuedAt: Instant? = authorized.getAttribute(ISSUED_AT)
                    val expiresAt: Instant? = authorized.getAttribute(OAuth2IntrospectionClaimNames.EXPIRES_AT)
                    val accessToken = OAuth2AccessToken(BEARER, token, issuedAt, expiresAt)
                    OAuth2UserRequest(clientRegistration, accessToken)
                }
                .flatMap { userRequest: OAuth2UserRequest -> oauth2UserService.loadUser(userRequest) }
    }
}
----
======

Nếu bạn không sử dụng `spring-security-oauth2-client` thì việc này vẫn khá đơn giản.
Bạn chỉ cần gọi `/userinfo` bằng instance `WebClient` của riêng mình:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class UserInfoOpaqueTokenIntrospector implements ReactiveOpaqueTokenIntrospector {
    private final ReactiveOpaqueTokenIntrospector delegate = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build();
    private final WebClient rest = WebClient.create();

    @Override
    public Mono<OAuth2AuthenticatedPrincipal> introspect(String token) {
        return this.delegate.introspect(token)
		        .map(this::makeUserInfoRequest);
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class UserInfoOpaqueTokenIntrospector : ReactiveOpaqueTokenIntrospector {
    private val delegate: ReactiveOpaqueTokenIntrospector = SpringReactiveOpaqueTokenIntrospector
            .withIntrospectionUri("https://idp.example.org/introspect")
            .clientId("client").clientSecret("secret").build()
    private val rest: WebClient = WebClient.create()

    override fun introspect(token: String): Mono<OAuth2AuthenticatedPrincipal> {
        return delegate.introspect(token)
                .map(this::makeUserInfoRequest)
    }
}
----
======

Dù theo cách nào, sau khi tạo `ReactiveOpaqueTokenIntrospector`, bạn nên expose nó dưới dạng `@Bean` để ghi đè các giá trị mặc định:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ReactiveOpaqueTokenIntrospector introspector() {
    return new UserInfoOpaqueTokenIntrospector();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun introspector(): ReactiveOpaqueTokenIntrospector {
    return UserInfoOpaqueTokenIntrospector()
}
----
======
