[[jc-webflux]]
= Bảo mật WebFlux

Hỗ trợ WebFlux của Spring Security dựa trên một `WebFilter` và hoạt động giống nhau trên cả Spring WebFlux và Spring WebFlux.Fn.
Một vài sample application minh họa code:

* Hello WebFlux {gh-samples-url}/reactive/webflux/java/hello-security[hellowebflux]
* Hello WebFlux.Fn {gh-samples-url}/reactive/webflux-fn/hello-security[hellowebfluxfn]
* Hello WebFlux Method {gh-samples-url}/reactive/webflux/java/method[hellowebflux-method]


== Cấu hình bảo mật WebFlux tối thiểu

Đoạn mã sau đây trình bày một cấu hình bảo mật WebFlux tối thiểu:

.Cấu hình bảo mật WebFlux tối thiểu
[tabs]
======
Java::
+
[source,java,role="primary"]
-----
@Configuration
@EnableWebFluxSecurity
public class HelloWebfluxSecurityConfig {

	@Bean
	public MapReactiveUserDetailsService userDetailsService() {
		UserDetails user = User.withDefaultPasswordEncoder()
			.username("user")
			.password("user")
			.roles("USER")
			.build();
		return new MapReactiveUserDetailsService(user);
	}
}
-----

Kotlin::
+
[source,kotlin,role="secondary"]
-----
@Configuration
@EnableWebFluxSecurity
class HelloWebfluxSecurityConfig {

    @Bean
    fun userDetailsService(): ReactiveUserDetailsService {
        val userDetails = User.withDefaultPasswordEncoder()
                .username("user")
                .password("user")
                .roles("USER")
                .build()
        return MapReactiveUserDetailsService(userDetails)
    }
}
-----
======

Cấu hình này cung cấp authentication bằng form và HTTP Basic, thiết lập authorization để yêu cầu user đã authenticated khi truy cập mọi page, thiết lập trang đăng nhập mặc định và trang đăng xuất mặc định, thiết lập các HTTP security header, thêm bảo vệ CSRF và nhiều chức năng khác.

== Cấu hình bảo mật WebFlux tường minh

Phần sau đây trình bày phiên bản tường minh của cấu hình bảo mật WebFlux tối thiểu:

.Cấu hình bảo mật WebFlux tường minh
[tabs]
======
Java::
+
[source,java,role="primary"]
-----
@Configuration
@EnableWebFluxSecurity
public class HelloWebfluxSecurityConfig {

	@Bean
	public MapReactiveUserDetailsService userDetailsService() {
		UserDetails user = User.withDefaultPasswordEncoder()
			.username("user")
			.password("user")
			.roles("USER")
			.build();
		return new MapReactiveUserDetailsService(user);
	}

	@Bean
	public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
			    .anyExchange().authenticated()
			)
			.httpBasic(withDefaults())
			.formLogin(withDefaults());
		return http.build();
	}
}
-----

Kotlin::
+
[source,kotlin,role="secondary"]
-----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
class HelloWebfluxSecurityConfig {

    @Bean
    fun userDetailsService(): ReactiveUserDetailsService {
        val userDetails = User.withDefaultPasswordEncoder()
                .username("user")
                .password("user")
                .roles("USER")
                .build()
        return MapReactiveUserDetailsService(userDetails)
    }

    @Bean
    fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        return http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            formLogin { }
            httpBasic { }
        }
    }
}
-----
======

[NOTE]
Hãy bảo đảm import function `org.springframework.security.config.web.server.invoke` để enable Kotlin DSL trong class của bạn, vì IDE không phải lúc nào cũng tự động import method này, dẫn đến lỗi compile.

Cấu hình này tường minh thiết lập tất cả các thành phần giống cấu hình tối thiểu.
Từ đây, bạn có thể dễ dàng thay đổi các giá trị mặc định hơn.

Bạn có thể tìm thêm các ví dụ về cấu hình tường minh trong các unit test bằng cách tìm https://github.com/spring-projects/spring-security/search?q=path%3Aconfig%2Fsrc%2Ftest%2F+EnableWebFluxSecurity[`EnableWebFluxSecurity` trong thư mục `config/src/test/`].

[[jc-webflux-multiple-filter-chains]]
=== Hỗ trợ nhiều filter chain

Bạn có thể cấu hình nhiều instance `SecurityWebFilterChain` để tách cấu hình dựa trên các instance `RequestMatcher`.

Ví dụ, bạn có thể tách riêng cấu hình cho các URL bắt đầu bằng `/api`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
static class MultiSecurityHttpConfig {

    @Order(Ordered.HIGHEST_PRECEDENCE)                                                      <1>
    @Bean
    SecurityWebFilterChain apiHttpSecurity(ServerHttpSecurity http) {
        http
            .securityMatcher(new PathPatternParserServerWebExchangeMatcher("/api/**"))      <2>
            .authorizeExchange((authorize) -> authorize
                .anyExchange().authenticated()
            )
            .oauth2ResourceServer(OAuth2ResourceServerSpec::jwt);                           <3>
        return http.build();
    }

    @Bean
    SecurityWebFilterChain webHttpSecurity(ServerHttpSecurity http) {                       <4>
        http
            .authorizeExchange((authorize) -> authorize
                .anyExchange().authenticated()
            )
            .httpBasic(withDefaults());                                                     <5>
        return http.build();
    }

    @Bean
    ReactiveUserDetailsService userDetailsService() {
        return new MapReactiveUserDetailsService(
                PasswordEncodedUser.user(), PasswordEncodedUser.admin());
    }

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.web.server.invoke

@Configuration
@EnableWebFluxSecurity
open class MultiSecurityHttpConfig {
    @Order(Ordered.HIGHEST_PRECEDENCE)                                                      <1>
    @Bean
    open fun apiHttpSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
        return http {
            securityMatcher(PathPatternParserServerWebExchangeMatcher("/api/**"))           <2>
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2ResourceServer {
                jwt { }                                                                     <3>
            }
        }
    }

    @Bean
    open fun webHttpSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {            <4>
        return http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            httpBasic { }                                                                   <5>
        }
    }

    @Bean
    open fun userDetailsService(): ReactiveUserDetailsService {
        return MapReactiveUserDetailsService(
            PasswordEncodedUser.user(), PasswordEncodedUser.admin()
        )
    }
}
----
======

<1> Cấu hình một `SecurityWebFilterChain` với `@Order` để chỉ định `SecurityWebFilterChain` nào Spring Security cần xem xét trước
<2> Sử dụng `PathPatternParserServerWebExchangeMatcher` để chỉ ra rằng `SecurityWebFilterChain` này chỉ áp dụng cho các URL path bắt đầu bằng `/api/`
<3> Chỉ định các cơ chế authentication sẽ được sử dụng cho các endpoint `/api/**`
<4> Tạo một instance `SecurityWebFilterChain` khác với precedence thấp hơn để so khớp tất cả URL còn lại
<5> Chỉ định các cơ chế authentication sẽ được sử dụng cho phần còn lại của ứng dụng

Spring Security chọn một `SecurityWebFilterChain` `@Bean` cho mỗi request.
Nó so khớp các request theo thứ tự dựa trên định nghĩa `securityMatcher`.

Trong trường hợp này, điều đó có nghĩa là nếu URL path bắt đầu bằng `/api`, Spring Security sử dụng `apiHttpSecurity`.
Nếu URL không bắt đầu bằng `/api`, Spring Security mặc định sử dụng `webHttpSecurity`, vốn có một `securityMatcher` ngầm định so khớp với mọi request.


[[modular-serverhttpsecurity-configuration]]
== Cấu hình ServerHttpSecurity theo mô-đun

Nhiều người dùng muốn cấu hình Spring Security của mình nằm ở một nơi tập trung và sẽ chọn cấu hình trong khai báo Bean `SecurityWebFilterChain`.
Tuy nhiên, đôi khi người dùng muốn chia cấu hình thành các mô-đun.
Bạn có thể thực hiện việc này bằng:

* xref:#serverhttpsecurity-customizer-bean[Các Bean `Customizer<ServerHttpSecurity>`]
* xref:#top-level-customizer-bean[Các Bean `Customizer` cấp cao nhất của `ServerHttpSecurity`]

// FIXME: nội dung này cần liên kết đến vị trí phù hợp
// NOTE: Nếu bạn đang sử dụng xref:servlet/configuration/kotlin.adoc[] của Spring Security, bạn cũng có thể công khai các Bean `*Dsl -> Unit` như được trình bày trong xref:./kotlin.adoc#modular-httpsecuritydsl-configuration[Cấu hình HttpSecurityDsl theo mô-đun].


[[serverhttpsecurity-customizer-bean]]
=== Các Bean `Customizer<ServerHttpSecurity>`

Nếu muốn chia cấu hình bảo mật thành các mô-đun, bạn có thể đặt logic trong một Bean `Customizer<ServerHttpSecurity>`.
Ví dụ, cấu hình sau đây sẽ bảo đảm tất cả instance `ServerHttpSecurity` được cấu hình để:

include-code::./ServerHttpSecurityCustomizerBeanConfiguration[tag=httpSecurityCustomizer,indent=0]

<1> Đặt xref:servlet/exploits/headers.adoc#servlet-headers-csp[Content Security Policy] thành `object-src 'none'`
<2> xref:servlet/exploits/http.adoc#servlet-http-redirect[Chuyển hướng mọi request sang https]


[[top-level-customizer-bean]]
=== Các Bean `Customizer` cấp cao nhất của `ServerHttpSecurity`

Nếu muốn chia nhỏ security configuration thêm nữa, Spring Security sẽ tự động áp dụng mọi Bean `Customizer` cấp cao nhất của `HttpSecurity`.

Có thể hiểu type `Customizer` cấp cao nhất của `HttpSecurity` là bất kỳ `Customizer<T>` nào khớp với `public HttpSecurity.*(Customizer<T>)`.
Điều này có nghĩa là bất kỳ `Customizer<T>` nào là một argument duy nhất của một public method trên javadoc:org.springframework.security.config.annotation.web.builders.HttpSecurity[].

Một vài ví dụ có thể giúp làm rõ điều này.
Nếu `Customizer<ContentTypeOptionsConfig>` được publish dưới dạng Bean, nó sẽ không được tự động áp dụng vì là argument của javadoc:org.springframework.security.config.annotation.web.configurers.HeadersConfigurer#contentTypeOptions(org.springframework.security.config.Customizer)[], vốn không phải là method được định nghĩa trên `HttpSecurity`.
Tuy nhiên, nếu `Customizer<HeadersConfigurer<HttpSecurity>>` được publish dưới dạng Bean, nó sẽ được tự động áp dụng vì là argument của javadoc:org.springframework.security.config.annotation.web.builders.HttpSecurity#headers(org.springframework.security.config.Customizer)[].

Ví dụ, cấu hình sau đây sẽ bảo đảm xref:servlet/exploits/headers.adoc#servlet-headers-csp[Content Security Policy] được đặt thành `object-src 'none'`:

include-code::./TopLevelCustomizerBeanConfiguration[tag=headersCustomizer,indent=0]

[[customizer-bean-ordering]]
=== Thứ tự Bean Customizer

Trước tiên, mỗi xref:#httpsecurity-customizer-bean[Bean Customizer<HttpSecurity>] được áp dụng bằng {spring-framework-api-url}org/springframework/beans/factory/ObjectProvider.html#orderedStream()[ObjectProvider#orderedStream()].
Điều này có nghĩa là nếu có nhiều Bean `Customizer<HttpSecurity>`, bạn có thể thêm annotation {spring-framework-api-url}org/springframework/core/annotation/Order.html[@Order] vào các định nghĩa Bean để kiểm soát thứ tự.

Tiếp theo, từng type `Customizer` xref:#top-level-customizer-bean[cấp cao nhất của `HttpSecurity`] được tra cứu và áp dụng bằng `ObjectProvider#orderedStream()`.
Nếu có hai bean `Customizer<HeadersConfigurer<HttpSecurity>>` và hai instance `Customizer<HttpsRedirectConfigurer<HttpSecurity>>`, thứ tự gọi từng kiểu `Customizer` là không xác định.
Tuy nhiên, thứ tự của từng instance `Customizer<HttpsRedirectConfigurer<HttpSecurity>>` được xác định bởi `ObjectProvider#orderedStream()` và có thể được kiểm soát bằng `@Order` trên các định nghĩa Bean.

Cuối cùng, Bean `HttpSecurity` được inject dưới dạng Bean.
Tất cả instance `Customizer` được áp dụng trước khi Bean `HttpSecurity` được tạo.
Điều này cho phép ghi đè các tùy chỉnh do các Bean `Customizer` cung cấp.

Bạn có thể tìm một ví dụ minh họa thứ tự ở bên dưới:

include-code::./CustomizerBeanOrderingConfiguration[tag=sample,indent=0]

<1> Trước tiên, tất cả instance `Customizer<HttpSecurity>` được áp dụng.
Bean `adminAuthorization` có `@Order` cao nhất nên được áp dụng trước.
Nếu các Bean `Customizer<HttpSecurity>` không có annotation `@Order` hoặc các annotation `@Order` có cùng giá trị, thứ tự áp dụng các instance `Customizer<HttpSecurity>` là không xác định.
<2> `userAuthorization` được áp dụng tiếp theo vì là một instance của `Customizer<HttpSecurity>`
<3> Thứ tự của các kiểu `Customizer` là không xác định.
Trong ví dụ này, thứ tự của `contentSecurityPolicy`, `contentTypeOptions` và `httpsRedirect` là không xác định.
Nếu thêm `@Order(Ordered.HIGHEST_PRECEDENCE)` vào `contentTypeOptions`, chúng ta sẽ biết `contentTypeOptions` đứng trước `contentSecurityPolicy` (chúng cùng kiểu), nhưng không biết `httpsRedirect` đứng trước hay sau các Bean `Customizer<HeadersConfigurer<HttpSecurity>>`.
<4> Sau khi tất cả Bean `Customizer` được áp dụng, `HttpSecurity` được truyền vào dưới dạng Bean.
