[[springsecuritykerberos]]
= Spring và Spring Security Kerberos
:figures: servlet/authentication/kerberos

Phần này của tài liệu tham khảo giải thích chức năng cốt lõi
mà Spring Security Kerberos cung cấp cho mọi ứng dụng dựa trên Spring.

<<ssk-authprovider>> mô tả việc hỗ trợ authentication provider.

<<ssk-spnego>> mô tả việc hỗ trợ Spnego Negotiate.

<<ssk-resttemplate>> mô tả việc hỗ trợ cho RestTemplate.


[[ssk-authprovider]]
== Authentication Provider

Cấu hình authentication provider bằng JavaConfig.

[source,java,indent=0]
----
include::example$kerberos/AuthProviderConfig.java[tags=snippetA]
----

[[ssk-spnego]]
== Spnego Negotiate

Cấu hình Spnego bằng JavaConfig.

[source,java,indent=0]
----
include::example$kerberos/SpnegoConfig.java[tags=snippetA]
----

[[ssk-resttemplate]]
== Sử dụng KerberosRestTemplate

Nếu cần truy cập bằng code vào các web resource được Kerberos bảo vệ, bạn có thể
sử dụng `KerberosRestTemplate`; class này mở rộng `RestTemplate` và thực hiện các
thao tác login cần thiết trước khi chuyển việc xử lý cho các method thực tế của
`RestTemplate`. Về cơ bản, bạn có một số tùy chọn để cấu hình template này.

- Để trống keyTabLocation và userPrincipal nếu bạn muốn
  sử dụng ticket đã cache.
- Sử dụng keyTabLocation và userPrincipal nếu bạn muốn dùng
  file keytab.
- Sử dụng loginOptions nếu bạn muốn tùy chỉnh các option của Krb5LoginModule.
- Sử dụng httpClient đã được tùy chỉnh.

Với ticket cache.
[source,java,indent=0]
----
include::example$kerberos/KerberosRestTemplateConfig.java[tags=snippetA]
----

Với file keytab.
[source,java,indent=0]
----
include::example$kerberos/KerberosRestTemplateConfig.java[tags=snippetB]
----

[[ssk-kerberosldap]]
== Authentication với LDAP service

Trong hầu hết các sample, chúng tôi sử dụng `DummyUserDetailsService`
vì không nhất thiết phải query thông tin của một user thực sau khi
authentication bằng Kerberos thành công, và chúng ta có thể sử dụng thông tin
principal của Kerberos để tạo dummy user đó. Tuy nhiên, vẫn có cách an toàn để
truy cập các LDAP service được Kerberos bảo vệ và query thông tin user
từ đó.

`KerberosLdapContextSource` có thể được sử dụng để bind vào LDAP thông qua Kerberos,
và đã được chứng minh là hoạt động tốt với các Windows AD service.

[source,java,indent=0]
----
include::example$kerberos/KerberosLdapContextSourceConfig.java[tags=snippetA]
----

[TIP]
====
Mẫu xref:servlet/authentication/kerberos/samples.adoc#samples-sec-server-win-auth[Mẫu Security Server Windows Auth]
hiện được cấu hình để query thông tin user từ AD nếu authentication diễn ra qua Kerberos.
====
