[[appendix-faq]]
= Câu hỏi thường gặp về Spring Security

FAQ này gồm các phần sau:

* <<appendix-faq-general-questions>>
* <<appendix-faq-common-problems>>
* <<appendix-faq-architecture>>
* <<appendix-faq-howto>>

[[appendix-faq-general-questions]]
== Câu hỏi chung

FAQ này giải đáp các câu hỏi chung sau:

* <<appendix-faq-other-concerns>>
* <<appendix-faq-web-xml>>
* <<appendix-faq-requirements>>
* <<appendix-faq-start-simple>>


[[appendix-faq-other-concerns]]
=== Spring Security có thể đáp ứng tất cả yêu cầu security của application không?

Spring Security cung cấp cho bạn một framework linh hoạt để đáp ứng các yêu cầu authentication và authorization, nhưng còn nhiều vấn đề khác khi xây dựng một application an toàn nằm ngoài phạm vi của nó.
Web application dễ bị mọi loại tấn công, và bạn nên làm quen với chúng, tốt nhất là trước khi bắt đầu phát triển để có thể thiết kế và viết code có tính đến chúng ngay từ đầu.
Hãy xem https://www.owasp.org/[website OWASP] để biết thông tin về những vấn đề chính mà các nhà phát triển web application phải đối mặt và các biện pháp đối phó có thể sử dụng.


[[appendix-faq-web-xml]]
=== Tại sao không sử dụng security của web.xml?

Giả sử bạn đang phát triển một enterprise application dựa trên Spring.
Thông thường, bạn cần xử lý bốn khía cạnh security: authentication, security cho web request, security ở service layer (các method triển khai business logic) và security cho instance của domain object (các domain object khác nhau có thể có permission khác nhau). Với các yêu cầu điển hình này, chúng ta có những cân nhắc sau:

* _Authentication_: servlet specification cung cấp một cách tiếp cận cho authentication.
Tuy nhiên, bạn cần cấu hình container để thực hiện authentication, việc này thường yêu cầu chỉnh sửa các thiết lập "`realm`" dành riêng cho container.
Điều này tạo ra một cấu hình không portable. Ngoài ra, nếu cần viết một Java class thực tế để triển khai authentication interface của container, cấu hình còn kém portable hơn.
Với Spring Security, bạn đạt được tính portable hoàn toàn, xuống đến cấp WAR.
Spring Security cũng cung cấp lựa chọn các authentication provider và cơ chế đã được kiểm chứng trong production, nghĩa là bạn có thể chuyển đổi cách authentication tại thời điểm deploy.
Điều này đặc biệt có giá trị với các nhà cung cấp phần mềm viết sản phẩm cần hoạt động trong một target environment không xác định.

* _Web request security:_ servlet specification cung cấp một cách để bảo vệ request URI.
Tuy nhiên, các URI này chỉ có thể được biểu diễn bằng format URI path hạn chế riêng của servlet specification.
Spring Security cung cấp một cách tiếp cận toàn diện hơn nhiều.
Chẳng hạn, bạn có thể sử dụng Ant path hoặc regular expression, xem xét các phần khác của URI ngoài page được request (ví dụ,
bạn có thể xem xét HTTP GET parameter), và triển khai source dữ liệu cấu hình runtime của riêng mình.
Điều này có nghĩa là bạn có thể thay đổi security cho web request một cách động trong quá trình web application thực thi.

* _Security ở service layer và domain object:_ Việc servlet specification không hỗ trợ security ở service layer hoặc security cho instance của domain object tạo ra những hạn chế nghiêm trọng đối với application nhiều tầng.
Thông thường, developer hoặc bỏ qua các yêu cầu này hoặc triển khai logic security trong code của MVC controller (hoặc tệ hơn nữa, bên trong view). Cách tiếp cận này có những bất lợi nghiêm trọng:

** _Separation of concerns:_ Authorization là một crosscutting concern và nên được triển khai như vậy.
MVC controller hoặc view triển khai code authorization khiến việc test cả controller lẫn logic authorization khó hơn, debug khó hơn và thường dẫn đến trùng lặp code.

** _Hỗ trợ rich client và web service:_ Nếu cuối cùng cần hỗ trợ thêm một loại client, mọi code authorization được nhúng trong web layer đều không thể tái sử dụng.
Cần lưu ý rằng Spring remoting exporter chỉ export các bean ở service layer (không export MVC controller). Do đó, logic authorization cần được đặt ở service layer để hỗ trợ nhiều loại client.

** _Vấn đề phân tầng:_ MVC controller hoặc view là architectural layer không phù hợp để triển khai các quyết định authorization liên quan đến method ở service layer hoặc instance của domain object.
Mặc dù có thể truyền principal vào service layer để layer này đưa ra quyết định authorization, cách đó sẽ thêm một argument vào mọi method ở service layer.
Một cách tiếp cận thanh lịch hơn là dùng `ThreadLocal` để lưu principal, dù cách này có thể làm thời gian phát triển tăng đến mức xét trên chi phí-lợi ích thì dùng một security framework chuyên dụng sẽ kinh tế hơn.

** _Chất lượng code authorization:_ Người ta thường nói về web framework rằng chúng "`giúp làm điều đúng dễ hơn và làm điều sai khó hơn`". Security framework cũng vậy, vì chúng được thiết kế theo cách trừu tượng cho nhiều mục đích.
Tự viết code authorization từ đầu không cung cấp "`design check`" mà một framework đem lại, và code authorization nội bộ thường thiếu những cải tiến xuất hiện từ việc triển khai rộng rãi, peer review và các version mới.

Với application đơn giản, security của servlet specification có thể là đủ.
Tuy nhiên, khi xét trong bối cảnh portability của web container, yêu cầu cấu hình, tính linh hoạt hạn chế của security cho web request và việc không có security ở service layer cũng như instance của domain object, có thể hiểu vì sao developer thường tìm đến các giải pháp thay thế.


[[appendix-faq-requirements]]
=== Yêu cầu các version Java và Spring Framework nào?

Spring Security 3.0 và 3.1 yêu cầu tối thiểu JDK 1.5, đồng thời yêu cầu Spring 3.0.3 là version tối thiểu.
Tốt nhất, bạn nên dùng các version release mới nhất để tránh vấn đề.

Spring Security 2.0.x yêu cầu JDK version tối thiểu là 1.4 và được build dựa trên Spring 2.0.x.
Nó cũng phải tương thích với application sử dụng Spring 2.5.x.


[[appendix-faq-start-simple]]
==== Tôi có một scenario phức tạp. Có thể đã sai ở đâu?

(Câu trả lời này xử lý các scenario phức tạp nói chung bằng cách xét một scenario cụ thể.)

Giả sử bạn mới dùng Spring Security và cần xây dựng một application hỗ trợ CAS single sign-on qua HTTPS, đồng thời cho phép basic authentication cục bộ đối với một số URL và thực hiện authentication dựa trên nhiều source thông tin user backend (LDAP và JDBC). Bạn đã sao chép một số file cấu hình nhưng phát hiện nó không hoạt động. Có thể đã sai ở đâu?

Bạn cần hiểu các công nghệ định sử dụng trước khi có thể xây dựng application thành công với chúng.
Security rất phức tạp.
Thiết lập một cấu hình đơn giản bằng login form và một số user hard-code với namespace của Spring Security tương đối dễ dàng.
Chuyển sang dùng database JDBC làm backend cũng khá dễ.
Tuy nhiên, nếu cố nhảy thẳng vào một deployment scenario phức tạp như trên, gần như chắc chắn bạn sẽ thất vọng.
Để thiết lập các hệ thống như CAS, cấu hình LDAP server và cài đặt SSL certificate đúng cách, bạn cần vượt qua một đường cong học tập rất lớn.
Vì vậy, bạn cần thực hiện từng bước một.

Từ góc nhìn Spring Security, điều đầu tiên bạn nên làm là theo hướng dẫn "`Getting Started`" trên website.
Hướng dẫn này đưa bạn qua một loạt bước để bắt đầu chạy được và có một số hình dung về cách framework hoạt động.
Nếu sử dụng các công nghệ khác mà bạn chưa quen, bạn nên nghiên cứu và cố gắng bảo đảm có thể sử dụng chúng độc lập trước khi kết hợp vào một hệ thống phức tạp.

[[appendix-faq-common-problems]]
== Vấn đề thường gặp

Phần này đề cập đến những vấn đề thường gặp nhất khi sử dụng Spring Security:

* Authentication
** <<appendix-faq-bad-credentials>>
** <<appendix-faq-login-loop>>
** <<appendix-faq-anon-access-denied>>
** <<appendix-faq-cached-secure-page>>
** <<auth-exception-credentials-not-found>>
** <<appendix-faq-ldap-authentication>>
* Quản lý session
** <<appendix-faq-concurrent-session-same-browser>>
** <<appendix-faq-new-session-on-authentication>>
** <<appendix-faq-tomcat-https-session>>
** <<appendix-faq-session-listener-missing>>
** <<appendix-faq-unwanted-session-creation>>
* Khác
** <<appendix-faq-forbidden-csrf>>
** <<appendix-faq-no-security-on-forward>>
** <<appendix-faq-method-security-in-web-context>>
** <<appendix-faq-no-filters-no-context>>
** <<appendix-faq-method-security-with-taglib>>

[[appendix-faq-bad-credentials]]
=== Khi cố đăng nhập, tôi nhận được thông báo lỗi "`Bad Credentials`". Có vấn đề gì?

Điều này có nghĩa là authentication đã thất bại.
Thông báo không cho biết lý do, vì việc tránh cung cấp chi tiết có thể giúp attacker đoán tên account hoặc password là một practice tốt.

Điều này cũng có nghĩa là nếu hỏi câu này trên mạng, bạn không nên mong đợi nhận được câu trả lời trừ khi cung cấp thêm thông tin.
Như với mọi vấn đề, bạn nên kiểm tra output từ debug log và ghi nhận mọi exception stacktrace cùng các message liên quan.
Bạn nên step through code trong debugger để xem authentication thất bại ở đâu và vì sao.
Bạn cũng nên viết một test case thực thi cấu hình authentication bên ngoài application.
Nếu dùng hashed password, hãy bảo đảm value được lưu trong database _chính xác_ giống value do `PasswordEncoder` được cấu hình trong application tạo ra.


[[appendix-faq-login-loop]]
=== Application của tôi rơi vào "`endless loop`" khi cố đăng nhập. Chuyện gì đang xảy ra?

Một vấn đề phổ biến là user gặp vòng lặp vô hạn và bị redirect về login page vì login page vô tình được cấu hình thành resource "`secured`".
Hãy bảo đảm cấu hình của bạn cho phép anonymous access đến login page.
Bạn có thể làm điều đó bằng DSL xref:servlet/authorization/authorize-http-requests.adoc[`authorizeHttpRequests`].

[TIP]
====
Khi sử dụng cấu hình dựa trên namespace hoặc DSL, một kiểm tra được thực hiện lúc load application context và warning message được ghi log nếu login page có vẻ được bảo vệ.
====

[[appendix-faq-anon-access-denied]]
=== Tôi nhận được exception với message "Access is denied (user is anonymous);". Có vấn đề gì?

Đây là message ở debug level xuất hiện lần đầu anonymous user cố truy cập một protected resource.

[source]
----
DEBUG [ExceptionTranslationFilter] - Access is denied (user is anonymous); redirecting to authentication entry point
org.springframework.security.AccessDeniedException: Access is denied
at org.springframework.security.vote.AffirmativeBased.decide(AffirmativeBased.java:68)
at org.springframework.security.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:262)
----

Đây là điều bình thường và không có gì đáng lo.


[[appendix-faq-cached-secure-page]]
=== Tại sao tôi vẫn thấy secured page ngay cả sau khi đã logout khỏi application?

Lý do phổ biến nhất là browser đã cache page và bạn đang xem một bản sao được lấy từ cache của browser.
Hãy xác minh bằng cách kiểm tra browser có thực sự gửi request hay không (kiểm tra server access log và debug log, hoặc dùng browser debugging plugin phù hợp, chẳng hạn "`Tamper Data`" cho Firefox). Điều này không liên quan đến Spring Security; bạn nên cấu hình application hoặc server để đặt các response header `Cache-Control` phù hợp.
Lưu ý rằng SSL request không bao giờ được cache.


[[auth-exception-credentials-not-found]]
=== Tôi nhận được exception với message "An Authentication object was not found in the SecurityContext". Có vấn đề gì?

Listing sau hiển thị một message khác ở debug level xuất hiện lần đầu anonymous user cố truy cập một protected resource. Tuy nhiên, listing này cho thấy điều xảy ra khi bạn không có `AnonymousAuthenticationFilter` trong cấu hình filter chain:

[source]
----
DEBUG [ExceptionTranslationFilter] - Authentication exception occurred; redirecting to authentication entry point
org.springframework.security.AuthenticationCredentialsNotFoundException:
							An Authentication object was not found in the SecurityContext
at org.springframework.security.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:342)
at org.springframework.security.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:254)
----

Đây là điều bình thường và không có gì đáng lo.


[[appendix-faq-ldap-authentication]]
=== Tôi không thể làm cho LDAP authentication hoạt động. Cấu hình của tôi có vấn đề gì?

Lưu ý rằng permission của LDAP directory thường không cho phép đọc password của user.
Do đó, thường không thể dùng <<appendix-faq-what-is-userdetailservice>>, trong đó Spring Security so sánh password đã lưu với password user gửi lên.
Cách tiếp cận phổ biến nhất là sử dụng LDAP "`bind`", một trong các operation được https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol[LDAP protocol] hỗ trợ. Với cách này, Spring Security xác thực password bằng cách thử authentication vào directory với tư cách user.

Vấn đề phổ biến nhất với LDAP authentication là thiếu hiểu biết về cấu trúc tree và cấu hình của directory server.
Điều này khác nhau giữa các công ty, vì vậy bạn phải tự tìm hiểu.
Trước khi thêm cấu hình Spring Security LDAP vào application, bạn nên viết một test đơn giản bằng code Java LDAP tiêu chuẩn (không dùng Spring Security) và bảo đảm trước tiên có thể làm cho nó hoạt động.
Ví dụ, để authenticate một user, bạn có thể dùng code sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----

@Test
public void ldapAuthenticationIsSuccessful() throws Exception {
		Hashtable<String,String> env = new Hashtable<String,String>();
		env.put(Context.SECURITY_AUTHENTICATION, "simple");
		env.put(Context.SECURITY_PRINCIPAL, "cn=joe,ou=users,dc=mycompany,dc=com");
		env.put(Context.PROVIDER_URL, "ldap://mycompany.com:389/dc=mycompany,dc=com");
		env.put(Context.SECURITY_CREDENTIALS, "joespassword");
		env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");

		InitialLdapContext ctx = new InitialLdapContext(env, null);

}

----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Test
fun ldapAuthenticationIsSuccessful() {
    val env = Hashtable<String, String>()
    env[Context.SECURITY_AUTHENTICATION] = "simple"
    env[Context.SECURITY_PRINCIPAL] = "cn=joe,ou=users,dc=mycompany,dc=com"
    env[Context.PROVIDER_URL] = "ldap://mycompany.com:389/dc=mycompany,dc=com"
    env[Context.SECURITY_CREDENTIALS] = "joespassword"
    env[Context.INITIAL_CONTEXT_FACTORY] = "com.sun.jndi.ldap.LdapCtxFactory"
    val ctx = InitialLdapContext(env, null)
}
----
======

=== Quản lý session

Các vấn đề về quản lý session là nguồn câu hỏi phổ biến.
Nếu đang phát triển Java web application, bạn nên hiểu session được duy trì như thế nào giữa servlet container và browser của user.
Bạn cũng nên hiểu sự khác nhau giữa secure cookie và non-secure cookie, cũng như tác động của việc sử dụng HTTP và HTTPS rồi chuyển đổi giữa hai giao thức.
Spring Security không liên quan đến việc duy trì session hoặc cung cấp session identifier.
Việc này hoàn toàn do servlet container xử lý.


[[appendix-faq-concurrent-session-same-browser]]
=== Tôi đang sử dụng concurrent session control của Spring Security để ngăn user đăng nhập nhiều lần cùng lúc. Khi mở một browser window khác sau khi đăng nhập, nó không ngăn tôi đăng nhập lại. Tại sao tôi có thể đăng nhập nhiều lần?

Browser thường duy trì một session duy nhất cho mỗi browser instance.
Bạn không thể có hai session riêng biệt cùng lúc.
Vì vậy, nếu đăng nhập lại trong một window hoặc tab khác, bạn chỉ đang re-authenticate trong cùng session.
Vì vậy, nếu đăng nhập lại trong một window hoặc tab khác, bạn đang re-authenticate trong cùng session.
Server không biết gì về tab, window hoặc browser instance.
Nó chỉ thấy các HTTP request và gắn chúng với một session cụ thể dựa trên value của cookie `JSESSIONID` chứa trong request.
Khi user authenticate trong một session, concurrent session control của Spring Security kiểm tra số _session khác đã được authenticated_ của user đó.
Nếu user đã authenticate bằng cùng session, việc re-authenticate không có tác dụng.


[[appendix-faq-new-session-on-authentication]]
=== Tại sao session ID thay đổi khi tôi authenticate thông qua Spring Security?

Với cấu hình mặc định, Spring Security thay đổi session ID khi user authenticate.
Nếu sử dụng container Servlet 3.1 hoặc mới hơn, session ID chỉ đơn giản được thay đổi.
Nếu sử dụng container cũ hơn, Spring Security invalidate session hiện tại, tạo session mới và chuyển dữ liệu session sang session mới.
Thay đổi session identifier theo cách này ngăn chặn tấn công "`session-fixation`".
Bạn có thể tìm hiểu thêm về việc này trên mạng và trong reference manual.


[[appendix-faq-tomcat-https-session]]
=== Tôi sử dụng Tomcat (hoặc servlet container khác) và đã bật HTTPS cho login page, sau đó chuyển lại HTTP. Việc này không hoạt động. Tôi lại quay về login page sau khi authenticate.
Việc này không hoạt động, tôi chỉ lại quay về login page sau khi authenticate.

Điều này xảy ra vì session được tạo dưới HTTPS, với session cookie được đánh dấu là "`secure`", sau đó không thể được sử dụng dưới HTTP. Browser không gửi cookie trở lại server nên mọi session state (bao gồm thông tin security context) bị mất. Bắt đầu session bằng HTTP trước sẽ hoạt động, vì session cookie không được đánh dấu là secure.
Tuy nhiên, xref:servlet/authentication/session-management.adoc#ns-session-fixation[Session Fixation Protection] của Spring Security có thể gây ảnh hưởng vì nó khiến một session ID cookie mới được gửi về browser của user, thường kèm secure flag.
Để khắc phục, bạn có thể tắt session fixation protection. Tuy nhiên, trong các Servlet container mới hơn, bạn cũng có thể cấu hình session cookie để không bao giờ dùng secure flag.


[IMPORTANT]
====
Nhìn chung, chuyển đổi giữa HTTP và HTTPS không phải là ý hay, vì mọi application sử dụng HTTP đều dễ bị tấn công man-in-the-middle.
Để thực sự an toàn, user nên bắt đầu truy cập site bằng HTTPS và tiếp tục sử dụng nó cho đến khi logout.
Ngay cả việc click vào link HTTPS từ một page được truy cập qua HTTP cũng tiềm ẩn rủi ro.
Nếu cần thêm lý do thuyết phục, hãy xem một tool như https://github.com/moxie0/sslstrip/[sslstrip].
====


=== Tôi không chuyển đổi giữa HTTP và HTTPS, nhưng session vẫn bị mất. Chuyện gì đã xảy ra?

Session được duy trì bằng cách trao đổi session cookie hoặc thêm parameter `jsessionid` vào URL (việc này tự động xảy ra nếu bạn dùng JSTL để output URL hoặc gọi `HttpServletResponse.encodeUrl` trên URL, ví dụ trước một redirect). Nếu client tắt cookie và bạn không rewrite URL để bao gồm `jsessionid`, session sẽ bị mất.
Lưu ý rằng sử dụng cookie được ưu tiên vì lý do security, vì nó không làm lộ thông tin session trong URL.

[[appendix-faq-session-listener-missing]]
=== Tôi đang cố sử dụng hỗ trợ concurrent session-control, nhưng không thể đăng nhập lại dù chắc chắn đã logout và chưa vượt quá số session cho phép. Có vấn đề gì?

Hãy bảo đảm bạn đã thêm listener vào file `web.xml`.
Điều thiết yếu là phải bảo đảm Spring Security session registry được thông báo khi một session bị destroy.
Nếu không, thông tin session sẽ không bị xóa khỏi registry.
Ví dụ sau thêm một listener trong file `web.xml`:

[source,xml]
----
<listener>
		<listener-class>org.springframework.security.web.session.HttpSessionEventPublisher</listener-class>
</listener>
----

[[appendix-faq-unwanted-session-creation]]
=== Spring Security tạo session ở đâu đó dù tôi đã cấu hình không tạo bằng cách đặt attribute create-session thành never. Có vấn đề gì?

Điều này thường có nghĩa là application của user đang tạo session ở đâu đó nhưng user không biết.
Thủ phạm phổ biến nhất là JSP. Nhiều người không biết JSP mặc định tạo session.
Để ngăn JSP tạo session, hãy thêm directive `<%@ page session="false" %>` vào đầu page.

Nếu gặp khó khăn khi xác định session được tạo ở đâu, bạn có thể thêm debug code để truy tìm các vị trí đó. Một cách là thêm `javax.servlet.http.HttpSessionListener` vào application; listener này gọi `Thread.dumpStack()` trong method `sessionCreated`.

[[appendix-faq-forbidden-csrf]]
=== Tôi nhận được 403 Forbidden khi thực hiện POST. Có vấn đề gì?

Nếu HTTP POST trả về lỗi HTTP 403 Forbidden nhưng HTTP GET hoạt động, vấn đề rất có thể liên quan đến xref:features/exploits/csrf.adoc#csrf[CSRF]. Hãy cung cấp CSRF Token hoặc tắt CSRF protection (cách sau không được khuyến nghị).

[[appendix-faq-no-security-on-forward]]
=== Tôi forward request đến URL khác bằng RequestDispatcher nhưng các security constraint không được áp dụng.

Mặc định, các filter không được áp dụng cho forward hoặc include.
Nếu thực sự muốn security filter được áp dụng cho forward hoặc include, bạn phải cấu hình rõ ràng trong file `web.xml` bằng element `<dispatcher>`, là child element của element `<filter-mapping>`.


[[appendix-faq-method-security-in-web-context]]
=== Tôi đã thêm element <global-method-security> của Spring Security vào application context, nhưng khi thêm security annotation vào Spring MVC controller bean (Struts action, v.v.), chúng dường như không có tác dụng. Tại sao?

Trong một Spring web application, application context chứa các Spring MVC bean cho dispatcher servlet thường tách biệt với main application context.
Context này thường được định nghĩa trong file có tên `myapp-servlet.xml`, trong đó `myapp` là tên được gán cho Spring `DispatcherServlet` trong file `web.xml`. Một application có thể có nhiều instance `DispatcherServlet`, mỗi instance có application context tách biệt riêng.
Các bean trong những context "`child`" này không hiển thị với phần còn lại của application.
Application context "`parent`" được load bởi `ContextLoaderListener` mà bạn định nghĩa trong file `web.xml` và hiển thị với tất cả child context.
Parent context này thường là nơi bạn định nghĩa security configuration, bao gồm element `<global-method-security>`. Do đó, mọi security constraint áp dụng cho method trong các web bean này không được thực thi, vì các bean không được nhìn thấy từ `DispatcherServlet` context.
Bạn cần chuyển declaration `<global-method-security>` sang web context hoặc chuyển các bean cần được bảo vệ vào main application context.

Nhìn chung, chúng tôi khuyến nghị áp dụng method security ở service layer thay vì trên từng web controller.


[[appendix-faq-no-filters-no-context]]
=== Tôi có một user chắc chắn đã được authenticate, nhưng khi cố truy cập SecurityContextHolder trong một số request, Authentication lại là null. Tại sao tôi không thấy thông tin user?
Tại sao tôi không thấy thông tin user?

Nếu đã loại request khỏi security filter chain bằng cách sử dụng attribute `filters='none'` trong element `<intercept-url>` khớp với URL pattern, `SecurityContextHolder` sẽ không được populate cho request đó.
Hãy kiểm tra debug log để xem request có đi qua filter chain hay không.
(Bạn đang đọc debug log, đúng không?)

[[appendix-faq-method-security-with-taglib]]
=== authorize JSP Tag không tôn trọng method security annotation của tôi khi sử dụng URL attribute. Tại sao?

Method security không ẩn link khi sử dụng attribute `url` trong `<sec:authorize>`, vì chúng ta không thể dễ dàng reverse engineer URL nào được map tới controller endpoint nào. Khả năng của chúng ta bị giới hạn vì controller có thể dựa vào header, user hiện tại và các chi tiết khác để xác định method nào cần invoke.

[[appendix-faq-architecture]]
== Câu hỏi về Spring Security Architecture

Phần này đề cập đến các câu hỏi thường gặp về Spring Security architecture:

. <<appendix-faq-where-is-class-x>>
. <<appendix-faq-namespace-to-bean-mapping>>
. <<appendix-faq-role-prefix>>
. <<appendix-faq-what-dependencies>>
. <<appendix-faq-unboundid-deps>>
. <<appendix-faq-what-is-userdetailservice>>


[[appendix-faq-where-is-class-x]]
=== Làm thế nào để biết class X nằm trong package nào?

Cách tốt nhất để tìm class là cài source Spring Security vào IDE. Distribution bao gồm source jar cho từng module trong project.
Thêm các source jar này vào source path của project, sau đó bạn có thể điều hướng trực tiếp đến các class Spring Security (`Ctrl-Shift-T` trong Eclipse). Điều này cũng giúp debug dễ hơn và cho phép troubleshoot exception bằng cách xem trực tiếp code tại nơi chúng xảy ra để hiểu chuyện gì đang diễn ra.

[[appendix-faq-namespace-to-bean-mapping]]
=== Các namespace element map tới conventional bean configuration như thế nào?

Có phần tổng quan về các bean được namespace tạo ra trong namespace appendix của reference guide.
Ngoài ra còn có bài blog chi tiết tên là "Behind the Spring Security Namespace" trên https://spring.io/blog/2010/03/06/behind-the-spring-security-namespace/[blog.springsource.com]. Nếu muốn biết đầy đủ chi tiết, code nằm trong module `spring-security-config` thuộc Spring Security 3.0 distribution.
Có lẽ trước tiên bạn nên đọc các chapter về namespace parsing trong tài liệu tham chiếu Spring Framework tiêu chuẩn.


[[appendix-faq-role-prefix]]
=== "ROLE_" có nghĩa là gì?

`ROLE_` là một cách xác định bản chất của một authority cụ thể.
Authority có tiền tố `ROLE_` nghĩa là authority đó là một role, có thể được suy ra từ authorization model RBAC.

Có tiền tố cho phép phân biệt rõ với OAuth 2.0 scope (sử dụng `SCOPE_`) cũng như authority được cấp từ các source khác.

Bạn có thể chọn không thêm tiền tố cho authority.
Các authorization component hiện đại của Spring Security cho phép bạn cung cấp toàn bộ tên authority, khiến tiền tố trở nên không cần thiết.
Ví dụ là xref:servlet/authorization/authorize-http-requests.adoc[`authorizeHttpRequests`] và xref:servlet/authorization/method-security.adoc[`@PreAuthorize`] cho phép bạn gọi `hasAuthority` hoặc `hasRole`.

[[appendix-faq-what-dependencies]]
=== Làm thế nào để biết cần thêm dependency nào vào application để làm việc với Spring Security?

Điều này phụ thuộc vào feature bạn sử dụng và loại application bạn đang phát triển.
Trong Spring Security 3.0, các jar của project được chia thành những vùng chức năng tách biệt rõ ràng, vì vậy dễ xác định các Spring Security jar cần thiết từ yêu cầu của application.
Mọi application đều cần jar `spring-security-core`.
Nếu phát triển web application, bạn cần jar `spring-security-web`.
Nếu sử dụng security namespace configuration, bạn cần jar `spring-security-config`. Để hỗ trợ LDAP, bạn cần jar `spring-security-ldap`, v.v.

Với third-party jar, tình hình không phải lúc nào cũng rõ ràng như vậy.
Một điểm bắt đầu tốt là sao chép các jar đó từ thư mục `WEB-INF/lib` của một trong các sample application được build sẵn.
Với application cơ bản, bạn có thể bắt đầu từ tutorial sample.
Với application cơ bản, bạn có thể bắt đầu từ tutorial sample.
Nếu muốn sử dụng LDAP với embedded test server, hãy dùng LDAP sample làm điểm bắt đầu.
Reference manual cũng bao gồm <<appendix-namespace,một appendix>> liệt kê first-level dependency cho mỗi Spring Security module, cùng một số thông tin về việc dependency có optional hay không và khi nào cần đến chúng.

Nếu build project bằng Maven, việc thêm các Spring Security module phù hợp làm dependency vào file `pom.xml` sẽ tự động kéo theo các core jar mà framework yêu cầu.
Bất kỳ dependency nào được đánh dấu là "`optional`" trong file `pom.xml` của Spring Security đều phải được thêm vào file `pom.xml` của bạn nếu cần sử dụng.

[[appendix-faq-unboundid-deps]]
=== Cần dependency nào để chạy embedded UnboundID LDAP server?

Bạn cần thêm dependency sau vào project:

[tabs]
======
Maven::
+
[source,maven,role="primary"]
----
<dependency>
		<groupId>com.unboundid</groupId>
		<artifactId>unboundid-ldapsdk</artifactId>
		<version>7.0.1</version>
		<scope>runtime</scope>
</dependency>
----

Gradle::
+
[source,gradle,role="secondary"]
----
implementation 'com.unboundid:unboundid-ldapsdk:7.0.1'
----
======


[[appendix-faq-apacheds-deps]]
=== Cần dependency nào để chạy embedded ApacheDS LDAP server?

Spring Security 7 loại bỏ hỗ trợ cho Apache DS.
Thay vào đó, hãy sử dụng <<appendix-faq-unboundid-deps,UnboundID>>.

[[appendix-faq-what-is-userdetailservice]]
=== UserDetailsService là gì và tôi có cần một UserDetailsService không?

`UserDetailsService` là một DAO interface dùng để load dữ liệu dành riêng cho một user account.
Nó không có chức năng nào khác ngoài việc load dữ liệu đó để các component khác trong framework sử dụng.
Nó không chịu trách nhiệm authenticate user.
Việc authenticate user bằng cặp username và password thường do `DaoAuthenticationProvider` thực hiện; provider này được inject một `UserDetailsService` để load password (và dữ liệu khác) của user rồi so sánh với value được gửi lên.
Lưu ý rằng nếu dùng LDAP, <<appendix-faq-ldap-authentication,cách tiếp cận này có thể không hoạt động>>.

Nếu muốn tùy chỉnh authentication process, bạn nên tự triển khai `AuthenticationProvider`.
Xem https://spring.io/blog/2010/08/02/spring-security-in-google-app-engine/[bài blog] này để xem ví dụ tích hợp Spring Security authentication với Google App Engine.

[[appendix-faq-howto]]
== Câu hỏi How-to thường gặp

Phần này đề cập đến các câu hỏi how-to thường gặp về Spring Security:

. <<appendix-faq-extra-login-fields>>
. <<appendix-faq-matching-url-fragments>>
. <<appendix-faq-request-details-in-user-service>>
. <<appendix-faq-access-session-from-user-service>>
. <<appendix-faq-password-in-user-service>>
. <<appendix-faq-dynamic-url-metadata>>
. <<appendix-faq-ldap-authorities>>
. <<appendix-faq-namespace-post-processor>>


[[appendix-faq-extra-login-fields]]
=== Tôi cần đăng nhập với thông tin không chỉ gồm username. Làm thế nào để thêm hỗ trợ cho login field bổ sung (chẳng hạn tên công ty)?

Câu hỏi này được đặt đi đặt lại nhiều lần, vì vậy bạn có thể tìm thêm thông tin bằng cách search online.

Login information được gửi lên được xử lý bởi một instance của `UsernamePasswordAuthenticationFilter`. Bạn cần tùy chỉnh class này để xử lý các data field bổ sung. Một lựa chọn là sử dụng authentication token class tùy chỉnh của riêng bạn (thay vì `UsernamePasswordAuthenticationToken` tiêu chuẩn). Lựa chọn khác là nối các field bổ sung với username (ví dụ dùng ký tự `:` làm separator) rồi truyền chúng trong username property của `UsernamePasswordAuthenticationToken`.

Bạn cũng cần tùy chỉnh authentication process thực tế.
Ví dụ, nếu dùng custom authentication token class, bạn phải viết một `AuthenticationProvider` (hoặc extend `DaoAuthenticationProvider` tiêu chuẩn) để xử lý nó. Nếu đã nối các field, bạn có thể triển khai `UserDetailsService` của riêng mình để tách chúng ra và load user data phù hợp cho authentication.

[[appendix-faq-matching-url-fragments]]
=== Làm thế nào để áp dụng các intercept-url constraint khác nhau khi các URL được request chỉ khác nhau ở fragment (chẳng hạn /thing1#thing2 và /thing1#thing3)?

Bạn không thể làm vậy, vì fragment không được truyền từ browser đến server.
Từ góc nhìn server, các URL là giống hệt nhau.
Đây là câu hỏi phổ biến từ GWT user.

[[appendix-faq-request-details-in-user-service]]
=== Làm thế nào để truy cập IP Address của user (hoặc web-request data khác) trong UserDetailsService?

Bạn không thể (trừ khi dùng một thứ như thread-local variable), vì thông tin duy nhất được cung cấp cho interface là username.
Thay vì triển khai `UserDetailsService`, bạn nên triển khai trực tiếp `AuthenticationProvider` và trích xuất thông tin từ `Authentication` token được cung cấp.

Trong web setup tiêu chuẩn, method `getDetails()` trên `Authentication` object sẽ trả về một instance của `WebAuthenticationDetails`. Nếu cần thêm thông tin, bạn có thể inject custom `AuthenticationDetailsSource` vào authentication filter đang sử dụng.
Nếu dùng namespace, chẳng hạn với element `<form-login>`, bạn nên xóa element này và thay bằng declaration `<custom-filter>` trỏ đến `UsernamePasswordAuthenticationFilter` được cấu hình tường minh.


[[appendix-faq-access-session-from-user-service]]
=== Làm thế nào để truy cập HttpSession từ UserDetailsService?

Bạn không thể, vì `UserDetailsService` không biết về servlet API. Nếu muốn lưu custom user data, bạn nên tùy chỉnh `UserDetails` object được trả về.
Sau đó có thể truy cập object này ở bất kỳ đâu thông qua `SecurityContextHolder` thread-local. Lời gọi `SecurityContextHolder.getContext().getAuthentication().getPrincipal()` trả về custom object này.

Nếu thực sự cần truy cập session, bạn phải làm vậy bằng cách tùy chỉnh web tier.


[[appendix-faq-password-in-user-service]]
=== Làm thế nào để truy cập password của user trong UserDetailsService?

Bạn không thể (và cũng không nên, ngay cả khi tìm được cách). Có lẽ bạn đang hiểu sai mục đích của nó.
Xem "<<appendix-faq-what-is-userdetailservice,UserDetailsService là gì?>>" ở phần trước của FAQ.


[[appendix-faq-dynamic-url-metadata]]
=== Làm thế nào để định nghĩa động các URL được bảo vệ trong application?

Mọi người thường hỏi cách lưu mapping giữa URL được bảo vệ và security metadata attribute trong database thay vì trong application context.

Điều đầu tiên bạn nên tự hỏi là liệu có thực sự cần làm vậy không.
Nếu application cần an toàn, security cũng cần được test kỹ lưỡng dựa trên một policy đã định nghĩa.
Có thể cần auditing và acceptance testing trước khi đưa vào production environment.
Một tổ chức coi trọng security cần nhận thức rằng lợi ích từ quy trình test kỹ lưỡng có thể bị xóa sạch ngay lập tức nếu cho phép sửa security setting tại runtime bằng cách thay đổi một hoặc hai row trong configuration database.
Nếu đã cân nhắc điều này (có thể bằng cách sử dụng nhiều layer security trong application), Spring Security cho phép bạn tùy chỉnh hoàn toàn source của security metadata.
Bạn có thể làm cho nó hoàn toàn dynamic nếu muốn.

Cả method security và web security đều được bảo vệ bởi các implementation của `AuthorizationManager`.
Đối với web security, bạn có thể cung cấp implementation riêng của `AuthorizationManager<RequestAuthorizationContext>` và truyền nó cho filter chain DSL như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class DynamicAuthorizationManager implements AuthorizationManager<RequestAuthorizationContext> {
	private final MyExternalAuthorizationService authz;

	// ...

    @Override
    public AuthorizationResult authorize(Supplier<Authentication> authentication, RequestAuthorizationContext context) {
		// query the external service
    }
}

// ...

http
    .authorizeHttpRequests((authorize) -> authorize.anyRequest().access(dynamicAuthorizationManager))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class DynamicAuthorizationManager : AuthorizationManager<RequestAuthorizationContext?> {
    private val rules: MyAuthorizationRulesRepository? = null

    // ...

    override fun authorize(authentication: Supplier<Authentication?>?, context: RequestAuthorizationContext?): AuthorizationResult {
		// look up rules from the database
    }
}

// ...

http {
    authorizeHttpRequests {
        authorize(anyRequest, dynamicAuthorizationManager)
    }
}
----
======

Đối với method security, bạn có thể cung cấp implementation riêng của `AuthorizationManager<MethodInvocation>` và truyền nó cho Spring AOP như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class DynamicAuthorizationManager implements AuthorizationManager<MethodInvocation> {
	private final MyExternalAuthorizationService authz;

	// ...

    @Override
    public AuthorizationResult authorize(Supplier<Authentication> authentication, MethodInvocation invocation) {
		// query the external service
    }
}

// ...

@Bean
static Advisor securedAuthorizationAdvisor(DynamicAuthorizationManager dynamicAuthorizationManager) {
    return AuthorizationManagerBeforeMethodInterceptor.secured(dynamicAuthorizationManager)
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class DynamicAuthorizationManager : AuthorizationManager<MethodInvocation?> {
    private val authz: MyExternalAuthorizationService? = null

     // ...
    override fun authorize(authentication: Supplier<Authentication?>?, invocation: MethodInvocation?): AuthorizationResult {
		// query the external service
    }
}

companion object {
    @Bean
    fun securedAuthorizationAdvisor(dynamicAuthorizationManager: DynamicAuthorizationManager): Advisor {
        return AuthorizationManagerBeforeMethodInterceptor.preAuthorize(dynamicAuthorizationManager)
    }
}
----
======


[[appendix-faq-ldap-authorities]]
=== Làm thế nào để authenticate với LDAP nhưng load các role của user từ database?

Bean `LdapAuthenticationProvider` (xử lý LDAP authentication thông thường trong Spring Security) được cấu hình với hai strategy interface riêng biệt: một interface thực hiện authentication và một interface load các authority của user, lần lượt có tên `LdapAuthenticator` và `LdapAuthoritiesPopulator`.
`DefaultLdapAuthoritiesPopulator` load các authority của user từ LDAP directory và có nhiều configuration parameter để bạn chỉ định cách truy xuất chúng.

Để sử dụng JDBC thay thế, bạn có thể tự triển khai interface bằng SQL phù hợp với schema của mình:

[tabs]
======
Java::
+
[source,java,role="primary"]
----

public class MyAuthoritiesPopulator implements LdapAuthoritiesPopulator {
    @Autowired
    JdbcTemplate template;

    List<GrantedAuthority> getGrantedAuthorities(DirContextOperations userData, String username) {
        return template.query("select role from roles where username = ?",
                new String[] {username},
                new RowMapper<GrantedAuthority>() {
             /**
             *  We're assuming here that you're using the standard convention of using the role
             *  prefix "ROLE_" to mark attributes which are supported by Spring Security's RoleVoter.
             */
            @Override
            public GrantedAuthority mapRow(ResultSet rs, int rowNum) throws SQLException {
                return new SimpleGrantedAuthority("ROLE_" + rs.getString(1));
            }
        });
    }
}

----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class MyAuthoritiesPopulator : LdapAuthoritiesPopulator {
    @Autowired
    lateinit var template: JdbcTemplate

    override fun getGrantedAuthorities(userData: DirContextOperations, username: String): MutableList<GrantedAuthority?> {
        return template.query("select role from roles where username = ?",
            arrayOf(username)
        ) { rs, _ ->
            /**
             * We're assuming here that you're using the standard convention of using the role
             * prefix "ROLE_" to mark attributes which are supported by Spring Security's RoleVoter.
             */
            SimpleGrantedAuthority("ROLE_" + rs.getString(1))
        }
    }
}
----
======

Sau đó, bạn thêm một bean thuộc kiểu này vào application context và inject nó vào `LdapAuthenticationProvider`. Việc này được đề cập trong phần cấu hình LDAP bằng explicit Spring bean ở chapter LDAP của reference manual.
Lưu ý rằng trong trường hợp này bạn không thể sử dụng namespace để cấu hình.
Bạn cũng nên tham khảo xref:attachment$api/java/index.html[Javadoc] cho các class và interface liên quan.


[[appendix-faq-namespace-post-processor]]
=== Tôi muốn sửa property của bean được namespace tạo ra, nhưng schema không có gì hỗ trợ việc đó. Tôi có thể làm gì mà không phải từ bỏ việc sử dụng namespace?

Chức năng namespace được giới hạn có chủ ý, vì vậy không bao quát mọi việc bạn có thể làm với plain bean.
Nếu muốn làm điều gì đó đơn giản, chẳng hạn sửa một bean hoặc inject dependency khác, bạn có thể thực hiện bằng cách thêm `BeanPostProcessor` vào configuration.
Bạn có thể tìm thêm thông tin trong {spring-framework-reference-url}core/beans/factory-extension.html#beans-factory-extension-bpp[Spring Reference Manual]. Để làm vậy, bạn cần biết một chút về các bean được tạo ra, vì vậy cũng nên đọc bài blog được đề cập trong câu hỏi trước về <<appendix-faq-namespace-to-bean-mapping,cách namespace map tới Spring bean>>.

Thông thường, bạn sẽ thêm functionality cần thiết vào method `postProcessBeforeInitialization` của `BeanPostProcessor`. Giả sử bạn muốn tùy chỉnh `AuthenticationDetailsSource` được `UsernamePasswordAuthenticationFilter` sử dụng (được tạo bởi element `form-login`). Bạn muốn trích xuất một header cụ thể có tên `CUSTOM_HEADER` từ request và sử dụng nó khi authenticate user.
Processor class sẽ có dạng như listing sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class CustomBeanPostProcessor implements BeanPostProcessor {

		public Object postProcessAfterInitialization(Object bean, String name) {
				if (bean instanceof UsernamePasswordAuthenticationFilter) {
						System.out.println("********* Post-processing " + name);
						((UsernamePasswordAuthenticationFilter)bean).setAuthenticationDetailsSource(
										new AuthenticationDetailsSource() {
												public Object buildDetails(Object context) {
														return ((HttpServletRequest)context).getHeader("CUSTOM_HEADER");
												}
										});
				}
				return bean;
		}

		public Object postProcessBeforeInitialization(Object bean, String name) {
				return bean;
		}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class CustomBeanPostProcessor : BeanPostProcessor {
    override fun postProcessAfterInitialization(bean: Any, name: String): Any {
        if (bean is UsernamePasswordAuthenticationFilter) {
            println("********* Post-processing $name")
            bean.setAuthenticationDetailsSource(
                AuthenticationDetailsSource<HttpServletRequest, Any?> { context -> context.getHeader("CUSTOM_HEADER") })
        }
        return bean
    }

    override fun postProcessBeforeInitialization(bean: Any, name: String?): Any {
        return bean
    }
}
----
======

Sau đó, bạn đăng ký bean này trong application context.
Spring tự động invoke processor này trên các bean được định nghĩa trong application context.
