[[community]]
= Cộng đồng Spring Security

Chào mừng bạn đến với Cộng đồng Spring Security!
Phần này thảo luận về cách bạn có thể tận dụng tối đa cộng đồng rộng lớn của chúng ta.


[[community-help]]
== Nhận trợ giúp
Nếu bạn cần trợ giúp về Spring Security, chúng tôi sẵn sàng hỗ trợ.
Dưới đây là một số cách tốt nhất để nhận trợ giúp:

* Đọc tài liệu này.
* Thử một trong nhiều xref:samples.adoc#samples[ứng dụng mẫu] của chúng tôi.
* Đặt câu hỏi trên https://stackoverflow.com/questions/tagged/spring-security[https://stackoverflow.com] với thẻ `spring-security`.
* Báo cáo lỗi và yêu cầu cải tiến tại https://github.com/spring-projects/spring-security/issues

[[community-becoming-involved]]
== Tham gia đóng góp
Chúng tôi hoan nghênh sự tham gia của bạn vào dự án Spring Security.
Có nhiều cách để đóng góp, bao gồm trả lời câu hỏi trên Stack Overflow, viết mã mới, cải thiện mã hiện có, hỗ trợ tài liệu, phát triển các ví dụ mẫu hoặc hướng dẫn, báo cáo lỗi, hoặc đơn giản là đưa ra đề xuất.
Để biết thêm thông tin, hãy xem https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc[Tài liệu đóng góp] của chúng tôi.

[[community-source]]
== Mã nguồn

Bạn có thể tìm mã nguồn của Spring Security trên GitHub tại https://github.com/spring-projects/spring-security/

[[community-license]]
== Giấy phép Apache 2

Spring Security là phần mềm mã nguồn mở được phát hành theo https://www.apache.org/licenses/LICENSE-2.0.html[giấy phép Apache 2.0].

== Mạng xã hội

Bạn có thể theo dõi https://twitter.com/SpringSecurity[@SpringSecurity] và https://twitter.com/SpringSecurity/lists/team[nhóm Spring Security] trên Twitter để cập nhật những tin tức mới nhất.
Bạn cũng có thể theo dõi https://twitter.com/SpringCentral[@SpringCentral] để cập nhật thông tin về toàn bộ danh mục Spring.
