[[getting]]
[[getting-gradle]]
= Lấy Spring Security

Phần này mô tả cách lấy các tệp nhị phân của Spring Security.
Xem xref:community.adoc#community-source[Mã nguồn] để biết cách lấy mã nguồn.

== Đánh số phiên bản

Các phiên bản Spring Security được định dạng theo MAJOR.MINOR.PATCH như sau:

* Các phiên bản MAJOR có thể chứa các thay đổi gây lỗi tương thích.
Thông thường, những thay đổi này được thực hiện để cải thiện bảo mật nhằm phù hợp với các thực hành bảo mật hiện đại.
* Các phiên bản MINOR chứa những cải tiến nhưng được xem là các bản cập nhật thụ động.
* Cấp độ PATCH phải hoàn toàn tương thích theo cả hai chiều, với các phiên bản trước và sau, ngoại trừ khả năng có những thay đổi sửa lỗi.


[[maven]]
== Cách sử dụng

Giống như hầu hết các dự án mã nguồn mở, Spring Security triển khai các dependency của mình dưới dạng artifact Maven, nhờ đó chúng tương thích với cả Maven và Gradle. Các phần sau minh họa cách tích hợp Spring Security với những build tool này, kèm các ví dụ cho Spring Boot và cách sử dụng độc lập.

[[getting-maven-boot]]
[[getting-gradle-boot]]
=== Spring Boot

Spring Boot cung cấp một starter `spring-boot-starter-security` tập hợp các dependency liên quan đến Spring Security.
Cách đơn giản nhất và được ưu tiên để sử dụng starter là dùng https://docs.spring.io/initializr/docs/current/reference/html/[Spring Initializr] thông qua tích hợp IDE trong (https://joshlong.com/jl/blogPost/tech_tip_geting_started_with_spring_boot.html[Eclipse] hoặc https://www.jetbrains.com/help/idea/spring-boot.html#d1489567e2[IntelliJ], https://github.com/AlexFalappa/nb-springboot/wiki/Quick-Tour[NetBeans]) hoặc thông qua https://start.spring.io.
Ngoài ra, bạn có thể thêm starter theo cách thủ công, như trong ví dụ sau:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... other dependency elements ... -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-security</artifactId>
	</dependency>
</dependencies>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	implementation "org.springframework.boot:spring-boot-starter-security"
}
----
======

Vì Spring Boot cung cấp một Maven BOM để quản lý các phiên bản dependency, bạn không cần chỉ định phiên bản.
Nếu muốn ghi đè phiên bản Spring Security, bạn có thể thực hiện bằng một build property như minh họa dưới đây:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring-security.version>{spring-security-version}</spring-security.version>
</properties>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring-security.version']='{spring-security-version}'
----
======

Vì Spring Security chỉ thực hiện các thay đổi gây lỗi tương thích trong những bản phát hành major, bạn có thể an toàn sử dụng phiên bản Spring Security mới hơn với Spring Boot.
Tuy nhiên, đôi khi bạn cũng cần cập nhật phiên bản Spring Framework.
Bạn có thể thực hiện việc đó bằng cách thêm một build property như sau:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring.version>{spring-core-version}</spring.version>
</properties>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring.version']='{spring-core-version}'
----
======

Nếu sử dụng các tính năng bổ sung (chẳng hạn LDAP, OAuth 2 và những tính năng khác), bạn cũng cần bao gồm xref:modules.adoc#modules[Các module và dependency của project] phù hợp.

[[getting-maven-no-boot]]
=== Cách sử dụng độc lập (Không có Spring Boot)

Khi sử dụng Spring Security không có Spring Boot, cách được ưu tiên là sử dụng BOM của Spring Security để đảm bảo một phiên bản Spring Security nhất quán được sử dụng trong toàn bộ project.

[tabs]
======
Maven::
+
.pom.xml
[source,xml,ubs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... other dependency elements ... -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-bom</artifactId>
			<version>{spring-security-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.security:spring-security-bom:{spring-security-version}'
	}
}
----
======

[TIP]
Spring cung cấp https://github.com/spring-gradle-plugins/dependency-management-plugin[`Dependency Management Plugin`] cho Gradle

Một tập dependency Maven tối thiểu cho Spring Security thường có dạng như ví dụ sau:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... other dependency elements ... -->
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-web</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-config</artifactId>
	</dependency>
</dependencies>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	implementation "org.springframework.security:spring-security-web"
	implementation "org.springframework.security:spring-security-config"
}
----
======

Nếu sử dụng các tính năng bổ sung (chẳng hạn LDAP, OAuth 2 và những tính năng khác), bạn cũng cần bao gồm xref:modules.adoc#modules[Các module và dependency của project] phù hợp.

Spring Security được build dựa trên Spring Framework {spring-core-version} nhưng nhìn chung sẽ hoạt động với mọi phiên bản mới hơn của Spring Framework 5.x.
Nhiều người dùng có thể gặp vấn đề vì các dependency bắc cầu của Spring Security phân giải thành Spring Framework {spring-core-version}, điều này có thể gây ra những vấn đề bất thường trên classpath.
Cách dễ nhất để giải quyết vấn đề này là sử dụng `spring-framework-bom` trong phần `<dependencyManagement>` của `pom.xml` hoặc phần `dependencyManagement` của `build.gradle`.

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... other dependency elements ... -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-framework-bom</artifactId>
			<version>{spring-core-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework:spring-framework-bom:{spring-core-version}'
	}
}
----
======

[TIP]
Spring cung cấp https://github.com/spring-gradle-plugins/dependency-management-plugin[`Dependency Management Plugin`] cho Gradle

Ví dụ trước đảm bảo rằng tất cả dependency bắc cầu của Spring Security đều sử dụng các module Spring {spring-core-version}.

[NOTE]
====
Cách tiếp cận này sử dụng khái niệm "`bill of materials`" (BOM) của Maven và chỉ khả dụng trong Maven 2.0.9+.
Để biết thêm chi tiết về cách dependency được phân giải, xem https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Tài liệu Introduction to the Dependency Mechanism của Maven].
====

[[maven-repositories]]
=== Các repository Maven
Tất cả https://github.com/spring-projects/spring-security/wiki/Release-Schedule-Guidelines[bản phát hành GA] đều được triển khai lên Maven Central, vì vậy bạn không cần khai báo thêm Maven repository trong cấu hình build.

Đối với Gradle, sử dụng repository `mavenCentral()` là đủ cho các bản phát hành GA.

.build.gradle
[source,groovy]
----
repositories {
	mavenCentral()
}
----

Nếu sử dụng một phiên bản SNAPSHOT, bạn cần đảm bảo đã định nghĩa Spring Snapshot repository:

[tabs]
======
Maven::
+
.pom.xml
[source,xml]
----
<repositories>
	<!-- ... possibly other repository elements ... -->
	<repository>
		<id>spring-snapshot</id>
		<name>Spring Snapshot Repository</name>
		<url>https://repo.spring.io/snapshot</url>
	</repository>
</repositories>
----

Gradle::
+
.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/snapshot' }
}
----
======

Nếu sử dụng một phiên bản milestone hoặc release candidate, bạn cần đảm bảo đã định nghĩa Spring Milestone repository, như ví dụ sau:

[tabs]
======
Maven::
+
.pom.xml
[source,xml]
----
<repositories>
	<!-- ... possibly other repository elements ... -->
	<repository>
		<id>spring-milestone</id>
		<name>Spring Milestone Repository</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
</repositories>
----

Gradle::
+
.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/milestone' }
}
----
======
