// FIXME: Nội dung này có thể phù hợp hơn trong Getting Spring Security cùng với thông tin artifact

[[modules]]
= Các module và dependency của dự án
Trong Spring Security 3.0, codebase được chia thành các JAR riêng biệt để phân tách rõ hơn các nhóm chức năng khác nhau và dependency của bên thứ ba.
Nếu sử dụng Maven để build dự án, đây là các module bạn nên thêm vào `pom.xml`.
Ngay cả khi không sử dụng Maven, chúng tôi vẫn khuyến nghị bạn tham khảo các file `pom.xml` để hình dung về dependency của bên thứ ba và version.
Một ý tưởng hữu ích khác là xem xét các thư viện được đưa vào các ứng dụng mẫu.

Phần này cung cấp thông tin tham khảo về các module trong Spring Security và các dependency bổ sung mà chúng yêu cầu để hoạt động trong một ứng dụng đang chạy.
Chúng tôi không liệt kê các dependency chỉ được sử dụng khi build hoặc test chính Spring Security.
Chúng tôi cũng không liệt kê các transitive dependency mà các dependency bên ngoài yêu cầu.

Version Spring được yêu cầu được liệt kê trên website của dự án, vì vậy các version cụ thể được bỏ qua đối với dependency của Spring trong các ví dụ.
Lưu ý rằng một số dependency được liệt kê là "`optional`" trong các ví dụ vẫn có thể cần thiết cho các chức năng không liên quan đến security khác trong một ứng dụng Spring.
Ngoài ra, các dependency được liệt kê là "`optional`" có thể thực tế không được đánh dấu như vậy trong các file Maven POM của dự án nếu chúng được sử dụng trong phần lớn ứng dụng.
Chúng chỉ là "`optional`" theo nghĩa bạn không cần chúng trừ khi sử dụng chức năng được chỉ định.

Khi một module phụ thuộc vào module Spring Security khác, các dependency không tùy chọn của module được phụ thuộc cũng được giả định là bắt buộc và không được liệt kê riêng.


[[spring-security-core]]
== Core -- `spring-security-core.jar`
Module này chứa các class và interface authentication và kiểm soát truy cập cốt lõi, hỗ trợ remoting và các provisioning API cơ bản.
Nó được yêu cầu bởi mọi ứng dụng sử dụng Spring Security.
Nó hỗ trợ ứng dụng độc lập, remote client, method security (service layer) và JDBC user provisioning.
Nó chứa các top-level package sau:

* `org.springframework.security.core`
* `org.springframework.security.access`
* `org.springframework.security.authentication`
* `org.springframework.security.provisioning`

.Dependency của Core
|===
| Dependency | Version | Mô tả

| ehcache
| 1.6.2
| Bắt buộc nếu sử dụng implementation user cache dựa trên Ehcache (tùy chọn).

| spring-aop
|
| Method security dựa trên Spring AOP

| spring-beans
|
| Bắt buộc cho cấu hình Spring

| spring-expression
|
| Bắt buộc cho method security dựa trên expression (tùy chọn)

| spring-jdbc
|
| Bắt buộc nếu sử dụng database để lưu trữ user data (tùy chọn).

| spring-tx
|
| Bắt buộc nếu sử dụng database để lưu trữ user data (tùy chọn).

| aspectjrt
| 1.6.10
| Bắt buộc nếu sử dụng hỗ trợ AspectJ (tùy chọn).

| jsr250-api
| 1.0
| Bắt buộc nếu sử dụng annotation method-security JSR-250 (tùy chọn).
|===


[[spring-security-remoting]]
== Remoting -- `spring-security-remoting.jar`
Module này cung cấp integration với Spring Remoting.
Bạn không cần module này trừ khi đang viết một remote client sử dụng Spring Remoting.
Package chính là `org.springframework.security.remoting`.

.Dependency của Remoting
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| spring-web
|
| Bắt buộc cho client sử dụng hỗ trợ HTTP remoting.
|===

[[spring-security-web]]
== Web -- `spring-security-web.jar`
Module này chứa các filter và code infrastructure web-security liên quan.
Nó chứa mọi thành phần có dependency Servlet API.
Bạn cần module này nếu yêu cầu các service web authentication của Spring Security và kiểm soát truy cập dựa trên URL.
Package chính là `org.springframework.security.web`.

.Dependency của Web
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| spring-web
|
| Bắt buộc cho client sử dụng hỗ trợ HTTP remoting.

| spring-jdbc
|
| Bắt buộc cho persistent remember-me token repository dựa trên JDBC (tùy chọn).

| spring-tx
|
| Bắt buộc bởi các implementation persistent token repository của remember-me (tùy chọn).
|===

[[spring-security-config]]
== Config -- `spring-security-config.jar`
Module này chứa code phân tích security namespace và code Java configuration.
Bạn cần module này nếu sử dụng Spring Security XML namespace để cấu hình hoặc sử dụng hỗ trợ Java Configuration của Spring Security.
Package chính là `org.springframework.security.config`.
Không class nào được thiết kế để sử dụng trực tiếp trong ứng dụng.

.Dependency của Config
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| spring-security-web
|
| Bắt buộc nếu sử dụng bất kỳ namespace configuration nào liên quan đến web (tùy chọn).

| spring-security-ldap
|
| Bắt buộc nếu sử dụng các tùy chọn LDAP namespace (tùy chọn).

| aspectjweaver
| 1.6.10
| Bắt buộc nếu sử dụng cú pháp protect-pointcut namespace (tùy chọn).
|===

[[spring-security-ldap]]
== LDAP -- `spring-security-ldap.jar`
Module này cung cấp code LDAP authentication và provisioning.
Nó được yêu cầu nếu cần sử dụng LDAP authentication hoặc quản lý LDAP user entry.
Top-level package là `org.springframework.security.ldap`.

.Dependency của LDAP
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| spring-ldap-core
| 1.3.0
| Hỗ trợ LDAP dựa trên Spring LDAP.

| spring-tx
|
| Các class data exception là bắt buộc.

| com.unboundid:unboundid-ldapsdk
|
| Bắt buộc nếu sử dụng embedded LDAP server

| ldapsdk
| 4.1
| Mozilla LdapSDK.
Được sử dụng để decode LDAP password policy control, chẳng hạn khi sử dụng chức năng password-policy với OpenLDAP.
|===

[[spring-security-oauth2-core]]
== OAuth 2.0 Core -- `spring-security-oauth2-core.jar`
`spring-security-oauth2-core.jar` chứa các class và interface cốt lõi cung cấp hỗ trợ cho OAuth 2.0 Authorization Framework và OpenID Connect Core 1.0.
Nó được yêu cầu bởi các ứng dụng sử dụng OAuth 2.0 hoặc OpenID Connect Core 1.0, chẳng hạn client, resource server và authorization server.
Top-level package là `org.springframework.security.oauth2.core`.


[[spring-security-oauth2-client]]
== OAuth 2.0 Client -- `spring-security-oauth2-client.jar`
`spring-security-oauth2-client.jar` chứa phần hỗ trợ client của Spring Security cho OAuth 2.0 Authorization Framework và OpenID Connect Core 1.0.
Nó được yêu cầu bởi các ứng dụng sử dụng OAuth 2.0 hoặc OpenID Connect Core 1.0, chẳng hạn client, resource server và authorization server.
Top-level package là `org.springframework.security.oauth2.core`.


[[spring-security-oauth2-jose]]
== OAuth 2.0 JOSE -- `spring-security-oauth2-jose.jar`
`spring-security-oauth2-jose.jar` chứa phần hỗ trợ của Spring Security cho framework JOSE (Javascript Object Signing and Encryption).
Framework JOSE được thiết kế để cung cấp một phương thức truyền claim an toàn giữa các bên.
Nó được xây dựng từ một tập hợp các specification:

* JSON Web Token (JWT)
* JSON Web Signature (JWS)
* JSON Web Encryption (JWE)
* JSON Web Key (JWK)

Nó chứa các top-level package sau:

* `org.springframework.security.oauth2.jwt`
* `org.springframework.security.oauth2.jose`

[[spring-security-oauth2-resource-server]]
== OAuth 2.0 Resource Server -- `spring-security-oauth2-resource-server.jar`
`spring-security-oauth2-resource-server.jar` chứa phần hỗ trợ của Spring Security cho OAuth 2.0 Resource Server.
Nó được sử dụng để bảo vệ API bằng OAuth 2.0 Bearer Token.
Top-level package là `org.springframework.security.oauth2.server.resource`.

[[spring-security-acl]]
== ACL -- `spring-security-acl.jar`
Module này chứa một implementation ACL chuyên biệt cho domain object.
Nó được sử dụng để áp dụng security cho các instance domain object cụ thể trong ứng dụng.
Top-level package là `org.springframework.security.acls`.

.Dependency của ACL
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| ehcache
| 1.6.2
| Bắt buộc nếu sử dụng implementation ACL cache dựa trên Ehcache (tùy chọn nếu sử dụng implementation của riêng bạn).

| spring-jdbc
|
| Bắt buộc nếu sử dụng AclService mặc định dựa trên JDBC (tùy chọn nếu tự triển khai).

| spring-tx
|
| Bắt buộc nếu sử dụng AclService mặc định dựa trên JDBC (tùy chọn nếu tự triển khai).
|===

[[spring-security-cas]]
== CAS -- `spring-security-cas.jar`
Module này chứa integration CAS client của Spring Security.
Bạn nên sử dụng module này nếu muốn sử dụng web authentication của Spring Security với CAS single sign-on server.
Top-level package là `org.springframework.security.cas`.

.Dependency của CAS
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| spring-security-web
|
|

| cas-client-core
| 3.1.12
| JA-SIG CAS Client.
Đây là nền tảng của integration Spring Security.

| ehcache
| 1.6.2
| Bắt buộc nếu sử dụng ticket cache dựa trên Ehcache (tùy chọn).
|===


[[spring-security-test]]
== Test -- `spring-security-test.jar`
Module này cung cấp hỗ trợ test với Spring Security.

[[spring-security-taglibs]]
== Taglibs -- `spring-security-taglibs.jar`
Cung cấp các implementation JSP tag của Spring Security.

.Dependency của Taglib
|===
| Dependency | Version | Mô tả

| spring-security-core
|
|

| spring-security-web
|
|

| spring-security-acl
|
| Bắt buộc nếu sử dụng tag `accesscontrollist` hoặc expression `hasPermission()` với ACL (tùy chọn).

| spring-expression
|
| Bắt buộc nếu sử dụng expression SPEL trong access constraint của tag.
|===
