= Cấu hình cốt lõi

[[oauth2login-sample-boot]]
== Ví dụ Spring Boot

Spring Boot cung cấp đầy đủ khả năng auto-configuration cho OAuth 2.0 Login.

Phần này trình bày cách cấu hình {gh-samples-url}/servlet/spring-boot/java/oauth2/login[*ví dụ OAuth 2.0 Login*] bằng cách sử dụng _Google_ làm _Authentication Provider_ và bao quát các chủ đề sau:

* <<oauth2login-sample-initial-setup>>
* <<oauth2login-sample-redirect-uri>>
* <<oauth2login-sample-application-config>>
* <<oauth2login-sample-boot-application>>


[[oauth2login-sample-initial-setup]]
=== Thiết lập ban đầu

Để sử dụng hệ thống authentication OAuth 2.0 của Google để đăng nhập, bạn phải thiết lập một dự án trong Google API Console để lấy các OAuth 2.0 credentials.

[NOTE]
====
https://developers.google.com/identity/protocols/OpenIDConnect[Triển khai OAuth 2.0 của Google] cho authentication tuân thủ đặc tả https://openid.net/connect/[OpenID Connect 1.0] và được https://openid.net/certification/[chứng nhận OpenID].
====

Làm theo hướng dẫn trên trang https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect], bắt đầu từ phần "`Thiết lập OAuth 2.0`".

Sau khi hoàn tất hướng dẫn "`Lấy OAuth 2.0 credentials`", bạn sẽ có một OAuth Client mới với credentials bao gồm Client ID và Client Secret.


[[oauth2login-sample-redirect-uri]]
=== Thiết lập redirect URI

redirect URI là path trong application mà user-agent của end-user được redirect về sau khi họ đã authenticated với Google và được cấp quyền truy cập vào OAuth Client (<<oauth2login-sample-initial-setup,được tạo ở bước trước>>) trên trang Consent.

Trong phần "`Thiết lập redirect URI`", đảm bảo trường *Authorized redirect URIs* được đặt thành `http://localhost:8080/login/oauth2/code/google`.

[TIP]
====
Template redirect URI mặc định là `+{baseUrl}/login/oauth2/code/{registrationId}+`.
`registrationId` là identifier duy nhất của xref:servlet/oauth2/client/index.adoc#oauth2Client-client-registration[`ClientRegistration`].
====

[IMPORTANT]
====
Nếu OAuth Client chạy phía sau một proxy server, bạn nên kiểm tra xref:features/exploits/http.adoc#http-proxy-server[Cấu hình máy chủ proxy] để đảm bảo application được cấu hình đúng.
Ngoài ra, xem các xref:servlet/oauth2/client/authorization-grants.adoc#oauth2Client-auth-code-redirect-uri[biến template `URI`] được hỗ trợ cho `redirect-uri`.
====


[[oauth2login-sample-application-config]]
=== Cấu hình application.yml

Bây giờ bạn đã có một OAuth Client mới cho Google, bạn cần cấu hình application để sử dụng OAuth Client cho _authentication flow_.
Để thực hiện việc đó:

. Mở `application.yml` và đặt cấu hình sau:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
+
.Thuộc tính OAuth Client
<1> `spring.security.oauth2.client.registration` là tiền tố thuộc tính cơ sở cho các thuộc tính OAuth Client.
<2> Theo sau tiền tố thuộc tính cơ sở là ID của xref:servlet/oauth2/client/index.adoc#oauth2Client-client-registration[`ClientRegistration`], chẳng hạn như Google.

. Thay thế các giá trị trong thuộc tính `client-id` và `client-secret` bằng các OAuth 2.0 credentials bạn đã tạo trước đó.


[[oauth2login-sample-boot-application]]
=== Khởi động ứng dụng

Khởi chạy ứng dụng mẫu Spring Boot và truy cập `http://localhost:8080`.
Sau đó, bạn được chuyển hướng đến trang login mặc định được _auto-generated_, trang này hiển thị một liên kết tới Google.

Nhấp vào liên kết Google, sau đó bạn được chuyển hướng đến Google để thực hiện authentication.

Sau khi authenticated bằng credentials của tài khoản Google, bạn sẽ thấy màn hình Consent.
Màn hình Consent yêu cầu bạn cho phép hoặc từ chối quyền truy cập vào OAuth Client đã tạo trước đó.
Nhấp *Allow* để ủy quyền cho OAuth Client truy cập địa chỉ email và thông tin profile cơ bản của bạn.

Tại thời điểm này, OAuth Client truy xuất địa chỉ email và thông tin profile cơ bản của bạn từ https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] và thiết lập một session authenticated.


[[oauth2login-boot-property-mappings]]
== Ánh xạ thuộc tính Spring Boot

Bảng sau trình bày ánh xạ giữa các thuộc tính OAuth Client của Spring Boot và các thuộc tính xref:servlet/oauth2/client/index.adoc#oauth2Client-client-registration[ClientRegistration].

|===
|Spring Boot |ClientRegistration

|`spring.security.oauth2.client.registration._[registrationId]_`
|`registrationId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-id`
|`clientId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-secret`
|`clientSecret`

|`spring.security.oauth2.client.registration._[registrationId]_.client-authentication-method`
|`clientAuthenticationMethod`

|`spring.security.oauth2.client.registration._[registrationId]_.authorization-grant-type`
|`authorizationGrantType`

|`spring.security.oauth2.client.registration._[registrationId]_.redirect-uri`
|`redirectUri`

|`spring.security.oauth2.client.registration._[registrationId]_.scope`
|`scopes`

|`spring.security.oauth2.client.registration._[registrationId]_.client-name`
|`clientName`

|`spring.security.oauth2.client.provider._[providerId]_.authorization-uri`
|`providerDetails.authorizationUri`

|`spring.security.oauth2.client.provider._[providerId]_.token-uri`
|`providerDetails.tokenUri`

|`spring.security.oauth2.client.provider._[providerId]_.jwk-set-uri`
|`providerDetails.jwkSetUri`

|`spring.security.oauth2.client.provider._[providerId]_.issuer-uri`
|`providerDetails.issuerUri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-uri`
|`providerDetails.userInfoEndpoint.uri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-authentication-method`
|`providerDetails.userInfoEndpoint.authenticationMethod`

|`spring.security.oauth2.client.provider._[providerId]_.user-name-attribute`
|`providerDetails.userInfoEndpoint.userNameAttributeName`
|===

[TIP]
====
Bạn có thể cấu hình ban đầu một `ClientRegistration` bằng discovery từ https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] của OpenID Connect Provider hoặc https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] của Authorization Server, bằng cách chỉ định thuộc tính `spring.security.oauth2.client.provider._[providerId]_.issuer-uri`.
====


[[oauth2login-common-oauth2-provider]]
== CommonOAuth2Provider

`CommonOAuth2Provider` định nghĩa sẵn một tập các thuộc tính client mặc định cho một số provider phổ biến: Google, GitHub, Facebook, X và Okta.

Ví dụ, `authorization-uri`, `token-uri` và `user-info-uri` thường không thay đổi đối với một provider.
Vì vậy, việc cung cấp các giá trị mặc định là hợp lý để giảm cấu hình cần thiết.

Như đã trình bày trước đó, khi chúng ta <<oauth2login-sample-application-config,đã cấu hình một Google client>>, chỉ cần các thuộc tính `client-id` và `client-secret`.

Đoạn cấu hình sau đây là một ví dụ:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
----

[TIP]
Việc tự động đặt giá trị mặc định cho các thuộc tính client hoạt động liền mạch ở đây vì `registrationId` (`google`) khớp với `enum` `GOOGLE` (không phân biệt hoa thường) trong `CommonOAuth2Provider`.

Trong trường hợp bạn muốn chỉ định một `registrationId` khác, chẳng hạn như `google-login`, bạn vẫn có thể sử dụng cơ chế tự động đặt giá trị mặc định cho các thuộc tính client bằng cách cấu hình thuộc tính `provider`.

Đoạn cấu hình sau đây là một ví dụ:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google-login:	<1>
            provider: google	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
<1> `registrationId` được đặt thành `google-login`.
<2> Thuộc tính `provider` được đặt thành `google`, qua đó sử dụng cơ chế tự động đặt giá trị mặc định cho các thuộc tính client được thiết lập bởi `CommonOAuth2Provider.GOOGLE.getBuilder()`.

[[oauth2login-custom-provider-properties]]
== Cấu hình thuộc tính provider tùy chỉnh

Có một số provider OAuth 2.0 hỗ trợ multi-tenancy, dẫn đến các protocol endpoint khác nhau cho mỗi tenant (hoặc sub-domain).

Ví dụ, một OAuth Client được đăng ký với Okta được gán cho một sub-domain cụ thể và có các protocol endpoint riêng.

Trong các trường hợp này, Spring Boot cung cấp thuộc tính cơ sở sau để cấu hình các thuộc tính provider tùy chỉnh: `spring.security.oauth2.client.provider._[providerId]_`.

Đoạn cấu hình sau đây là một ví dụ:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          okta:	<1>
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
----
<1> Thuộc tính cơ sở (`spring.security.oauth2.client.provider.okta`) cho phép cấu hình tùy chỉnh địa chỉ của các protocol endpoint.

[[oauth2login-override-boot-autoconfig]]
== Ghi đè auto-configuration của Spring Boot

Class auto-configuration của Spring Boot để hỗ trợ OAuth Client là `OAuth2ClientAutoConfiguration`.

Nó thực hiện các tác vụ sau:

* Đăng ký một `ClientRegistrationRepository` `@Bean` được tạo từ các `ClientRegistration` của các thuộc tính OAuth Client đã cấu hình.
* Đăng ký một `SecurityFilterChain` `@Bean` và bật OAuth 2.0 Login thông qua `httpSecurity.oauth2Login()`.

Nếu cần ghi đè auto-configuration dựa trên các yêu cầu cụ thể, bạn có thể thực hiện theo các cách sau:

* <<oauth2login-register-clientregistrationrepository-bean>>
* <<oauth2login-provide-securityfilterchain-bean>>
* <<oauth2login-completely-override-autoconfiguration>>

[[oauth2login-register-clientregistrationrepository-bean]]
=== Đăng ký `ClientRegistrationRepository` @Bean

Ví dụ sau đây cho thấy cách đăng ký một `ClientRegistrationRepository` `@Bean`:

[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
public class OAuth2LoginConfig {

	@Bean
	public ClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
			.clientId("google-client-id")
			.clientSecret("google-client-secret")
			.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
			.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
			.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
			.scope("openid", "profile", "email", "address", "phone")
			.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
			.tokenUri("https://www.googleapis.com/oauth2/v4/token")
			.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
			.userNameAttributeName(IdTokenClaimNames.SUB)
			.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
			.clientName("Google")
			.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
class OAuth2LoginConfig {
    @Bean
    fun clientRegistrationRepository(): ClientRegistrationRepository {
        return InMemoryClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
======


[[oauth2login-provide-securityfilterchain-bean]]
=== Đăng ký `SecurityFilterChain` @Bean

Ví dụ sau đây cho thấy cách đăng ký một `SecurityFilterChain` `@Bean` với `@EnableWebSecurity` và bật OAuth 2.0 Login thông qua `httpSecurity.oauth2Login()`:

.Cấu hình OAuth2 Login
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults());
		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2LoginSecurityConfig {

    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
        }
        return http.build()
    }
}
----
======


[[oauth2login-completely-override-autoconfiguration]]
=== Ghi đè hoàn toàn auto-configuration

Ví dụ sau đây cho thấy cách ghi đè hoàn toàn auto-configuration bằng cách đăng ký một `ClientRegistrationRepository` `@Bean` và một `SecurityFilterChain` `@Bean`.

.Ghi đè auto-configuration
[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
public class OAuth2LoginConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults());
		return http.build();
	}

	@Bean
	public ClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
			.clientId("google-client-id")
			.clientSecret("google-client-secret")
			.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
			.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
			.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
			.scope("openid", "profile", "email", "address", "phone")
			.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
			.tokenUri("https://www.googleapis.com/oauth2/v4/token")
			.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
			.userNameAttributeName(IdTokenClaimNames.SUB)
			.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
			.clientName("Google")
			.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
class OAuth2LoginConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
        }
        return http.build()
    }

    @Bean
    fun clientRegistrationRepository(): ClientRegistrationRepository {
        return InMemoryClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
======


[[oauth2login-javaconfig-wo-boot]]
== Cấu hình Java không có Spring Boot

Nếu bạn không thể sử dụng Spring Boot và muốn cấu hình một trong các provider được định nghĩa sẵn trong `CommonOAuth2Provider` (ví dụ Google), hãy áp dụng cấu hình sau:

.Cấu hình OAuth2 Login
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2LoginConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults());
		return http.build();
	}

	@Bean
	public ClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryClientRegistrationRepository(this.googleClientRegistration());
	}

	@Bean
	public OAuth2AuthorizedClientService authorizedClientService(
			ClientRegistrationRepository clientRegistrationRepository) {
		return new InMemoryOAuth2AuthorizedClientService(clientRegistrationRepository);
	}

	@Bean
	public OAuth2AuthorizedClientRepository authorizedClientRepository(
			OAuth2AuthorizedClientService authorizedClientService) {
		return new AuthenticatedPrincipalOAuth2AuthorizedClientRepository(authorizedClientService);
	}

	private ClientRegistration googleClientRegistration() {
		return CommonOAuth2Provider.GOOGLE.getBuilder("google")
			.clientId("google-client-id")
			.clientSecret("google-client-secret")
			.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
open class OAuth2LoginConfig {
    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
        }
        return http.build()
    }

    @Bean
    open fun clientRegistrationRepository(): ClientRegistrationRepository {
        return InMemoryClientRegistrationRepository(googleClientRegistration())
    }

    @Bean
    open fun authorizedClientService(
        clientRegistrationRepository: ClientRegistrationRepository?
    ): OAuth2AuthorizedClientService {
        return InMemoryOAuth2AuthorizedClientService(clientRegistrationRepository)
    }

    @Bean
    open fun authorizedClientRepository(
        authorizedClientService: OAuth2AuthorizedClientService?
    ): OAuth2AuthorizedClientRepository {
        return AuthenticatedPrincipalOAuth2AuthorizedClientRepository(authorizedClientService)
    }

    private fun googleClientRegistration(): ClientRegistration {
        return CommonOAuth2Provider.GOOGLE.getBuilder("google")
            .clientId("google-client-id")
            .clientSecret("google-client-secret")
            .build()
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http auto-config="true">
	<intercept-url pattern="/**" access="authenticated"/>
	<oauth2-login authorized-client-repository-ref="authorizedClientRepository"/>
</http>

<client-registrations>
	<client-registration registration-id="google"
						 client-id="google-client-id"
						 client-secret="google-client-secret"
						 provider-id="google"/>
</client-registrations>

<b:bean id="authorizedClientService"
		class="org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService"
		autowire="constructor"/>

<b:bean id="authorizedClientRepository"
		class="org.springframework.security.oauth2.client.web.AuthenticatedPrincipalOAuth2AuthorizedClientRepository">
	<b:constructor-arg ref="authorizedClientService"/>
</b:bean>
----
======
