= Logout OIDC

Khi người dùng cuối có thể đăng nhập vào ứng dụng của bạn, điều quan trọng là phải cân nhắc cách họ sẽ logout.

Nói chung, có ba trường hợp sử dụng bạn cần cân nhắc:

1. Tôi chỉ muốn thực hiện logout cục bộ
2. Tôi muốn logout cả ứng dụng của mình và OIDC Provider, do ứng dụng của mình khởi tạo
3. Tôi muốn logout cả ứng dụng của mình và OIDC Provider, do OIDC Provider khởi tạo

[[configure-local-logout]]
== Logout cục bộ

Để thực hiện logout cục bộ, không cần cấu hình OIDC đặc biệt.
Spring Security tự động thiết lập một endpoint logout cục bộ mà bạn có thể xref:servlet/authentication/logout.adoc[cấu hình thông qua DSL `logout()`].

[[configure-client-initiated-oidc-logout]]
== Logout do Client khởi tạo theo OpenID Connect 1.0

OpenID Connect Session Management 1.0 cho phép logout người dùng cuối tại Provider bằng cách sử dụng Client.
Một trong các chiến lược hiện có là https://openid.net/specs/openid-connect-rpinitiated-1_0.html[RP-Initiated Logout].

Nếu OpenID Provider hỗ trợ cả Session Management và https://openid.net/specs/openid-connect-discovery-1_0.html[Discovery], client có thể lấy `URL` `end_session_endpoint` từ https://openid.net/specs/openid-connect-session-1_0.html#OPMetadata[Discovery Metadata] của OpenID Provider.
Bạn có thể thực hiện điều này bằng cách cấu hình `ClientRegistration` với `issuer-uri` như sau:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            ...
        provider:
          okta:
            issuer-uri: https://dev-1234.oktapreview.com
----

Ngoài ra, bạn nên cấu hình `OidcClientInitiatedLogoutSuccessHandler`, class triển khai RP-Initiated Logout, như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2LoginSecurityConfig {

	@Autowired
	private ClientRegistrationRepository clientRegistrationRepository;

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults())
			.logout((logout) -> logout
				.logoutSuccessHandler(oidcLogoutSuccessHandler())
			);
		return http.build();
	}

	private LogoutSuccessHandler oidcLogoutSuccessHandler() {
		OidcClientInitiatedLogoutSuccessHandler oidcLogoutSuccessHandler =
				new OidcClientInitiatedLogoutSuccessHandler(this.clientRegistrationRepository);

		// Thiết lập địa chỉ mà User Agent của End User sẽ được chuyển hướng đến
		// sau khi logout đã được thực hiện tại Provider
		oidcLogoutSuccessHandler.setPostLogoutRedirectUri("{baseUrl}");

		return oidcLogoutSuccessHandler;
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2LoginSecurityConfig {
    @Autowired
    private lateinit var clientRegistrationRepository: ClientRegistrationRepository

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
            logout {
                logoutSuccessHandler = oidcLogoutSuccessHandler()
            }
        }
        return http.build()
    }

    private fun oidcLogoutSuccessHandler(): LogoutSuccessHandler {
        val oidcLogoutSuccessHandler = OidcClientInitiatedLogoutSuccessHandler(clientRegistrationRepository)

        // Thiết lập địa chỉ mà User Agent của End User sẽ được chuyển hướng đến
        // sau khi logout đã được thực hiện tại Provider
        oidcLogoutSuccessHandler.setPostLogoutRedirectUri("{baseUrl}")
        return oidcLogoutSuccessHandler
    }
}
----
======

[NOTE]
====
`OidcClientInitiatedLogoutSuccessHandler` hỗ trợ placeholder `+{baseUrl}+`.
Nếu được sử dụng, base URL của ứng dụng, chẳng hạn `https://app.example.org`, sẽ thay thế placeholder này tại thời điểm request.
====

[NOTE]
====
Theo mặc định, `OidcClientInitiatedLogoutSuccessHandler` chuyển hướng đến URL logout bằng HTTP redirect tiêu chuẩn với method `GET`.
Để thực hiện logout bằng request `POST`, hãy đặt redirect strategy thành `FormPostRedirectStrategy`, chẳng hạn bằng `OidcClientInitiatedLogoutSuccessHandler.setRedirectStrategy(new FormPostRedirectStrategy())`.
====

[[configure-provider-initiated-oidc-logout]]
== Logout Back-Channel theo OpenID Connect 1.0

OpenID Connect Session Management 1.0 cho phép logout end user tại Client bằng cách để Provider thực hiện một API call đến Client.
Điều này được gọi là https://openid.net/specs/openid-connect-backchannel-1_0.html[OIDC Back-Channel Logout].

Để bật tính năng này, bạn có thể thiết lập endpoint Back-Channel Logout trong DSL như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
OidcBackChannelLogoutHandler oidcLogoutHandler() {
	return new OidcBackChannelLogoutHandler();
}

@Bean
public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
    http
        .authorizeHttpRequests((authorize) -> authorize
            .anyRequest().authenticated()
        )
        .oauth2Login(withDefaults())
        .oidcLogout((logout) -> logout
            .backChannel(Customizer.withDefaults())
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun oidcLogoutHandler(): OidcBackChannelLogoutHandler {
    return OidcBackChannelLogoutHandler()
}

@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        authorizeHttpRequests {
            authorize(anyRequest, authenticated)
        }
        oauth2Login { }
        oidcLogout {
            backChannel { }
        }
    }
    return http.build()
}
----
======

Sau đó, bạn cần một cách lắng nghe các event do Spring Security publish để xóa các entry `OidcSessionInformation` cũ, như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public HttpSessionEventPublisher sessionEventPublisher() {
    return new HttpSessionEventPublisher();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun sessionEventPublisher(): HttpSessionEventPublisher {
    return HttpSessionEventPublisher()
}
----
======

Điều này đảm bảo rằng khi `HttpSession#invalidate` được gọi, session cũng được xóa khỏi memory.

Vậy là xong!

Điều này sẽ thiết lập endpoint `+/logout/connect/back-channel/{registrationId}+` mà OIDC Provider có thể request để invalidate một session cụ thể của người dùng cuối trong ứng dụng của bạn.

[NOTE]
`oidcLogout` yêu cầu `oauth2Login` cũng phải được cấu hình.

[NOTE]
`oidcLogout` yêu cầu session cookie phải có tên `JSESSIONID` để logout chính xác từng session thông qua backchannel.

=== Kiến trúc Logout Back-Channel

Hãy xét một `ClientRegistration` có identifier là `registrationId`.

Luồng tổng thể của Back-Channel logout như sau:

1. Tại thời điểm đăng nhập, Spring Security liên kết ID Token, CSRF Token và Provider Session ID (nếu có) với session id của ứng dụng trong implementation `OidcSessionRegistry`.
2. Sau đó, tại thời điểm logout, OIDC Provider của bạn thực hiện API call đến `/logout/connect/back-channel/registrationId`, kèm theo Logout Token cho biết `sub` (người dùng cuối) hoặc `sid` (Provider Session ID) cần logout.
3. Spring Security kiểm tra chữ ký và các claim của token.
4. Nếu token chứa claim `sid`, chỉ session của Client liên kết với provider session đó mới bị kết thúc.
5. Nếu không, nếu token chứa claim `sub`, tất cả session của Client tương ứng với người dùng cuối đó sẽ bị kết thúc.

[NOTE]
Hãy nhớ rằng hỗ trợ OIDC của Spring Security là multi-tenant.
Điều này có nghĩa là nó chỉ kết thúc các session có Client khớp với claim `aud` trong Logout Token.

Một điểm đáng chú ý trong implementation của kiến trúc này là nó truyền request back-channel đến nội bộ cho từng session tương ứng.
Thoạt đầu, điều này có vẻ không cần thiết.
Tuy nhiên, hãy nhớ rằng Servlet API không cung cấp quyền truy cập trực tiếp vào `HttpSession` store.
Bằng cách thực hiện một logout call nội bộ, session tương ứng giờ đây có thể được invalidate.

Ngoài ra, việc giả lập logout call nội bộ cho phép chạy từng tập hợp ``LogoutHandler`` trên session đó và `SecurityContext` tương ứng.

=== Tùy chỉnh Session Logout Endpoint

Khi `OidcBackChannelLogoutHandler` được publish, session logout endpoint là `+{baseUrl}+/logout/connect/back-channel/+{registrationId}+`.

Nếu `OidcBackChannelLogoutHandler` không được wire, URL sẽ là `+{baseUrl}+/logout/connect/back-channel/+{registrationId}+`. Cách này không được khuyến nghị vì yêu cầu truyền một CSRF token, điều có thể khó thực hiện tùy thuộc vào loại repository mà ứng dụng của bạn sử dụng.

Nếu cần tùy chỉnh endpoint, bạn có thể cung cấp URL như sau:


[tabs]
======

Java::
+
[source=java,role="primary"]
----
http
    // ...
    .oidcLogout((oidc) -> oidc
        .backChannel((backChannel) -> backChannel
            .logoutUri("http://localhost:9000/logout/connect/back-channel/+{registrationId}+")
        )
    );
----

Kotlin::
+
[source=kotlin,role="secondary"]
----
http {
    oidcLogout {
        backChannel {
            logoutUri = "http://localhost:9000/logout/connect/back-channel/+{registrationId}+"
        }
    }
}
----
======

=== Tùy chỉnh tên Session Logout Cookie

Theo mặc định, session logout endpoint sử dụng cookie `JSESSIONID` để liên kết session với `OidcSessionInformation` tương ứng.

Tuy nhiên, tên cookie mặc định trong Spring Session là `SESSION`.

Bạn có thể cấu hình tên cookie của Spring Session trong DSL như sau:

[tabs]
======
Java::
+
[source=java,role="primary"]
----
@Bean
OidcBackChannelLogoutHandler oidcLogoutHandler(OidcSessionRegistry oidcSessionRegistry) {
    OidcBackChannelLogoutHandler logoutHandler = new OidcBackChannelLogoutHandler(oidcSessionRegistry);
    logoutHandler.setSessionCookieName("SESSION");
    return logoutHandler;
}
----

Kotlin::
+
[source=kotlin,role="secondary"]
----
@Bean
open fun oidcLogoutHandler(val sessionRegistry: OidcSessionRegistry): OidcBackChannelLogoutHandler {
    val logoutHandler = OidcBackChannelLogoutHandler(sessionRegistry)
    logoutHandler.setSessionCookieName("SESSION")
    return logoutHandler
}
----
======

[[oidc-backchannel-logout-session-registry]]
=== Tùy chỉnh OIDC Provider Session Registry

Theo mặc định, Spring Security lưu trong memory tất cả liên kết giữa OIDC Provider session và Client session.

Có một số trường hợp, chẳng hạn ứng dụng dạng cluster, trong đó sẽ thuận tiện hơn nếu lưu thông tin này ở một nơi riêng biệt, chẳng hạn database.

Bạn có thể thực hiện điều này bằng cách cấu hình `OidcSessionRegistry` tùy chỉnh như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public final class MySpringDataOidcSessionRegistry implements OidcSessionRegistry {
    private final OidcProviderSessionRepository sessions;

    // ...

    @Override
    public void saveSessionInformation(OidcSessionInformation info) {
        this.sessions.save(info);
    }

    @Override
    public OidcSessionInformation removeSessionInformation(String clientSessionId) {
       return this.sessions.removeByClientSessionId(clientSessionId);
    }

    @Override
    public Iterable<OidcSessionInformation> removeSessionInformation(OidcLogoutToken token) {
        return token.getSessionId() != null ?
            this.sessions.removeBySessionIdAndIssuerAndAudience(...) :
            this.sessions.removeBySubjectAndIssuerAndAudience(...);
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class MySpringDataOidcSessionRegistry: OidcSessionRegistry {
    val sessions: OidcProviderSessionRepository

    // ...

    @Override
    fun saveSessionInformation(info: OidcSessionInformation) {
        this.sessions.save(info)
    }

    @Override
    fun removeSessionInformation(clientSessionId: String): OidcSessionInformation {
       return this.sessions.removeByClientSessionId(clientSessionId);
    }

    @Override
    fun removeSessionInformation(token: OidcLogoutToken): Iterable<OidcSessionInformation> {
        return token.getSessionId() != null ?
            this.sessions.removeBySessionIdAndIssuerAndAudience(...) :
            this.sessions.removeBySubjectAndIssuerAndAudience(...);
    }
}
----
======
