[[servlet-authentication-caching-user-details]]
= Caching `UserDetails`

Spring Security cung cấp hỗ trợ caching `UserDetails` bằng <<servlet-authentication-caching-user-details-service,`CachingUserDetailsService`>>.
Ngoài ra, bạn có thể sử dụng annotation <<servlet-authentication-caching-user-details-cacheable,`@Cacheable`>> của Spring Framework.
Trong cả hai trường hợp, bạn cần <<servlet-authentication-caching-user-details-credential-erasure,vô hiệu hóa việc xóa credential>> để validate các password được retrieve từ cache.

[[servlet-authentication-caching-user-details-service]]
== `CachingUserDetailsService`

`CachingUserDetailsService` của Spring Security triển khai xref:servlet/authentication/passwords/user-details-service.adoc#servlet-authentication-userdetailsservice[UserDetailsService] để cung cấp hỗ trợ caching `UserDetails`.
`CachingUserDetailsService` cung cấp hỗ trợ caching `UserDetails` bằng cách delegate cho `UserDetailsService` được cung cấp.
Kết quả sau đó được lưu vào một `UserCache` để giảm lượng computation cần thực hiện trong các lần gọi tiếp theo.

Ví dụ sau chỉ cần định nghĩa một `@Bean` đóng gói một implementation cụ thể của `UserDetailsService` và một `UserCache` để caching `UserDetails`:

.Cung cấp một `CachingUserDetailsService` `@Bean`
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public CachingUserDetailsService cachingUserDetailsService(UserCache userCache) {
	UserDetailsService delegate = ...;
    CachingUserDetailsService service = new CachingUserDetailsService(delegate);
    service.setUserCache(userCache);
    return service;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun cachingUserDetailsService(userCache: UserCache): CachingUserDetailsService {
    val delegate: UserDetailsService = ...
    val service = CachingUserDetailsService(delegate)
    service.userCache = userCache
    return service
}
----
======

[[servlet-authentication-caching-user-details-cacheable]]
== `@Cacheable`

Một cách tiếp cận khác là sử dụng {spring-framework-reference-url}integration.html#cache-annotations-cacheable[`@Cacheable`] của Spring Framework trong implementation `UserDetailsService` để cache `UserDetails` theo `username`.
Lợi ích của cách tiếp cận này là configuration đơn giản hơn, đặc biệt nếu application của bạn đã sử dụng caching ở nơi khác.

Ví dụ sau giả định caching đã được cấu hình và annotate `loadUserByUsername` bằng `@Cacheable`:

.`UserDetailsService` được annotate bằng `@Cacheable`
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Service
public class MyCustomUserDetailsImplementation implements UserDetailsService {

    @Override
    @Cacheable
    public UserDetails loadUserByUsername(String username) {
        // some logic here to get the actual user details
        return userDetails;
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Service
class MyCustomUserDetailsImplementation : UserDetailsService {

    @Cacheable
    override fun loadUserByUsername(username: String): UserDetails {
        // some logic here to get the actual user details
        return userDetails
    }
}
----
======

[[servlet-authentication-caching-user-details-credential-erasure]]
== Vô hiệu hóa việc xóa credential

Dù sử dụng <<servlet-authentication-caching-user-details-service,`CachingUserDetailsService`>> hay <<servlet-authentication-caching-user-details-cacheable,`@Cacheable`>>, bạn cần vô hiệu hóa xref:servlet/authentication/architecture.adoc#servlet-authentication-providermanager-erasing-credentials[việc xóa credential] để `UserDetails` chứa `password` dùng để validate khi được retrieve từ cache.
Ví dụ sau vô hiệu hóa việc xóa credential đối với `AuthenticationManager` toàn cục bằng cách configure `AuthenticationManagerBuilder` do Spring Security cung cấp:

.Vô hiệu hóa việc xóa credential đối với `AuthenticationManager` toàn cục
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		// ...
		return http.build();
	}

	@Bean
	public UserDetailsService userDetailsService() {
		// Return a UserDetailsService that caches users
		// ...
	}

	@Autowired
	public void configure(AuthenticationManagerBuilder builder) {
		builder.eraseCredentials(false);
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		// ...
		return http.build()
	}

	@Bean
	fun userDetailsService(): UserDetailsService {
		// Return a UserDetailsService that caches users
		// ...
	}

	@Autowired
	fun configure(builder: AuthenticationManagerBuilder) {
		builder.eraseCredentials(false)
	}

}
----
=====
