[[servlet-authentication-credentialscontainer]]
= CredentialsContainer

Interface javadoc:org.springframework.security.core.CredentialsContainer[] cho biết đối tượng triển khai nó chứa dữ liệu nhạy cảm và được Spring Security sử dụng nội bộ để xóa credential của authentication sau khi authentication thành công.
Interface này được hầu hết các domain class nội bộ của Spring Security triển khai, chẳng hạn như javadoc:org.springframework.security.core.userdetails.User[] và javadoc:org.springframework.security.authentication.UsernamePasswordAuthenticationToken[].

`ProviderManager` kiểm tra xem `Authentication` được trả về có triển khai interface này hay không.
Nếu có, xref:servlet/authentication/architecture.adoc#servlet-authentication-providermanager-erasing-credentials[nó gọi method `eraseCredentials`] để xóa credential khỏi đối tượng.

Nếu muốn các đối tượng authentication tùy chỉnh của bạn được xóa credential sau authentication, bạn nên đảm bảo các class đó triển khai interface `CredentialsContainer`.

Những người viết các triển khai `AuthenticationProvider` của riêng mình nên tạo và trả về một đối tượng `Authentication` phù hợp tại đó, không chứa dữ liệu nhạy cảm, thay vì sử dụng interface này.
