[[servlet-authentication-inmemory]]
= Authentication trong bộ nhớ

`InMemoryUserDetailsManager` của Spring Security triển khai xref:servlet/authentication/passwords/user-details-service.adoc#servlet-authentication-userdetailsservice[UserDetailsService] để hỗ trợ authentication dựa trên username/password được lưu trong bộ nhớ.
`InMemoryUserDetailsManager` cung cấp khả năng quản lý `UserDetails` bằng cách triển khai interface `UserDetailsManager`.
Spring Security sử dụng authentication dựa trên `UserDetails` khi được cấu hình để xref:servlet/authentication/passwords/index.adoc#servlet-authentication-unpwd-input[chấp nhận username và password] cho authentication.

Trong ví dụ sau, chúng ta sử dụng xref:features/authentication/password-storage.adoc#authentication-password-storage-boot-cli[Spring Boot CLI] để encode giá trị password là `password` và nhận được password đã encode là `+{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW+`:

.Cấu hình Java cho InMemoryUserDetailsManager
[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Bean
public UserDetailsService users() {
	UserDetails user = User.builder()
		.username("user")
		.password("{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
		.roles("USER")
		.build();
	UserDetails admin = User.builder()
		.username("admin")
		.password("{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
		.roles("USER", "ADMIN")
		.build();
	return new InMemoryUserDetailsManager(user, admin);
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<user-service>
	<user name="user"
		password="{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW"
		authorities="ROLE_USER" />
	<user name="admin"
		password="{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW"
		authorities="ROLE_USER,ROLE_ADMIN" />
</user-service>
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun users(): UserDetailsService {
    val user = User.builder()
        .username("user")
        .password("{bcrypt}$2a$10\$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
        .roles("USER")
        .build()
    val admin = User.builder()
        .username("admin")
        .password("{bcrypt}$2a$10\$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
        .roles("USER", "ADMIN")
        .build()
    return InMemoryUserDetailsManager(user, admin)
}
----
======

Các ví dụ trước lưu password ở định dạng an toàn nhưng trải nghiệm làm quen ban đầu còn nhiều điểm chưa thuận tiện.

Trong ví dụ sau, chúng ta sử dụng xref:features/authentication/password-storage.adoc#authentication-password-storage-dep-getting-started[User.withDefaultPasswordEncoder] để đảm bảo password được lưu trong bộ nhớ được bảo vệ.
Tuy nhiên, cách này không ngăn được việc lấy password bằng cách decompile source code.
Vì lý do này, `User.withDefaultPasswordEncoder` chỉ nên được sử dụng để "`làm quen ban đầu`" và không dành cho production.

.InMemoryUserDetailsManager với User.withDefaultPasswordEncoder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public UserDetailsService users() {
	// The builder will ensure the passwords are encoded before saving in memory
	UserBuilder users = User.withDefaultPasswordEncoder();
	UserDetails user = users
		.username("user")
		.password("password")
		.roles("USER")
		.build();
	UserDetails admin = users
		.username("admin")
		.password("password")
		.roles("USER", "ADMIN")
		.build();
	return new InMemoryUserDetailsManager(user, admin);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun users(): UserDetailsService {
    // The builder will ensure the passwords are encoded before saving in memory
    val users = User.withDefaultPasswordEncoder()
    val user = users
        .username("user")
        .password("password")
        .roles("USER")
        .build()
    val admin = users
        .username("admin")
        .password("password")
        .roles("USER", "ADMIN")
        .build()
    return InMemoryUserDetailsManager(user, admin)
}
----
======

Không có cách đơn giản nào để sử dụng `User.withDefaultPasswordEncoder` với cấu hình dựa trên XML.
Đối với demo hoặc chỉ để bắt đầu sử dụng, bạn có thể thêm tiền tố `+{noop}+` vào password để chỉ ra rằng xref:features/authentication/password-storage.adoc#authentication-password-storage-dpe-format[không được sử dụng encoding]:

.<user-service> `+{noop}+` Cấu hình XML
[source,xml,attrs="-attributes"]
----
<user-service>
	<user name="user"
		password="{noop}password"
		authorities="ROLE_USER" />
	<user name="admin"
		password="{noop}password"
		authorities="ROLE_USER,ROLE_ADMIN" />
</user-service>
----
