[[servlet-authentication-jdbc]]
= JDBC Authentication

`JdbcDaoImpl` của Spring Security triển khai xref:servlet/authentication/passwords/user-details-service.adoc#servlet-authentication-userdetailsservice[`UserDetailsService`] để cung cấp hỗ trợ cho authentication dựa trên username và password được truy xuất bằng JDBC.
`JdbcUserDetailsManager` mở rộng `JdbcDaoImpl` để cung cấp khả năng quản lý `UserDetails` thông qua interface `UserDetailsManager`.
Spring Security sử dụng authentication dựa trên `UserDetails` khi được cấu hình để xref:servlet/authentication/passwords/index.adoc#servlet-authentication-unpwd-input[chấp nhận username/password] cho authentication.

Trong các phần sau, chúng ta thảo luận về:

* <<servlet-authentication-jdbc-schema>> được Spring Security JDBC Authentication sử dụng
* <<servlet-authentication-jdbc-datasource>>
* <<servlet-authentication-jdbc-bean>>

[[servlet-authentication-jdbc-schema]]
== Schema mặc định

Spring Security cung cấp các truy vấn mặc định cho authentication dựa trên JDBC.
Phần này cung cấp các schema mặc định tương ứng được sử dụng cùng với các truy vấn mặc định.
Bạn cần điều chỉnh schema để phù hợp với mọi tùy chỉnh đối với các truy vấn và database dialect mà bạn sử dụng.

[[servlet-authentication-jdbc-schema-user]]
=== Schema người dùng

`JdbcDaoImpl` yêu cầu các bảng để tải password, trạng thái account (enabled hoặc disabled) và danh sách authority (role) của người dùng.

[NOTE]
====
Schema mặc định cũng được cung cấp dưới dạng resource trên classpath có tên `org/springframework/security/core/userdetails/jdbc/users.ddl`.
====

.Schema người dùng mặc định
[source,sql]
----
create table users(
	username varchar_ignorecase(50) not null primary key,
	password varchar_ignorecase(500) not null,
	enabled boolean not null
);

create table authorities (
	username varchar_ignorecase(50) not null,
	authority varchar_ignorecase(50) not null,
	constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);
----

Oracle là một lựa chọn database phổ biến nhưng yêu cầu schema hơi khác:

.Schema người dùng mặc định cho database Oracle
[source,sql]
----
CREATE TABLE USERS (
    USERNAME NVARCHAR2(128) PRIMARY KEY,
    PASSWORD NVARCHAR2(128) NOT NULL,
    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL
);


CREATE TABLE AUTHORITIES (
    USERNAME NVARCHAR2(128) NOT NULL,
    AUTHORITY NVARCHAR2(128) NOT NULL
);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ENABLE;
----

[[servlet-authentication-jdbc-schema-group]]
=== Schema nhóm

Nếu ứng dụng của bạn sử dụng các nhóm, bạn cần cung cấp schema nhóm:

.Schema nhóm mặc định
[source,sql]
----
create table groups (
	id bigint generated by default as identity(start with 0) primary key,
	group_name varchar_ignorecase(50) not null
);

create table group_authorities (
	group_id bigint not null,
	authority varchar(50) not null,
	constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);

create table group_members (
	id bigint generated by default as identity(start with 0) primary key,
	username varchar(50) not null,
	group_id bigint not null,
	constraint fk_group_members_group foreign key(group_id) references groups(id)
);
----

[[servlet-authentication-jdbc-datasource]]
== Thiết lập một DataSource

Trước khi cấu hình `JdbcUserDetailsManager`, chúng ta phải tạo một `DataSource`.
Trong ví dụ này, chúng ta thiết lập một {spring-framework-reference-url}data-access/jdbc/embedded-database-support.html[DataSource nhúng] được khởi tạo với <<servlet-authentication-jdbc-schema,schema người dùng mặc định>>.

.DataSource nhúng
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
DataSource dataSource() {
	return new EmbeddedDatabaseBuilder()
		.setType(H2)
		.addScript(JdbcDaoImpl.DEFAULT_USER_SCHEMA_DDL_LOCATION)
		.build();
}
----

XML::
+
[source,xml,role="secondary"]
----
<jdbc:embedded-database>
	<jdbc:script location="classpath:org/springframework/security/core/userdetails/jdbc/users.ddl"/>
</jdbc:embedded-database>
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun dataSource(): DataSource {
    return EmbeddedDatabaseBuilder()
        .setType(H2)
        .addScript(JdbcDaoImpl.DEFAULT_USER_SCHEMA_DDL_LOCATION)
        .build()
}
----
======

Trong môi trường production, bạn cần đảm bảo rằng mình thiết lập kết nối đến một database bên ngoài.

[[servlet-authentication-jdbc-bean]]
== Bean JdbcUserDetailsManager

Trong ví dụ này, chúng ta sử dụng xref:features/authentication/password-storage.adoc#authentication-password-storage-boot-cli[Spring Boot CLI] để mã hóa giá trị password là `password` và nhận được password đã mã hóa là `+{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW+`.
Xem phần xref:features/authentication/password-storage.adoc#authentication-password-storage[PasswordEncoder] để biết thêm chi tiết về cách lưu trữ password.

.JdbcUserDetailsManager

[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Bean
UserDetailsManager users(DataSource dataSource) {
	UserDetails user = User.builder()
		.username("user")
		.password("{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
		.roles("USER")
		.build();
	UserDetails admin = User.builder()
		.username("admin")
		.password("{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
		.roles("USER", "ADMIN")
		.build();
	JdbcUserDetailsManager users = new JdbcUserDetailsManager(dataSource);
	users.createUser(user);
	users.createUser(admin);
	return users;
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<jdbc-user-service>
	<user name="user"
		password="{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW"
		authorities="ROLE_USER" />
	<user name="admin"
		password="{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW"
		authorities="ROLE_USER,ROLE_ADMIN" />
</jdbc-user-service>
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun users(dataSource: DataSource): UserDetailsManager {
    val user = User.builder()
            .username("user")
            .password("{bcrypt}$2a$10\$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
            .roles("USER")
            .build();
    val admin = User.builder()
            .username("admin")
            .password("{bcrypt}$2a$10\$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW")
            .roles("USER", "ADMIN")
            .build();
    val users = JdbcUserDetailsManager(dataSource)
    users.createUser(user)
    users.createUser(admin)
    return users
}
----
======
