[[servlet-authentication-ldap]]
= LDAP Authentication

LDAP (Lightweight Directory Access Protocol) thường được các tổ chức sử dụng làm kho lưu trữ tập trung thông tin người dùng và làm authentication service.
LDAP cũng có thể được dùng để lưu trữ thông tin role của người dùng ứng dụng.

LDAP-based authentication của Spring Security được Spring Security sử dụng khi được cấu hình để xref:servlet/authentication/passwords/index.adoc#servlet-authentication-unpwd-input[chấp nhận username/password] cho authentication.
Tuy sử dụng username và password cho authentication, cơ chế này không sử dụng `UserDetailsService`, bởi vì trong <<servlet-authentication-ldap-bind,bind authentication>>, LDAP server không trả về password nên ứng dụng không thể thực hiện việc kiểm tra password.

Có nhiều kịch bản khác nhau để cấu hình LDAP server, vì vậy LDAP provider của Spring Security có thể được cấu hình hoàn toàn.
Provider này sử dụng các strategy interface riêng cho authentication và việc lấy role, đồng thời cung cấp các implementation mặc định có thể được cấu hình để xử lý nhiều tình huống.

[[servlet-authentication-ldap-required-dependencies]]
== Các dependency bắt buộc

Để bắt đầu, hãy thêm dependency `spring-security-ldap` vào project.
Khi sử dụng Spring Boot, hãy thêm các dependency sau:

.Dependency LDAP của Spring Security
[tabs]
======
Maven::
+
[source,xml,role="primary"]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-ldap</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-ldap</artifactId>
</dependency>
----

Gradle::
+
[source,groovy,role="secondary"]
----
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-data-ldap"
    implementation "org.springframework.security:spring-security-ldap"
}
----
======

[[servlet-authentication-ldap-prerequisites]]
== Điều kiện tiên quyết

Bạn nên nắm rõ LDAP trước khi thử sử dụng LDAP với Spring Security.
Liên kết sau cung cấp phần giới thiệu hữu ích về các khái niệm liên quan và hướng dẫn thiết lập directory bằng LDAP server miễn phí OpenLDAP: https://www.zytrax.com/books/ldap/.
Việc quen thuộc ở mức nhất định với các JNDI API dùng để truy cập LDAP từ Java cũng có thể hữu ích.
LDAP provider không sử dụng bất kỳ thư viện LDAP bên thứ ba nào (Mozilla, JLDAP hoặc thư viện khác), nhưng sử dụng rộng rãi Spring LDAP, vì vậy việc quen thuộc với project đó có thể hữu ích nếu bạn dự định thêm các tùy chỉnh của riêng mình.

Khi sử dụng LDAP authentication, bạn nên bảo đảm đã cấu hình đúng LDAP connection pooling.
Nếu chưa quen với cách thực hiện, hãy xem https://docs.oracle.com/javase/jndi/tutorial/ldap/connect/config.html[tài liệu Java LDAP].


// FIXME:
// ldap server
//	embedded (both java and xml)
//	external
// authentication
//	bind
//	password
//	roles
//	search, etc (other APIs)

[[servlet-authentication-ldap-embedded]]
== Thiết lập Embedded LDAP Server

Việc đầu tiên cần làm là bảo đảm bạn có LDAP Server để cấu hình trỏ tới.
Để đơn giản, thường nên bắt đầu với embedded LDAP Server.
Spring Security hỗ trợ sử dụng một trong các lựa chọn sau:

* <<servlet-authentication-ldap-unboundid>>
* <<servlet-authentication-ldap-apacheds>>

Trong các ví dụ sau, chúng ta cung cấp `users.ldif` dưới dạng classpath resource để khởi tạo embedded LDAP server với hai user là `user` và `admin`, cả hai đều có password là `password`:

.users.ldif
[source,ldif]
----
dn: ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: organizationalUnit
ou: groups

dn: ou=people,dc=springframework,dc=org
objectclass: top
objectclass: organizationalUnit
ou: people

dn: uid=admin,ou=people,dc=springframework,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Rod Johnson
sn: Johnson
uid: admin
userPassword: password

dn: uid=user,ou=people,dc=springframework,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Dianne Emu
sn: Emu
uid: user
userPassword: password

dn: cn=user,ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: groupOfNames
cn: user
member: uid=admin,ou=people,dc=springframework,dc=org
member: uid=user,ou=people,dc=springframework,dc=org

dn: cn=admin,ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: groupOfNames
cn: admin
member: uid=admin,ou=people,dc=springframework,dc=org
----

[[servlet-authentication-ldap-unboundid]]
=== Embedded UnboundID Server

Nếu muốn sử dụng https://ldap.com/unboundid-ldap-sdk-for-java/[UnboundID], hãy khai báo các dependency sau:

.Dependency của UnboundID
[tabs]
======
Maven::
+
[source,xml,role="primary",subs="verbatim,attributes"]
----
<dependency>
	<groupId>com.unboundid</groupId>
	<artifactId>unboundid-ldapsdk</artifactId>
	<version>{unboundid-ldapsdk-version}</version>
	<scope>runtime</scope>
</dependency>
----

Gradle::
+
[source,groovy,role="secondary",subs="verbatim,attributes"]
----
dependencies {
	runtimeOnly "com.unboundid:unboundid-ldapsdk:{unboundid-ldapsdk-version}"
}
----
======

Sau đó, bạn có thể cấu hình Embedded LDAP Server bằng `EmbeddedLdapServerContextSourceFactoryBean`.
Cấu hình này yêu cầu Spring Security khởi động một LDAP server trong bộ nhớ:

.Cấu hình Embedded LDAP Server
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean() {
	return EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun contextSourceFactoryBean(): EmbeddedLdapServerContextSourceFactoryBean {
    return EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer()
}
----
======

Ngoài ra, bạn có thể tự cấu hình Embedded LDAP Server.
Nếu chọn cách này, bạn phải chịu trách nhiệm quản lý lifecycle của Embedded LDAP Server.

.Cấu hình Embedded LDAP Server tường minh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
UnboundIdContainer ldapContainer() {
	return new UnboundIdContainer("dc=springframework,dc=org",
				"classpath:users.ldif");
}
----

XML::
+
[source,xml,role="secondary"]
----
<b:bean class="org.springframework.security.ldap.server.UnboundIdContainer"
	c:defaultPartitionSuffix="dc=springframework,dc=org"
	c:ldif="classpath:users.ldif"/>
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun ldapContainer(): UnboundIdContainer {
    return UnboundIdContainer("dc=springframework,dc=org","classpath:users.ldif")
}
----
======

[[servlet-authentication-ldap-apacheds]]
=== Embedded ApacheDS Server

Spring Security 7 loại bỏ hỗ trợ cho Apache DS.
Thay vào đó, hãy sử dụng <<servlet-authentication-ldap-unboundid,UnboundID>>.

[[servlet-authentication-ldap-contextsource]]
== LDAP ContextSource

Sau khi có LDAP Server để cấu hình trỏ tới, bạn cần cấu hình Spring Security trỏ tới LDAP server sẽ được dùng để authenticate user.
Để thực hiện việc đó, hãy tạo một LDAP `ContextSource` (tương đương với JDBC `DataSource`).
Nếu đã cấu hình `EmbeddedLdapServerContextSourceFactoryBean`, Spring Security sẽ tạo một LDAP `ContextSource` trỏ tới embedded LDAP server.

.LDAP Context Source với Embedded LDAP Server
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean() {
	EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean =
			EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer();
	contextSourceFactoryBean.setPort(0);
	return contextSourceFactoryBean;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun contextSourceFactoryBean(): EmbeddedLdapServerContextSourceFactoryBean {
    val contextSourceFactoryBean = EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer()
    contextSourceFactoryBean.setPort(0)
    return contextSourceFactoryBean
}
----
======

Ngoài ra, bạn có thể cấu hình tường minh LDAP `ContextSource` để kết nối tới LDAP server được cung cấp:

.LDAP Context Source
[tabs]
======
Java::
+
[source,java,role="primary"]
----
ContextSource contextSource(UnboundIdContainer container) {
	return new DefaultSpringSecurityContextSource("ldap://localhost:53389/dc=springframework,dc=org");
}
----

XML::
+
[source,xml,role="secondary"]
----
<ldap-server
	url="ldap://localhost:53389/dc=springframework,dc=org" />
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
fun contextSource(container: UnboundIdContainer): ContextSource {
    return DefaultSpringSecurityContextSource("ldap://localhost:53389/dc=springframework,dc=org")
}
----
======

[[servlet-authentication-ldap-authentication]]
== Authentication

LDAP support của Spring Security không sử dụng xref:servlet/authentication/passwords/user-details-service.adoc#servlet-authentication-userdetailsservice[UserDetailsService] vì LDAP bind authentication không cho phép client đọc password, thậm chí cả phiên bản đã hash của password.
Điều này có nghĩa là không có cách nào để đọc password rồi thực hiện authentication bằng Spring Security.

Vì lý do này, LDAP support được triển khai thông qua interface `LdapAuthenticator`.
Interface `LdapAuthenticator` cũng chịu trách nhiệm lấy mọi user attribute cần thiết.
Điều này là do permission trên các attribute có thể phụ thuộc vào loại authentication đang được sử dụng.
Ví dụ, nếu bind với tư cách user, có thể cần đọc các attribute bằng permission của chính user đó.

Spring Security cung cấp hai implementation của `LdapAuthenticator`:

* <<servlet-authentication-ldap-bind>>
* <<servlet-authentication-ldap-pwd>>

[[servlet-authentication-ldap-bind]]
== Sử dụng Bind Authentication

https://ldap.com/the-ldap-bind-operation/[Bind Authentication] là cơ chế phổ biến nhất để authenticate user bằng LDAP.
Trong bind authentication, credential của user (username và password) được gửi tới LDAP server để server authenticate chúng.
Ưu điểm của bind authentication là secret của user (password) không cần được cung cấp cho client, giúp bảo vệ chúng khỏi bị rò rỉ.

Ví dụ sau minh họa cấu hình bind authentication:

.Bind Authentication
[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
	factory.setUserDnPatterns("uid={0},ou=people");
	return factory.createAuthenticationManager();
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
	user-dn-pattern="uid={0},ou=people"/>
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource): AuthenticationManager {
    val factory = LdapBindAuthenticationManagerFactory(contextSource)
    factory.setUserDnPatterns("uid={0},ou=people")
    return factory.createAuthenticationManager()
}
----
======

Ví dụ đơn giản trên lấy DN của user bằng cách thay user login name vào pattern được cung cấp, sau đó thử bind với tư cách user đó bằng login password.
Cách này phù hợp nếu tất cả user được lưu dưới một node duy nhất trong directory.
Nếu muốn cấu hình LDAP search filter để định vị user, bạn có thể sử dụng cấu hình sau:

.Bind Authentication với Search Filter
[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
	factory.setUserSearchFilter("(uid={0})");
	factory.setUserSearchBase("ou=people");
	return factory.createAuthenticationManager();
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
		user-search-filter="(uid={0})"
	user-search-base="ou=people"/>
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource): AuthenticationManager {
    val factory = LdapBindAuthenticationManagerFactory(contextSource)
    factory.setUserSearchFilter("(uid={0})")
    factory.setUserSearchBase("ou=people")
    return factory.createAuthenticationManager()
}
----
======

Khi được sử dụng với `ContextSource` <<servlet-authentication-ldap-contextsource,định nghĩa ở trên>>, cấu hình này sẽ thực hiện tìm kiếm dưới DN `ou=people,dc=springframework,dc=org` bằng `+(uid={0})+` làm filter.
Một lần nữa, user login name được thay vào parameter trong filter name, vì vậy hệ thống tìm kiếm entry có attribute `uid` bằng user name.
Nếu không cung cấp user search base, việc tìm kiếm sẽ được thực hiện từ root.

[[servlet-authentication-ldap-pwd]]
== Sử dụng Password Authentication

Password comparison là việc so sánh password do user cung cấp với password được lưu trong repository.
Việc này có thể được thực hiện bằng cách lấy giá trị của password attribute rồi kiểm tra cục bộ, hoặc thực hiện thao tác LDAP "`compare`", trong đó password được cung cấp sẽ được gửi tới server để so sánh và giá trị password thực tế không bao giờ được lấy về.
Không thể thực hiện LDAP compare khi password đã được hash đúng cách với salt ngẫu nhiên.

.Cấu hình Password Compare tối thiểu
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapPasswordComparisonAuthenticationManagerFactory factory = new LdapPasswordComparisonAuthenticationManagerFactory(
			contextSource, NoOpPasswordEncoder.getInstance());
	factory.setUserDnPatterns("uid={0},ou=people");
	return factory.createAuthenticationManager();
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
		user-dn-pattern="uid={0},ou=people">
	<password-compare />
</ldap-authentication-provider>
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource?): AuthenticationManager? {
    val factory = LdapPasswordComparisonAuthenticationManagerFactory(
        contextSource, NoOpPasswordEncoder.getInstance()
    )
    factory.setUserDnPatterns("uid={0},ou=people")
    return factory.createAuthenticationManager()
}
----
======

Ví dụ sau minh họa một cấu hình nâng cao hơn với một số tùy chỉnh:

.Cấu hình Password Compare
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapPasswordComparisonAuthenticationManagerFactory factory = new LdapPasswordComparisonAuthenticationManagerFactory(
			contextSource, new BCryptPasswordEncoder());
	factory.setUserDnPatterns("uid={0},ou=people");
	factory.setPasswordAttribute("pwd");  // <1>
	return factory.createAuthenticationManager();
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
		user-dn-pattern="uid={0},ou=people">
	<password-compare password-attribute="pwd"> <!--1-->
		<password-encoder ref="passwordEncoder" /> <!--2-->
	</password-compare>
</ldap-authentication-provider>
<b:bean id="passwordEncoder"
	class="org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder" />
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource): AuthenticationManager {
    val factory = LdapPasswordComparisonAuthenticationManagerFactory(
        contextSource, BCryptPasswordEncoder()
    )
    factory.setUserDnPatterns("uid={0},ou=people")
    factory.setPasswordAttribute("pwd") // <1>
    return factory.createAuthenticationManager()
}
----
======

<1> Chỉ định password attribute là `pwd`.

== LdapAuthoritiesPopulator

`LdapAuthoritiesPopulator` của Spring Security được dùng để xác định những authority nào được trả về cho user.
Ví dụ sau minh họa cách cấu hình `LdapAuthoritiesPopulator`:

.Cấu hình LdapAuthoritiesPopulator
[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Bean
LdapAuthoritiesPopulator authorities(BaseLdapPathContextSource contextSource) {
	String groupSearchBase = "";
	DefaultLdapAuthoritiesPopulator authorities =
		new DefaultLdapAuthoritiesPopulator(contextSource, groupSearchBase);
	authorities.setGroupSearchFilter("member={0}");
	return authorities;
}

@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource, LdapAuthoritiesPopulator authorities) {
	LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
	factory.setUserDnPatterns("uid={0},ou=people");
	factory.setLdapAuthoritiesPopulator(authorities);
	return factory.createAuthenticationManager();
}
----

XML::
+
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
	user-dn-pattern="uid={0},ou=people"
	group-search-filter="member={0}"/>
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun authorities(contextSource: BaseLdapPathContextSource): LdapAuthoritiesPopulator {
    val groupSearchBase = ""
    val authorities = DefaultLdapAuthoritiesPopulator(contextSource, groupSearchBase)
    authorities.setGroupSearchFilter("member={0}")
    return authorities
}

@Bean
fun authenticationManager(
    contextSource: BaseLdapPathContextSource,
    authorities: LdapAuthoritiesPopulator): AuthenticationManager {
    val factory = LdapBindAuthenticationManagerFactory(contextSource)
    factory.setUserDnPatterns("uid={0},ou=people")
    factory.setLdapAuthoritiesPopulator(authorities)
    return factory.createAuthenticationManager()
}
----
======

== Active Directory

Active Directory hỗ trợ các tùy chọn authentication không chuẩn riêng, và pattern sử dụng thông thường không hoàn toàn phù hợp với `LdapAuthenticationProvider` tiêu chuẩn.
Thông thường, authentication được thực hiện bằng domain username (ở dạng `user@domain`) thay vì LDAP distinguished name.
Để đơn giản hóa việc này, Spring Security có một authentication provider được tùy chỉnh cho thiết lập Active Directory điển hình.

Cấu hình `ActiveDirectoryLdapAuthenticationProvider` khá đơn giản.
Bạn chỉ cần cung cấp domain name và LDAP URL chứa địa chỉ của server.

[NOTE]
====
Cũng có thể lấy IP address của server bằng DNS lookup.
Hiện tại tính năng này chưa được hỗ trợ, nhưng hy vọng sẽ được hỗ trợ trong phiên bản tương lai.
====

Ví dụ sau cấu hình Active Directory:

.Ví dụ cấu hình Active Directory
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ActiveDirectoryLdapAuthenticationProvider authenticationProvider() {
	return new ActiveDirectoryLdapAuthenticationProvider("example.com", "ldap://company.example.com/");
}
----

XML::
+
[source,xml,role="secondary"]
----
<bean id="authenticationProvider"
        class="org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider">
	<constructor-arg value="example.com" />
	<constructor-arg value="ldap://company.example.com/" />
</bean>
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationProvider(): ActiveDirectoryLdapAuthenticationProvider {
    return ActiveDirectoryLdapAuthenticationProvider("example.com", "ldap://company.example.com/")
}
----
======
