= Di chuyển SAML 2.0

== Kỳ vọng `<saml2:LogoutResponse>` khi validation của `<saml2:LogoutRequest>` thất bại

SAML identity provider mong đợi service provider trả về một `<saml2:LogoutResponse>` báo lỗi nếu việc process `<saml2:LogoutRequest>` thất bại.

Các version trước của Spring Security trả về 401 trong một số trường hợp, làm gián đoạn chuỗi logout request và response từ mỗi relying party.

Trong Spring Security 7, hành vi này đã được khắc phục và bạn không cần làm gì.

Tuy nhiên, nếu điều này gây ra vấn đề cho bạn, bạn có thể quay lại hành vi cũ bằng cách công bố một `Saml2LogoutRequestResolver` trả về `null` khi cần một `<saml2:LogoutRequest>` báo lỗi.
Bạn có thể tạo một delegate như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
Saml2LogoutResponseResolver logoutResponseResolver(RelyingPartyRegistrationRepository registrations) {
    OpenSaml5LogoutResponseResolver delegate = new OpenSaml5LogoutResponseResolver(registrations);
    return new Saml2LogoutResponseResolver() {
        @Override
        public void resolve(HttpServletRequest request, Authentication authentication) {
            delegate.resolve(request, authentication);
        }

        @Override
        public void resolve(HttpServletRequest request, Authentication authentication, Saml2AuthenticationException error) {
            return null;
        }
    };
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun logoutResponseResolver(registrations: RelyingPartyRegistrationRepository?): Saml2LogoutResponseResolver {
    val delegate = OpenSaml5LogoutResponseResolver(registrations)
    return object : Saml2LogoutResponseResolver() {
        override fun resolve(request: HttpServletRequest?, authentication: Authentication?) {
            delegate.resolve(request, authentication)
        }

        override fun resolve(request: HttpServletRequest?, authentication: Authentication?, error: Saml2AuthenticationException?) {
            return null
        }
    }
}
----
======

== Ưu tiên `Saml2ResponseAuthenticationAccessor` thay vì `Saml2AuthenticatedPrincipal`

Spring Security 7 tách các chi tiết của `<saml2:Assertion>` khỏi principal.
Điều này cho phép Spring Security truy xuất các chi tiết assertion cần thiết để thực hiện Single Logout.

Điều này khiến `Saml2AuthenticatedPrincipal` trở thành deprecated.
Bạn không còn cần implement nó để sử dụng `Saml2Authentication`.

Thay vào đó, credential implement `Saml2ResponseAssertionAccessor`; Spring Security 7 ưu tiên accessor này khi xác định action thích hợp dựa trên authentication.

Thay đổi này được tự động thực hiện cho bạn khi sử dụng các giá trị mặc định.

Nếu điều này gây ra vấn đề cho bạn khi nâng cấp, bạn có thể cung cấp một `ResponseAuthenticationConverter` tùy chỉnh để trả về `Saml2Authentication` thay vì `Saml2AssertionAuthentication` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
OpenSaml5AuthenticationProvider authenticationProvider() {
	OpenSaml5AuthenticationProvider authenticationProvider =
		new OpenSaml5AuthenticationProvider();
	ResponseAuthenticationConverter defaults = new ResponseAuthenticationConverter();
	authenticationProvider.setResponseAuthenticationConverter(
		defaults.andThen((authentication) -> new Saml2Authentication(
			authentication.getPrincipal(),
			authentication.getSaml2Response(),
			authentication.getAuthorities())));
	return authenticationProvider;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationProvider(): OpenSaml5AuthenticationProvider {
	val authenticationProvider = OpenSaml5AuthenticationProvider()
	val defaults = ResponseAuthenticationConverter()
	authenticationProvider.setResponseAuthenticationConverter(
		defaults.andThen { authentication ->
			Saml2Authentication(authentication.getPrincipal(),
				authentication.getSaml2Response(),
				authentication.getAuthorities())
		})
	return authenticationProvider
}
----
======

Nếu tự tạo một instance `Saml2Authentication`, hãy cân nhắc chuyển sang `Saml2AssertionAuthentication` để nhận được lợi ích tương tự như giá trị mặc định hiện tại.

== Không process GET request `<saml2:Response>` bằng `Saml2AuthenticationTokenConverter`

Spring Security không hỗ trợ process payload `<saml2:Response>` qua GET vì SAML 2.0 spec không hỗ trợ cách này.

Để tuân thủ điều này tốt hơn, kể từ Spring Security 8, `Saml2AuthenticationTokenConverter` và `OpenSaml5AuthenticationTokenConverter` sẽ không xử lý các yêu cầu GET theo mặc định.
Để chuẩn bị cho điều này, property `shouldConvertGetRequests` khả dụng.
Để sử dụng, hãy cung cấp converter riêng như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
OpenSaml5AuthenticationTokenConverter authenticationConverter(RelyingPartyRegistrationRepository registrations) {
	OpenSaml5AuthenticationTokenConverter authenticationConverter = new OpenSaml5AuthenticationTokenConverter(registrations);
	authenticationConverter.setShouldConvertGetRequests(false);
	return authenticationConverter;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationConverter(val registrations: RelyingPartyRegistrationRepository): Saml2AuthenticationTokenConverter {
	val authenticationConverter = Saml2AuthenticationTokenConverter(registrations)
	authenticationConverter.setShouldConvertGetRequests(false)
	return authenticationConverter
}
----
======

Nếu bắt buộc phải tiếp tục sử dụng `Saml2AuthenticationTokenConverter` hoặc `OpenSaml5AuthenticationTokenConverter` để process GET request, bạn có thể gọi `setShouldConvertGetRequests` với `true`.
