[[webflux-cors]]
= CORS

Spring Framework cung cấp {spring-framework-reference-url}web/webflux-cors.html#webflux-cors-intro[hỗ trợ hạng nhất cho CORS].
CORS phải được xử lý trước Spring Security, vì pre-flight request không chứa cookie nào (cụ thể là `JSESSIONID`).
Nếu request không chứa cookie nào và Spring Security được xử lý trước, Spring Security sẽ xác định rằng người dùng chưa được authenticated (vì request không có cookie nào) và từ chối request đó.

Cách dễ nhất để đảm bảo CORS được xử lý trước là sử dụng `CorsWebFilter`.
Bạn có thể tích hợp `CorsWebFilter` với Spring Security bằng cách cung cấp một `CorsConfigurationSource`.
Ví dụ sau tích hợp hỗ trợ CORS trong Spring Security:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
UrlBasedCorsConfigurationSource corsConfigurationSource() {
	CorsConfiguration configuration = new CorsConfiguration();
	configuration.setAllowedOrigins(Arrays.asList("https://example.com"));
	configuration.setAllowedMethods(Arrays.asList("GET","POST"));
	UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
	source.registerCorsConfiguration("/**", configuration);
	return source;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun corsConfigurationSource(): UrlBasedCorsConfigurationSource {
    val configuration = CorsConfiguration()
    configuration.allowedOrigins = listOf("https://example.com")
    configuration.allowedMethods = listOf("GET", "POST")
    val source = UrlBasedCorsConfigurationSource()
    source.registerCorsConfiguration("/**", configuration)
    return source
}
----
======

Đoạn mã sau vô hiệu hóa tích hợp CORS trong Spring Security:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		// ...
		.cors((cors) -> cors.disable());
	return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        cors {
            disable()
        }
    }
}
----
======

[WARNING]
====
CORS là một tính năng bảo mật dựa trên trình duyệt.
Việc vô hiệu hóa CORS trong Spring Security không loại bỏ cơ chế bảo vệ CORS khỏi trình duyệt của bạn.
Thay vào đó, bạn đang loại bỏ hỗ trợ CORS khỏi Spring Security, và người dùng sẽ không thể tương tác với backend Spring của bạn từ một ứng dụng trình duyệt cross-origin.
Để khắc phục lỗi CORS trong ứng dụng, bạn phải bật hỗ trợ CORS và cung cấp một nguồn cấu hình phù hợp.
====
