[[native-image-method-security]]
= method security trong GraalVM Native Image

Mặc dù xref:servlet/authorization/method-security.adoc[method security] được hỗ trợ trong GraalVM Native Image, một số trường hợp sử dụng cần application cung cấp thêm hint.

== Sử dụng các annotation `@PreAuthorize` và `@PostAuthorize`

Việc sử dụng các annotation `@PreAuthorize` và `@PostAuthorize` yêu cầu thêm hint nếu bạn có implementation tùy chỉnh của các class `UserDetails` hoặc `Authentication`.

Hãy xem ví dụ bạn có một implementation tùy chỉnh của class `UserDetails` như sau và implementation đó được `UserDetailsService` trả về:

.Implementation tùy chỉnh của UserDetails
[source,java]
----
public class CustomUserDetails implements UserDetails {

    private final String username;

    private final String password;

    private final Collection<? extends GrantedAuthority> authorities;

    public boolean isAdmin() {
        return this.authorities.contains(new SimpleGrantedAuthority("ROLE_ADMIN"));
    }

    // constructors, getters and setters
}
----

Và bạn muốn sử dụng method `isAdmin()` bên trong annotation `@PreAuthorize` như sau:

.Sử dụng isAdmin() để bảo vệ một method
[source,java]
----
@PreAuthorize("principal?.isAdmin()")
public String hello() {
    return "Hello!";
}
----

[NOTE]
====
Hãy nhớ rằng bạn cần xref:servlet/authorization/method-security.adoc#jc-enable-method-security[thêm annotation `@EnableMethodSecurity`] vào class cấu hình để bật các annotation method security.
====

Nếu bạn {spring-boot-reference-url}how-to/native-image/developing-your-first-application.html[chạy native image] của ứng dụng với cấu hình trên, bạn sẽ nhận được lỗi tương tự sau khi cố gọi method `hello()`:

[source]
----
failed: java.lang.IllegalArgumentException: Failed to evaluate expression 'principal?.isAdmin()' with root cause
org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method isAdmin() cannot be found on type com.mypackage.CustomUserDetails
----

Điều này có nghĩa là không tìm thấy method `isAdmin()` trên class `CustomUserDetails`.
Nguyên nhân là Spring Security sử dụng reflection để gọi method `isAdmin()`, còn GraalVM Native Image không hỗ trợ reflection theo mặc định.

Để khắc phục vấn đề này, bạn cần cung cấp hint cho GraalVM Native Image để cho phép reflection trên method `CustomUserDetails#isAdmin()`.
Chúng ta có thể thực hiện việc này bằng cách cung cấp {spring-boot-reference-url}reference/packaging/native-image/advanced-topics.html#packaging.native-image.advanced.custom-hints[hint tùy chỉnh].
Trong ví dụ này, chúng ta sẽ sử dụng {spring-framework-reference-url}core/aot.html#aot.hints.register-reflection[annotation `@RegisterReflectionForBinding`].

[NOTE]
====
Bạn có thể cần đăng ký tất cả các class mà bạn muốn sử dụng trong các annotation `@PreAuthorize` và `@PostAuthorize`.
====

.Sử dụng @RegisterReflectionForBinding
[source,java]
----
@Configuration
@RegisterReflectionForBinding(CustomUserDetails.class)
public class MyConfiguration {
    //...
}
----

Vậy là xong; giờ bạn có thể chạy native image của ứng dụng và ứng dụng sẽ hoạt động như mong đợi.
