[[servlet-events]]
= Các sự kiện authorization

Mỗi khi một authorization bị từ chối, một `AuthorizationDeniedEvent` sẽ được phát ra.
Ngoài ra, có thể phát một `AuthorizationGrantedEvent` cho các authorization được cấp phép.

Để lắng nghe các sự kiện này, trước tiên bạn phải công bố một `AuthorizationEventPublisher`.

`SpringAuthorizationEventPublisher` của Spring Security có thể đáp ứng tốt nhu cầu này.
Thành phần này phát hành các sự kiện authorization bằng `ApplicationEventPublisher` của Spring:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public AuthorizationEventPublisher authorizationEventPublisher
        (ApplicationEventPublisher applicationEventPublisher) {
    return new SpringAuthorizationEventPublisher(applicationEventPublisher);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizationEventPublisher
        (applicationEventPublisher: ApplicationEventPublisher?): AuthorizationEventPublisher {
    return SpringAuthorizationEventPublisher(applicationEventPublisher)
}
----
======

Sau đó, bạn có thể sử dụng cơ chế hỗ trợ `@EventListener` của Spring:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class AuthenticationEvents {

    @EventListener
    public void onFailure(AuthorizationDeniedEvent failure) {
		// ...
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class AuthenticationEvents {

    @EventListener
    fun onFailure(failure: AuthorizationDeniedEvent?) {
        // ...
    }
}
----
======

[[authorization-granted-events]]
== Các sự kiện authorization được cấp phép

Vì các ``AuthorizationGrantedEvent`` có khả năng tạo ra nhiều sự kiện gây nhiễu, chúng không được phát hành theo mặc định.

Trên thực tế, việc phát hành các sự kiện này có thể sẽ yêu cầu bạn bổ sung một số logic nghiệp vụ để bảo đảm ứng dụng không bị ngập trong quá nhiều sự kiện authorization gây nhiễu.

Bạn có thể cung cấp predicate của riêng mình để lọc các sự kiện thành công.
Ví dụ, publisher sau chỉ phát hành các authorization grant mà `ROLE_ADMIN` được yêu cầu:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
AuthorizationEventPublisher authorizationEventPublisher() {
    SpringAuthorizationEventPublisher eventPublisher = new SpringAuthorizationEventPublisher();
    eventPublisher.setShouldPublishEvent((result) -> {
        if (!result.isGranted()) {
            return true;
        }
        if (result instanceof AuthorityAuthorizationDecision decision) {
            Collection<GrantedAuthority> authorities = decision.getAuthorities();
            return AuthorityUtils.authorityListToSet(authorities).contains("ROLE_ADMIN");
        }
        return false;
    });
    return eventPublisher;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizationEventPublisher(): AuthorizationEventPublisher {
    val eventPublisher = SpringAuthorizationEventPublisher()
    eventPublisher.setShouldPublishEvent { (result) ->
        if (!result.isGranted()) {
            return true
        }
        if (decision is AuthorityAuthorizationDecision) {
            val authorities = decision.getAuthorities()
            return AuthorityUtils.authorityListToSet(authorities).contains("ROLE_ADMIN")
        }
        return false
    }
    return eventPublisher
}
----
======
