[[servlet-events]]
= Các event authorization

Với mỗi authorization bị từ chối, một `AuthorizationDeniedEvent` được publish.
Ngoài ra, có thể publish một `AuthorizationGrantedEvent` cho các authorization được cấp.

Để lắng nghe các event này, trước tiên bạn phải publish một `AuthorizationEventPublisher`.

`SpringAuthorizationEventPublisher` của Spring Security có lẽ sẽ đáp ứng tốt nhu cầu này.
Publisher này publish các event authorization bằng `ApplicationEventPublisher` của Spring:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public AuthorizationEventPublisher authorizationEventPublisher
        (ApplicationEventPublisher applicationEventPublisher) {
    return new SpringAuthorizationEventPublisher(applicationEventPublisher);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizationEventPublisher
        (applicationEventPublisher: ApplicationEventPublisher?): AuthorizationEventPublisher {
    return SpringAuthorizationEventPublisher(applicationEventPublisher)
}
----
======

Sau đó, bạn có thể sử dụng cơ chế hỗ trợ `@EventListener` của Spring:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class AuthenticationEvents {

    @EventListener
    public void onFailure(AuthorizationDeniedEvent failure) {
		// ...
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class AuthenticationEvents {

    @EventListener
    fun onFailure(failure: AuthorizationDeniedEvent?) {
        // ...
    }
}
----
======

[[authorization-granted-events]]
== Các event authorization được cấp

Vì các ``AuthorizationGrantedEvent`` có khả năng tạo ra khá nhiều event gây nhiễu, chúng không được publish theo mặc định.

Trên thực tế, việc publish các event này có thể sẽ yêu cầu bạn bổ sung một số business logic để bảo đảm application không bị ngập trong quá nhiều event authorization gây nhiễu.

Bạn có thể cung cấp predicate của riêng mình để filter các event thành công.
Ví dụ, publisher sau chỉ publish các authorization grant mà `ROLE_ADMIN` được yêu cầu:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
AuthorizationEventPublisher authorizationEventPublisher() {
    SpringAuthorizationEventPublisher eventPublisher = new SpringAuthorizationEventPublisher();
    eventPublisher.setShouldPublishEvent((result) -> {
        if (!result.isGranted()) {
            return true;
        }
        if (result instanceof AuthorityAuthorizationDecision decision) {
            Collection<GrantedAuthority> authorities = decision.getAuthorities();
            return AuthorityUtils.authorityListToSet(authorities).contains("ROLE_ADMIN");
        }
        return false;
    });
    return eventPublisher;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizationEventPublisher(): AuthorizationEventPublisher {
    val eventPublisher = SpringAuthorizationEventPublisher()
    eventPublisher.setShouldPublishEvent { (result) ->
        if (!result.isGranted()) {
            return true
        }
        if (decision is AuthorityAuthorizationDecision) {
            val authorities = decision.getAuthorities()
            return AuthorityUtils.authorityListToSet(authorities).contains("ROLE_ADMIN")
        }
        return false
    }
    return eventPublisher
}
----
======
