[[servlet-authorization]]
= Authorization
:page-section-summary-toc: 1

Sau khi đã xác định xref:servlet/authentication/index.adoc[cách người dùng sẽ authenticate], bạn cũng cần cấu hình các authorization rule cho application.

Các khả năng authorization nâng cao trong Spring Security là một trong những lý do thuyết phục nhất khiến framework này được ưa chuộng.
Bất kể bạn chọn cách authenticate nào (dù sử dụng mechanism và provider do Spring Security cung cấp hay tích hợp với một container hoặc một authentication authority khác không thuộc Spring Security), các authorization service đều có thể được sử dụng trong application theo cách nhất quán và đơn giản.

Bạn nên cân nhắc gắn các authorization rule vào xref:servlet/authorization/authorize-http-requests.adoc[request URI] và xref:servlet/authorization/method-security.adoc[method] ngay từ đầu.
Trong cả hai trường hợp, bạn có thể lắng nghe và phản ứng với các xref:servlet/authorization/events.adoc[authorization event] được publish bởi mỗi authorization check.
Phần dưới đây cũng có nhiều thông tin chi tiết về xref:servlet/authorization/architecture.adoc[cách Spring Security thực hiện authorization] và cách fine-tune authorization sau khi đã thiết lập mô hình cơ bản.

[NOTE]
====
Kể từ Spring Security 7, Access API (`AccessDecisionManager`, `AccessDecisionVoter`, etc.) được chuyển sang một legacy module là `spring-security-access`.
Đối với application mới, bạn không cần include dependency này.
Đối với các application cũ chưa migrate sang Authorization API, module này được cung cấp để hỗ trợ bạn tiếp tục migration.
====
