[[servlet-hello]]
= Hello Spring Security

Phần này trình bày thiết lập tối thiểu để sử dụng Spring Security với {spring-boot-reference-url}[Spring Boot], sau đó chỉ bạn đến các bước tiếp theo.

[NOTE]
====
Bạn có thể tìm application starter đã hoàn chỉnh tại {gh-samples-url}/servlet/spring-boot/java/hello-security[repository sample của chúng tôi].
Để thuận tiện, bạn có thể tải xuống một application Spring Boot + Spring Security tối thiểu https://start.spring.io/starter.zip?type=maven-project&language=java&packaging=jar&jvmVersion=1.8&groupId=example&artifactId=hello-security&name=hello-security&description=Hello%20Security&packageName=example.hello-security&dependencies=web,security[được Spring Initializr chuẩn bị].
====

[[servlet-hello-dependencies]]
== Cập nhật dependency

Trước tiên, bạn cần thêm Spring Security vào classpath của application; có hai cách để thực hiện việc này là xref:getting-spring-security.adoc#getting-maven-boot[sử dụng Maven] hoặc xref:getting-spring-security.adoc#getting-gradle-boot[Gradle].

[[servlet-hello-starting]]
== Khởi động Hello Spring Security Boot

Khi Spring Security đã <<servlet-hello-dependencies,trên classpath>>, giờ bạn có thể {spring-boot-reference-url}reference/using/running-your-application.html[chạy application Spring Boot].
Đoạn mã sau đây hiển thị một phần output cho biết Spring Security đã được bật trong application của bạn:

.Chạy application Spring Boot
[tabs]
======
Maven::
+
[source,bash,role="primary"]
----
$ ./mvnw spring-boot:run
...
INFO 23689 --- [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 8e557245-73e2-4286-969a-ff57fe326336

...
----

Gradle::
+
[source,bash,role="secondary"]
----
$ ./gradlew :bootRun
...
INFO 23689 --- [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 8e557245-73e2-4286-969a-ff57fe326336

...
----

Jar::
+
[source,bash,role="secondary"]
----
$ java -jar target/myapplication-0.0.1.jar
...
INFO 23689 --- [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 8e557245-73e2-4286-969a-ff57fe326336

...
----
======

Bây giờ application đã chạy, bạn có thể thử gọi một endpoint để xem điều gì xảy ra.
Nếu gọi một endpoint không có credential như sau:

.Truy vấn application Boot được bảo vệ
[source,bash]
----
$ curl -i http://localhost:8080/some/path
HTTP/1.1 401
...
----

thì Spring Security từ chối quyền truy cập với `401 Unauthorized`.

[TIP]
Nếu cung cấp cùng URL đó trong trình duyệt, request sẽ được redirect đến trang login mặc định.

Nếu gọi một endpoint với credential (được tìm thấy trong console output) như sau:

.Truy vấn với credential
[source,bash]
----
$ curl -i -u user:8e557245-73e2-4286-969a-ff57fe326336 http://localhost:8080/some/path
HTTP/1.1 404
...
----

thì Spring Boot sẽ xử lý request và trả về `404 Not Found` trong trường hợp này vì `/some/path` không tồn tại.

Từ đây, bạn có thể:

* Hiểu rõ hơn <<servlet-hello-auto-configuration,những gì Spring Boot bật theo mặc định trong Spring Security>>
* Đọc về các <<security-use-cases,use case phổ biến>> mà Spring Security hỗ trợ
* Bắt đầu cấu hình xref:servlet/authentication/index.adoc[authentication]

[[servlet-hello-auto-configuration]]
== Kỳ vọng trong runtime

Cấu hình mặc định của Spring Boot và Spring Security cung cấp các hành vi sau trong runtime:

* Yêu cầu người dùng đã authentication xref:servlet/authorization/authorize-http-requests.adoc[cho mọi endpoint] (bao gồm endpoint `/error` của Boot)
* xref:servlet/authentication/passwords/user-details-service.adoc[Đăng ký một user mặc định] với password được tạo khi startup (password được ghi vào console; trong ví dụ trước, password là `8e557245-73e2-4286-969a-ff57fe326336`)
* Bảo vệ xref:servlet/authentication/passwords/password-encoder.adoc[việc lưu trữ password bằng BCrypt] cũng như các cơ chế khác
* Cung cấp flow xref:servlet/authentication/passwords/form.adoc[login] dựa trên form và flow xref:servlet/authentication/logout.adoc[logout]
* Thực hiện authentication cho xref:servlet/authentication/passwords/form.adoc[login dựa trên form] cũng như xref:servlet/authentication/passwords/basic.adoc[HTTP Basic]
* Cung cấp content negotiation; đối với web request, redirect đến trang login; đối với service request, trả về `401 Unauthorized`
* xref:servlet/exploits/csrf.adoc[Giảm thiểu CSRF] các cuộc tấn công
* xref:servlet/authentication/session-management.adoc#ns-session-fixation[Giảm thiểu Session Fixation] các cuộc tấn công
* Ghi xref:servlet/exploits/headers.adoc#servlet-headers-hsts[Strict-Transport-Security] để https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[đảm bảo HTTPS]
* Ghi xref:servlet/exploits/headers.adoc#servlet-headers-content-type-options[X-Content-Type-Options] để giảm thiểu https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-content-type-options[các cuộc tấn công sniffing]
* Ghi xref:servlet/exploits/headers.adoc#servlet-headers-cache-control[các header Cache Control] để bảo vệ các resource đã authentication
* Ghi xref:servlet/exploits/headers.adoc#servlet-headers-frame-options[X-Frame-Options] để giảm thiểu https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-frame-options[Clickjacking]
* Tích hợp với xref:servlet/integrations/servlet-api.adoc[các method authentication của ``HttpServletRequest``]
* Công bố xref:servlet/authentication/events.adoc[các event authentication thành công và thất bại]

Việc hiểu cách Spring Boot phối hợp với Spring Security để đạt được điều này có thể hữu ích.
Xem {spring-boot-api-url}org/springframework/boot/security/autoconfigure/SecurityAutoConfiguration.html[auto-configuration bảo mật của Boot], ta thấy nó thực hiện các việc sau (được đơn giản hóa để minh họa):

.Auto-configuration bảo mật của Spring Boot
[source,java]
----
@EnableWebSecurity <1>
@Configuration
public class DefaultSecurityConfig {
    @Bean
    @ConditionalOnMissingBean(UserDetailsService.class)
    InMemoryUserDetailsManager inMemoryUserDetailsManager() { <2>
        String generatedPassword = // ...;
        return new InMemoryUserDetailsManager(User.withUsername("user")
                .password(generatedPassword).roles("USER").build());
    }

    @Bean
    @ConditionalOnMissingBean(AuthenticationEventPublisher.class)
    DefaultAuthenticationEventPublisher defaultAuthenticationEventPublisher(ApplicationEventPublisher delegate) { <3>
        return new DefaultAuthenticationEventPublisher(delegate);
    }
}
----
1. Thêm annotation `@EnableWebSecurity`. (Trong số các việc khác, annotation này công bố xref:servlet/architecture.adoc#servlet-securityfilterchain[chuỗi `Filter` mặc định của Spring Security] dưới dạng một `@Bean`)
2. Công bố một `@Bean` xref:servlet/authentication/passwords/user-details-service.adoc[`UserDetailsService`] với username là `user` và password được tạo ngẫu nhiên, password này được ghi vào console
3. Công bố một `@Bean` xref:servlet/authentication/events.adoc[`AuthenticationEventPublisher`] để công bố các event authentication

[NOTE]
Spring Boot thêm mọi `Filter` được công bố dưới dạng `@Bean` vào filter chain của application.
Điều này có nghĩa là việc sử dụng `@EnableWebSecurity` kết hợp với Spring Boot sẽ tự động đăng ký filter chain của Spring Security cho mọi request.

[[security-use-cases]]
== Use case bảo mật

Có một số hướng mà bạn có thể tiếp tục từ đây.
Để xác định bước tiếp theo cho bạn và application của bạn, hãy cân nhắc các use case phổ biến mà Spring Security được xây dựng để giải quyết:

* Tôi đang xây dựng REST API và cần xref:servlet/oauth2/resource-server/jwt.adoc[authenticate JWT] hoặc xref:servlet/oauth2/resource-server/opaque-token.adoc[bearer token khác]
* Tôi đang xây dựng Web Application, API Gateway hoặc BFF và
** cần xref:servlet/oauth2/login/core.adoc[login bằng OAuth 2.0 hoặc OIDC]
** cần xref:servlet/saml2/login/index.adoc[login bằng SAML 2.0]
** cần xref:servlet/authentication/cas.adoc[login bằng CAS]
* Tôi cần quản lý
** user trong xref:servlet/authentication/passwords/ldap.adoc[LDAP] hoặc xref:servlet/authentication/passwords/ldap.adoc#_active_directory[Active Directory], với xref:servlet/integrations/data.adoc[Spring Data] hoặc với xref:servlet/authentication/passwords/jdbc.adoc[JDBC]
** xref:servlet/authentication/passwords/storage.adoc[password]

Nếu không trường hợp nào trong số đó phù hợp với nhu cầu của bạn, hãy cân nhắc application của bạn theo thứ tự sau:

1. *Protocol*: Trước tiên, hãy cân nhắc protocol mà application của bạn sẽ sử dụng để giao tiếp.
Đối với application dựa trên servlet, Spring Security hỗ trợ HTTP cũng như xref:servlet/integrations/websocket.adoc[Websockets].
2. *Authentication*: Tiếp theo, hãy cân nhắc cách người dùng sẽ xref:servlet/authentication/index.adoc[authenticate] và authentication đó sẽ là stateful hay stateless
3. *Authorization*: Sau đó, hãy cân nhắc cách bạn xác định xref:servlet/authorization/index.adoc[những gì người dùng được authorization thực hiện]
4. *Phòng vệ*: Cuối cùng, hãy xref:servlet/exploits/csrf.adoc#csrf-considerations[tích hợp với các cơ chế bảo vệ mặc định của Spring Security] và cân nhắc xref:servlet/exploits/headers.adoc[các cơ chế bảo vệ bổ sung bạn cần]
