= OAuth 2.0 Bearer Tokens

[[oauth2resourceserver-bearertoken-resolver]]
== Phân giải Bearer Token

Theo mặc định, Resource Server tìm bearer token trong header `Authorization`.
Tuy nhiên, bạn có thể tùy chỉnh điều này theo một vài cách.

=== Đọc Bearer Token từ header tùy chỉnh

Ví dụ, bạn có thể cần đọc bearer token từ một header tùy chỉnh.
Để làm điều này, bạn có thể publish `DefaultBearerTokenResolver` dưới dạng bean hoặc wire một instance vào DSL, như trong ví dụ sau:

.Header tùy chỉnh cho Bearer Token
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
BearerTokenResolver bearerTokenResolver() {
    DefaultBearerTokenResolver bearerTokenResolver = new DefaultBearerTokenResolver();
    bearerTokenResolver.setBearerTokenHeaderName(HttpHeaders.PROXY_AUTHORIZATION);
    return bearerTokenResolver;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun bearerTokenResolver(): BearerTokenResolver {
    val bearerTokenResolver = DefaultBearerTokenResolver()
    bearerTokenResolver.setBearerTokenHeaderName(HttpHeaders.PROXY_AUTHORIZATION)
    return bearerTokenResolver
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
    <oauth2-resource-server bearer-token-resolver-ref="bearerTokenResolver"/>
</http>

<bean id="bearerTokenResolver"
        class="org.springframework.security.oauth2.server.resource.web.DefaultBearerTokenResolver">
    <property name="bearerTokenHeaderName" value="Proxy-Authorization"/>
</bean>
----
======

Hoặc, trong trường hợp provider sử dụng cả header và giá trị tùy chỉnh, bạn có thể dùng `HeaderBearerTokenResolver` thay thế.

=== Đọc Bearer Token từ form parameter

Hoặc, nếu muốn đọc token từ một form parameter, bạn có thể cấu hình `DefaultBearerTokenResolver` như sau:

.Bearer Token trong form parameter
[tabs]
======
Java::
+
[source,java,role="primary"]
----
DefaultBearerTokenResolver resolver = new DefaultBearerTokenResolver();
resolver.setAllowFormEncodedBodyParameter(true);
http
    .oauth2ResourceServer((oauth2) -> oauth2
        .bearerTokenResolver(resolver)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val resolver = DefaultBearerTokenResolver()
resolver.setAllowFormEncodedBodyParameter(true)
http {
    oauth2ResourceServer {
        bearerTokenResolver = resolver
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
    <oauth2-resource-server bearer-token-resolver-ref="bearerTokenResolver"/>
</http>

<bean id="bearerTokenResolver"
        class="org.springframework.security.oauth2.server.resource.web.HeaderBearerTokenResolver">
    <property name="allowFormEncodedBodyParameter" value="true"/>
</bean>
----
======

== Truyền Bearer Token

Sau khi Resource Server đã validate token, việc truyền token đó đến các downstream service có thể hữu ích.
Điều này khá đơn giản với javadoc:org.springframework.security.oauth2.server.resource.web.reactive.function.client.ServletBearerExchangeFilterFunction[], như trong ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public WebClient rest() {
    return WebClient.builder()
            .filter(new ServletBearerExchangeFilterFunction())
            .build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun rest(): WebClient {
    return WebClient.builder()
            .filter(ServletBearerExchangeFilterFunction())
            .build()
}
----
======

Khi `WebClient` ở trên được dùng để thực hiện các request, Spring Security sẽ tra cứu `Authentication` hiện tại và trích xuất credential javadoc:org.springframework.security.oauth2.core.AbstractOAuth2Token[].
Sau đó, nó sẽ truyền token đó trong header `Authorization`.

Ví dụ:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .retrieve()
        .bodyToMono(String.class)
        .block()
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .retrieve()
        .bodyToMono<String>()
        .block()
----
======

Đoạn code trên sẽ gọi `https://other-service.example.com/endpoint` và tự thêm header `Authorization` chứa bearer token cho bạn.

Ở những nơi bạn cần override behavior này, chỉ cần tự cung cấp header như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .headers((headers) -> headers.setBearerAuth(overridingToken))
        .retrieve()
        .bodyToMono(String.class)
        .block()
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
this.rest.get()
        .uri("https://other-service.example.com/endpoint")
        .headers{  headers -> headers.setBearerAuth(overridingToken)}
        .retrieve()
        .bodyToMono<String>()
        .block()
----
======

Trong trường hợp này, filter sẽ fallback và chỉ forward request đến phần còn lại của web filter chain.

[NOTE]
Không giống javadoc:org.springframework.security.oauth2.client.web.reactive.function.client.ServletOAuth2AuthorizedClientExchangeFilterFunction[filter function của OAuth 2.0 Client], filter function này không cố gắng gia hạn token nếu token đã hết hạn.
Để có mức hỗ trợ này, hãy dùng OAuth 2.0 Client filter.

=== Hỗ trợ `RestTemplate`

Hiện tại chưa có cách tương đương với `ServletBearerExchangeFilterFunction` cho `RestTemplate`, nhưng bạn có thể propagate bearer token của request khá đơn giản bằng interceptor riêng:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
RestTemplate rest() {
	RestTemplate rest = new RestTemplate();
	rest.getInterceptors().add((request, body, execution) -> {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		if (authentication == null) {
			return execution.execute(request, body);
		}

		if (!(authentication.getCredentials() instanceof AbstractOAuth2Token)) {
			return execution.execute(request, body);
		}

		AbstractOAuth2Token token = (AbstractOAuth2Token) authentication.getCredentials();
	    request.getHeaders().setBearerAuth(token.getTokenValue());
	    return execution.execute(request, body);
	});
	return rest;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun rest(): RestTemplate {
    val rest = RestTemplate()
    rest.interceptors.add(ClientHttpRequestInterceptor { request, body, execution ->
        val authentication: Authentication? = SecurityContextHolder.getContext().authentication
        if (authentication == null) {
            return execution.execute(request, body)
        }

        if (authentication.credentials !is AbstractOAuth2Token) {
            return execution.execute(request, body)
        }

        request.headers.setBearerAuth(authentication.credentials.tokenValue)
        execution.execute(request, body)
    })
    return rest
}
----
======


[NOTE]
Không giống javadoc:org.springframework.security.oauth2.client.OAuth2AuthorizedClientManager[OAuth 2.0 Authorized Client Manager], filter interceptor này không cố gắng gia hạn token nếu token đã hết hạn.
Để có mức hỗ trợ này, hãy tạo một interceptor bằng xref:servlet/oauth2/client/index.adoc#oauth2client[OAuth 2.0 Authorized Client Manager].

[[oauth2resourceserver-bearertoken-failure]]
== Lỗi Bearer Token

Bearer token có thể invalid vì nhiều lý do. Ví dụ, token có thể không còn active.

Trong những trường hợp này, Resource Server sẽ throw `InvalidBearerTokenException`.
Giống như các exception khác, điều này tạo ra error response của OAuth 2.0 Bearer Token:

[source,http request]
----
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer error_code="invalid_token", error_description="Unsupported algorithm of none", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
----

Ngoài ra, sự kiện này được publish dưới dạng `AuthenticationFailureBadCredentialsEvent`. Bạn có thể xref:servlet/authentication/events.adoc#servlet-events[lắng nghe sự kiện này trong ứng dụng của mình] như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class FailureEvents {
	@EventListener
    public void onFailure(AuthenticationFailureBadCredentialsEvent badCredentials) {
		if (badCredentials.getAuthentication() instanceof BearerTokenAuthenticationToken) {
		    // ... handle
        }
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class FailureEvents {
    @EventListener
    fun onFailure(badCredentials: AuthenticationFailureBadCredentialsEvent) {
        if (badCredentials.authentication is BearerTokenAuthenticationToken) {
            // ... handle
        }
    }
}
----
======
