= Multi-tenancy trong OAuth 2.0 Resource Server

[[oauth2reourceserver-opaqueandjwt]]
== Hỗ trợ cả JWT và opaque token

Trong một số trường hợp, bạn có thể cần xử lý cả hai loại token.
Ví dụ, bạn có thể hỗ trợ nhiều tenant, trong đó một tenant phát hành JWT còn tenant còn lại phát hành opaque token.

Nếu quyết định này phải được đưa ra tại thời điểm nhận request, bạn có thể dùng `AuthenticationManagerResolver` để thực hiện việc đó như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
AuthenticationManagerResolver<HttpServletRequest> tokenAuthenticationManagerResolver
        (JwtDecoder jwtDecoder, OpaqueTokenIntrospector opaqueTokenIntrospector) {
    AuthenticationManager jwt = new ProviderManager(new JwtAuthenticationProvider(jwtDecoder));
    AuthenticationManager opaqueToken = new ProviderManager(
            new OpaqueTokenAuthenticationProvider(opaqueTokenIntrospector));
    return (request) -> useJwt(request) ? jwt : opaqueToken;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun tokenAuthenticationManagerResolver
        (jwtDecoder: JwtDecoder, opaqueTokenIntrospector: OpaqueTokenIntrospector):
        AuthenticationManagerResolver<HttpServletRequest> {
    val jwt = ProviderManager(JwtAuthenticationProvider(jwtDecoder))
    val opaqueToken = ProviderManager(OpaqueTokenAuthenticationProvider(opaqueTokenIntrospector));

    return AuthenticationManagerResolver { request ->
        if (useJwt(request)) {
            jwt
        } else {
            opaqueToken
        }
    }
}
----
======

NOTE: Việc triển khai `useJwt(HttpServletRequest)` nhiều khả năng sẽ phụ thuộc vào dữ liệu tùy chỉnh của request, chẳng hạn như path.

Sau đó, chỉ định `AuthenticationManagerResolver` này trong DSL:

.AuthenticationManager Resolver
[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    .authorizeHttpRequests((authorize) -> authorize
        .anyRequest().authenticated()
    )
    .oauth2ResourceServer((oauth2) -> oauth2
        .authenticationManagerResolver(this.tokenAuthenticationManagerResolver)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    authorizeHttpRequests {
        authorize(anyRequest, authenticated)
    }
    oauth2ResourceServer {
        authenticationManagerResolver = tokenAuthenticationManagerResolver()
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
    <oauth2-resource-server authentication-manager-resolver-ref="tokenAuthenticationManagerResolver"/>
</http>
----
======

[[oauth2resourceserver-multitenancy]]
== Đa tenant

Một resource server được xem là multi-tenant khi có nhiều strategy xác minh bearer token, được phân biệt bằng một tenant identifier.

Ví dụ, resource server của bạn có thể chấp nhận bearer token từ hai authorization server khác nhau.
Hoặc authorization server của bạn có thể đại diện cho nhiều issuer khác nhau.

Trong mỗi trường hợp, cần thực hiện hai việc và có các đánh đổi tương ứng với cách bạn chọn để thực hiện chúng:

1. Xác định tenant
2. Truyền tenant

=== Xác định tenant bằng claim

Một cách để phân biệt các tenant là dựa trên issuer claim. Vì issuer claim nằm trong JWT đã ký, bạn có thể thực hiện việc này bằng `JwtIssuerAuthenticationManagerResolver` như sau:

.Tenant trong mô hình multi-tenant bằng JWT claim
[tabs]
======
Java::
+
[source,java,role="primary"]
----
JwtIssuerAuthenticationManagerResolver authenticationManagerResolver = JwtIssuerAuthenticationManagerResolver
    .fromTrustedIssuers("https://idp.example.org/issuerOne", "https://idp.example.org/issuerTwo");

http
    .authorizeHttpRequests((authorize) -> authorize
        .anyRequest().authenticated()
    )
    .oauth2ResourceServer((oauth2) -> oauth2
        .authenticationManagerResolver(authenticationManagerResolver)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val customAuthenticationManagerResolver = JwtIssuerAuthenticationManagerResolver
    .fromTrustedIssuers("https://idp.example.org/issuerOne", "https://idp.example.org/issuerTwo")
http {
    authorizeHttpRequests {
        authorize(anyRequest, authenticated)
    }
    oauth2ResourceServer {
        authenticationManagerResolver = customAuthenticationManagerResolver
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
    <oauth2-resource-server authentication-manager-resolver-ref="authenticationManagerResolver"/>
</http>

<bean id="authenticationManagerResolver"
        class="org.springframework.security.oauth2.server.resource.authentication.JwtIssuerAuthenticationManagerResolver">
    <constructor-arg>
        <list>
            <value>https://idp.example.org/issuerOne</value>
            <value>https://idp.example.org/issuerTwo</value>
        </list>
    </constructor-arg>
</bean>
----
======

Điều này hữu ích vì các issuer endpoint được load theo cơ chế lazy.
Thực tế, `JwtAuthenticationProvider` tương ứng chỉ được khởi tạo khi request đầu tiên có issuer tương ứng được gửi đến.
Điều này cho phép ứng dụng khởi động mà không phụ thuộc vào việc các authorization server đó đang hoạt động và sẵn sàng.

==== Tenant động

Đương nhiên, có thể bạn không muốn khởi động lại ứng dụng mỗi khi thêm tenant mới.
Trong trường hợp này, bạn có thể cấu hình `JwtIssuerAuthenticationManagerResolver` bằng một repository chứa các instance `AuthenticationManager`, repository này có thể cập nhật tại runtime, như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
private void addManager(Map<String, AuthenticationManager> authenticationManagers, String issuer) {
	JwtAuthenticationProvider authenticationProvider = new JwtAuthenticationProvider
	        (JwtDecoders.fromIssuerLocation(issuer));
	authenticationManagers.put(issuer, authenticationProvider::authenticate);
}

// ...

JwtIssuerAuthenticationManagerResolver authenticationManagerResolver =
        new JwtIssuerAuthenticationManagerResolver(authenticationManagers::get);

http
    .authorizeHttpRequests((authorize) -> authorize
        .anyRequest().authenticated()
    )
    .oauth2ResourceServer((oauth2) -> oauth2
        .authenticationManagerResolver(authenticationManagerResolver)
    );
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
private fun addManager(authenticationManagers: MutableMap<String, AuthenticationManager>, issuer: String) {
    val authenticationProvider = JwtAuthenticationProvider(JwtDecoders.fromIssuerLocation(issuer))
    authenticationManagers[issuer] = AuthenticationManager {
        authentication: Authentication? -> authenticationProvider.authenticate(authentication)
    }
}

// ...

val customAuthenticationManagerResolver: JwtIssuerAuthenticationManagerResolver =
    JwtIssuerAuthenticationManagerResolver(authenticationManagers::get)
http {
    authorizeHttpRequests {
        authorize(anyRequest, authenticated)
    }
    oauth2ResourceServer {
        authenticationManagerResolver = customAuthenticationManagerResolver
    }
}
----
======

Trong trường hợp này, bạn tạo `JwtIssuerAuthenticationManagerResolver` bằng một strategy để lấy `AuthenticationManager` dựa trên issuer.
Cách tiếp cận này cho phép chúng ta thêm và xóa các phần tử khỏi repository (được thể hiện dưới dạng `Map` trong đoạn code) tại runtime.

NOTE: Sẽ không an toàn nếu chỉ cần nhận bất kỳ issuer nào rồi tạo `AuthenticationManager` từ issuer đó.
Issuer phải là giá trị mà code có thể xác minh từ một nguồn đáng tin cậy, chẳng hạn như danh sách issuer được cho phép.

==== Chỉ parse claim một lần

Bạn có thể đã nhận thấy strategy này tuy đơn giản nhưng có đánh đổi: JWT được `AuthenticationManagerResolver` parse một lần, rồi lại được xref:servlet/oauth2/resource-server/jwt.adoc#oauth2resourceserver-jwt-architecture-jwtdecoder[`JwtDecoder`] parse lần nữa ở thời điểm sau trong request.

Có thể giảm số lần parse bổ sung này bằng cách cấu hình trực tiếp xref:servlet/oauth2/resource-server/jwt.adoc#oauth2resourceserver-jwt-architecture-jwtdecoder[`JwtDecoder`] với một `JWTClaimsSetAwareJWSKeySelector` của Nimbus:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class TenantJWSKeySelector
    implements JWTClaimsSetAwareJWSKeySelector<SecurityContext> {

	private final TenantRepository tenants; <1>
	private final Map<String, JWSKeySelector<SecurityContext>> selectors = new ConcurrentHashMap<>(); <2>

	public TenantJWSKeySelector(TenantRepository tenants) {
		this.tenants = tenants;
	}

	@Override
	public List<? extends Key> selectKeys(JWSHeader jwsHeader, JWTClaimsSet jwtClaimsSet, SecurityContext securityContext)
			throws KeySourceException {
		return this.selectors.computeIfAbsent(toTenant(jwtClaimsSet), this::fromTenant)
				.selectJWSKeys(jwsHeader, securityContext);
	}

	private String toTenant(JWTClaimsSet claimSet) {
		return (String) claimSet.getClaim("iss");
	}

	private JWSKeySelector<SecurityContext> fromTenant(String tenant) {
		return Optional.ofNullable(this.tenants.findById(tenant)) <3>
		        .map((t) -> t.getAttrbute("jwks_uri"))
				.map(this::fromUri)
				.orElseThrow(() -> new IllegalArgumentException("unknown tenant"));
	}

	private JWSKeySelector<SecurityContext> fromUri(String uri) {
		try {
			return JWSAlgorithmFamilyJWSKeySelector.fromJWKSetURL(new URL(uri)); <4>
		} catch (Exception ex) {
			throw new IllegalArgumentException(ex);
		}
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class TenantJWSKeySelector(tenants: TenantRepository) : JWTClaimsSetAwareJWSKeySelector<SecurityContext> {
    private val tenants: TenantRepository <1>
    private val selectors: MutableMap<String, JWSKeySelector<SecurityContext>> = ConcurrentHashMap() <2>

    init {
        this.tenants = tenants
    }

    fun selectKeys(jwsHeader: JWSHeader?, jwtClaimsSet: JWTClaimsSet, securityContext: SecurityContext): List<Key?> {
        return selectors.computeIfAbsent(toTenant(jwtClaimsSet)) { tenant: String -> fromTenant(tenant) }
                .selectJWSKeys(jwsHeader, securityContext)
    }

    private fun toTenant(claimSet: JWTClaimsSet): String {
        return claimSet.getClaim("iss") as String
    }

    private fun fromTenant(tenant: String): JWSKeySelector<SecurityContext> {
        return Optional.ofNullable(this.tenants.findById(tenant)) <3>
                .map { t -> t.getAttrbute("jwks_uri") }
                .map { uri: String -> fromUri(uri) }
                .orElseThrow { IllegalArgumentException("unknown tenant") }
    }

    private fun fromUri(uri: String): JWSKeySelector<SecurityContext?> {
        return try {
            JWSAlgorithmFamilyJWSKeySelector.fromJWKSetURL(URL(uri)) <4>
        } catch (ex: Exception) {
            throw IllegalArgumentException(ex)
        }
    }
}
----
======
<1> Một source giả định cung cấp thông tin về tenant
<2> Một cache cho các ``JWSKeySelector``, được key theo tenant identifier
<3> Lookup tenant an toàn hơn so với việc tự tính endpoint JWK Set on the fly - việc lookup hoạt động như một danh sách các tenant được cho phép
<4> Tạo một `JWSKeySelector` dựa trên các loại key trả về từ endpoint JWK Set - việc lookup lazy ở đây nghĩa là bạn không cần cấu hình tất cả tenant khi khởi động

Key selector ở trên là composition của nhiều key selector.
Nó chọn key selector cần dùng dựa trên claim `iss` trong JWT.

NOTE: Để sử dụng cách tiếp cận này, hãy đảm bảo authorization server được cấu hình để đưa claim set vào chữ ký của token.
Nếu không, bạn không có gì đảm bảo issuer chưa bị thay đổi bởi kẻ tấn công.

Tiếp theo, chúng ta có thể tạo một `JWTProcessor`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
JWTProcessor jwtProcessor(JWTClaimsSetAwareJWSKeySelector keySelector) {
	ConfigurableJWTProcessor<SecurityContext> jwtProcessor =
            new DefaultJWTProcessor();
	jwtProcessor.setJWTClaimSetJWSKeySelector(keySelector);
	return jwtProcessor;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtProcessor(keySelector: JWTClaimsSetAwareJWSKeySelector<SecurityContext>): JWTProcessor<SecurityContext> {
    val jwtProcessor = DefaultJWTProcessor<SecurityContext>()
    jwtProcessor.jwtClaimsSetAwareJWSKeySelector = keySelector
    return jwtProcessor
}
----
======

Như bạn đã thấy, đánh đổi của việc đưa khả năng nhận biết tenant xuống mức này là cần thêm cấu hình.
Chỉ còn thêm một ít cấu hình.

Tiếp theo, chúng ta vẫn cần đảm bảo đang validate issuer.
Tuy nhiên, vì issuer có thể khác nhau với từng JWT, bạn cũng sẽ cần một tenant-aware validator:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class TenantJwtIssuerValidator implements OAuth2TokenValidator<Jwt> {
    private final TenantRepository tenants;

    private final OAuth2Error error = new OAuth2Error(OAuth2ErrorCodes.INVALID_TOKEN, "The iss claim is not valid",
            "https://tools.ietf.org/html/rfc6750#section-3.1");

    public TenantJwtIssuerValidator(TenantRepository tenants) {
        this.tenants = tenants;
    }

    @Override
    public OAuth2TokenValidatorResult validate(Jwt token) {
        if(this.tenants.findById(token.getIssuer()) != null) {
            return OAuth2TokenValidatorResult.success();
        }
        return OAuth2TokenValidatorResult.failure(this.error);
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class TenantJwtIssuerValidator(private val tenants: TenantRepository) : OAuth2TokenValidator<Jwt> {
    private val error: OAuth2Error = OAuth2Error(OAuth2ErrorCodes.INVALID_TOKEN, "The iss claim is not valid",
            "https://tools.ietf.org/html/rfc6750#section-3.1")

    override fun validate(token: Jwt): OAuth2TokenValidatorResult {
        return if (tenants.findById(token.issuer) != null)
            OAuth2TokenValidatorResult.success() else OAuth2TokenValidatorResult.failure(error)
    }
}
----
======
Bây giờ chúng ta đã có tenant-aware processor và validator, có thể tiếp tục tạo xref:servlet/oauth2/resource-server/jwt.adoc#oauth2resourceserver-jwt-architecture-jwtdecoder[`JwtDecoder`] của mình:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
JwtDecoder jwtDecoder(JWTProcessor jwtProcessor, OAuth2TokenValidator<Jwt> jwtValidator) {
	NimbusJwtDecoder decoder = new NimbusJwtDecoder(jwtProcessor);
	OAuth2TokenValidator<Jwt> validator = new DelegatingOAuth2TokenValidator<>
			(JwtValidators.createDefault(), jwtValidator);
	decoder.setJwtValidator(validator);
	return decoder;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(jwtProcessor: JWTProcessor<SecurityContext>?, jwtValidator: OAuth2TokenValidator<Jwt>?): JwtDecoder {
    val decoder = NimbusJwtDecoder(jwtProcessor)
    val validator: OAuth2TokenValidator<Jwt> = DelegatingOAuth2TokenValidator(JwtValidators.createDefault(), jwtValidator)
    decoder.setJwtValidator(validator)
    return decoder
}
----
======

Chúng ta đã hoàn tất phần xác định tenant.

Nếu bạn chọn xác định tenant bằng một thứ khác ngoài JWT claim, bạn cần đảm bảo xử lý các downstream resource server theo cùng cách.
Ví dụ, nếu xác định tenant bằng subdomain, bạn có thể cần gửi request đến downstream resource server bằng cùng subdomain đó.

Tuy nhiên, nếu bạn xác định tenant bằng một claim trong bearer token, hãy đọc tiếp để tìm hiểu về xref:servlet/oauth2/resource-server/bearer-tokens.adoc#oauth2resourceserver-bearertoken-resolver[tính năng hỗ trợ bearer token propagation của Spring Security].
