[[oauth2resourceserver-protected-resource-metadata]]
= Metadata của Protected Resource OAuth 2.0

`OAuth2ResourceServerConfigurer.ProtectedResourceMetadataConfigurer` cung cấp khả năng tùy chỉnh https://www.rfc-editor.org/rfc/rfc9728.html#section-3[endpoint OAuth 2.0 Protected Resource Metadata].
Nó định nghĩa một extension point cho phép bạn tùy chỉnh https://www.rfc-editor.org/rfc/rfc9728.html#section-3.2[response OAuth 2.0 Protected Resource Metadata].

`OAuth2ResourceServerConfigurer.ProtectedResourceMetadataConfigurer` cung cấp tùy chọn cấu hình sau:

[source,java]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
	http
		.oauth2ResourceServer((resourceServer) ->
			resourceServer
				.protectedResourceMetadata(protectedResourceMetadata ->
                    protectedResourceMetadata
                        .protectedResourceMetadataCustomizer(protectedResourceMetadataCustomizer)   <1>
				)
		);

	return http.build();
}
----
<1> `protectedResourceMetadataCustomizer()`: `Consumer` cung cấp quyền truy cập vào `OAuth2ProtectedResourceMetadata.Builder`, cho phép tùy chỉnh các claim trong cấu hình của Resource Server.

`OAuth2ResourceServerConfigurer.ProtectedResourceMetadataConfigurer` cấu hình `OAuth2ProtectedResourceMetadataFilter` và đăng ký filter này với `SecurityFilterChain` `@Bean` của Resource Server.
`OAuth2ProtectedResourceMetadataFilter` là `Filter` trả về https://www.rfc-editor.org/rfc/rfc9728.html#section-3.2[response OAuth2ProtectedResourceMetadata].
