[[anonymous]]
= Anonymous Authentication


[[anonymous-overview]]
== Tổng quan
Thông thường, việc áp dụng lập trường "`deny-by-default`" được xem là một thực hành bảo mật tốt, trong đó bạn chỉ rõ những gì được phép và từ chối mọi thứ khác.
Việc xác định những gì người dùng unauthenticated có thể truy cập cũng tương tự, đặc biệt là đối với các ứng dụng web.
Nhiều website yêu cầu người dùng phải authenticated đối với mọi thứ ngoài một vài URL (ví dụ như các trang home và login).
Trong trường hợp đó, cách dễ nhất là định nghĩa các access configuration attribute cho những URL cụ thể này thay vì cho mọi tài nguyên được bảo vệ.
Nói cách khác, đôi khi sẽ thuận tiện nếu mặc định yêu cầu `ROLE_SOMETHING` và chỉ cho phép một số ngoại lệ nhất định đối với quy tắc này, chẳng hạn như các trang login, logout và home của ứng dụng.
Bạn cũng có thể hoàn toàn loại các trang này khỏi filter chain, qua đó bỏ qua các kiểm tra access control, nhưng điều này có thể không mong muốn vì những lý do khác, đặc biệt nếu các trang đó hoạt động khác nhau đối với người dùng đã authenticated.

Đó là ý nghĩa của anonymous authentication.
Lưu ý rằng về mặt khái niệm, không có khác biệt thực sự giữa người dùng "`anonymously authenticated`" và người dùng `unauthenticated`.
Anonymous authentication của Spring Security chỉ cung cấp cho bạn một cách thuận tiện hơn để cấu hình các access-control attribute.
Các lời gọi đến servlet API, chẳng hạn như `getCallerPrincipal`, vẫn trả về null, mặc dù thực tế có một object anonymous authentication trong `SecurityContextHolder`.

Có những tình huống khác mà anonymous authentication hữu ích, chẳng hạn khi một auditing interceptor truy vấn `SecurityContextHolder` để xác định principal nào chịu trách nhiệm cho một thao tác nhất định.
Các class có thể được viết robust hơn nếu biết rằng `SecurityContextHolder` luôn chứa một object `Authentication` và không bao giờ chứa `null`.


[[anonymous-config]]
== Cấu hình
Hỗ trợ anonymous authentication được cung cấp tự động khi bạn sử dụng cấu hình HTTP (được giới thiệu trong Spring Security 3.0).
Bạn có thể tùy chỉnh (hoặc vô hiệu hóa) nó bằng cách sử dụng element `<anonymous>`.
Bạn không cần cấu hình các bean được mô tả ở đây trừ khi đang sử dụng cấu hình bean truyền thống.

Ba class phối hợp với nhau để cung cấp tính năng anonymous authentication.
`AnonymousAuthenticationToken` là một implementation của `Authentication` và lưu trữ các instance `GrantedAuthority` áp dụng cho anonymous principal.
Có một `AnonymousAuthenticationProvider` tương ứng, được nối vào `ProviderManager` để các instance `AnonymousAuthenticationToken` được chấp nhận.
Cuối cùng, một `AnonymousAuthenticationFilter` được nối sau các cơ chế authentication thông thường và tự động thêm một `AnonymousAuthenticationToken` vào `SecurityContextHolder` nếu ở đó chưa có `Authentication` nào.
Filter và authentication provider được định nghĩa như sau:

[source,xml]
----
<bean id="anonymousAuthFilter"
	class="org.springframework.security.web.authentication.AnonymousAuthenticationFilter">
<property name="key" value="foobar"/>
<property name="userAttribute" value="anonymousUser,ROLE_ANONYMOUS"/>
</bean>

<bean id="anonymousAuthenticationProvider"
	class="org.springframework.security.authentication.AnonymousAuthenticationProvider">
<property name="key" value="foobar"/>
</bean>
----



`key` được dùng chung giữa filter và authentication provider, để các token do thành phần trước tạo ra được thành phần sau chấp nhận.

[NOTE]
====
Không nên xem việc sử dụng property `key` là cung cấp bất kỳ bảo mật thực sự nào ở đây.
Nó chỉ là một thao tác ghi sổ.
Nếu bạn dùng chung một `ProviderManager` có chứa `AnonymousAuthenticationProvider` trong một kịch bản mà client authentication có thể tạo object `Authentication` (chẳng hạn với các lời gọi RMI), client độc hại có thể gửi một `AnonymousAuthenticationToken` do chính nó tạo ra (với username và danh sách authority đã chọn).
Nếu có thể đoán được `key` hoặc biết được giá trị của nó, token sẽ được anonymous provider chấp nhận.
Đây không phải là vấn đề trong cách sử dụng thông thường. Tuy nhiên, nếu sử dụng RMI, bạn nên dùng một `ProviderManager` đã tùy chỉnh và loại anonymous provider, thay vì dùng chung `ProviderManager` mà bạn sử dụng cho các cơ chế HTTP authentication.
====

`userAttribute` được biểu diễn dưới dạng `usernameInTheAuthenticationToken,grantedAuthority[,grantedAuthority]`.
Cú pháp tương tự được sử dụng sau dấu bằng cho property `userMap` của `InMemoryDaoImpl`.

Như đã giải thích trước đó, lợi ích của anonymous authentication là mọi URI pattern đều có thể được áp dụng các quy tắc access control, như ví dụ sau đây cho thấy:

[source,xml]
----
<bean id="filterSecurityInterceptor"
	class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="httpRequestAccessDecisionManager"/>
<property name="securityMetadata">
	<security:filter-security-metadata-source>
	<security:intercept-url pattern='/index.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/hello.htm' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/logoff.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/login.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/**' access='ROLE_USER'/>
	</security:filter-security-metadata-source>" +
</property>
</bean>
----

[[anonymous-auth-trust-resolver]]
== AuthenticationTrustResolver
Khép lại phần thảo luận về anonymous authentication là interface `AuthenticationTrustResolver`, cùng với implementation `AuthenticationTrustResolverImpl` tương ứng.
Interface này cung cấp method `isAnonymous(Authentication)`, cho phép các class quan tâm tính đến loại trạng thái authentication đặc biệt này.
`ExceptionTranslationFilter` sử dụng interface này khi xử lý các instance `AccessDeniedException`.
Nếu một `AccessDeniedException` được ném ra và authentication thuộc kiểu anonymous, thay vì ném response 403 (forbidden), filter sẽ gọi `AuthenticationEntryPoint` để principal có thể authentication đúng cách.
Đây là một phân biệt cần thiết. Nếu không, các principal sẽ luôn được xem là "`authenticated`" và không bao giờ có cơ hội login thông qua form, basic, digest hoặc một cơ chế authentication thông thường khác.

Chúng ta thường thấy attribute `ROLE_ANONYMOUS` trong cấu hình interceptor trước đó được thay thế bằng `IS_AUTHENTICATED_ANONYMOUSLY`, vốn về cơ bản có cùng ý nghĩa khi định nghĩa access control.
Đây là một ví dụ về việc sử dụng `AuthenticatedVoter`, được đề cập trong xref:servlet/authorization/architecture.adoc#authz-authenticated-voter[chương authorization].
Nó sử dụng một `AuthenticationTrustResolver` để xử lý attribute cấu hình cụ thể này và cấp quyền truy cập cho người dùng anonymous.
Cách tiếp cận `AuthenticatedVoter` mạnh hơn vì cho phép bạn phân biệt giữa người dùng anonymous, remember-me và fully authenticated.
Tuy nhiên, nếu không cần chức năng này, bạn có thể tiếp tục dùng `ROLE_ANONYMOUS`, được xử lý bởi `RoleVoter` tiêu chuẩn của Spring Security.

[[anonymous-auth-mvc-controller]]
== Lấy Anonymous Authentication với Spring MVC

{spring-framework-reference-url}web/webmvc/mvc-controller/ann-methods/arguments.html[Spring MVC phân giải các parameter có kiểu `Principal`] bằng argument resolver riêng của nó.

Điều này có nghĩa là một cấu trúc như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String method(Authentication authentication) {
	if (authentication instanceof AnonymousAuthenticationToken) {
		return "anonymous";
	} else {
		return "not anonymous";
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun method(authentication: Authentication?): String {
    return if (authentication is AnonymousAuthenticationToken) {
        "anonymous"
    } else {
        "not anonymous"
    }
}
----
======

Sẽ luôn trả về "not anonymous", ngay cả với các request anonymous.
Lý do là Spring MVC phân giải parameter bằng `HttpServletRequest#getPrincipal`, vốn là `null` khi request là anonymous.

Nếu muốn lấy `Authentication` trong các request anonymous, hãy sử dụng
xref:servlet/integrations/mvc.adoc#mvc-current-security-context[`@CurrentSecurityContext`] thay vào đó:

.Sử dụng CurrentSecurityContext cho các anonymous request
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String method(@CurrentSecurityContext SecurityContext context) {
	if (context.getAuthentication() instanceOf AnonymousAuthenticationToken) {
		return "anonymous"
	} else {
		return "not anonymous"
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun method(@CurrentSecurityContext context : SecurityContext) : String {
   return if (context!!.authentication is AnonymousAuthenticationToken) {
	"anonymous"
   } else {
	"not anonymous"
   }
}
----
======
