[[servlet-cas]]
= Xác thực CAS

[[cas-overview]]
== Tổng quan
JA-SIG phát triển một hệ thống đăng nhập một lần trên toàn doanh nghiệp có tên là CAS.
Không giống các sáng kiến khác, Central Authentication Service của JA-SIG là mã nguồn mở, được sử dụng rộng rãi, dễ hiểu, độc lập nền tảng và hỗ trợ khả năng proxy.
Spring Security hỗ trợ đầy đủ CAS và cung cấp một lộ trình di chuyển dễ dàng từ các triển khai Spring Security cho một ứng dụng đến các triển khai cho nhiều ứng dụng được bảo vệ bởi một CAS server trên toàn doanh nghiệp.

Bạn có thể tìm hiểu thêm về CAS tại https://www.apereo.org.
Bạn cũng cần truy cập trang này để tải các file CAS Server.

[[cas-how-it-works]]
== CAS hoạt động như thế nào
Mặc dù website CAS có các tài liệu mô tả chi tiết kiến trúc của CAS, ở đây chúng tôi vẫn trình bày lại tổng quan trong bối cảnh của Spring Security.
Spring Security 3.x hỗ trợ CAS 3.
Tại thời điểm viết tài liệu, CAS server ở version 3.4.

Bạn cần thiết lập một CAS server ở đâu đó trong doanh nghiệp của mình.
CAS server đơn giản chỉ là một WAR file tiêu chuẩn, vì vậy việc thiết lập server không có gì khó khăn.
Bên trong WAR file, bạn sẽ tùy chỉnh trang đăng nhập và các trang đăng nhập một lần khác hiển thị cho người dùng.

Khi triển khai CAS 3.4 server, bạn cũng cần chỉ định một `AuthenticationHandler` trong `deployerConfigContext.xml` đi kèm CAS.
`AuthenticationHandler` có một method đơn giản trả về boolean cho biết một tập Credentials đã cho có hợp lệ hay không.
Triển khai `AuthenticationHandler` của bạn cần liên kết với một loại kho authentication backend nào đó, chẳng hạn LDAP server hoặc database.
Bản thân CAS tích hợp sẵn nhiều ``AuthenticationHandler`` để hỗ trợ việc này.
Khi tải xuống và triển khai server war file, nó được thiết lập để xác thực thành công những người dùng nhập password trùng với username, điều hữu ích cho việc kiểm thử.

Ngoài bản thân CAS server, các thành phần chính khác tất nhiên là những web application an toàn được triển khai trên toàn doanh nghiệp.
Các web application này được gọi là "service".
Có ba loại service.
Những service xác thực service ticket, những service có thể lấy proxy ticket và những service xác thực proxy ticket.
Việc xác thực proxy ticket khác ở chỗ danh sách proxy phải được kiểm tra và proxy ticket thường có thể được sử dụng lại.


[[cas-sequence]]
=== Trình tự tương tác giữa Spring Security và CAS
Tương tác cơ bản giữa web browser, CAS server và một service được Spring Security bảo vệ như sau:

* Người dùng web đang duyệt các trang công khai của service.
CAS hoặc Spring Security không tham gia.
* Cuối cùng, người dùng yêu cầu một trang được bảo mật hoặc một trong các bean mà trang sử dụng được bảo mật.
`ExceptionTranslationFilter` của Spring Security sẽ phát hiện `AccessDeniedException` hoặc `AuthenticationException`.
* Vì đối tượng `Authentication` của người dùng (hoặc việc không có đối tượng này) gây ra `AuthenticationException`, `ExceptionTranslationFilter` sẽ gọi `AuthenticationEntryPoint` đã cấu hình.
Nếu sử dụng CAS, đây sẽ là class `CasAuthenticationEntryPoint`.
* `CasAuthenticationEntryPoint` sẽ redirect browser của người dùng đến CAS server.
Nó cũng chỉ ra parameter `service`, là callback URL cho service Spring Security (ứng dụng của bạn).
Ví dụ, URL mà browser được redirect đến có thể là https://my.company.com/cas/login?service=https%3A%2F%2Fserver3.company.com%2Fwebapp%2Flogin/cas.
* Sau khi browser của người dùng redirect đến CAS, người dùng sẽ được yêu cầu nhập username và password.
Nếu người dùng gửi một session cookie cho biết họ đã đăng nhập trước đó, họ sẽ không bị yêu cầu đăng nhập lại (có một ngoại lệ đối với quy trình này, sẽ được đề cập sau).
CAS sẽ sử dụng `PasswordHandler` (hoặc `AuthenticationHandler` nếu sử dụng CAS 3.0) được đề cập ở trên để quyết định username và password có hợp lệ hay không.
* Sau khi đăng nhập thành công, CAS sẽ redirect browser của người dùng trở lại service ban đầu.
Nó cũng sẽ bao gồm parameter `ticket`, là một chuỗi opaque đại diện cho "service ticket".
Tiếp tục ví dụ trước, URL mà browser được redirect đến có thể là https://server3.company.com/webapp/login/cas?ticket=ST-0-ER94xMJmn6pha35CQRoZ.
* Quay lại web application của service, `CasAuthenticationFilter` luôn lắng nghe các request đến `/login/cas` (có thể cấu hình lại, nhưng trong phần giới thiệu này chúng ta sẽ dùng giá trị mặc định).
Filter xử lý sẽ tạo một `UsernamePasswordAuthenticationToken` đại diện cho service ticket.
principal sẽ bằng `CasAuthenticationFilter.CAS_STATEFUL_IDENTIFIER`, còn credential sẽ là giá trị opaque của service ticket.
Sau đó request authentication này sẽ được chuyển đến `AuthenticationManager` đã cấu hình.
* Triển khai `AuthenticationManager` sẽ là `ProviderManager`, vốn được cấu hình với `CasAuthenticationProvider`.
`CasAuthenticationProvider` chỉ phản hồi với ``UsernamePasswordAuthenticationToken`` có principal riêng của CAS (chẳng hạn `CasAuthenticationFilter.CAS_STATEFUL_IDENTIFIER`) và ``CasAuthenticationToken`` (sẽ được đề cập sau).
* `CasAuthenticationProvider` sẽ kiểm tra service ticket bằng triển khai `TicketValidator`.
Thông thường đây sẽ là `Cas20ServiceTicketValidator`, một trong các class có trong CAS client library.
Nếu ứng dụng cần kiểm tra proxy ticket, `Cas20ProxyTicketValidator` sẽ được sử dụng.
`TicketValidator` tạo một HTTPS request đến CAS server để kiểm tra service ticket.
Request này cũng có thể bao gồm proxy callback URL, như trong ví dụ này: https://my.company.com/cas/proxyValidate?service=https%3A%2F%2Fserver3.company.com%2Fwebapp%2Flogin/cas&ticket=ST-0-ER94xMJmn6pha35CQRoZ&pgtUrl=https://server3.company.com/webapp/login/cas/proxyreceptor.
* Trên CAS server, request kiểm tra sẽ được tiếp nhận.
Nếu service ticket được gửi khớp với service URL mà ticket được cấp cho, CAS sẽ cung cấp response xác nhận ở dạng XML, trong đó có username.
Nếu có proxy tham gia authentication (được thảo luận bên dưới), danh sách proxy cũng được đưa vào XML response.
* [TÙY CHỌN] Nếu request đến CAS validation service bao gồm proxy callback URL (trong parameter `pgtUrl`), CAS sẽ đưa một chuỗi `pgtIou` vào XML response.
`pgtIou` này đại diện cho một proxy-granting ticket IOU.
Sau đó CAS server sẽ tự tạo kết nối HTTPS trở lại `pgtUrl`.
Việc này nhằm authentication lẫn nhau giữa CAS server và service URL được khai báo.
Kết nối HTTPS sẽ được dùng để gửi proxy granting ticket đến web application ban đầu.
Ví dụ, https://server3.company.com/webapp/login/cas/proxyreceptor?pgtIou=PGTIOU-0-R0zlgrl4pdAQwBvJWO3vnNpevwqStbSGcq3vKB2SqSFFRnjPHt&pgtId=PGT-1-si9YkkHLrtACBo64rmsi3v2nf7cpCResXg5MpESZFArbaZiOKH.
* `Cas20TicketValidator` sẽ phân tích XML nhận được từ CAS server.
Nó sẽ trả về cho `CasAuthenticationProvider` một `TicketResponse`, trong đó có username (bắt buộc), danh sách proxy (nếu có) và proxy-granting ticket IOU (nếu đã yêu cầu proxy callback).
* Tiếp theo, `CasAuthenticationProvider` sẽ gọi `CasProxyDecider` đã cấu hình.
`CasProxyDecider` cho biết danh sách proxy trong `TicketResponse` có được service chấp nhận hay không.
Spring Security cung cấp một số triển khai: `RejectProxyTickets`, `AcceptAnyCasProxy` và `NamedCasProxyDecider`.
Các tên này hầu như đã tự giải thích, ngoại trừ `NamedCasProxyDecider`, cho phép cung cấp một `List` gồm các proxy đáng tin cậy.
* Tiếp theo, `CasAuthenticationProvider` sẽ yêu cầu một `AuthenticationUserDetailsService` tải các đối tượng `GrantedAuthority` áp dụng cho người dùng có trong `Assertion`.
Nếu không có vấn đề gì, `CasAuthenticationProvider` sẽ tạo `CasAuthenticationToken`, bao gồm các chi tiết trong `TicketResponse` và một tập ``GrantedAuthority`` chứa ít nhất `FACTOR_BEARER`.
* Sau đó quyền điều khiển trở về `CasAuthenticationFilter`, nơi đặt `CasAuthenticationToken` đã tạo vào security context.
* Browser của người dùng được redirect đến trang ban đầu gây ra `AuthenticationException` (hoặc destination tùy chỉnh, phụ thuộc cấu hình).

Thật tốt vì bạn vẫn đang theo dõi!
Bây giờ hãy xem cách cấu hình phần này

[[cas-client]]
== Cấu hình CAS Client
Phía web application của CAS được Spring Security làm cho đơn giản hơn.
Giả định rằng bạn đã biết các kiến thức cơ bản về cách sử dụng Spring Security, nên những nội dung này sẽ không được nhắc lại bên dưới.
Chúng ta sẽ giả định đang sử dụng cấu hình dựa trên namespace và thêm các CAS bean cần thiết.
Mỗi phần được xây dựng dựa trên phần trước đó.
Bạn có thể tìm thấy một CAS sample application đầy đủ trong Spring Security xref:samples.adoc#samples[Các sample].


[[cas-st]]
=== Xác thực Service Ticket
Phần này mô tả cách thiết lập Spring Security để authentication Service Ticket.
Thông thường đây là tất cả những gì một web application cần.
Bạn cần thêm một `ServiceProperties` bean vào application context.
Bean này đại diện cho CAS service của bạn:

[source,xml]
----
<bean id="serviceProperties"
	class="org.springframework.security.cas.ServiceProperties">
<property name="service"
	value="https://localhost:8443/cas-sample/login/cas"/>
<property name="sendRenew" value="false"/>
</bean>
----

`service` phải bằng một URL sẽ được `CasAuthenticationFilter` giám sát.
`sendRenew` mặc định là false, nhưng nên đặt thành true nếu ứng dụng của bạn đặc biệt nhạy cảm.
Parameter này cho CAS login service biết rằng không chấp nhận đăng nhập một lần.
Thay vào đó, người dùng sẽ phải nhập lại username và password để truy cập service.

Các bean sau nên được cấu hình để bắt đầu quy trình authentication CAS (giả định bạn đang sử dụng cấu hình namespace):

[source,xml]
----
<security:http entry-point-ref="casEntryPoint">
...
<security:custom-filter position="CAS_FILTER" ref="casFilter" />
</security:http>

<bean id="casFilter"
	class="org.springframework.security.cas.web.CasAuthenticationFilter">
<property name="authenticationManager" ref="authenticationManager"/>
</bean>

<bean id="casEntryPoint"
	class="org.springframework.security.cas.web.CasAuthenticationEntryPoint">
<property name="loginUrl" value="https://localhost:9443/cas/login"/>
<property name="serviceProperties" ref="serviceProperties"/>
</bean>
----

Để CAS hoạt động, property `authenticationEntryPoint` của `ExceptionTranslationFilter` phải được đặt thành `CasAuthenticationEntryPoint` bean.
Có thể dễ dàng thực hiện việc này bằng xref:servlet/appendix/namespace/http.adoc#nsa-http-entry-point-ref[entry-point-ref] như trong ví dụ trên.
`CasAuthenticationEntryPoint` phải tham chiếu đến `ServiceProperties` bean (đã thảo luận ở trên), bean này cung cấp URL đến CAS login server của doanh nghiệp.
Đây là nơi browser của người dùng sẽ được redirect đến.

`CasAuthenticationFilter` có các property rất giống `UsernamePasswordAuthenticationFilter` (được dùng cho form-based login).
Bạn có thể sử dụng các property này để tùy chỉnh những thứ như behavior khi authentication thành công và thất bại.

Tiếp theo, bạn cần thêm một `CasAuthenticationProvider` và các collaborator của nó:

[source,xml,attrs="-attributes"]
----
<security:authentication-manager alias="authenticationManager">
<security:authentication-provider ref="casAuthenticationProvider" />
</security:authentication-manager>

<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
<property name="authenticationUserDetailsService">
	<bean class="org.springframework.security.core.userdetails.UserDetailsByNameServiceWrapper">
	<constructor-arg ref="userService" />
	</bean>
</property>
<property name="serviceProperties" ref="serviceProperties" />
<property name="ticketValidator">
	<bean class="org.apereo.cas.client.validation.Cas20ServiceTicketValidator">
	<constructor-arg index="0" value="https://localhost:9443/cas" />
	</bean>
</property>
<property name="key" value="an_id_for_this_auth_provider_only"/>
</bean>

<security:user-service id="userService">
<!-- Password is prefixed with {noop} to indicate to DelegatingPasswordEncoder that
NoOpPasswordEncoder should be used.
This is not safe for production, but makes reading
in samples easier.
Normally passwords should be hashed using BCrypt -->
<security:user name="joe" password="{noop}joe" authorities="ROLE_USER" />
...
</security:user-service>
----

`CasAuthenticationProvider` sử dụng một instance `UserDetailsService` để tải các authority cho người dùng sau khi người dùng đã được CAS authentication.
Ở đây chúng tôi trình bày một thiết lập in-memory đơn giản.
Lưu ý rằng `CasAuthenticationProvider` thực sự không sử dụng password cho authentication, nhưng có sử dụng authority.

Các bean đều tương đối dễ hiểu nếu bạn xem lại phần <<cas-how-it-works,CAS hoạt động như thế nào>>.

Như vậy là hoàn tất cấu hình cơ bản nhất cho CAS.
Nếu bạn không mắc lỗi nào, web application của bạn sẽ hoạt động tốt trong framework đăng nhập một lần của CAS.
Các phần khác của Spring Security không cần quan tâm đến việc CAS đã xử lý authentication.
Trong các phần tiếp theo, chúng ta sẽ thảo luận một số cấu hình nâng cao hơn (tùy chọn).


[[cas-singlelogout]]
=== Đăng xuất một lần
CAS protocol hỗ trợ Single Logout và có thể dễ dàng thêm vào cấu hình Spring Security.
Dưới đây là các cập nhật cho cấu hình Spring Security để xử lý Single Logout

[source,xml]
----
<security:http entry-point-ref="casEntryPoint">
...
<security:logout logout-success-url="/cas-logout.jsp"/>
<security:custom-filter ref="requestSingleLogoutFilter" before="LOGOUT_FILTER"/>
<security:custom-filter ref="singleLogoutFilter" before="CAS_FILTER"/>
</security:http>

<!-- This filter handles a Single Logout Request from the CAS Server -->
<bean id="singleLogoutFilter" class="org.apereo.cas.client.session.SingleSignOutFilter"/>

<!-- This filter redirects to the CAS Server to signal Single Logout should be performed -->
<bean id="requestSingleLogoutFilter"
	class="org.springframework.security.web.authentication.logout.LogoutFilter">
<constructor-arg value="https://localhost:9443/cas/logout"/>
<constructor-arg>
	<bean class=
		"org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler"/>
</constructor-arg>
<property name="filterProcessesUrl" value="/logout/cas"/>
</bean>
----

Phần tử `logout` logout người dùng khỏi ứng dụng local, nhưng không kết thúc session với CAS server hoặc bất kỳ ứng dụng nào khác mà người dùng đã đăng nhập.
Filter `requestSingleLogoutFilter` cho phép request URL `/spring_security_cas_logout` để redirect ứng dụng đến CAS Server logout URL đã cấu hình.
Sau đó CAS Server sẽ gửi request Single Logout đến tất cả service đã đăng nhập.
`singleLogoutFilter` xử lý request Single Logout bằng cách tra cứu `HttpSession` trong một `Map` static rồi invalidate nó.

Có thể bạn sẽ thấy khó hiểu vì sao cần cả phần tử `logout` và `singleLogoutFilter`.
Logout local trước được xem là best practice vì `SingleSignOutFilter` chỉ lưu `HttpSession` trong một `Map` static để gọi invalidate trên đó.
Với cấu hình trên, flow logout sẽ là:

* Người dùng request `/logout`, thao tác này sẽ logout người dùng khỏi ứng dụng local và đưa người dùng đến trang logout success.
* Trang logout success, `/cas-logout.jsp`, nên hướng dẫn người dùng nhấp vào một link trỏ đến `/logout/cas` để logout khỏi tất cả ứng dụng.
* Khi người dùng nhấp vào link, người dùng được redirect đến CAS single logout URL (https://localhost:9443/cas/logout).
* Ở phía CAS Server, CAS single logout URL sau đó gửi các request single logout đến tất cả CAS Service.
Ở phía CAS Service, `SingleSignOutFilter` của Apereo xử lý request logout bằng cách invalidate session ban đầu.



Bước tiếp theo là thêm nội dung sau vào web.xml của bạn

[source,xml]
----
<filter>
<filter-name>characterEncodingFilter</filter-name>
<filter-class>
	org.springframework.web.filter.CharacterEncodingFilter
</filter-class>
<init-param>
	<param-name>encoding</param-name>
	<param-value>UTF-8</param-value>
</init-param>
</filter>
<filter-mapping>
<filter-name>characterEncodingFilter</filter-name>
<url-pattern>/*</url-pattern>
</filter-mapping>
<listener>
<listener-class>
	org.apereo.cas.client.session.SingleSignOutHttpSessionListener
</listener-class>
</listener>
----

Khi sử dụng SingleSignOutFilter, bạn có thể gặp một số vấn đề về encoding.
Do đó, nên thêm `CharacterEncodingFilter` để bảo đảm character encoding chính xác khi sử dụng `SingleSignOutFilter`.
Một lần nữa, hãy tham khảo tài liệu của Apereo CAS để biết chi tiết.
`SingleSignOutHttpSessionListener` bảo đảm rằng khi một `HttpSession` hết hạn, mapping được dùng cho single logout sẽ bị xóa.


[[cas-pt-client]]
=== Authentication đến Stateless Service bằng CAS
Phần này mô tả cách authentication đến một service bằng CAS.
Nói cách khác, phần này thảo luận cách thiết lập một client sử dụng service được authentication bằng CAS.
Phần tiếp theo mô tả cách thiết lập một stateless service để xác thực bằng CAS.


[[cas-pt-client-config]]
==== Cấu hình CAS để lấy Proxy Granting Ticket
Để authentication đến một stateless service, ứng dụng cần lấy proxy granting ticket (PGT).
Phần này mô tả cách cấu hình Spring Security để lấy PGT, xây dựng trên cấu hình thencas-st[Xác thực Service Ticket].

Bước đầu tiên là đưa một `ProxyGrantingTicketStorage` vào cấu hình Spring Security.
Nó được dùng để lưu các PGT mà `CasAuthenticationFilter` lấy được, để có thể dùng chúng lấy proxy ticket.
Ví dụ cấu hình được trình bày bên dưới

[source,xml]
----
<!--
NOTE: In a real application you should not use an in memory implementation.
You will also want to ensure to clean up expired tickets by calling
ProxyGrantingTicketStorage.cleanup()
-->
<bean id="pgtStorage" class="org.apereo.cas.client.proxy.ProxyGrantingTicketStorageImpl"/>
----

Bước tiếp theo là cập nhật `CasAuthenticationProvider` để có thể lấy proxy ticket.
Để thực hiện việc này, thay `Cas20ServiceTicketValidator` bằng `Cas20ProxyTicketValidator`.
`proxyCallbackUrl` nên được đặt thành URL nơi ứng dụng sẽ nhận PGT.
Cuối cùng, cấu hình cũng phải tham chiếu `ProxyGrantingTicketStorage` để có thể sử dụng PGT lấy proxy ticket.
Bạn có thể xem ví dụ về các thay đổi cấu hình cần thực hiện bên dưới.

[source,xml]
----
<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
...
<property name="ticketValidator">
	<bean class="org.apereo.cas.client.validation.Cas20ProxyTicketValidator">
	<constructor-arg value="https://localhost:9443/cas"/>
		<property name="proxyCallbackUrl"
		value="https://localhost:8443/cas-sample/login/cas/proxyreceptor"/>
	<property name="proxyGrantingTicketStorage" ref="pgtStorage"/>
	</bean>
</property>
</bean>
----

Bước cuối cùng là cập nhật `CasAuthenticationFilter` để chấp nhận PGT và lưu chúng vào `ProxyGrantingTicketStorage`.
Điều quan trọng là `proxyReceptorUrl` phải khớp với `proxyCallbackUrl` của `Cas20ProxyTicketValidator`.
Ví dụ cấu hình được trình bày bên dưới.

[source,xml]
----

<bean id="casFilter"
		class="org.springframework.security.cas.web.CasAuthenticationFilter">
	...
	<property name="proxyGrantingTicketStorage" ref="pgtStorage"/>
	<property name="proxyReceptorUrl" value="/login/cas/proxyreceptor"/>
</bean>

----

[[cas-pt-client-sample]]
==== Gọi Stateless Service bằng Proxy Ticket
Bây giờ Spring Security đã lấy được PGT, bạn có thể dùng chúng để tạo proxy ticket, vốn có thể được dùng để authentication đến stateless service.
CAS xref:samples.adoc#samples[ứng dụng mẫu] có một ví dụ hoạt động trong `ProxyTicketSampleServlet`.
Code ví dụ được trình bày bên dưới:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
protected void doGet(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
// NOTE: The CasAuthenticationToken can also be obtained using
// SecurityContextHolder.getContext().getAuthentication()
final CasAuthenticationToken token = (CasAuthenticationToken) request.getUserPrincipal();
// proxyTicket could be reused to make calls to the CAS service even if the
// target url differs
final String proxyTicket = token.getAssertion().getPrincipal().getProxyTicketFor(targetUrl);

// Make a remote call using the proxy ticket
final String serviceUrl = targetUrl+"?ticket="+URLEncoder.encode(proxyTicket, "UTF-8");
String proxyResponse = CommonUtils.getResponseFromServer(serviceUrl, "UTF-8");
...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
protected fun doGet(request: HttpServletRequest, response: HttpServletResponse?) {
    // NOTE: The CasAuthenticationToken can also be obtained using
    // SecurityContextHolder.getContext().getAuthentication()
    val token = request.userPrincipal as CasAuthenticationToken
    // proxyTicket could be reused to make calls to the CAS service even if the
    // target url differs
    val proxyTicket = token.assertion.principal.getProxyTicketFor(targetUrl)

    // Make a remote call using the proxy ticket
    val serviceUrl: String = targetUrl + "?ticket=" + URLEncoder.encode(proxyTicket, "UTF-8")
    val proxyResponse = CommonUtils.getResponseFromServer(serviceUrl, "UTF-8")
}
----
======

[[cas-pt]]
=== Xác thực Proxy Ticket
`CasAuthenticationProvider` phân biệt giữa stateful client và stateless client.
Stateful client là bất kỳ client nào gửi request đến `filterProcessesUrl` của `CasAuthenticationFilter`.
Stateless client là bất kỳ client nào gửi authentication request đến `CasAuthenticationFilter` trên URL khác với `filterProcessesUrl`.

Vì remoting protocol không có cách tự biểu diễn trong context của một `HttpSession`, không thể dựa vào cách làm mặc định là lưu security context trong session giữa các request.
Hơn nữa, vì CAS server invalidate ticket sau khi ticket được `TicketValidator` kiểm tra, việc gửi cùng proxy ticket trong các request tiếp theo sẽ không hoạt động.

Một lựa chọn rõ ràng là hoàn toàn không sử dụng CAS cho các client remoting protocol.
Tuy nhiên, điều này sẽ loại bỏ nhiều tính năng đáng mong muốn của CAS.
Ở mức trung gian, `CasAuthenticationProvider` sử dụng `StatelessTicketCache`.
Thành phần này chỉ được dùng cho stateless client có principal bằng `CasAuthenticationFilter.CAS_STATELESS_IDENTIFIER`.
Cụ thể, `CasAuthenticationProvider` sẽ lưu `CasAuthenticationToken` kết quả vào `StatelessTicketCache`, với proxy ticket làm key.
Theo đó, client remoting protocol có thể gửi cùng proxy ticket và `CasAuthenticationProvider` sẽ không cần liên hệ CAS server để kiểm tra (ngoại trừ request đầu tiên).
Sau khi được authentication, proxy ticket có thể được dùng cho các URL khác với target service ban đầu.

Phần này xây dựng trên các phần trước để hỗ trợ authentication proxy ticket.
Bước đầu tiên là chỉ định authentication tất cả artifact như bên dưới.

[source,xml]
----
<bean id="serviceProperties"
	class="org.springframework.security.cas.ServiceProperties">
...
<property name="authenticateAllArtifacts" value="true"/>
</bean>
----

Bước tiếp theo là chỉ định `serviceProperties` và `authenticationDetailsSource` cho `CasAuthenticationFilter`.
Property `serviceProperties` hướng dẫn `CasAuthenticationFilter` thử authentication tất cả artifact thay vì chỉ những artifact có trên `filterProcessesUrl`.
`ServiceAuthenticationDetailsSource` tạo một `ServiceAuthenticationDetails`, bảo đảm URL hiện tại, dựa trên `HttpServletRequest`, được dùng làm service URL khi kiểm tra ticket.
Có thể tùy chỉnh cách tạo service URL bằng cách inject một `AuthenticationDetailsSource` tùy chỉnh trả về `ServiceAuthenticationDetails` tùy chỉnh.

[source,xml]
----
<bean id="casFilter"
	class="org.springframework.security.cas.web.CasAuthenticationFilter">
...
<property name="serviceProperties" ref="serviceProperties"/>
<property name="authenticationDetailsSource">
	<bean class=
	"org.springframework.security.cas.web.authentication.ServiceAuthenticationDetailsSource">
	<constructor-arg ref="serviceProperties"/>
	</bean>
</property>
</bean>
----

Bạn cũng cần cập nhật `CasAuthenticationProvider` để xử lý proxy ticket.
Để thực hiện việc này, thay `Cas20ServiceTicketValidator` bằng `Cas20ProxyTicketValidator`.
Bạn cần cấu hình `statelessTicketCache` và các proxy muốn chấp nhận.
Bạn có thể xem ví dụ về các cập nhật cần thiết để chấp nhận tất cả proxy bên dưới.

[source,xml]
----

<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
...
<property name="ticketValidator">
	<bean class="org.apereo.cas.client.validation.Cas20ProxyTicketValidator">
	<constructor-arg value="https://localhost:9443/cas"/>
	<property name="acceptAnyProxy" value="true"/>
	</bean>
</property>
<property name="statelessTicketCache">
	<bean class="org.springframework.security.cas.authentication.SpringCacheBasedTicketCache">
	<property name="cache">
		<bean class="net.sf.ehcache.Cache"
			init-method="initialise" destroy-method="dispose">
		<constructor-arg value="casTickets"/>
		<constructor-arg value="50"/>
		<constructor-arg value="true"/>
		<constructor-arg value="false"/>
		<constructor-arg value="3600"/>
		<constructor-arg value="900"/>
		</bean>
	</property>
	</bean>
</property>
</bean>
----
