[[servlet-jaas]]
= JAAS Provider

Spring Security cung cấp một package để delegate các authentication request tới Java Authentication and Authorization Service (JAAS).
Phần này mô tả package đó.


[[jaas-abstractjaasauthenticationprovider]]
== AbstractJaasAuthenticationProvider
Class `AbstractJaasAuthenticationProvider` là base class cho các implementation JAAS `AuthenticationProvider` được cung cấp.
Các subclass phải implement một method tạo `LoginContext`.
`AbstractJaasAuthenticationProvider` có một số dependency có thể được inject vào, như được mô tả trong phần còn lại của phần này.


[[jaas-callbackhandler]]
=== JAAS CallbackHandler
Hầu hết instance `LoginModule` của JAAS đều yêu cầu một callback nào đó.
Các callback này thường được dùng để lấy username và password từ user.

Trong một Spring Security deployment, Spring Security chịu trách nhiệm về tương tác này với user (thông qua authentication mechanism).
Do đó, tại thời điểm authentication request được delegate tới JAAS, authentication mechanism của Spring Security đã điền đầy đủ một object `Authentication` chứa mọi thông tin mà JAAS `LoginModule` yêu cầu.

Vì vậy, JAAS package của Spring Security cung cấp hai callback handler mặc định: `JaasNameCallbackHandler` và `JaasPasswordCallbackHandler`.
Mỗi callback handler này implement `JaasAuthenticationCallbackHandler`.
Trong hầu hết trường hợp, có thể sử dụng các callback handler này mà không cần hiểu cơ chế nội bộ.

Đối với những trường hợp cần toàn quyền kiểm soát hành vi callback, `AbstractJaasAuthenticationProvider` bọc nội bộ các instance `JaasAuthenticationCallbackHandler` này bằng một `InternalCallbackHandler`.
`InternalCallbackHandler` là class thực sự implement interface `CallbackHandler` thông thường của JAAS.
Mỗi khi JAAS `LoginModule` được sử dụng, một list các instance `InternalCallbackHandler` được cấu hình bằng application context sẽ được truyền cho nó.
Nếu `LoginModule` yêu cầu một callback từ các instance `InternalCallbackHandler`, callback đó lần lượt được truyền tới các instance `JaasAuthenticationCallbackHandler` được bọc.

[[jaas-authoritygranter]]
=== JAAS AuthorityGranter
JAAS làm việc với các principal.
Ngay cả "`roles`" cũng được biểu diễn dưới dạng principal trong JAAS.
Trong khi đó, Spring Security làm việc với các object `Authentication`.
Mỗi object `Authentication` chứa một principal duy nhất và nhiều instance `GrantedAuthority`.
Để hỗ trợ mapping giữa các concept khác nhau này, JAAS package của Spring Security bao gồm một interface `AuthorityGranter`.

Một `AuthorityGranter` chịu trách nhiệm kiểm tra một JAAS principal và trả về một set các object `String` đại diện cho các authority được gán cho principal đó.
Với mỗi chuỗi authority được trả về, `AbstractJaasAuthenticationProvider` tạo một `JaasGrantedAuthority` (implement interface `GrantedAuthority` của Spring Security) chứa chuỗi authority và JAAS principal đã được truyền cho `AuthorityGranter`.
`AbstractJaasAuthenticationProvider` lấy các JAAS principal bằng cách trước tiên xác thực thành công credential của người dùng bằng JAAS `LoginModule`, sau đó truy cập `LoginContext` mà nó trả về.
Một lời gọi tới `LoginContext.getSubject().getPrincipals()` được thực hiện; mỗi principal thu được sẽ được truyền cho từng `AuthorityGranter` được khai báo trên property `AbstractJaasAuthenticationProvider.setAuthorityGranters(List)`.

Spring Security không bao gồm bất kỳ instance `AuthorityGranter` nào dùng trong production, vì mỗi JAAS principal đều có ý nghĩa phụ thuộc vào implementation.
Tuy nhiên, theo mặc định Spring Security cấp authority `FACTOR_PASSWORD` khi authentication thành công.

[TIP]
====
Trong unit test có một `TestAuthorityGranter` minh họa một implementation `AuthorityGranter` đơn giản.
====

[[jaas-defaultjaasauthenticationprovider]]
== DefaultJaasAuthenticationProvider
`DefaultJaasAuthenticationProvider` cho phép inject một object JAAS `Configuration` vào provider dưới dạng dependency.
Sau đó, provider tạo một `LoginContext` bằng cách sử dụng JAAS `Configuration` đã được inject.
Điều này có nghĩa là `DefaultJaasAuthenticationProvider` không bị bind với bất kỳ implementation cụ thể nào của `Configuration`, không giống `JaasAuthenticationProvider`.


[[jaas-inmemoryconfiguration]]
=== InMemoryConfiguration
Để dễ inject một `Configuration` vào `DefaultJaasAuthenticationProvider`, một in-memory implementation mặc định có tên `InMemoryConfiguration` được cung cấp.
Constructor của implementation này nhận một `Map`, trong đó mỗi key đại diện cho tên login configuration, còn value đại diện cho một `Array` gồm các instance `AppConfigurationEntry`.
`InMemoryConfiguration` cũng hỗ trợ một `Array` mặc định gồm các object `AppConfigurationEntry`, được dùng nếu không tìm thấy mapping nào trong `Map` đã cung cấp.
Để biết chi tiết, xem Javadoc của javadoc:org.springframework.security.authentication.jaas.memory.InMemoryConfiguration[].


[[jaas-djap-config]]
=== Configuration mẫu cho DefaultJaasAuthenticationProvider
Mặc dù Spring configuration cho `InMemoryConfiguration` có thể dài dòng hơn các JAAS configuration file tiêu chuẩn, việc sử dụng nó cùng với `DefaultJaasAuthenticationProvider` linh hoạt hơn `JaasAuthenticationProvider`, vì nó không phụ thuộc vào `Configuration` implementation mặc định.

Ví dụ sau cung cấp configuration cho `DefaultJaasAuthenticationProvider` sử dụng `InMemoryConfiguration`.
Lưu ý rằng custom implementation của `Configuration` cũng có thể dễ dàng được inject vào `DefaultJaasAuthenticationProvider`.

[source,xml]
----
<bean id="jaasAuthProvider"
class="org.springframework.security.authentication.jaas.DefaultJaasAuthenticationProvider">
<property name="configuration">
<bean class="org.springframework.security.authentication.jaas.memory.InMemoryConfiguration">
<constructor-arg>
	<map>
	<!--
	SPRINGSECURITY is the default loginContextName
	for AbstractJaasAuthenticationProvider
	-->
	<entry key="SPRINGSECURITY">
	<array>
	<bean class="javax.security.auth.login.AppConfigurationEntry">
		<constructor-arg value="sample.SampleLoginModule" />
		<constructor-arg>
		<util:constant static-field=
			"javax.security.auth.login.AppConfigurationEntry$LoginModuleControlFlag.REQUIRED"/>
		</constructor-arg>
		<constructor-arg>
		<map></map>
		</constructor-arg>
		</bean>
	</array>
	</entry>
	</map>
	</constructor-arg>
</bean>
</property>
<property name="authorityGranters">
<list>
	<!-- You will need to write your own implementation of AuthorityGranter -->
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
</list>
</property>
</bean>
----


[[jaas-jaasauthenticationprovider]]
== JaasAuthenticationProvider
`JaasAuthenticationProvider` giả định rằng `Configuration` mặc định là một instance của https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/login/ConfigFile.html[`ConfigFile`].
Giả định này được đưa ra để có thể thử update `Configuration`.
Sau đó, `JaasAuthenticationProvider` sử dụng `Configuration` mặc định để tạo `LoginContext`.

Giả sử chúng ta có một JAAS login configuration file `/WEB-INF/login.conf` với nội dung sau:

[source,txt]
----
JAASTest {
	sample.SampleLoginModule required;
};
----

Giống như mọi Spring Security bean, `JaasAuthenticationProvider` được cấu hình thông qua application context.
Các khai báo sau tương ứng với JAAS login configuration file ở trên:

[source,xml]
----

<bean id="jaasAuthenticationProvider"
class="org.springframework.security.authentication.jaas.JaasAuthenticationProvider">
<property name="loginConfig" value="/WEB-INF/login.conf"/>
<property name="loginContextName" value="JAASTest"/>
<property name="callbackHandlers">
<list>
<bean
	class="org.springframework.security.authentication.jaas.JaasNameCallbackHandler"/>
<bean
	class="org.springframework.security.authentication.jaas.JaasPasswordCallbackHandler"/>
</list>
</property>
<property name="authorityGranters">
	<list>
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
	</list>
</property>
</bean>
----

[[jaas-apiprovision]]
== Chạy với tư cách Subject
Nếu được cấu hình, `JaasApiIntegrationFilter` cố gắng chạy dưới dạng `Subject` của `JaasAuthenticationToken`.
Điều này có nghĩa là có thể truy cập `Subject` bằng:

[source,java]
----
Subject subject = Subject.getSubject(AccessController.getContext());
----

Bạn có thể cấu hình integration này bằng attribute xref:servlet/appendix/namespace/http.adoc#nsa-http-jaas-api-provision[jaas-api-provision].
Tính năng này hữu ích khi tích hợp với các API legacy hoặc API bên ngoài phụ thuộc vào việc JAAS Subject được populate.
