[[servlet-jaas]]
= Nhà cung cấp Java Authentication and Authorization Service (JAAS)

Spring Security cung cấp một gói để ủy thác các yêu cầu authentication cho Java Authentication and Authorization Service (JAAS).
Phần này thảo luận về gói đó.


[[jaas-abstractjaasauthenticationprovider]]
== AbstractJaasAuthenticationProvider
Class `AbstractJaasAuthenticationProvider` là nền tảng cho các triển khai `AuthenticationProvider` JAAS được cung cấp.
Các subclass phải triển khai một method tạo `LoginContext`.
`AbstractJaasAuthenticationProvider` có một số dependency có thể được inject vào nó, như sẽ được thảo luận trong phần còn lại của phần này.


[[jaas-callbackhandler]]
=== JAAS CallbackHandler
Hầu hết instance `LoginModule` JAAS đều yêu cầu một callback nào đó.
Các callback này thường được dùng để lấy tên người dùng và mật khẩu từ người dùng.

Trong một triển khai Spring Security, Spring Security chịu trách nhiệm về tương tác này với người dùng (thông qua cơ chế authentication).
Do đó, tại thời điểm yêu cầu authentication được ủy quyền cho JAAS, cơ chế authentication của Spring Security đã điền đầy đủ một object `Authentication` chứa mọi thông tin mà `LoginModule` JAAS yêu cầu.

Vì vậy, gói JAAS của Spring Security cung cấp hai callback handler mặc định: `JaasNameCallbackHandler` và `JaasPasswordCallbackHandler`.
Mỗi callback handler này triển khai `JaasAuthenticationCallbackHandler`.
Trong hầu hết trường hợp, có thể sử dụng các callback handler này mà không cần hiểu cơ chế nội bộ.

Đối với những trường hợp cần toàn quyền kiểm soát hành vi callback, `AbstractJaasAuthenticationProvider` bọc nội bộ các instance `JaasAuthenticationCallbackHandler` này bằng một `InternalCallbackHandler`.
`InternalCallbackHandler` là class thực sự triển khai interface `CallbackHandler` thông thường của JAAS.
Mỗi khi `LoginModule` JAAS được sử dụng, một danh sách các instance `InternalCallbackHandler` được cấu hình bằng application context sẽ được truyền cho nó.
Nếu `LoginModule` yêu cầu callback từ các instance `InternalCallbackHandler`, callback đó lần lượt được truyền đến các instance `JaasAuthenticationCallbackHandler` được bọc.

[[jaas-authoritygranter]]
=== JAAS AuthorityGranter
JAAS làm việc với principal.
Ngay cả "`roles`" cũng được biểu diễn dưới dạng principal trong JAAS.
Mặt khác, Spring Security làm việc với các object `Authentication`.
Mỗi object `Authentication` chứa một principal duy nhất và nhiều instance `GrantedAuthority`.
Để hỗ trợ ánh xạ giữa các khái niệm khác nhau này, gói JAAS của Spring Security bao gồm một interface `AuthorityGranter`.

Một `AuthorityGranter` chịu trách nhiệm kiểm tra một principal JAAS và trả về một tập các object `String` biểu diễn các authority được gán cho principal đó.
Với mỗi chuỗi authority được trả về, `AbstractJaasAuthenticationProvider` tạo một `JaasGrantedAuthority` (triển khai interface `GrantedAuthority` của Spring Security) chứa chuỗi authority và principal JAAS đã được truyền cho `AuthorityGranter`.
`AbstractJaasAuthenticationProvider` lấy các principal JAAS bằng cách trước tiên xác thực thành công credential của người dùng sử dụng `LoginModule` JAAS, sau đó truy cập `LoginContext` mà nó trả về.
Một lời gọi đến `LoginContext.getSubject().getPrincipals()` được thực hiện; mỗi principal thu được sẽ được truyền cho từng `AuthorityGranter` được khai báo trên property `AbstractJaasAuthenticationProvider.setAuthorityGranters(List)`.

Spring Security không bao gồm instance `AuthorityGranter` nào dùng trong production, vì mỗi principal JAAS đều có ý nghĩa phụ thuộc vào triển khai.
Tuy nhiên, Spring Security mặc định cấp authority `FACTOR_PASSWORD` khi authentication thành công.

[TIP]
====
Có một `TestAuthorityGranter` trong các unit test minh họa một triển khai `AuthorityGranter` đơn giản.
====

[[jaas-defaultjaasauthenticationprovider]]
== DefaultJaasAuthenticationProvider
`DefaultJaasAuthenticationProvider` cho phép inject một object `Configuration` JAAS vào nó dưới dạng dependency.
Sau đó, nó tạo một `LoginContext` bằng cách sử dụng `Configuration` JAAS đã được inject.
Điều này có nghĩa là `DefaultJaasAuthenticationProvider` không bị ràng buộc với một triển khai cụ thể nào của `Configuration`, như `JaasAuthenticationProvider`.


[[jaas-inmemoryconfiguration]]
=== InMemoryConfiguration
Để dễ dàng inject một `Configuration` vào `DefaultJaasAuthenticationProvider`, một triển khai mặc định trong bộ nhớ có tên `InMemoryConfiguration` được cung cấp.
Constructor của triển khai này nhận một `Map`, trong đó mỗi key biểu diễn tên cấu hình đăng nhập, còn value biểu diễn một `Array` các instance `AppConfigurationEntry`.
`InMemoryConfiguration` cũng hỗ trợ một `Array` mặc định gồm các object `AppConfigurationEntry`, được sử dụng nếu không tìm thấy mapping nào trong `Map` đã cung cấp.
Để biết chi tiết, xem Javadoc của javadoc:org.springframework.security.authentication.jaas.memory.InMemoryConfiguration[].


[[jaas-djap-config]]
=== Cấu hình ví dụ DefaultJaasAuthenticationProvider
Mặc dù cấu hình Spring cho `InMemoryConfiguration` có thể dài dòng hơn các file cấu hình JAAS tiêu chuẩn, việc sử dụng nó cùng với `DefaultJaasAuthenticationProvider` linh hoạt hơn `JaasAuthenticationProvider`, vì nó không phụ thuộc vào triển khai `Configuration` mặc định.

Ví dụ tiếp theo cung cấp cấu hình `DefaultJaasAuthenticationProvider` sử dụng `InMemoryConfiguration`.
Lưu ý rằng các triển khai tùy chỉnh của `Configuration` cũng có thể dễ dàng được inject vào `DefaultJaasAuthenticationProvider`.

[source,xml]
----
<bean id="jaasAuthProvider"
class="org.springframework.security.authentication.jaas.DefaultJaasAuthenticationProvider">
<property name="configuration">
<bean class="org.springframework.security.authentication.jaas.memory.InMemoryConfiguration">
<constructor-arg>
	<map>
	<!--
	SPRINGSECURITY is the default loginContextName
	for AbstractJaasAuthenticationProvider
	-->
	<entry key="SPRINGSECURITY">
	<array>
	<bean class="javax.security.auth.login.AppConfigurationEntry">
		<constructor-arg value="sample.SampleLoginModule" />
		<constructor-arg>
		<util:constant static-field=
			"javax.security.auth.login.AppConfigurationEntry$LoginModuleControlFlag.REQUIRED"/>
		</constructor-arg>
		<constructor-arg>
		<map></map>
		</constructor-arg>
		</bean>
	</array>
	</entry>
	</map>
	</constructor-arg>
</bean>
</property>
<property name="authorityGranters">
<list>
	<!-- You will need to write your own implementation of AuthorityGranter -->
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
</list>
</property>
</bean>
----


[[jaas-jaasauthenticationprovider]]
== JaasAuthenticationProvider
`JaasAuthenticationProvider` giả định rằng `Configuration` mặc định là một instance của https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/login/ConfigFile.html[`ConfigFile`].
Giả định này được đưa ra để thử cập nhật `Configuration`.
Sau đó, `JaasAuthenticationProvider` sử dụng `Configuration` mặc định để tạo `LoginContext`.

Giả sử chúng ta có một file cấu hình đăng nhập JAAS `/WEB-INF/login.conf` với nội dung sau:

[source,txt]
----
JAASTest {
	sample.SampleLoginModule required;
};
----

Giống như mọi bean Spring Security, `JaasAuthenticationProvider` được cấu hình thông qua application context.
Các khai báo sau tương ứng với file cấu hình đăng nhập JAAS ở trên:

[source,xml]
----

<bean id="jaasAuthenticationProvider"
class="org.springframework.security.authentication.jaas.JaasAuthenticationProvider">
<property name="loginConfig" value="/WEB-INF/login.conf"/>
<property name="loginContextName" value="JAASTest"/>
<property name="callbackHandlers">
<list>
<bean
	class="org.springframework.security.authentication.jaas.JaasNameCallbackHandler"/>
<bean
	class="org.springframework.security.authentication.jaas.JaasPasswordCallbackHandler"/>
</list>
</property>
<property name="authorityGranters">
	<list>
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
	</list>
</property>
</bean>
----

[[jaas-apiprovision]]
== Chạy với tư cách Subject
Nếu được cấu hình, `JaasApiIntegrationFilter` cố gắng chạy với tư cách `Subject` trên `JaasAuthenticationToken`.
Điều này có nghĩa là có thể truy cập `Subject` bằng:

[source,java]
----
Subject subject = Subject.getSubject(AccessController.getContext());
----

Bạn có thể cấu hình việc tích hợp này bằng attribute xref:servlet/appendix/namespace/http.adoc#nsa-http-jaas-api-provision[jaas-api-provision].
Tính năng này hữu ích khi tích hợp với các API legacy hoặc bên ngoài phụ thuộc vào việc JAAS Subject được điền thông tin.
