[[jc-logout]]
= Xử lý logout

Trong ứng dụng cho phép người dùng cuối xref:servlet/authentication/index.adoc[đăng nhập], họ cũng nên có thể logout.

Theo mặc định, Spring Security cung cấp endpoint `/logout`, vì vậy không cần thêm code.

Phần còn lại của mục này trình bày một số use case mà bạn có thể cân nhắc:

* Tôi muốn <<logout-java-configuration,hiểu kiến trúc của logout>>
* Tôi muốn <<customizing-logout-uris,tùy chỉnh URI logout hoặc URI logout thành công>>
* Tôi muốn biết khi nào cần <<permit-logout-endpoints,cho phép rõ ràng endpoint `/logout`>>
* Tôi muốn <<clear-all-site-data,xóa cookie, storage và/hoặc cache>> khi người dùng logout
* Tôi đang sử dụng OAuth 2.0 và muốn xref:servlet/oauth2/login/advanced.adoc#oauth2login-advanced-oidc-logout[phối hợp logout với một Authorization Server]
* Tôi đang sử dụng SAML 2.0 và muốn xref:servlet/saml2/logout.adoc[phối hợp logout với một Identity Provider]
* Tôi đang sử dụng CAS và muốn xref:servlet/authentication/cas.adoc#cas-singlelogout[phối hợp logout với một Identity Provider]

[[logout-architecture]]
[[logout-java-configuration]]
== Tìm hiểu kiến trúc của logout

Khi bạn include {spring-boot-reference-url}reference/using/build-systems.html#using.build-systems.starters[dependency `spring-boot-starter-security`] hoặc sử dụng annotation `@EnableWebSecurity`, Spring Security sẽ thêm hỗ trợ logout và theo mặc định xử lý cả `GET /logout` lẫn `POST /logout`.

Nếu bạn gửi request `GET /logout`, Spring Security sẽ hiển thị trang xác nhận logout.
Ngoài việc cung cấp cơ chế xác nhận lại hữu ích cho người dùng, trang này còn cung cấp cách đơn giản để cung cấp xref:servlet/exploits/csrf.adoc[CSRF token cần thiết] cho `POST /logout`.

Lưu ý rằng nếu xref:servlet/exploits/csrf.adoc[CSRF protection] bị vô hiệu hóa trong config, Spring Security sẽ không hiển thị trang xác nhận logout mà thực hiện logout trực tiếp.

[TIP]
Trong ứng dụng của bạn, không cần sử dụng `GET /logout` để thực hiện logout.
Miễn là xref:servlet/exploits/csrf.adoc[CSRF token cần thiết] có trong request, ứng dụng của bạn chỉ cần gửi `POST /logout` để thực hiện logout.

Nếu bạn gửi request `POST /logout`, request này sẽ thực hiện các thao tác mặc định sau thông qua một loạt instance javadoc:org.springframework.security.web.authentication.logout.LogoutHandler[]:

- Vô hiệu hóa HTTP session (javadoc:org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler[])
- Xóa xref:servlet/authentication/session-management.adoc#use-securitycontextholderstrategy[`SecurityContextHolderStrategy`] (javadoc:org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler[])
- Xóa xref:servlet/authentication/persistence.adoc#securitycontextrepository[`SecurityContextRepository`] (javadoc:org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler[])
- Dọn dẹp mọi xref:servlet/authentication/rememberme.adoc[authentication bằng RememberMe] (`TokenRememberMeServices` / `PersistentTokenRememberMeServices`)
- Xóa mọi xref:servlet/exploits/csrf.adoc[CSRF token] đã lưu (javadoc:org.springframework.security.web.csrf.CsrfLogoutHandler[])
- xref:servlet/authentication/events.adoc[Phát] event `LogoutSuccessEvent` (javadoc:org.springframework.security.web.authentication.logout.LogoutSuccessEventPublishingLogoutHandler[])

Sau khi hoàn tất, nó sẽ gọi javadoc:org.springframework.security.web.authentication.logout.LogoutSuccessHandler[] mặc định để redirect đến `/login?logout`.

[[customizing-logout-uris]]
== Tùy chỉnh URI logout

Vì `LogoutFilter` xuất hiện trước xref:servlet/authorization/authorize-http-requests.adoc[`AuthorizationFilter`] trong xref:servlet/architecture.adoc#servlet-filterchain-figure[filter chain], theo mặc định không cần cho phép rõ ràng endpoint `/logout`.
Do đó, nhìn chung chỉ <<permit-logout-endpoints,endpoint logout tùy chỉnh>> do bạn tự tạo mới cần cấu hình `permitAll` để có thể truy cập.

Ví dụ, nếu chỉ muốn thay đổi URI mà Spring Security đang match, bạn có thể thực hiện việc này trong DSL `logout` như sau:

.URI logout tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    .logout((logout) -> logout.logoutUrl("/my/logout/uri"))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    logout {
        logoutUrl = "/my/logout/uri"
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<logout logout-url="/my/logout/uri"/>
----
======

và không cần thay đổi authorization vì việc này chỉ điều chỉnh `LogoutFilter`.

[NOTE]
====
URI được truyền cho `logoutUrl` (và `logoutSuccessUrl`) sẽ được match và redirect đúng theo giá trị đó.
Nếu muốn một trong hai URI nằm dưới base path của servlet ứng dụng, hãy thêm rõ prefix đó, ví dụ `logoutUrl("/api/logout")`.
====

[[permit-logout-endpoints]]
Tuy nhiên, nếu bạn tạo endpoint logout thành công của riêng mình (hoặc trong trường hợp hiếm gặp, <<creating-custom-logout-endpoint,endpoint logout của riêng bạn>>), chẳng hạn bằng {spring-framework-reference-url}web.html#spring-web[Spring MVC], bạn sẽ cần cho phép endpoint đó trong Spring Security.
Điều này là do Spring MVC xử lý request của bạn sau khi Spring Security đã xử lý xong.

Bạn có thể thực hiện việc này bằng `authorizeHttpRequests` hoặc `<intercept-url>` như sau:

.Endpoint Logout tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    .authorizeHttpRequests((authorize) -> authorize
        .requestMatchers("/my/success/endpoint").permitAll()
        // ...
    )
    .logout((logout) -> logout.logoutSuccessUrl("/my/success/endpoint"))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    authorizeHttpRequests {
        authorize("/my/success/endpoint", permitAll)
    }
    logout {
        logoutSuccessUrl = "/my/success/endpoint"
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
    <filter-url pattern="/my/success/endpoint" access="permitAll"/>
    <logout logout-success-url="/my/success/endpoint"/>
</http>
----
======

Trong ví dụ này, bạn yêu cầu `LogoutFilter` redirect đến `/my/success/endpoint` khi hoàn tất.
Đồng thời, bạn cho phép rõ ràng endpoint `/my/success/endpoint` trong xref:servlet/authorization/authorize-http-requests.adoc[`AuthorizationFilter`].

Tuy nhiên, việc chỉ định hai lần có thể khá rườm rà.
Nếu đang sử dụng Java config, bạn có thể đặt property `permitAll` trong DSL `logout` như sau:

.Cho phép endpoint logout tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    .authorizeHttpRequests((authorize) -> authorize
        // ...
    )
    .logout((logout) -> logout
        .logoutSuccessUrl("/my/success/endpoint")
        .permitAll()
    )
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http
    authorizeHttpRequests {
        // ...
    }
    logout {
        logoutSuccessUrl = "/my/success/endpoint"
        permitAll = true
    }
----
======

thiết lập này sẽ tự thêm tất cả URI logout vào danh sách được phép cho bạn.

[[add-logout-handler]]
== Thêm các tác vụ dọn dẹp

Nếu đang sử dụng Java config, bạn có thể thêm các tác vụ dọn dẹp riêng bằng cách gọi method `addLogoutHandler` trong DSL `logout`, như sau:

.Logout handler tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
CookieClearingLogoutHandler cookies = new CookieClearingLogoutHandler("our-custom-cookie");
http
    .logout((logout) -> logout.addLogoutHandler(cookies))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    logout {
        addLogoutHandler(CookieClearingLogoutHandler("our-custom-cookie"))
    }
}
----
======

[NOTE]
Vì các instance javadoc:org.springframework.security.web.authentication.logout.LogoutHandler[] được dùng để dọn dẹp, chúng không nên ném exception.

[TIP]
Vì javadoc:org.springframework.security.web.authentication.logout.LogoutHandler[] là một functional interface, bạn có thể cung cấp một instance tùy chỉnh dưới dạng lambda.

Một số cấu hình của logout handler phổ biến đến mức được cung cấp trực tiếp trong DSL `logout` và element `<logout>`.
Ví dụ, bạn có thể cấu hình việc vô hiệu hóa session hoặc chỉ định các cookie bổ sung cần xóa.

Ví dụ, bạn có thể cấu hình javadoc:org.springframework.security.web.authentication.logout.CookieClearingLogoutHandler[] như trên.

[[delete-cookies]]
Hoặc bạn có thể đặt giá trị cấu hình phù hợp như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    .logout((logout) -> logout.deleteCookies("our-custom-cookie"))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    logout {
        deleteCookies("our-custom-cookie")
    }
}
----

Xml::
+
[source,kotlin,role="secondary"]
----
<http>
    <logout delete-cookies="our-custom-cookie"/>
</http>
----
======

[NOTE]
Không cần chỉ định cookie `JSESSIONID` vì javadoc:org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler[] sẽ xóa cookie này khi vô hiệu hóa session.

[[clear-all-site-data]]
=== Sử dụng Clear-Site-Data để logout người dùng

HTTP header `Clear-Site-Data` là chỉ thị được trình duyệt hỗ trợ để xóa cookie, storage và cache thuộc website đó.
Đây là một cách tiện lợi và an toàn để đảm bảo mọi thứ, bao gồm session cookie, được dọn dẹp khi logout.

Bạn có thể cấu hình Spring Security ghi header `Clear-Site-Data` khi logout như sau:

.Sử dụng Clear-Site-Data
[tabs]
======
Java::
+
[source,java,role="primary"]
----
HeaderWriterLogoutHandler clearSiteData = new HeaderWriterLogoutHandler(new ClearSiteDataHeaderWriter(Directive.ALL));
http
    .logout((logout) -> logout.addLogoutHandler(clearSiteData))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val clearSiteData = HeaderWriterLogoutHandler(ClearSiteDataHeaderWriter(Directive.ALL))
http {
    logout {
        addLogoutHandler(clearSiteData)
    }
}
----
======

Bạn truyền cho constructor của `ClearSiteDataHeaderWriter` danh sách những thứ muốn được xóa.

Cấu hình trên xóa toàn bộ site data, nhưng bạn cũng có thể cấu hình để chỉ xóa cookie như sau:

.Sử dụng Clear-Site-Data để xóa cookie
[tabs]
======
Java::
+
[source,java,role="primary"]
----
HeaderWriterLogoutHandler clearSiteData = new HeaderWriterLogoutHandler(new ClearSiteDataHeaderWriter(Directive.COOKIES));
http
    .logout((logout) -> logout.addLogoutHandler(clearSiteData))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val clearSiteData = HeaderWriterLogoutHandler(ClearSiteDataHeaderWriter(Directive.COOKIES))
http {
    logout {
        addLogoutHandler(clearSiteData)
    }
}
----
======

[[customizing-logout-success]]
== Tùy chỉnh xử lý logout thành công

Mặc dù sử dụng `logoutSuccessUrl` là đủ cho hầu hết trường hợp, bạn có thể cần làm điều gì đó khác thay vì redirect đến một URL sau khi logout hoàn tất.
javadoc:org.springframework.security.web.authentication.logout.LogoutSuccessHandler[] là component của Spring Security dùng để tùy chỉnh các thao tác sau khi logout thành công.

Ví dụ, thay vì redirect, bạn có thể chỉ muốn trả về một status code.
Trong trường hợp này, bạn có thể cung cấp một instance của success handler như sau:

.Tùy chỉnh logout thành công để trả về HTTP status code
[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    .logout((logout) -> logout.logoutSuccessHandler(new HttpStatusReturningLogoutSuccessHandler()))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    logout {
        logoutSuccessHandler = HttpStatusReturningLogoutSuccessHandler()
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<bean name="mySuccessHandlerBean" class="org.springframework.security.web.authentication.logout.HttpStatusReturningLogoutSuccessHandler"/>
<http>
    <logout success-handler-ref="mySuccessHandlerBean"/>
</http>
----
======

[TIP]
Vì javadoc:org.springframework.security.web.authentication.logout.LogoutSuccessHandler[] là một functional interface, bạn có thể cung cấp một instance tùy chỉnh dưới dạng lambda.

[[creating-custom-logout-endpoint]]
== Tạo endpoint logout tùy chỉnh

Bạn nên sử dụng DSL `logout` được cung cấp để cấu hình logout.
Một lý do là rất dễ quên gọi các component cần thiết của Spring Security để đảm bảo logout đầy đủ và đúng cách.

Trên thực tế, <<add-logout-handler,đăng ký một `LogoutHandler` tùy chỉnh>> thường đơn giản hơn việc tạo một endpoint {spring-framework-reference-url}web.html#spring-web[Spring MVC] để thực hiện logout.

Tuy vậy, nếu bạn gặp trường hợp cần một endpoint logout tùy chỉnh, như ví dụ sau:

.Endpoint logout tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@PostMapping("/my/logout")
public String performLogout() {
    // .. perform logout
    return "redirect:/home";
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@PostMapping("/my/logout")
fun performLogout(): String {
    // .. perform logout
    return "redirect:/home"
}
----
======

thì endpoint đó cần gọi javadoc:org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler[] của Spring Security để đảm bảo logout an toàn và đầy đủ.
Tối thiểu cần có đoạn tương tự như sau:

.Endpoint logout tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
SecurityContextLogoutHandler logoutHandler = new SecurityContextLogoutHandler();

@PostMapping("/my/logout")
public String performLogout(Authentication authentication, HttpServletRequest request, HttpServletResponse response) {
    // .. perform logout
    this.logoutHandler.logout(request, response, authentication);
    return "redirect:/home";
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val logoutHandler = SecurityContextLogoutHandler()

@PostMapping("/my/logout")
fun performLogout(val authentication: Authentication, val request: HttpServletRequest, val response: HttpServletResponse): String {
    // .. perform logout
    this.logoutHandler.logout(request, response, authentication)
    return "redirect:/home"
}
----
======

Thao tác này sẽ xóa javadoc:org.springframework.security.core.context.SecurityContextHolderStrategy[] và javadoc:org.springframework.security.web.context.SecurityContextRepository[] khi cần.

Ngoài ra, bạn sẽ cần <<permit-logout-endpoints,cho phép rõ ràng endpoint>>.

[WARNING]
Việc không gọi javadoc:org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler[] có nghĩa là xref:servlet/authentication/architecture.adoc#servlet-authentication-securitycontext[`SecurityContext`] vẫn có thể khả dụng trong các request tiếp theo, nghĩa là người dùng thực sự chưa logout.

[[testing-logout]]
== Kiểm thử logout
Sau khi cấu hình logout, bạn có thể kiểm thử bằng xref:servlet/test/mockmvc/logout.adoc[hỗ trợ MockMvc của Spring Security].

[[jc-logout-references]]
== Các tài liệu tham khảo khác về logout

- xref:servlet/test/mockmvc/logout.adoc#test-logout[Kiểm thử logout]
- xref:servlet/integrations/servlet-api.adoc#servletapi-logout[HttpServletRequest.logout()]
- xref:servlet/authentication/rememberme.adoc#remember-me-impls[Các interface và implementation của Remember-Me]
- xref:servlet/exploits/csrf.adoc#csrf-considerations-logout[Logout] trong mục Các lưu ý về CSRF
- Mục xref:servlet/authentication/cas.adoc#cas-singlelogout[Single Logout] (giao thức CAS)
- Tài liệu về xref:servlet/appendix/namespace/http.adoc#nsa-logout[element logout] trong mục Spring Security XML Namespace
