[[passkeys]]
= Passkeys

Spring Security hỗ trợ https://www.passkeys.com[passkey].
Passkey là phương thức authentication bảo mật hơn mật khẩu và được xây dựng bằng https://www.w3.org/TR/webauthn-3/[WebAuthn].

Để sử dụng passkey cho authentication, trước hết người dùng phải xref:servlet/authentication/passkeys.adoc#passkeys-register[đăng ký credential mới].
Sau khi credential được đăng ký, người dùng có thể dùng credential đó để thực hiện authentication bằng cách xref:servlet/authentication/passkeys.adoc#passkeys-verify[xác minh authentication assertion].

[[passkeys-dependencies]]
== Các dependency bắt buộc

Để bắt đầu, thêm dependency `spring-security-webauthn` vào dự án.

[NOTE]
====
Điều này giả định rằng bạn đang quản lý version của Spring Security bằng Spring Boot hoặc BOM của Spring Security như mô tả trong xref:getting-spring-security.adoc[].
====

.Các dependency của passkey
[tabs]
======
Maven::
+
[source,xml,role="primary",subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-webauthn</artifactId>
</dependency>
----

Gradle::
+
[source,groovy,role="secondary",subs="verbatim,attributes"]
----
dependencies {
    implementation "org.springframework.security:spring-security-webauthn"
}
----
======

[[passkeys-configuration]]
== Cấu hình

Cấu hình sau bật authentication bằng passkey.
Cấu hình này cung cấp cách xref:./passkeys.adoc#passkeys-register[] tại `/webauthn/register` và một trang đăng nhập mặc định cho phép xref:./passkeys.adoc#passkeys-verify[authentication bằng passkey].

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityFilterChain filterChain(HttpSecurity http) {
	// ...
	http
		// ...
		.formLogin(withDefaults())
		.webAuthn((webAuthn) -> webAuthn
			.rpId("example.com")
			.allowedOrigins("https://example.com")
			// các property tùy chọn
			.creationOptionsRepository(new CustomPublicKeyCredentialCreationOptionsRepository())
			.messageConverter(new CustomHttpMessageConverter())
		);
	return http.build();
}

@Bean
UserDetailsService userDetailsService() {
	UserDetails userDetails = User.withDefaultPasswordEncoder()
		.username("user")
		.password("password")
		.roles("USER")
		.build();

	return new InMemoryUserDetailsManager(userDetails);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
	// ...
	http {
		webAuthn {
			rpId = "example.com"
			allowedOrigins = setOf("https://example.com")
			// các property tùy chọn
			creationOptionsRepository = CustomPublicKeyCredentialCreationOptionsRepository()
			messageConverter = CustomHttpMessageConverter()
		}
	}
}

@Bean
open fun userDetailsService(): UserDetailsService {
	val userDetails = User.withDefaultPasswordEncoder()
		.username("user")
		.password("password")
		.roles("USER")
		.build()
	return InMemoryUserDetailsManager(userDetails)
}
----
======


[[passkeys-configuration-persistence]]
=== Persistence bằng JDBC và tùy chỉnh

WebAuthn thực hiện persistence bằng javadoc:org.springframework.security.web.webauthn.management.PublicKeyCredentialUserEntityRepository[] và javadoc:org.springframework.security.web.webauthn.management.UserCredentialRepository[].
Mặc định là persistence trong bộ nhớ, nhưng persistence bằng JDBC được hỗ trợ với javadoc:org.springframework.security.web.webauthn.management.JdbcPublicKeyCredentialUserEntityRepository[] và javadoc:org.springframework.security.web.webauthn.management.JdbcUserCredentialRepository[].
Để cấu hình persistence dựa trên JDBC, cung cấp các repository dưới dạng Bean:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
JdbcPublicKeyCredentialUserEntityRepository jdbcPublicKeyCredentialRepository(JdbcOperations jdbc) {
	return new JdbcPublicKeyCredentialUserEntityRepository(jdbc);
}

@Bean
JdbcUserCredentialRepository jdbcUserCredentialRepository(JdbcOperations jdbc) {
	return new JdbcUserCredentialRepository(jdbc);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun jdbcPublicKeyCredentialRepository(jdbc: JdbcOperations): JdbcPublicKeyCredentialUserEntityRepository {
    return JdbcPublicKeyCredentialUserEntityRepository(jdbc)
}

@Bean
fun jdbcUserCredentialRepository(jdbc: JdbcOperations): JdbcUserCredentialRepository {
    return JdbcUserCredentialRepository(jdbc)
}
----
======

Nếu JDBC không đáp ứng nhu cầu, bạn có thể tự tạo implementation của các interface và sử dụng chúng bằng cách cung cấp chúng dưới dạng Bean tương tự ví dụ trên.

[[passkeys-configuration-pkccor]]
=== PublicKeyCredentialCreationOptionsRepository tùy chỉnh

`PublicKeyCredentialCreationOptionsRepository` được dùng để persist `PublicKeyCredentialCreationOptions` giữa các request.
Mặc định, `PublicKeyCredentialCreationOptions` được persist trong `HttpSession`, nhưng đôi khi người dùng cần tùy chỉnh hành vi này.
Có thể thực hiện việc này bằng cách đặt property tùy chọn `creationOptionsRepository` như minh họa trong xref:./passkeys.adoc#passkeys-configuration[Cấu hình] hoặc cung cấp một Bean `PublicKeyCredentialCreationOptionsRepository`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
CustomPublicKeyCredentialCreationOptionsRepository creationOptionsRepository() {
	return new CustomPublicKeyCredentialCreationOptionsRepository();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun creationOptionsRepository(): CustomPublicKeyCredentialCreationOptionsRepository {
	return CustomPublicKeyCredentialCreationOptionsRepository()
}
----
======

[[passkeys-register]]
== Đăng ký credential mới

Để sử dụng passkey, trước hết người dùng phải https://www.w3.org/TR/webauthn-3/#sctn-registering-a-new-credential[đăng ký credential mới].

Việc đăng ký credential mới gồm hai bước:

1. Yêu cầu các tùy chọn đăng ký
2. Đăng ký credential

[[passkeys-register-options]]
=== Yêu cầu các tùy chọn đăng ký

Bước đầu tiên khi đăng ký credential mới là yêu cầu các tùy chọn đăng ký.
Trong Spring Security, request các tùy chọn đăng ký thường được thực hiện bằng JavaScript và có dạng:

[NOTE]
====
Spring Security cung cấp một trang đăng ký mặc định có thể dùng làm tài liệu tham khảo về cách đăng ký credential.
====

.Yêu cầu các tùy chọn đăng ký
[source,http]
----
POST /webauthn/register/options
X-CSRF-TOKEN: 4bfd1575-3ad1-4d21-96c7-4ef2d9f86721
----

Yêu cầu trên sẽ lấy các tùy chọn đăng ký cho người dùng hiện tại đã authenticated.
Vì challenge được persist (state bị thay đổi) để so sánh tại thời điểm đăng ký, request phải là POST và phải bao gồm CSRF token.

.Phản hồi cho các tùy chọn đăng ký
[source,json]
----
{
  "rp": {
    "name": "SimpleWebAuthn Example",
    "id": "example.localhost"
  },
  "user": {
    "name": "user@example.localhost",
    "id": "oWJtkJ6vJ_m5b84LB4_K7QKTCTEwLIjCh4tFMCGHO4w",
    "displayName": "user@example.localhost"
  },
  "challenge": "q7lCdd3SVQxdC-v8pnRAGEn1B2M-t7ZECWPwCAmhWvc",
  "pubKeyCredParams": [
    {
      "type": "public-key",
      "alg": -8
    },
    {
      "type": "public-key",
      "alg": -7
    },
    {
      "type": "public-key",
      "alg": -257
    }
  ],
  "timeout": 300000,
  "excludeCredentials": [],
  "authenticatorSelection": {
    "residentKey": "required",
    "userVerification": "preferred"
  },
  "attestation": "none",
  "extensions": {
    "credProps": true
  }
}
----

[[passkeys-register-create]]
=== Đăng ký credential

Sau khi lấy được các tùy chọn đăng ký, chúng được dùng để tạo các credential sẽ được đăng ký.
Để đăng ký credential mới, ứng dụng nên truyền các tùy chọn vào https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-create[`navigator.credentials.create`] sau khi giải mã base64url các giá trị nhị phân như `user.id`, `challenge` và `excludeCredentials[].id`.

Sau đó có thể gửi giá trị trả về đến máy chủ dưới dạng một JSON request.
Ví dụ về request đăng ký được trình bày bên dưới:

.Ví dụ request đăng ký
[source,http]
----
POST /webauthn/register
X-CSRF-TOKEN: 4bfd1575-3ad1-4d21-96c7-4ef2d9f86721

{
  "publicKey": { // <1>
    "credential": {
      "id": "dYF7EGnRFFIXkpXi9XU2wg",
      "rawId": "dYF7EGnRFFIXkpXi9XU2wg",
      "response": {
        "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YViUy9GqwTRaMpzVDbXq1dyEAXVOxrou08k22ggRC45MKNhdAAAAALraVWanqkAfvZZFYZpVEg0AEHWBexBp0RRSF5KV4vV1NsKlAQIDJiABIVggQjmrekPGzyqtoKK9HPUH-8Z2FLpoqkklFpFPQVICQ3IiWCD6I9Jvmor685fOZOyGXqUd87tXfvJk8rxj9OhuZvUALA",
        "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiSl9RTi10SFJYRWVKYjlNcUNrWmFPLUdOVmlibXpGVGVWMk43Z0ptQUdrQSIsIm9yaWdpbiI6Imh0dHBzOi8vZXhhbXBsZS5sb2NhbGhvc3Q6ODQ0MyIsImNyb3NzT3JpZ2luIjpmYWxzZX0",
        "transports": [
          "internal",
          "hybrid"
        ]
      },
      "type": "public-key",
      "clientExtensionResults": {},
      "authenticatorAttachment": "platform"
    },
    "label": "1password" // <2>
  }
}
----
<1> Kết quả gọi `navigator.credentials.create` với các giá trị nhị phân được mã hóa base64url.
<2> Nhãn do người dùng chọn để gắn với credential này, giúp người dùng phân biệt credential.

.Ví dụ phản hồi đăng ký thành công
[source,http]
----
HTTP/1.1 200 OK

{
  "success": true
}
----

[[passkeys-verify]]
== Xác minh authentication assertion

Sau khi xref:./passkeys.adoc#passkeys-register[], passkey có thể được https://www.w3.org/TR/webauthn-3/#sctn-verifying-assertion[xác minh] (authenticated).

Việc xác minh credential gồm hai bước:

1. Yêu cầu các tùy chọn xác minh
2. Xác minh credential

[[passkeys-verify-options]]
=== Yêu cầu các tùy chọn xác minh

Bước đầu tiên khi xác minh credential là yêu cầu các tùy chọn xác minh.
Trong Spring Security, request các tùy chọn xác minh thường được thực hiện bằng JavaScript và có dạng:

[NOTE]
====
Spring Security cung cấp một trang đăng nhập mặc định có thể dùng làm tài liệu tham khảo về cách xác minh credential.
====

.Yêu cầu các tùy chọn xác minh
[source,http]
----
POST /webauthn/authenticate/options
X-CSRF-TOKEN: 4bfd1575-3ad1-4d21-96c7-4ef2d9f86721
----

Yêu cầu trên sẽ lấy các tùy chọn xác minh.
Vì challenge được persist (state bị thay đổi) để so sánh tại thời điểm authentication, request phải là POST và phải bao gồm CSRF token.

Phản hồi sẽ chứa các tùy chọn để lấy credential, trong đó các giá trị nhị phân như `challenge` được mã hóa base64url.

.Ví dụ phản hồi cho các tùy chọn xác minh
[source,json]
----
{
  "challenge": "cQfdGrj9zDg3zNBkOH3WPL954FTOShVy0-CoNgSewNM",
  "timeout": 300000,
  "rpId": "example.localhost",
  "allowCredentials": [],
  "userVerification": "preferred",
  "extensions": {}
}
----

[[passkeys-verify-get]]
=== Xác minh credential

Sau khi lấy được các tùy chọn xác minh, chúng được dùng để lấy credential.
Để lấy credential, ứng dụng nên truyền các tùy chọn vào https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-create[`navigator.credentials.get`] sau khi giải mã base64url các giá trị nhị phân như `challenge`.

Sau đó có thể gửi giá trị trả về của `navigator.credentials.get` đến máy chủ dưới dạng một JSON request.
Các giá trị nhị phân như `rawId` và `response.*` phải được mã hóa base64url.
Ví dụ về request authentication được trình bày bên dưới:

.Ví dụ request authentication
[source,http]
----
POST /login/webauthn
X-CSRF-TOKEN: 4bfd1575-3ad1-4d21-96c7-4ef2d9f86721

{
  "id": "dYF7EGnRFFIXkpXi9XU2wg",
  "rawId": "dYF7EGnRFFIXkpXi9XU2wg",
  "response": {
    "authenticatorData": "y9GqwTRaMpzVDbXq1dyEAXVOxrou08k22ggRC45MKNgdAAAAAA",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiRFVsRzRDbU9naWhKMG1vdXZFcE9HdUk0ZVJ6MGRRWmxUQmFtbjdHQ1FTNCIsIm9yaWdpbiI6Imh0dHBzOi8vZXhhbXBsZS5sb2NhbGhvc3Q6ODQ0MyIsImNyb3NzT3JpZ2luIjpmYWxzZX0",
    "signature": "MEYCIQCW2BcUkRCAXDmGxwMi78jknenZ7_amWrUJEYoTkweldAIhAMD0EMp1rw2GfwhdrsFIeDsL7tfOXVPwOtfqJntjAo4z",
    "userHandle": "Q3_0Xd64_HW0BlKRAJnVagJTpLKLgARCj8zjugpRnVo"
  },
  "clientExtensionResults": {},
  "authenticatorAttachment": "platform"
}
----

.Ví dụ phản hồi authentication thành công
[source,http]
----
HTTP/1.1 200 OK

{
  "redirectUrl": "/", // <1>
  "authenticated": true // <2>
}
----
<1> URL để redirect đến
<2> Cho biết người dùng đã authenticated

.Ví dụ phản hồi authentication thất bại
[source,http]
----
HTTP/1.1 401 OK

----
