[[runas]]
= Thay thế Authentication bằng Run-As

[[runas-overview]]
`AbstractSecurityInterceptor` có khả năng tạm thời thay thế đối tượng `Authentication` trong `SecurityContext` và `SecurityContextHolder` trong giai đoạn callback của đối tượng được bảo mật.
Việc này chỉ xảy ra nếu đối tượng `Authentication` ban đầu đã được `AuthenticationManager` và `AccessDecisionManager` xử lý thành công.
`RunAsManager` chỉ ra đối tượng `Authentication` thay thế, nếu có, cần được sử dụng trong `SecurityInterceptorCallback`.

Bằng cách tạm thời thay thế đối tượng `Authentication` trong giai đoạn callback của đối tượng được bảo mật, lời gọi được bảo mật có thể gọi các đối tượng khác yêu cầu các credential khác nhau cho authentication và authorization.
Lời gọi đó cũng có thể thực hiện các kiểm tra bảo mật nội bộ đối với những đối tượng `GrantedAuthority` cụ thể.
Vì Spring Security cung cấp một số class hỗ trợ tự động cấu hình các protocol remoting dựa trên nội dung của `SecurityContextHolder`, những thay thế run-as này đặc biệt hữu ích khi gọi các web service từ xa.

[[runas-config]]
== Cấu hình
Spring Security cung cấp một interface `RunAsManager`:

[source,java]
----
Authentication buildRunAs(Authentication authentication, Object object,
	List<ConfigAttribute> config);

boolean supports(ConfigAttribute attribute);

boolean supports(Class clazz);
----


Method đầu tiên trả về đối tượng `Authentication` sẽ thay thế đối tượng `Authentication` hiện có trong suốt thời gian lời gọi method.
Nếu method trả về `null`, điều đó cho biết không nên thực hiện việc thay thế.
Method thứ hai được `AbstractSecurityInterceptor` sử dụng như một phần của việc validation lúc khởi động đối với các configuration attribute.
Method `supports(Class)` được một triển khai security interceptor gọi để bảo đảm `RunAsManager` đã cấu hình hỗ trợ kiểu đối tượng được bảo mật mà security interceptor cung cấp.

Spring Security cung cấp một triển khai cụ thể của `RunAsManager`.
Class `RunAsManagerImpl` trả về một `RunAsUserToken` thay thế nếu bất kỳ `ConfigAttribute` nào bắt đầu bằng `RUN_AS_`.
Nếu tìm thấy `ConfigAttribute` như vậy, `RunAsUserToken` thay thế chứa cùng principal, credential và granted authority như đối tượng `Authentication` ban đầu, cùng với một `SimpleGrantedAuthority` mới cho mỗi `ConfigAttribute` `RUN_AS_`.
Mỗi `SimpleGrantedAuthority` mới được thêm tiền tố `ROLE_`, theo sau là `ConfigAttribute` `RUN_AS`.
Ví dụ, `RUN_AS_SERVER` tạo ra một `RunAsUserToken` thay thế chứa granted authority `ROLE_RUN_AS_SERVER`.

`RunAsUserToken` thay thế cũng giống như bất kỳ đối tượng `Authentication` nào khác.
Nó cần được `AuthenticationManager` thực hiện authentication, có thể thông qua việc ủy quyền cho một `AuthenticationProvider` phù hợp.
`RunAsImplAuthenticationProvider` thực hiện authentication đó.
`RunAsImplAuthenticationProvider` chấp nhận mọi `RunAsUserToken` được cung cấp là hợp lệ.

Để bảo đảm code độc hại không thể tạo một `RunAsUserToken` rồi cung cấp nó để được `RunAsImplAuthenticationProvider` chấp nhận chắc chắn, hash của một key được lưu trong tất cả token được tạo.
`RunAsManagerImpl` và `RunAsImplAuthenticationProvider` được tạo trong bean context với cùng một key:

[source,xml]
----
<bean id="runAsManager"
	class="org.springframework.security.access.intercept.RunAsManagerImpl">
<property name="key" value="my_run_as_password"/>
</bean>

<bean id="runAsAuthenticationProvider"
	class="org.springframework.security.access.intercept.RunAsImplAuthenticationProvider">
<property name="key" value="my_run_as_password"/>
</bean>
----

Bằng cách sử dụng cùng một key, mỗi `RunAsUserToken` có thể được validation vì nó được tạo bởi một `RunAsManagerImpl` đã được chấp thuận.
`RunAsUserToken` là bất biến sau khi được tạo, vì lý do bảo mật.
