[[runas]]
= Thay thế Authentication bằng Run-As

[[runas-overview]]
`AbstractSecurityInterceptor` có khả năng tạm thời thay thế `Authentication` object trong `SecurityContext` và `SecurityContextHolder` trong callback phase của secure object.
Việc này chỉ xảy ra nếu `Authentication` object ban đầu đã được `AuthenticationManager` và `AccessDecisionManager` xử lý thành công.
`RunAsManager` chỉ ra replacement `Authentication` object, nếu có, sẽ được sử dụng trong `SecurityInterceptorCallback`.

Bằng cách tạm thời thay thế `Authentication` object trong callback phase của secure object, secured invocation có thể gọi các object khác yêu cầu các credential khác nhau cho authentication và authorization.
Secured invocation cũng có thể thực hiện các security check nội bộ đối với các `GrantedAuthority` object cụ thể.
Vì Spring Security cung cấp một số class hỗ trợ tự động cấu hình các remoting protocol dựa trên nội dung của `SecurityContextHolder`, các run-as replacement này đặc biệt hữu ích khi gọi remote web service.

[[runas-config]]
== Cấu hình
Spring Security cung cấp một interface `RunAsManager`:

[source,java]
----
Authentication buildRunAs(Authentication authentication, Object object,
	List<ConfigAttribute> config);

boolean supports(ConfigAttribute attribute);

boolean supports(Class clazz);
----


Method đầu tiên trả về `Authentication` object sẽ thay thế `Authentication` object hiện có trong suốt thời gian method invocation.
Nếu method trả về `null`, điều đó cho biết không nên thực hiện replacement.
Method thứ hai được `AbstractSecurityInterceptor` sử dụng như một phần của startup validation đối với các configuration attribute.
Method `supports(Class)` được một security interceptor implementation gọi để bảo đảm `RunAsManager` đã cấu hình hỗ trợ kiểu secure object mà security interceptor cung cấp.

Spring Security cung cấp một implementation cụ thể của `RunAsManager`.
Class `RunAsManagerImpl` trả về một replacement `RunAsUserToken` nếu bất kỳ `ConfigAttribute` nào bắt đầu bằng `RUN_AS_`.
Nếu tìm thấy `ConfigAttribute` như vậy, replacement `RunAsUserToken` chứa cùng principal, credentials và granted authorities như `Authentication` object ban đầu, cùng với một `SimpleGrantedAuthority` mới cho mỗi `RUN_AS_` `ConfigAttribute`.
Mỗi `SimpleGrantedAuthority` mới được thêm prefix `ROLE_`, theo sau là `RUN_AS` `ConfigAttribute`.
Ví dụ, `RUN_AS_SERVER` tạo ra một replacement `RunAsUserToken` chứa granted authority `ROLE_RUN_AS_SERVER`.

Replacement `RunAsUserToken` cũng giống như mọi `Authentication` object khác.
Nó cần được `AuthenticationManager` authenticated, có thể thông qua việc delegate đến một `AuthenticationProvider` phù hợp.
`RunAsImplAuthenticationProvider` thực hiện authentication đó.
`RunAsImplAuthenticationProvider` chấp nhận mọi `RunAsUserToken` được cung cấp là hợp lệ.

Để bảo đảm malicious code không thể tạo một `RunAsUserToken` rồi cung cấp token đó để `RunAsImplAuthenticationProvider` chấp nhận, hash của một key được lưu trong mọi token được tạo.
`RunAsManagerImpl` và `RunAsImplAuthenticationProvider` được tạo trong bean context với cùng một key:

[source,xml]
----
<bean id="runAsManager"
	class="org.springframework.security.access.intercept.RunAsManagerImpl">
<property name="key" value="my_run_as_password"/>
</bean>

<bean id="runAsAuthenticationProvider"
	class="org.springframework.security.access.intercept.RunAsImplAuthenticationProvider">
<property name="key" value="my_run_as_password"/>
</bean>
----

Bằng cách sử dụng cùng một key, mỗi `RunAsUserToken` có thể được validate vì nó được tạo bởi một `RunAsManagerImpl` đã được chấp thuận.
`RunAsUserToken` là bất biến sau khi được tạo, vì lý do bảo mật.
