[[session-mgmt]]
= Persistence của Authentication và Session Management

Sau khi có một application xref:servlet/authentication/index.adoc[thực hiện authentication cho các request], điều quan trọng là xem xét authentication thu được sẽ được persist và restore như thế nào trong các request tiếp theo.

Theo mặc định, việc này được thực hiện tự động.
Nếu bạn có một custom filter hoặc controller đang thiết lập `SecurityContext`, bạn cần dùng `SecurityContextRepository` để persist nó qua các request.

Nếu đang upgrade từ một version cũ hơn, bạn có thể quan tâm đến setting `requireExplicitSave`, setting này giữ lại default của Spring Security 5; tuy nhiên, lưu ý rằng nó chủ yếu phục vụ mục đích migration.

Nếu muốn, bạn có thể <<how-it-works-requireexplicitsave,đọc thêm về cách requireExplicitSave hoạt động>> hoặc <<requireexplicitsave,vì sao nó quan trọng>>. Nếu không, trong hầu hết trường hợp, bạn đã hoàn tất section này.

Nhưng trước khi rời khỏi section này, hãy xem application của bạn có thuộc trường hợp sử dụng nào sau đây không:

* Tôi muốn <<understanding-session-management-components,tìm hiểu các component của Session Management>>
* Tôi muốn <<ns-concurrent-sessions,giới hạn số lần một người dùng có thể đăng nhập đồng thời>>
* Tôi muốn <<store-authentication-manually,tự lưu authentication trực tiếp>> thay vì để Spring Security thực hiện việc đó
* Tôi đang tự lưu authentication và muốn <<properly-clearing-authentication,xóa nó>>
* Tôi đang dùng <<the-sessionmanagementfilter, `SessionManagementFilter`>> và cần <<moving-away-from-sessionmanagementfilter,hướng dẫn chuyển sang cách khác>>
* Tôi muốn lưu authentication <<customizing-where-authentication-is-stored,vào nơi khác ngoài session>>
* Tôi đang dùng <<stateless-authentication, stateless authentication>>, nhưng <<storing-stateless-authentication-in-the-session,vẫn muốn lưu nó vào session>>
* Tôi đang dùng `SessionCreationPolicy.NEVER` nhưng <<never-policy-session-still-created,ứng dụng vẫn đang tạo session>>.


[[understanding-session-management-components]]
== Tìm hiểu các component của Session Management

Hỗ trợ cho Session Management gồm một vài component phối hợp với nhau để cung cấp chức năng này.
Các component đó là xref:servlet/authentication/persistence.adoc#securitycontextholderfilter[`SecurityContextHolderFilter`], xref:servlet/authentication/persistence.adoc#securitycontextpersistencefilter[`SecurityContextPersistenceFilter`] và <<the-sessionmanagementfilter,`SessionManagementFilter`>>.

[NOTE]
=====
Trong Spring Security 6, `SecurityContextPersistenceFilter` và `SessionManagementFilter` không được thiết lập theo mặc định.
Ngoài ra, mỗi ứng dụng chỉ nên thiết lập một trong `SecurityContextHolderFilter` hoặc `SecurityContextPersistenceFilter`, không bao giờ thiết lập cả hai.
=====

[[the-sessionmanagementfilter]]
=== `SessionManagementFilter`

`SessionManagementFilter` kiểm tra nội dung của `SecurityContextRepository` với nội dung hiện tại của `SecurityContextHolder` để xác định người dùng đã được authenticated trong request hiện tại hay chưa, thường thông qua một cơ chế authentication non-interactive như pre-authentication hoặc remember-me  footnote:[
Các cơ chế authentication thực hiện redirect sau khi authenticate (chẳng hạn form-login) sẽ không được `SessionManagementFilter` phát hiện, vì filter sẽ không được gọi trong request thực hiện authentication.
Trong các trường hợp này, chức năng session management phải được xử lý riêng.
].
Nếu repository chứa `SecurityContext`, filter không làm gì cả.
Nếu không, và `SecurityContext` thread-local chứa một object `Authentication` (không phải anonymous), filter giả định rằng người dùng đã được authenticated bởi một filter trước đó trong stack.
Sau đó, filter sẽ gọi `SessionAuthenticationStrategy` đã được cấu hình.

Nếu người dùng hiện chưa được authenticated, filter sẽ kiểm tra xem request có chứa session ID không hợp lệ hay không (chẳng hạn do timeout), rồi gọi `InvalidSessionStrategy` đã cấu hình nếu có.
Hành vi phổ biến nhất là redirect đến một URL cố định; hành vi này được đóng gói trong implementation chuẩn `SimpleRedirectInvalidSessionStrategy`.
Implementation này cũng được dùng khi cấu hình URL cho invalid session thông qua namespace, <<session-mgmt,như đã mô tả trước đó>>.

[[moving-away-from-sessionmanagementfilter]]
==== Chuyển khỏi `SessionManagementFilter`

Trong Spring Security 5, cấu hình mặc định dựa vào `SessionManagementFilter` để phát hiện người dùng vừa authenticate và gọi javadoc:org.springframework.security.web.authentication.session.SessionAuthenticationStrategy[SessionAuthenticationStrategy].
Vấn đề là trong một setup điển hình, `HttpSession` phải được đọc trong mọi request.

Trong Spring Security 6, mặc định là chính các authentication mechanism phải gọi `SessionAuthenticationStrategy`.
Điều này có nghĩa là không cần phát hiện thời điểm `Authentication` hoàn tất, và do đó không cần đọc `HttpSession` trong mọi request.

==== Các điểm cần cân nhắc khi chuyển khỏi `SessionManagementFilter`

Trong Spring Security 6, `SessionManagementFilter` không được dùng theo mặc định; vì vậy, một số method trong DSL `sessionManagement` sẽ không có tác dụng.

|===
|Method |Thay thế

|`sessionAuthenticationErrorUrl`
|Cấu hình javadoc:org.springframework.security.web.authentication.AuthenticationFailureHandler[] trong authentication mechanism

|`sessionAuthenticationFailureHandler`
|Cấu hình javadoc:org.springframework.security.web.authentication.AuthenticationFailureHandler[] trong authentication mechanism

|`sessionAuthenticationStrategy`
|Cấu hình `SessionAuthenticationStrategy` trong cơ chế authentication như đã <<moving-away-from-sessionmanagementfilter,thảo luận ở trên>>
|===

Nếu cố dùng bất kỳ method nào trong số này, một exception sẽ được ném ra.


[[customizing-where-authentication-is-stored]]
== Tùy chỉnh nơi lưu Authentication

Theo mặc định, Spring Security lưu `SecurityContext` vào HTTP session. Tuy nhiên, có một số lý do khiến bạn có thể muốn tùy chỉnh việc này:

* Bạn có thể muốn gọi các setter riêng lẻ trên instance `HttpSessionSecurityContextRepository`
* Bạn có thể muốn lưu `SecurityContext` vào cache hoặc database để hỗ trợ horizontal scaling

Trước tiên, bạn cần tạo một implementation của `SecurityContextRepository` hoặc dùng implementation có sẵn như `HttpSessionSecurityContextRepository`, sau đó có thể thiết lập nó trong `HttpSecurity`.

[[customizing-the-securitycontextrepository]]
.Tùy chỉnh `SecurityContextRepository`
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    SecurityContextRepository repo = new MyCustomSecurityContextRepository();
    http
        // ...
        .securityContext((context) -> context
            .securityContextRepository(repo)
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    val repo = MyCustomSecurityContextRepository()
    http {
        // ...
        securityContext {
            securityContextRepository = repo
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http security-context-repository-ref="repo">
    <!-- ... -->
</http>
<bean name="repo" class="com.example.MyCustomSecurityContextRepository" />
----
======

[NOTE]
====
Cấu hình trên thiết lập `SecurityContextRepository` trên `SecurityContextHolderFilter` và các authentication filter **tham gia**, chẳng hạn `UsernamePasswordAuthenticationFilter`.
Để thiết lập nó trên cả các stateless filter, hãy xem <<storing-stateless-authentication-in-the-session,cách tùy chỉnh `SecurityContextRepository` cho Stateless Authentication>>.
====

Nếu đang dùng cơ chế authentication tùy chỉnh, bạn có thể muốn <<store-authentication-manually,tự lưu `Authentication`>>.

[[store-authentication-manually]]
=== Lưu `Authentication` thủ công

Trong một số trường hợp, chẳng hạn khi bạn tự authenticate cho người dùng thay vì dựa vào các filter của Spring Security, bạn có thể dùng một custom filter hoặc endpoint {spring-framework-reference-url}/web.html#mvc-controller[Spring MVC controller] để thực hiện việc đó.
Nếu muốn lưu authentication giữa các request, chẳng hạn lưu vào `HttpSession`, bạn phải làm như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
private SecurityContextRepository securityContextRepository =
        new HttpSessionSecurityContextRepository(); <1>

@PostMapping("/login")
public void login(@RequestBody LoginRequest loginRequest, HttpServletRequest request, HttpServletResponse response) { <2>
    UsernamePasswordAuthenticationToken token = UsernamePasswordAuthenticationToken.unauthenticated(
        loginRequest.getUsername(), loginRequest.getPassword()); <3>
    Authentication authentication = authenticationManager.authenticate(token); <4>
    SecurityContext context = securityContextHolderStrategy.createEmptyContext();
    context.setAuthentication(authentication); <5>
    securityContextHolderStrategy.setContext(context);
    securityContextRepository.saveContext(context, request, response); <6>
}

class LoginRequest {

    private String username;
    private String password;

    // getters and setters
}
----
======

<1> Thêm `SecurityContextRepository` vào controller
<2> Inject `HttpServletRequest` và `HttpServletResponse` để có thể lưu `SecurityContext`
<3> Tạo `UsernamePasswordAuthenticationToken` chưa authentication bằng credential được cung cấp
<4> Gọi `AuthenticationManager#authenticate` để authenticate người dùng
<5> Tạo `SecurityContext` và thiết lập `Authentication` vào đó
<6> Lưu `SecurityContext` vào `SecurityContextRepository`

Vậy là xong.
Nếu chưa chắc `securityContextHolderStrategy` trong ví dụ trên là gì, bạn có thể đọc thêm trong <<use-securitycontextholderstrategy,section Sử dụng `SecurityContextStrategy`>>.

[[properly-clearing-authentication]]
=== Xóa Authentication đúng cách

Nếu đang dùng xref:servlet/authentication/logout.adoc[Logout Support] của Spring Security, nó xử lý nhiều việc cho bạn, bao gồm xóa và lưu context.
Tuy nhiên, nếu cần tự logout người dùng khỏi ứng dụng, bạn phải bảo đảm mình đang xref:servlet/authentication/logout.adoc#creating-custom-logout-endpoint[xóa và lưu context đúng cách].

[[stateless-authentication]]
=== Cấu hình Persistence cho Stateless Authentication

Đôi khi không cần tạo và duy trì `HttpSession`, chẳng hạn để persist authentication qua các request.
Một số authentication mechanism như xref:servlet/authentication/passwords/basic.adoc[HTTP Basic] là stateless và vì vậy sẽ authenticate lại người dùng trong mỗi request.

Nếu không muốn tạo session, bạn có thể dùng `SessionCreationPolicy.STATELESS` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        // ...
        .sessionManagement((session) -> session
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        // ...
        sessionManagement {
            sessionCreationPolicy = SessionCreationPolicy.STATELESS
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http create-session="stateless">
    <!-- ... -->
</http>
----
======

Cấu hình trên là <<customizing-where-authentication-is-stored,cấu hình `SecurityContextRepository`>> để dùng `NullSecurityContextRepository`, đồng thời xref:servlet/architecture.adoc#requestcache-prevent-saved-request[ngăn request được lưu vào session].


[[never-policy-session-still-created]]
Nếu đang dùng `SessionCreationPolicy.NEVER`, bạn có thể nhận thấy ứng dụng vẫn đang tạo `HttpSession`.
Trong hầu hết trường hợp, điều này xảy ra vì xref:servlet/architecture.adoc#savedrequests[request được lưu vào session] để sau khi authentication thành công, request lại resource cần authentication.
Để tránh điều đó, hãy xem section xref:servlet/architecture.adoc#requestcache-prevent-saved-request[về cách ngăn request được lưu].


[[storing-stateless-authentication-in-the-session]]
==== Lưu Stateless Authentication vào Session

Nếu vì lý do nào đó bạn đang dùng một stateless authentication mechanism nhưng vẫn muốn lưu authentication vào session, bạn có thể dùng `HttpSessionSecurityContextRepository` thay cho `NullSecurityContextRepository`.

Đối với xref:servlet/authentication/passwords/basic.adoc[HTTP Basic], bạn có thể thêm xref:servlet/configuration/java.adoc#post-processing-configured-objects[`ObjectPostProcessor`] để thay đổi `SecurityContextRepository` mà `BasicAuthenticationFilter` sử dụng:

.Lưu authentication của HTTP Basic vào `HttpSession`
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityFilterChain web(HttpSecurity http) throws Exception {
    http
        // ...
        .httpBasic((basic) -> basic
            .addObjectPostProcessor(new ObjectPostProcessor<BasicAuthenticationFilter>() {
                @Override
                public <O extends BasicAuthenticationFilter> O postProcess(O filter) {
                    filter.setSecurityContextRepository(new HttpSessionSecurityContextRepository());
                    return filter;
                }
            })
        );

    return http.build();
}
----
======

Điều này cũng áp dụng cho các authentication mechanism khác, chẳng hạn xref:servlet/oauth2/resource-server/index.adoc[Bearer Token Authentication].


[[requireexplicitsave]]
== Tìm hiểu Require Explicit Save

Trong Spring Security 5, hành vi mặc định là xref:servlet/authentication/architecture.adoc#servlet-authentication-securitycontext[`SecurityContext`] được tự động lưu vào xref:servlet/authentication/persistence.adoc#securitycontextrepository[`SecurityContextRepository`] bằng <<securitycontextpersistencefilter, `SecurityContextPersistenceFilter`>>.
Việc lưu phải được thực hiện ngay trước khi `HttpServletResponse` được commit và ngay trước `SecurityContextPersistenceFilter`.
Đáng tiếc, auto-persistence của `SecurityContext` có thể khiến người dùng bất ngờ khi được thực hiện trước khi request hoàn tất (tức ngay trước khi commit `HttpServletResponse`).
Việc theo dõi state để xác định có cần save hay không cũng phức tạp, đôi khi dẫn đến các lần write không cần thiết vào `SecurityContextRepository` (tức `HttpSession`).

Vì những lý do này, `SecurityContextPersistenceFilter` đã deprecated và được thay thế bằng `SecurityContextHolderFilter`.
Trong Spring Security 6, hành vi mặc định là xref:servlet/authentication/persistence.adoc#securitycontextholderfilter[`SecurityContextHolderFilter`] chỉ đọc `SecurityContext` từ `SecurityContextRepository` và nạp nó vào `SecurityContextHolder`.
Giờ đây, người dùng phải lưu tường minh `SecurityContext` bằng `SecurityContextRepository` nếu muốn `SecurityContext` được persist giữa các request.
Điều này loại bỏ sự mơ hồ và cải thiện performance bằng cách chỉ yêu cầu ghi vào `SecurityContextRepository` (tức `HttpSession`) khi cần.

[[how-it-works-requireexplicitsave]]
=== Cách hoạt động

Tóm lại, khi `requireExplicitSave` là `true`, Spring Security thiết lập xref:servlet/authentication/persistence.adoc#securitycontextholderfilter[`SecurityContextHolderFilter`] thay cho xref:servlet/authentication/persistence.adoc#securitycontextpersistencefilter[`SecurityContextPersistenceFilter`]


[[ns-concurrent-sessions]]
== Cấu hình Concurrent Session Control
Nếu muốn đặt giới hạn số lần một người dùng có thể login vào application, Spring Security hỗ trợ sẵn điều này với các bổ sung đơn giản sau.
Trước tiên, bạn cần thêm listener sau vào cấu hình để Spring Security được cập nhật về các event trong lifecycle của session:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public HttpSessionEventPublisher httpSessionEventPublisher() {
    return new HttpSessionEventPublisher();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun httpSessionEventPublisher(): HttpSessionEventPublisher {
    return HttpSessionEventPublisher()
}
----

web.xml::
+
[source,xml,role="secondary"]
----
<listener>
<listener-class>
    org.springframework.security.web.session.HttpSessionEventPublisher
</listener-class>
</listener>
----
======

Sau đó thêm các dòng sau vào security configuration:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .sessionManagement((session) -> session
            .maximumSessions(1)
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        sessionManagement {
            sessionConcurrency {
                maximumSessions = 1
            }
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
...
<session-management>
    <concurrency-control max-sessions="1" />
</session-management>
</http>
----
======


Điều này ngăn người dùng login nhiều lần; lần login thứ hai sẽ khiến session đầu tiên bị invalidate.

Bạn cũng có thể điều chỉnh giới hạn này tùy theo người dùng.
Ví dụ, administrator có thể được phép có nhiều hơn một session:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
	AuthorizationManager<?> isAdmin = AuthorityAuthorizationManager.hasRole("ADMIN");
    http
        .sessionManagement((session) -> session
            .maximumSessions((authentication) -> isAdmin.authorize(() -> authentication, null).isGranted() ? -1 : 1)
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    val isAdmin: AuthorizationManager<*> = AuthorityAuthorizationManager.hasRole("ADMIN")
    http {
        sessionManagement {
            sessionConcurrency {
                maximumSessions {
                    authentication -> if (isAdmin.authorize({ authentication }, null)!!.isGranted) -1 else 1
                }
            }
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
...
<session-management>
    <concurrency-control max-sessions-ref="sessionLimit" />
</session-management>
</http>

<b:bean id="sessionLimit" class="my.SessionLimitImplementation"/>
----
======

Khi dùng Spring Boot, bạn có thể test các cấu hình trên như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
public class MaximumSessionsTests {

    @Autowired
    private MockMvc mvc;

    @Test
    void loginOnSecondLoginThenFirstSessionTerminated() throws Exception {
        MvcResult mvcResult = this.mvc.perform(formLogin())
                .andExpect(authenticated())
                .andReturn();

        MockHttpSession firstLoginSession = (MockHttpSession) mvcResult.getRequest().getSession();

        this.mvc.perform(get("/").session(firstLoginSession))
                .andExpect(authenticated());

        this.mvc.perform(formLogin()).andExpect(authenticated());

        // session đầu tiên bị chấm dứt bởi lần đăng nhập thứ hai
        this.mvc.perform(get("/").session(firstLoginSession))
                .andExpect(unauthenticated());
    }

}
----
======

Bạn có thể thử bằng {gh-samples-url}/servlet/spring-boot/java/session-management/maximum-sessions[Maximum Sessions sample].

Một trường hợp phổ biến khác là bạn muốn ngăn login lần thứ hai; khi đó có thể dùng:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .sessionManagement((session) -> session
            .maximumSessions(1)
            .maxSessionsPreventsLogin(true)
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        sessionManagement {
            sessionConcurrency {
                maximumSessions = 1
                maxSessionsPreventsLogin = true
            }
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
<session-management>
    <concurrency-control max-sessions="1" error-if-maximum-exceeded="true" />
</session-management>
</http>
----
======


Khi đó, lần login thứ hai sẽ bị từ chối.
"Bị từ chối" nghĩa là người dùng sẽ được chuyển đến `authentication-failure-url` nếu đang dùng form-based login.
Nếu lần authentication thứ hai diễn ra qua một non-interactive mechanism khác, chẳng hạn "remember-me", client sẽ nhận lỗi "unauthorized" (401).
Nếu thay vào đó muốn dùng error page, bạn có thể thêm attribute `session-authentication-error-url` vào element `session-management`.

Khi dùng Spring Boot, bạn có thể test cấu hình trên như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
public class MaximumSessionsPreventLoginTests {

    @Autowired
    private MockMvc mvc;

    @Test
    void loginOnSecondLoginThenPreventLogin() throws Exception {
        MvcResult mvcResult = this.mvc.perform(formLogin())
                .andExpect(authenticated())
                .andReturn();

        MockHttpSession firstLoginSession = (MockHttpSession) mvcResult.getRequest().getSession();

        this.mvc.perform(get("/").session(firstLoginSession))
                .andExpect(authenticated());

        // lần đăng nhập thứ hai bị ngăn
        this.mvc.perform(formLogin()).andExpect(unauthenticated());

        // session đầu tiên vẫn hợp lệ
        this.mvc.perform(get("/").session(firstLoginSession))
                .andExpect(authenticated());
    }

}
----
======

Nếu đang dùng custom authentication filter cho form-based login, bạn phải cấu hình tường minh hỗ trợ concurrent session control.
Bạn có thể thử bằng {gh-samples-url}/servlet/spring-boot/java/session-management/maximum-sessions-prevent-login[Maximum Sessions Prevent Login sample].

[NOTE]
=====
Nếu đang dùng implementation tùy chỉnh của `UserDetails`, hãy bảo đảm bạn override các method **equals()** và **hashCode()**.
Implementation `SessionRegistry` mặc định trong Spring Security dựa trên một in-memory Map sử dụng các method này để nhận diện và quản lý session của người dùng một cách chính xác.
Không override chúng có thể khiến việc theo dõi session và so sánh người dùng hoạt động không như mong đợi.
=====

== Phát hiện Session Timeout

Session tự hết hạn, và không cần làm gì để bảo đảm `SecurityContext` được xóa.
Dù vậy, Spring Security có thể phát hiện khi session hết hạn và thực hiện các hành động cụ thể do bạn chỉ định.
Ví dụ, bạn có thể muốn redirect đến một endpoint cụ thể khi người dùng thực hiện request bằng session đã hết hạn.
Việc này được thực hiện thông qua `invalidSessionUrl` trong `HttpSecurity`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .sessionManagement((session) -> session
            .invalidSessionUrl("/invalidSession")
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        sessionManagement {
            invalidSessionUrl = "/invalidSession"
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
...
<session-management invalid-session-url="/invalidSession" />
</http>
----
======

Lưu ý rằng nếu dùng cơ chế này để phát hiện session timeout, nó có thể báo lỗi không chính xác nếu người dùng logout rồi login lại mà không đóng trình duyệt.
Điều này xảy ra vì session cookie không bị xóa khi bạn invalidate session và sẽ được gửi lại dù người dùng đã logout.
Nếu gặp trường hợp đó, bạn có thể muốn <<clearing-session-cookie-on-logout,cấu hình logout để xóa session cookie>>.

=== Tùy chỉnh Invalid Session Strategy

`invalidSessionUrl` là một convenience method để thiết lập `InvalidSessionStrategy` bằng javadoc:org.springframework.security.web.session.SimpleRedirectInvalidSessionStrategy[implementation `SimpleRedirectInvalidSessionStrategy`].
Nếu muốn tùy chỉnh hành vi, bạn có thể implement interface javadoc:org.springframework.security.web.session.InvalidSessionStrategy[] và cấu hình nó bằng method `invalidSessionStrategy`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .sessionManagement((session) -> session
            .invalidSessionStrategy(new MyCustomInvalidSessionStrategy())
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        sessionManagement {
            invalidSessionStrategy = MyCustomInvalidSessionStrategy()
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
...
<session-management invalid-session-strategy-ref="myCustomInvalidSessionStrategy" />
<bean name="myCustomInvalidSessionStrategy" class="com.example.MyCustomInvalidSessionStrategy" />
</http>
----
======

[[clearing-session-cookie-on-logout]]
== Xóa Session Cookie khi Logout

Bạn có thể xóa tường minh cookie JSESSIONID khi logout, chẳng hạn bằng cách dùng https://w3c.github.io/webappsec-clear-site-data/[header `Clear-Site-Data`] trong logout handler:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .logout((logout) -> logout
            .addLogoutHandler(new HeaderWriterLogoutHandler(new ClearSiteDataHeaderWriter(COOKIES)))
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        logout {
            addLogoutHandler(HeaderWriterLogoutHandler(ClearSiteDataHeaderWriter(COOKIES)))
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
<logout success-handler-ref="clearSiteDataHandler" />
<b:bean id="clearSiteDataHandler" class="org.springframework.security.web.authentication.logout.HeaderWriterLogoutHandler">
    <b:constructor-arg>
        <b:bean class="org.springframework.security.web.header.writers.ClearSiteDataHeaderWriter">
            <b:constructor-arg>
                <b:list>
                    <b:value>COOKIES</b:value>
                </b:list>
            </b:constructor-arg>
        </b:bean>
    </b:constructor-arg>
</b:bean>
</http>
----
======

Cách này có ưu điểm là không phụ thuộc vào container và sẽ hoạt động với mọi container hỗ trợ header `Clear-Site-Data`.

Ngoài ra, bạn cũng có thể dùng cú pháp sau trong logout handler:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .logout((logout) -> logout
            .deleteCookies("JSESSIONID")
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        logout {
            deleteCookies("JSESSIONID")
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
  <logout delete-cookies="JSESSIONID" />
</http>
----
======

Đáng tiếc là không thể bảo đảm cách này hoạt động với mọi servlet container, vì vậy bạn cần kiểm thử trong môi trường của mình.

[NOTE]
=====
Nếu chạy ứng dụng phía sau proxy, bạn cũng có thể xóa session cookie bằng cách cấu hình proxy server.
Ví dụ, khi dùng `mod_headers` của Apache HTTPD, directive sau xóa cookie `JSESSIONID` bằng cách làm nó hết hạn trong response của logout request (giả sử ứng dụng được deploy dưới path `/tutorial`):
=====

[source,xml]
----
<LocationMatch "/tutorial/logout">
Header always set Set-Cookie "JSESSIONID=;Path=/tutorial;Expires=Thu, 01 Jan 1970 00:00:00 GMT"
</LocationMatch>
----

Xem thêm chi tiết trong các section xref:servlet/exploits/headers.adoc#servlet-headers-clear-site-data[Clear Site Data] và xref:servlet/authentication/logout.adoc[Logout].



[[ns-session-fixation]]
== Tìm hiểu cơ chế bảo vệ trước Session Fixation Attack

https://en.wikipedia.org/wiki/Session_fixation[Session fixation attack] là một rủi ro tiềm ẩn, trong đó kẻ tấn công có thể tạo một session bằng cách truy cập site, sau đó thuyết phục người dùng khác login bằng cùng session đó (chẳng hạn gửi cho họ một link chứa session identifier dưới dạng parameter).
Spring Security tự động bảo vệ khỏi việc này bằng cách tạo session mới hoặc thay đổi session ID theo cách khác khi người dùng đăng nhập.

=== Cấu hình cơ chế bảo vệ Session Fixation

Bạn có thể kiểm soát strategy cho Session Fixation Protection bằng cách chọn một trong ba option được khuyến nghị:

* `changeSessionId` - Không tạo session mới.
Thay vào đó, dùng cơ chế bảo vệ session fixation do Servlet container cung cấp (`HttpServletRequest#changeSessionId()`).
Option này chỉ có trong Servlet 3.1 (Java EE 7) và các container mới hơn.
Chỉ định option này trong container cũ hơn sẽ gây ra exception.
Đây là mặc định trong Servlet 3.1 và các container mới hơn.

* `newSession` - Tạo một session "sạch" mới mà không copy session data hiện tại (các attribute liên quan đến Spring Security vẫn được copy).

* `migrateSession` - Tạo một session mới và copy mọi session attribute hiện có sang session mới.
Đây là mặc định trong Servlet 3.0 hoặc các container cũ hơn.

Bạn có thể cấu hình session fixation protection như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .sessionManagement((session) -> session
            .sessionFixation((sessionFixation) -> sessionFixation
                .newSession()
            )
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        sessionManagement {
            sessionFixation {
                newSession()
            }
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http>
  <session-management session-fixation-protection="newSession" />
</http>
----
======

Khi session fixation protection xảy ra, một `SessionFixationProtectionEvent` sẽ được publish trong `ApplicationContext`.
Nếu dùng `changeSessionId`, cơ chế bảo vệ này __cũng__ khiến mọi ``jakarta.servlet.http.HttpSessionIdListener`` được thông báo, vì vậy hãy cẩn thận nếu code của bạn lắng nghe cả hai event.

Bạn cũng có thể đặt session fixation protection thành `none` để tắt, nhưng không khuyến nghị vì điều đó khiến ứng dụng dễ bị tấn công.



[[use-securitycontextholderstrategy]]
== Sử dụng `SecurityContextHolderStrategy`

Xem block code sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(
        loginRequest.getUsername(), loginRequest.getPassword());
Authentication authentication = this.authenticationManager.authenticate(token);
// ...
SecurityContext context = SecurityContextHolder.createEmptyContext(); <1>
context.setAuthentication(authentication); <2>
SecurityContextHolder.setContext(context); <3>
----
======

1. Tạo một instance `SecurityContext` rỗng bằng cách truy cập tĩnh vào `SecurityContextHolder`.
2. Thiết lập object `Authentication` trong instance `SecurityContext`.
3. Thiết lập instance `SecurityContext` vào `SecurityContextHolder` theo cách tĩnh.

Dù code trên hoạt động tốt, nó có thể gây ra một số hiệu ứng không mong muốn: khi các component truy cập `SecurityContext` theo cách tĩnh thông qua `SecurityContextHolder`, điều này có thể tạo race condition khi có nhiều `ApplicationContext` muốn chỉ định `SecurityContextHolderStrategy`.
Điều này là vì trong `SecurityContextHolder` có một strategy cho mỗi classloader thay vì một strategy cho mỗi `ApplicationContext`.

Để giải quyết việc này, các component có thể wire `SecurityContextHolderStrategy` từ `ApplicationContext`.
Theo mặc định, chúng vẫn lookup strategy từ `SecurityContextHolder`.

Các thay đổi này phần lớn là internal, nhưng cho phép application autowire `SecurityContextHolderStrategy` thay vì truy cập tĩnh vào `SecurityContext`.
Để làm vậy, bạn nên đổi code thành:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class SomeClass {

    private final SecurityContextHolderStrategy securityContextHolderStrategy = SecurityContextHolder.getContextHolderStrategy();

    public void someMethod() {
        UsernamePasswordAuthenticationToken token = UsernamePasswordAuthenticationToken.unauthenticated(
                loginRequest.getUsername(), loginRequest.getPassword());
        Authentication authentication = this.authenticationManager.authenticate(token);
        // ...
        SecurityContext context = this.securityContextHolderStrategy.createEmptyContext(); <1>
        context.setAuthentication(authentication); <2>
        this.securityContextHolderStrategy.setContext(context); <3>
    }

}
----
======

1. Tạo một instance `SecurityContext` rỗng bằng `SecurityContextHolderStrategy` đã cấu hình.
2. Thiết lập object `Authentication` trong instance `SecurityContext`.
3. Thiết lập instance `SecurityContext` vào `SecurityContextHolderStrategy`.


[[session-mgmt-force-session-creation]]
== Buộc tạo Session eager

Đôi khi việc tạo session eager có thể hữu ích.
Bạn có thể thực hiện việc này bằng javadoc:org.springframework.security.web.session.ForceEagerSessionCreationFilter[], được cấu hình như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .sessionManagement((session) -> session
            .sessionCreationPolicy(SessionCreationPolicy.ALWAYS)
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        sessionManagement {
            sessionCreationPolicy = SessionCreationPolicy.ALWAYS
        }
    }
    return http.build()
}
----

XML::
+
[source,xml,role="secondary"]
----
<http create-session="ALWAYS">

</http>
----
======



== Đọc tiếp

- Session trong môi trường cluster với https://docs.spring.io/spring-session/reference/index.html[Spring Session]
