[[servlet-x509]]
= X.509 Authentication

[[x509-overview]]
Trường hợp sử dụng phổ biến nhất của authentication bằng certificate X.509 là xác minh danh tính của server khi sử dụng SSL, thường là khi sử dụng HTTPS từ browser.
Browser tự động kiểm tra rằng certificate do server cung cấp đã được cấp (ký số) bởi một trong danh sách các certificate authority đáng tin cậy mà nó duy trì.

Bạn cũng có thể sử dụng SSL với "`mutual authentication`". Khi đó, server yêu cầu client cung cấp một certificate hợp lệ trong quá trình SSL handshake.
Server thực hiện authentication cho client bằng cách kiểm tra rằng certificate của client được ký bởi một certificate authority được chấp nhận.
Nếu đã cung cấp certificate hợp lệ, application có thể lấy certificate đó thông qua Servlet API.
Ví dụ, nếu sử dụng Tomcat, bạn nên đọc https://tomcat.apache.org/tomcat-10.1-doc/ssl-howto.html[hướng dẫn SSL của Tomcat].
Bạn nên hoàn tất việc này trước khi thử sử dụng với Spring Security.

Module X.509 của Spring Security trích xuất certificate bằng một filter.
Module này map certificate với một user của application và load tập các authority được cấp cho user đó để sử dụng với hạ tầng Spring Security tiêu chuẩn, cụ thể bao gồm ít nhất authority `FACTOR_X509` khi <<servlet-x509-config, sử dụng DSL `HttpSecurity`>>.

[[servlet-x509-config]]
== Thêm X.509 Authentication vào web application của bạn

Tương tự xref:reactive/authentication/x509.adoc[Reactive X.509 authentication], Servlet X.509 authentication filter cho phép trích xuất authentication token từ certificate do client cung cấp.

Ví dụ sau minh họa một Reactive X.509 security configuration:

include-code::./DefaultX509Configuration[tag=springSecurity,indent=0]

Trong cấu hình trên, khi không cung cấp cả `principalExtractor` lẫn `authenticationManager`, các giá trị mặc định sẽ được sử dụng.
Principal extractor mặc định là `SubjectX500PrincipalExtractor`, trích xuất trường CN (tên chung) từ certificate do client cung cấp.
Authentication manager mặc định là `ReactivePreAuthenticatedAuthenticationManager`, thực hiện user account validation, kiểm tra rằng user account có name được trích xuất bởi `principalExtractor` tồn tại và không bị locked, disabled hoặc expired.

Ví dụ sau minh họa cách override các giá trị mặc định này:

include-code::./CustomX509Configuration[tag=springSecurity,indent=0]

Trong ví dụ trước, username được trích xuất từ trường `emailAddress` của certificate client thay vì CN, và account lookup sử dụng một custom instance `ReactiveAuthenticationManager`.

Để xem ví dụ cấu hình Netty và `WebClient` hoặc command-line tool `curl` để sử dụng mutual TLS và bật X.509 authentication, hãy xem https://github.com/spring-projects/spring-security-samples/tree/main/servlet/java-configuration/authentication/x509.


[[x509-ssl-config]]
== Thiết lập SSL trong Tomcat
Có một số certificate được tạo sẵn trong {gh-samples-url}/servlet/java-configuration/authentication/x509/server[Spring Security Samples repository].
Bạn có thể sử dụng các certificate này để bật SSL cho testing nếu không muốn tự tạo certificate.
File `server.jks` chứa certificate của server, private key và certificate của certificate authority phát hành.
Ngoài ra còn có một số file client certificate cho user từ các sample application.
Bạn có thể cài đặt các file này vào browser để bật SSL client authentication.

Để chạy Tomcat với hỗ trợ SSL, đặt file `server.jks` vào thư mục `conf` của Tomcat và thêm connector sau vào file `server.xml`:

[source,xml]
----
<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" scheme="https" secure="true"
			clientAuth="true" sslProtocol="TLS"
			keystoreFile="${catalina.home}/conf/server.jks"
			keystoreType="JKS" keystorePass="password"
			truststoreFile="${catalina.home}/conf/server.jks"
			truststoreType="JKS" truststorePass="password"
/>
----

`clientAuth` cũng có thể được đặt thành `want` nếu bạn vẫn muốn các SSL connection thành công ngay cả khi client không cung cấp certificate.
Các client không cung cấp certificate không thể truy cập bất kỳ object nào được Spring Security bảo vệ, trừ khi bạn sử dụng cơ chế authentication không phải X.509, chẳng hạn form authentication.
