[[servlet-x509]]
= Authentication X.509

[[x509-overview]]
Trường hợp sử dụng phổ biến nhất của authentication bằng chứng chỉ X.509 là xác minh danh tính của máy chủ khi sử dụng SSL, thường là khi sử dụng HTTPS từ trình duyệt.
Trình duyệt tự động kiểm tra rằng chứng chỉ do máy chủ cung cấp đã được cấp (ký số) bởi một trong các authority cấp chứng chỉ đáng tin cậy thuộc danh sách mà nó duy trì.

Bạn cũng có thể sử dụng SSL với "`mutual authentication`". Khi đó, máy chủ yêu cầu client cung cấp một chứng chỉ hợp lệ trong quá trình SSL handshake.
Máy chủ thực hiện authentication cho client bằng cách kiểm tra rằng chứng chỉ của client được ký bởi một authority được chấp nhận.
Nếu đã cung cấp chứng chỉ hợp lệ, ứng dụng có thể lấy chứng chỉ đó thông qua servlet API.
Ví dụ, nếu sử dụng Tomcat, bạn nên đọc https://tomcat.apache.org/tomcat-10.1-doc/ssl-howto.html[hướng dẫn SSL của Tomcat].
Bạn nên hoàn tất việc này trước khi thử sử dụng với Spring Security.

Mô-đun X.509 của Spring Security trích xuất chứng chỉ bằng một filter.
Mô-đun này ánh xạ chứng chỉ với một người dùng của ứng dụng và tải tập các authority được cấp cho người dùng đó để sử dụng với hạ tầng Spring Security tiêu chuẩn, cụ thể bao gồm ít nhất authority `FACTOR_X509` khi <<servlet-x509-config, sử dụng DSL `HttpSecurity`>>.

[[servlet-x509-config]]
== Thêm Authentication X.509 vào ứng dụng Web của bạn

Tương tự xref:reactive/authentication/x509.adoc[authentication X.509 trong Reactive], filter authentication x509 của Servlet cho phép trích xuất authentication token từ chứng chỉ do client cung cấp.

Ví dụ sau minh họa một cấu hình bảo mật x509 Reactive:

include-code::./DefaultX509Configuration[tag=springSecurity,indent=0]

Trong cấu hình trên, khi không cung cấp cả `principalExtractor` lẫn `authenticationManager`, các giá trị mặc định sẽ được sử dụng.
principal extractor mặc định là `SubjectX500PrincipalExtractor`, trích xuất trường CN (tên chung) từ chứng chỉ do client cung cấp.
authentication manager mặc định là `ReactivePreAuthenticatedAuthenticationManager`, thực hiện validation tài khoản người dùng, kiểm tra rằng một tài khoản người dùng có tên được trích xuất bởi `principalExtractor` tồn tại và không bị khóa, vô hiệu hóa hoặc hết hạn.

Ví dụ sau minh họa cách ghi đè các giá trị mặc định này:

include-code::./CustomX509Configuration[tag=springSecurity,indent=0]

Trong ví dụ trước, tên người dùng được trích xuất từ trường `emailAddress` của chứng chỉ client thay vì CN, và việc tra cứu tài khoản sử dụng một instance `ReactiveAuthenticationManager` tùy chỉnh.

Để xem ví dụ cấu hình Netty và `WebClient` hoặc tool dòng lệnh `curl` để sử dụng mutual TLS và bật authentication X.509, hãy xem https://github.com/spring-projects/spring-security-samples/tree/main/servlet/java-configuration/authentication/x509.


[[x509-ssl-config]]
== Thiết lập SSL trong Tomcat
Có một số chứng chỉ được tạo sẵn trong {gh-samples-url}/servlet/java-configuration/authentication/x509/server[kho lưu trữ Spring Security Samples].
Bạn có thể sử dụng các chứng chỉ này để bật SSL cho việc kiểm thử nếu không muốn tự tạo chứng chỉ.
File `server.jks` chứa chứng chỉ của máy chủ, khóa riêng và chứng chỉ của authority cấp phát.
Ngoài ra còn có một số file chứng chỉ client cho người dùng từ các ứng dụng mẫu.
Bạn có thể cài đặt các file này vào trình duyệt để bật authentication SSL cho client.

Để chạy Tomcat với hỗ trợ SSL, đặt file `server.jks` vào thư mục `conf` của Tomcat và thêm connector sau vào file `server.xml`:

[source,xml]
----
<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" scheme="https" secure="true"
			clientAuth="true" sslProtocol="TLS"
			keystoreFile="${catalina.home}/conf/server.jks"
			keystoreType="JKS" keystorePass="password"
			truststoreFile="${catalina.home}/conf/server.jks"
			truststoreType="JKS" truststorePass="password"
/>
----

`clientAuth` cũng có thể được đặt thành `want` nếu bạn vẫn muốn các kết nối SSL thành công ngay cả khi client không cung cấp chứng chỉ.
Các client không cung cấp chứng chỉ không thể truy cập bất kỳ đối tượng nào được Spring Security bảo vệ, trừ khi bạn sử dụng cơ chế authentication không phải X.509, chẳng hạn authentication bằng biểu mẫu.
