[[servlet-saml2login-authenticate-responses]]
= Xác thực các ``<saml2:Response>``

Để xác minh các Response SAML 2.0, Spring Security sử dụng xref:servlet/saml2/login/overview.adoc#servlet-saml2login-authentication-saml2authenticationtokenconverter[`Saml2AuthenticationTokenConverter`] để tạo request `Authentication` và xref:servlet/saml2/login/overview.adoc#servlet-saml2login-architecture[`OpenSaml5AuthenticationProvider`] để xác thực request đó.

Bạn có thể cấu hình việc này theo một số cách, bao gồm:

1. Thay đổi cách tra cứu `RelyingPartyRegistration`
2. Thiết lập clock skew để validate timestamp
3. Ánh xạ response thành một danh sách các instance `GrantedAuthority`
4. Tùy chỉnh chiến lược xác thực assertion
5. Tùy chỉnh chiến lược giải mã các phần tử response và assertion

Để cấu hình các nội dung này, bạn sẽ sử dụng method `saml2Login#authenticationManager` trong DSL.

[[saml2-response-processing-endpoint]]
== Thay đổi Endpoint xử lý SAML Response

Endpoint mặc định là `+/login/saml2/sso/{registrationId}+`.
Bạn có thể thay đổi endpoint này trong DSL và metadata liên quan như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityFilterChain securityFilters(HttpSecurity http) throws Exception {
	http
        // ...
        .saml2Login((saml2) -> saml2.loginProcessingUrl("/saml2/login/sso"))
        // ...

    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun securityFilters(val http: HttpSecurity): SecurityFilterChain {
	http {
        // ...
        .saml2Login {
            loginProcessingUrl = "/saml2/login/sso"
        }
        // ...
    }

    return http.build()
}
----
======

và:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
relyingPartyRegistrationBuilder.assertionConsumerServiceLocation("/saml/SSO")
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
relyingPartyRegistrationBuilder.assertionConsumerServiceLocation("/saml/SSO")
----
======

[[relyingpartyregistrationresolver-apply]]
== Thay đổi cách tra cứu `RelyingPartyRegistration`

Theo mặc định, converter này sẽ match với bất kỳ `<saml2:AuthnRequest>` liên quan nào hoặc bất kỳ `registrationId` nào mà nó tìm thấy trong URL.
Hoặc nếu không tìm thấy trong cả hai trường hợp đó, nó sẽ thử tra cứu bằng phần tử `<saml2:Response#Issuer>`.

Có một số trường hợp bạn có thể cần cách xử lý tinh vi hơn, chẳng hạn khi hỗ trợ binding `ARTIFACT`.
Trong những trường hợp đó, bạn có thể tùy chỉnh việc tra cứu thông qua một `AuthenticationConverter` tùy chỉnh như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityFilterChain securityFilters(HttpSecurity http, AuthenticationConverter authenticationConverter) throws Exception {
	http
        // ...
        .saml2Login((saml2) -> saml2.authenticationConverter(authenticationConverter))
        // ...

    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun securityFilters(val http: HttpSecurity, val converter: AuthenticationConverter): SecurityFilterChain {
	http {
        // ...
        .saml2Login {
            authenticationConverter = converter
        }
        // ...
    }

    return http.build()
}
----
======

[[servlet-saml2login-opensamlauthenticationprovider-clockskew]]
== Thiết lập clock skew

Không hiếm trường hợp asserting party và Relying Party có đồng hồ hệ thống không được đồng bộ hoàn toàn.
Vì lý do đó, bạn có thể cấu hình `OpenSaml5AuthenticationProvider.AssertionValidator` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        OpenSaml5AuthenticationProvider authenticationProvider = new OpenSaml5AuthenticationProvider();
        AssertionValidator assertionValidator = AssertionValidator.builder()
                .clockSkew(Duration.ofMinutes(10)).build();
		authenticationProvider.setAssertionValidator(assertionValidator);
        http
            .authorizeHttpRequests((authorize) -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login((saml2) -> saml2
                .authenticationManager(new ProviderManager(authenticationProvider))
            );
        return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----


@Configuration @EnableWebSecurity
class SecurityConfig {
    @Bean
    @Throws(Exception::class)
    fun filterChain(http: HttpSecurity): SecurityFilterChain {
        val authenticationProvider = OpenSaml5AuthenticationProvider()
        val assertionValidator = AssertionValidator.builder().clockSkew(Duration.ofMinutes(10)).build()
        authenticationProvider.setAssertionValidator(assertionValidator)
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            saml2Login {
                authenticationManager = ProviderManager(authenticationProvider)
            }
        }
        return http.build()
    }
}
----
======

== Chuyển đổi một `Assertion` thành một `Authentication`

`OpenSamlXAuthenticationProvider#setResponseAuthenticationConverter` cho phép bạn thay đổi cách chuyển đổi assertion thành một instance `Authentication`.

Bạn có thể thiết lập một converter tùy chỉnh như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {
    @Autowired
    Converter<ResponseToken, Saml2Authentication> authenticationConverter;

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        OpenSaml5AuthenticationProvider authenticationProvider = new OpenSaml5AuthenticationProvider();
        authenticationProvider.setResponseAuthenticationConverter(this.authenticationConverter);

        http
            .authorizeHttpRequests((authorize) -> authorize
                .anyRequest().authenticated())
            .saml2Login((saml2) -> saml2
                .authenticationManager(new ProviderManager(authenticationProvider))
            );
        return http.build();
    }

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
open class SecurityConfig {
    @Autowired
    var authenticationConverter: Converter<ResponseToken, Saml2Authentication>? = null

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        val authenticationProvider = OpenSaml5AuthenticationProvider()
        authenticationProvider.setResponseAuthenticationConverter(this.authenticationConverter)
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            saml2Login {
                authenticationManager = ProviderManager(authenticationProvider)
            }
        }
        return http.build()
    }
}
----
======

Các ví dụ tiếp theo đều dựa trên cấu trúc chung này để minh họa những trường hợp khác nhau mà converter này hữu ích.

[[servlet-saml2login-opensamlauthenticationprovider-userdetailsservice]]
== Kết hợp với một `UserDetailsService`

Hoặc có thể bạn muốn đưa user details từ một `UserDetailsService` legacy vào.
Trong trường hợp đó, response authentication converter có thể hữu ích như minh họa dưới đây:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
class MyUserDetailsResponseAuthenticationConverter implements Converter<ResponseToken, Saml2Authentication> {
	private final ResponseAuthenticationConverter delegate = new ResponseAuthenticationConverter();
	private final UserDetailsService userDetailsService;

	MyUserDetailsResponseAuthenticationConverter(UserDetailsService userDetailsService) {
		this.userDetailsService = userDetailsService;
	}

	@Override
    public Saml2Authentication convert(ResponseToken responseToken) {
	    Saml2Authentication authentication = this.delegate.convert(responseToken); <1>
        String username = authentication.getName();
		UserDetails user  = this.userDetailsService.loadUserByUsername(username); <2>
		String saml2Response = authentication.getSaml2Response();
		Saml2ResponseAssertionAccessor assertion = new OpenSamlResponseAssertionAccessor(
				saml2Response, CollectionUtils.getFirst(responseToken.getResponse().getAssertions()));
		Collection<GrantedAuthority> authorities = user.getAuthorities();
		return new Saml2AssertionAuthentication(user, assertion, authorities); <3>
    }

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
open class MyUserDetailsResponseAuthenticationConverter(private val userDetailsService: UserDetailsService) : Converter<ResponseToken, Saml2Authentication> {

    private val delegate = ResponseAuthenticationConverter()

    override fun convert(responseToken: ResponseToken): Saml2Authentication {
	    val authentication = this.delegate.convert(responseToken) <1>
        val username = authentication.name
		val userDetails = this.userDetailsService.loadUserByUsername(username) <2>
		val saml2Response = authentication.saml2Response
		val assertion = OpenSamlResponseAssertionAccessor(
				saml2Response, responseToken.response.assertions.firstOrNull())
		val authorities = principal.getAuthorities()
		return Saml2AssertionAuthentication(userDetails, assertion, userDetails.authorities) <3>
    }

}
----
======
<1> Thứ nhất, gọi converter mặc định, converter này trích xuất attributes và authorities từ response
<2> Thứ hai, gọi xref:servlet/authentication/passwords/user-details-service.adoc#servlet-authentication-userdetailsservice[`UserDetailsService`] bằng thông tin liên quan
<3> Thứ ba, trả về một authentication có chứa user details

[TIP]
====
Nếu `UserDetailsService` của bạn trả về một giá trị cũng implement `AuthenticatedPrincipal`, bạn không cần một authentication implementation tùy chỉnh.
====

[NOTE]
Không bắt buộc phải gọi authentication converter mặc định của ``OpenSaml5AuthenticationProvider``.
Converter này trả về một `Saml2AuthenticatedPrincipal` chứa các attributes đã trích xuất từ các ``AttributeStatement`` cùng với authority `ROLE_USER` duy nhất.

=== Cấu hình Principal Name

Đôi khi principal name không nằm trong phần tử `<saml2:NameID>`.
Trong trường hợp đó, bạn có thể cấu hình `ResponseAuthenticationConverter` bằng một strategy tùy chỉnh như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ResponseAuthenticationConverter authenticationConverter() {
	ResponseAuthenticationConverter authenticationConverter = new ResponseAuthenticationConverter();
	authenticationConverter.setPrincipalNameConverter((assertion) -> {
		// ... work with OpenSAML's Assertion object to extract the principal
	});
	return authenticationConverter;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationConverter(): ResponseAuthenticationConverter {
    val authenticationConverter: ResponseAuthenticationConverter = ResponseAuthenticationConverter()
    authenticationConverter.setPrincipalNameConverter { assertion ->
		// ... work with OpenSAML's Assertion object to extract the principal
    }
    return authenticationConverter
}
----
======

=== Cấu hình Granted Authorities của Principal

Spring Security tự động cấp `ROLE_USER` khi sử dụng `OpenSamlXAuhenticationProvider`.
Với `OpenSaml5AuthenticationProvider`, bạn có thể cấu hình một tập hợp granted authorities khác như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
ResponseAuthenticationConverter authenticationConverter() {
	ResponseAuthenticationConverter authenticationConverter = new ResponseAuthenticationConverter();
	authenticationConverter.setPrincipalNameConverter((assertion) -> {
		// ... grant the needed authorities based on attributes in the assertion
	});
	return authenticationConverter;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationConverter(): ResponseAuthenticationConverter {
    val authenticationConverter = ResponseAuthenticationConverter()
    authenticationConverter.setPrincipalNameConverter{ assertion ->
		// ... grant the needed authorities based on attributes in the assertion
    }
    return authenticationConverter
}
----
======

[[servlet-saml2login-opensamlauthenticationprovider-additionalvalidation]]
== Thực hiện xác thực Response bổ sung

`OpenSaml5AuthenticationProvider` xác thực các giá trị `Issuer` và `Destination` ngay sau khi giải mã `Response`.
Bạn có thể tùy chỉnh việc xác thực bằng cách mở rộng validator mặc định và nối thêm response validator của mình, hoặc thay thế hoàn toàn bằng validator riêng.

Ví dụ, bạn có thể ném một exception tùy chỉnh cùng mọi thông tin bổ sung có trong object `Response` như sau:
[source,java]
----
OpenSaml5AuthenticationProvider provider = new OpenSaml5AuthenticationProvider();
ResponseValidator responseValidator = ResponseValidator.withDefaults(myCustomValidator);
provider.setResponseValidator(responseValidator);
----

Bạn cũng có thể tùy chỉnh các bước xác thực mà Spring Security sẽ thực hiện.
Ví dụ, nếu muốn bỏ qua việc xác thực `Response#InResponseTo`, bạn có thể gọi constructor của ``ResponseValidator``, loại `InResponseToValidator` khỏi danh sách:

[source,java]
----
OpenSaml5AuthenticationProvider provider = new OpenSaml5AuthenticationProvider();
ResponseValidator responseValidator = new ResponseValidator(new DestinationValidator(), new IssuerValidator());
provider.setResponseValidator(responseValidator);
----

[TIP]
====
OpenSAML thực hiện xác thực `Asssertion#InResponseTo` trong class `BearerSubjectConfirmationValidator`, có thể cấu hình bằng <<_performing_additional_assertion_validation, setAssertionValidator>>.
====

== Thực hiện xác thực Assertion bổ sung
`OpenSaml5AuthenticationProvider` thực hiện việc xác thực tối thiểu đối với các Assertion SAML 2.0.
Sau khi xác minh signature, nó sẽ:

1. Xác thực các condition `<AudienceRestriction>` và `<DelegationRestriction>`
2. Xác thực các ``<SubjectConfirmation>``, ngoại trừ mọi thông tin địa chỉ IP

Để thực hiện xác thực bổ sung, bạn có thể cấu hình assertion validator riêng, ủy quyền cho validator mặc định của ``OpenSaml5AuthenticationProvider`` rồi thực hiện phần xác thực của mình.

[[servlet-saml2login-opensamlauthenticationprovider-onetimeuse]]
Ví dụ, bạn có thể sử dụng `OneTimeUseConditionValidator` của OpenSAML để xác thực thêm condition `<OneTimeUse>` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
OpenSaml5AuthenticationProvider provider = new OpenSaml5AuthenticationProvider();
OneTimeUseConditionValidator validator = ...;
AssertionValidator assertionValidator = AssertionValidator.builder()
        .conditionValidators((c) -> c.add(validator)).build();
provider.setAssertionValidator(assertionValidator);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val provider = OpenSaml5AuthenticationProvider()
val validator: OneTimeUseConditionValidator = ...;
val assertionValidator = AssertionValidator.builder()
        .conditionValidators { add(validator) }.build()
provider.setAssertionValidator(assertionValidator)
----
======

Bạn có thể sử dụng cùng builder này để loại bỏ các validator không muốn dùng như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
OpenSaml5AuthenticationProvider provider = new OpenSaml5AuthenticationProvider();
AssertionValidator assertionValidator = AssertionValidator.builder()
        .conditionValidators((c) -> c.removeIf(AudienceRestrictionValidator.class::isInstance)).build();
provider.setAssertionValidator(assertionValidator);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val provider = new OpenSaml5AuthenticationProvider()
val assertionValidator = AssertionValidator.builder()
        .conditionValidators {
			c: List<ConditionValidator> -> c.removeIf { it is AudienceRestrictionValidator }
        }.build()
provider.setAssertionValidator(assertionValidator)
----
======

[[servlet-saml2login-opensamlauthenticationprovider-decryption]]
== Tùy chỉnh việc giải mã

Spring Security tự động giải mã các phần tử `<saml2:EncryptedAssertion>`, `<saml2:EncryptedAttribute>` và `<saml2:EncryptedID>` bằng xref:servlet/saml2/login/overview.adoc#servlet-saml2login-rpr-credentials[các instance `Saml2X509Credential`] dùng cho việc giải mã, đã đăng ký trong xref:servlet/saml2/login/overview.adoc#servlet-saml2login-relyingpartyregistration[`RelyingPartyRegistration`].

`OpenSaml5AuthenticationProvider` cung cấp xref:servlet/saml2/login/overview.adoc#servlet-saml2login-architecture[hai chiến lược giải mã].
Response decrypter dùng để giải mã các phần tử được mã hóa của `<saml2:Response>`, chẳng hạn `<saml2:EncryptedAssertion>`.
Assertion decrypter dùng để giải mã các phần tử được mã hóa của `<saml2:Assertion>`, chẳng hạn `<saml2:EncryptedAttribute>` và `<saml2:EncryptedID>`.

Bạn có thể thay thế chiến lược giải mã mặc định của ``OpenSaml5AuthenticationProvider`` bằng chiến lược của mình.
Ví dụ, nếu có một service riêng giải mã các assertion trong một `<saml2:Response>`, bạn có thể sử dụng service đó thay thế như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
MyDecryptionService decryptionService = ...;
OpenSaml5AuthenticationProvider provider = new OpenSaml5AuthenticationProvider();
provider.setResponseElementsDecrypter((responseToken) -> decryptionService.decrypt(responseToken.getResponse()));
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val decryptionService: MyDecryptionService = ...
val provider = OpenSaml5AuthenticationProvider()
provider.setResponseElementsDecrypter { responseToken -> decryptionService.decrypt(responseToken.response) }
----
======

Nếu cũng đang giải mã các phần tử riêng lẻ trong một `<saml2:Assertion>`, bạn cũng có thể tùy chỉnh assertion decrypter:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
provider.setAssertionElementsDecrypter((assertionToken) -> decryptionService.decrypt(assertionToken.getAssertion()));
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
provider.setAssertionElementsDecrypter { assertionToken -> decryptionService.decrypt(assertionToken.assertion) }
----
======

NOTE: Có hai decrypter riêng biệt vì assertion có thể được ký riêng với response.
Cố gắng giải mã các phần tử của assertion đã ký trước khi xác minh signature có thể làm signature mất hiệu lực.
Nếu asserting party của bạn chỉ ký response, thì có thể giải mã an toàn mọi phần tử chỉ bằng response decrypter.

[[servlet-saml2login-authenticationmanager-custom]]
== Sử dụng Authentication Manager tùy chỉnh

[[servlet-saml2login-opensamlauthenticationprovider-authenticationmanager]]
Tất nhiên, method DSL `authenticationManager` cũng có thể được sử dụng để thực hiện authentication SAML 2.0 hoàn toàn tùy chỉnh.
Authentication manager này cần nhận một object `Saml2AuthenticationToken` chứa dữ liệu XML Response SAML 2.0.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        AuthenticationManager authenticationManager = new MySaml2AuthenticationManager(...);
        http
            .authorizeHttpRequests((authorize) -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login((saml2) -> saml2
                .authenticationManager(authenticationManager)
            )
        ;
        return http.build();
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
open class SecurityConfig {
    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        val customAuthenticationManager: AuthenticationManager = MySaml2AuthenticationManager(...)
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            saml2Login {
                authenticationManager = customAuthenticationManager
            }
        }
        return http.build()
    }
}
----
======

[[servlet-saml2login-authenticatedprincipal]]
== Sử dụng `Saml2AuthenticatedPrincipal`

Khi Relying Party được cấu hình chính xác cho một asserting party cụ thể, nó đã sẵn sàng chấp nhận các assertion.
Sau khi Relying Party validate một assertion, kết quả là một `Saml2Authentication` với một `Saml2AuthenticatedPrincipal`.

Điều này có nghĩa là bạn có thể truy cập principal trong controller như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class MainController {
	@GetMapping("/")
	public String index(@AuthenticationPrincipal Saml2AuthenticatedPrincipal principal, Model model) {
		String email = principal.getFirstAttribute("email");
		model.setAttribute("email", email);
		return "index";
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class MainController {
    @GetMapping("/")
    fun index(@AuthenticationPrincipal principal: Saml2AuthenticatedPrincipal, model: Model): String {
        val email = principal.getFirstAttribute<String>("email")
        model.setAttribute("email", email)
        return "index"
    }
}
----
======

[TIP]
Vì đặc tả SAML 2.0 cho phép mỗi attribute có nhiều giá trị, bạn có thể gọi `getAttribute` để lấy danh sách attributes hoặc `getFirstAttribute` để lấy giá trị đầu tiên trong danh sách.
`getFirstAttribute` khá tiện dụng khi bạn biết chỉ có một giá trị.
