[[servlet-saml2login-sp-initiated-factory]]
= Tạo các ``<saml2:AuthnRequest>``

Như đã nêu trước đó, tính năng hỗ trợ SAML 2.0 của Spring Security tạo một `<saml2:AuthnRequest>` để bắt đầu authentication với asserting party.

Spring Security thực hiện điều này một phần bằng cách đăng ký `Saml2WebSsoAuthenticationRequestFilter` trong filter chain.
Theo mặc định, filter này phản hồi các endpoint `+/saml2/authenticate/{registrationId}+` và `+/saml2/authenticate?registrationId={registrationId}+`.

Ví dụ, nếu ứng dụng được deploy tại `https://rp.example.com` và bạn đặt registration ID là `okta`, bạn có thể truy cập:

`https://rp.example.org/saml2/authenticate/okta`

và kết quả sẽ là một redirect chứa parameter `SAMLRequest` bao gồm `<saml2:AuthnRequest>` đã được ký, nén bằng deflate và encode.

[[configuring-authentication-request-uri]]
== Cấu hình endpoint cho `<saml2:AuthnRequest>`

Để cấu hình một endpoint khác endpoint mặc định, bạn có thể đặt giá trị trong `saml2Login`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityFilterChain filterChain(HttpSecurity http) {
	http
        .saml2Login((saml2) -> saml2
            .authenticationRequestUriQuery("/custom/auth/sso?peerEntityID={registrationId}")
        );
	return new CustomSaml2AuthenticationRequestRepository();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        saml2Login {
            authenticationRequestUriQuery = "/custom/auth/sso?peerEntityID={registrationId}"
        }
    }
    return CustomSaml2AuthenticationRequestRepository()
}
----
======

[[servlet-saml2login-store-authn-request]]
== Thay đổi cách lưu trữ `<saml2:AuthnRequest>`

`Saml2WebSsoAuthenticationRequestFilter` sử dụng một `Saml2AuthenticationRequestRepository` để persist một instance `AbstractSaml2AuthenticationRequest` trước khi xref:servlet/saml2/login/authentication-requests.adoc#servlet-saml2login-sp-initiated-factory[gửi `<saml2:AuthnRequest>`] đến asserting party.

Ngoài ra, `Saml2WebSsoAuthenticationFilter` và `Saml2AuthenticationTokenConverter` sử dụng một `Saml2AuthenticationRequestRepository` để load mọi `AbstractSaml2AuthenticationRequest` trong quá trình xref:servlet/saml2/login/authentication.adoc#servlet-saml2login-authenticate-responses[authenticate `<saml2:Response>`].

Theo mặc định, Spring Security sử dụng `HttpSessionSaml2AuthenticationRequestRepository`, nơi lưu `AbstractSaml2AuthenticationRequest` trong `HttpSession`.

Nếu có một implementation tùy chỉnh của `Saml2AuthenticationRequestRepository`, bạn có thể cấu hình nó bằng cách expose nó dưới dạng `@Bean` như trong ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
Saml2AuthenticationRequestRepository<AbstractSaml2AuthenticationRequest> authenticationRequestRepository() {
	return new CustomSaml2AuthenticationRequestRepository();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun authenticationRequestRepository(): Saml2AuthenticationRequestRepository<AbstractSaml2AuthenticationRequest> {
    return CustomSaml2AuthenticationRequestRepository()
}
----
======

=== Cache `<saml2:AuthnRequest>` theo Relay State

Nếu không muốn sử dụng session để lưu `<saml2:AuthnRequest>`, bạn cũng có thể lưu nó trong distributed cache.
Điều này có thể hữu ích nếu bạn đang cố sử dụng `SameSite=Strict` và khiến authentication request bị mất trong redirect từ Identity Provider.

[NOTE]
=====
Điều quan trọng cần nhớ là việc lưu nó trong session mang lại các lợi ích về security.
Một trong những lợi ích đó là defense tự nhiên chống login fixation mà việc lưu trong session cung cấp.
Ví dụ, nếu một application lookup authentication request từ session, thì ngay cả khi attacker cung cấp SAML response của họ cho victim, login vẫn sẽ fail.

Mặt khác, nếu trust InResponseTo hoặc RelayState để retrieve authentication request, thì không có cách nào biết liệu handshake đó có request SAML response hay không.
=====

Để hỗ trợ việc này, Spring Security có `CacheSaml2AuthenticationRequestRepository`, bạn có thể publish nó dưới dạng bean để filter chain tự động pick up:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
Saml2AuthenticationRequestRepository<?> authenticationRequestRepository() {
	return new CacheSaml2AuthenticationRequestRepository();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationRequestRepository(): Saml2AuthenticationRequestRepository<*> {
    return CacheSaml2AuthenticationRequestRepository()
}
----
======


[[servlet-saml2login-sp-initiated-factory-signing]]
== Thay đổi cách gửi `<saml2:AuthnRequest>`

Theo mặc định, Spring Security ký từng `<saml2:AuthnRequest>` và gửi nó bằng GET tới asserting party.

Nhiều asserting party không yêu cầu `<saml2:AuthnRequest>` phải được ký.
Bạn có thể tự động cấu hình điều này thông qua `RelyingPartyRegistrations`, hoặc cấu hình thủ công như sau:


.Không yêu cầu ký AuthnRequests
[tabs]
======
Boot::
+
[source,yaml,role="primary"]
----
spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              entity-id: ...
              singlesignon.sign-request: false
----

Java::
+
[source,java,role="secondary"]
----
RelyingPartyRegistration relyingPartyRegistration = RelyingPartyRegistration.withRegistrationId("okta")
        // ...
        .assertingPartyMetadata((party) -> party
            // ...
            .wantAuthnRequestsSigned(false)
        )
        .build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
var relyingPartyRegistration: RelyingPartyRegistration =
    RelyingPartyRegistration.withRegistrationId("okta")
        // ...
        .assertingPartyMetadata { party: AssertingPartyMetadata.Builder -> party
                // ...
                .wantAuthnRequestsSigned(false)
        }
        .build()
----
======

Nếu không, bạn cần chỉ định một private key cho `RelyingPartyRegistration#signingX509Credentials` để Spring Security có thể ký `<saml2:AuthnRequest>` trước khi gửi.

[[servlet-saml2login-sp-initiated-factory-algorithm]]
Theo mặc định, Spring Security sẽ ký `<saml2:AuthnRequest>` bằng `rsa-sha256`, mặc dù một số asserting party sẽ yêu cầu một algorithm khác, như được chỉ ra trong metadata của họ.

Bạn có thể cấu hình algorithm dựa trên xref:servlet/saml2/login/overview.adoc#servlet-saml2login-relyingpartyregistrationrepository[metadata của asserting party bằng `RelyingPartyRegistrations`].

Hoặc bạn có thể cung cấp thủ công:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
String metadataLocation = "classpath:asserting-party-metadata.xml";
RelyingPartyRegistration relyingPartyRegistration = RelyingPartyRegistrations.fromMetadataLocation(metadataLocation)
        // ...
        .assertingPartyMetadata((party) -> party
            // ...
            .signingAlgorithms((sign) -> sign.add(SignatureConstants.ALGO_ID_SIGNATURE_RSA_SHA512))
        )
        .build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
var metadataLocation = "classpath:asserting-party-metadata.xml"
var relyingPartyRegistration: RelyingPartyRegistration =
    RelyingPartyRegistrations.fromMetadataLocation(metadataLocation)
        // ...
        .assertingPartyMetadata { party: AssertingPartyMetadata.Builder -> party
                // ...
                .signingAlgorithms { sign: MutableList<String?> ->
                    sign.add(
                        SignatureConstants.ALGO_ID_SIGNATURE_RSA_SHA512
                    )
                }
        }
        .build()
----
======

NOTE: Đoạn snippet trên sử dụng class `SignatureConstants` của OpenSAML để cung cấp tên algorithm.
Tuy nhiên, việc này chỉ nhằm thuận tiện.
Vì datatype là `String`, bạn có thể cung cấp trực tiếp tên algorithm.

[[servlet-saml2login-sp-initiated-factory-binding]]
Một số asserting party yêu cầu `<saml2:AuthnRequest>` phải được POST.
Bạn có thể tự động cấu hình điều này thông qua `RelyingPartyRegistrations`, hoặc cấu hình thủ công như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
RelyingPartyRegistration relyingPartyRegistration = RelyingPartyRegistration.withRegistrationId("okta")
        // ...
        .assertingPartyMetadata((party) -> party
            // ...
            .singleSignOnServiceBinding(Saml2MessageBinding.POST)
        )
        .build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
var relyingPartyRegistration: RelyingPartyRegistration? =
    RelyingPartyRegistration.withRegistrationId("okta")
        // ...
        .assertingPartyMetadata { party: AssertingPartyMetadata.Builder -> party
            // ...
            .singleSignOnServiceBinding(Saml2MessageBinding.POST)
        }
        .build()
----
======

[[servlet-saml2login-sp-initiated-factory-custom-authnrequest]]
== Tùy chỉnh instance `AuthnRequest` của OpenSAML

Có một số lý do bạn có thể muốn điều chỉnh một `AuthnRequest`.
Ví dụ, bạn có thể muốn set `ForceAuthN` thành `true`, trong khi theo mặc định Spring Security set nó thành `false`.

Bạn có thể custom các element của `AuthnRequest` của OpenSAML bằng cách publish một `OpenSaml5AuthenticationRequestResolver` dưới dạng `@Bean`, như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
Saml2AuthenticationRequestResolver authenticationRequestResolver(RelyingPartyRegistrationRepository registrations) {
    RelyingPartyRegistrationResolver registrationResolver =
            new DefaultRelyingPartyRegistrationResolver(registrations);
    OpenSaml5AuthenticationRequestResolver authenticationRequestResolver =
            new OpenSaml5AuthenticationRequestResolver(registrationResolver);
    authenticationRequestResolver.setAuthnRequestCustomizer((context) -> context
            .getAuthnRequest().setForceAuthn(true));
    return authenticationRequestResolver;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationRequestResolver(registrations : RelyingPartyRegistrationRepository) : Saml2AuthenticationRequestResolver {
    val registrationResolver : RelyingPartyRegistrationResolver =
            new DefaultRelyingPartyRegistrationResolver(registrations)
    val authenticationRequestResolver : OpenSaml5AuthenticationRequestResolver =
            new OpenSaml5AuthenticationRequestResolver(registrationResolver)
    authenticationRequestResolver.setAuthnRequestCustomizer((context) -> context
            .getAuthnRequest().setForceAuthn(true))
    return authenticationRequestResolver
}
----
======
