
[[kotlin-config]]
= Cấu hình Kotlin

Cấu hình Kotlin của Spring Security đã có từ Spring Security 5.3.
Cấu hình này cho phép user cấu hình Spring Security bằng native Kotlin DSL.

[NOTE]
====
Spring Security cung cấp https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/kotlin/hello-security[một ứng dụng mẫu] để minh họa việc sử dụng Kotlin Configuration của Spring Security.
====

[[kotlin-config-httpsecurity]]
== HttpSecurity

Làm thế nào Spring Security biết rằng chúng ta muốn yêu cầu mọi user phải authenticated?
Làm thế nào Spring Security biết rằng chúng ta muốn hỗ trợ authentication dựa trên form?
Có một configuration class (gọi là `SecurityFilterChain`) được invoke ngầm phía sau.
Class này được cấu hình bằng implementation mặc định sau:

[source,kotlin]
----
import org.springframework.security.config.annotation.web.invoke

@Bean
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        authorizeHttpRequests {
            authorize(anyRequest, authenticated)
        }
        formLogin { }
        httpBasic { }
    }
    return http.build()
}
----

[NOTE]
Hãy nhớ import function `org.springframework.security.config.annotation.web.invoke` để bật Kotlin DSL trong class của bạn, vì IDE không phải lúc nào cũng tự động import method này, dẫn đến lỗi biên dịch.

Cấu hình mặc định (được trình bày trong ví dụ trước):

* Đảm bảo mọi request đến application đều yêu cầu user phải authenticated
* Cho phép user authenticate bằng form-based login
* Cho phép user authenticate bằng HTTP Basic authentication

Lưu ý rằng configuration này tương đương với XML namespace configuration:

[source,xml]
----
<http>
	<intercept-url pattern="/**" access="authenticated"/>
	<form-login />
	<http-basic />
</http>
----

=== Nhiều instance của HttpSecurity

Để quản lý security hiệu quả trong một application mà một số khu vực cần các mức bảo vệ khác nhau, chúng ta có thể sử dụng nhiều filter chain cùng với DSL method `securityMatcher`.
Cách tiếp cận này cho phép chúng ta định nghĩa các security configuration riêng biệt, phù hợp với từng phần cụ thể của application, từ đó tăng cường security và khả năng kiểm soát tổng thể của application.

Chúng ta có thể cấu hình nhiều instance `HttpSecurity`, giống như có thể có nhiều block `<http>` trong XML.
Điểm mấu chốt là đăng ký nhiều `SecurityFilterChain` ``@Bean``.
Ví dụ sau có configuration khác cho các URL bắt đầu bằng `/api/`:

[[multiple-httpsecurity-instances-kotlin]]
[source,kotlin]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class MultiHttpSecurityConfig {
    @Bean                                                            <1>
    open fun userDetailsService(): UserDetailsService {
        val users = User.withDefaultPasswordEncoder()
        val manager = InMemoryUserDetailsManager()
        manager.createUser(users.username("user").password("password").roles("USER").build())
        manager.createUser(users.username("admin").password("password").roles("USER","ADMIN").build())
        return manager
    }

    @Bean
    @Order(1)                                                        <2>
    open fun apiFilterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            securityMatcher("/api/**")                               <3>
            authorizeHttpRequests {
                authorize(anyRequest, hasRole("ADMIN"))
            }
            httpBasic { }
        }
        return http.build()
    }

    @Bean                                                            <4>
    open fun formLoginFilterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            formLogin { }
        }
        return http.build()
    }
}
----
<1> Cấu hình Authentication như bình thường.
<2> Tạo một instance `SecurityFilterChain` có `@Order` để chỉ định `SecurityFilterChain` nào được xem xét trước.
<3> `http.securityMatcher()` cho biết `HttpSecurity` này chỉ áp dụng cho các URL bắt đầu bằng `/api/`.
<4> Tạo một instance `SecurityFilterChain` khác.
Nếu URL không bắt đầu bằng `/api/`, configuration này sẽ được sử dụng.
Configuration này được xem xét sau `apiFilterChain` vì có giá trị `@Order` sau `1` (không có `@Order` thì mặc định là cuối cùng).

=== Chọn `securityMatcher` hay `requestMatchers`

Một câu hỏi thường gặp là:

> Điểm khác nhau giữa method `http.securityMatcher()` và `requestMatchers()` được sử dụng cho request authorization (tức là bên trong `http.authorizeHttpRequests()`) là gì?

Để trả lời câu hỏi này, cần hiểu rằng mỗi instance `HttpSecurity` được sử dụng để build một `SecurityFilterChain` đều chứa một `RequestMatcher` để match các request đến.
Nếu request không match `SecurityFilterChain` có độ ưu tiên cao hơn (ví dụ `@Order(1)`), request có thể được thử với filter chain có độ ưu tiên thấp hơn (ví dụ không có `@Order`).

[NOTE]
====
Logic match giữa nhiều filter chain được thực hiện bởi xref:servlet/architecture.adoc#servlet-filterchainproxy[`FilterChainProxy`].
====

`RequestMatcher` mặc định match *mọi request* để đảm bảo Spring Security *bảo vệ mọi request theo mặc định*.

[NOTE]
====
Việc chỉ định `securityMatcher` sẽ ghi đè mặc định này.
====

[WARNING]
====
Nếu không có filter chain nào match một request cụ thể, request đó sẽ *không được Spring Security bảo vệ*.
====

Ví dụ sau minh họa một filter chain duy nhất chỉ bảo vệ các request bắt đầu bằng `/secured/`:

[[choosing-security-matcher-request-matchers-kotlin]]
[source,kotlin]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class PartialSecurityConfig {
	@Bean
	open fun userDetailsService(): UserDetailsService {
		// ...
	}

	@Bean
	open fun securedFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			securityMatcher("/secured/**")                             <1>
			authorizeHttpRequests {
				authorize("/secured/user", hasRole("USER"))            <2>
				authorize("/secured/admin", hasRole("ADMIN"))          <3>
				authorize(anyRequest, authenticated)                   <4>
			}
			httpBasic { }
			formLogin { }
		}
		return http.build()
	}
}
----
<1> Các request bắt đầu bằng `/secured/` sẽ được bảo vệ, còn các request khác thì không.
<2> Request đến `/secured/user` yêu cầu authority `ROLE_USER`.
<3> Request đến `/secured/admin` yêu cầu authority `ROLE_ADMIN`.
<4> Mọi request khác (chẳng hạn `/secured/other`) chỉ yêu cầu user phải authenticated.

[TIP]
====
_Khuyến nghị_ cung cấp một `SecurityFilterChain` không chỉ định `securityMatcher` để đảm bảo toàn bộ application được bảo vệ, như đã minh họa trong <<multiple-httpsecurity-instances-kotlin,ví dụ trước>>.
====

Lưu ý rằng method `requestMatchers` chỉ áp dụng cho từng authorization rule riêng lẻ.
Mỗi request được liệt kê ở đó cũng phải match với `securityMatcher` tổng thể của instance `HttpSecurity` cụ thể được sử dụng để tạo `SecurityFilterChain`.
Trong ví dụ này, việc sử dụng `anyRequest()` sẽ match mọi request khác trong `SecurityFilterChain` cụ thể này (vốn phải bắt đầu bằng `/secured/`).

[NOTE]
====
Xem xref:servlet/authorization/authorize-http-requests.adoc[Authorization cho HttpServletRequests] để biết thêm thông tin về `requestMatchers`.
====

=== Các endpoint của `SecurityFilterChain`

Một số filter trong `SecurityFilterChain` trực tiếp cung cấp endpoint, chẳng hạn `UsernamePasswordAuthenticationFilter` được thiết lập bởi `http.formLogin()` và cung cấp endpoint `POST /login`.
Trong <<choosing-security-matcher-request-matchers-kotlin,ví dụ trên>>, endpoint `/login` không match với `http.securityMatcher("/secured/**")`, do đó application đó sẽ không có endpoint `GET /login` hoặc `POST /login`.
Các request như vậy sẽ trả về `404 Not Found`.
Điều này thường khiến user bất ngờ.

Việc chỉ định `http.securityMatcher()` ảnh hưởng đến các request được `SecurityFilterChain` đó match.
Tuy nhiên, việc này không tự động ảnh hưởng đến các endpoint do filter chain cung cấp.
Trong những trường hợp đó, bạn có thể cần tùy chỉnh URL của các endpoint mà bạn muốn filter chain cung cấp.

Ví dụ sau minh họa một configuration bảo vệ các request bắt đầu bằng `/secured/` và từ chối mọi request khác, đồng thời tùy chỉnh các endpoint do `SecurityFilterChain` cung cấp:

[[security-filter-chain-endpoints-kotlin]]
[source,kotlin]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecuredSecurityConfig {
	@Bean
	open fun userDetailsService(): UserDetailsService {
		// ...
	}

	@Bean
	@Order(1)
	open fun securedFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			securityMatcher("/secured/**")                             <1>
			authorizeHttpRequests {
				authorize(anyRequest, authenticated)                   <2>
			}
			formLogin {                                                <3>
                loginPage = "/secured/login"
                loginProcessingUrl = "/secured/login"
                permitAll = true
			}
			logout {                                                   <4>
                logoutUrl = "/secured/logout"
                logoutSuccessUrl = "/secured/login?logout"
                permitAll = true
			}
		}
		return http.build()
	}

	@Bean
    open fun defaultFilterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, denyAll)                         <5>
            }
        }
        return http.build()
    }
}
----
<1> Các request bắt đầu bằng `/secured/` sẽ được filter chain này bảo vệ.
<2> Các request bắt đầu bằng `/secured/` yêu cầu user phải authenticated.
<3> Tùy chỉnh form login để thêm tiền tố `/secured/` vào URL.
<4> Tùy chỉnh logout để thêm tiền tố `/secured/` vào URL.
<5> Mọi request khác sẽ bị từ chối.

[NOTE]
====
Ví dụ này tùy chỉnh login page và logout page, việc này vô hiệu hóa các page được Spring Security tạo.
Bạn phải xref:servlet/authentication/passwords/form.adoc#servlet-authentication-form-custom[tự cung cấp] các endpoint tùy chỉnh cho `GET /secured/login` và `GET /secured/logout`.
Lưu ý rằng Spring Security vẫn cung cấp endpoint `POST /secured/login` và `POST /secured/logout` cho bạn.
====

=== Ví dụ thực tế

Ví dụ sau minh họa một configuration thực tế hơn một chút, kết hợp tất cả các thành phần này:

[[real-world-example-kotlin]]
[source,kotlin]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class BankingSecurityConfig {
    @Bean                                                              <1>
    open fun userDetailsService(): UserDetailsService {
        val users = User.withDefaultPasswordEncoder()
        val manager = InMemoryUserDetailsManager()
        manager.createUser(users.username("user1").password("password").roles("USER", "VIEW_BALANCE").build())
        manager.createUser(users.username("user2").password("password").roles("USER").build())
        manager.createUser(users.username("admin").password("password").roles("ADMIN").build())
        return manager
    }

    @Bean
    @Order(1)                                                          <2>
    open fun approvalsSecurityFilterChain(http: HttpSecurity): SecurityFilterChain {
        val approvalsPaths = arrayOf("/accounts/approvals/**", "/loans/approvals/**", "/credit-cards/approvals/**")
        http {
            securityMatcher(*approvalsPaths)
            authorizeHttpRequests {
				authorize(anyRequest, hasRole("ADMIN"))
            }
            httpBasic { }
        }
        return http.build()
    }

    @Bean
    @Order(2)                                                          <3>
	open fun bankingSecurityFilterChain(http: HttpSecurity): SecurityFilterChain {
        val bankingPaths = arrayOf("/accounts/**", "/loans/**", "/credit-cards/**", "/balances/**")
		val viewBalancePaths = arrayOf("/balances/**")
        http {
            securityMatcher(*bankingPaths)
            authorizeHttpRequests {
                authorize(viewBalancePaths, hasRole("VIEW_BALANCE"))
				authorize(anyRequest, hasRole("USER"))
            }
        }
        return http.build()
    }

    @Bean                                                              <4>
	open fun defaultSecurityFilterChain(http: HttpSecurity): SecurityFilterChain {
        val allowedPaths = arrayOf("/", "/user-login", "/user-logout", "/notices", "/contact", "/register")
        http {
            authorizeHttpRequests {
                authorize(allowedPaths, permitAll)
				authorize(anyRequest, authenticated)
            }
			formLogin {
                loginPage = "/user-login"
                loginProcessingUrl = "/user-login"
			}
			logout {
                logoutUrl = "/user-logout"
                logoutSuccessUrl = "/?logout"
			}
        }
        return http.build()
    }
}
----
<1> Bắt đầu bằng việc cấu hình các thiết lập authentication.
<2> Định nghĩa một instance `SecurityFilterChain` với `@Order(1)`, nghĩa là filter chain này có độ ưu tiên cao nhất.
    Filter chain này chỉ áp dụng cho các request bắt đầu bằng `/accounts/approvals/`, `/loans/approvals/` hoặc `/credit-cards/approvals/`.
	Các request đến filter chain này yêu cầu authority `ROLE_ADMIN` và cho phép HTTP Basic Authentication.
<3> Tiếp theo, tạo một instance `SecurityFilterChain` khác với `@Order(2)`, sẽ được xem xét thứ hai.
    Filter chain này chỉ áp dụng cho các request bắt đầu bằng `/accounts/`, `/loans/`, `/credit-cards/` hoặc `/balances/`.
	Lưu ý rằng vì filter chain này được xem xét thứ hai, mọi request chứa `/approvals/` sẽ match filter chain trước đó và *không* được filter chain này match.
	Các request đến filter chain này yêu cầu authority `ROLE_USER`.
	Filter chain này không định nghĩa authentication nào vì filter chain tiếp theo (mặc định) chứa configuration đó.
<4> Cuối cùng, tạo thêm một instance `SecurityFilterChain` không có annotation `@Order`.
	Configuration này sẽ xử lý các request không được các filter chain khác bao phủ và được xử lý cuối cùng (không có `@Order` thì mặc định là cuối cùng).
	Các request match `/`, `/user-login`, `/user-logout`, `/notices`, `/contact` và `/register` được phép truy cập mà không cần authentication.
	Mọi request khác yêu cầu user phải authenticated để truy cập bất kỳ URL nào không được cho phép rõ ràng hoặc được các filter chain khác bảo vệ.


[[modular-httpsecuritydsl-configuration]]
== Cấu hình dạng module cho HttpSecurityDsl

Nhiều user muốn đặt security configuration của họ ở một nơi tập trung và sẽ chọn cấu hình trong một instance `SecurityFilterChain` duy nhất.
Tuy nhiên, đôi khi user muốn chia configuration thành các module.
Có thể thực hiện việc này bằng:

* xref:#httpsecuritydsl-bean[Các Bean HttpSecurityDsl.() -> Unit]
* xref:#top-level-dsl-bean[Các Bean Security DSL cấp cao nhất]

NOTE: Vì Kotlin DSL (`HttpSecurityDsl`) của Spring Security sử dụng `HttpSecurity`, toàn bộ xref:./kotlin.adoc#modular-bean-configuration[Tùy chỉnh Bean dạng module] của Java được áp dụng trước xref:#modular-httpsecuritydsl-configuration[Cấu hình HttpSecurity dạng module].

[[httpsecuritydsl-bean]]
=== Các Bean HttpSecurityDsl.() -> Unit

Nếu muốn chia security configuration thành các module, bạn có thể đặt logic trong một Bean `HttpSecurityDsl.() -> Unit`.
Ví dụ, configuration sau sẽ đảm bảo mọi instance `HttpSecurityDsl` được cấu hình để:

include-code::./HttpSecurityDslBeanConfiguration[tag=httpSecurityDslBean,indent=0]

<1> Đặt xref:servlet/exploits/headers.adoc#servlet-headers-csp[Content Security Policy] thành `object-src 'none'`
<2> xref:servlet/exploits/http.adoc#servlet-http-redirect[Chuyển hướng mọi request sang https]


[[top-level-dsl-bean]]
=== Các Bean Security DSL cấp cao nhất

Nếu muốn modularize security configuration hơn nữa, Spring Security sẽ tự động áp dụng mọi Bean Security DSL cấp cao nhất.

Có thể tóm tắt Security DSL cấp cao nhất là bất kỳ class DSL nào match `public HttpSecurityDsl.*(<Dsl>)`.
Điều này có nghĩa là bất kỳ Security DSL nào là một argument duy nhất của một public method trên `HttpSecurityDsl`.

Một vài ví dụ có thể giúp làm rõ điều này.
Nếu `ContentTypeOptionsDsl.() -> Unit` được publish dưới dạng Bean, nó sẽ không được tự động áp dụng vì là argument của `HeadersDsl#contentTypeOptions(ContentTypeOptionsDsl.() -> Unit)` và không phải là argument của method được định nghĩa trên `HttpSecurityDsl`.
Tuy nhiên, nếu `HeadersDsl.() -> Unit` được publish dưới dạng Bean, nó sẽ được tự động áp dụng vì là argument của `HttpSecurityDsl.headers(HeadersDsl.() -> Unit)`.

Ví dụ, configuration sau đảm bảo mọi instance `HttpSecurityDsl` được cấu hình để:

include-code::./TopLevelDslBeanConfiguration[tag=headersSecurity,indent=0]

<1> Đặt xref:servlet/exploits/headers.adoc#servlet-headers-csp[Content Security Policy] thành `object-src 'none'`

[[dsl-bean-ordering]]
=== Thứ tự của các Bean DSL

Đầu tiên, toàn bộ xref:servlet/configuration/java.adoc#modular-httpsecurity-configuration[Cấu hình HttpSecurity dạng module] được áp dụng vì Kotlin DSL sử dụng một Bean `HttpSecurity`.

Thứ hai, mỗi xref:#httpsecuritydsl-bean[Các Bean HttpSecurityDsl.() -> Unit] được áp dụng bằng {spring-framework-api-url}org/springframework/beans/factory/ObjectProvider.html#orderedStream()[ObjectProvider#orderedStream()].
Điều này có nghĩa là nếu có nhiều Bean `HttpSecurity.() -> Unit`, có thể thêm annotation {spring-framework-api-url}org/springframework/core/annotation/Order.html[@Order] vào các định nghĩa Bean để kiểm soát thứ tự.

Tiếp theo, mỗi type xref:#top-level-dsl-bean[Bean Security DSL cấp cao nhất] được lookup và áp dụng bằng `ObjectProvider#orderedStream()`.
Nếu có các type Bean Security DSL cấp cao nhất khác nhau (ví dụ `HeadersDsl.() -> Unit` và `HttpsRedirectDsl.() -> Unit`), thứ tự gọi từng type DSL là không xác định.
Tuy nhiên, thứ tự của từng instance thuộc cùng một type Bean Security DSL cấp cao nhất được xác định bởi `ObjectProvider#orderedStream()` và có thể được kiểm soát bằng `@Order` trên các định nghĩa Bean.

Cuối cùng, Bean `HttpSecurityDsl` được inject dưới dạng một Bean.
Mọi Bean `*Dsl.() -> Unit` được áp dụng trước khi Bean `HttpSecurityDsl` được tạo.
Điều này cho phép ghi đè các tùy chỉnh do các Bean `*Dsl.() -> Unit` cung cấp.

Ví dụ dưới đây minh họa thứ tự:

include-code::./DslBeanOrderingConfiguration[tag=sample,indent=0]

<1> Toàn bộ xref:servlet/configuration/java.adoc#modular-httpsecurity-configuration[Cấu hình HttpSecurity dạng module] được áp dụng vì Kotlin DSL sử dụng một Bean `HttpSecurity`.
<2> Mọi instance `HttpSecurity.() -> Unit` được áp dụng.
Bean `adminAuthorization` có `@Order` cao nhất nên được áp dụng trước.
Nếu các Bean `HttpSecurity.() -> Unit` không có annotation `@Order`, hoặc các annotation `@Order` có cùng giá trị, thứ tự áp dụng các instance `HttpSecurity.() -> Unit` là không xác định.
<3> `userAuthorization` được áp dụng tiếp theo vì là một instance của `HttpSecurity.() -> Unit`.
<4> Thứ tự của các type `*Dsl.() -> Unit` là không xác định.
Trong ví dụ này, thứ tự của `contentSecurityPolicy`, `contentTypeOptions` và `httpsRedirect` là không xác định.
Nếu thêm `@Order(Ordered.HIGHEST_PRECEDENCE)` vào `contentTypeOptions`, chúng ta sẽ biết `contentTypeOptions` đứng trước `contentSecurityPolicy` (chúng cùng một type), nhưng không biết `httpsRedirect` đứng trước hay sau các Bean `HeadersDsl.() -> Unit`.
<5> Sau khi áp dụng mọi Bean `*Dsl.() -> Unit`, `HttpSecurityDsl` được truyền vào dưới dạng một Bean.
