
[[ns-config]]
= Cấu hình Namespace Security


Cấu hình Namespace đã có từ version 2.0 của Spring Framework.
Nó cho phép bạn bổ sung cú pháp application context của Spring bean truyền thống bằng các phần tử từ XML schema bổ sung.
Bạn có thể tìm thêm thông tin trong {spring-framework-reference-url}index.html[Tài liệu tham khảo] của Spring.
Bạn có thể sử dụng một phần tử namespace để cấu hình ngắn gọn hơn một bean riêng lẻ hoặc, mạnh mẽ hơn, để định nghĩa một cú pháp cấu hình thay thế gần hơn với miền bài toán và ẩn đi độ phức tạp bên dưới đối với user.
Một phần tử đơn giản có thể che giấu việc nhiều bean và bước xử lý đang được thêm vào application context.
Ví dụ, thêm phần tử sau từ namespace `security` vào application context sẽ khởi động một LDAP server embedded để sử dụng cho việc testing trong ứng dụng:

[source,xml]
----
<security:ldap-server />
----

Cách này đơn giản hơn nhiều so với việc wiring các bean UnboundID Server tương đương.
Các yêu cầu cấu hình thay thế phổ biến nhất được hỗ trợ bằng các attribute trên phần tử `ldap-server`, và user không phải bận tâm về việc cần tạo những bean nào hay tên thuộc tính của bean là gì.
Bạn có thể tìm hiểu thêm về cách sử dụng phần tử `ldap-server` trong chương về xref:servlet/authentication/passwords/ldap.adoc#servlet-authentication-ldap[LDAP Authentication].
Một XML editor tốt trong khi chỉnh sửa file application context sẽ cung cấp thông tin về các attribute và phần tử hiện có.
Chúng tôi khuyến nghị bạn dùng https://spring.io/tools/sts[Spring Tool Suite], vì công cụ này có các tính năng đặc biệt để làm việc với các namespace chuẩn của Spring.

Để bắt đầu sử dụng namespace `security` trong application context, hãy thêm jar `spring-security-config` vào classpath.
Sau đó, bạn chỉ cần thêm khai báo schema vào file application context:

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
xmlns:security="http://www.springframework.org/schema/security"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
		https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/security
		https://www.springframework.org/schema/security/spring-security.xsd">
	...
</beans>
----

Trong nhiều ví dụ bạn thấy (và trong các ứng dụng mẫu), chúng tôi thường sử dụng `security` (thay vì `beans`) làm namespace mặc định. Điều này nghĩa là chúng ta có thể bỏ prefix trên mọi phần tử của namespace security, giúp nội dung dễ đọc hơn.
Bạn cũng có thể muốn làm vậy nếu application context được chia thành các file riêng và phần lớn cấu hình security nằm trong một file trong số đó.
Khi đó, file application context security sẽ bắt đầu như sau:

[source,xml]
----
<beans:beans xmlns="http://www.springframework.org/schema/security"
xmlns:beans="http://www.springframework.org/schema/beans"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
		https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/security
		https://www.springframework.org/schema/security/spring-security.xsd">
	...
</beans:beans>
----

Từ đây trở đi trong chương này, chúng ta giả định đang sử dụng cú pháp này.


== Thiết kế Namespace
Namespace được thiết kế để bao quát những cách sử dụng framework phổ biến nhất và cung cấp cú pháp đơn giản, ngắn gọn để bật chúng trong một ứng dụng.
Thiết kế này dựa trên các dependency quy mô lớn bên trong framework và có thể được chia thành những khu vực sau:

* _Web/HTTP Security_ là phần phức tạp nhất.
Phần này thiết lập các Filter và các bean service liên quan được sử dụng để áp dụng các cơ chế authentication của framework, bảo vệ URL, render trang đăng nhập và trang lỗi, cùng nhiều chức năng khác.

* _Business Object (Method) Security_ định nghĩa các tùy chọn để bảo vệ service layer.

* _AuthenticationManager_ xử lý các yêu cầu authentication từ những phần khác của framework.

* _AccessDecisionManager_ đưa ra quyết định access cho web security và method security.
Một implementation mặc định được đăng ký, nhưng bạn có thể chọn sử dụng một implementation tùy chỉnh được khai báo bằng cú pháp Spring bean thông thường.

* Các instance _AuthenticationProvider_ cung cấp các cơ chế mà authentication manager sử dụng để authentication user.
Namespace hỗ trợ một số tùy chọn chuẩn và cung cấp cách thêm các bean tùy chỉnh được khai báo bằng cú pháp truyền thống.

* _UserDetailsService_ có quan hệ chặt chẽ với các authentication provider nhưng thường cũng được các bean khác yêu cầu.

Các phần sau sẽ trình bày cách cấu hình những thành phần này.

[[ns-getting-started]]
== Bắt đầu với Cấu hình Namespace Security
Phần này trình bày cách xây dựng một cấu hình namespace để sử dụng một số tính năng chính của framework.
Chúng ta giả định ban đầu bạn muốn chạy ứng dụng nhanh nhất có thể, đồng thời thêm authentication support và access control vào một web application hiện có, với một vài login dùng để testing.
Sau đó, chúng ta xem cách chuyển sang authentication dựa trên database hoặc security repository khác.
Các phần sau sẽ giới thiệu những tùy chọn cấu hình namespace nâng cao hơn.

[[ns-web-xml]]
=== Cấu hình web.xml
Việc đầu tiên bạn cần làm là thêm khai báo Filter sau vào file `web.xml`:

[source,xml]
----
<filter>
<filter-name>springSecurityFilterChain</filter-name>
<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
</filter>

<filter-mapping>
<filter-name>springSecurityFilterChain</filter-name>
<url-pattern>/*</url-pattern>
</filter-mapping>
----

`DelegatingFilterProxy` là một class của Spring Framework ủy quyền cho một implementation Filter được định nghĩa dưới dạng Spring bean trong application context của bạn.
Trong trường hợp này, bean có tên là `springSecurityFilterChain`, một bean hạ tầng nội bộ được namespace tạo ra để xử lý web security.
Trong trường hợp này, bean có tên là "springSecurityFilterChain", một bean hạ tầng nội bộ được namespace tạo ra để xử lý web security.
Lưu ý rằng bạn không nên tự sử dụng tên bean này.
Sau khi thêm bean này vào `web.xml`, bạn đã sẵn sàng bắt đầu chỉnh sửa file application context.
Các service web security được cấu hình bằng phần tử `<http>`.

[[ns-minimal]]
=== Cấu hình <http> Tối thiểu
Để bật web security, bạn cần cấu hình như sau:

[source,xml]
----
<http>
<intercept-url pattern="/**" access="hasRole('USER')" />
<form-login />
<logout />
</http>
----

Listing này cho biết chúng ta muốn:

* Bảo vệ tất cả URL trong ứng dụng, yêu cầu role `ROLE_USER` để truy cập
* Đăng nhập vào ứng dụng bằng form với username và password
* Đăng ký một URL logout cho phép chúng ta logout khỏi ứng dụng

Phần tử `<http>` là phần tử cha cho toàn bộ chức năng namespace liên quan đến web.
Phần tử `<intercept-url>` định nghĩa một `pattern`, được so khớp với các URL của request đến bằng cú pháp đường dẫn Ant. Xem phần về xref:servlet/exploits/firewall.adoc#servlet-httpfirewall[`HttpFirewall`] để biết thêm chi tiết về cách việc so khớp thực sự được thực hiện.
Bạn cũng có thể sử dụng so khớp regular expression làm phương án thay thế (xem namespace appendix để biết thêm chi tiết).
Attribute `access` định nghĩa các yêu cầu access cho những request khớp với pattern đã cho.
Với cấu hình mặc định, đây thường là danh sách role được phân tách bằng dấu phẩy; user phải có ít nhất một role trong số đó để được phép thực hiện request.
Prefix `ROLE_` là một marker cho biết cần thực hiện so sánh đơn giản với các authority của user.
Nói cách khác, cần sử dụng một kiểm tra thông thường dựa trên role.
Access control trong Spring Security không bị giới hạn ở việc sử dụng các role đơn giản (do đó cần có prefix để phân biệt các loại security attribute khác nhau).
Phần sau sẽ trình bày cách diễn giải có thể thay đổi. Cách diễn giải các giá trị được phân tách bằng dấu phẩy trong attribute `access` phụ thuộc vào implementation nào của <<ns-access-manager,`AccessDecisionManager`>> được sử dụng.
Kể từ Spring Security 3.0, bạn cũng có thể điền attribute này bằng một xref:servlet/authorization/authorize-http-requests.adoc#authorization-expressions[EL expression].


[NOTE]
====
Bạn có thể sử dụng nhiều phần tử `<intercept-url>` để định nghĩa các yêu cầu access khác nhau cho các nhóm URL khác nhau, nhưng chúng được đánh giá theo thứ tự được liệt kê và match đầu tiên sẽ được sử dụng.
Vì vậy, bạn phải đặt các match cụ thể nhất lên đầu.
Bạn cũng có thể thêm attribute `method` để giới hạn match vào một HTTP method cụ thể (`GET`, `POST`, `PUT`, v.v.).
====

Để thêm user, bạn có thể định nghĩa trực tiếp một tập dữ liệu dùng để testing trong namespace:

[source,xml,attrs="-attributes"]
----
<authentication-manager>
<authentication-provider>
	<user-service>
	<!-- Password is prefixed with {noop} to indicate to DelegatingPasswordEncoder that
	NoOpPasswordEncoder should be used. This is not safe for production, but makes reading
	in samples easier. Normally passwords should be hashed using BCrypt -->
	<user name="jimi" password="{noop}jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{noop}bobspassword" authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>
----

Listing trước đó cho thấy một ví dụ về cách lưu trữ an toàn các password tương tự.
Password được thêm prefix `+{bcrypt}+` để chỉ dẫn cho `DelegatingPasswordEncoder`, vốn hỗ trợ mọi `PasswordEncoder` đã cấu hình khi matching, rằng các password được hash bằng BCrypt:

[source,xml,attrs="-attributes"]
----
<authentication-manager>
<authentication-provider>
	<user-service>
	<user name="jimi" password="{bcrypt}$2a$10$ddEWZUl8aU0GdZPPpy7wbu82dvEw/pBpbRvDQRqA41y6mK1CoH00m"
			authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{bcrypt}$2a$10$/elFpMBnAYYig6KRR5bvOOYeZr1ie1hSogJryg9qDlhza4oCw1Qka"
			authorities="ROLE_USER" />
	<user name="jimi" password="{noop}jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{noop}bobspassword" authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>
----


[subs="quotes"]
****
Phần tử `<http>` chịu trách nhiệm tạo một `FilterChainProxy` và các bean Filter mà nó sử dụng.
Những vấn đề thường gặp trước đây, chẳng hạn như thứ tự Filter không đúng, không còn là vấn đề nữa vì vị trí của các Filter đã được định nghĩa trước.

Phần tử `<authentication-provider>` tạo một bean `DaoAuthenticationProvider`, còn phần tử `<user-service>` tạo một `InMemoryDaoImpl`.
Mọi phần tử `authentication-provider` phải là phần tử con của phần tử `<authentication-manager>`, phần tử này tạo một `ProviderManager` và đăng ký các authentication provider với nó.
Bạn có thể tìm thông tin chi tiết hơn về các bean được tạo trong xref:servlet/appendix/namespace/index.adoc#appendix-namespace[namespace appendix].
Bạn nên đối chiếu appendix này nếu muốn bắt đầu tìm hiểu những class quan trọng trong framework là gì và chúng được sử dụng như thế nào, đặc biệt nếu sau này bạn muốn tùy chỉnh.
****

Cấu hình trước đó định nghĩa hai user, password của họ và role của họ trong ứng dụng (được sử dụng cho access control).
Bạn cũng có thể tải thông tin user từ một properties file chuẩn bằng cách đặt attribute `properties` trên phần tử `user-service`.
Xem phần về xref:servlet/authentication/passwords/in-memory.adoc#servlet-authentication-inmemory[in-memory authentication] để biết thêm chi tiết về định dạng file.
Việc sử dụng phần tử `<authentication-provider>` nghĩa là authentication manager sẽ sử dụng thông tin user để xử lý các yêu cầu authentication.
Bạn có thể có nhiều phần tử `<authentication-provider>` để định nghĩa các authentication source khác nhau. Mỗi source sẽ được tham vấn lần lượt.

Tại thời điểm này, bạn có thể khởi động ứng dụng và hệ thống sẽ yêu cầu bạn login để tiếp tục.
Hãy thử hoặc thử thực hành với ứng dụng mẫu "`tutorial`" đi kèm project.

[[ns-form-target]]
==== Thiết lập Đích Mặc định Sau Khi Login
Nếu form login không được yêu cầu do một nỗ lực truy cập resource được bảo vệ, tùy chọn `default-target-url` sẽ được áp dụng.
Đây là URL mà user được chuyển đến sau khi login thành công. Mặc định là `/`.
Bạn cũng có thể cấu hình để user _luôn_ kết thúc ở trang này (bất kể login là "`on-demand`" hay user chủ động chọn login) bằng cách đặt attribute `always-use-default-target` thành `true`.
Điều này hữu ích nếu ứng dụng của bạn luôn yêu cầu user bắt đầu tại một trang "`home`", ví dụ:

[source,xml]
----
<http pattern="/login.htm*" security="none"/>
<http use-expressions="false">
<intercept-url pattern='/**' access='ROLE_USER' />
<form-login login-page='/login.htm' default-target-url='/home.htm'
		always-use-default-target='true' />
</http>
----

Để kiểm soát đích đến nhiều hơn, bạn có thể sử dụng attribute `authentication-success-handler-ref` thay cho `default-target-url`.
Bean được tham chiếu phải là một instance của `AuthenticationSuccessHandler`.

[[ns-web-advanced]]
== Tính năng Web Nâng cao
Phần này trình bày nhiều tính năng vượt ra ngoài những nội dung cơ bản.

[[ns-custom-filters]]
=== Thêm Filter của riêng bạn
Nếu đã từng sử dụng Spring Security, bạn biết rằng framework duy trì một chain các Filter để áp dụng các service của nó.
Bạn có thể muốn thêm Filter của riêng mình vào stack tại những vị trí cụ thể hoặc sử dụng một Filter của Spring Security mà hiện chưa có tùy chọn cấu hình namespace (chẳng hạn CAS).
// FIXME: Is it still true that there is no CAS filter?
Ngoài ra, bạn có thể muốn sử dụng một phiên bản đã tùy chỉnh của Filter namespace chuẩn, chẳng hạn `UsernamePasswordAuthenticationFilter` (được tạo bởi phần tử `<form-login>`), để tận dụng một số tùy chọn cấu hình bổ sung có sẵn khi bạn sử dụng bean một cách tường minh.
Bạn có thể làm điều này bằng cấu hình namespace như thế nào, khi filter chain không được expose trực tiếp?

Thứ tự của các Filter luôn được thực thi nghiêm ngặt khi bạn sử dụng namespace.
Khi application context đang được tạo, các bean Filter được sắp xếp bằng code xử lý namespace, và mỗi Filter Spring Security chuẩn đều có một alias trong namespace cùng một vị trí được biết trước.

[NOTE]
====
Trong các version trước, việc sắp xếp diễn ra sau khi các instance Filter được tạo, trong quá trình post-processing application context.
Trong version 3.0+, việc sắp xếp hiện được thực hiện ở cấp bean metadata, trước khi các class được khởi tạo.
Điều này ảnh hưởng đến cách bạn thêm Filter của riêng mình vào stack, vì toàn bộ danh sách Filter phải được biết trong quá trình parse phần tử `<http>`, nên cú pháp đã thay đổi một chút trong version 3.0.
====

Các Filter, alias và phần tử, attribute namespace tạo ra Filter được trình bày trong bảng sau, theo thứ tự chúng xuất hiện trong filter chain:

[[filter-stack]]
.Bí danh và Thứ tự Filter Chuẩn
|===
| Bí danh | Class Filter | Phần tử hoặc Attribute Namespace

| DISABLE_ENCODE_URL_FILTER
| `DisableEncodeUrlFilter`
| `http@disable-url-rewriting`

| FORCE_EAGER_SESSION_FILTER
| `ForceEagerSessionCreationFilter`
| `http@create-session="ALWAYS"`

|  CHANNEL_FILTER
| `ChannelProcessingFilter`
| `http/intercept-url@requires-channel`

|  SECURITY_CONTEXT_FILTER
| `SecurityContextPersistenceFilter`
| `http`

|  CONCURRENT_SESSION_FILTER
| `ConcurrentSessionFilter`
| `session-management/concurrency-control`

| HEADERS_FILTER
| `HeaderWriterFilter`
| `http/headers`

| CSRF_FILTER
| `CsrfFilter`
| `http/csrf`

|  LOGOUT_FILTER
| `LogoutFilter`
| `http/logout`

|  X509_FILTER
| `X509AuthenticationFilter`
| `http/x509`

|  PRE_AUTH_FILTER
| `AbstractPreAuthenticatedProcessingFilter` Các subclass
| N/A

|  CAS_FILTER
| `CasAuthenticationFilter`
| N/A

|  FORM_LOGIN_FILTER
| `UsernamePasswordAuthenticationFilter`
| `http/form-login`

|  BASIC_AUTH_FILTER
| `BasicAuthenticationFilter`
| `http/http-basic`

|  SERVLET_API_SUPPORT_FILTER
| `SecurityContextHolderAwareRequestFilter`
| `http/@servlet-api-provision`

| JAAS_API_SUPPORT_FILTER
| `JaasApiIntegrationFilter`
| `http/@jaas-api-provision`

|  REMEMBER_ME_FILTER
| `RememberMeAuthenticationFilter`
| `http/remember-me`

|  ANONYMOUS_FILTER
| `AnonymousAuthenticationFilter`
| `http/anonymous`

|  SESSION_MANAGEMENT_FILTER
| `SessionManagementFilter`
| `session-management`

| EXCEPTION_TRANSLATION_FILTER
| `ExceptionTranslationFilter`
| `http`

|  FILTER_SECURITY_INTERCEPTOR
| `FilterSecurityInterceptor`
| `http`

|  SWITCH_USER_FILTER
| `SwitchUserFilter`
| N/A
|===

Bạn có thể thêm Filter của riêng mình vào stack bằng phần tử `custom-filter` và một trong các tên này để chỉ định vị trí Filter của bạn sẽ xuất hiện:

[source,xml]
----
<http>
<custom-filter position="FORM_LOGIN_FILTER" ref="myFilter" />
</http>

<beans:bean id="myFilter" class="com.mycompany.MySpecialAuthenticationFilter"/>
----

Bạn cũng có thể sử dụng attribute `after` hoặc `before` nếu muốn chèn Filter của mình trước hoặc sau một Filter khác trong stack.
Bạn có thể sử dụng `FIRST` và `LAST` với attribute `position` để cho biết muốn Filter của mình xuất hiện trước hoặc sau toàn bộ stack.

.Tránh xung đột vị trí Filter
[TIP]
====
Nếu chèn một Filter tùy chỉnh có thể chiếm cùng vị trí với một Filter chuẩn do namespace tạo ra, bạn không nên vô tình đưa vào các phiên bản namespace.
Hãy xóa mọi phần tử tạo ra các Filter có chức năng mà bạn muốn thay thế.

Lưu ý rằng bạn không thể thay thế các Filter được tạo ra bởi chính việc sử dụng phần tử `<http>`: `SecurityContextPersistenceFilter`, `ExceptionTranslationFilter` hoặc `FilterSecurityInterceptor`.
Theo mặc định, một `AnonymousAuthenticationFilter` được thêm vào; và trừ khi bạn đã tắt xref:servlet/authentication/session-management.adoc#ns-session-fixation[bảo vệ session-fixation], một `SessionManagementFilter` cũng được thêm vào filter chain.
====

Nếu thay thế một Filter namespace yêu cầu authentication entry point (nghĩa là quá trình authentication được kích hoạt bởi việc một user chưa được authentication cố truy cập resource được bảo vệ), bạn cũng cần thêm một bean entry-point tùy chỉnh.

[[ns-method-security]]
== Method Security
Kể từ version 2.0, Spring Security hỗ trợ đáng kể việc thêm security vào các method của service layer.
Nó hỗ trợ security bằng annotation JSR-250 cũng như annotation `@Secured` nguyên bản của framework.
Kể từ version 3.0, bạn cũng có thể sử dụng xref:servlet/authorization/method-security.adoc#authorizing-with-annotations[các annotation dựa trên expression].
Bạn có thể áp dụng security cho một bean riêng lẻ (bằng cách sử dụng phần tử `intercept-methods` để trang trí khai báo bean) hoặc bảo vệ nhiều bean trên toàn bộ service layer bằng pointcut theo phong cách AspectJ.

[[ns-access-manager]]
== AccessDecisionManager Mặc định
Phần này giả định rằng bạn có một số hiểu biết về architecture nền tảng cho access control trong Spring Security.
Nếu không, bạn có thể bỏ qua và quay lại sau, vì phần này chỉ liên quan đến những người cần tùy chỉnh để sử dụng security phức tạp hơn security dựa trên role đơn giản.

Khi sử dụng cấu hình namespace, một instance mặc định của `AccessDecisionManager` sẽ tự động được đăng ký cho bạn và được sử dụng để đưa ra quyết định access cho các lần gọi method và access URL web, dựa trên các access attribute bạn chỉ định trong khai báo `intercept-url` và `protect-pointcut` (và trong annotation nếu bạn sử dụng annotation để bảo vệ method).

Strategy mặc định là sử dụng một `AccessDecisionManager` `AffirmativeBased` cùng với một `RoleVoter` và một `AuthenticatedVoter`.
Bạn có thể tìm hiểu thêm về các thành phần này trong chương về xref:servlet/authorization/architecture.adoc#authz-arch[authorization].


[[ns-custom-access-mgr]]
=== Tùy chỉnh AccessDecisionManager
Nếu cần sử dụng một strategy access control phức tạp hơn, bạn có thể đặt một lựa chọn thay thế cho cả method security và web security.

Đối với method security, bạn thực hiện việc này bằng cách đặt attribute `access-decision-manager-ref` trên `global-method-security` thành `id` của bean `AccessDecisionManager` phù hợp trong application context:

[source,xml]
----
<global-method-security access-decision-manager-ref="myAccessDecisionManagerBean">
...
</global-method-security>
----

Cú pháp đối với web security cũng tương tự, nhưng attribute nằm trên phần tử `http`:

[source,xml]
----
<http access-decision-manager-ref="myAccessDecisionManagerBean">
...
</http>
----
