[[oauth2-client-additional-features]]
= [[oauth2Client-additional-features]]Các tính năng của Authorized Client

Phần này trình bày các tính năng bổ sung mà Spring Security cung cấp cho OAuth2 Client.

[[oauth2-client-registered-authorized-client]]
== [[oauth2Client-registered-authorized-client]]Resolve một Authorized Client

Annotation `@RegisteredOAuth2AuthorizedClient` cung cấp khả năng resolve một method parameter thành một argument value có kiểu `OAuth2AuthorizedClient`.
Đây là một alternative thuận tiện cho việc access `OAuth2AuthorizedClient` bằng `OAuth2AuthorizedClientManager` hoặc `OAuth2AuthorizedClientService`.
Ví dụ sau cho thấy cách sử dụng `@RegisteredOAuth2AuthorizedClient`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@GetMapping("/")
	public String index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
		OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

		...

		return "index";
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {
    @GetMapping("/")
    fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): String {
        val accessToken = authorizedClient.accessToken

        ...

        return "index"
    }
}
----
======

Annotation `@RegisteredOAuth2AuthorizedClient` được xử lý bởi `OAuth2AuthorizedClientArgumentResolver`, component trực tiếp sử dụng xref:servlet/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[`OAuth2AuthorizedClientManager`] và do đó kế thừa các capability của nó.

[[oauth2-client-rest-client]]
== Tích hợp RestClient

Hỗ trợ cho `RestClient` được cung cấp bởi `OAuth2ClientHttpRequestInterceptor`.
Interceptor này cho phép request các protected resource bằng cách đặt token `Bearer` vào header `Authorization` của request outbound.
Interceptor sử dụng trực tiếp `OAuth2AuthorizedClientManager` và do đó kế thừa các khả năng sau:

* Thực hiện request OAuth 2.0 Access Token để lấy `OAuth2AccessToken` nếu client chưa được authorize
** `authorization_code`: Kích hoạt redirect của Authorization Request để initiate flow
** `client_credentials`: access token được lấy trực tiếp từ Token Endpoint
** Các grant type bổ sung được hỗ trợ bằng cách xref:servlet/oauth2/index.adoc#oauth2-client-enable-extension-grant-type[bật các grant type mở rộng]
* Nếu `OAuth2AccessToken` hiện có hết hạn, token này được refresh (hoặc renew)

Ví dụ sau sử dụng `OAuth2AuthorizedClientManager` mặc định để configure một `RestClient` có thể truy cập các protected resource bằng cách đặt token `Bearer` vào header `Authorization` của mỗi request:

.Cấu hình `RestClient` với `ClientHttpRequestInterceptor`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);

		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager): RestClient {
		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)

		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

}
----
=====

[[oauth2-client-rest-client-registration-id]]
=== Cung cấp `clientRegistrationId`

`OAuth2ClientHttpRequestInterceptor` sử dụng `ClientRegistrationIdResolver` để xác định client nào được dùng để lấy access token.
Theo mặc định, `RequestAttributeClientRegistrationIdResolver` được dùng để resolve `clientRegistrationId` từ `HttpRequest#attributes()`.

Ví dụ sau minh họa cách cung cấp `clientRegistrationId` thông qua attributes:

.Cung cấp `clientRegistrationId` thông qua attributes
[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId;

@Controller
public class ResourceController {

	private final RestClient restClient;

	public ResourceController(RestClient restClient) {
		this.restClient = restClient;
	}

	@GetMapping("/")
	public String index() {
		String resourceUri = "...";

		String body = this.restClient.get()
				.uri(resourceUri)
				.attributes(clientRegistrationId("okta"))   // <1>
				.retrieve()
				.body(String.class);

		// ...

		return "index";
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId
import org.springframework.web.client.body

@Controller
class ResourceController(private restClient: RestClient) {

	@GetMapping("/")
	fun index(): String {
		val resourceUri = "..."

		val body: String = restClient.get()
				.uri(resourceUri)
				.attributes(clientRegistrationId("okta"))   // <1>
				.retrieve()
				.body<String>()

		// ...

		return "index"
	}

}
----
======
<1> `clientRegistrationId()` là một method `static` trong `RequestAttributeClientRegistrationIdResolver`.

Ngoài ra, có thể cung cấp một `ClientRegistrationIdResolver` tùy chỉnh.
Ví dụ sau configure một implementation tùy chỉnh để resolve `clientRegistrationId` từ user hiện tại.

.Cấu hình `ClientHttpRequestInterceptor` với `ClientRegistrationIdResolver` tùy chỉnh
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
		requestInterceptor.setClientRegistrationIdResolver(clientRegistrationIdResolver());

		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

	private static ClientRegistrationIdResolver clientRegistrationIdResolver() {
		return (request) -> {
			Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
			return (authentication instanceof OAuth2AuthenticationToken principal)
					? principal.getAuthorizedClientRegistrationId() : null;
		};
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager): RestClient {
		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)
		requestInterceptor.setClientRegistrationIdResolver(clientRegistrationIdResolver())

		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

	fun clientRegistrationIdResolver(): ClientRegistrationIdResolver {
		return ClientRegistrationIdResolver { request ->
			val authentication = SecurityContextHolder.getContext().getAuthentication()
			return if (authentication instanceof OAuth2AuthenticationToken) {
				authentication.getAuthorizedClientRegistrationId()
			} else {
                null
			}
		}
	}

}
----
=====

[[oauth2-client-rest-client-principal]]
=== Cung cấp `principal`

`OAuth2ClientHttpRequestInterceptor` sử dụng `PrincipalResolver` để xác định tên principal nào được liên kết với access token, cho phép application chọn cách scope `OAuth2AuthorizedClient` được lưu trữ.
Theo mặc định, `SecurityContextHolderPrincipalResolver` được dùng để resolve `principal` hiện tại từ `SecurityContextHolder`.

Ngoài ra, có thể resolve `principal` từ `HttpRequest#attributes()` bằng cách configure `RequestAttributePrincipalResolver`, như ví dụ sau:

.Cấu hình `ClientHttpRequestInterceptor` với `RequestAttributePrincipalResolver`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
		requestInterceptor.setPrincipalResolver(new RequestAttributePrincipalResolver());

		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager): RestClient {
		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)
		requestInterceptor.setPrincipalResolver(RequestAttributePrincipalResolver())

		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

}
----
=====

Ví dụ sau minh họa cách cung cấp tên `principal` thông qua attributes để scope `OAuth2AuthorizedClient` theo application thay vì user hiện tại:

.Cung cấp tên `principal` thông qua attributes
[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId;
import static org.springframework.security.oauth2.client.web.client.RequestAttributePrincipalResolver.principal;

@Controller
public class ResourceController {

	private final RestClient restClient;

	public ResourceController(RestClient restClient) {
		this.restClient = restClient;
	}

	@GetMapping("/")
	public String index() {
		String resourceUri = "...";

		String body = this.restClient.get()
				.uri(resourceUri)
				.attributes(clientRegistrationId("okta"))
				.attributes(principal("my-application"))   // <1>
				.retrieve()
				.body(String.class);

		// ...

		return "index";
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId
import org.springframework.security.oauth2.client.web.client.RequestAttributePrincipalResolver.principal
import org.springframework.web.client.body

@Controller
class ResourceController(private restClient: RestClient) {

    @GetMapping("/")
	fun index(): String {
		val resourceUri = "..."

		val body: String = restClient.get()
				.uri(resourceUri)
				.attributes(clientRegistrationId("okta"))
				.attributes(principal("my-application"))   // <1>
				.retrieve()
				.body<String>()

		// ...

		return "index"
	}

}
----
======
<1> `principal()` là một method `static` trong `RequestAttributePrincipalResolver`.

[[oauth2-client-rest-client-authorization-failure-handler]]
=== Xử lý lỗi

Nếu access token không hợp lệ vì bất kỳ lý do nào (ví dụ: token hết hạn), việc xử lý lỗi bằng cách xóa access token để token không thể được sử dụng lại có thể hữu ích.
Có thể thiết lập interceptor để tự động thực hiện việc này bằng cách cung cấp `OAuth2AuthorizationFailureHandler` nhằm xóa access token.

Ví dụ sau sử dụng `OAuth2AuthorizedClientRepository` để thiết lập `OAuth2AuthorizationFailureHandler` nhằm xóa `OAuth2AuthorizedClient` không hợp lệ *trong* context của một `HttpServletRequest`:

.Cấu hình `OAuth2AuthorizationFailureHandler` bằng `OAuth2AuthorizedClientRepository`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager,
			OAuth2AuthorizedClientRepository authorizedClientRepository) {

		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);

		OAuth2AuthorizationFailureHandler authorizationFailureHandler =
			OAuth2ClientHttpRequestInterceptor.authorizationFailureHandler(authorizedClientRepository);
		requestInterceptor.setAuthorizationFailureHandler(authorizationFailureHandler);

		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager,
			authorizedClientRepository: OAuth2AuthorizedClientRepository): RestClient {

		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)

		val authorizationFailureHandler = OAuth2ClientHttpRequestInterceptor
			.authorizationFailureHandler(authorizedClientRepository)
		requestInterceptor.setAuthorizationFailureHandler(authorizationFailureHandler)

		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

}
----
=====

Ngoài ra, có thể sử dụng `OAuth2AuthorizedClientService` để xóa `OAuth2AuthorizedClient` không hợp lệ *ngoài* context của một `HttpServletRequest`, như ví dụ sau:

.Cấu hình `OAuth2AuthorizationFailureHandler` bằng `OAuth2AuthorizedClientService`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager,
			OAuth2AuthorizedClientService authorizedClientService) {

		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);

		OAuth2AuthorizationFailureHandler authorizationFailureHandler =
			OAuth2ClientHttpRequestInterceptor.authorizationFailureHandler(authorizedClientService);
		requestInterceptor.setAuthorizationFailureHandler(authorizationFailureHandler);

		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager,
			authorizedClientService: OAuth2AuthorizedClientService): RestClient {

		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)

		val authorizationFailureHandler = OAuth2ClientHttpRequestInterceptor
			.authorizationFailureHandler(authorizedClientService)
		requestInterceptor.setAuthorizationFailureHandler(authorizationFailureHandler)

		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

}
----
=====

[[oauth2-client-rest-client-interface]]
=== HTTP Service Clients

Hỗ trợ OAuth của Spring Security tích hợp với xref:features/integrations/rest/http-service-client.adoc[].

[[oauth2-client-web-client]]
== [[oauth2Client-webclient-servlet]]WebClient integration cho môi trường Servlet

OAuth 2.0 Client support tích hợp với `WebClient` bằng `ExchangeFilterFunction`.

`ServletOAuth2AuthorizedClientExchangeFilterFunction` cung cấp mechanism để request các protected resource bằng cách sử dụng `OAuth2AuthorizedClient` và include `OAuth2AccessToken` liên kết vào request dưới dạng Bearer Token.
Nó trực tiếp sử dụng xref:servlet/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[`OAuth2AuthorizedClientManager`] và do đó kế thừa các capability sau:

* Một `OAuth2AccessToken` được request nếu client chưa được authorize.
** `authorization_code`: Kích hoạt redirect Authorization Request để bắt đầu flow.
** `client_credentials`: access token được lấy trực tiếp từ Token Endpoint.
* Nếu `OAuth2AccessToken` đã expired, nó sẽ được refresh (hoặc renew) nếu có `OAuth2AuthorizedClientProvider` để thực hiện authorization

Code sau minh họa cách configure `WebClient` với OAuth 2.0 Client support:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	return WebClient.builder()
			.apply(oauth2Client.oauth2Configuration())
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager?): WebClient {
    val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    return WebClient.builder()
            .apply(oauth2Client.oauth2Configuration())
            .build()
}
----
======

[[oauth2-client-web-client-authorized-client]]
=== Cung cấp Authorized Client

`ServletOAuth2AuthorizedClientExchangeFilterFunction` xác định client cần sử dụng (cho một request) bằng cách resolve `OAuth2AuthorizedClient` từ `ClientRequest.attributes()` (request attributes).

Code sau minh họa cách set một `OAuth2AuthorizedClient` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
	String resourceUri = ...

	String body = webClient
			.get()
			.uri(resourceUri)
			.attributes(oauth2AuthorizedClient(authorizedClient))   <1>
			.retrieve()
			.bodyToMono(String.class)
			.block();

	...

	return "index";
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): String {
    val resourceUri: String = ...
    val body: String = webClient
            .get()
            .uri(resourceUri)
            .attributes(oauth2AuthorizedClient(authorizedClient)) <1>
            .retrieve()
            .bodyToMono()
            .block()

    ...

    return "index"
}
----
======
<1> `oauth2AuthorizedClient()` là một method `static` trong `ServletOAuth2AuthorizedClientExchangeFilterFunction`.

Code sau minh họa cách set `ClientRegistration.getRegistrationId()` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String index() {
	String resourceUri = ...

	String body = webClient
			.get()
			.uri(resourceUri)
			.attributes(clientRegistrationId("okta"))   <1>
			.retrieve()
			.bodyToMono(String.class)
			.block();

	...

	return "index";
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(): String {
    val resourceUri: String = ...

    val body: String = webClient
            .get()
            .uri(resourceUri)
            .attributes(clientRegistrationId("okta"))  <1>
            .retrieve()
            .bodyToMono()
            .block()

    ...

    return "index"
}
----
======
<1> `clientRegistrationId()` là một method `static` trong `ServletOAuth2AuthorizedClientExchangeFilterFunction`.

Code sau minh họa cách set một `Authentication` làm request attribute:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String index() {
	String resourceUri = ...

	Authentication anonymousAuthentication = new AnonymousAuthenticationToken(
			"anonymous", "anonymousUser", AuthorityUtils.createAuthorityList("ROLE_ANONYMOUS"));
	String body = webClient
			.get()
			.uri(resourceUri)
			.attributes(authentication(anonymousAuthentication))   <1>
			.retrieve()
			.bodyToMono(String.class)
			.block();

	...

	return "index";
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(): String {
    val resourceUri: String = ...

    val anonymousAuthentication: Authentication = AnonymousAuthenticationToken(
            "anonymous", "anonymousUser", AuthorityUtils.createAuthorityList("ROLE_ANONYMOUS"))
    val body: String = webClient
            .get()
            .uri(resourceUri)
            .attributes(authentication(anonymousAuthentication))  <1>
            .retrieve()
            .bodyToMono()
            .block()

    ...

    return "index"
}
----
======
<1> `authentication()` là một method `static` trong `ServletOAuth2AuthorizedClientExchangeFilterFunction`.

[WARNING]
====
Bạn nên thận trọng với tính năng này vì tất cả HTTP request sẽ nhận một access token gắn với principal đã cung cấp.
====

[[oauth2-client-web-client-default-authorized-client]]
=== Thiết lập Authorized Client mặc định

Nếu cả `OAuth2AuthorizedClient` và `ClientRegistration.getRegistrationId()` đều không được cung cấp dưới dạng request attribute, `ServletOAuth2AuthorizedClientExchangeFilterFunction` có thể xác định client _default_ cần sử dụng tùy theo configuration của nó.

Nếu `setDefaultOAuth2AuthorizedClient(true)` được configure và user đã authenticated bằng `HttpSecurity.oauth2Login()`, `OAuth2AccessToken` liên kết với `OAuth2AuthenticationToken` hiện tại sẽ được sử dụng.

Code sau minh họa configuration cụ thể:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultOAuth2AuthorizedClient(true);
	return WebClient.builder()
			.apply(oauth2Client.oauth2Configuration())
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager?): WebClient {
    val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultOAuth2AuthorizedClient(true)
    return WebClient.builder()
            .apply(oauth2Client.oauth2Configuration())
            .build()
}
----
======

[WARNING]
====
Hãy thận trọng với tính năng này vì tất cả HTTP request đều nhận access token.
====

Ngoài ra, nếu `setDefaultClientRegistrationId("okta")` được configure với một `ClientRegistration` hợp lệ, `OAuth2AccessToken` liên kết với `OAuth2AuthorizedClient` sẽ được sử dụng.

Code sau minh họa configuration cụ thể:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultClientRegistrationId("okta");
	return WebClient.builder()
			.apply(oauth2Client.oauth2Configuration())
			.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager?): WebClient {
    val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultClientRegistrationId("okta")
    return WebClient.builder()
            .apply(oauth2Client.oauth2Configuration())
            .build()
}
----
======

[WARNING]
====
Hãy thận trọng với tính năng này vì tất cả HTTP request đều nhận access token.
====
