[[oauth2-client-authorization-grants]]
= [[oauth2Client-auth-grant-support]]Hỗ trợ Authorization Grant

Phần này mô tả khả năng hỗ trợ authorization grant của Spring Security.

[[oauth2-client-authorization-code]]
== [[oauth2Client-auth-code-grant]]Authorization Code

[NOTE]
====
Xem OAuth 2.0 Authorization Framework để biết thêm chi tiết về grant https://tools.ietf.org/html/rfc6749#section-1.3.1[Authorization Code].
====

[[oauth2-client-authorization-code-authorization]]
=== Nhận Authorization

[NOTE]
====
Xem protocol flow https://tools.ietf.org/html/rfc6749#section-4.1.1[Authorization Request/Response] cho grant Authorization Code.
====

[[oauth2-client-authorization-code-authorization-request]]
=== Khởi tạo Authorization Request

`OAuth2AuthorizationRequestRedirectFilter` sử dụng `OAuth2AuthorizationRequestResolver` để resolve một `OAuth2AuthorizationRequest` và khởi tạo flow grant Authorization Code bằng cách redirect user-agent của end-user đến Authorization Endpoint của Authorization Server.

Vai trò chính của `OAuth2AuthorizationRequestResolver` là resolve một `OAuth2AuthorizationRequest` từ web request được cung cấp.
Implementation mặc định `DefaultOAuth2AuthorizationRequestResolver` khớp với path mặc định `+/oauth2/authorization/{registrationId}+`, trích xuất `registrationId` và dùng nó để xây dựng `OAuth2AuthorizationRequest` cho `ClientRegistration` tương ứng.

Hãy xem các property Spring Boot sau cho một registration của OAuth 2.0 Client:

[source,yaml,attrs="-attributes"]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/okta"
            scope: read, write
        provider:
          okta:
            authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

Với các property trước đó, request có base path `/oauth2/authorization/okta` khởi tạo redirect Authorization Request bởi `OAuth2AuthorizationRequestRedirectFilter` và cuối cùng bắt đầu flow grant Authorization Code.

[NOTE]
====
`AuthorizationCodeOAuth2AuthorizedClientProvider` là một implementation của `OAuth2AuthorizedClientProvider` cho grant Authorization Code,
đồng thời cũng khởi tạo redirect Authorization Request bởi `OAuth2AuthorizationRequestRedirectFilter`.
====

Nếu OAuth 2.0 Client là https://tools.ietf.org/html/rfc6749#section-2.1[Public Client], hãy cấu hình registration của OAuth 2.0 Client như sau:

[source,yaml,attrs="-attributes"]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/okta"
            # ...
----

Public Client được hỗ trợ bằng cách sử dụng https://tools.ietf.org/html/rfc7636[Proof Key for Code Exchange] (PKCE).
Nếu client đang chạy trong môi trường không đáng tin cậy (chẳng hạn native application hoặc web browser-based application) và do đó không thể duy trì tính bảo mật của credentials, PKCE sẽ tự động được sử dụng khi các điều kiện sau đúng:

. `client-secret` bị bỏ qua (hoặc rỗng)
. `client-authentication-method` được đặt thành `none` (`ClientAuthenticationMethod.NONE`)

hoặc

. Khi `ClientRegistration.clientSettings.requireProofKey` là `true` (trong trường hợp này `ClientRegistration.authorizationGrantType` phải là `authorization_code`)


[TIP]
====
Nếu OAuth 2.0 Provider không hỗ trợ PKCE cho https://tools.ietf.org/html/rfc6749#section-2.1[Confidential Clients], bạn cần vô hiệu hóa PKCE bằng cách đặt `ClientRegistration.clientSettings.requireProofKey` thành `false`.
====

[[oauth2-client-authorization-code-redirect-uri]]
[[oauth2Client-auth-code-redirect-uri]]`DefaultOAuth2AuthorizationRequestResolver` cũng hỗ trợ các biến template `URI` cho `redirect-uri` bằng cách sử dụng `UriComponentsBuilder`.

Cấu hình sau sử dụng tất cả biến template `URI` được hỗ trợ:

[source,yaml,attrs="-attributes"]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            # ...
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/authorized/{registrationId}"
            # ...
----

[NOTE]
====
`+{baseUrl}+` được resolve thành `+{baseScheme}://{baseHost}{basePort}{basePath}+`
====

Cấu hình `redirect-uri` bằng các biến template `URI` đặc biệt hữu ích khi OAuth 2.0 Client chạy phía sau xref:features/exploits/http.adoc#http-proxy-server[Proxy Server].
Việc này đảm bảo các header `X-Forwarded-*` được sử dụng khi mở rộng `redirect-uri`.

[[oauth2-client-authorization-code-authorization-request-resolver]]
=== Tùy chỉnh Authorization Request

Một trong các trường hợp sử dụng chính mà `OAuth2AuthorizationRequestResolver` có thể đáp ứng là tùy chỉnh Authorization Request bằng các parameter bổ sung ngoài những parameter tiêu chuẩn được định nghĩa trong OAuth 2.0 Authorization Framework.

Ví dụ, OpenID Connect định nghĩa các request parameter OAuth 2.0 bổ sung cho https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest[Authorization Code Flow], bằng cách mở rộng các parameter tiêu chuẩn được định nghĩa trong https://tools.ietf.org/html/rfc6749#section-4.1.1[OAuth 2.0 Authorization Framework].
Một trong các parameter mở rộng đó là parameter `prompt`.

[NOTE]
====
Parameter `prompt` là tùy chọn. Giá trị của parameter này là danh sách các chuỗi ASCII được phân tách bằng dấu cách và phân biệt chữ hoa chữ thường, chỉ định liệu Authorization Server có yêu cầu End-User re-authentication và consent hay không. Các giá trị được định nghĩa là: `none`, `login`, `consent` và `select_account`.
====

Ví dụ sau cho thấy cách cấu hình `DefaultOAuth2AuthorizationRequestResolver` với một `Consumer<OAuth2AuthorizationRequest.Builder>` để tùy chỉnh Authorization Request cho `oauth2Login()`, bằng cách thêm request parameter `prompt=consent`.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2LoginSecurityConfig {

	@Autowired
	private ClientRegistrationRepository clientRegistrationRepository;

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login((oauth2) -> oauth2
				.authorizationEndpoint((authorization) -> authorization
					.authorizationRequestResolver(
						authorizationRequestResolver(this.clientRegistrationRepository)
					)
				)
			);
		return http.build();
	}

	private OAuth2AuthorizationRequestResolver authorizationRequestResolver(
			ClientRegistrationRepository clientRegistrationRepository) {

		DefaultOAuth2AuthorizationRequestResolver authorizationRequestResolver =
				new DefaultOAuth2AuthorizationRequestResolver(
						clientRegistrationRepository, "/oauth2/authorization");
		authorizationRequestResolver.setAuthorizationRequestCustomizer(
				authorizationRequestCustomizer());

		return  authorizationRequestResolver;
	}

	private Consumer<OAuth2AuthorizationRequest.Builder> authorizationRequestCustomizer() {
		return customizer -> customizer
					.additionalParameters((params) -> params.put("prompt", "consent"));
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class SecurityConfig {

    @Autowired
    private lateinit var customClientRegistrationRepository: ClientRegistrationRepository

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeHttpRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login {
                authorizationEndpoint {
                    authorizationRequestResolver = authorizationRequestResolver(customClientRegistrationRepository)
                }
            }
        }
        return http.build()
    }

    private fun authorizationRequestResolver(
            clientRegistrationRepository: ClientRegistrationRepository?): OAuth2AuthorizationRequestResolver {
        val authorizationRequestResolver = DefaultOAuth2AuthorizationRequestResolver(
                clientRegistrationRepository, "/oauth2/authorization")
        authorizationRequestResolver.setAuthorizationRequestCustomizer(
                authorizationRequestCustomizer())
        return authorizationRequestResolver
    }

    private fun authorizationRequestCustomizer(): Consumer<OAuth2AuthorizationRequest.Builder> {
        return Consumer { customizer ->
            customizer
                    .additionalParameters { params -> params["prompt"] = "consent" }
        }
    }
}
----
======

Trong use case đơn giản, khi request parameter bổ sung luôn giống nhau đối với một provider cụ thể, bạn có thể thêm trực tiếp parameter đó vào property `authorization-uri`.

Ví dụ, nếu giá trị của request parameter `prompt` luôn là `consent` đối với provider `okta`, bạn có thể cấu hình như sau:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize?prompt=consent
----

Ví dụ trước đó minh họa trường hợp sử dụng phổ biến là thêm một parameter tùy chỉnh bên cạnh các parameter tiêu chuẩn.
Ngoài ra, nếu yêu cầu của bạn phức tạp hơn, bạn có thể toàn quyền xây dựng Authorization Request URI bằng cách override property `OAuth2AuthorizationRequest.authorizationRequestUri`.

[TIP]
====
`OAuth2AuthorizationRequest.Builder.build()` xây dựng `OAuth2AuthorizationRequest.authorizationRequestUri`, đại diện cho Authorization Request URI bao gồm tất cả query parameter bằng format `application/x-www-form-urlencoded`.
====

Cấu hình mẫu sau là một biến thể của `authorizationRequestCustomizer()` trong ví dụ trước đó và thay vào đó override property `OAuth2AuthorizationRequest.authorizationRequestUri`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
private Consumer<OAuth2AuthorizationRequest.Builder> authorizationRequestCustomizer() {
	return customizer -> customizer
				.authorizationRequestUri((uriBuilder) -> uriBuilder
					.queryParam("prompt", "consent").build());
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
private fun authorizationRequestCustomizer(): Consumer<OAuth2AuthorizationRequest.Builder> {
    return Consumer { customizer: OAuth2AuthorizationRequest.Builder ->
        customizer
                .authorizationRequestUri { uriBuilder: UriBuilder ->
                    uriBuilder
                            .queryParam("prompt", "consent").build()
                }
    }
}
----
======

[[oauth2-client-authorization-code-authorization-request-repository]]
=== Lưu Authorization Request

`AuthorizationRequestRepository` chịu trách nhiệm persist `OAuth2AuthorizationRequest` từ lúc Authorization Request được khởi tạo cho đến khi nhận được Authorization Response (callback).

[TIP]
====
`OAuth2AuthorizationRequest` được dùng để correlate và validate Authorization Response.
====

Implementation mặc định của `AuthorizationRequestRepository` là `HttpSessionOAuth2AuthorizationRequestRepository`, lưu `OAuth2AuthorizationRequest` trong `HttpSession`.

Nếu bạn có implementation tùy chỉnh của `AuthorizationRequestRepository`, bạn có thể cấu hình như sau:

.Cấu hình AuthorizationRequestRepository
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.oauth2Client((oauth2) -> oauth2
				.authorizationCodeGrant((codeGrant) -> codeGrant
					.authorizationRequestRepository(this.authorizationRequestRepository())
					// ...
				)
			)
            .oauth2Login((oauth2) -> oauth2
                .authorizationEndpoint((endpoint) -> endpoint
                    .authorizationRequestRepository(this.authorizationRequestRepository())
                    // ...
                )
            );
			return http.build();
	}

    @Bean
    public AuthorizationRequestRepository<OAuth2AuthorizationRequest> authorizationRequestRepository() {
        return new CustomOAuth2AuthorizationRequestRepository();
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            oauth2Client {
                authorizationCodeGrant {
                    authorizationRequestRepository = authorizationRequestRepository()
                }
            }
        }
        return http.build()
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
	<oauth2-client>
		<authorization-code-grant authorization-request-repository-ref="authorizationRequestRepository"/>
	</oauth2-client>
</http>
----
======

[[oauth2-client-authorization-code-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Xem protocol flow https://tools.ietf.org/html/rfc6749#section-4.1.3[Access Token Request/Response] cho grant Authorization Code.
====

Implementation mặc định của `OAuth2AccessTokenResponseClient` cho grant Authorization Code là `RestClientAuthorizationCodeTokenResponseClient`, sử dụng một instance `RestClient` để exchange authorization code lấy access token tại Token Endpoint của Authorization Server.

:section-id: authorization-code
:grant-type: Authorization Code
:class-name: RestClientAuthorizationCodeTokenResponseClient
:grant-request: OAuth2AuthorizationCodeGrantRequest
:leveloffset: +1
include::partial$servlet/oauth2/client/rest-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-authorization-code-access-token-response-client-dsl]]
=== Tùy chỉnh bằng DSL

Dù bạn tùy chỉnh `{class-name}` hay cung cấp implementation riêng của `OAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng DSL (thay cho <<oauth2-client-authorization-code-access-token-response-client-bean,đăng ký một bean>>) như sau:

.Cấu hình Access Token Response bằng DSL
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.oauth2Client((oauth2) -> oauth2
				.authorizationCodeGrant((codeGrant) -> codeGrant
					.accessTokenResponseClient(this.accessTokenResponseClient())
					// ...
				)
			);
		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            oauth2Client {
                authorizationCodeGrant {
                    accessTokenResponseClient = accessTokenResponseClient()
                }
            }
        }
        return http.build()
    }
}
----

Xml::
+
[source,xml,role="secondary"]
----
<http>
	<oauth2-client>
		<authorization-code-grant access-token-response-client-ref="accessTokenResponseClient"/>
	</oauth2-client>
</http>
----
======

[[oauth2-client-refresh-token]]
== [[oauth2Client-refresh-token-grant]]Refresh Token

[NOTE]
====
Xem OAuth 2.0 Authorization Framework để biết thêm chi tiết về https://tools.ietf.org/html/rfc6749#section-1.5[Refresh Token].
====

[[oauth2-client-refresh-token-access-token]]
=== Làm mới Access Token

[NOTE]
====
Xem protocol flow https://tools.ietf.org/html/rfc6749#section-6[Access Token Request/Response] cho grant Refresh Token.
====

Implementation mặc định của `OAuth2AccessTokenResponseClient` cho grant Refresh Token là `RestClientRefreshTokenTokenResponseClient`, sử dụng một instance `RestClient` để lấy access token tại Token Endpoint của Authorization Server.

:section-id: refresh-token
:grant-type: Refresh Token
:class-name: RestClientRefreshTokenTokenResponseClient
:grant-request: OAuth2RefreshTokenGrantRequest
:leveloffset: +1
include::partial$servlet/oauth2/client/rest-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-refresh-token-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `RestClientRefreshTokenTokenResponseClient` hay cung cấp implementation riêng của `OAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `OAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-refresh-token-access-token-response-client-bean,đăng ký một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Customize
OAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> refreshTokenTokenResponseClient = ...

OAuth2AuthorizedClientProvider authorizedClientProvider =
		OAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken((configurer) -> configurer.accessTokenResponseClient(refreshTokenTokenResponseClient))
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Customize
val refreshTokenTokenResponseClient: OAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> = ...

val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
        .authorizationCode()
        .refreshToken { it.accessTokenResponseClient(refreshTokenTokenResponseClient) }
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[NOTE]
====
`OAuth2AuthorizedClientProviderBuilder.builder().refreshToken()` cấu hình một `RefreshTokenOAuth2AuthorizedClientProvider`,
là implementation của `OAuth2AuthorizedClientProvider` cho grant Refresh Token.
====

Với grant type `authorization_code`, Access Token Response có thể tùy chọn trả về `OAuth2RefreshToken`.
Nếu `OAuth2AuthorizedClient.getRefreshToken()` khả dụng và `OAuth2AuthorizedClient.getAccessToken()` đã hết hạn, access token sẽ được `RefreshTokenOAuth2AuthorizedClientProvider` tự động refresh.

[[oauth2-client-client-credentials]]
== [[oauth2Client-client-creds-grant]]Client Credentials

[NOTE]
====
Vui lòng tham khảo OAuth 2.0 Authorization Framework để biết thêm chi tiết về grant https://tools.ietf.org/html/rfc6749#section-1.3.4[Client Credentials].
====

[[oauth2-client-client-credentials-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Xem protocol flow https://tools.ietf.org/html/rfc6749#section-4.4.2[Access Token Request/Response] cho grant Client Credentials.
====

Implementation mặc định của `OAuth2AccessTokenResponseClient` cho grant Client Credentials là `RestClientClientCredentialsTokenResponseClient`, sử dụng một instance `RestClient` để lấy access token tại Token Endpoint của Authorization Server.

:section-id: client-credentials
:grant-type: Client Credentials
:class-name: RestClientClientCredentialsTokenResponseClient
:grant-request: OAuth2ClientCredentialsGrantRequest
:leveloffset: +1
include::partial$servlet/oauth2/client/rest-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-client-credentials-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `RestClientClientCredentialsTokenResponseClient` hay cung cấp implementation riêng của `OAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `OAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-client-credentials-access-token-response-client-bean,đăng ký một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Customize
OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsTokenResponseClient = ...

OAuth2AuthorizedClientProvider authorizedClientProvider =
		OAuth2AuthorizedClientProviderBuilder.builder()
				.clientCredentials((configurer) -> configurer.accessTokenResponseClient(clientCredentialsTokenResponseClient))
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Customize
val clientCredentialsTokenResponseClient: OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> = ...

val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
        .clientCredentials { it.accessTokenResponseClient(clientCredentialsTokenResponseClient) }
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[NOTE]
====
`OAuth2AuthorizedClientProviderBuilder.builder().clientCredentials()` cấu hình một `ClientCredentialsOAuth2AuthorizedClientProvider`,
là implementation của `OAuth2AuthorizedClientProvider` cho grant Client Credentials.
====

[[oauth2-client-client-credentials-authorized-client-manager]]
=== Sử dụng Access Token

Hãy xem các property Spring Boot sau cho một registration của OAuth 2.0 Client:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: client_credentials
            scope: read, write
        provider:
          okta:
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

Tiếp theo là `@Bean` `OAuth2AuthorizedClientManager`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.clientCredentials()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Với các property và bean trước đó, bạn có thể lấy `OAuth2AccessToken` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private OAuth2AuthorizedClientManager authorizedClientManager;

	@GetMapping("/")
	public String index(Authentication authentication,
						HttpServletRequest servletRequest,
						HttpServletResponse servletResponse) {

		OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
				.principal(authentication)
				.attributes(attrs -> {
					attrs.put(HttpServletRequest.class.getName(), servletRequest);
					attrs.put(HttpServletResponse.class.getName(), servletResponse);
				})
				.build();
		OAuth2AuthorizedClient authorizedClient = this.authorizedClientManager.authorize(authorizeRequest);

		OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

		// ...

		return "index";
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class OAuth2ClientController {

    @Autowired
    private lateinit var authorizedClientManager: OAuth2AuthorizedClientManager

    @GetMapping("/")
    fun index(authentication: Authentication?,
              servletRequest: HttpServletRequest,
              servletResponse: HttpServletResponse): String {
        val authorizeRequest: OAuth2AuthorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
                .principal(authentication)
                .attributes(Consumer { attrs: MutableMap<String, Any> ->
                    attrs[HttpServletRequest::class.java.name] = servletRequest
                    attrs[HttpServletResponse::class.java.name] = servletResponse
                })
                .build()
        val authorizedClient = authorizedClientManager.authorize(authorizeRequest)
        val accessToken: OAuth2AccessToken = authorizedClient.accessToken

        // ...

        return "index"
    }
}
----
======

[NOTE]
====
`HttpServletRequest` và `HttpServletResponse` đều là attribute TÙY CHỌN.
Nếu không được cung cấp, chúng mặc định là `ServletRequestAttributes` bằng cách sử dụng `RequestContextHolder.getRequestAttributes()`.
====

[[oauth2-client-jwt-bearer]]
== JWT Bearer

[NOTE]
====
Vui lòng tham khảo JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grants để biết thêm chi tiết về grant https://datatracker.ietf.org/doc/html/rfc7523[JWT Bearer].
====

[[oauth2-client-jwt-bearer-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Vui lòng tham khảo protocol flow https://datatracker.ietf.org/doc/html/rfc7523#section-2.1[Access Token Request/Response] cho grant JWT Bearer.
====

Implementation mặc định của `OAuth2AccessTokenResponseClient` cho grant JWT Bearer là `RestClientJwtBearerTokenResponseClient`, sử dụng một instance `RestClient` để lấy access token tại Token Endpoint của Authorization Server.

:section-id: jwt-bearer
:grant-type: JWT Bearer
:class-name: RestClientJwtBearerTokenResponseClient
:grant-request: JwtBearerGrantRequest
:leveloffset: +1
include::partial$servlet/oauth2/client/rest-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-jwt-bearer-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `RestClientJwtBearerTokenResponseClient` hay cung cấp implementation riêng của `OAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `OAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-jwt-bearer-access-token-response-client-bean,đăng ký một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Customize
OAuth2AccessTokenResponseClient<JwtBearerGrantRequest> jwtBearerTokenResponseClient = ...

JwtBearerOAuth2AuthorizedClientProvider jwtBearerAuthorizedClientProvider = new JwtBearerOAuth2AuthorizedClientProvider();
jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerTokenResponseClient);

OAuth2AuthorizedClientProvider authorizedClientProvider =
		OAuth2AuthorizedClientProviderBuilder.builder()
				.provider(jwtBearerAuthorizedClientProvider)
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Customize
val jwtBearerTokenResponseClient: OAuth2AccessTokenResponseClient<JwtBearerGrantRequest> = ...

val jwtBearerAuthorizedClientProvider = JwtBearerOAuth2AuthorizedClientProvider()
jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerTokenResponseClient)

val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
        .provider(jwtBearerAuthorizedClientProvider)
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[[oauth2-client-jwt-bearer-authorized-client-manager]]
=== Sử dụng Access Token

Với các property Spring Boot sau đây cho một registration của OAuth 2.0 Client:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: read
        provider:
          okta:
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

...và `@Bean` `OAuth2AuthorizedClientManager`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	JwtBearerOAuth2AuthorizedClientProvider jwtBearerAuthorizedClientProvider =
			new JwtBearerOAuth2AuthorizedClientProvider();

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.provider(jwtBearerAuthorizedClientProvider)
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val jwtBearerAuthorizedClientProvider = JwtBearerOAuth2AuthorizedClientProvider()
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .provider(jwtBearerAuthorizedClientProvider)
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Bạn có thể lấy `OAuth2AccessToken` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RestController
public class OAuth2ResourceServerController {

	@Autowired
	private OAuth2AuthorizedClientManager authorizedClientManager;

	@GetMapping("/resource")
	public String resource(JwtAuthenticationToken jwtAuthentication) {
		OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
				.principal(jwtAuthentication)
				.build();
		OAuth2AuthorizedClient authorizedClient = this.authorizedClientManager.authorize(authorizeRequest);
		OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

		// ...

	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class OAuth2ResourceServerController {

    @Autowired
    private lateinit var authorizedClientManager: OAuth2AuthorizedClientManager

    @GetMapping("/resource")
    fun resource(jwtAuthentication: JwtAuthenticationToken?): String {
        val authorizeRequest: OAuth2AuthorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
                .principal(jwtAuthentication)
                .build()
        val authorizedClient = authorizedClientManager.authorize(authorizeRequest)
        val accessToken: OAuth2AccessToken = authorizedClient.accessToken

        // ...

    }
}
----
======

[NOTE]
====
Theo mặc định, `JwtBearerOAuth2AuthorizedClientProvider` resolve assertion `Jwt` thông qua `OAuth2AuthorizationContext.getPrincipal().getPrincipal()`, do đó ví dụ trước sử dụng `JwtAuthenticationToken`.
====

[TIP]
====
Nếu cần resolve assertion `Jwt` từ một nguồn khác, bạn có thể cung cấp cho `JwtBearerOAuth2AuthorizedClientProvider.setJwtAssertionResolver()` một `Function<OAuth2AuthorizationContext, Jwt>` tùy chỉnh.
====

[[oauth2-client-token-exchange]]
== [[oauth2Client-token-exchange-grant]]Token Exchange

[NOTE]
====
Vui lòng tham khảo OAuth 2.0 Token Exchange để biết thêm chi tiết về grant https://datatracker.ietf.org/doc/html/rfc8693[Token Exchange].
====

[[oauth2-client-token-exchange-access-token]]
=== Yêu cầu Access Token

[NOTE]
====
Vui lòng tham khảo protocol flow https://datatracker.ietf.org/doc/html/rfc8693#section-2[Token Exchange Request and Response] cho grant Token Exchange.
====

Implementation mặc định của `OAuth2AccessTokenResponseClient` cho grant Token Exchange là `RestClientTokenExchangeTokenResponseClient`, sử dụng một instance `RestClient` để lấy access token tại Token Endpoint của Authorization Server.

:section-id: token-exchange
:grant-type: Token Exchange
:class-name: RestClientTokenExchangeTokenResponseClient
:grant-request: TokenExchangeGrantRequest
:leveloffset: +1
include::partial$servlet/oauth2/client/rest-client-access-token-response-client.adoc[]

:leveloffset: -1

[[oauth2-client-token-exchange-authorized-client-provider-builder]]
=== Tùy chỉnh bằng Builder

Dù bạn tùy chỉnh `RestClientTokenExchangeTokenResponseClient` hay cung cấp implementation riêng của `OAuth2AccessTokenResponseClient`, bạn có thể cấu hình bằng `OAuth2AuthorizedClientProviderBuilder` (thay cho <<oauth2-client-token-exchange-access-token-response-client-bean,đăng ký một bean>>) như sau:

.Cấu hình Access Token Response bằng Builder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Customize
OAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> tokenExchangeTokenResponseClient = ...

TokenExchangeOAuth2AuthorizedClientProvider tokenExchangeAuthorizedClientProvider = new TokenExchangeOAuth2AuthorizedClientProvider();
tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeTokenResponseClient);

OAuth2AuthorizedClientProvider authorizedClientProvider =
		OAuth2AuthorizedClientProviderBuilder.builder()
				.provider(tokenExchangeAuthorizedClientProvider)
				.build();

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Customize
val tokenExchangeTokenResponseClient: OAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> = ...

val tokenExchangeAuthorizedClientProvider = TokenExchangeOAuth2AuthorizedClientProvider()
tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeTokenResponseClient)

val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
        .provider(tokenExchangeAuthorizedClientProvider)
        .build()

// ...

authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
----
======

[[oauth2-client-token-exchange-authorized-client-manager]]
=== [[token-exchange-grant-access-token]]Sử dụng Access Token

Với các property Spring Boot sau đây cho một registration của OAuth 2.0 Client:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            scope: read
        provider:
          okta:
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
----

...và `@Bean` `OAuth2AuthorizedClientManager`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	TokenExchangeOAuth2AuthorizedClientProvider tokenExchangeAuthorizedClientProvider =
			new TokenExchangeOAuth2AuthorizedClientProvider();

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.provider(tokenExchangeAuthorizedClientProvider)
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val tokenExchangeAuthorizedClientProvider = TokenExchangeOAuth2AuthorizedClientProvider()
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .provider(tokenExchangeAuthorizedClientProvider)
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Bạn có thể lấy `OAuth2AccessToken` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RestController
public class OAuth2ResourceServerController {

	@Autowired
	private OAuth2AuthorizedClientManager authorizedClientManager;

	@GetMapping("/resource")
	public String resource(JwtAuthenticationToken jwtAuthentication) {
		OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
				.principal(jwtAuthentication)
				.build();
		OAuth2AuthorizedClient authorizedClient = this.authorizedClientManager.authorize(authorizeRequest);
		OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

		// ...

	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class OAuth2ResourceServerController {

    @Autowired
    private lateinit var authorizedClientManager: OAuth2AuthorizedClientManager

    @GetMapping("/resource")
    fun resource(jwtAuthentication: JwtAuthenticationToken?): String {
        val authorizeRequest: OAuth2AuthorizeRequest = OAuth2AuthorizeRequest.withClientRegistrationId("okta")
                .principal(jwtAuthentication)
                .build()
        val authorizedClient = authorizedClientManager.authorize(authorizeRequest)
        val accessToken: OAuth2AccessToken = authorizedClient.accessToken

        // ...

    }
}
----
======

[NOTE]
====
Theo mặc định, `TokenExchangeOAuth2AuthorizedClientProvider` resolve subject token (dưới dạng một `OAuth2Token`) thông qua `OAuth2AuthorizationContext.getPrincipal().getPrincipal()`, do đó ví dụ trước sử dụng `JwtAuthenticationToken`.
Actor token không được resolve theo mặc định.
====

[TIP]
====
Nếu cần resolve subject token từ một nguồn khác, bạn có thể cung cấp cho `TokenExchangeOAuth2AuthorizedClientProvider.setSubjectTokenResolver()` một `Function<OAuth2AuthorizationContext, OAuth2Token>` tùy chỉnh.
====

[TIP]
====
Nếu cần resolve actor token, bạn có thể cung cấp cho `TokenExchangeOAuth2AuthorizedClientProvider.setActorTokenResolver()` một `Function<OAuth2AuthorizationContext, OAuth2Token>` tùy chỉnh.
====
