[[oauth2Client-core-interface-class]]
= Interface và Class cốt lõi

Phần này mô tả các interface và class cốt lõi của OAuth2 mà Spring Security cung cấp.

[[oauth2Client-client-registration]]
== ClientRegistration

`ClientRegistration` là biểu diễn của một client được đăng ký với một Provider OAuth 2.0 hoặc OpenID Connect 1.0.

Một object `ClientRegistration` chứa các thông tin như client ID, client secret, loại authorization grant, redirect URI, scope, authorization URI, token URI và các chi tiết khác.

`ClientRegistration` và các thuộc tính của nó được định nghĩa như sau:

[source,java]
----
public final class ClientRegistration {
	private String registrationId;	<1>
	private String clientId;	<2>
	private String clientSecret;	<3>
	private ClientAuthenticationMethod clientAuthenticationMethod;	<4>
	private AuthorizationGrantType authorizationGrantType;	<5>
	private String redirectUri;	<6>
	private Set<String> scopes;	<7>
	private ProviderDetails providerDetails;
	private String clientName;	<8>

	public class ProviderDetails {
		private String authorizationUri;	<9>
		private String tokenUri;	<10>
		private UserInfoEndpoint userInfoEndpoint;
		private String jwkSetUri;	<11>
		private String issuerUri;	<12>
        private Map<String, Object> configurationMetadata;  <13>

		public class UserInfoEndpoint {
			private String uri;	<14>
            private AuthenticationMethod authenticationMethod;  <15>
			private String userNameAttributeName;	<16>

		}
	}

	public static final class ClientSettings {
		private boolean requireProofKey; // <17>
	}
}
----
<1> `registrationId`: ID xác định duy nhất `ClientRegistration`.
<2> `clientId`: Mã định danh client.
<3> `clientSecret`: Client secret.
<4> `clientAuthenticationMethod`: Phương thức được dùng để thực hiện authentication cho Client với Provider.
Các giá trị được hỗ trợ là *client_secret_basic*, *client_secret_post*, *private_key_jwt*, *client_secret_jwt* và *none* https://tools.ietf.org/html/rfc6749#section-2.1[(các client public)].
<5> `authorizationGrantType`: OAuth 2.0 Authorization Framework định nghĩa bốn loại https://tools.ietf.org/html/rfc6749#section-1.3[Authorization Grant].
 Các giá trị được hỗ trợ là `authorization_code`, `client_credentials` và extension grant type `urn:ietf:params:oauth:grant-type:jwt-bearer`.
<6> `redirectUri`: Redirect URI đã đăng ký của client mà _Authorization Server_ dùng để redirect user-agent của end-user
  đến đó sau khi end-user đã authentication và cấp quyền truy cập cho client.
<7> `scopes`: Các scope được client yêu cầu trong flow Authorization Request, chẳng hạn như openid, email hoặc profile.
<8> `clientName`: Tên mô tả được dùng cho client.
Tên này có thể được sử dụng trong một số tình huống, chẳng hạn khi hiển thị tên client trên trang đăng nhập được tạo tự động.
<9> `authorizationUri`: URI của Authorization Endpoint dành cho Authorization Server.
<10> `tokenUri`: URI của Token Endpoint dành cho Authorization Server.
<11> `jwkSetUri`: URI được dùng để lấy https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] Set từ Authorization Server,
chứa các khóa mật mã được dùng để xác minh https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)] của ID Token và (tùy chọn) UserInfo Response.
<12> `issuerUri`: Trả về URI định danh issuer của Provider OpenID Connect 1.0 hoặc OAuth 2.0 Authorization Server.
<13> `configurationMetadata`: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Thông tin cấu hình OpenID Provider].
Thông tin này chỉ khả dụng khi property Spring Boot `spring.security.oauth2.client.provider.[providerId].issuerUri` được cấu hình.
<14> `(userInfoEndpoint)uri`: URI của UserInfo Endpoint được dùng để truy cập các claim và thuộc tính của end-user đã authentication.
<15> `(userInfoEndpoint)authenticationMethod`: Phương thức authentication được dùng khi gửi access token đến UserInfo Endpoint.
Các giá trị được hỗ trợ là *header*, *form* và *query*.
<16> `userNameAttributeName`: Tên của thuộc tính được trả về trong UserInfo Response, tham chiếu đến Name hoặc Identifier của end-user.
<17> [[oauth2Client-client-registration-requireProofKey]]`requireProofKey`: Nếu `true` hoặc nếu `clientAuthenticationMethod` là `none` thì PKCE sẽ được bật. Mặc định là `true` cho grant type `authorization_code` và `false` cho các grant type khác.

Bạn có thể cấu hình ban đầu một `ClientRegistration` bằng cách sử dụng cơ chế discovery của https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[endpoint cấu hình] của OpenID Connect Provider hoặc https://tools.ietf.org/html/rfc8414#section-3[endpoint metadata] của Authorization Server.

`ClientRegistrations` cung cấp các method tiện ích để cấu hình `ClientRegistration` theo cách này, như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
ClientRegistration clientRegistration =
    ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val clientRegistration = ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build()
----
======

Đoạn code trước đó lần lượt truy vấn `https://idp.example.com/issuer/.well-known/openid-configuration`, `https://idp.example.com/.well-known/openid-configuration/issuer` và `https://idp.example.com/.well-known/oauth-authorization-server/issuer`, rồi dừng ở endpoint đầu tiên trả về response 200.

Ngoài ra, bạn có thể sử dụng `ClientRegistrations.fromOidcIssuerLocation()` để chỉ query Configuration endpoint của OpenID Connect Provider.

[[oauth2Client-client-registration-repo]]
== ClientRegistrationRepository

`ClientRegistrationRepository` đóng vai trò repository cho các `ClientRegistration` của OAuth 2.0 / OpenID Connect 1.0.

[NOTE]
====
Thông tin đăng ký client cuối cùng được lưu trữ và sở hữu bởi Authorization Server tương ứng.
Repository này cho phép lấy một tập con của thông tin đăng ký client chính được lưu trữ với Authorization Server.
====

Auto-configuration của Spring Boot bind từng property dưới `spring.security.oauth2.client.registration._[registrationId]_` vào một instance `ClientRegistration`, sau đó tập hợp các instance `ClientRegistration` vào một `ClientRegistrationRepository`.

[NOTE]
====
Implementation mặc định của `ClientRegistrationRepository` là `InMemoryClientRegistrationRepository`.
====

Auto-configuration cũng đăng ký `ClientRegistrationRepository` dưới dạng `@Bean` trong `ApplicationContext` để application có thể sử dụng nó cho dependency injection nếu cần.

Listing sau đây minh họa một ví dụ:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ClientRegistrationRepository clientRegistrationRepository;

	@GetMapping("/")
	public String index() {
		ClientRegistration oktaRegistration =
			this.clientRegistrationRepository.findByRegistrationId("okta");

		...

		return "index";
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var clientRegistrationRepository: ClientRegistrationRepository

    @GetMapping("/")
    fun index(): String {
        val oktaRegistration =
                this.clientRegistrationRepository.findByRegistrationId("okta")

        //...

        return "index";
    }
}
----
======

[[oauth2Client-authorized-client]]
== OAuth2AuthorizedClient

`OAuth2AuthorizedClient` là biểu diễn của một Authorized Client.
Một client được xem là đã hoàn tất authorization khi end-user (Resource Owner) đã cấp quyền cho client truy cập các protected resource của mình.

`OAuth2AuthorizedClient` dùng để liên kết một `OAuth2AccessToken` (và `OAuth2RefreshToken` tùy chọn) với một `ClientRegistration` (client) và resource owner, là end-user `Principal` đã cấp quyền.


[[oauth2Client-authorized-repo-service]]
== OAuth2AuthorizedClientRepository và OAuth2AuthorizedClientService

`OAuth2AuthorizedClientRepository` chịu trách nhiệm lưu trữ các `OAuth2AuthorizedClient` giữa các web request, trong khi vai trò chính của `OAuth2AuthorizedClientService` là quản lý các `OAuth2AuthorizedClient` ở cấp application.

Từ góc nhìn của developer, `OAuth2AuthorizedClientRepository` hoặc `OAuth2AuthorizedClientService` cho phép tra cứu `OAuth2AccessToken` liên kết với một client để token này có thể được dùng khởi tạo request đến protected resource.

Listing sau đây minh họa một ví dụ:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

    @Autowired
    private OAuth2AuthorizedClientService authorizedClientService;

    @GetMapping("/")
    public String index(Authentication authentication) {
        OAuth2AuthorizedClient authorizedClient =
            this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName());

        OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

        ...

        return "index";
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var authorizedClientService: OAuth2AuthorizedClientService

    @GetMapping("/")
    fun index(authentication: Authentication): String {
        val authorizedClient: OAuth2AuthorizedClient =
            this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName());
        val accessToken = authorizedClient.accessToken

        ...

        return "index";
    }
}
----
======

[NOTE]
====
Auto-configuration của Spring Boot đăng ký một `OAuth2AuthorizedClientRepository` hoặc `OAuth2AuthorizedClientService` `@Bean` trong `ApplicationContext`.
Tuy nhiên, application có thể override và đăng ký một `OAuth2AuthorizedClientRepository` hoặc `OAuth2AuthorizedClientService` `@Bean` tùy chỉnh.
====

Implementation mặc định của `OAuth2AuthorizedClientService` là `InMemoryOAuth2AuthorizedClientService`, lưu trữ các object `OAuth2AuthorizedClient` trong memory.

Ngoài ra, bạn có thể cấu hình implementation JDBC `JdbcOAuth2AuthorizedClientService` để lưu trữ các instance `OAuth2AuthorizedClient` trong database.

[NOTE]
====
`JdbcOAuth2AuthorizedClientService` phụ thuộc vào định nghĩa bảng được mô tả trong xref:servlet/appendix/database-schema.adoc#dbschema-oauth2-client[ Schema Client OAuth 2.0].
====


[[oauth2Client-authorized-manager-provider]]
== OAuth2AuthorizedClientManager và OAuth2AuthorizedClientProvider

`OAuth2AuthorizedClientManager` chịu trách nhiệm quản lý tổng thể các `OAuth2AuthorizedClient`.

Các trách nhiệm chính bao gồm:

* Thực hiện authorization (hoặc re-authorization) cho một OAuth 2.0 Client bằng cách sử dụng `OAuth2AuthorizedClientProvider`.
* Ủy quyền việc lưu trữ một `OAuth2AuthorizedClient`, thường bằng cách sử dụng `OAuth2AuthorizedClientService` hoặc `OAuth2AuthorizedClientRepository`.
* Ủy quyền cho `OAuth2AuthorizationSuccessHandler` khi OAuth 2.0 Client được authorization (hoặc re-authorization) thành công.
* Ủy quyền cho `OAuth2AuthorizationFailureHandler` khi OAuth 2.0 Client không thể authorization (hoặc re-authorization).

Một `OAuth2AuthorizedClientProvider` triển khai một strategy để authorization (hoặc re-authorization) cho một OAuth 2.0 Client.
Các implementation thường triển khai một loại authorization grant, chẳng hạn như `authorization_code`, `client_credentials` và các loại khác.

Implementation mặc định của `OAuth2AuthorizedClientManager` là `DefaultOAuth2AuthorizedClientManager`, được liên kết với một `OAuth2AuthorizedClientProvider` có thể hỗ trợ nhiều loại authorization grant bằng một composite dựa trên delegation.
Bạn có thể sử dụng `OAuth2AuthorizedClientProviderBuilder` để cấu hình và xây dựng composite dựa trên delegation.

Đoạn code sau minh họa cách cấu hình và xây dựng một composite `OAuth2AuthorizedClientProvider` hỗ trợ các loại authorization grant `authorization_code`, `refresh_token` và `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======

Khi một lần authorization thành công, `DefaultOAuth2AuthorizedClientManager` ủy quyền cho `OAuth2AuthorizationSuccessHandler`, handler này (theo mặc định) lưu `OAuth2AuthorizedClient` thông qua `OAuth2AuthorizedClientRepository`.
Trong trường hợp re-authorization thất bại (ví dụ refresh token không còn hợp lệ), `OAuth2AuthorizedClient` đã được lưu trước đó sẽ bị xóa khỏi `OAuth2AuthorizedClientRepository` thông qua `RemoveAuthorizedClientOAuth2AuthorizationFailureHandler`.
Bạn có thể tùy chỉnh hành vi mặc định thông qua `setAuthorizationSuccessHandler(OAuth2AuthorizationSuccessHandler)` và `setAuthorizationFailureHandler(OAuth2AuthorizationFailureHandler)`.

`DefaultOAuth2AuthorizedClientManager` cũng được liên kết với một `contextAttributesMapper` có kiểu `Function<OAuth2AuthorizeRequest, Map<String, Object>>`, chịu trách nhiệm ánh xạ các attribute từ `OAuth2AuthorizeRequest` sang một `Map` các attribute được liên kết với `OAuth2AuthorizationContext`.
Điều này hữu ích khi bạn cần cung cấp cho `OAuth2AuthorizedClientProvider` các attribute bắt buộc (được hỗ trợ).

Đoạn code sau minh họa `contextAttributesMapper`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	// Assuming the attributes are supplied as `HttpServletRequest` parameters,
	// map the `HttpServletRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
	authorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

	return authorizedClientManager;
}

private Function<OAuth2AuthorizeRequest, Map<String, Object>> contextAttributesMapper() {
	return authorizeRequest -> {
		Map<String, Object> contextAttributes = Collections.emptyMap();
		HttpServletRequest servletRequest = authorizeRequest.getAttribute(HttpServletRequest.class.getName());
		String param1 = servletRequest.getParameter("param1");
		String param2 = servletRequest.getParameter("param2");
		if (StringUtils.hasText(param1) && StringUtils.hasText(param2)) {
			contextAttributes = new HashMap<>();
			contextAttributes.put("param1", param1);
			contextAttributes.put("param2", param2);
		}
		return contextAttributes;
	};
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

	// Assuming the attributes are supplied as `HttpServletRequest` parameters,
	// map the `HttpServletRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
    authorizedClientManager.setContextAttributesMapper(contextAttributesMapper())
    return authorizedClientManager
}

private fun contextAttributesMapper(): Function<OAuth2AuthorizeRequest, MutableMap<String, Any>> {
    return Function { authorizeRequest ->
        var contextAttributes: MutableMap<String, Any> = mutableMapOf()
        val servletRequest: HttpServletRequest = authorizeRequest.getAttribute(HttpServletRequest::class.java.name)
        val param1: String = servletRequest.getParameter("param1")
        val param2: String = servletRequest.getParameter("param2")
        if (StringUtils.hasText(param1) && StringUtils.hasText(param2)) {
            contextAttributes = hashMapOf()
            contextAttributes["param1"] = param1
            contextAttributes["param2"] = param2
        }
        contextAttributes
    }
}
----
======

`DefaultOAuth2AuthorizedClientManager` được thiết kế để sử dụng _bên trong_ context của một `HttpServletRequest`.
Khi hoạt động _bên ngoài_ context của `HttpServletRequest`, hãy sử dụng `AuthorizedClientServiceOAuth2AuthorizedClientManager` thay thế.

Service application là một use case phổ biến để sử dụng `AuthorizedClientServiceOAuth2AuthorizedClientManager`.
Service application thường chạy ở background, không có tương tác của user và thường chạy dưới một system-level account thay vì user account.
Một OAuth 2.0 Client được cấu hình với grant type `client_credentials` có thể được xem là một loại service application.

Đoạn code sau minh họa cách cấu hình `AuthorizedClientServiceOAuth2AuthorizedClientManager` hỗ trợ grant type `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientService authorizedClientService) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.clientCredentials()
					.build();

	AuthorizedClientServiceOAuth2AuthorizedClientManager authorizedClientManager =
			new AuthorizedClientServiceOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientService);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientService: OAuth2AuthorizedClientService): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build()
    val authorizedClientManager = AuthorizedClientServiceOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientService)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======
