[[oauth2-client]]
= OAuth 2.0 Client
:page-section-summary-toc: 1

Các tính năng của OAuth 2.0 Client hỗ trợ vai trò Client được định nghĩa trong https://tools.ietf.org/html/rfc6749#section-1.1[OAuth 2.0 Authorization Framework].

Ở mức khái quát, các tính năng cốt lõi gồm:

.Hỗ trợ Authorization Grant
* xref:servlet/oauth2/client/authorization-grants.adoc#oauth2-client-authorization-code[Authorization Code]
* xref:servlet/oauth2/client/authorization-grants.adoc#oauth2-client-refresh-token[Refresh Token]
* xref:servlet/oauth2/client/authorization-grants.adoc#oauth2-client-client-credentials[Client Credentials]
* xref:servlet/oauth2/client/authorization-grants.adoc#oauth2-client-jwt-bearer[JWT Bearer]
* xref:servlet/oauth2/client/authorization-grants.adoc#oauth2-client-token-exchange[Token Exchange]

.Hỗ trợ Client Authentication
* xref:servlet/oauth2/client/client-authentication.adoc#oauth2-client-authentication-jwt-bearer[JWT Bearer]

.Hỗ trợ HTTP Client (để request các resource được bảo vệ)
* xref:servlet/oauth2/client/authorized-clients.adoc#oauth2-client-rest-client[Tích hợp `RestClient`]
* xref:servlet/oauth2/client/authorized-clients.adoc#oauth2-client-web-client[Tích hợp `WebClient` cho môi trường Servlet]

DSL `HttpSecurity.oauth2Client()` cung cấp một số tùy chọn cấu hình để tùy chỉnh các thành phần cốt lõi được OAuth 2.0 Client sử dụng.
Ngoài ra, `HttpSecurity.oauth2Client().authorizationCodeGrant()` cho phép tùy chỉnh grant Authorization Code.

Đoạn mã sau đây cho thấy đầy đủ các tùy chọn cấu hình do DSL `HttpSecurity.oauth2Client()` cung cấp:

.Các tùy chọn cấu hình OAuth2 Client
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.oauth2Client((oauth2) -> oauth2
				.clientRegistrationRepository(this.clientRegistrationRepository())
				.authorizedClientRepository(this.authorizedClientRepository())
				.authorizedClientService(this.authorizedClientService())
				.authorizationCodeGrant((codeGrant) -> codeGrant
					.authorizationRequestRepository(this.authorizationRequestRepository())
					.authorizationRequestResolver(this.authorizationRequestResolver())
					.accessTokenResponseClient(this.accessTokenResponseClient())
				)
			);
		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            oauth2Client {
                clientRegistrationRepository = clientRegistrationRepository()
                authorizedClientRepository = authorizedClientRepository()
                authorizedClientService = authorizedClientService()
                authorizationCodeGrant {
                    authorizationRequestRepository = authorizationRequestRepository()
                    authorizationRequestResolver = authorizationRequestResolver()
                    accessTokenResponseClient = accessTokenResponseClient()
                }
            }
        }
        return http.build()
    }
}
----
======

Ngoài DSL `HttpSecurity.oauth2Client()`, cấu hình XML cũng được hỗ trợ.

Đoạn mã sau đây cho thấy đầy đủ các tùy chọn cấu hình có trong xref:servlet/appendix/namespace/http.adoc#nsa-oauth2-client[ namespace bảo mật]:

.Các tùy chọn cấu hình XML của OAuth2 Client
[source,xml]
----
<http>
	<oauth2-client client-registration-repository-ref="clientRegistrationRepository"
				   authorized-client-repository-ref="authorizedClientRepository"
				   authorized-client-service-ref="authorizedClientService">
		<authorization-code-grant
				authorization-request-repository-ref="authorizationRequestRepository"
				authorization-request-resolver-ref="authorizationRequestResolver"
				access-token-response-client-ref="accessTokenResponseClient"/>
	</oauth2-client>
</http>
----

`OAuth2AuthorizedClientManager` chịu trách nhiệm quản lý authorization (hoặc re-authorization) của một OAuth 2.0 Client, phối hợp với một hoặc nhiều `OAuth2AuthorizedClientProvider`.

Đoạn mã sau đây minh họa cách đăng ký một `OAuth2AuthorizedClientManager` `@Bean` và liên kết nó với một composite `OAuth2AuthorizedClientProvider` hỗ trợ các loại authorization grant `authorization_code`, `refresh_token` và `client_credentials`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider: OAuth2AuthorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======
