[[servlet-saml2login-metadata]]
= Metadata SAML 2.0

Spring Security có thể <<parsing-asserting-party-metadata,parse metadata của asserting party>> để tạo một instance `AssertingPartyMetadata`, đồng thời <<publishing-relying-party-metadata,publish metadata của relying party>> từ một instance `RelyingPartyRegistration`.

[[parsing-asserting-party-metadata]]
== Parse metadata `<saml2:IDPSSODescriptor>`

Bạn có thể parse metadata của asserting party xref:servlet/saml2/login/overview.adoc#servlet-saml2login-relyingpartyregistrationrepository[bằng cách sử dụng `RelyingPartyRegistrations`].

Khi sử dụng phần hỗ trợ vendor của OpenSAML, `AssertingPartyMetadata` thu được sẽ có kiểu `OpenSamlAssertingPartyDetails`.
Điều này có nghĩa là bạn có thể lấy underlying OpenSAML XMLObject bằng cách thực hiện như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
OpenSamlAssertingPartyDetails details = (OpenSamlAssertingPartyDetails)
        registration.getAssertingPartyMetadata();
EntityDescriptor openSamlEntityDescriptor = details.getEntityDescriptor();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val details: OpenSamlAssertingPartyDetails =
        registration.getAssertingPartyMetadata() as OpenSamlAssertingPartyDetails
val openSamlEntityDescriptor: EntityDescriptor = details.getEntityDescriptor()
----
======

[[using-assertingpartymetadatarepository]]
=== Sử dụng `AssertingPartyMetadataRepository`

Bạn cũng có thể nhắm mục tiêu cụ thể hơn so với `RelyingPartyRegistrations` bằng cách sử dụng `AssertingPartyMetadataRepository`, một interface chỉ cho phép truy xuất metadata của asserting party.

Điều này cung cấp ba tính năng hữu ích:

* Các implementation có thể refresh metadata của asserting party theo cách có tính đến expiry
* Các implementation của `RelyingPartyRegistrationRepository` có thể dễ dàng thể hiện mối quan hệ giữa một relying party và một hoặc nhiều asserting party tương ứng
* Các implementation có thể xác minh chữ ký metadata

Ví dụ, `OpenSaml5AssertingPartyMetadataRepository` sử dụng `MetadataResolver` của OpenSAML, một API mà các implementation của nó thường xuyên refresh underlying metadata theo cách có tính đến expiry.

Điều này có nghĩa là giờ đây bạn có thể tạo một `RelyingPartyRegistrationRepository` có khả năng refresh chỉ với vài dòng code:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class RefreshableRelyingPartyRegistrationRepository
        implements IterableRelyingPartyRegistrationRepository {

	private final AssertingPartyMetadataRepository metadata =
            OpenSaml5AssertingPartyMetadataRepository
                .fromTrustedMetadataLocation("https://idp.example.org/metadata").build();

	@Override
    public RelyingPartyRegistration findByRegistrationId(String registrationId) {
		AssertingPartyMetadata metadata = this.metadata.findByEntityId(registrationId);
        if (metadata == null) {
            return null;
        }
		return applyRelyingParty(metadata);
    }

	@Override
    public Iterator<RelyingPartyRegistration> iterator() {
		return StreamSupport.stream(this.metadata.spliterator(), false)
            .map(this::applyRelyingParty).iterator();
    }

	private RelyingPartyRegistration applyRelyingParty(AssertingPartyMetadata metadata) {
		return RelyingPartyRegistration.withAssertingPartyMetadata(metadata)
            // apply any relying party configuration
            .build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class RefreshableRelyingPartyRegistrationRepository : IterableRelyingPartyRegistrationRepository {

    private val metadata: AssertingPartyMetadataRepository =
        OpenSaml5AssertingPartyMetadataRepository.fromTrustedMetadataLocation(
            "https://idp.example.org/metadata").build()

    fun findByRegistrationId(registrationId:String?): RelyingPartyRegistration {
        val metadata = this.metadata.findByEntityId(registrationId)
        if (metadata == null) {
            return null
        }
        return applyRelyingParty(metadata)
    }

    fun iterator(): Iterator<RelyingPartyRegistration> {
        return StreamSupport.stream(this.metadata.spliterator(), false)
            .map(this::applyRelyingParty).iterator()
    }

    private fun applyRelyingParty(metadata: AssertingPartyMetadata): RelyingPartyRegistration {
        val details: AssertingPartyMetadata = metadata as AssertingPartyMetadata
        return RelyingPartyRegistration.withAssertingPartyMetadata(details)
            // apply any relying party configuration
            .build()
    }
 }
----
======

[TIP]
`OpenSaml5AssertingPartyMetadataRepository` cũng cung cấp một constructor để bạn có thể truyền vào một custom `MetadataResolver`. Vì underlying `MetadataResolver` xử lý expiry và refresh, nếu bạn gọi trực tiếp constructor, bạn chỉ nhận được các tính năng này khi cung cấp một implementation thực hiện việc đó.

=== Xác minh chữ ký metadata

Bạn cũng có thể xác minh chữ ký metadata bằng cách sử dụng `OpenSaml5AssertingPartyMetadataRepository` và cung cấp tập hợp ``Saml2X509Credential``s phù hợp như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
OpenSaml5AssertingPartyMetadataRepository.withMetadataLocation("https://idp.example.org/metadata")
    .verificationCredentials((c) -> c.add(myVerificationCredential))
    .build();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
OpenSaml5AssertingPartyMetadataRepository.withMetadataLocation("https://idp.example.org/metadata")
    .verificationCredentials({ c : Collection<Saml2X509Credential> ->
        c.add(myVerificationCredential) })
    .build()
----
======

[NOTE]
Nếu không cung cấp credential nào, component sẽ không thực hiện signature validation.

[[publishing-relying-party-metadata]]
== Tạo metadata `<saml2:SPSSODescriptor>`

Bạn có thể publish một metadata endpoint bằng DSL method `saml2Metadata`, như minh họa bên dưới:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
http
    // ...
    .saml2Login(withDefaults())
    .saml2Metadata(withDefaults());
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
http {
    //...
    saml2Login { }
    saml2Metadata { }
}
----
======

Bạn có thể sử dụng metadata endpoint này để đăng ký relying party của mình với asserting party.
Việc này thường đơn giản như tìm đúng trường biểu mẫu để cung cấp metadata endpoint.

Theo mặc định, metadata endpoint là `+/saml2/metadata+`, nhưng nó cũng hỗ trợ `+/saml2/metadata/{registrationId}+` và `+/saml2/service-provider-metadata/{registrationId}+`.

Bạn có thể thay đổi điều này bằng cách gọi method `metadataUrl` trong DSL:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
.saml2Metadata((saml2) -> saml2.metadataUrl("/saml/metadata"))
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
saml2Metadata {
	metadataUrl = "/saml/metadata"
}
----
======

== Thay đổi cách tra cứu một `RelyingPartyRegistration`

Nếu bạn có một chiến lược khác để xác định `RelyingPartyRegistration` nào cần sử dụng, bạn có thể cấu hình `Saml2MetadataResponseResolver` của riêng mình như dưới đây:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
Saml2MetadataResponseResolver metadataResponseResolver(RelyingPartyRegistrationRepository registrations) {
	RequestMatcherMetadataResponseResolver metadata = new RequestMatcherMetadataResponseResolver(
			(id) -> registrations.findByRegistrationId("relying-party"));
	metadata.setMetadataFilename("metadata.xml");
	return metadata;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun metadataResponseResolver(val registrations: RelyingPartyRegistrationRepository): Saml2MetadataResponseResolver {
    val metadata = new RequestMatcherMetadataResponseResolver(
			id: String -> registrations.findByRegistrationId("relying-party"))
	metadata.setMetadataFilename("metadata.xml")
	return metadata
}
----
======
