[[nsa-authentication]]
= Dịch vụ authentication
Trước Spring Security 3.0, một `AuthenticationManager` được tự động đăng ký nội bộ.
Hiện tại, bạn phải đăng ký tường minh một `AuthenticationManager` bằng phần tử `<authentication-manager>`.
Phần tử này tạo một instance của class `ProviderManager` của Spring Security, class này cần được cấu hình bằng danh sách gồm một hoặc nhiều instance `AuthenticationProvider`.
Các instance này có thể được tạo bằng các phần tử cú pháp do namespace cung cấp, hoặc có thể là các định nghĩa bean tiêu chuẩn, được đánh dấu để thêm vào danh sách bằng phần tử `authentication-provider`.


[[nsa-authentication-manager]]
== <authentication-manager>
Mọi ứng dụng Spring Security sử dụng namespace đều phải bao gồm phần tử này ở đâu đó.
Phần tử này chịu trách nhiệm đăng ký `AuthenticationManager` cung cấp các dịch vụ authentication cho ứng dụng.
Mọi phần tử tạo instance `AuthenticationProvider` đều nên là phần tử con của phần tử này.


[[nsa-authentication-manager-attributes]]
=== <authentication-manager> Thuộc tính


[[nsa-authentication-manager-alias]]
* **alias**
Thuộc tính này cho phép bạn định nghĩa một tên alias cho instance nội bộ để sử dụng trong cấu hình của riêng bạn.


[[nsa-authentication-manager-erase-credentials]]
* **erase-credentials**
Nếu được đặt thành true, AuthenticationManager sẽ cố gắng xóa mọi dữ liệu credential trong object Authentication được trả về sau khi user đã được authenticated.
Về bản chất, thuộc tính này ánh xạ tới property `eraseCredentialsAfterAuthentication` của xref:servlet/authentication/architecture.adoc#servlet-authentication-providermanager[`ProviderManager`].

[[nsa-authentication-manager-observation-registry-ref]]
* **observation-registry-ref**
Một tham chiếu tới `ObservationRegistry` được sử dụng cho `FilterChain` và các component liên quan

[[nsa-authentication-manager-id]]
* **id**
Thuộc tính này cho phép bạn định nghĩa một id cho instance nội bộ để sử dụng trong cấu hình của riêng bạn.
Nó tương đương với phần tử alias, nhưng mang lại trải nghiệm nhất quán hơn với các phần tử sử dụng thuộc tính id.


[[nsa-authentication-manager-children]]
=== Phần tử con của <authentication-manager>


* <<nsa-authentication-provider,authentication-provider>>
* xref:servlet/appendix/namespace/ldap.adoc#nsa-ldap-authentication-provider[ldap-authentication-provider]



[[nsa-authentication-provider]]
== <authentication-provider>
Trừ khi được sử dụng với thuộc tính `ref`, phần tử này là cách viết tắt để cấu hình một `DaoAuthenticationProvider`.
`DaoAuthenticationProvider` tải thông tin user từ một `UserDetailsService` và so sánh tổ hợp username/password với các giá trị được cung cấp khi đăng nhập.
Instance `UserDetailsService` có thể được định nghĩa bằng một phần tử namespace khả dụng (`jdbc-user-service`, hoặc bằng thuộc tính `user-service-ref` để trỏ tới một bean được định nghĩa ở nơi khác trong application context).



[[nsa-authentication-provider-parents]]
=== Phần tử cha của <authentication-provider>


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-authentication-provider-attributes]]
=== <authentication-provider> Thuộc tính


[[nsa-authentication-provider-ref]]
* **ref**
Định nghĩa một tham chiếu tới bean Spring triển khai `AuthenticationProvider`.

Nếu bạn đã viết triển khai `AuthenticationProvider` của riêng mình (hoặc vì lý do nào đó muốn cấu hình một trong các triển khai của Spring Security dưới dạng bean truyền thống), bạn có thể sử dụng cú pháp sau để thêm triển khai đó vào danh sách nội bộ của `ProviderManager`:

[source,xml]
----

<security:authentication-manager>
  <security:authentication-provider ref="myAuthenticationProvider" />
</security:authentication-manager>
<bean id="myAuthenticationProvider" class="com.something.MyAuthenticationProvider"/>

----




[[nsa-authentication-provider-user-service-ref]]
* **user-service-ref**
Một tham chiếu tới bean triển khai UserDetailsService, có thể được tạo bằng phần tử bean tiêu chuẩn hoặc phần tử user-service tùy chỉnh.


[[nsa-authentication-provider-children]]
=== Phần tử con của <authentication-provider>


* <<nsa-jdbc-user-service,jdbc-user-service>>
* xref:servlet/appendix/namespace/ldap.adoc#nsa-ldap-user-service[ldap-user-service]
* <<nsa-password-encoder,password-encoder>>
* <<nsa-user-service,user-service>>



[[nsa-jdbc-user-service]]
== <jdbc-user-service>
Tạo một UserDetailsService dựa trên JDBC.


[[nsa-jdbc-user-service-attributes]]
=== <jdbc-user-service> Thuộc tính


[[nsa-jdbc-user-service-authorities-by-username-query]]
* **authorities-by-username-query**
Một câu lệnh SQL để truy vấn các authority được cấp cho user dựa trên username.

Giá trị mặc định là

[source]
----
select username, authority from authorities where username = ?
----




[[nsa-jdbc-user-service-cache-ref]]
* **cache-ref**
Định nghĩa một tham chiếu tới cache để sử dụng với UserDetailsService.


[[nsa-jdbc-user-service-data-source-ref]]
* **data-source-ref**
ID của bean DataSource cung cấp các bảng cần thiết.


[[nsa-jdbc-user-service-group-authorities-by-username-query]]
* **group-authorities-by-username-query**
Một câu lệnh SQL để truy vấn các group authority của user dựa trên username.
Giá trị mặc định là

+

[source]
----
select
g.id, g.group_name, ga.authority
from
groups g, group_members gm, group_authorities ga
where
gm.username = ? and g.id = ga.group_id and g.id = gm.group_id
----




[[nsa-jdbc-user-service-id]]
* **id**
Một bean identifier, được sử dụng để tham chiếu tới bean ở nơi khác trong context.


[[nsa-jdbc-user-service-role-prefix]]
* **role-prefix**
Một tiền tố chuỗi không rỗng được thêm vào các chuỗi role được tải từ persistent storage (giá trị mặc định là "ROLE_").
Sử dụng giá trị "none" để không có tiền tố trong trường hợp giá trị mặc định không rỗng.


[[nsa-jdbc-user-service-users-by-username-query]]
* **users-by-username-query**
Một câu lệnh SQL để truy vấn username, password và trạng thái enabled dựa trên username.
Giá trị mặc định là

+

[source]
----
select username, password, enabled from users where username = ?
----




[[nsa-password-encoder]]
== <password-encoder>
Authentication provider có thể được cấu hình tùy chọn để sử dụng password encoder như mô tả trong xref:features/authentication/password-storage.adoc#authentication-password-storage[Lưu trữ mật khẩu].
Điều này sẽ khiến bean được inject instance `PasswordEncoder` thích hợp.


[[nsa-password-encoder-parents]]
=== Phần tử cha của <password-encoder>


* <<nsa-authentication-provider,authentication-provider>>
* xref:servlet/appendix/namespace/authentication-manager.adoc#nsa-password-compare[password-compare]



[[nsa-password-encoder-attributes]]
=== <password-encoder> Thuộc tính


[[nsa-password-encoder-hash]]
* **hash**
Định nghĩa thuật toán hashing được sử dụng cho password của user.
Chúng tôi đặc biệt khuyến nghị không sử dụng MD4 vì đây là một thuật toán hashing rất yếu.


[[nsa-password-encoder-ref]]
* **ref**
Định nghĩa một tham chiếu tới bean Spring triển khai `PasswordEncoder`.


[[nsa-user-service]]
== <user-service>
Tạo một UserDetailsService in-memory từ một file properties hoặc một danh sách các phần tử con "user".
Username được chuyển đổi nội bộ thành chữ thường để cho phép tra cứu không phân biệt chữ hoa chữ thường, vì vậy không nên sử dụng phần tử này nếu cần phân biệt chữ hoa chữ thường.


[[nsa-user-service-attributes]]
=== <user-service> Thuộc tính


[[nsa-user-service-id]]
* **id**
Một bean identifier, được sử dụng để tham chiếu tới bean ở nơi khác trong context.


[[nsa-user-service-properties]]
* **properties**
Vị trí của một file Properties, trong đó mỗi dòng có định dạng

+

[source]
----
username=password,grantedAuthority[,grantedAuthority][,enabled|disabled]
----




[[nsa-user-service-children]]
=== Phần tử con của <user-service>


* <<nsa-user,user>>



[[nsa-user]]
== <user>
Đại diện cho một user trong application.


[[nsa-user-parents]]
=== Phần tử cha của <user>


* <<nsa-user-service,user-service>>



[[nsa-user-attributes]]
=== <user> Thuộc tính


[[nsa-user-authorities]]
* **authorities**
Một hoặc nhiều authority được cấp cho user.
Phân tách các authority bằng dấu phẩy (không có khoảng trắng).
Ví dụ: "ROLE_USER,ROLE_ADMINISTRATOR"


[[nsa-user-disabled]]
* **disabled**
Có thể được đặt thành "true" để đánh dấu account là disabled và không thể sử dụng.


[[nsa-user-locked]]
* **locked**
Có thể được đặt thành "true" để đánh dấu account là locked và không thể sử dụng.


[[nsa-user-name]]
* **name**
Username được gán cho user.


[[nsa-user-password]]
* **password**
Password được gán cho user.
Password này có thể được hashing nếu authentication provider tương ứng hỗ trợ hashing (hãy nhớ đặt thuộc tính "hash" của phần tử "user-service").
Có thể bỏ qua thuộc tính này trong trường hợp dữ liệu sẽ không được sử dụng cho authentication mà chỉ để truy cập các authority.
Nếu bị bỏ qua, namespace sẽ tạo một giá trị ngẫu nhiên, ngăn việc vô tình sử dụng giá trị đó cho authentication.
Không được để trống.
