[[nsa-authentication]]
= Dịch vụ authentication
Trước Spring Security 3.0, một `AuthenticationManager` được tự động đăng ký nội bộ.
Hiện tại, bạn phải đăng ký tường minh một `AuthenticationManager` bằng element `<authentication-manager>`.
Element này tạo một instance của class `ProviderManager` của Spring Security, class này cần được cấu hình bằng danh sách gồm một hoặc nhiều instance `AuthenticationProvider`.
Các instance này có thể được tạo bằng các syntax element do namespace cung cấp, hoặc có thể là các định nghĩa bean tiêu chuẩn, được đánh dấu để thêm vào danh sách bằng element `authentication-provider`.


[[nsa-authentication-manager]]
== <authentication-manager>
Mọi ứng dụng Spring Security sử dụng namespace đều phải có element này ở đâu đó.
Element này chịu trách nhiệm đăng ký `AuthenticationManager` cung cấp các dịch vụ authentication cho ứng dụng.
Tất cả element tạo instance `AuthenticationProvider` nên là child element của element này.


[[nsa-authentication-manager-attributes]]
=== Các attribute của <authentication-manager>


[[nsa-authentication-manager-alias]]
* **alias**
Attribute này cho phép bạn định nghĩa một tên alias cho instance nội bộ để sử dụng trong cấu hình của riêng bạn.


[[nsa-authentication-manager-erase-credentials]]
* **erase-credentials**
Nếu được đặt thành true, AuthenticationManager sẽ cố gắng xóa mọi dữ liệu credential trong object Authentication được trả về sau khi user đã được authenticated.
Về bản chất, attribute này ánh xạ tới property `eraseCredentialsAfterAuthentication` của xref:servlet/authentication/architecture.adoc#servlet-authentication-providermanager[`ProviderManager`].

[[nsa-authentication-manager-observation-registry-ref]]
* **observation-registry-ref**
Một tham chiếu tới `ObservationRegistry` được sử dụng cho `FilterChain` và các component liên quan

[[nsa-authentication-manager-id]]
* **id**
Attribute này cho phép bạn định nghĩa một id cho instance nội bộ để sử dụng trong cấu hình của riêng bạn.
Nó tương đương với alias element, nhưng mang lại trải nghiệm nhất quán hơn với các element sử dụng attribute id.


[[nsa-authentication-manager-children]]
=== Các child element của <authentication-manager>


* <<nsa-authentication-provider,authentication-provider>>
* xref:servlet/appendix/namespace/ldap.adoc#nsa-ldap-authentication-provider[ldap-authentication-provider]



[[nsa-authentication-provider]]
== <authentication-provider>
Trừ khi được sử dụng với attribute `ref`, element này là cách viết tắt để cấu hình một `DaoAuthenticationProvider`.
`DaoAuthenticationProvider` tải thông tin user từ một `UserDetailsService` và so sánh tổ hợp username/password với các giá trị được cung cấp khi đăng nhập.
Instance `UserDetailsService` có thể được định nghĩa bằng một element namespace khả dụng (`jdbc-user-service`) hoặc bằng attribute `user-service-ref` trỏ tới một bean được định nghĩa ở nơi khác trong application context.



[[nsa-authentication-provider-parents]]
=== Các parent element của <authentication-provider>


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-authentication-provider-attributes]]
=== Các attribute của <authentication-provider>


[[nsa-authentication-provider-ref]]
* **ref**
Định nghĩa một tham chiếu tới bean Spring triển khai `AuthenticationProvider`.

Nếu bạn đã viết triển khai `AuthenticationProvider` của riêng mình (hoặc vì lý do nào đó muốn cấu hình một trong các triển khai của Spring Security dưới dạng bean truyền thống), bạn có thể sử dụng cú pháp sau để thêm triển khai đó vào danh sách nội bộ của `ProviderManager`:

[source,xml]
----

<security:authentication-manager>
  <security:authentication-provider ref="myAuthenticationProvider" />
</security:authentication-manager>
<bean id="myAuthenticationProvider" class="com.something.MyAuthenticationProvider"/>

----




[[nsa-authentication-provider-user-service-ref]]
* **user-service-ref**
Một tham chiếu tới bean triển khai UserDetailsService, có thể được tạo bằng standard bean element hoặc custom user-service element.


[[nsa-authentication-provider-children]]
=== Các child element của <authentication-provider>


* <<nsa-jdbc-user-service,jdbc-user-service>>
* xref:servlet/appendix/namespace/ldap.adoc#nsa-ldap-user-service[ldap-user-service]
* <<nsa-password-encoder,password-encoder>>
* <<nsa-user-service,user-service>>



[[nsa-jdbc-user-service]]
== <jdbc-user-service>
Tạo một UserDetailsService dựa trên JDBC.


[[nsa-jdbc-user-service-attributes]]
=== Các attribute của <jdbc-user-service>


[[nsa-jdbc-user-service-authorities-by-username-query]]
* **authorities-by-username-query**
Một câu lệnh SQL để truy vấn các authority được cấp cho user dựa trên username.

Giá trị mặc định là

[source]
----
select username, authority from authorities where username = ?
----




[[nsa-jdbc-user-service-cache-ref]]
* **cache-ref**
Định nghĩa một tham chiếu tới cache để sử dụng với UserDetailsService.


[[nsa-jdbc-user-service-data-source-ref]]
* **data-source-ref**
ID của bean DataSource cung cấp các bảng cần thiết.


[[nsa-jdbc-user-service-group-authorities-by-username-query]]
* **group-authorities-by-username-query**
Một câu lệnh SQL để truy vấn các group authority của user dựa trên username.
Giá trị mặc định là

+

[source]
----
select
g.id, g.group_name, ga.authority
from
groups g, group_members gm, group_authorities ga
where
gm.username = ? and g.id = ga.group_id and g.id = gm.group_id
----




[[nsa-jdbc-user-service-id]]
* **id**
Một bean identifier, được sử dụng để tham chiếu tới bean ở nơi khác trong context.


[[nsa-jdbc-user-service-role-prefix]]
* **role-prefix**
Một prefix dạng string không rỗng được thêm vào các role được load từ persistent storage (giá trị mặc định là "ROLE_").
Sử dụng giá trị "none" để không có prefix trong trường hợp giá trị mặc định không rỗng.


[[nsa-jdbc-user-service-users-by-username-query]]
* **users-by-username-query**
Một câu lệnh SQL để truy vấn username, password và trạng thái enabled dựa trên username.
Giá trị mặc định là

+

[source]
----
select username, password, enabled from users where username = ?
----




[[nsa-password-encoder]]
== <password-encoder>
Các authentication provider có thể được cấu hình tùy chọn để sử dụng password encoder như mô tả trong xref:features/authentication/password-storage.adoc#authentication-password-storage[Lưu trữ mật khẩu].
Điều này sẽ khiến bean được inject một instance `PasswordEncoder` thích hợp.


[[nsa-password-encoder-parents]]
=== Các parent element của <password-encoder>


* <<nsa-authentication-provider,authentication-provider>>
* xref:servlet/appendix/namespace/authentication-manager.adoc#nsa-password-compare[password-compare]



[[nsa-password-encoder-attributes]]
=== Các attribute của <password-encoder>


[[nsa-password-encoder-hash]]
* **hash**
Định nghĩa hashing algorithm được sử dụng cho password của user.
Chúng tôi đặc biệt khuyến nghị không sử dụng MD4 vì đây là một hashing algorithm rất yếu.


[[nsa-password-encoder-ref]]
* **ref**
Định nghĩa một tham chiếu tới bean Spring triển khai `PasswordEncoder`.


[[nsa-user-service]]
== <user-service>
Tạo một UserDetailsService in-memory từ một file properties hoặc một danh sách các child element "user".
Username được chuyển thành lowercase trong nội bộ để cho phép case-insensitive lookup, vì vậy không nên sử dụng element này nếu cần case-sensitive.


[[nsa-user-service-attributes]]
=== Các attribute của <user-service>


[[nsa-user-service-id]]
* **id**
Một bean identifier, được sử dụng để tham chiếu tới bean ở nơi khác trong context.


[[nsa-user-service-properties]]
* **properties**
Vị trí của một file Properties, trong đó mỗi dòng có định dạng

+

[source]
----
username=password,grantedAuthority[,grantedAuthority][,enabled|disabled]
----




[[nsa-user-service-children]]
=== Các child element của <user-service>


* <<nsa-user,user>>



[[nsa-user]]
== <user>
Đại diện cho một user trong application.


[[nsa-user-parents]]
=== Các parent element của <user>


* <<nsa-user-service,user-service>>



[[nsa-user-attributes]]
=== Các attribute của <user>


[[nsa-user-authorities]]
* **authorities**
Một hoặc nhiều authority được cấp cho user.
Phân tách các authority bằng dấu phẩy (không có khoảng trắng).
Ví dụ: "ROLE_USER,ROLE_ADMINISTRATOR"


[[nsa-user-disabled]]
* **disabled**
Có thể được đặt thành "true" để đánh dấu account là disabled và không thể sử dụng.


[[nsa-user-locked]]
* **locked**
Có thể được đặt thành "true" để đánh dấu account là locked và không thể sử dụng.


[[nsa-user-name]]
* **name**
Username được gán cho user.


[[nsa-user-password]]
* **password**
Password được gán cho user.
Password này có thể được hash nếu authentication provider tương ứng hỗ trợ hashing (hãy nhớ đặt attribute "hash" của element "user-service").
Có thể bỏ qua attribute này trong trường hợp dữ liệu sẽ không được sử dụng cho authentication mà chỉ để truy cập các authority.
Nếu bị bỏ qua, namespace sẽ tạo một giá trị ngẫu nhiên, ngăn việc vô tình sử dụng giá trị đó cho authentication.
Không được để trống.
