[[nsa-web]]
= Bảo mật ứng dụng web

[[nsa-debug]]
== <debug>
Cho phép hạ tầng debug của Spring Security.
Tính năng này cung cấp thông tin debug dễ đọc (nhiều dòng) để giám sát các request đi vào security filter.
Thông tin này có thể bao gồm dữ liệu nhạy cảm, chẳng hạn như request parameter hoặc header, vì vậy chỉ nên được sử dụng trong môi trường phát triển.

[[nsa-http]]
== <http>
Nếu sử dụng một element `<http>` trong ứng dụng, một bean `FilterChainProxy` có tên "springSecurityFilterChain" sẽ được tạo, và cấu hình trong element này được dùng để xây dựng một filter chain bên trong
`FilterChainProxy`.
Kể từ Spring Security 3.1, có thể sử dụng các element `http` bổ sung để thêm các filter chain khác footnote:[Xem pass:specialcharacters,macros[xref:servlet/configuration/xml-namespace.adoc#ns-web-xml[chương giới thiệu]] để biết cách thiết lập ánh xạ từ `web.xml` của bạn ].
Một số filter cốt lõi luôn được tạo trong filter chain, còn các filter khác sẽ được thêm vào stack tùy thuộc vào các attribute và child element hiện có.
Vị trí của các filter tiêu chuẩn là cố định (xem
xref:servlet/configuration/xml-namespace.adoc#filter-stack[bảng thứ tự filter] trong phần giới thiệu namespace), loại bỏ một nguồn lỗi phổ biến của các phiên bản framework trước, khi người dùng phải tự cấu hình filter chain trong
bean `FilterChainProxy`.
Tất nhiên, bạn vẫn có thể làm vậy nếu cần toàn quyền kiểm soát cấu hình.


Tất cả filter cần tham chiếu đến xref:servlet/authentication/architecture.adoc#servlet-authentication-authenticationmanager[`AuthenticationManager`] sẽ tự động được inject instance nội bộ do cấu hình namespace tạo ra.

Mỗi block namespace `<http>` luôn tạo một `SecurityContextPersistenceFilter`, một `ExceptionTranslationFilter` và một `FilterSecurityInterceptor`.
Các filter này là cố định và không thể được thay thế bằng lựa chọn khác.


[[nsa-http-attributes]]
=== Các attribute của <http>
Các attribute trên element `<http>` kiểm soát một số thuộc tính của các filter cốt lõi.

[[nsa-http-use-authorization-manager]]
* **use-authorization-manager**
Dùng API AuthorizationManager thay cho SecurityMetadataSource (mặc định là true)

[[nsa-http-authorization-manager-ref]]
* **authorization-manager-ref**
Dùng AuthorizationManager này thay vì suy ra một instance từ các element `<intercept-url>`.

[[nsa-http-access-decision-manager-ref]]
* **access-decision-manager-ref**
Attribute tùy chọn chỉ định ID của implementation `AccessDecisionManager` được dùng để thực hiện authorization cho các HTTP request.
Mặc định, một implementation `AffirmativeBased` được dùng cùng với `RoleVoter` và `AuthenticatedVoter`.


[[nsa-http-authentication-manager-ref]]
* **authentication-manager-ref**
Tham chiếu đến `AuthenticationManager` được dùng cho `FilterChain` do element `<http>` này tạo ra.

[[nsa-http-observation-registry-ref]]
* **observation-registry-ref**
Tham chiếu đến `ObservationRegistry` được dùng cho `FilterChain` và các component liên quan.

[[nsa-http-auto-config]]
* **auto-config**
Tự động đăng ký form login, BASIC authentication và logout service.
Nếu đặt thành "true", tất cả capability này sẽ được thêm vào (dù bạn vẫn có thể tùy chỉnh từng capability bằng cách cung cấp element tương ứng).
Nếu không chỉ định, mặc định là "false".
Không khuyến nghị sử dụng attribute này.
Thay vào đó, hãy dùng các element cấu hình tường minh để tránh nhầm lẫn.


[[nsa-http-create-session]]
* **create-session**
Kiểm soát mức độ chủ động khi các class Spring Security tạo HTTP session.
Các tùy chọn gồm:

** `always` - Spring Security sẽ chủ động tạo session nếu session chưa tồn tại.
** `ifRequired` - Spring Security chỉ tạo session khi session được yêu cầu (value mặc định).
** `never` - Spring Security không bao giờ tạo session, nhưng sẽ sử dụng session nếu ứng dụng tạo nó.
** `stateless` - Spring Security không tạo session và bỏ qua session khi lấy `Authentication` của Spring.

[[nsa-http-disable-url-rewriting]]
* **disable-url-rewriting**
Ngăn session ID được nối vào URL trong ứng dụng.
Client phải sử dụng cookie nếu attribute này được đặt thành `true`.
Mặc định là `true`.


[[nsa-http-entry-point-ref]]
* **entry-point-ref**
Thông thường, `AuthenticationEntryPoint` được dùng sẽ được thiết lập tùy thuộc vào các authentication mechanism đã cấu hình.
Attribute này cho phép override hành vi đó bằng cách định nghĩa một bean `AuthenticationEntryPoint` tùy chỉnh để khởi động quy trình authentication.


[[nsa-http-jaas-api-provision]]
* **jaas-api-provision**
Nếu có, chạy request dưới dạng `Subject` lấy được từ `JaasAuthenticationToken`; tính năng này được triển khai bằng cách thêm bean `JaasApiIntegrationFilter` vào stack.
Mặc định là `false`.


[[nsa-http-name]]
* **name**
Một bean identifier, được dùng để tham chiếu đến bean ở nơi khác trong context.


[[nsa-http-once-per-request]]
* **once-per-request**
Tương ứng với property `observeOncePerRequest` của `FilterSecurityInterceptor`.
Mặc định là `false`.


[[nsa-http-filter-all-dispatcher-types]]
* **filter-all-dispatcher-types**
Tương ứng với property `shouldFilterAllDispatcherTypes` của `AuthorizationFilter`. Không hoạt động khi `use-authorization-manager=false`.
Mặc định là `true`.


[[nsa-http-pattern]]
* **pattern**
Việc định nghĩa pattern cho element <<nsa-http,http>> kiểm soát các request sẽ đi qua danh sách filter mà element này định nghĩa.
Cách diễn giải phụ thuộc vào <<nsa-http-request-matcher,request-matcher>> đã cấu hình.
Nếu không định nghĩa pattern, mọi request sẽ được match, vì vậy các pattern cụ thể nhất nên được khai báo trước.


[[nsa-http-realm]]
* **realm**
Thiết lập tên realm được dùng cho basic authentication (nếu được bật).
Tương ứng với property `realmName` trên `BasicAuthenticationEntryPoint`.

[[nsa-http-redirect-to-https-request-matcher-ref]]
* **redirect-to-https-request-matcher-ref**
Tham chiếu đến bean triển khai `RequestMatcher` để xác định request nào phải được redirect đến HTTPS.
Điều này hữu ích, chẳng hạn khi muốn chạy HTTP cục bộ và HTTPS trên production dựa trên request header.

[[nsa-http-request-matcher]]
* **request-matcher**
Định nghĩa strategy `RequestMatcher` được dùng trong `FilterChainProxy` và các bean do `intercept-url` tạo ra để match request đi vào.
Các tùy chọn hiện tại là `mvc`, `ant`, `regex` và `ciRegex`, lần lượt tương ứng với Spring MVC, ant, regular-expression và regular-expression không phân biệt chữ hoa chữ thường.
Một instance riêng được tạo cho mỗi element <<nsa-intercept-url,intercept-url>> bằng các attribute <<nsa-intercept-url-pattern,pattern>>, <<nsa-intercept-url-method,method>> và <<nsa-intercept-url-servlet-path,servlet-path>> của element đó.
Mặc định, path được match bằng `PathPatternRequestMatcher`; tuy nhiên, regular expression được match bằng `RegexRequestMatcher`.
Xem Javadoc của các class này để biết thêm chi tiết về cách matching.
MVC là strategy mặc định nếu Spring MVC có trong classpath; nếu không, các Ant path sẽ được sử dụng.


[[nsa-http-request-matcher-ref]]
* **request-matcher-ref**
Tham chiếu đến bean triển khai `RequestMatcher` để xác định có nên dùng `FilterChain` này hay không.
Đây là lựa chọn mạnh hơn so với <<nsa-http-pattern,pattern>>.


[[nsa-http-security]]
* **security**
Một request pattern có thể được ánh xạ đến một filter chain rỗng bằng cách đặt attribute này thành `none`.
Không áp dụng security và không có feature nào của Spring Security khả dụng.

[[nsa-http-security-context-holder-strategy-ref]]
* **security-context-repository-ref**
Cho phép inject `SecurityContextHolderStrategy` tùy chỉnh vào `SecurityContextPersistenceFilter`, `SecurityContextHolderFilter`, `BasicAuthenticationFilter`, `UsernamePasswordAuthenticationFilter`, `ExceptionTranslationFilter`, `LogoutFilter` và các filter khác.

[[nsa-http-security-context-explicit-save]]
* **security-context-explicit-save**
Nếu là true, dùng `SecurityContextHolderFilter` thay cho `SecurityContextPersistenceFilter`.
Yêu cầu save tường minh.


[[nsa-http-security-context-repository-ref]]
* **security-context-repository-ref**
Cho phép inject `SecurityContextRepository` tùy chỉnh vào `SecurityContextPersistenceFilter`.


[[nsa-http-servlet-api-provision]]
* **servlet-api-provision**
Cung cấp các security method của `HttpServletRequest` như `isUserInRole()` và `getPrincipal()`, được triển khai bằng cách thêm bean `SecurityContextHolderAwareRequestFilter` vào stack.
Mặc định là `true`.


[[nsa-http-use-expressions]]
* **use-expressions**
Cho phép EL expression trong attribute `access`, như được mô tả trong chương xref:servlet/authorization/authorize-http-requests.adoc#authorization-expressions[access control dựa trên expression].
Giá trị mặc định là true.


[[nsa-http-children]]
=== Các child element của <http>
* <<nsa-access-denied-handler,access-denied-handler>>
* <<nsa-anonymous,anonymous>>
* <<nsa-cors,cors>>
* <<nsa-csrf,csrf>>
* <<nsa-custom-filter,custom-filter>>
* <<nsa-expression-handler,expression-handler>>
* <<nsa-form-login,form-login>>
* <<nsa-headers,headers>>
* <<nsa-http-basic,http-basic>>
* <<nsa-intercept-url,intercept-url>>
* <<nsa-jee,jee>>
* <<nsa-logout,logout>>
* <<nsa-oauth2-client,oauth2-client>>
* <<nsa-oauth2-login,oauth2-login>>
* <<nsa-oauth2-resource-server,oauth2-resource-server>>
* <<nsa-password-management,password-management>>
* <<nsa-port-mappings,port-mappings>>
* <<nsa-remember-me,remember-me>>
* <<nsa-request-cache,request-cache>>
* <<nsa-saml2-login,saml2-login>>
* <<nsa-saml2-logout,saml2-logout>>
* <<nsa-session-management,session-management>>
* <<nsa-x509,x509>>


[[nsa-access-denied-handler]]
== <access-denied-handler>
Element này cho phép đặt property `errorPage` cho `AccessDeniedHandler` mặc định được `ExceptionTranslationFilter` sử dụng bằng attribute <<nsa-access-denied-handler-error-page,error-page>>, hoặc cung cấp implementation riêng bằng attribute <<nsa-access-denied-handler-ref,ref>>.
Nội dung này được thảo luận chi tiết hơn trong phần về xref:servlet/architecture.adoc#servlet-exceptiontranslationfilter[ExceptionTranslationFilter].


[[nsa-access-denied-handler-parents]]
=== Parent Element của <access-denied-handler>

* <<nsa-http,http>>

[[nsa-access-denied-handler-attributes]]
=== Attribute của <access-denied-handler>


[[nsa-access-denied-handler-error-page]]
* **error-page**
Trang access denied mà authenticated user sẽ được redirect đến nếu họ request một trang mà họ không có authority truy cập.


[[nsa-access-denied-handler-ref]]
* **ref**
Định nghĩa tham chiếu đến Spring bean kiểu `AccessDeniedHandler`.


[[nsa-cors]]
== <cors>
Element này cho phép cấu hình một `CorsFilter`.
Phải chỉ định `CorsFilter` hoặc `CorsConfigurationSource`.
Nếu có Spring MVC, hệ thống sẽ cố tra cứu `CorsConfigurationSource` của Spring MVC.

[[nsa-cors-attributes]]
=== Attribute của <cors>
Các attribute trên element `<cors>` kiểm soát các header.

[[nsa-cors-ref]]
* **ref**
Attribute tùy chọn chỉ định tên bean của một `CorsFilter`.

[[nsa-cors-configuration-source-ref]]
* **cors-configuration-source-ref**
Attribute tùy chọn chỉ định tên bean của `CorsConfigurationSource` được inject vào `CorsFilter` do XML namespace tạo ra.

[[nsa-cors-parents]]
=== Parent Element của <cors>

* <<nsa-http,http>>

[[nsa-headers]]
== <headers>
Element này cho phép cấu hình các security header bổ sung được gửi cùng response.
Element này giúp dễ dàng cấu hình một số header và cũng cho phép đặt header tùy chỉnh thông qua element <<nsa-header,header>>.
Có thể tìm thêm thông tin trong phần xref:features/exploits/headers.adoc#headers[Security Headers] của tài liệu tham chiếu.

** `Cache-Control`, `Pragma` và `Expires` - Có thể được đặt bằng element <<nsa-cache-control,cache-control>>.
Điều này bảo đảm browser không cache các trang được bảo vệ.
** `Strict-Transport-Security` - Có thể được đặt bằng element <<nsa-hsts,hsts>>.
Điều này bảo đảm browser tự động request HTTPS cho các request trong tương lai.
** `X-Frame-Options` - Có thể được đặt bằng element <<nsa-frame-options,frame-options>>.
Header https://en.wikipedia.org/wiki/Clickjacking#X-Frame-Options[X-Frame-Options] có thể được dùng để ngăn các cuộc tấn công clickjacking.
** `X-XSS-Protection` - Có thể được đặt bằng element <<nsa-xss-protection,xss-protection>>.
Header https://en.wikipedia.org/wiki/Cross-site_scripting[X-XSS-Protection ] có thể được browser dùng để thực hiện một số kiểm tra cơ bản.
** `X-Content-Type-Options` - Có thể được đặt bằng element <<nsa-content-type-options,content-type-options>>.
Header https://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[X-Content-Type-Options] ngăn Internet Explorer thực hiện MIME sniffing đối với response, khiến response có content-type khác với content-type đã khai báo.
Điều này cũng áp dụng cho Google Chrome khi download extension.
** `Public-Key-Pinning` hoặc `Public-Key-Pinning-Report-Only` - Có thể được đặt bằng element <<nsa-hpkp,hpkp>>.
Điều này cho phép website HTTPS chống lại việc bị attacker giả mạo bằng các certificate cấp sai hoặc gian lận theo cách khác.
** `Content-Security-Policy` hoặc `Content-Security-Policy-Report-Only` - Có thể được đặt bằng element <<nsa-content-security-policy,content-security-policy>>.
https://www.w3.org/TR/CSP2/[Content Security Policy (CSP)] là cơ chế mà web application có thể tận dụng để giảm thiểu lỗ hổng content injection, chẳng hạn cross-site scripting (XSS).
** `Referrer-Policy` - Có thể được đặt bằng element <<nsa-referrer-policy,referrer-policy>>, https://www.w3.org/TR/referrer-policy/[Referrer-Policy] là cơ chế mà web application có thể tận dụng để quản lý trường referrer, chứa trang cuối cùng mà user đã truy cập.
** `Feature-Policy` - Có thể được đặt bằng element <<nsa-feature-policy,feature-policy>>, https://wicg.github.io/feature-policy/[Feature-Policy] là cơ chế cho phép web developer chọn lọc bật, tắt và sửa đổi hành vi của một số API và web feature trong browser.
** `Cross-Origin-Opener-Policy` - Có thể được đặt bằng element <<nsa-cross-origin-opener-policy,cross-origin-opener-policy>>, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy[Cross-Origin-Opener-Policy] là cơ chế cho phép bảo đảm một top-level document không chia sẻ browsing context group với cross-origin document.
** `Cross-Origin-Embedder-Policy` - Có thể được đặt bằng element <<nsa-cross-origin-embedder-policy,cross-origin-embedder-policy>>, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy[Cross-Origin-Embedder-Policy] là cơ chế ngăn document tải các cross-origin resource không cấp quyền rõ ràng cho document.
** `Cross-Origin-Resource-Policy` - Có thể được đặt bằng element <<nsa-cross-origin-resource-policy,cross-origin-resource-policy>>, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy[Cross-Origin-Resource-Policy] là cơ chế cho phép browser chặn các no-cors request cross-origin/cross-site đến resource được chỉ định.

[[nsa-headers-attributes]]
=== Attribute của <headers>
Các attribute trên element `<headers>` kiểm soát các header.


[[nsa-headers-defaults-disabled]]
* **defaults-disabled**
Attribute tùy chọn chỉ định việc tắt các HTTP response header mặc định của Spring Security.
Mặc định là false (các header mặc định được bao gồm).

[[nsa-headers-disabled]]
* **disabled**
Attribute tùy chọn chỉ định việc tắt các HTTP response header của Spring Security.
Mặc định là false (các header được bật).


[[nsa-headers-parents]]
=== Parent Element của <headers>

* <<nsa-http,http>>



[[nsa-headers-children]]
=== Child Element của <headers>


* <<nsa-cache-control,cache-control>>
* <<nsa-content-security-policy,content-security-policy>>
* <<nsa-content-type-options,content-type-options>>
* <<nsa-cross-origin-embedder-policy,cross-origin-embedder-policy>>
* <<nsa-cross-origin-opener-policy,cross-origin-opener-policy>>
* <<nsa-cross-origin-resource-policy,cross-origin-resource-policy>>
* <<nsa-feature-policy,feature-policy>>
* <<nsa-frame-options,frame-options>>
* <<nsa-header,header>>
* <<nsa-hpkp,hpkp>>
* <<nsa-hsts,hsts>>
* <<nsa-permissions-policy,permission-policy>>
* <<nsa-referrer-policy,referrer-policy>>
* <<nsa-xss-protection,xss-protection>>



[[nsa-cache-control]]
== <cache-control>
Thêm các header `Cache-Control`, `Pragma` và `Expires` để bảo đảm browser không cache các trang được bảo vệ.


[[nsa-cache-control-attributes]]
=== Attribute của <cache-control>

[[nsa-cache-control-disabled]]
* **disabled**
Chỉ định có tắt Cache Control hay không.
Mặc định là false.


[[nsa-cache-control-parents]]
=== Parent Element của <cache-control>


* <<nsa-headers,headers>>



[[nsa-hsts]]
== <hsts>
Khi được bật, thêm header https://tools.ietf.org/html/rfc6797[Strict-Transport-Security] vào response cho mọi secure request.
Điều này cho phép server chỉ dẫn browser tự động sử dụng HTTPS cho các request trong tương lai.


[[nsa-hsts-attributes]]
=== Attribute của <hsts>

[[nsa-hsts-disabled]]
* **disabled**
Chỉ định có tắt Strict-Transport-Security hay không.
Mặc định là false.

[[nsa-hsts-include-subdomains]]
* **include-sub-domains**
Chỉ định có bao gồm subdomain hay không.
Mặc định là true.


[[nsa-hsts-max-age-seconds]]
* **max-age-seconds**
Chỉ định khoảng thời gian tối đa host được xem là Known HSTS Host.
Mặc định là một năm.


[[nsa-hsts-request-matcher-ref]]
* **request-matcher-ref**
Instance `RequestMatcher` được dùng để xác định có nên đặt header hay không.
Mặc định là khi HttpServletRequest.isSecure() trả về true.

[[nsa-hsts-preload]]
* **preload**
Chỉ định có bao gồm preload hay không.
Mặc định là false.

[[nsa-hsts-parents]]
=== Parent Element của <hsts>

* <<nsa-headers,headers>>



[[nsa-hpkp]]
== <hpkp>
Khi được bật, thêm header https://tools.ietf.org/html/rfc7469[Public Key Pinning Extension for HTTP] vào response cho mọi secure request.
Điều này cho phép website HTTPS chống lại việc bị attacker giả mạo bằng các certificate cấp sai hoặc gian lận theo cách khác.


[[nsa-hpkp-attributes]]
=== Attribute của <hpkp>

[[nsa-hpkp-disabled]]
* **disabled**
Chỉ định có tắt HTTP Public Key Pinning (HPKP) hay không.
Mặc định là true.

[[nsa-hpkp-include-subdomains]]
* **include-sub-domains**
Chỉ định có bao gồm subdomain hay không.
Mặc định là false.


[[nsa-hpkp-max-age-seconds]]
* **max-age-seconds**
Đặt giá trị cho directive max-age của header Public-Key-Pins.
Mặc định là 60 ngày.


[[nsa-hpkp-report-only]]
* **report-only**
Chỉ định browser chỉ nên báo cáo các lỗi validation pin.
Mặc định là true.


[[nsa-hpkp-report-uri]]
* **report-uri**
Chỉ định URI mà browser sẽ báo cáo các lỗi validation pin đến.


[[nsa-hpkp-parents]]
=== Parent Element của <hpkp>

* <<nsa-headers,headers>>


[[nsa-pins]]
== <pins>
Danh sách pin.


[[nsa-pins-children]]
=== Child Element của <pins>

* <<nsa-pin,pin>>


[[nsa-pin]]
== <pin>
Một pin được chỉ định bằng fingerprint SPKI được mã hóa base64 làm value và thuật toán cryptographic hash làm attribute.

[[nsa-pin-attributes]]
=== Attribute của <pin>

[[nsa-pin-algorithm]]
* **algorithm**
Thuật toán cryptographic hash.
Mặc định là SHA256.


[[nsa-pin-parents]]
=== Parent Element của <pin>

* <<nsa-pins,pins>>



[[nsa-content-security-policy]]
== <content-security-policy>
Khi được bật, thêm header https://www.w3.org/TR/CSP2/[Content Security Policy (CSP)] vào response.
CSP là cơ chế mà web application có thể tận dụng để giảm thiểu lỗ hổng content injection, chẳng hạn cross-site scripting (XSS).

[[nsa-content-security-policy-attributes]]
=== Attribute của <content-security-policy>

[[nsa-content-security-policy-policy-directives]]
* **policy-directives**
Các security policy directive cho header Content-Security-Policy; hoặc nếu report-only được đặt thành true thì header Content-Security-Policy-Report-Only được sử dụng.

[[nsa-content-security-policy-report-only]]
* **report-only**
Đặt thành true để bật header Content-Security-Policy-Report-Only, chỉ nhằm báo cáo các vi phạm policy.
Mặc định là false.

[[nsa-content-security-policy-parents]]
=== Parent Element của <content-security-policy>

* <<nsa-headers,headers>>



[[nsa-referrer-policy]]
== <referrer-policy>
Khi được bật, thêm header https://www.w3.org/TR/referrer-policy/[Referrer Policy] vào response.

[[nsa-referrer-policy-attributes]]
=== Attribute của <referrer-policy>

[[nsa-referrer-policy-policy]]
* **policy**
Policy cho header Referrer-Policy.
Mặc định là "no-referrer".

[[nsa-referrer-policy-parents]]
=== Parent Element của <referrer-policy>

* <<nsa-headers,headers>>



[[nsa-feature-policy]]
== <feature-policy>
Khi được bật, thêm header https://wicg.github.io/feature-policy/[Feature Policy] vào response.

[[nsa-feature-policy-attributes]]
=== Attribute của <feature-policy>

[[nsa-feature-policy-policy-directives]]
* **policy-directives**
Các security policy directive cho header Feature-Policy.

[[nsa-feature-policy-parents]]
=== Parent Element của <feature-policy>

* <<nsa-headers,headers>>



[[nsa-frame-options]]
== <frame-options>
Khi được bật, thêm https://tools.ietf.org/html/draft-ietf-websec-x-frame-options[X-Frame-Options header] vào response; điều này cho phép các browser mới hơn thực hiện một số kiểm tra security và ngăn các cuộc tấn công https://en.wikipedia.org/wiki/Clickjacking[clickjacking].


[[nsa-frame-options-attributes]]
=== Attribute của <frame-options>

[[nsa-frame-options-disabled]]
* **disabled**
Nếu bị tắt, header X-Frame-Options sẽ không được bao gồm.
Mặc định là false.

[[nsa-frame-options-policy]]
* **policy**
** `DENY` Trang không thể được hiển thị trong frame, bất kể site nào cố thực hiện điều đó.
Đây là giá trị mặc định khi frame-options-policy được chỉ định.
** `SAMEORIGIN` Trang chỉ có thể được hiển thị trong frame trên cùng origin với chính trang đó.

+

Nói cách khác, nếu chỉ định DENY, việc cố tải trang trong frame sẽ thất bại không chỉ khi được tải từ site khác mà cả khi được tải từ cùng site.
Ngược lại, nếu chỉ định SAMEORIGIN, bạn vẫn có thể dùng trang trong frame miễn là site đưa trang đó vào frame cũng là site cung cấp trang.



[[nsa-frame-options-parents]]
=== Parent Element của <frame-options>

* <<nsa-headers,headers>>

[[nsa-permissions-policy]]
== <permissions-policy>
Thêm https://w3c.github.io/webappsec-permissions-policy/[Permissions-Policy header] vào response.

[[nsa-permissions-policy-attributes]]
=== Attribute của <permissions-policy>

[[nsa-permissions-policy-policy]]
* **policy**
Giá trị policy cần ghi cho header `Permissions-Policy`.

[[nsa-permissions-policy-parents]]
=== Parent Element của <permissions-policy>

* <<nsa-headers,headers>>

[[nsa-xss-protection]]
== <xss-protection>
Thêm https://blogs.msdn.com/b/ie/archive/2008/07/02/ie8-security-part-iv-the-xss-filter.aspx[X-XSS-Protection header] vào response để hỗ trợ bảo vệ trước các cuộc tấn công https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)].
Điều này hoàn toàn không phải là biện pháp bảo vệ đầy đủ trước các cuộc tấn công XSS!


[[nsa-xss-protection-attributes]]
=== Attribute của <xss-protection>


[[nsa-xss-protection-disabled]]
* **xss-protection-disabled**
Không bao gồm header để bảo vệ trước https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)].


[[nsa-xss-protection-header-value]]
* **xss-protection-header-value**
Đặt value một cách tường minh cho header https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)].
Một trong các giá trị: "0", "1", "1; mode=block". Mặc định là "0".


[[nsa-xss-protection-parents]]
=== Parent Element của <xss-protection>

* <<nsa-headers,headers>>



[[nsa-content-type-options]]
== <content-type-options>
Thêm header X-Content-Type-Options với value `nosniff` vào response.
Điều này https://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[tắt MIME sniffing] cho IE8+ và Chrome extension.


[[nsa-content-type-options-attributes]]
=== Attribute của <content-type-options>

[[nsa-content-type-options-disabled]]
* **disabled**
Chỉ định có tắt Content Type Options hay không.
Mặc định là false.

[[nsa-content-type-options-parents]]
=== Parent Element của <content-type-options>


* <<nsa-headers,headers>>



[[nsa-cross-origin-embedder-policy]]
==== <cross-origin-embedder-policy>
Khi được bật, thêm header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy[Cross-Origin-Embedder-Policy] vào response.


[[nsa-cross-origin-embedder-policy-attributes]]
===== Attribute của <cross-origin-embedder-policy>

[[nsa-cross-origin-embedder-policy-policy]]
* **policy**
Policy cho header `Cross-Origin-Embedder-Policy`.

[[nsa-cross-origin-embedder-policy-parents]]
===== Parent Element của <cross-origin-embedder-policy>


* <<nsa-headers,headers>>



[[nsa-cross-origin-opener-policy]]
==== <cross-origin-opener-policy>
Khi được bật, thêm header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy[Cross-Origin-Opener-Policy] vào response.


[[nsa-cross-origin-opener-policy-attributes]]
===== Attribute của <cross-origin-opener-policy>

[[nsa-cross-origin-opener-policy-policy]]
* **policy**
Policy cho header `Cross-Origin-Opener-Policy`.

[[nsa-cross-origin-opener-policy-parents]]
===== Parent Element của <cross-origin-opener-policy>


* <<nsa-headers,headers>>



[[nsa-cross-origin-resource-policy]]
==== <cross-origin-resource-policy>
Khi được bật, thêm header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy[Cross-Origin-Resource-Policy] vào response.


[[nsa-cross-origin-resource-policy-attributes]]
===== Attribute của <cross-origin-resource-policy>

[[nsa-cross-origin-resource-policy-policy]]
* **policy**
Policy cho header `Cross-Origin-Resource-Policy`.

[[nsa-cross-origin-resource-policy-parents]]
===== Parent Element của <cross-origin-resource-policy>


* <<nsa-headers,headers>>



[[nsa-header]]
== <header>
Thêm header bổ sung vào response; cần chỉ định cả name và value.


[[nsa-header-attributes]]
=== Attribute của <header-attributes>


[[nsa-header-name]]
* **header-name**
`name` của header.


[[nsa-header-value]]
* **value**
`value` của header cần thêm.


[[nsa-header-ref]]
* **ref**
Tham chiếu đến implementation tùy chỉnh của interface `HeaderWriter`.


[[nsa-header-parents]]
=== Parent Element của <header>


* <<nsa-headers,headers>>



[[nsa-anonymous]]
== <anonymous>
Thêm `AnonymousAuthenticationFilter` vào stack và một `AnonymousAuthenticationProvider`.
Cần thiết nếu bạn sử dụng attribute `IS_AUTHENTICATED_ANONYMOUSLY`.


[[nsa-anonymous-parents]]
=== Parent Element của <anonymous>


* <<nsa-http,http>>



[[nsa-anonymous-attributes]]
=== Attribute của <anonymous>


[[nsa-anonymous-enabled]]
* **enabled**
Với thiết lập namespace mặc định, facility anonymous authentication được tự động bật.
Bạn có thể tắt facility này bằng property.


[[nsa-anonymous-granted-authority]]
* **granted-authority**
Authority được cấp sẽ gán cho anonymous request.
Thông thường, authority này được dùng để gán các role cụ thể cho anonymous request, sau đó có thể dùng trong các quyết định authorization.
Nếu không đặt, mặc định là `ROLE_ANONYMOUS`.


[[nsa-anonymous-key]]
* **key**
Key được chia sẻ giữa provider và filter.
Thông thường không cần đặt key này.
Nếu không đặt, key sẽ mặc định là một giá trị ngẫu nhiên an toàn được sinh ra.
Do đó, đặt giá trị này có thể cải thiện thời gian startup khi sử dụng chức năng anonymous, vì việc sinh giá trị ngẫu nhiên an toàn có thể mất thời gian.


[[nsa-anonymous-username]]
* **username**
Username sẽ được gán cho anonymous request.
Điều này cho phép xác định principal, có thể quan trọng đối với logging và auditing.
Nếu không đặt, mặc định là `anonymousUser`.


[[nsa-csrf]]
== <csrf>
Element này sẽ thêm cơ chế bảo vệ https://en.wikipedia.org/wiki/Cross-site_request_forgery[Cross Site Request Forgery (CSRF)] cho ứng dụng.
Element này cũng cập nhật `RequestCache` mặc định để chỉ replay request "GET" sau khi authentication thành công.
Có thể tìm thêm thông tin trong phần xref:features/exploits/csrf.adoc#csrf[Cross Site Request Forgery (CSRF)] của tài liệu tham chiếu.


[[nsa-csrf-parents]]
=== Parent Element của <csrf>


* <<nsa-http,http>>



[[nsa-csrf-attributes]]
=== Attribute của <csrf>

[[nsa-csrf-disabled]]
* **disabled**
Attribute tùy chọn chỉ định việc tắt cơ chế bảo vệ CSRF của Spring Security.
Mặc định là false (cơ chế bảo vệ CSRF được bật).
Bạn nên giữ cơ chế bảo vệ CSRF được bật.

[[nsa-csrf-token-repository-ref]]
* **token-repository-ref**
CsrfTokenRepository cần sử dụng.
Mặc định là `HttpSessionCsrfTokenRepository`.

[[nsa-csrf-request-handler-ref]]
* **request-handler-ref**
`CsrfTokenRequestHandler` tùy chọn cần sử dụng. Mặc định là `CsrfTokenRequestAttributeHandler`.

[[nsa-csrf-request-matcher-ref]]
* **request-matcher-ref**
Instance `RequestMatcher` được dùng để xác định có nên áp dụng CSRF hay không.
Mặc định là mọi HTTP method ngoại trừ "GET", "TRACE", "HEAD", "OPTIONS".


[[nsa-custom-filter]]
== <custom-filter>
Element này được dùng để thêm filter vào filter chain.
Element này không tạo thêm bean nào mà dùng để chọn bean kiểu `jakarta.servlet.Filter` đã được định nghĩa trong application context, rồi thêm bean đó vào một vị trí cụ thể trong filter chain do Spring Security duy trì.
Có thể tìm đầy đủ chi tiết trong xref:servlet/configuration/xml-namespace.adoc#ns-custom-filters[ chương namespace].


[[nsa-custom-filter-parents]]
=== Parent Element của <custom-filter>


* <<nsa-http,http>>



[[nsa-custom-filter-attributes]]
=== Attribute của <custom-filter>


[[nsa-custom-filter-after]]
* **after**
Filter ngay sau filter mà custom-filter sẽ được đặt trong chain.
Tính năng này chỉ cần thiết cho user nâng cao muốn đưa filter riêng vào security filter chain và có kiến thức về các filter Spring Security tiêu chuẩn.
Tên filter ánh xạ đến các implementation filter cụ thể của Spring Security.


[[nsa-custom-filter-before]]
* **before**
Filter ngay trước filter mà custom-filter sẽ được đặt trong chain.


[[nsa-custom-filter-position]]
* **position**
Vị trí tường minh mà custom-filter sẽ được đặt trong chain.
Dùng khi thay thế một filter tiêu chuẩn.


[[nsa-custom-filter-ref]]
* **ref**
Định nghĩa tham chiếu đến Spring bean triển khai `Filter`.


[[nsa-expression-handler]]
== <expression-handler>
Định nghĩa instance `SecurityExpressionHandler` sẽ được dùng nếu access-control dựa trên expression được bật.
Nếu không cung cấp, một implementation mặc định (không hỗ trợ ACL) sẽ được sử dụng.


[[nsa-expression-handler-parents]]
=== Parent Element của <expression-handler>


* xref:servlet/appendix/namespace/method-security.adoc#nsa-global-method-security[global-method-security]
* <<nsa-http,http>>
* xref:servlet/appendix/namespace/method-security.adoc#nsa-method-security[method-security]
* xref:servlet/appendix/namespace/websocket.adoc#nsa-websocket-message-broker[websocket-message-broker]



[[nsa-expression-handler-attributes]]
=== Attribute của <expression-handler>


[[nsa-expression-handler-ref]]
* **ref**
Định nghĩa tham chiếu đến Spring bean triển khai `SecurityExpressionHandler`.


[[nsa-form-login]]
== <form-login>
Được dùng để thêm `UsernamePasswordAuthenticationFilter` vào filter stack và `LoginUrlAuthenticationEntryPoint` vào application context nhằm cung cấp authentication theo yêu cầu.
Element này luôn được ưu tiên hơn các entry point khác do namespace tạo ra.
Nếu không cung cấp attribute, một login page sẽ được tự động tạo tại URL "/login" footnote:[
Tính năng này chỉ được cung cấp để thuận tiện và không dành cho production (nơi đã chọn view technology và có thể dùng technology đó để render login page tùy chỉnh).
Class `DefaultLoginPageGeneratingFilter` chịu trách nhiệm render login page và sẽ cung cấp form login cho cả form login thông thường và/hoặc OIDC nếu cần.
] Có thể tùy chỉnh hành vi bằng <<nsa-form-login-attributes, các Attribute của `<form-login>`>>.


[[nsa-form-login-parents]]
=== Parent Element của <form-login>


* <<nsa-http,http>>



[[nsa-form-login-attributes]]
=== Attribute của <form-login>


[[nsa-form-login-always-use-default-target]]
* **always-use-default-target**
Nếu đặt thành `true`, user sẽ luôn bắt đầu tại giá trị được cung cấp bởi <<nsa-form-login-default-target-url,default-target-url>>, bất kể họ đến login page bằng cách nào.
Ánh xạ đến property `alwaysUseDefaultTargetUrl` của `UsernamePasswordAuthenticationFilter`.
Giá trị mặc định là `false`.


[[nsa-form-login-authentication-details-source-ref]]
* **authentication-details-source-ref**
Tham chiếu đến `AuthenticationDetailsSource` được authentication filter sử dụng.


[[nsa-form-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
Có thể dùng thay cho <<nsa-form-login-authentication-failure-url,authentication-failure-url>>, cho phép toàn quyền kiểm soát luồng điều hướng sau khi authentication thất bại.
Giá trị phải là tên của bean `AuthenticationFailureHandler` trong application context.


[[nsa-form-login-authentication-failure-url]]
* **authentication-failure-url**
Ánh xạ đến property `authenticationFailureUrl` của `UsernamePasswordAuthenticationFilter`.
Định nghĩa URL mà browser sẽ redirect đến khi login thất bại.
Mặc định là `/login?error`; URL này sẽ được automatic login page generator tự động xử lý, render lại login page cùng thông báo lỗi.


[[nsa-form-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
Có thể dùng thay cho <<nsa-form-login-default-target-url,default-target-url>> và <<nsa-form-login-always-use-default-target,always-use-default-target>>, cho phép toàn quyền kiểm soát luồng điều hướng sau khi authentication thành công.
Giá trị phải là tên của bean `AuthenticationSuccessHandler` trong application context.
Mặc định, một implementation của `SavedRequestAwareAuthenticationSuccessHandler` được sử dụng và inject cùng <<nsa-form-login-default-target-url,default-target-url >>.


[[nsa-form-login-default-target-url]]
* **default-target-url**
Ánh xạ đến property `defaultTargetUrl` của `UsernamePasswordAuthenticationFilter`.
Nếu không đặt, giá trị mặc định là "/" (application root).
User sẽ được đưa đến URL này sau khi login, với điều kiện họ không được yêu cầu login khi đang cố truy cập secured resource; trong trường hợp đó, họ sẽ được đưa đến URL ban đầu đã request.


[[nsa-form-login-login-page]]
* **login-page**
URL được dùng để render login page.
Ánh xạ đến property `loginFormUrl` của `LoginUrlAuthenticationEntryPoint`.
Mặc định là "/login".


[[nsa-form-login-login-processing-url]]
* **login-processing-url**
Ánh xạ đến property `filterProcessesUrl` của `UsernamePasswordAuthenticationFilter`.
Giá trị mặc định là "/login".


[[nsa-form-login-password-parameter]]
* **password-parameter**
Tên request parameter chứa password.
Mặc định là "password".


[[nsa-form-login-username-parameter]]
* **username-parameter**
Tên request parameter chứa username.
Mặc định là "username".

[[nsa-form-login-authentication-success-forward-url]]
* **authentication-success-forward-url**
Ánh xạ `ForwardAuthenticationSuccessHandler` vào property `authenticationSuccessHandler` của `UsernamePasswordAuthenticationFilter`.


[[nsa-form-login-authentication-failure-forward-url]]
* **authentication-failure-forward-url**
Ánh xạ `ForwardAuthenticationFailureHandler` vào property `authenticationFailureHandler` của `UsernamePasswordAuthenticationFilter`.


[[nsa-oauth2-login]]
== <oauth2-login>
Feature xref:servlet/oauth2/login/index.adoc#oauth2login[OAuth 2.0 Login] cho phép cấu hình hỗ trợ authentication bằng OAuth 2.0 và/hoặc OpenID Connect 1.0 Provider.


[[nsa-oauth2-login-parents]]
=== Parent Element của <oauth2-login>

* <<nsa-http,http>>

[[nsa-oauth2-login-attributes]]
=== Attribute của <oauth2-login>


[[nsa-oauth2-login-client-registration-repository-ref]]
* **client-registration-repository-ref**
Tham chiếu đến `ClientRegistrationRepository`.


[[nsa-oauth2-login-authorized-client-repository-ref]]
* **authorized-client-repository-ref**
Tham chiếu đến `OAuth2AuthorizedClientRepository`.


[[nsa-oauth2-login-authorized-client-service-ref]]
* **authorized-client-service-ref**
Tham chiếu đến `OAuth2AuthorizedClientService`.


[[nsa-oauth2-login-authorization-request-repository-ref]]
* **authorization-request-repository-ref**
Tham chiếu đến `AuthorizationRequestRepository`.


[[nsa-oauth2-login-authorization-request-resolver-ref]]
* **authorization-request-resolver-ref**
Tham chiếu đến `OAuth2AuthorizationRequestResolver`.


[[nsa-oauth2-login-authorization-redirect-strategy-ref]]
* **authorization-redirect-strategy-ref**
Tham chiếu đến `RedirectStrategy` dùng cho authorization.


[[nsa-oauth2-login-access-token-response-client-ref]]
* **access-token-response-client-ref**
Tham chiếu đến `OAuth2AccessTokenResponseClient`.


[[nsa-oauth2-login-user-authorities-mapper-ref]]
* **user-authorities-mapper-ref**
Tham chiếu đến `GrantedAuthoritiesMapper`.


[[nsa-oauth2-login-user-service-ref]]
* **user-service-ref**
Tham chiếu đến `OAuth2UserService`.


[[nsa-oauth2-login-oidc-user-service-ref]]
* **oidc-user-service-ref**
Tham chiếu đến `OAuth2UserService` của OpenID Connect.


[[nsa-oauth2-login-login-processing-url]]
* **login-processing-url**
URI nơi filter xử lý authentication request.


[[nsa-oauth2-login-login-page]]
* **login-page**
URI đưa user đến login.


[[nsa-oauth2-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
Tham chiếu đến `AuthenticationSuccessHandler`.


[[nsa-oauth2-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
Tham chiếu đến `AuthenticationFailureHandler`.


[[nsa-oauth2-login-jwt-decoder-factory-ref]]
* **jwt-decoder-factory-ref**
Tham chiếu đến `JwtDecoderFactory` được `OidcAuthorizationCodeAuthenticationProvider` sử dụng.


[[nsa-oauth2-client]]
== <oauth2-client>
Cấu hình hỗ trợ xref:servlet/oauth2/client/index.adoc#oauth2client[OAuth 2.0 Client].


[[nsa-oauth2-client-parents]]
=== Parent Element của <oauth2-client>

* <<nsa-http,http>>

[[nsa-oauth2-client-attributes]]
=== Attribute của <oauth2-client>


[[nsa-oauth2-client-client-registration-repository-ref]]
* **client-registration-repository-ref**
Tham chiếu đến `ClientRegistrationRepository`.


[[nsa-oauth2-client-authorized-client-repository-ref]]
* **authorized-client-repository-ref**
Tham chiếu đến `OAuth2AuthorizedClientRepository`.


[[nsa-oauth2-client-authorized-client-service-ref]]
* **authorized-client-service-ref**
Tham chiếu đến `OAuth2AuthorizedClientService`.


[[nsa-oauth2-client-children]]
=== Child Element của <oauth2-client>

* <<nsa-authorization-code-grant,authorization-code-grant>>


[[nsa-authorization-code-grant]]
== <authorization-code-grant>
Cấu hình hỗ trợ cho xref:servlet/oauth2/client/authorization-grants.adoc#oauth2Client-auth-grant-support[OAuth 2.0 Authorization Code Grant].


[[nsa-authorization-code-grant-parents]]
=== Parent Element của <authorization-code-grant>

* <<nsa-oauth2-client,oauth2-client>>


[[nsa-authorization-code-grant-attributes]]
=== Attribute của <authorization-code-grant>


[[nsa-authorization-code-grant-authorization-request-repository-ref]]
* **authorization-request-repository-ref**
Tham chiếu đến `AuthorizationRequestRepository`.


[[nsa-authorization-code-grant-authorization-redirect-strategy-ref]]
* **authorization-redirect-strategy-ref**
Tham chiếu đến `RedirectStrategy` dùng cho authorization.


[[nsa-authorization-code-grant-authorization-request-resolver-ref]]
* **authorization-request-resolver-ref**
Tham chiếu đến `OAuth2AuthorizationRequestResolver`.


[[nsa-authorization-code-grant-access-token-response-client-ref]]
* **access-token-response-client-ref**
Tham chiếu đến `OAuth2AccessTokenResponseClient`.


[[nsa-client-registrations]]
== <client-registrations>
Element container cho các client được đăng ký (xref:servlet/oauth2/client/index.adoc#oauth2Client-client-registration[ClientRegistration]) với OAuth 2.0 hoặc OpenID Connect 1.0 Provider.


[[nsa-client-registrations-children]]
=== Child Element của <client-registrations>

* <<nsa-client-registration,client-registration>>
* <<nsa-provider,provider>>


[[nsa-client-registration]]
== <client-registration>
Đại diện cho một client được đăng ký với OAuth 2.0 hoặc OpenID Connect 1.0 Provider.


[[nsa-client-registration-parents]]
=== Parent Element của <client-registration>

* <<nsa-client-registrations,client-registrations>>


[[nsa-client-registration-attributes]]
=== Attribute của <client-registration>


[[nsa-client-registration-registration-id]]
* **registration-id**
ID xác định duy nhất `ClientRegistration`.


[[nsa-client-registration-client-id]]
* **client-id**
Client identifier.


[[nsa-client-registration-client-secret]]
* **client-secret**
Client secret.


[[nsa-client-registration-client-authentication-method]]
* **client-authentication-method**
Method được dùng để authenticate Client với Provider.
Các value được hỗ trợ là *client_secret_basic*, *client_secret_post*, *private_key_jwt*, *client_secret_jwt* và *none* https://tools.ietf.org/html/rfc6749#section-2.1[(public clients)].


[[nsa-client-registration-authorization-grant-type]]
* **authorization-grant-type**
OAuth 2.0 Authorization Framework định nghĩa bốn loại https://tools.ietf.org/html/rfc6749#section-1.3[Authorization Grant].
Các value được hỗ trợ là `authorization_code`, `client_credentials`, `password`, cũng như extension grant type `urn:ietf:params:oauth:grant-type:jwt-bearer`.


[[nsa-client-registration-redirect-uri]]
* **redirect-uri**
Redirect URI đã đăng ký của client mà _Authorization Server_ redirect user-agent của end-user đến sau khi end-user đã được authenticate và authorize để truy cập client.


[[nsa-client-registration-scope]]
* **scope**
Scope được client request trong flow Authorization Request, chẳng hạn `openid`, `email` hoặc `profile`.


[[nsa-client-registration-client-name]]
* **client-name**
Tên mô tả được dùng cho client.
Tên này có thể được dùng trong một số trường hợp, chẳng hạn khi hiển thị tên client trong login page được tự động sinh.

[[nsa-client-registration-provider-id]]
* **provider-id**
Tham chiếu đến provider liên kết. Có thể tham chiếu element `<provider>` hoặc dùng một trong các provider phổ biến (google, github, facebook, okta).


[[nsa-provider]]
== <provider>
Thông tin cấu hình cho OAuth 2.0 hoặc OpenID Connect 1.0 Provider.


[[nsa-provider-parents]]
=== Parent Element của <provider>

* <<nsa-client-registrations,client-registrations>>


[[nsa-provider-attributes]]
=== Attribute của <provider>


[[nsa-provider-provider-id]]
* **provider-id**
ID xác định duy nhất provider.


[[nsa-provider-authorization-uri]]
* **authorization-uri**
URI Authorization Endpoint của Authorization Server.


[[nsa-provider-token-uri]]
* **token-uri**
URI Token Endpoint của Authorization Server.


[[nsa-provider-user-info-uri]]
* **user-info-uri**
URI UserInfo Endpoint được dùng để truy cập claim/attribute của authenticated end-user.


[[nsa-provider-user-info-authentication-method]]
* **user-info-authentication-method**
Authentication method được dùng khi gửi access token đến UserInfo Endpoint.
Các value được hỗ trợ là *header*, *form* và *query*.


[[nsa-provider-user-info-user-name-attribute]]
* **user-info-user-name-attribute**
Tên attribute được trả về trong UserInfo Response, tham chiếu đến Name hoặc Identifier của end-user.


[[nsa-provider-jwk-set-uri]]
* **jwk-set-uri**
URI được dùng để lấy https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] Set từ Authorization Server; set này chứa các cryptographic key dùng để verify https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)] của ID Token và tùy chọn verify UserInfo Response.


[[nsa-provider-issuer-uri]]
* **issuer-uri**
URI được dùng để cấu hình ban đầu một `ClientRegistration` bằng discovery https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] của OpenID Connect Provider hoặc https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] của Authorization Server.

[[nsa-oauth2-resource-server]]
== <oauth2-resource-server>
Thêm `BearerTokenAuthenticationFilter`, `BearerTokenAuthenticationEntryPoint` và `BearerTokenAccessDeniedHandler` vào cấu hình.
Ngoài ra, phải chỉ định `<jwt>` hoặc `<opaque-token>`.

[[nsa-oauth2-resource-server-parents]]
=== Parent Element của <oauth2-resource-server>

* <<nsa-http,http>>

[[nsa-oauth2-resource-server-children]]
=== Child Element của <oauth2-resource-server>

* <<nsa-jwt,jwt>>
* <<nsa-opaque-token,opaque-token>>

[[nsa-oauth2-resource-server-attributes]]
=== Attribute của <oauth2-resource-server>

[[nsa-oauth2-resource-server-authentication-manager-resolver-ref]]
* **authentication-manager-resolver-ref**
Tham chiếu đến `AuthenticationManagerResolver` dùng để resolve `AuthenticationManager` tại thời điểm request.

[[nsa-oauth2-resource-server-bearer-token-resolver-ref]]
* **bearer-token-resolver-ref**
Tham chiếu đến `BearerTokenResolver` dùng để lấy bearer token từ request.
Không thể dùng cùng với `authentication-converter-ref`.

[[nsa-oauth2-resource-server-entry-point-ref]]
* **entry-point-ref**
Tham chiếu đến `AuthenticationEntryPoint` dùng để xử lý unauthorized request.

[[nsa-oauth2-resource-server-authentication-converter-ref]]
* **authentication-converter-ref**
Tham chiếu đến `AuthenticationConverter` dùng để chuyển request thành authentication.
Không thể dùng cùng với `bearer-token-resolver-ref`.

[[nsa-jwt]]
== <jwt>
Đại diện cho OAuth 2.0 Resource Server sẽ thực hiện authorization cho JWT.


[[nsa-jwt-parents]]
=== Parent Element của <jwt>

* <<nsa-oauth2-resource-server,oauth2-resource-server>>


[[nsa-jwt-attributes]]
=== Attribute của <jwt>

[[nsa-jwt-jwt-authentication-converter-ref]]
* **jwt-authentication-converter-ref**
Tham chiếu đến `Converter<Jwt, AbstractAuthenticationToken>`.

[[nsa-jwt-decoder-ref]]
* **jwt-decoder-ref**
Tham chiếu đến `JwtDecoder`. Đây là component ở mức cao hơn, ghi đè `jwk-set-uri`.

[[nsa-jwt-jwk-set-uri]]
* **jwk-set-uri**
JWK Set Uri được dùng để tải signing verification key từ OAuth 2.0 Authorization Server.

[[nsa-opaque-token]]
== <opaque-token>
Đại diện cho OAuth 2.0 Resource Server sẽ thực hiện authorization cho opaque token.

[[nsa-opaque-token-parents]]
=== Parent Element của <opaque-token>

* <<nsa-oauth2-resource-server,oauth2-resource-server>>

[[nsa-opaque-token-attributes]]
=== Attribute của <opaque-token>

[[nsa-opaque-token-introspector-ref]]
* **introspector-ref**
Tham chiếu đến `OpaqueTokenIntrospector`. Đây là component ở mức cao hơn, ghi đè `introspection-uri`, `client-id` và `client-secret`.

[[nsa-opaque-token-introspection-uri]]
* **introspection-uri**
Introspection URI được dùng để introspect thông tin của opaque token. Phải đi kèm `client-id` và `client-secret`.

[[nsa-opaque-token-client-id]]
* **client-id**
Client Id dùng cho client authentication với `introspection-uri` đã cung cấp.

[[nsa-opaque-token-client-secret]]
* **client-secret**
Client Secret dùng cho client authentication với `introspection-uri` đã cung cấp.

[[nsa-opaque-token-authentication-converter-ref]]
* **authentication-converter-ref**
Tham chiếu đến `OpaqueTokenAuthenticationConverter`. Chịu trách nhiệm chuyển kết quả introspection thành công thành một instance `Authentication`.


[[nsa-relying-party-registrations]]
== <relying-party-registrations>
Element container cho các relying party được đăng ký (xref:servlet/saml2/login/overview.adoc#servlet-saml2login-relyingpartyregistration[ClientRegistration]) với SAML 2.0 Identity Provider.

[[nsa-relying-party-registrations-attributes]]
=== Attribute của <relying-party-registrations>

[[nsa-relying-party-registrations-id]]
* **id**
ID xác định duy nhất `RelyingPartyRegistrationRepository`.

[[nsa-relying-party-registrations-children]]
=== Child Element của <relying-party-registrations>

* <<nsa-asserting-party,asserting-party>>
* <<nsa-relying-party-registration,relying-party-registration>>


[[nsa-relying-party-registration]]
== <relying-party-registration>
Đại diện cho relying party được đăng ký với SAML 2.0 Identity Provider.


[[nsa-relying-party-registration-parents]]
=== Parent Element của <relying-party-registration>

* <<nsa-relying-party-registrations,relying-party-registrations>>


[[nsa-relying-party-registration-attributes]]
=== Attribute của <relying-party-registration>


[[nsa-relying-party-registration-registration-id]]
* **registration-id**
ID xác định duy nhất `RelyingPartyRegistration`.

[[nsa-relying-party-registration-metadata-location]]
* **metadata-location**
Vị trí metadata của asserting party.

[[nsa-relying-party-registration-entity-id]]
* **client-id**
https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf#2.9%20EntityDescriptor[EntityID] của relying party.


[[nsa-relying-party-registration-assertion-consumer-service-location]]
* **assertion-consumer-service-location**
Location của AssertionConsumerService. Tương đương với value trong `&lt;AssertionConsumerService Location="..."/&gt;` của `&lt;SPSSODescriptor&gt;` của relying party.


[[nsa-relying-party-registration-assertion-consumer-service-binding]]
* **assertion-consumer-service-binding**
Binding của AssertionConsumerService. Tương đương với value trong `&lt;AssertionConsumerService Binding="..."/&gt;` của `&lt;SPSSODescriptor&gt;` của relying party.
Các value được hỗ trợ là *POST* và *REDIRECT*.

[[nsa-relying-party-registration-single-logout-service-location]]
* **single-logout-service-location**
Location của SingleLogoutService. Tương đương với value trong &lt;SingleLogoutService Location="..."/&gt; của &lt;SPSSODescriptor&gt; của relying party.

[[nsa-relying-party-registration-single-logout-service-response-location]]
* **single-logout-service-response-location**
ResponseLocation của SingleLogoutService. Tương đương với value trong &lt;SingleLogoutService ResponseLocation="..."/&gt; của &lt;SPSSODescriptor&gt; của relying party.

[[nsa-relying-party-registration-single-logout-service-binding]]
* **single-logout-service-binding**
Binding của SingleLogoutService. Tương đương với value trong &lt;SingleLogoutService Binding="..."/&gt; của &lt;SPSSODescriptor&gt; của relying party.
Các value được hỗ trợ là *POST* và *REDIRECT*.

[[nsa-relying-party-registration-asserting-party-id]]
* **asserting-party-id**
Tham chiếu đến asserting party liên kết. Phải tham chiếu đến element `<asserting-party>`.

[[nsa-relying-party-registration-children]]
=== Child Element của <relying-party-registration>

* <<nsa-decryption-credential,decryption-credential>>
* <<nsa-signing-credential,signing-credential>>


[[nsa-decryption-credential]]
== <decryption-credential>
Decryption credential được liên kết với relying party.


[[nsa-decryption-credential-parents]]
=== Parent Element của <decryption-credential>

* <<nsa-relying-party-registration,relying-party-registration>>


[[nsa-decryption-credential-attributes]]
=== Attribute của <decryption-credential>


[[nsa-decryption-credential-certificate-location]]
* **certificate-location**
Vị trí lấy certificate.

[[nsa-decryption-credential-private-key-location]]
* **private-key-location**
Vị trí lấy private key của Relying Party.


[[nsa-signing-credential]]
== <signing-credential>
Signing credential được liên kết với relying party.


[[nsa-signing-credential-parents]]
=== Parent Element của <verification-credential>

* <<nsa-relying-party-registration,relying-party-registration>>


[[nsa-signing-credential-attributes]]
=== Attribute của <verification-credential>


[[nsa-signing-credential-certificate-location]]
* **certificate-location**
Vị trí lấy certificate này.

[[nsa-signing-credential-private-key-location]]
* **private-key-location**
Vị trí lấy private key của Relying Party.



[[nsa-asserting-party]]
== <asserting-party>
Thông tin cấu hình cho SAML 2.0 Asserting Party.


[[nsa-asserting-party-parents]]
=== Parent Element của <asserting-party>

* <<nsa-relying-party-registrations,relying-party-registrations>>


[[nsa-asserting-party-attributes]]
=== Attribute của <asserting-party>


[[nsa-asserting-party-asserting-party-id]]
* **asserting-party-id**
ID xác định duy nhất asserting party.


[[nsa-asserting-party-entity-id]]
* **entity-id**
EntityID của Asserting Party.


[[nsa-asserting-party-want-authn-requests-signed]]
* **want-authn-requests-signed**
Thiết lập `WantAuthnRequestsSigned`, cho biết asserting party muốn relying party ký `AuthnRequest` trước khi gửi.


[[nsa-asserting-party-single-sign-on-service-location]]
* **single-sign-on-service-location**
Vị trí https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf#2.5%20Endpoint[SingleSignOnService].


[[nsa-asserting-party-single-sign-on-service-binding]]
* **single-sign-on-service-binding**
Binding https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf#2.5%20Endpoint[SingleSignOnService].
Các value được hỗ trợ là *POST* và *REDIRECT*.


[[nsa-asserting-party-signing-algorithms]]
* **signing-algorithms**
Danh sách algorithm `org.opensaml.saml.ext.saml2alg.SigningMethod` cho asserting party này, theo thứ tự ưu tiên.


[[nsa-asserting-party-single-logout-service-location]]
* **single-logout-service-location**
Location của SingleLogoutService. Tương đương với value trong &lt;SingleLogoutService Location="..."/&gt; của &lt;IDPSSODescriptor&gt; của asserting party.


[[nsa-asserting-party-single-logout-service-response-location]]
* **single-logout-service-response-location**
ResponseLocation của SingleLogoutService. Tương đương với value trong &lt;SingleLogoutService ResponseLocation="..."/&gt; của &lt;IDPSSODescriptor&gt; của asserting party.


[[nsa-asserting-party-single-logout-service-binding]]
* **single-logout-service-binding**
Binding của SingleLogoutService. Tương đương với value trong &lt;SingleLogoutService Binding="..."/&gt; của &lt;IDPSSODescriptor&gt; của asserting party.
Các value được hỗ trợ là *POST* và *REDIRECT*.


[[nsa-asserting-party-children]]
=== Child Element của <asserting-party>

* <<nsa-encryption-credential,encryption-credential>>
* <<nsa-verification-credential,verification-credential>>


[[nsa-encryption-credential]]
== <encryption-credential>
Encryption credential liên kết với asserting party.


[[nsa-encryption-credential-parents]]
=== Parent Element của <encryption-credential>

* <<nsa-asserting-party,asserting-party>>


[[nsa-encryption-credential-attributes]]
=== Attribute của <encryption-credential>


[[nsa-encryption-credential-certificate-location]]
* **certificate-location**
Vị trí lấy certificate.

[[nsa-encryption-credential-private-key-location]]
* **private-key-location**
Vị trí lấy private key của Relying Party.


[[nsa-verification-credential]]
== <verification-credential>
Verification credential liên kết với asserting party.


[[nsa-verification-credential-parents]]
=== Parent Element của <verification-credential>

* <<nsa-asserting-party,asserting-party>>


[[nsa-verification-credential-attributes]]
=== Attribute của <verification-credential>


[[nsa-verification-credential-certificate-location]]
* **certificate-location**
Vị trí lấy certificate này.

[[nsa-verification-credential-private-key-location]]
* **private-key-location**
Vị trí lấy private key của Relying Party.



[[nsa-http-basic]]
== <http-basic>
Thêm `BasicAuthenticationFilter` và `BasicAuthenticationEntryPoint` vào cấu hình.
`BasicAuthenticationEntryPoint` chỉ được dùng làm entry point của cấu hình nếu form-based login không được bật.


[[nsa-http-basic-parents]]
=== Parent Element của <http-basic>


* <<nsa-http,http>>



[[nsa-http-basic-attributes]]
=== Attribute của <http-basic>


[[nsa-http-basic-authentication-details-source-ref]]
* **authentication-details-source-ref**
Tham chiếu đến `AuthenticationDetailsSource` được authentication filter sử dụng.


[[nsa-http-basic-entry-point-ref]]
* **entry-point-ref**
Thiết lập `AuthenticationEntryPoint` được `BasicAuthenticationFilter` sử dụng.


[[nsa-http-firewall]]
== Element <http-firewall>
Đây là top-level element có thể được dùng để inject implementation tùy chỉnh của `HttpFirewall` vào `FilterChainProxy` do namespace tạo ra.
Implementation mặc định phù hợp với hầu hết ứng dụng.


[[nsa-http-firewall-attributes]]
=== Attribute của <http-firewall>


[[nsa-http-firewall-ref]]
* **ref**
Định nghĩa tham chiếu đến Spring bean triển khai `HttpFirewall`.


[[nsa-intercept-url]]
== <intercept-url>
Element này được dùng để định nghĩa tập URL pattern mà ứng dụng quan tâm và cấu hình cách xử lý chúng.
Element này được dùng để xây dựng `FilterInvocationSecurityMetadataSource` mà `FilterSecurityInterceptor` sử dụng.
Element này cũng chịu trách nhiệm cấu hình `ChannelProcessingFilter` nếu, chẳng hạn, một số URL cần được truy cập bằng HTTPS.
Khi match các pattern đã chỉ định với request đi vào, việc matching được thực hiện theo thứ tự khai báo các element.
Vì vậy, pattern cụ thể nhất nên đứng trước và pattern tổng quát nhất đứng sau cùng.


[[nsa-intercept-url-parents]]
=== Parent Element của <intercept-url>


* <<nsa-filter-security-metadata-source,filter-security-metadata-source>>
* <<nsa-http,http>>



[[nsa-intercept-url-attributes]]
=== Attribute của <intercept-url>


[[nsa-intercept-url-access]]
* **access**
Liệt kê các access attribute sẽ được lưu trong `FilterInvocationSecurityMetadataSource` cho tổ hợp URL pattern/method đã định nghĩa.
Đây phải là danh sách phân tách bằng dấu phẩy gồm các security configuration attribute (chẳng hạn tên role).


[[nsa-intercept-url-method]]
* **method**
HTTP method được dùng kết hợp với pattern và servlet path (tùy chọn) để match request đi vào.
Nếu bỏ qua, mọi method đều match.
Nếu một pattern giống hệt được chỉ định cả có method và không có method, match cụ thể theo method sẽ được ưu tiên.


[[nsa-intercept-url-pattern]]
* **pattern**
Pattern định nghĩa URL path.
Nội dung phụ thuộc vào attribute `request-matcher` của element `<http>` chứa nó, vì vậy sẽ mặc định dùng MVC matcher nếu Spring MVC có trong classpath.


[[nsa-intercept-url-request-matcher-ref]]
* **request-matcher-ref**
Tham chiếu đến `RequestMatcher` được dùng để xác định có sử dụng `<intercept-url>` này hay không.


[[nsa-intercept-url-requires-channel]]
* **requires-channel**
Có thể là "http" hoặc "https", tùy thuộc vào việc URL pattern cụ thể nên được truy cập qua HTTP hay HTTPS tương ứng.
Ngoài ra, có thể dùng value "any" khi không có preference.
Nếu attribute này xuất hiện trên bất kỳ element `<intercept-url>` nào, một `ChannelProcessingFilter` sẽ được thêm vào filter stack và các dependency bổ sung của nó được thêm vào application context.

Nếu thêm cấu hình `<port-mappings>`, cấu hình này sẽ được các bean `SecureChannelProcessor` và `InsecureChannelProcessor` sử dụng để xác định port dùng khi redirect sang HTTP/HTTPS.

NOTE: Property này không hợp lệ với <<nsa-filter-security-metadata-source,filter-security-metadata-source>>

[[nsa-intercept-url-servlet-path]]
* **servlet-path**
Servlet path được dùng kết hợp với pattern và HTTP method để match request đi vào.
Attribute này chỉ áp dụng khi <<nsa-http-request-matcher,request-matcher>> là 'mvc'.
Ngoài ra, value chỉ bắt buộc trong 2 trường hợp sau: 1) Có từ 2 `HttpServlet` trở lên được đăng ký trong `ServletContext`, có mapping bắt đầu bằng `'/'` và khác nhau; 2) Pattern bắt đầu bằng cùng value với path của `HttpServlet` đã đăng ký, không tính `HttpServlet` mặc định (root) `'/'`.

NOTE: Property này không hợp lệ với <<nsa-filter-security-metadata-source,filter-security-metadata-source>>


[[nsa-jee]]
== <jee>
Thêm J2eePreAuthenticatedProcessingFilter vào filter chain để tích hợp với container authentication.


[[nsa-jee-parents]]
=== Parent Element của <jee>


* <<nsa-http,http>>



[[nsa-jee-attributes]]
=== Attribute của <jee>


[[nsa-jee-mappable-roles]]
* **mappable-roles**
Danh sách role phân tách bằng dấu phẩy cần tìm trong HttpServletRequest đi vào.


[[nsa-jee-user-service-ref]]
* **user-service-ref**
Tham chiếu đến ID của user-service (hoặc `UserDetailsService` bean).


[[nsa-logout]]
== <logout>
Thêm `LogoutFilter` vào filter stack.
Filter này được cấu hình bằng `SecurityContextLogoutHandler`.


[[nsa-logout-parents]]
=== Parent Element của <logout>


* <<nsa-http,http>>



[[nsa-logout-attributes]]
=== Attribute của <logout>


[[nsa-logout-delete-cookies]]
* **delete-cookies**
Danh sách phân tách bằng dấu phẩy gồm tên các cookie cần xóa khi user logout.


[[nsa-logout-invalidate-session]]
* **invalidate-session**
Ánh xạ đến `invalidateHttpSession` của `SecurityContextLogoutHandler`.
Mặc định là "true", vì vậy session sẽ bị invalidate khi logout.


[[nsa-logout-logout-success-url]]
* **logout-success-url**
URL đích mà user sẽ được đưa đến sau khi logout.
Mặc định là <form-login-login-page>/?logout (tức là /login?logout).

+

Đặt attribute này sẽ inject `SimpleRedirectInvalidSessionStrategy` được cấu hình bằng value của attribute vào `SessionManagementFilter`.
Khi một session ID không hợp lệ được gửi, strategy sẽ được gọi và redirect đến URL đã cấu hình.


[[nsa-logout-logout-url]]
* **logout-url**
URL sẽ gây logout (tức là được filter xử lý).
Mặc định là "/logout".


[[nsa-logout-success-handler-ref]]
* **success-handler-ref**
Có thể dùng để cung cấp instance `LogoutSuccessHandler`, được gọi để kiểm soát điều hướng sau khi logout.


[[nsa-saml2-login]]
== <saml2-login>
Feature xref:servlet/saml2/login/index.adoc#servlet-saml2login[SAML 2.0 Login] cho phép cấu hình hỗ trợ authentication bằng SAML 2.0 Service Provider.


[[nsa-saml2-login-parents]]
=== Parent Element của <saml2-login>

* <<nsa-http,http>>

[[nsa-saml2-login-attributes]]
=== Attribute của <saml2-login>


[[nsa-saml2-login-relying-party-registration-repository-ref]]
* **relying-party-registration-repository-ref**
Tham chiếu đến `RelyingPartyRegistrationRepository`.


[[nsa-saml2-login-authentication-request-repository-ref]]
* **authentication-request-repository-ref**
Tham chiếu đến `Saml2AuthenticationRequestRepository`.


[[nsa-saml2-login-authentication-request-resolver-ref]]
* **authentication-request-context-resolver-ref**
Tham chiếu đến `Saml2AuthenticationRequestResolver`.


[[nsa-saml2-login-authentication-converter-ref]]
* **authentication-converter-ref**
Tham chiếu đến `AuthenticationConverter`.


[[nsa-saml2-login-login-processing-url]]
* **login-processing-url**
URI nơi filter xử lý authentication request.


[[nsa-saml2-login-login-page]]
* **login-page**
URI đưa user đến login.


[[nsa-saml2-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
Tham chiếu đến `AuthenticationSuccessHandler`.


[[nsa-saml2-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
Tham chiếu đến `AuthenticationFailureHandler`.


[[nsa-saml2-login-authentication-manager-ref]]
* **authentication-manager-ref**
Tham chiếu đến `AuthenticationManager`.


[[nsa-saml2-logout]]
== <saml2-logout>
Feature xref:servlet/saml2/logout.adoc#servlet-saml2login-logout[SAML 2.0 Single Logout] cấu hình hỗ trợ SAML 2.0 Single Logout do RP và AP khởi tạo.


[[nsa-saml2-logout-parents]]
=== Parent Element của <saml2-logout>

* <<nsa-http,http>>

[[nsa-saml2-logout-attributes]]
=== Attribute của <saml2-logout>


[[nsa-saml2-logout-logout-url]]
* **logout-url**
URL mà relying party hoặc asserting party có thể dùng để trigger logout.


[[nsa-saml2-logout-logout-request-url]]
* **logout-request-url**
URL mà asserting party có thể dùng để gửi SAML 2.0 Logout Request.


[[nsa-saml2-logout-logout-response-url]]
* **logout-response-url**
URL mà asserting party có thể dùng để gửi SAML 2.0 Logout Response.


[[nsa-saml2-logout-relying-party-registration-repository-ref]]
* **relying-party-registration-repository-ref**
Tham chiếu đến `RelyingPartyRegistrationRepository`.


[[nsa-saml2-logout-logout-request-validator-ref]]
* **logout-request-validator-ref**
Tham chiếu đến `Saml2LogoutRequestValidator`.


[[nsa-saml2-logout-logout-request-resolver-ref]]
* **logout-request-resolver-ref**
Tham chiếu đến `Saml2LogoutRequestResolver`.


[[nsa-saml2-logout-logout-request-repository-ref]]
* **logout-request-repository-ref**
Tham chiếu đến `Saml2LogoutRequestRepository`.


[[nsa-saml2-logout-logout-response-validator-ref]]
* **logout-response-validator-ref**
Tham chiếu đến `Saml2LogoutResponseValidator`.


[[nsa-saml2-logout-logout-response-resolver-ref]]
* **logout-response-resolver-ref**
Tham chiếu đến `Saml2LogoutResponseResolver`.



[[nsa-password-management]]
== <password-management>
Element này cấu hình password management.

[[nsa-password-management-parents]]
=== Parent Element của <password-management>

* <<nsa-http,http>>

[[nsa-password-management-attributes]]
=== Attribute của <password-management>

[[nsa-password-management-change-password-page]]
* **change-password-page**
Trang change password. Mặc định là "/change-password".

[[nsa-port-mappings]]
== <port-mappings>
Mặc định, một instance `PortMapperImpl` sẽ được thêm vào cấu hình để dùng khi redirect đến secure và insecure URL.
Có thể tùy chọn dùng element này để ghi đè các mapping mặc định do class đó định nghĩa.
Mỗi child element `<port-mapping>` định nghĩa một cặp port HTTP:HTTPS.
Các mapping mặc định là 80:443 và 8080:8443.
Có thể tìm ví dụ ghi đè các mapping này trong xref:servlet/exploits/http.adoc#servlet-http-redirect[Redirect đến HTTPS].


[[nsa-port-mappings-parents]]
=== Parent Element của <port-mappings>


* <<nsa-http,http>>



[[nsa-port-mappings-children]]
=== Child Element của <port-mappings>


* <<nsa-port-mapping,port-mapping>>



[[nsa-port-mapping]]
== <port-mapping>
Cung cấp cách map http port sang https port khi buộc redirect.


[[nsa-port-mapping-parents]]
=== Parent Element của <port-mapping>


* <<nsa-port-mappings,port-mappings>>



[[nsa-port-mapping-attributes]]
=== Attribute của <port-mapping>


[[nsa-port-mapping-http]]
* **http**
Http port cần dùng.


[[nsa-port-mapping-https]]
* **https**
HTTPS port cần dùng.


[[nsa-remember-me]]
== <remember-me>
Thêm `RememberMeAuthenticationFilter` vào stack.
Sau đó filter này sẽ được cấu hình bằng `TokenBasedRememberMeServices`, `PersistentTokenBasedRememberMeServices` hoặc bean do user chỉ định triển khai `RememberMeServices`, tùy thuộc vào thiết lập attribute.


[[nsa-remember-me-parents]]
=== Parent Element của <remember-me>


* <<nsa-http,http>>



[[nsa-remember-me-attributes]]
=== Attribute của <remember-me>


[[nsa-remember-me-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
Thiết lập property `authenticationSuccessHandler` trên `RememberMeAuthenticationFilter` nếu cần điều hướng tùy chỉnh.
Giá trị phải là tên của bean `AuthenticationSuccessHandler` trong application context.


[[nsa-remember-me-data-source-ref]]
* **data-source-ref**
Tham chiếu đến bean `DataSource`.
Nếu được đặt, `PersistentTokenBasedRememberMeServices` sẽ được dùng và cấu hình với instance `JdbcTokenRepositoryImpl`.


[[nsa-remember-me-remember-me-parameter]]
* **remember-me-parameter**
Tên request parameter bật hoặc tắt remember-me authentication.
Mặc định là "remember-me".
Ánh xạ đến property "parameter" của `AbstractRememberMeServices`.


[[nsa-remember-me-remember-me-cookie]]
* **remember-me-cookie**
Tên cookie lưu token cho remember-me authentication.
Mặc định là "remember-me".
Ánh xạ đến property "cookieName" của `AbstractRememberMeServices`.


[[nsa-remember-me-key]]
* **key**
Ánh xạ đến property "key" của `AbstractRememberMeServices`.
Nên đặt thành một value duy nhất để bảo đảm remember-me cookie chỉ hợp lệ trong một application footnote:[
Điều này không ảnh hưởng đến việc sử dụng `PersistentTokenBasedRememberMeServices`, trong đó token được lưu ở phía server.
].
Nếu không đặt, một giá trị ngẫu nhiên an toàn sẽ được sinh ra.
Vì việc sinh giá trị ngẫu nhiên an toàn có thể mất thời gian, đặt tường minh value này có thể cải thiện thời gian startup khi sử dụng chức năng remember-me.


[[nsa-remember-me-services-alias]]
* **services-alias**
Export `RememberMeServices` được định nghĩa nội bộ dưới dạng bean alias, cho phép các bean khác trong application context sử dụng.


[[nsa-remember-me-services-ref]]
* **services-ref**
Cho phép toàn quyền kiểm soát implementation `RememberMeServices` mà filter sử dụng.
Giá trị phải là `id` của bean trong application context triển khai interface này.
Bean cũng nên triển khai `LogoutHandler` nếu đang sử dụng logout filter.


[[nsa-remember-me-token-repository-ref]]
* **token-repository-ref**
Cấu hình `PersistentTokenBasedRememberMeServices` nhưng cho phép sử dụng bean `PersistentTokenRepository` tùy chỉnh.


[[nsa-remember-me-token-validity-seconds]]
* **token-validity-seconds**
Ánh xạ đến property `tokenValiditySeconds` của `AbstractRememberMeServices`.
Chỉ định khoảng thời gian tính bằng giây mà remember-me cookie có hiệu lực.
Mặc định cookie có hiệu lực trong 14 ngày.


[[nsa-remember-me-use-secure-cookie]]
* **use-secure-cookie**
Khuyến nghị chỉ gửi remember-me cookie qua HTTPS và do đó đánh dấu cookie là "secure".
Mặc định, secure cookie sẽ được dùng nếu connection mà login request đi qua là secure (như nên có).
Nếu đặt property này thành `false`, secure cookie sẽ không được dùng.
Đặt thành `true` sẽ luôn đặt secure flag trên cookie.
Attribute này ánh xạ đến property `useSecureCookie` của `AbstractRememberMeServices`.


[[nsa-remember-me-user-service-ref]]
* **user-service-ref**
Các implementation remember-me service cần truy cập `UserDetailsService`, vì vậy phải có một instance được định nghĩa trong application context.
Nếu chỉ có một instance, namespace configuration sẽ tự động chọn và sử dụng instance đó.
Nếu có nhiều instance, bạn có thể chỉ định tường minh bean `id` bằng attribute này.


[[nsa-request-cache]]
== Element <request-cache>
Thiết lập instance `RequestCache` mà `ExceptionTranslationFilter` dùng để lưu thông tin request trước khi gọi `AuthenticationEntryPoint`.


[[nsa-request-cache-parents]]
=== Parent Element của <request-cache>

* <<nsa-http,http>>

[[nsa-request-cache-attributes]]
=== Attribute của <request-cache>


[[nsa-request-cache-ref]]
* **ref**
Định nghĩa tham chiếu đến Spring bean là một `RequestCache`.


[[nsa-session-management]]
== <session-management>
Chức năng liên quan đến session management được triển khai bằng cách thêm `SessionManagementFilter` vào filter stack.


[[nsa-session-management-parents]]
=== Parent Element của <session-management>


* <<nsa-http,http>>



[[nsa-session-management-attributes]]
=== Attribute của <session-management>


[[nsa-session-management-authentication-strategy-explicit-invocation]]
* **authentication-strategy-explicit-invocation**
Đặt attribute này thành true nghĩa là `SessionManagementFilter` sẽ không được inject và bắt buộc phải gọi `SessionAuthenticationStrategy` một cách tường minh.

[[nsa-session-management-invalid-session-url]]
* **invalid-session-url**
Đặt attribute này sẽ inject `SimpleRedirectInvalidSessionStrategy` được cấu hình bằng value của attribute vào `SessionManagementFilter`.
Khi một session ID không hợp lệ được gửi, strategy sẽ được invoke và redirect đến URL đã cấu hình.

[[nsa-session-management-invalid-session-strategy-ref]]
* **invalid-session-url**
Cho phép inject instance `InvalidSessionStrategy` được `SessionManagementFilter` sử dụng.
Dùng attribute này hoặc `invalid-session-url`, không dùng cả hai.

[[nsa-session-management-session-authentication-error-url]]
* **session-authentication-error-url**
Định nghĩa URL của error page sẽ được hiển thị khi `SessionAuthenticationStrategy` ném exception.
Nếu không đặt, error code unauthorized (401) sẽ được trả về client.
Lưu ý attribute này không áp dụng nếu lỗi xảy ra trong form-based login, khi đó URL cho authentication failure sẽ được ưu tiên.


[[nsa-session-management-session-authentication-strategy-ref]]
* **session-authentication-strategy-ref**
Cho phép inject instance `SessionAuthenticationStrategy` được `SessionManagementFilter` sử dụng.


[[nsa-session-management-session-fixation-protection]]
* **session-fixation-protection**
Cho biết cách áp dụng cơ chế bảo vệ session fixation khi user authenticate.
Nếu đặt thành "none", không áp dụng cơ chế bảo vệ.
"newSession" tạo session rỗng mới, chỉ migrate các attribute liên quan đến Spring Security.
"migrateSession" tạo session mới và copy toàn bộ session attribute sang session mới.
Trong Servlet 3.1 (Java EE 7) và container mới hơn, chỉ định "changeSessionId" sẽ giữ session hiện tại và dùng cơ chế bảo vệ session fixation do container cung cấp (HttpServletRequest#changeSessionId()).
Mặc định là "changeSessionId" trong Servlet 3.1 và container mới hơn, "migrateSession" trong container cũ hơn.
Ném exception nếu dùng "changeSessionId" trong container cũ hơn.

+

Nếu cơ chế bảo vệ session fixation được bật, `SessionManagementFilter` được inject `DefaultSessionAuthenticationStrategy` đã cấu hình phù hợp.
Xem Javadoc của class này để biết thêm chi tiết.


[[nsa-session-management-children]]
=== Child Element của <session-management>


* <<nsa-concurrency-control,concurrency-control>>



[[nsa-concurrency-control]]
== <concurrency-control>
Thêm hỗ trợ concurrent session control, cho phép giới hạn số session đang hoạt động mà một user có thể có.
Một `ConcurrentSessionFilter` sẽ được tạo và `ConcurrentSessionControlAuthenticationStrategy` sẽ được dùng cùng `SessionManagementFilter`.
Nếu element `form-login` đã được khai báo, strategy object cũng sẽ được inject vào authentication filter đã tạo.
Một instance `SessionRegistry` (instance `SessionRegistryImpl`, trừ khi user muốn dùng bean tùy chỉnh) sẽ được tạo để strategy sử dụng.


[[nsa-concurrency-control-parents]]
=== Parent Element của <concurrency-control>


* <<nsa-session-management,session-management>>



[[nsa-concurrency-control-attributes]]
=== Attribute của <concurrency-control>


[[nsa-concurrency-control-error-if-maximum-exceeded]]
* **error-if-maximum-exceeded**
Nếu đặt thành "true", `SessionAuthenticationException` sẽ được ném khi user cố vượt quá số session tối đa được phép.
Hành vi mặc định là expire session ban đầu.


[[nsa-concurrency-control-expired-url]]
* **expired-url**
URL mà user sẽ được redirect đến nếu cố sử dụng session đã bị concurrent session controller "expired" vì user vượt quá số session được phép và đã login lại ở nơi khác.
Nên được đặt trừ khi `exception-if-maximum-exceeded` được đặt.
Nếu không cung cấp value, thông báo hết hạn sẽ được ghi trực tiếp vào response.

[[nsa-concurrency-control-expired-session-strategy-ref]]
* **expired-url**
Cho phép inject instance ExpiredSessionStrategy được ConcurrentSessionFilter sử dụng.

[[nsa-concurrency-control-max-sessions]]
* **max-sessions**
Ánh xạ đến property `maximumSessions` của `ConcurrentSessionControlAuthenticationStrategy`.
Chỉ định `-1` làm value để hỗ trợ số session không giới hạn.

[[nsa-concurrency-control-max-sessions-ref]]
* **max-sessions-ref**
Cho phép inject instance SessionLimit được ConcurrentSessionControlAuthenticationStrategy sử dụng.

[[nsa-concurrency-control-session-registry-alias]]
* **session-registry-alias**
Cũng có thể hữu ích khi có tham chiếu đến session registry nội bộ để dùng trong bean riêng hoặc admin interface.
Bạn có thể expose bean nội bộ bằng attribute `session-registry-alias`, đặt cho bean một tên có thể dùng ở nơi khác trong cấu hình.


[[nsa-concurrency-control-session-registry-ref]]
* **session-registry-ref**
User có thể cung cấp implementation `SessionRegistry` riêng bằng attribute `session-registry-ref`.
Các bean concurrent session control khác sẽ được wire để sử dụng implementation đó.


[[nsa-x509]]
== <x509>
Thêm hỗ trợ X.509 authentication.
Một `X509AuthenticationFilter` sẽ được thêm vào stack và một bean `Http403ForbiddenEntryPoint` sẽ được tạo.
Bean sau chỉ được dùng nếu không có authentication mechanism nào khác đang được sử dụng (chức năng duy nhất là trả về HTTP 403 error code).
Một `PreAuthenticatedAuthenticationProvider` cũng sẽ được tạo, delegate việc tải user authority cho `UserDetailsService`.


[[nsa-x509-parents]]
=== Parent Element của <x509>


* <<nsa-http,http>>



[[nsa-x509-attributes]]
=== Attribute của <x509>


[[nsa-x509-authentication-details-source-ref]]
* **authentication-details-source-ref**
Tham chiếu đến `AuthenticationDetailsSource`.

[[nsa-x509-principal-extractor-ref]]
* **principal-extractor-ref**
Tham chiếu đến `X509PrincipalExtractor` được authentication filter sử dụng.


[[nsa-x509-subject-principal-regex]]
* **subject-principal-regex**
Định nghĩa regular expression được dùng để trích xuất username từ certificate (để dùng với `UserDetailsService`).


[[nsa-x509-user-service-ref]]
* **user-service-ref**
Cho phép dùng `UserDetailsService` cụ thể với X.509 trong trường hợp có nhiều instance được cấu hình.
Nếu không đặt, hệ thống sẽ cố tự động tìm và sử dụng instance phù hợp.


[[nsa-filter-chain-map]]
== <filter-chain-map>
Được dùng để cấu hình tường minh một instance `FilterChainProxy` với `FilterChainMap`.


[[nsa-filter-chain-map-attributes]]
=== Attribute của <filter-chain-map>


[[nsa-filter-chain-map-request-matcher]]
* **request-matcher**
Định nghĩa strategy dùng để matching request đi vào.
Các tùy chọn hiện tại là 'ant' (cho ant path pattern), 'regex' cho regular expression và 'ciRegex' cho regular expression không phân biệt chữ hoa chữ thường.


[[nsa-filter-chain-map-children]]
=== Child Element của <filter-chain-map>


* <<nsa-filter-chain,filter-chain>>



[[nsa-filter-chain]]
== <filter-chain>
Được dùng để định nghĩa URL pattern cụ thể và danh sách filter áp dụng cho các URL match pattern đó.
Khi nhiều element filter-chain được tập hợp thành một danh sách để cấu hình FilterChainProxy, pattern cụ thể nhất phải được đặt ở đầu danh sách và pattern tổng quát nhất ở cuối.


[[nsa-filter-chain-parents]]
=== Parent Element của <filter-chain>


* <<nsa-filter-chain-map,filter-chain-map>>



[[nsa-filter-chain-attributes]]
=== Attribute của <filter-chain>


[[nsa-filter-chain-filters]]
* **filters**
Danh sách phân tách bằng dấu phẩy gồm các tham chiếu đến Spring bean triển khai `Filter`.
Value "none" nghĩa là không dùng `Filter` nào cho `FilterChain` này.


[[nsa-filter-chain-pattern]]
* **pattern**
Pattern tạo RequestMatcher kết hợp với <<nsa-filter-chain-map-request-matcher,request-matcher>>.


[[nsa-filter-chain-request-matcher-ref]]
* **request-matcher-ref**
Tham chiếu đến `RequestMatcher` được dùng để xác định có nên invoke filter nào từ attribute `filters` hay không.


[[nsa-filter-security-metadata-source]]
== <filter-security-metadata-source>
Được dùng để cấu hình tường minh bean FilterSecurityMetadataSource nhằm sử dụng với FilterSecurityInterceptor.
Thông thường chỉ cần khi bạn cấu hình tường minh `FilterChainProxy` thay vì dùng element `<http>`.
Các element `<intercept-url>` được dùng chỉ nên chứa attribute pattern, method và access.
Các attribute khác sẽ dẫn đến lỗi cấu hình.


[[nsa-filter-security-metadata-source-attributes]]
=== Attribute của <filter-security-metadata-source>


[[nsa-filter-security-metadata-source-id]]
* **id**
Bean identifier, được dùng để tham chiếu bean ở nơi khác trong context.


[[nsa-filter-security-metadata-source-request-matcher]]
* **request-matcher**
Định nghĩa strategy dùng để matching request đi vào.
Các tùy chọn hiện tại là 'ant' (cho ant path pattern), 'regex' cho regular expression và 'ciRegex' cho regular expression không phân biệt chữ hoa chữ thường.


[[nsa-filter-security-metadata-source-use-expressions]]
* **use-expressions**
Cho phép sử dụng expression trong attribute `access` của các element `<intercept-url>` thay cho danh sách configuration attribute truyền thống.
Mặc định là 'true'.
Nếu được bật, mỗi attribute phải chứa một Boolean expression duy nhất.
Nếu expression được đánh giá là 'true', quyền truy cập sẽ được cấp.


[[nsa-filter-security-metadata-source-children]]
=== Child Element của <filter-security-metadata-source>


* <<nsa-intercept-url,intercept-url>>
