[[nsa-ldap]]
= Các tùy chọn namespace LDAP
LDAP được trình bày khá chi tiết trong xref:servlet/authentication/passwords/ldap.adoc#servlet-authentication-ldap[chương riêng về LDAP].
Ở đây, chúng ta sẽ giải thích thêm cách các tùy chọn namespace ánh xạ tới các Spring bean.
Phần triển khai LDAP sử dụng Spring LDAP rộng rãi, vì vậy hiểu biết nhất định về API của dự án đó có thể hữu ích.


[[nsa-ldap-server]]
== Xác định LDAP Server bằng phần tử
`<ldap-server>`
Phần tử này thiết lập một `ContextSource` của Spring LDAP để các LDAP bean khác sử dụng, đồng thời xác định vị trí LDAP server và các thông tin khác (chẳng hạn như username và password nếu server không cho phép truy cập ẩn danh) để kết nối tới server đó.
Nó cũng có thể được dùng để tạo một embedded server phục vụ testing.
Chi tiết cú pháp của cả hai tùy chọn được trình bày trong xref:servlet/authentication/passwords/ldap.adoc#servlet-authentication-ldap[chương LDAP].
Triển khai thực tế của `ContextSource` là `DefaultSpringSecurityContextSource`, mở rộng class `LdapContextSource` của Spring LDAP.
Các attribute `manager-dn` và `manager-password` lần lượt ánh xạ tới các property `userDn` và `password` của class này.

Nếu chỉ có một server được định nghĩa trong application context, các bean LDAP do namespace định nghĩa khác sẽ tự động sử dụng server đó.
Nếu có nhiều server, bạn có thể cung cấp attribute "id" cho phần tử và tham chiếu tới server đó từ các namespace bean khác bằng attribute `server-ref`.
Đây chính là bean `id` của instance `ContextSource`, nếu bạn muốn sử dụng nó trong các Spring bean truyền thống khác.


[[nsa-ldap-server-attributes]]
=== Các attribute của phần tử <ldap-server>

[[nsa-ldap-server-mode]]
* **mode**
Chỉ định rõ embedded LDAP server sẽ được sử dụng. Giá trị duy nhất được hỗ trợ là `unboundid`. Theo mặc định, server sẽ được chọn dựa trên việc thư viện có sẵn trong classpath hay không.

[[nsa-ldap-server-id]]
* **id**
Một định danh bean, được dùng để tham chiếu đến bean ở nơi khác trong context.


[[nsa-ldap-server-ldif]]
* **ldif**
Chỉ định rõ resource file ldif cần load vào embedded LDAP server.
ldif phải là một Spring resource pattern (tức là classpath:init.ldif).
Mặc định là classpath*:*.ldif


[[nsa-ldap-server-manager-dn]]
* **manager-dn**
Username (DN) của identity người dùng "manager", được dùng để authenticate với một LDAP server (không phải embedded).
Nếu bỏ qua, truy cập ẩn danh sẽ được sử dụng.


[[nsa-ldap-server-manager-password]]
* **manager-password**
Mật khẩu cho manager DN.
Đây là giá trị bắt buộc nếu `manager-dn` được chỉ định.


[[nsa-ldap-server-port]]
* **port**
Chỉ định số cổng IP.
Ví dụ, được dùng để cấu hình embedded LDAP server.
Giá trị mặc định là 33389.


[[nsa-ldap-server-root]]
* **root**
Root suffix tùy chọn cho embedded LDAP server.
Mặc định là "dc=springframework,dc=org"


[[nsa-ldap-server-url]]
* **url**
Chỉ định URL của LDAP server khi không sử dụng embedded LDAP server.


[[nsa-ldap-authentication-provider]]
== <ldap-authentication-provider>
Phần tử này là cách viết rút gọn để tạo một instance `LdapAuthenticationProvider`.
Theo mặc định, phần tử này được cấu hình với một instance `BindAuthenticator` và một `DefaultAuthoritiesPopulator`.
Cũng như mọi authentication provider được định nghĩa bằng namespace, nó phải được bao gồm dưới dạng phần tử con của phần tử `authentication-provider`.


[[nsa-ldap-authentication-provider-parents]]
=== Các phần tử cha của <ldap-authentication-provider>


* xref:servlet/appendix/namespace/authentication-manager.adoc#nsa-authentication-manager[authentication-manager]



[[nsa-ldap-authentication-provider-attributes]]
=== Các attribute của <ldap-authentication-provider>


[[nsa-ldap-authentication-provider-group-role-attribute]]
* **group-role-attribute**
Tên LDAP attribute chứa tên role sẽ được dùng trong Spring Security.
Ánh xạ tới property `groupRoleAttribute` của ``DefaultLdapAuthoritiesPopulator``.
Mặc định là "cn".


[[nsa-ldap-authentication-provider-group-search-base]]
* **group-search-base**
Search base để tìm group membership.
Ánh xạ tới constructor argument `groupSearchBase` của ``DefaultLdapAuthoritiesPopulator``.
Mặc định là "" (tìm kiếm từ root).


[[nsa-ldap-authentication-provider-group-search-filter]]
* **group-search-filter**
Bộ lọc tìm kiếm group.
Ánh xạ tới property `groupSearchFilter` của ``DefaultLdapAuthoritiesPopulator``.
Mặc định là `+(uniqueMember={0})+`.
Tham số được thay thế là DN của user.


[[nsa-ldap-authentication-provider-role-prefix]]
* **role-prefix**
Một chuỗi prefix không rỗng sẽ được thêm vào các role string được load từ persistent storage.
Ánh xạ tới property `rolePrefix` của ``DefaultLdapAuthoritiesPopulator``.
Mặc định là "ROLE_".
Sử dụng giá trị "none" để không có prefix trong trường hợp giá trị mặc định không rỗng.


[[nsa-ldap-authentication-provider-server-ref]]
* **server-ref**
Server tùy chọn cần sử dụng.
Nếu bỏ qua và một LDAP server mặc định được đăng ký (bằng `<ldap-server>` không có Id), server đó sẽ được sử dụng.


[[nsa-ldap-authentication-provider-user-context-mapper-ref]]
* **user-context-mapper-ref**
Cho phép tùy chỉnh rõ ràng user object đã được load bằng cách chỉ định một UserDetailsContextMapper bean; bean này sẽ được gọi với thông tin context từ directory entry của user.


[[nsa-ldap-authentication-provider-user-details-class]]
* **user-details-class**
Cho phép chỉ định objectClass của user entry.
Nếu được đặt, framework sẽ cố load các attribute chuẩn cho class đã định nghĩa vào UserDetails object được trả về.


[[nsa-ldap-authentication-provider-user-dn-pattern]]
* **user-dn-pattern**
Nếu user nằm ở một vị trí cố định trong directory (tức là bạn có thể tính trực tiếp DN từ username mà không cần thực hiện directory search), bạn có thể dùng attribute này để ánh xạ trực tiếp tới DN.
Nó ánh xạ trực tiếp tới property `userDnPatterns` của `AbstractLdapAuthenticator`.
Giá trị là một pattern cụ thể dùng để xây dựng DN của user, ví dụ `+uid={0},ou=people+`.
Key `+{0}+` phải hiện diện và sẽ được thay thế bằng username.


[[nsa-ldap-authentication-provider-user-search-base]]
* **user-search-base**
Search base để tìm user.
Mặc định là "".
Chỉ được dùng với một 'user-search-filter'.

+

Nếu cần thực hiện search để định vị user trong directory, bạn có thể đặt các attribute này để kiểm soát search.
`BindAuthenticator` sẽ được cấu hình với một `FilterBasedLdapUserSearch`; các giá trị attribute ánh xạ trực tiếp tới hai argument đầu tiên trong constructor của bean đó.
Nếu không đặt các attribute này và không cung cấp `user-dn-pattern` làm phương án thay thế, các giá trị tìm kiếm mặc định là `+user-search-filter="(uid={0})"+` và `user-search-base=""` sẽ được sử dụng.


[[nsa-ldap-authentication-provider-user-search-filter]]
* **user-search-filter**
LDAP filter được dùng để tìm user (tùy chọn).
Ví dụ `+(uid={0})+`.
Tham số được thay thế là login name của user.

+

Nếu cần thực hiện search để định vị user trong directory, bạn có thể đặt các attribute này để kiểm soát search.
`BindAuthenticator` sẽ được cấu hình với một `FilterBasedLdapUserSearch`; các giá trị attribute ánh xạ trực tiếp tới hai argument đầu tiên trong constructor của bean đó.
Nếu không đặt các attribute này và không cung cấp `user-dn-pattern` làm phương án thay thế, các giá trị tìm kiếm mặc định là `+user-search-filter="(uid={0})"+` và `user-search-base=""` sẽ được sử dụng.


[[nsa-ldap-authentication-provider-children]]
=== Các phần tử con của <ldap-authentication-provider>


* <<nsa-password-compare,password-compare>>



[[nsa-password-compare]]
== <password-compare>
Phần tử này được dùng như phần tử con của `<ldap-provider>` và chuyển chiến lược authentication từ `BindAuthenticator` sang `PasswordComparisonAuthenticator`.


[[nsa-password-compare-parents]]
=== Các phần tử cha của <password-compare>


* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>



[[nsa-password-compare-attributes]]
=== Các attribute của <password-compare>


[[nsa-password-compare-hash]]
* **hash**
Xác định hashing algorithm được dùng cho password của user.
Chúng tôi đặc biệt khuyến cáo không dùng MD4 vì đây là một hashing algorithm rất yếu.


[[nsa-password-compare-password-attribute]]
* **password-attribute**
Attribute trong directory chứa password của user.
Mặc định là "userPassword".


[[nsa-password-compare-children]]
=== Các phần tử con của <password-compare>


* xref:servlet/appendix/namespace/authentication-manager.adoc#nsa-password-encoder[password-encoder]



[[nsa-ldap-user-service]]
== <ldap-user-service>
Phần tử này cấu hình một LDAP `UserDetailsService`.
Class được dùng là `LdapUserDetailsService`, kết hợp giữa một `FilterBasedLdapUserSearch` và một `DefaultLdapAuthoritiesPopulator`.
Các attribute mà nó hỗ trợ có cách sử dụng giống như trong `<ldap-provider>`.


[[nsa-ldap-user-service-attributes]]
=== Các attribute của <ldap-user-service>


[[nsa-ldap-user-service-cache-ref]]
* **cache-ref**
Xác định một tham chiếu tới cache để sử dụng với UserDetailsService.


[[nsa-ldap-user-service-group-role-attribute]]
* **group-role-attribute**
Tên LDAP attribute chứa tên role sẽ được dùng trong Spring Security.
Mặc định là "cn".


[[nsa-ldap-user-service-group-search-base]]
* **group-search-base**
Search base để tìm group membership.
Mặc định là "" (tìm kiếm từ root).


[[nsa-ldap-user-service-group-search-filter]]
* **group-search-filter**
Bộ lọc tìm kiếm group.
Mặc định là `+(uniqueMember={0})+`.
Tham số được thay thế là DN của user.


[[nsa-ldap-user-service-id]]
* **id**
Một định danh bean, được dùng để tham chiếu đến bean ở nơi khác trong context.


[[nsa-ldap-user-service-role-prefix]]
* **role-prefix**
Một chuỗi prefix không rỗng sẽ được thêm vào các role string được load từ persistent storage (ví dụ
"ROLE_").
Sử dụng giá trị "none" để không có prefix trong trường hợp giá trị mặc định không rỗng.


[[nsa-ldap-user-service-server-ref]]
* **server-ref**
Server tùy chọn cần sử dụng.
Nếu bỏ qua và một LDAP server mặc định được đăng ký (bằng `<ldap-server>` không có Id), server đó sẽ được sử dụng.


[[nsa-ldap-user-service-user-context-mapper-ref]]
* **user-context-mapper-ref**
Cho phép tùy chỉnh rõ ràng user object đã được load bằng cách chỉ định một UserDetailsContextMapper bean; bean này sẽ được gọi với thông tin context từ directory entry của user.


[[nsa-ldap-user-service-user-details-class]]
* **user-details-class**
Cho phép chỉ định objectClass của user entry.
Nếu được đặt, framework sẽ cố load các attribute chuẩn cho class đã định nghĩa vào UserDetails object được trả về.


[[nsa-ldap-user-service-user-search-base]]
* **user-search-base**
Search base để tìm user.
Mặc định là "".
Chỉ được dùng với một 'user-search-filter'.


[[nsa-ldap-user-service-user-search-filter]]
* **user-search-filter**
LDAP filter được dùng để tìm user (tùy chọn).
Ví dụ `+(uid={0})+`.
Tham số được thay thế là login name của user.
