= Bảo mật phương thức

[[nsa-method-security]]
== <method-security>
Phần tử này là phương thức chính để bổ sung hỗ trợ bảo mật các phương thức trên các bean Spring Security.
Có thể bảo mật các phương thức bằng cách sử dụng các annotation (được định nghĩa ở cấp interface hoặc class) hoặc bằng cách định nghĩa một tập pointcut.

[[nsa-method-security-attributes]]
=== Các thuộc tính của <method-security>

[[nsa-method-security-pre-post-enabled]]
* **pre-post-enabled**
Bật các annotation pre và post invocation của Spring Security (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize) cho application context này.
Mặc định là "true".

[[nsa-method-security-secured-enabled]]
* **secured-enabled**
Bật annotation @Secured của Spring Security cho application context này.
Mặc định là "false".

[[nsa-method-security-jsr250-enabled]]
* **jsr250-enabled**
Bật các authorization annotation JSR-250 (@RolesAllowed, @PermitAll, @DenyAll) cho application context này.
Mặc định là "false".

[[nsa-method-security-mode]]
* **mode**
Nếu được đặt thành "aspectj", AspectJ sẽ được sử dụng để intercept các lần gọi phương thức.

[[nsa-method-security-proxy-target-class]]
* **proxy-target-class**
Nếu là true, proxy dựa trên class sẽ được sử dụng thay cho proxy dựa trên interface.
Mặc định là "false".

[[nsa-method-security-security-context-holder-strategy-ref]]
* **security-context-holder-strategy-ref**
Chỉ định một SecurityContextHolderStrategy được sử dụng khi lấy SecurityContext.
Mặc định là giá trị được trả về bởi SecurityContextHolder.getContextHolderStrategy().

[[nsa-method-security-observation-registry-ref]]
* **observation-registry-ref**
Một tham chiếu đến `ObservationRegistry` được sử dụng cho `FilterChain` và các component liên quan

[[nsa-method-security-children]]
=== Các phần tử con của <method-security>

* xref:servlet/appendix/namespace/http.adoc#nsa-expression-handler[expression-handler]
* <<nsa-protect-pointcut,protect-pointcut>>

[[nsa-global-method-security]]
== <global-method-security>
Phần tử này là phương thức chính để bổ sung hỗ trợ bảo mật các phương thức trên các bean Spring Security.
Có thể bảo mật các phương thức bằng cách sử dụng các annotation (được định nghĩa ở cấp interface hoặc class) hoặc bằng cách định nghĩa một tập pointcut dưới dạng các phần tử con, sử dụng cú pháp AspectJ.


[[nsa-global-method-security-attributes]]
=== Các thuộc tính của <global-method-security>

[NOTE]
=====
`<global-method-security>` đã deprecated và được thay thế bằng `<method-security>`.
Nếu cần sử dụng `<global-method-security>`, hãy thêm dependency `spring-security-access` vào cấu hình build.
=====

[[nsa-global-method-security-access-decision-manager-ref]]
* **access-decision-manager-ref**
Bảo mật phương thức sử dụng cùng cấu hình `AccessDecisionManager` như web security, nhưng có thể ghi đè cấu hình này bằng thuộc tính này.
Mặc định, một implementation AffirmativeBased được sử dụng cùng với một RoleVoter và một AuthenticatedVoter.


[[nsa-global-method-security-authentication-manager-ref]]
* **authentication-manager-ref**
Một tham chiếu đến `AuthenticationManager` sẽ được sử dụng cho method security.


[[nsa-global-method-security-jsr250-annotations]]
* **jsr250-annotations**
Chỉ định có sử dụng các thuộc tính theo kiểu JSR-250 hay không (ví dụ: "RolesAllowed").
Điều này yêu cầu các class javax.annotation.security có trên classpath.
Đặt giá trị này thành true cũng thêm một `Jsr250Voter` vào `AccessDecisionManager`, vì vậy cần đảm bảo thực hiện việc này nếu bạn đang sử dụng một implementation tùy chỉnh và muốn sử dụng các annotation này.


[[nsa-global-method-security-metadata-source-ref]]
* **metadata-source-ref**
Có thể cung cấp một instance `MethodSecurityMetadataSource` bên ngoài; instance này sẽ được ưu tiên hơn các nguồn khác (chẳng hạn các annotation mặc định).


[[nsa-global-method-security-mode]]
* **mode**
Có thể đặt thuộc tính này thành "aspectj" để chỉ định sử dụng AspectJ thay cho Spring AOP mặc định.
Các phương thức được bảo mật phải được weave bằng `AnnotationSecurityAspect` từ module `spring-security-aspects`.

Điều quan trọng cần lưu ý là AspectJ tuân theo quy tắc của Java rằng các annotation trên interface không được kế thừa.
Điều này có nghĩa là các phương thức định nghĩa Security annotation trên interface sẽ không được bảo mật.
Thay vào đó, khi sử dụng AspectJ, bạn phải đặt Security annotation trên class.


[[nsa-global-method-security-order]]
* **order**
Cho phép đặt "order" của advice cho method security interceptor.


[[nsa-global-method-security-pre-post-annotations]]
* **pre-post-annotations**
Chỉ định có bật việc sử dụng các annotation pre và post invocation của Spring Security (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize) cho application context này hay không.
Mặc định là "disabled".


[[nsa-global-method-security-proxy-target-class]]
* **proxy-target-class**
Nếu là true, proxy dựa trên class sẽ được sử dụng thay cho proxy dựa trên interface.


[[nsa-global-method-security-run-as-manager-ref]]
* **run-as-manager-ref**
Một tham chiếu đến implementation `RunAsManager` tùy chọn sẽ được `MethodSecurityInterceptor` đã cấu hình sử dụng


[[nsa-global-method-security-secured-annotations]]
* **secured-annotations**
Chỉ định có bật việc sử dụng các annotation @Secured của Spring Security cho application context này hay không.
Mặc định là "disabled".


[[nsa-global-method-security-children]]
=== Các phần tử con của <global-method-security>


* <<nsa-after-invocation-provider,after-invocation-provider>>
* xref:servlet/appendix/namespace/http.adoc#nsa-expression-handler[expression-handler]
* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>
* <<nsa-protect-pointcut,protect-pointcut>>



[[nsa-after-invocation-provider]]
== <after-invocation-provider>
Phần tử này có thể được sử dụng để bọc một `AfterInvocationProvider` nhằm cho security interceptor do namespace `<global-method-security>` quản lý sử dụng.
Bạn có thể định nghĩa không hoặc nhiều phần tử như vậy bên trong phần tử `global-method-security`, mỗi phần tử có thuộc tính `ref` trỏ đến một instance bean `AfterInvocationProvider` trong application context.


[[nsa-after-invocation-provider-parents]]
=== Các phần tử cha của <after-invocation-provider>


* <<nsa-global-method-security,global-method-security>>



[[nsa-after-invocation-provider-attributes]]
=== Các thuộc tính của <after-invocation-provider>

[NOTE]
=====
`<after-invocation-provider>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PostFilter` và `@PostAuthorize`].
Nếu cần sử dụng `<after-invocation-provider>`, hãy thêm dependency `spring-security-access` vào cấu hình build trong khi lập kế hoạch chuyển sang một tùy chọn hiện đại hơn.
=====

[[nsa-after-invocation-provider-ref]]
* **ref**
Định nghĩa một tham chiếu đến Spring bean triển khai `AfterInvocationProvider`.


[[nsa-pre-post-annotation-handling]]
== <pre-post-annotation-handling>
Cho phép thay thế hoàn toàn cơ chế dựa trên expression mặc định để xử lý các annotation pre và post invocation của Spring Security (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize).
Chỉ áp dụng khi các annotation này được bật.


[[nsa-pre-post-annotation-handling-parents]]
=== Các phần tử cha của <pre-post-annotation-handling>


* <<nsa-global-method-security,global-method-security>>



[[nsa-pre-post-annotation-handling-children]]
=== Các phần tử con của <pre-post-annotation-handling>


* <<nsa-invocation-attribute-factory,invocation-attribute-factory>>
* <<nsa-post-invocation-advice,post-invocation-advice>>
* <<nsa-pre-invocation-advice,pre-invocation-advice>>



[[nsa-invocation-attribute-factory]]
== <invocation-attribute-factory>
Định nghĩa instance PrePostInvocationAttributeFactory được sử dụng để tạo metadata pre và post invocation từ các phương thức có annotation.

[NOTE]
=====
`<invocation-attribute-factory>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PostFilter` và `@PostAuthorize`].
Nếu cần sử dụng `<invocation-attribute-factory>`, hãy thêm dependency `spring-security-access` vào cấu hình build trong khi lập kế hoạch chuyển sang một tùy chọn hiện đại hơn.
=====

[[nsa-invocation-attribute-factory-parents]]
=== Các phần tử cha của <invocation-attribute-factory>


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-invocation-attribute-factory-attributes]]
=== Các thuộc tính của <invocation-attribute-factory>


[[nsa-invocation-attribute-factory-ref]]
* **ref**
Định nghĩa một tham chiếu đến Id của Spring bean.


[[nsa-post-invocation-advice]]
== <post-invocation-advice>
Tùy chỉnh `PostInvocationAdviceProvider`, sử dụng ref làm `PostInvocationAuthorizationAdvice` cho phần tử <pre-post-annotation-handling>.

[NOTE]
=====
`<post-invocation-advice>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PostFilter` và `@PostAuthorize`].
Nếu cần sử dụng `<post-invocation-advice>`, hãy thêm dependency `spring-security-access` vào cấu hình build trong khi lập kế hoạch chuyển sang một tùy chọn hiện đại hơn.
=====

[[nsa-post-invocation-advice-parents]]
=== Các phần tử cha của <post-invocation-advice>


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-post-invocation-advice-attributes]]
=== Các thuộc tính của <post-invocation-advice>


[[nsa-post-invocation-advice-ref]]
* **ref**
Định nghĩa một tham chiếu đến Id của Spring bean.


[[nsa-pre-invocation-advice]]
== <pre-invocation-advice>
Tùy chỉnh `PreInvocationAuthorizationAdviceVoter`, sử dụng ref làm `PreInvocationAuthorizationAdviceVoter` cho phần tử <pre-post-annotation-handling>.

[NOTE]
=====
`<pre-invocation-advice>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PreFilter` và `@PreAuthorize`].
Nếu cần sử dụng `<pre-invocation-advice>`, hãy thêm dependency `spring-security-access` vào cấu hình build trong khi lập kế hoạch chuyển sang một tùy chọn hiện đại hơn.
=====

[[nsa-pre-invocation-advice-parents]]
=== Các phần tử cha của <pre-invocation-advice>


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-pre-invocation-advice-attributes]]
=== Các thuộc tính của <pre-invocation-advice>


[[nsa-pre-invocation-advice-ref]]
* **ref**
Định nghĩa một tham chiếu đến Id của Spring bean.


[[nsa-protect-pointcut]]
== Bảo mật phương thức bằng
`<protect-pointcut>`
Thay vì định nghĩa các thuộc tính bảo mật riêng cho từng phương thức hoặc class bằng annotation `@Secured`, bạn có thể định nghĩa các ràng buộc bảo mật cross-cutting trên toàn bộ tập phương thức và interface trong service layer bằng phần tử `<protect-pointcut>`.
Bạn có thể tìm thấy ví dụ trong xref:servlet/authorization/method-security.adoc#ns-protect-pointcut[phần giới thiệu namespace].

[[nsa-protect-pointcut-parents]]
=== Các phần tử cha của <protect-pointcut>


* <<nsa-global-method-security,global-method-security>>
* <<nsa-method-security,method-security>>



[[nsa-protect-pointcut-attributes]]
=== Các thuộc tính của <protect-pointcut>


[[nsa-protect-pointcut-access]]
* **access**
Danh sách các thuộc tính cấu hình quyền truy cập áp dụng cho tất cả phương thức khớp với pointcut, ví dụ:
"ROLE_A,ROLE_B"


[[nsa-protect-pointcut-expression]]
* **expression**
Một expression AspectJ, bao gồm keyword `execution`.
Ví dụ: `execution(int com.foo.TargetObject.countLength(String))`.


[[nsa-intercept-methods]]
== <intercept-methods>
Có thể được sử dụng bên trong định nghĩa bean để thêm security interceptor vào bean và thiết lập các thuộc tính cấu hình quyền truy cập cho các phương thức của bean


[[nsa-intercept-methods-attributes]]
=== Các thuộc tính của <intercept-methods>

[[nsa-intercept-methods-use-authorization-manager]]
* **use-authorization-manager**
Sử dụng API AuthorizationManager thay vì AccessDecisionManager (mặc định là true)

[[nsa-intercept-methods-authorization-manager-ref]]
* **authorization-manager-ref**
ID bean AuthorizationManager tùy chọn được sử dụng thay cho giá trị mặc định (ghi đè use-authorization-manager)

[[nsa-intercept-methods-access-decision-manager-ref]]
* **access-decision-manager-ref**
ID bean AccessDecisionManager tùy chọn được method security interceptor được tạo sử dụng.

[[nsa-intercept-methods-children]]
=== Các phần tử con của <intercept-methods>


* <<nsa-protect,protect>>



[[nsa-method-security-metadata-source]]
== <method-security-metadata-source>
Tạo một instance MethodSecurityMetadataSource

[NOTE]
=====
`<method-security-metadata-source>` đã deprecated và được thay thế bằng xref:servlet/authorization/method-security.adoc[`<method-security>`].
Nếu cần sử dụng `<method-security-metadata-source>`, hãy thêm dependency `spring-security-access` vào cấu hình build trong khi lập kế hoạch chuyển sang một tùy chọn hiện đại hơn.
=====

[[nsa-method-security-metadata-source-attributes]]
=== Các thuộc tính của <method-security-metadata-source>


[[nsa-method-security-metadata-source-id]]
* **id**
Một định danh bean, được sử dụng để tham chiếu đến bean ở nơi khác trong context.


[[nsa-method-security-metadata-source-use-expressions]]
* **use-expressions**
Bật việc sử dụng expression trong các thuộc tính 'access' của phần tử <intercept-url> thay cho danh sách thuộc tính cấu hình truyền thống.
Mặc định là 'false'.
Nếu được bật, mỗi thuộc tính phải chứa một Boolean expression duy nhất.
Nếu expression được đánh giá là 'true', quyền truy cập sẽ được cấp.


[[nsa-method-security-metadata-source-children]]
=== Các phần tử con của <method-security-metadata-source>


* <<nsa-protect,protect>>



[[nsa-protect]]
== <protect>
Định nghĩa một phương thức được bảo vệ và các thuộc tính cấu hình access control áp dụng cho phương thức đó.
Chúng tôi đặc biệt khuyến cáo bạn KHÔNG trộn các khai báo "protect" với bất kỳ service nào do "global-method-security" cung cấp.


[[nsa-protect-parents]]
=== Các phần tử cha của <protect>


* <<nsa-intercept-methods,intercept-methods>>
* <<nsa-method-security-metadata-source,method-security-metadata-source>>



[[nsa-protect-attributes]]
=== Các thuộc tính của <protect>


[[nsa-protect-access]]
* **access**
Danh sách các thuộc tính cấu hình quyền truy cập áp dụng cho phương thức, ví dụ:
"ROLE_A,ROLE_B".


[[nsa-protect-method]]
* **method**
Tên phương thức
