= Bảo mật phương thức

[[nsa-method-security]]
== <method-security>
Đây là cách chính để bổ sung khả năng bảo vệ method trên các Spring Security bean.
Có thể bảo vệ method bằng annotation (được định nghĩa ở cấp interface hoặc class) hoặc bằng cách định nghĩa một tập pointcut.

[[nsa-method-security-attributes]]
=== Các attribute của <method-security>

[[nsa-method-security-pre-post-enabled]]
* **pre-post-enabled**
Bật các annotation pre-invocation và post-invocation của Spring Security (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize) cho application context này.
Mặc định là "true".

[[nsa-method-security-secured-enabled]]
* **secured-enabled**
Bật annotation @Secured của Spring Security cho application context này.
Mặc định là "false".

[[nsa-method-security-jsr250-enabled]]
* **jsr250-enabled**
Bật các authorization annotation JSR-250 (@RolesAllowed, @PermitAll, @DenyAll) cho application context này.
Mặc định là "false".

[[nsa-method-security-mode]]
* **mode**
Nếu đặt thành "aspectj", AspectJ sẽ được dùng để intercept các method invocation.

[[nsa-method-security-proxy-target-class]]
* **proxy-target-class**
Nếu là true, proxy dựa trên class sẽ được dùng thay cho proxy dựa trên interface.
Mặc định là "false".

[[nsa-method-security-security-context-holder-strategy-ref]]
* **security-context-holder-strategy-ref**
Chỉ định một SecurityContextHolderStrategy dùng để lấy SecurityContext.
Mặc định là giá trị được trả về bởi SecurityContextHolder.getContextHolderStrategy().

[[nsa-method-security-observation-registry-ref]]
* **observation-registry-ref**
Một reference đến `ObservationRegistry` được dùng cho `FilterChain` và các component liên quan.

[[nsa-method-security-children]]
=== Các child element của <method-security>

* xref:servlet/appendix/namespace/http.adoc#nsa-expression-handler[expression-handler]
* <<nsa-protect-pointcut,protect-pointcut>>

[[nsa-global-method-security]]
== <global-method-security>
Đây là cách chính để bổ sung khả năng bảo vệ method trên các Spring Security bean.
Có thể bảo vệ method bằng annotation (được định nghĩa ở cấp interface hoặc class) hoặc bằng cách định nghĩa một tập pointcut dưới dạng child element, sử dụng cú pháp AspectJ.


[[nsa-global-method-security-attributes]]
=== Các attribute của <global-method-security>

[NOTE]
=====
`<global-method-security>` đã deprecated và được thay thế bằng `<method-security>`.
Nếu cần dùng `<global-method-security>`, hãy thêm dependency `spring-security-access` vào build configuration.
=====

[[nsa-global-method-security-access-decision-manager-ref]]
* **access-decision-manager-ref**
Method security dùng cùng configuration `AccessDecisionManager` với web security, nhưng có thể override bằng attribute này.
Mặc định, một implementation AffirmativeBased được dùng cùng với một RoleVoter và một AuthenticatedVoter.


[[nsa-global-method-security-authentication-manager-ref]]
* **authentication-manager-ref**
Một reference đến `AuthenticationManager` sẽ được dùng cho method security.


[[nsa-global-method-security-jsr250-annotations]]
* **jsr250-annotations**
Chỉ định có dùng các attribute theo style JSR-250 hay không (ví dụ: "RolesAllowed").
Điều này yêu cầu các class javax.annotation.security có trên classpath.
Đặt thành true cũng thêm một `Jsr250Voter` vào `AccessDecisionManager`, vì vậy nếu đang dùng một custom implementation và muốn dùng các annotation này, cần bảo đảm implementation đó cũng thêm voter này.


[[nsa-global-method-security-metadata-source-ref]]
* **metadata-source-ref**
Có thể cung cấp một instance `MethodSecurityMetadataSource` từ bên ngoài; instance này sẽ được ưu tiên hơn các source khác (chẳng hạn các default annotation).


[[nsa-global-method-security-mode]]
* **mode**
Có thể đặt attribute này thành "aspectj" để chỉ định dùng AspectJ thay cho Spring AOP mặc định.
Các method được secure phải được weave bằng `AnnotationSecurityAspect` từ module `spring-security-aspects`.

Điều quan trọng cần lưu ý là AspectJ tuân theo rule của Java rằng annotation trên interface không được kế thừa.
Điều này có nghĩa là các method khai báo Security annotation trên interface sẽ không được secure.
Thay vào đó, khi dùng AspectJ, phải đặt Security annotation trên class.


[[nsa-global-method-security-order]]
* **order**
Cho phép thiết lập "order" của advice cho method security interceptor.


[[nsa-global-method-security-pre-post-annotations]]
* **pre-post-annotations**
Chỉ định có bật việc sử dụng các annotation pre-invocation và post-invocation của Spring Security (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize) cho application context này hay không.
Mặc định là "disabled".


[[nsa-global-method-security-proxy-target-class]]
* **proxy-target-class**
Nếu là true, proxy dựa trên class sẽ được sử dụng thay cho proxy dựa trên interface.


[[nsa-global-method-security-run-as-manager-ref]]
* **run-as-manager-ref**
Một reference đến implementation `RunAsManager` tùy chọn mà `MethodSecurityInterceptor` đã cấu hình sẽ sử dụng.


[[nsa-global-method-security-secured-annotations]]
* **secured-annotations**
Chỉ định có bật việc sử dụng các annotation @Secured của Spring Security cho application context này hay không.
Mặc định là "disabled".


[[nsa-global-method-security-children]]
=== Các child element của <global-method-security>


* <<nsa-after-invocation-provider,after-invocation-provider>>
* xref:servlet/appendix/namespace/http.adoc#nsa-expression-handler[expression-handler]
* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>
* <<nsa-protect-pointcut,protect-pointcut>>



[[nsa-after-invocation-provider]]
== <after-invocation-provider>
Element này có thể dùng để bọc một `AfterInvocationProvider` để security interceptor do namespace `<global-method-security>` quản lý sử dụng.
Bạn có thể định nghĩa zero hoặc nhiều element như vậy bên trong element `global-method-security`, mỗi element có attribute `ref` trỏ đến một `AfterInvocationProvider` bean instance trong application context.


[[nsa-after-invocation-provider-parents]]
=== Parent element của <after-invocation-provider>


* <<nsa-global-method-security,global-method-security>>



[[nsa-after-invocation-provider-attributes]]
=== Các attribute của <after-invocation-provider>

[NOTE]
=====
`<after-invocation-provider>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PostFilter` và `@PostAuthorize`].
Nếu cần dùng `<after-invocation-provider>`, hãy thêm dependency `spring-security-access` vào build configuration trong khi lập kế hoạch chuyển sang một option hiện đại hơn.
=====

[[nsa-after-invocation-provider-ref]]
* **ref**
Định nghĩa một reference đến Spring bean triển khai `AfterInvocationProvider`.


[[nsa-pre-post-annotation-handling]]
== <pre-post-annotation-handling>
Cho phép thay thế hoàn toàn cơ chế mặc định dựa trên expression để xử lý các annotation pre-invocation và post-invocation của Spring Security (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize).
Chỉ áp dụng khi các annotation này được bật.


[[nsa-pre-post-annotation-handling-parents]]
=== Parent element của <pre-post-annotation-handling>


* <<nsa-global-method-security,global-method-security>>



[[nsa-pre-post-annotation-handling-children]]
=== Các child element của <pre-post-annotation-handling>


* <<nsa-invocation-attribute-factory,invocation-attribute-factory>>
* <<nsa-post-invocation-advice,post-invocation-advice>>
* <<nsa-pre-invocation-advice,pre-invocation-advice>>



[[nsa-invocation-attribute-factory]]
== <invocation-attribute-factory>
Định nghĩa instance PrePostInvocationAttributeFactory được dùng để tạo pre-invocation và post-invocation metadata từ các method có annotation.

[NOTE]
=====
`<invocation-attribute-factory>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PostFilter` và `@PostAuthorize`].
Nếu cần dùng `<invocation-attribute-factory>`, hãy thêm dependency `spring-security-access` vào build configuration trong khi lập kế hoạch chuyển sang một option hiện đại hơn.
=====

[[nsa-invocation-attribute-factory-parents]]
=== Parent element của <invocation-attribute-factory>


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-invocation-attribute-factory-attributes]]
=== Các attribute của <invocation-attribute-factory>


[[nsa-invocation-attribute-factory-ref]]
* **ref**
Định nghĩa một reference đến Id của Spring bean.


[[nsa-post-invocation-advice]]
== <post-invocation-advice>
Tùy chỉnh `PostInvocationAdviceProvider`, dùng ref làm `PostInvocationAuthorizationAdvice` cho element <pre-post-annotation-handling>.

[NOTE]
=====
`<post-invocation-advice>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PostFilter` và `@PostAuthorize`].
Nếu cần dùng `<post-invocation-advice>`, hãy thêm dependency `spring-security-access` vào build configuration trong khi lập kế hoạch chuyển sang một option hiện đại hơn.
=====

[[nsa-post-invocation-advice-parents]]
=== Parent element của <post-invocation-advice>


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-post-invocation-advice-attributes]]
=== Các attribute của <post-invocation-advice>


[[nsa-post-invocation-advice-ref]]
* **ref**
Định nghĩa một reference đến Id của Spring bean.


[[nsa-pre-invocation-advice]]
== <pre-invocation-advice>
Tùy chỉnh `PreInvocationAuthorizationAdviceVoter`, dùng ref làm `PreInvocationAuthorizationAdviceVoter` cho element <pre-post-annotation-handling>.

[NOTE]
=====
`<pre-invocation-advice>` đã deprecated và được thay thế bằng `<method-security>` cùng xref:servlet/authorization/method-security.adoc[`@PreFilter` và `@PreAuthorize`].
Nếu cần dùng `<pre-invocation-advice>`, hãy thêm dependency `spring-security-access` vào build configuration trong khi lập kế hoạch chuyển sang một option hiện đại hơn.
=====

[[nsa-pre-invocation-advice-parents]]
=== Parent element của <pre-invocation-advice>


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-pre-invocation-advice-attributes]]
=== Các attribute của <pre-invocation-advice>


[[nsa-pre-invocation-advice-ref]]
* **ref**
Định nghĩa một reference đến Id của Spring bean.


[[nsa-protect-pointcut]]
== Bảo vệ method bằng
`<protect-pointcut>`
Thay vì định nghĩa các security attribute riêng cho từng method hoặc class bằng annotation `@Secured`, bạn có thể định nghĩa các security constraint cross-cutting trên toàn bộ tập method và interface trong service layer bằng element `<protect-pointcut>`.
Bạn có thể xem ví dụ trong xref:servlet/authorization/method-security.adoc#ns-protect-pointcut[phần giới thiệu namespace].

[[nsa-protect-pointcut-parents]]
=== Parent element của <protect-pointcut>


* <<nsa-global-method-security,global-method-security>>
* <<nsa-method-security,method-security>>



[[nsa-protect-pointcut-attributes]]
=== Các attribute của <protect-pointcut>


[[nsa-protect-pointcut-access]]
* **access**
Danh sách access configuration attribute áp dụng cho tất cả method khớp với pointcut, ví dụ:
"ROLE_A,ROLE_B"


[[nsa-protect-pointcut-expression]]
* **expression**
Một AspectJ expression, bao gồm keyword `execution`.
Ví dụ: `execution(int com.foo.TargetObject.countLength(String))`.


[[nsa-intercept-methods]]
== <intercept-methods>
Có thể dùng bên trong bean definition để thêm security interceptor vào bean và thiết lập access configuration attribute cho các method của bean.


[[nsa-intercept-methods-attributes]]
=== Các attribute của <intercept-methods>

[[nsa-intercept-methods-use-authorization-manager]]
* **use-authorization-manager**
Dùng API AuthorizationManager thay cho AccessDecisionManager (mặc định là true)

[[nsa-intercept-methods-authorization-manager-ref]]
* **authorization-manager-ref**
AuthorizationManager bean ID tùy chọn được dùng thay cho giá trị mặc định (ghi đè use-authorization-manager)

[[nsa-intercept-methods-access-decision-manager-ref]]
* **access-decision-manager-ref**
ID của AccessDecisionManager bean tùy chọn mà method security interceptor được tạo sẽ sử dụng.

[[nsa-intercept-methods-children]]
=== Các child element của <intercept-methods>


* <<nsa-protect,protect>>



[[nsa-method-security-metadata-source]]
== <method-security-metadata-source>
Tạo một instance MethodSecurityMetadataSource.

[NOTE]
=====
`<method-security-metadata-source>` đã deprecated và được thay thế bằng xref:servlet/authorization/method-security.adoc[`<method-security>`].
Nếu cần sử dụng `<method-security-metadata-source>`, hãy thêm dependency `spring-security-access` vào cấu hình build trong khi lập kế hoạch chuyển sang một tùy chọn hiện đại hơn.
=====

[[nsa-method-security-metadata-source-attributes]]
=== Các attribute của <method-security-metadata-source>


[[nsa-method-security-metadata-source-id]]
* **id**
Một bean identifier, dùng để tham chiếu đến bean ở nơi khác trong context.


[[nsa-method-security-metadata-source-use-expressions]]
* **use-expressions**
Bật việc sử dụng expression trong các attribute 'access' của element <intercept-url> thay cho danh sách configuration attribute truyền thống.
Mặc định là 'false'.
Nếu được bật, mỗi thuộc tính phải chứa một Boolean expression duy nhất.
Nếu expression được evaluate thành 'true', quyền truy cập sẽ được cấp.


[[nsa-method-security-metadata-source-children]]
=== Các child element của <method-security-metadata-source>


* <<nsa-protect,protect>>



[[nsa-protect]]
== <protect>
Định nghĩa một method được bảo vệ và các access control configuration attribute áp dụng cho method đó.
Chúng tôi đặc biệt khuyến cáo bạn KHÔNG trộn các declaration "protect" với bất kỳ service nào do "global-method-security" cung cấp.


[[nsa-protect-parents]]
=== Parent element của <protect>


* <<nsa-intercept-methods,intercept-methods>>
* <<nsa-method-security-metadata-source,method-security-metadata-source>>



[[nsa-protect-attributes]]
=== Các attribute của <protect>


[[nsa-protect-access]]
* **access**
Danh sách access configuration attribute áp dụng cho method, ví dụ:
"ROLE_A,ROLE_B".


[[nsa-protect-method]]
* **method**
Tên method
