[[nsa-websocket-security]]
= Bảo mật WebSocket

Spring Security 4.0+ cung cấp hỗ trợ authorization cho các message.
Một ví dụ cụ thể về trường hợp hỗ trợ này hữu ích là cung cấp authorization trong các ứng dụng dựa trên WebSocket.

[[nsa-websocket-message-broker]]
== <websocket-message-broker>

Element websocket-message-broker có hai mode khác nhau.
Nếu không chỉ định <<nsa-websocket-message-broker-id,websocket-message-broker@id>>, element này sẽ thực hiện những việc sau:

* Đảm bảo mọi SimpAnnotationMethodMessageHandler đều đăng ký AuthenticationPrincipalArgumentResolver làm custom argument resolver.
Điều này cho phép sử dụng `@AuthenticationPrincipal` để resolve principal của `Authentication` hiện tại.
* Đảm bảo SecurityContextChannelInterceptor được tự động đăng ký với clientInboundChannel.
Điều này đưa user được tìm thấy trong Message vào SecurityContextHolder.
* Đảm bảo một ChannelSecurityInterceptor được đăng ký với clientInboundChannel.
Điều này cho phép chỉ định các authorization rule cho một message.
* Đảm bảo một CsrfChannelInterceptor được đăng ký với clientInboundChannel.
Điều này đảm bảo chỉ các request từ domain ban đầu mới được cho phép.
* Đảm bảo một CsrfTokenHandshakeInterceptor được đăng ký với WebSocketHttpRequestHandler, TransportHandlingSockJsService hoặc DefaultSockJsService.
Điều này đảm bảo CsrfToken mong đợi từ HttpServletRequest được sao chép vào các attribute của WebSocket Session.

Nếu cần quyền kiểm soát bổ sung, có thể chỉ định id và một ChannelSecurityInterceptor sẽ được gán cho id đó.
Sau đó, có thể thực hiện thủ công toàn bộ wiring với messaging infrastructure của Spring.
Cách này cồng kềnh hơn, nhưng cung cấp quyền kiểm soát lớn hơn đối với configuration.


[[nsa-websocket-message-broker-attributes]]
=== Các thuộc tính của <websocket-message-broker>

[[nsa-websocket-message-broker-id]]
* **id** Một bean identifier, được dùng để tham chiếu bean ChannelSecurityInterceptor ở nơi khác trong context.
Nếu được chỉ định, Spring Security yêu cầu configuration tường minh trong Spring Messaging.
Nếu không được chỉ định, Spring Security sẽ tự động tích hợp với messaging infrastructure như mô tả trong <<nsa-websocket-message-broker>>

[[nsa-websocket-message-broker-same-origin-disabled]]
* **same-origin-disabled** Tắt yêu cầu phải có CSRF token trong các Stomp header (mặc định là false).
Thay đổi giá trị mặc định hữu ích khi cần cho phép các origin khác tạo kết nối SockJS.

[[nsa-websocket-message-broker-authorization-manager-ref]]
* **authorization-manager-ref** Sử dụng instance `AuthorizationManager` này; khi được thiết lập, `use-authorization-manager` bị bỏ qua và được giả định là `true`

[[nsa-websocket-message-broker-use-authorization-manager]]
* **use-authorization-manager** Sử dụng API `AuthorizationManager` thay cho API `SecurityMetadataSource` (mặc định là true).

[[nsa-websocket-message-broker-security-context-holder-strategy-ref]]
* **security-context-holder-strategy-ref** Sử dụng `SecurityContextHolderStrategy` này (lưu ý chỉ được hỗ trợ khi kết hợp với API `AuthorizationManager`)

[[nsa-websocket-message-broker-children]]
=== Các element con của <websocket-message-broker>


* xref:servlet/appendix/namespace/http.adoc#nsa-expression-handler[expression-handler]
* <<nsa-intercept-message,intercept-message>>

[[nsa-intercept-message]]
== <intercept-message>

Định nghĩa một authorization rule cho một message.


[[nsa-intercept-message-parents]]
=== Các element cha của <intercept-message>


* <<nsa-websocket-message-broker,websocket-message-broker>>


[[nsa-intercept-message-attributes]]
=== Các thuộc tính của <intercept-message>

[[nsa-intercept-message-pattern]]
* **pattern** Một pattern dựa trên ant khớp với đích đến của Message.
Ví dụ, "/**" khớp với mọi Message có đích đến; "/admin/**" khớp với mọi Message có đích đến bắt đầu bằng "/admin/**".

[[nsa-intercept-message-type]]
* **type** Kiểu message cần khớp.
Các giá trị hợp lệ được định nghĩa trong SimpMessageType (tức là CONNECT, CONNECT_ACK, HEARTBEAT, MESSAGE, SUBSCRIBE, UNSUBSCRIBE, DISCONNECT, DISCONNECT_ACK, OTHER).

[[nsa-intercept-message-access]]
* **access** Expression được sử dụng để bảo vệ Message.
Ví dụ, "denyAll" sẽ từ chối quyền truy cập vào mọi Message khớp; "permitAll" sẽ cấp quyền truy cập cho mọi Message khớp; "hasRole('ADMIN') yêu cầu user hiện tại có role 'ROLE_ADMIN' đối với các Message khớp.
