[[data]]
= Tích hợp Spring Data

Spring Security cung cấp khả năng tích hợp Spring Data, cho phép tham chiếu đến người dùng hiện tại trong các query của bạn.
Việc đưa người dùng vào các query không chỉ hữu ích mà còn cần thiết để hỗ trợ paged results, vì việc filter results sau đó sẽ không scale được.

[[data-configuration]]
== Cấu hình Spring Data & Spring Security

Để sử dụng hỗ trợ này, hãy thêm dependency `org.springframework.security:spring-security-data` và cung cấp một bean thuộc kiểu `SecurityEvaluationContextExtension`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityEvaluationContextExtension securityEvaluationContextExtension() {
	return new SecurityEvaluationContextExtension();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun securityEvaluationContextExtension(): SecurityEvaluationContextExtension {
	return SecurityEvaluationContextExtension()
}
----
======

Trong cấu hình XML, nội dung này sẽ như sau:

[source,xml]
----
<bean class="org.springframework.security.data.repository.query.SecurityEvaluationContextExtension"/>
----

[[data-query]]
== Security Expressions trong @Query

Giờ đây có thể sử dụng Spring Security trong các query của bạn.

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public interface MessageRepository extends PagingAndSortingRepository<Message,Long> {
	@Query("select m from Message m where m.to.id = ?#{ principal?.id }")
	Page<Message> findInbox(Pageable pageable);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
interface MessageRepository : PagingAndSortingRepository<Message,Long> {
	@Query("select m from Message m where m.to.id = ?#{ principal?.id }")
	fun findInbox(pageable: Pageable): Page<Message>
}
----
======

Điều này kiểm tra xem `Authentication.getPrincipal().getId()` có bằng với recipient của `Message` hay không.
Lưu ý rằng ví dụ này giả định bạn đã tùy chỉnh principal thành một Object có property id.
Khi expose bean `SecurityEvaluationContextExtension`, tất cả các xref:servlet/authorization/method-security.adoc#authorization-expressions[Security Expressions phổ biến] đều khả dụng trong query.
