[[taglibs]]
= JSP Tag Libraries
Spring Security có taglib riêng, cung cấp hỗ trợ cơ bản để truy cập security information và áp dụng các security constraint trong JSP.


== Khai báo Taglib
Để sử dụng bất kỳ tag nào, bạn phải khai báo security taglib trong JSP:

[source,xml]
----
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
----

[[taglibs-authorize]]
== Tag authorize
Tag này được dùng để xác định nội dung bên trong có được evaluate hay không.
Trong Spring Security 3.0, tag này có thể được sử dụng theo hai cách.

[NOTE]
====
Các legacy option của Spring Security 2.0 cũng được hỗ trợ, nhưng không được khuyến khích.
====

Cách tiếp cận đầu tiên sử dụng một xref:servlet/authorization/authorize-http-requests.adoc#authorization-expressions[web-security expression], được chỉ định trong attribute `access` của tag.
Việc evaluate expression được ủy quyền cho `SecurityExpressionHandler<FilterInvocation>` được định nghĩa trong application context (bạn nên enable web expressions trong namespace configuration `<http>` để đảm bảo service này available).
Ví dụ:

[source,xml]
----
<sec:authorize access="hasRole('supervisor')">

Nội dung này chỉ hiển thị với những user có authority "supervisor" trong danh sách <tt>GrantedAuthority</tt> của họ.

</sec:authorize>
----

Khi được sử dụng cùng với `PermissionEvaluator` của Spring Security, tag này cũng có thể được dùng để check permission:

[source,xml]
----
<sec:authorize access="hasPermission(#domain,'read') or hasPermission(#domain,'write')">

Nội dung này chỉ hiển thị với những user có permission đọc hoặc ghi đối với Object được tìm thấy trong request attribute có tên "domain".

</sec:authorize>
----

Một requirement phổ biến là chỉ hiển thị một link cụ thể khi user thực sự được phép click vào link đó.
Làm thế nào để xác định trước một nội dung có được phép hay không? Tag này cũng có thể hoạt động ở một mode thay thế, cho phép bạn định nghĩa một URL cụ thể làm attribute.
Nếu user được phép invoke URL đó, tag body sẽ được evaluate. Nếu không, body sẽ bị bỏ qua.
Ví dụ:

[source,xml]
----
<sec:authorize url="/admin">

Nội dung này chỉ hiển thị với những user được authorization để gửi request đến URL "/admin".

</sec:authorize>
----

Để sử dụng tag này, bạn cũng phải có một instance của `WebInvocationPrivilegeEvaluator` trong application context.
Nếu sử dụng namespace, một instance sẽ được tự động register.
Đây là một instance của `DefaultWebInvocationPrivilegeEvaluator`, tạo một dummy web request cho URL được cung cấp và invoke security interceptor để xem request có thành công hay thất bại.
Điều này cho phép bạn delegate cho access-control setup được định nghĩa bằng các khai báo `intercept-url` trong namespace configuration `<http>`, đồng thời tránh phải duplicate thông tin (chẳng hạn các role bắt buộc) trong JSP.

Nếu có xref:servlet/authorization/authorize-http-requests.adoc#match-by-httpmethod[method-based authorization rule], bạn nên kết hợp approach này với attribute `method` (cung cấp HTTP method, chẳng hạn `POST`) để activate method-based rule mong muốn.
Ví dụ, nếu có rule `.requestMatchers(POST, "/admin").hasRole("ADMIN")`, bạn nên dùng `<sec:authorize method="POST" url="/admin">` để match.

Bạn có thể lưu kết quả Boolean từ việc evaluate tag (dù tag grant hay deny access) vào một variable trong page context scope bằng cách đặt attribute `var` thành tên variable, tránh phải duplicate và re-evaluate condition ở các vị trí khác trong page.


=== Vô hiệu hóa Tag Authorization khi testing
Việc ẩn một link trong page đối với unauthorized user không ngăn họ access URL.
Ví dụ, họ vẫn có thể nhập trực tiếp URL đó vào browser.
Trong quá trình testing, bạn có thể muốn reveal các khu vực đang bị ẩn để kiểm tra các link có thực sự được secure ở backend hay không.
Nếu đặt system property `spring.security.disableUISecurity` thành `true`, tag `authorize` vẫn chạy nhưng không hide nội dung.
Theo mặc định, tag này cũng bao quanh content bằng các tag `<span class="securityHiddenUI">...</span>`.
Điều này cho phép bạn hiển thị content "`hidden`" bằng một CSS style cụ thể, chẳng hạn background color khác.
Ví dụ, hãy thử chạy sample application "`tutorial`" với property này được enable.

Bạn cũng có thể set các property `spring.security.securedUIPrefix` và `spring.security.securedUISuffix` nếu muốn thay đổi surrounding text so với các tag `span` mặc định (hoặc dùng empty string để xóa hoàn toàn phần này).


== Tag authentication
Tag này cho phép truy cập object `Authentication` hiện tại được lưu trong security context.
Tag render trực tiếp một property của object trong JSP.
Ví dụ, nếu property `principal` của `Authentication` là một `UserDetails` instance của Spring Security, việc dùng `<sec:authentication property="principal.username" />` sẽ render tên của user hiện tại.

Tất nhiên, không bắt buộc phải dùng JSP tag cho việc này; một số người thích giữ logic trong view ở mức tối thiểu.
Bạn có thể truy cập object `Authentication` trong MVC controller (bằng cách gọi `SecurityContextHolder.getContext().getAuthentication()`) và đưa data trực tiếp vào model để view render.


== Tag accesscontrollist
Tag này chỉ hợp lệ khi được dùng với ACL module của Spring Security.
Tag này check một list các permission bắt buộc, được phân tách bằng dấu phẩy, cho một domain object được chỉ định.
Nếu current user có tất cả permission đó, tag body sẽ được evaluate.
Nếu không, body sẽ bị bỏ qua.

[CAUTION]
====
Nhìn chung, tag này nên được xem là deprecated.
Thay vào đó, dùng <<taglibs-authorize>>.
====

Listing sau đây minh họa một ví dụ:

[source,xml]
----
<sec:accesscontrollist hasPermission="1,2" domainObject="${someObject}">

<!-- Nội dung này sẽ được hiển thị nếu user có tất cả permission được biểu thị bởi các giá trị "1" hoặc "2" trên object đã cho. -->

</sec:accesscontrollist>
----

Các permission được truyền cho `PermissionFactory` được định nghĩa trong application context để convert chúng thành các instance ACL `Permission`, vì vậy chúng có thể ở bất kỳ format nào được factory hỗ trợ. Chúng không nhất thiết phải là integer. Chúng có thể là các string như `READ` hoặc `WRITE`.
Nếu không tìm thấy `PermissionFactory`, một instance của `DefaultPermissionFactory` sẽ được dùng.
`AclService` từ application context được dùng để load `Acl` instance cho object được cung cấp.
`Acl` được invoke với các permission bắt buộc để check xem tất cả chúng đã được grant hay chưa.

Tag này cũng hỗ trợ attribute `var`, giống tag `authorize`.

[[taglibs-csrfinput]]
== Tag csrfInput
Nếu CSRF protection được enable, tag này insert một hidden form field với name và value chính xác của CSRF protection token.
Nếu CSRF protection không được enable, tag này không output gì.

Thông thường, Spring Security tự động insert CSRF form field cho mọi tag `<form:form>` mà bạn sử dụng, nhưng nếu vì lý do nào đó bạn không thể dùng `<form:form>`, `csrfInput` là một replacement tiện dụng.

Bạn nên đặt tag này bên trong HTML `<form></form>` block, tại vị trí thường đặt các input field khác.
KHÔNG đặt tag này bên trong Spring `<form:form></form:form>` block.
Spring Security tự động handle các Spring form.
Listing sau đây minh họa một ví dụ:

[source,xml]
----
	<form method="post" action="/do/something">
		<sec:csrfInput />
		Tên:<br />
		<input type="text" name="name" />
		...
	</form>
----

[[taglibs-csrfmeta]]
== Tag csrfMetaTags
Nếu CSRF protection được enable, tag này insert các meta tag chứa form field name và header name của CSRF protection token, cùng với value của token.
Các meta tag này hữu ích để áp dụng CSRF protection trong JavaScript của application.

Bạn nên đặt `csrfMetaTags` bên trong HTML `<head></head>` block, tại vị trí thường đặt các meta tag khác.
Sau khi dùng tag này, bạn có thể access form field name, header name và token value bằng JavaScript.
Ví dụ này dùng JQuery để thực hiện việc này dễ hơn.
Listing sau đây minh họa một ví dụ:

[source,xml]
----
<!DOCTYPE html>
<html>
	<head>
		<title>Trang JavaScript được bảo vệ bằng CSRF</title>
		<meta name="description" content="Đây là phần mô tả cho trang này" />
		<sec:csrfMetaTags />
		<script type="text/javascript" language="javascript">

			var csrfParameter = $("meta[name='_csrf_parameter']").attr("content");
			var csrfHeader = $("meta[name='_csrf_header']").attr("content");
			var csrfToken = $("meta[name='_csrf']").attr("content");

			// sử dụng XMLHttpRequest trực tiếp để gửi request x-www-form-urlencoded
			var ajax = new XMLHttpRequest();
			ajax.open("POST", "https://www.example.org/do/something", true);
			ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded data");
			ajax.send(csrfParameter + "=" + csrfToken + "&name=John&...");

			// sử dụng XMLHttpRequest trực tiếp để gửi request không phải x-www-form-urlencoded
			var ajax = new XMLHttpRequest();
			ajax.open("POST", "https://www.example.org/do/something", true);
			ajax.setRequestHeader(csrfHeader, csrfToken);
			ajax.send("...");

			// sử dụng JQuery để gửi request x-www-form-urlencoded
			var data = {};
			data[csrfParameter] = csrfToken;
			data["name"] = "John";
			...
			$.ajax({
				url: "https://www.example.org/do/something",
				type: "POST",
				data: data,
				...
			});

			// sử dụng JQuery để gửi request không phải x-www-form-urlencoded
			var headers = {};
			headers[csrfHeader] = csrfToken;
			$.ajax({
				url: "https://www.example.org/do/something",
				type: "POST",
				headers: headers,
				...
			});

		<script>
	</head>
	<body>
		...
	</body>
</html>
----

Nếu CSRF protection không được enable, `csrfMetaTags` không output gì.
