[[mvc]]
= Tích hợp Spring MVC

Spring Security cung cấp một số tích hợp tùy chọn với Spring MVC.
Phần này trình bày chi tiết hơn về việc tích hợp.

[[mvc-enablewebmvcsecurity]]
[[mvc-enablewebsecurity]]
== @EnableWebSecurity

Để bật tích hợp Spring Security với Spring MVC, hãy thêm annotation `@EnableWebSecurity` vào cấu hình của bạn.

[NOTE]
====
Spring Security cung cấp cấu hình bằng cách sử dụng {spring-framework-reference-url}web/webmvc/mvc-config/customize.html[`WebMvcConfigurer`] của Spring MVC.
Điều này có nghĩa là nếu bạn sử dụng các tùy chọn nâng cao hơn, chẳng hạn tích hợp trực tiếp với `WebMvcConfigurationSupport`, bạn cần tự cung cấp cấu hình Spring Security.
====

[[mvc-requestmatcher]]
== PathPatternRequestMatcher

Spring Security tích hợp sâu với cơ chế Spring MVC dùng để so khớp URL thông qua `PathPatternRequestMatcher`.
Điều này giúp đảm bảo các quy tắc bảo mật của bạn khớp với logic được dùng để xử lý các request.

`PathPatternRequestMatcher` phải sử dụng cùng `PathPatternParser` với Spring MVC.
Nếu bạn không tùy chỉnh `PathPatternParser`, bạn có thể làm như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
PathPatternRequestMatcherBuilderFactoryBean usePathPattern() {
	return new PathPatternRequestMatcherBuilderFactoryBean();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun usePathPattern(): PathPatternRequestMatcherBuilderFactoryBean {
    return PathPatternRequestMatcherBuilderFactoryBean()
}
----

Xml::
+
[source,xml,role="secondary"]
----
<b:bean class="org.springframework.security.config.web.PathPatternRequestMatcherBuilderFactoryBean"/>
----
======

Sau đó, Spring Security sẽ tìm cấu hình Spring MVC phù hợp cho bạn.

Nếu bạn *có* tùy chỉnh instance `PathPatternParser` của Spring MVC, bạn sẽ cần <<security-mvc-same-application-context, cấu hình Spring Security và Spring MVC trong cùng một `ApplicationContext`>>.

[NOTE]
====
Chúng tôi luôn khuyến nghị bạn xây dựng các quy tắc authorization bằng cách so khớp với `HttpServletRequest` và sử dụng method security.

Việc xây dựng các quy tắc authorization bằng cách so khớp với `HttpServletRequest` hữu ích vì việc này diễn ra rất sớm trong code path và giúp giảm https://en.wikipedia.org/wiki/Attack_surface[bề mặt tấn công].
Method security đảm bảo rằng nếu ai đó bypass được các quy tắc web authorization, ứng dụng của bạn vẫn được bảo vệ.
Điều này được gọi là https://en.wikipedia.org/wiki/Defense_in_depth_(computing)[phòng thủ theo chiều sâu]
====

Giờ đây Spring MVC đã được tích hợp với Spring Security, bạn đã sẵn sàng viết một số xref:servlet/authorization/authorize-http-requests.adoc[quy tắc authorization] sử dụng `PathPatternRequestMatcher`.

[[mvc-authentication-principal]]
== @AuthenticationPrincipal

Spring Security cung cấp `AuthenticationPrincipalArgumentResolver`, có thể tự động resolve `Authentication.getPrincipal()` hiện tại cho các argument trong Spring MVC.
Khi sử dụng `@EnableWebSecurity`, thành phần này sẽ tự động được thêm vào cấu hình Spring MVC của bạn.
Nếu sử dụng cấu hình dựa trên XML, bạn phải tự thêm thành phần này:

[source,xml]
----
<mvc:annotation-driven>
		<mvc:argument-resolvers>
				<bean class="org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver" />
		</mvc:argument-resolvers>
</mvc:annotation-driven>
----

Sau khi cấu hình đúng `AuthenticationPrincipalArgumentResolver`, bạn có thể hoàn toàn tách layer Spring MVC khỏi Spring Security.

Hãy xét tình huống một `UserDetailsService` tùy chỉnh trả về một `Object` triển khai `UserDetails` và một `Object` `CustomUser` do bạn định nghĩa. Có thể truy cập `CustomUser` của user hiện tại đã được authenticated bằng đoạn code sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser() {
	Authentication authentication =
	SecurityContextHolder.getContext().getAuthentication();
	CustomUser custom = (CustomUser) authentication == null ? null : authentication.getPrincipal();

	// .. find messages for this user and return them ...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(): ModelAndView {
    val authentication: Authentication = SecurityContextHolder.getContext().authentication
    val custom: CustomUser? = if (authentication as CustomUser == null) null else authentication.principal

    // .. find messages for this user and return them ...
}
----
======

Kể từ Spring Security 3.2, bạn có thể resolve argument trực tiếp hơn bằng cách thêm một annotation:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@AuthenticationPrincipal customUser: CustomUser?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
======

Đôi khi bạn có thể cần biến đổi principal theo một cách nào đó.
Ví dụ, nếu `CustomUser` là `final` thì bạn không thể kế thừa nó.
Trong tình huống này, `UserDetailsService` có thể trả về một `Object` triển khai `UserDetails` và cung cấp method có tên `getCustomUser` để truy cập `CustomUser`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class CustomUserUserDetails extends User {
		// ...
		public CustomUser getCustomUser() {
				return customUser;
		}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class CustomUserUserDetails(
    username: String?,
    password: String?,
    authorities: MutableCollection<out GrantedAuthority>?
) : User(username, password, authorities) {
    // ...
    val customUser: CustomUser? = null
}
----
======

Sau đó, bạn có thể truy cập `CustomUser` bằng {spring-framework-reference-url}core/expressions.html[biểu thức SpEL] sử dụng `Authentication.getPrincipal()` làm root object:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal(expression = "customUser") CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal

// ...

@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@AuthenticationPrincipal(expression = "customUser") customUser: CustomUser?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
======

Bạn cũng có thể tham chiếu đến các bean trong biểu thức SpEL.
Ví dụ, bạn có thể sử dụng đoạn sau nếu dùng JPA để quản lý user và muốn sửa đổi rồi lưu một property của user hiện tại:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@PutMapping("/users/self")
public ModelAndView updateName(@AuthenticationPrincipal(expression = "@jpaEntityManager.merge(#this)") CustomUser attachedCustomUser,
		@RequestParam String firstName) {

	// change the firstName on an attached instance which will be persisted to the database
	attachedCustomUser.setFirstName(firstName);

	// ...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal

// ...

@PutMapping("/users/self")
open fun updateName(
    @AuthenticationPrincipal(expression = "@jpaEntityManager.merge(#this)") attachedCustomUser: CustomUser,
    @RequestParam firstName: String?
): ModelAndView {

    // change the firstName on an attached instance which will be persisted to the database
    attachedCustomUser.setFirstName(firstName)

    // ...
}
----
======

Bạn có thể tiếp tục loại bỏ dependency vào Spring Security bằng cách biến `@AuthenticationPrincipal` thành meta-annotation trên annotation của riêng mình.
Ví dụ tiếp theo minh họa cách thực hiện điều này trên annotation có tên `@CurrentUser`.

[NOTE]
====
Để loại bỏ dependency vào Spring Security, chính application sử dụng sẽ tạo `@CurrentUser`.
Bước này không bắt buộc nghiêm ngặt nhưng giúp cô lập dependency vào Spring Security ở một vị trí tập trung hơn.
====

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Target({ElementType.PARAMETER, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal
public @interface CurrentUser {}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Target(AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.TYPE)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
@AuthenticationPrincipal
annotation class CurrentUser
----
======

Bạn đã cô lập dependency vào Spring Security trong một file duy nhất.
Giờ đây `@CurrentUser` đã được xác định, bạn có thể dùng nó để cho biết cần resolve `CustomUser` của user hiện tại đã được authenticated:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@CurrentUser CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@CurrentUser customUser: CustomUser?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
======

Khi annotation là một meta-annotation, bạn cũng có thể truyền parameter cho nó.

Ví dụ, hãy xét trường hợp JWT là principal và bạn muốn chỉ định claim nào cần truy xuất.
Là một meta-annotation, bạn có thể viết như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Target({ElementType.PARAMETER, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal(expression = "claims['sub']")
public @interface CurrentUser {}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Target(AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.TYPE)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
@AuthenticationPrincipal(expression = "claims['sub']")
annotation class CurrentUser
----
======

Cách này đã khá mạnh.
Tuy nhiên, nó cũng bị giới hạn ở việc truy xuất claim `sub`.

Để linh hoạt hơn, trước tiên hãy đăng ký bean `AnnotationTemplateExpressionDefaults` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public AnnotationTemplateExpressionDefaults templateDefaults() {
	return new AnnotationTemplateExpressionDefaults();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun templateDefaults(): AnnotationTemplateExpressionDefaults {
	return AnnotationTemplateExpressionDefaults()
}
----

Xml::
+
[source,xml,role="secondary"]
----
<b:bean name="annotationExpressionTemplateDefaults" class="org.springframework.security.core.annotation.AnnotationTemplateExpressionDefaults"/>
----
======

Sau đó, bạn có thể cung cấp parameter cho `@CurrentUser` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Target({ElementType.PARAMETER, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal(expression = "claims['{claim}']")
public @interface CurrentUser {
	String claim() default 'sub';
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Target(AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.TYPE)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
@AuthenticationPrincipal(expression = "claims['{claim}']")
annotation class CurrentUser(val claim: String = "sub")
----
======

Điều này cho phép bạn linh hoạt hơn giữa các application của bạn theo cách sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@CurrentUser("user_id") String userId) {

	// .. find messages for this user and return them ...
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@CurrentUser("user_id") userId: String?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
======

[[mvc-current-security-context]]
== @CurrentSecurityContext

Spring Security cung cấp `CurrentSecurityContextArgumentResolver`, có thể tự động resolve `SecurityContext` hiện tại cho các argument trong Spring MVC.
Khi sử dụng `@EnableWebSecurity`, thành phần này sẽ tự động được thêm vào cấu hình Spring MVC của bạn.
Nếu sử dụng cấu hình dựa trên XML, bạn phải tự thêm thành phần này:

[source,xml]
----
<mvc:annotation-driven>
		<mvc:argument-resolvers>
				<bean class="org.springframework.security.web.method.annotation.CurrentSecurityContextArgumentResolver" />
		</mvc:argument-resolvers>
</mvc:annotation-driven>
----

Sau khi cấu hình `CurrentSecurityContextArgumentResolver`, bạn có thể truy cập trực tiếp `SecurityContext`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/me")
public String me(@CurrentSecurityContext SecurityContext context) {
	return context.getAuthentication().getName();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/me")
fun me(@CurrentSecurityContext context: SecurityContext): String {
    return context.authentication.name
}
----
======

Bạn cũng có thể sử dụng biểu thức SpEL có root là `SecurityContext`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/me")
public String me(@CurrentSecurityContext(expression = "authentication") Authentication authentication) {
	return authentication.getName();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/me")
fun me(@CurrentSecurityContext(expression = "authentication") authentication: Authentication): String {
    return authentication.name
}
----
======

[[mvc-async]]
== Tích hợp async trong Spring MVC

Spring Web MVC 3.2+ hỗ trợ rất tốt {spring-framework-reference-url}web/webmvc/mvc-ann-async.html[xử lý request bất đồng bộ].
Không cần cấu hình bổ sung, Spring Security tự động thiết lập `SecurityContext` cho `Thread` thực thi một `Callable` do controller của bạn trả về.
Ví dụ, `Callable` của method sau đây sẽ tự động được gọi với `SecurityContext` có tại thời điểm `Callable` được tạo:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RequestMapping(method=RequestMethod.POST)
public Callable<String> processUpload(final MultipartFile file) {

return new Callable<String>() {
	public Object call() throws Exception {
	// ...
	return "someView";
	}
};
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RequestMapping(method = [RequestMethod.POST])
open fun processUpload(file: MultipartFile?): Callable<String> {
    return Callable {
        // ...
        "someView"
    }
}
----
======


.Gắn SecurityContext với Callable
[NOTE]
====
Nói chính xác hơn về mặt kỹ thuật, Spring Security tích hợp với `WebAsyncManager`.
`SecurityContext` dùng để xử lý `Callable` là `SecurityContext` đang tồn tại trên `SecurityContextHolder` khi `startCallableProcessing` được gọi.
====

Không có tích hợp tự động với `DeferredResult` được controller trả về.
Điều này là vì `DeferredResult` do user tự xử lý, do đó không có cách nào tích hợp tự động với nó.
Tuy nhiên, bạn vẫn có thể sử dụng xref:features/integrations/concurrency.adoc#concurrency[Hỗ trợ concurrency] để cung cấp tích hợp minh bạch với Spring Security.

[[mvc-csrf]]
== Tích hợp Spring MVC và CSRF

Spring Security tích hợp với Spring MVC để bổ sung cơ chế bảo vệ CSRF.

=== Tự động đưa token vào

Spring Security tự động xref:servlet/exploits/csrf.adoc#csrf-integration-form[đưa CSRF Token vào] các form sử dụng {spring-framework-reference-url}web/webmvc-view/mvc-jsp.html#mvc-view-jsp-formtaglib-formtag[form tag của Spring MVC].
Hãy xét JSP sau:

[source,xml]
----
<jsp:root xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:form="http://www.springframework.org/tags/form" version="2.0">
	<jsp:directive.page language="java" contentType="text/html" />
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<!-- ... -->

	<c:url var="logoutUrl" value="/logout"/>
	<form:form action="${logoutUrl}"
		method="post">
	<input type="submit"
		value="Log out" />
	<input type="hidden"
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	</form:form>

	<!-- ... -->
</html>
</jsp:root>
----

Ví dụ trên xuất ra HTML tương tự như sau:

[source,xml]
----
<!-- ... -->

<form action="/context/logout" method="post">
<input type="submit" value="Log out"/>
<input type="hidden" name="_csrf" value="f81d4fae-7dec-11d0-a765-00a0c91e6bf6"/>
</form>

<!-- ... -->
----

[[mvc-csrf-resolver]]
=== Resolve `CsrfToken`

Spring Security cung cấp `CsrfTokenArgumentResolver`, có thể tự động resolve `CsrfToken` hiện tại cho các argument của Spring MVC.
Khi sử dụng xref:servlet/configuration/java.adoc#jc-hello-wsca[@EnableWebSecurity], thành phần này sẽ tự động được thêm vào cấu hình Spring MVC của bạn.
Nếu sử dụng cấu hình dựa trên XML, bạn phải tự thêm thành phần này.

Sau khi cấu hình đúng `CsrfTokenArgumentResolver`, bạn có thể cung cấp `CsrfToken` cho application sử dụng HTML tĩnh của mình:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RestController
public class CsrfController {

	@RequestMapping("/csrf")
	public CsrfToken csrf(CsrfToken token) {
		return token;
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RestController
class CsrfController {
    @RequestMapping("/csrf")
    fun csrf(token: CsrfToken): CsrfToken {
        return token
    }
}
----
======

Điều quan trọng là không để lộ `CsrfToken` cho các domain khác.
Điều này có nghĩa là nếu sử dụng https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS[Cross-Origin Resource Sharing (CORS)], bạn *KHÔNG* nên expose `CsrfToken` cho bất kỳ domain bên ngoài nào.

[[security-mvc-same-application-context]]
== Cấu hình Spring MVC và Spring Security trong cùng một `ApplicationContext`

Nếu sử dụng Boot, theo mặc định Spring MVC và Spring Security nằm trong cùng một application context.

Nếu không, đối với Java Config, việc cấu hình cả `@EnableWebMvc` và `@EnableWebSecurity` sẽ khởi tạo các component của Spring Security và Spring MVC trong cùng context.

Hoặc nếu dùng các ``ServletListener``s, bạn có thể làm như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class SecurityInitializer extends
    AbstractAnnotationConfigDispatcherServletInitializer {

  @Override
  protected Class<?>[] getRootConfigClasses() {
    return null;
  }

  @Override
  protected Class<?>[] getServletConfigClasses() {
    return new Class[] { RootConfiguration.class,
        WebMvcConfiguration.class };
  }

  @Override
  protected String[] getServletMappings() {
    return new String[] { "/" };
  }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
class SecurityInitializer : AbstractAnnotationConfigDispatcherServletInitializer() {
    override fun getRootConfigClasses(): Array<Class<*>>? {
        return null
    }

    override fun getServletConfigClasses(): Array<Class<*>> {
        return arrayOf(
            RootConfiguration::class.java,
            WebMvcConfiguration::class.java
        )
    }

    override fun getServletMappings(): Array<String> {
        return arrayOf("/")
    }
}
----
======

Cuối cùng, với file `web.xml`, bạn cấu hình `DispatcherServlet` như sau:

[source,xml]
----
<listener>
  <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
</listener>

<!-- All Spring Configuration (both MVC and Security) are in /WEB-INF/spring/ -->
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>/WEB-INF/spring/*.xml</param-value>
</context-param>

<servlet>
  <servlet-name>spring</servlet-name>
  <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
  <!-- Load from the ContextLoaderListener -->
  <init-param>
    <param-name>contextConfigLocation</param-name>
    <param-value></param-value>
  </init-param>
</servlet>

<servlet-mapping>
  <servlet-name>spring</servlet-name>
  <url-pattern>/</url-pattern>
</servlet-mapping>
----

`WebSecurityConfiguration` sau đây được đặt trong `ApplicationContext` của `DispatcherServlet`.
