[[servletapi]]
= Tích hợp Servlet API
Phần này mô tả cách Spring Security được tích hợp với Servlet API.


[[servletapi-25]]
== Tích hợp Servlet 2.5+

Phần này mô tả cách Spring Security tích hợp với đặc tả Servlet 2.5.


[[servletapi-remote-user]]
=== HttpServletRequest.getRemoteUser()
https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[`HttpServletRequest.getRemoteUser()`] trả về kết quả của `SecurityContextHolder.getContext().getAuthentication().getName()`, thường là username hiện tại. Điều này có thể hữu ích nếu bạn muốn hiển thị username hiện tại trong ứng dụng.
Ngoài ra, bạn có thể kiểm tra giá trị này có phải là null hay không để xác định user đã authentication hay đang anonymous.
Biết user đã authentication hay chưa có thể hữu ích để xác định một số thành phần UI có nên được hiển thị hay không (ví dụ: liên kết logout chỉ nên được hiển thị khi user đã authentication).


[[servletapi-user-principal]]
=== HttpServletRequest.getUserPrincipal()
https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[`HttpServletRequest.getUserPrincipal()`] trả về kết quả của `SecurityContextHolder.getContext().getAuthentication()`.
Điều này có nghĩa đây là một `Authentication`, thường là một instance của `UsernamePasswordAuthenticationToken` khi sử dụng authentication dựa trên username và password.
Điều này có thể hữu ích nếu bạn cần thêm thông tin về user của mình.
Ví dụ: bạn có thể đã tạo một `UserDetailsService` tùy chỉnh trả về một `UserDetails` tùy chỉnh chứa tên và họ của user.
Bạn có thể lấy thông tin này như sau:


[tabs]
======
Java::
+
[source,java,role="primary"]
----
Authentication auth = httpServletRequest.getUserPrincipal();
// giả sử UserDetails tùy chỉnh được tích hợp có tên là MyCustomUserDetails
// theo mặc định, thường là instance của UserDetails
MyCustomUserDetails userDetails = (MyCustomUserDetails) auth.getPrincipal();
String firstName = userDetails.getFirstName();
String lastName = userDetails.getLastName();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val auth: Authentication = httpServletRequest.getUserPrincipal()
// giả sử UserDetails tùy chỉnh được tích hợp có tên là MyCustomUserDetails
// theo mặc định, thường là instance của UserDetails
val userDetails: MyCustomUserDetails = auth.principal as MyCustomUserDetails
val firstName: String = userDetails.firstName
val lastName: String = userDetails.lastName
----
======

[NOTE]
====
Cần lưu ý rằng việc thực hiện quá nhiều logic rải rác trong ứng dụng thường là một practice không tốt.
Thay vào đó, nên tập trung logic này để giảm coupling giữa Spring Security và Servlet API.
====

[[servletapi-user-in-role]]
=== HttpServletRequest.isUserInRole(String)
https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[`HttpServletRequest.isUserInRole(String)`] xác định xem `SecurityContextHolder.getContext().getAuthentication().getAuthorities()` có chứa một `GrantedAuthority` với role được truyền vào `isUserInRole(String)` hay không.
Thông thường, user không nên truyền prefix `ROLE_` vào method này, vì prefix đó được tự động thêm vào.
Ví dụ: nếu bạn muốn xác định user hiện tại có authority "ROLE_ADMIN" hay không, bạn có thể dùng đoạn sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
boolean isAdmin = httpServletRequest.isUserInRole("ADMIN");
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val isAdmin: Boolean = httpServletRequest.isUserInRole("ADMIN")
----
======

Điều này có thể hữu ích để xác định một số thành phần UI có nên được hiển thị hay không.
Ví dụ: bạn có thể chỉ hiển thị các liên kết dành cho admin khi user hiện tại là admin.

[[servletapi-3]]
== Tích hợp Servlet 3+
Phần sau mô tả các method của Servlet 3 mà Spring Security tích hợp.


[[servletapi-authenticate]]
=== HttpServletRequest.authenticate(HttpServletResponse)
Bạn có thể sử dụng method https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#authenticate%28javax.servlet.http.HttpServletResponse%29[`HttpServletRequest.authenticate(HttpServletResponse)`] để đảm bảo user đã authentication.
Nếu user chưa authentication, `AuthenticationEntryPoint` đã cấu hình sẽ được sử dụng để yêu cầu user authentication (redirect đến trang login).


[[servletapi-login]]
=== HttpServletRequest.login(String,String)
Bạn có thể sử dụng method https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login%28java.lang.String,%20java.lang.String%29[`HttpServletRequest.login(String,String)`] để authentication user bằng `AuthenticationManager` hiện tại.
Ví dụ: đoạn sau sẽ thử authentication với username là `user` và password là `password`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
try {
httpServletRequest.login("user","password");
} catch(ServletException ex) {
// authentication không thành công
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
try {
    httpServletRequest.login("user", "password")
} catch (ex: ServletException) {
    // authentication không thành công
}
----
======

[NOTE]
====
Bạn không cần catch `ServletException` nếu muốn Spring Security xử lý lần authentication thất bại.
====

[[servletapi-logout]]
=== HttpServletRequest.logout()
Bạn có thể sử dụng method https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout%28%29[`HttpServletRequest.logout()`] để logout user hiện tại.

Thông thường, điều này có nghĩa là `SecurityContextHolder` được clear, `HttpSession` bị invalidate, mọi authentication "`Remember Me`" được cleanup, v.v.
Tuy nhiên, các implementation của `LogoutHandler` đã cấu hình sẽ khác nhau, tùy thuộc vào cấu hình Spring Security của bạn.
Lưu ý rằng sau khi gọi `HttpServletRequest.logout()`, bạn vẫn phải tự ghi response.
Thông thường, việc này sẽ bao gồm redirect đến trang welcome.

[[servletapi-start-runnable]]
=== AsyncContext.start(Runnable)
Method https://docs.oracle.com/javaee/6/api/javax/servlet/AsyncContext.html#start%28java.lang.Runnable%29[`AsyncContext.start(Runnable)`] đảm bảo credential của bạn được propagate đến `Thread` mới.
Bằng cách sử dụng concurrency support của Spring Security, Spring Security override `AsyncContext.start(Runnable)` để đảm bảo `SecurityContext` hiện tại được sử dụng khi xử lý Runnable.
Ví dụ sau output Authentication của user hiện tại:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
final AsyncContext async = httpServletRequest.startAsync();
async.start(new Runnable() {
	public void run() {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		try {
			final HttpServletResponse asyncResponse = (HttpServletResponse) async.getResponse();
			asyncResponse.setStatus(HttpServletResponse.SC_OK);
			asyncResponse.getWriter().write(String.valueOf(authentication));
			async.complete();
		} catch(Exception ex) {
			throw new RuntimeException(ex);
		}
	}
});
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val async: AsyncContext = httpServletRequest.startAsync()
async.start {
    val authentication: Authentication = SecurityContextHolder.getContext().authentication
    try {
        val asyncResponse = async.response as HttpServletResponse
        asyncResponse.status = HttpServletResponse.SC_OK
        asyncResponse.writer.write(String.valueOf(authentication))
        async.complete()
    } catch (ex: Exception) {
        throw RuntimeException(ex)
    }
}
----
======

[[servletapi-async]]
=== Hỗ trợ Servlet bất đồng bộ
Nếu sử dụng cấu hình dựa trên Java, bạn không cần thực hiện thêm bước nào.
Nếu sử dụng cấu hình XML, cần thực hiện một vài cập nhật.
Bước đầu tiên là đảm bảo bạn đã cập nhật file `web.xml` để sử dụng schema tối thiểu là 3.0:

[source,xml]
----
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://java.sun.com/xml/ns/javaee https://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
version="3.0">

</web-app>
----

Tiếp theo, bạn cần đảm bảo `springSecurityFilterChain` được thiết lập để xử lý request bất đồng bộ:

[source,xml]
----
<filter>
<filter-name>springSecurityFilterChain</filter-name>
<filter-class>
	org.springframework.web.filter.DelegatingFilterProxy
</filter-class>
<async-supported>true</async-supported>
</filter>
<filter-mapping>
<filter-name>springSecurityFilterChain</filter-name>
<url-pattern>/*</url-pattern>
<dispatcher>REQUEST</dispatcher>
<dispatcher>ASYNC</dispatcher>
</filter-mapping>
----

Lúc này, Spring Security cũng đảm bảo `SecurityContext` của bạn được propagate trên các request bất đồng bộ.

Vậy cơ chế này hoạt động như thế nào? Nếu không thực sự quan tâm, bạn có thể bỏ qua phần còn lại của section này.
Phần lớn cơ chế này đã được tích hợp trong đặc tả Servlet, nhưng Spring Security vẫn thực hiện một chút điều chỉnh để đảm bảo mọi thứ hoạt động đúng với các request bất đồng bộ.
Trước Spring Security 3.2, `SecurityContext` từ `SecurityContextHolder` được tự động lưu ngay khi `HttpServletResponse` được commit.
Điều này có thể gây ra vấn đề trong môi trường bất đồng bộ.
Hãy xem xét ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
httpServletRequest.startAsync();
new Thread("AsyncThread") {
	@Override
	public void run() {
		try {
			// Thực hiện công việc
			TimeUnit.SECONDS.sleep(1);

			// Ghi vào và commit httpServletResponse
			httpServletResponse.getOutputStream().flush();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
}.start();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
httpServletRequest.startAsync()
object : Thread("AsyncThread") {
    override fun run() {
        try {
            // Thực hiện công việc
            TimeUnit.SECONDS.sleep(1)

            // Ghi vào và commit httpServletResponse
            httpServletResponse.outputStream.flush()
        } catch (ex: java.lang.Exception) {
            ex.printStackTrace()
        }
    }
}.start()
----
======

Vấn đề là Spring Security không biết về `Thread` này, nên `SecurityContext` không được propagate đến đó.
Điều này có nghĩa là khi commit `HttpServletResponse`, không có `SecurityContext`.
Khi Spring Security tự động lưu `SecurityContext` trong lúc commit `HttpServletResponse`, hệ thống sẽ làm mất user đã login.

Kể từ version 3.2, Spring Security đủ thông minh để không còn tự động lưu `SecurityContext` khi commit `HttpServletResponse` ngay sau khi `HttpServletRequest.startAsync()` được invoke.

[[servletapi-31]]
== Tích hợp Servlet 3.1+
Phần sau mô tả các method của Servlet 3.1 mà Spring Security tích hợp.

[[servletapi-change-session-id]]
=== HttpServletRequest#changeSessionId()
https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#changeSessionId()[HttpServletRequest.changeSessionId()] là method mặc định để bảo vệ khỏi các cuộc tấn công xref:servlet/authentication/session-management.adoc#ns-session-fixation[Session Fixation] trong Servlet 3.1 trở lên.
