[[websocket]]
= Bảo mật WebSocket

Spring Security 4 đã bổ sung hỗ trợ bảo mật cho {spring-framework-reference-url}web/websocket.html[tính năng WebSocket của Spring].
Phần này mô tả cách sử dụng hỗ trợ WebSocket của Spring Security.

.Hỗ trợ JSR-356 trực tiếp
****
Spring Security không cung cấp hỗ trợ JSR-356 trực tiếp vì việc đó mang lại rất ít giá trị.
Ngoài ra, JSR-356 không cung cấp cách đánh chặn message, nên việc bảo mật sẽ mang tính xâm lấn.

Spring Framework cung cấp hỗ trợ sử dụng STOMP — một giao thức nhắn tin đơn giản, vốn được tạo ra để sử dụng trong các ngôn ngữ scripting với các frame lấy cảm hứng từ HTTP. STOMP được hỗ trợ rộng rãi và rất phù hợp để sử dụng qua WebSocket cũng như web. Để biết thêm chi tiết, xem {spring-framework-reference-url}web/websocket/stomp.html[tại đây].
****

[[websocket-authentication]]
== Authentication cho WebSocket

WebSocket sử dụng lại cùng thông tin authentication có trong HTTP request tại thời điểm kết nối WebSocket được thiết lập.
Điều này có nghĩa là `Principal` trên `HttpServletRequest` sẽ được chuyển cho WebSocket.
Nếu bạn sử dụng Spring Security, `Principal` trên `HttpServletRequest` sẽ tự động được ghi đè.

Cụ thể hơn, để bảo đảm một người dùng đã authenticated với ứng dụng WebSocket của bạn, bạn chỉ cần bảo đảm rằng mình đã thiết lập Spring Security để thực hiện authentication cho ứng dụng web dựa trên HTTP.

[[websocket-authorization]]
== Authorization cho WebSocket

Spring Security 4.0 đã giới thiệu hỗ trợ authorization cho WebSocket thông qua abstraction Spring Messaging.

Trong Spring Security 5.8, phần hỗ trợ này đã được làm mới để sử dụng API `AuthorizationManager`.

Để cấu hình authorization bằng Java Configuration, chỉ cần thêm annotation `@EnableWebSocketSecurity` và công bố một bean `AuthorizationManager<Message<?>>`, hoặc trong xref:servlet/appendix/namespace/websocket.adoc#nsa-websocket-security[XML] sử dụng attribute `use-authorization-manager`.
Một cách để thực hiện việc này là sử dụng `AuthorizationManagerMessageMatcherRegistry` nhằm chỉ định các mẫu endpoint như sau:

include-code::./WebSocketSecurityConfig[tag=snippet,indent=0]

<1> Mọi message `CONNECT` gửi vào đều yêu cầu một CSRF token hợp lệ để thực thi <<websocket-sameorigin,Chính sách Same Origin>>.
<2> `SecurityContextHolder` được điền user từ header attribute `simpUser` cho mọi request gửi vào.
<3> Các message của chúng ta yêu cầu authorization phù hợp. Cụ thể, mọi message gửi vào bắt đầu bằng `/user/` sẽ yêu cầu `ROLE_USER`. Bạn có thể tìm thêm chi tiết về authorization trong <<websocket-authorization>>

[[custom-authorization]]
=== Authorization tùy chỉnh

Khi sử dụng `AuthorizationManager`, việc tùy chỉnh khá đơn giản.
Ví dụ, bạn có thể công bố một `AuthorizationManager` yêu cầu mọi message có role là `"USER"` bằng cách sử dụng `AuthorityAuthorizationManager`, như bên dưới:

include-code::./WebSocketSecurityConfig[tag=snippet,indent=0]

Có một số cách để khớp message sâu hơn, như trong ví dụ nâng cao bên dưới:

include-code::./AdvancedWebSocketSecurityConfig[tag=snippet,indent=0]

Việc này sẽ bảo đảm rằng:

<1> Mọi message không có destination (tức là mọi thứ không phải kiểu Message `MESSAGE` hoặc `SUBSCRIBE`) sẽ yêu cầu người dùng đã authenticated
<2> Bất kỳ ai cũng có thể SUBSCRIBE tới `/user/queue/errors`
<3> Mọi message có destination bắt đầu bằng `"/app/"` sẽ yêu cầu người dùng có role `ROLE_USER`
<4> Mọi message bắt đầu bằng `"/user/"` hoặc `"/topic/friends/"` và có kiểu SUBSCRIBE sẽ yêu cầu `ROLE_USER`
<5> Mọi message khác có kiểu `MESSAGE` hoặc `SUBSCRIBE` đều bị từ chối. Do mục 6, chúng ta không cần bước này, nhưng nó minh họa cách khớp theo các kiểu message cụ thể.
<6> Mọi Message khác đều bị từ chối. Đây là một ý hay để bảo đảm bạn không bỏ sót bất kỳ message nào.

[[migrating-spel-expressions]]
=== Di chuyển biểu thức SpEL

Nếu bạn đang di chuyển từ một phiên bản Spring Security cũ hơn, các matcher destination của bạn có thể bao gồm biểu thức SpEL.
Khuyến nghị thay đổi chúng để sử dụng các triển khai cụ thể của `AuthorizationManager`, vì cách này có thể được kiểm thử độc lập.

Tuy nhiên, để hỗ trợ việc di chuyển, bạn có thể sử dụng
`org.springframework.security.messaging.access.expression.MessageExpressionAuthorizationManager`.

Và chỉ định một instance cho mỗi matcher mà bạn chưa thể di chuyển:

include-code::./WebSocketSecurityConfig[tag=snippet,indent=0]

[[websocket-authorization-notes]]
=== Ghi chú về authorization WebSocket

Để bảo mật ứng dụng đúng cách, bạn cần hiểu phần hỗ trợ WebSocket của Spring.

[[websocket-authorization-notes-messagetypes]]
==== Authorization WebSocket đối với các kiểu message

Bạn cần hiểu sự khác biệt giữa message kiểu `SUBSCRIBE` và `MESSAGE`, cũng như cách chúng hoạt động trong Spring.

Hãy xét một ứng dụng chat:

* Hệ thống có thể gửi một thông báo `MESSAGE` tới tất cả người dùng thông qua destination `/topic/system/notifications`.
* Client có thể nhận thông báo bằng cách SUBSCRIBE tới `/topic/system/notifications`.

Mặc dù chúng ta muốn client có thể SUBSCRIBE tới `/topic/system/notifications`, chúng ta không muốn cho phép họ gửi một `MESSAGE` tới destination đó.
Nếu cho phép gửi một `MESSAGE` tới `/topic/system/notifications`, client có thể gửi message trực tiếp tới endpoint đó và giả mạo hệ thống.

Nhìn chung, các ứng dụng thường từ chối mọi `MESSAGE` được gửi tới một destination bắt đầu bằng {spring-framework-reference-url}web/websocket/stomp.html[tiền tố broker] (`/topic/` hoặc `/queue/`).

[[websocket-authorization-notes-destinations]]
==== Authorization WebSocket đối với các destination

Bạn cũng nên hiểu cách các destination được biến đổi.

Hãy xét một ứng dụng chat:

* Người dùng có thể gửi message tới một người dùng cụ thể bằng cách gửi message tới destination `/app/chat`.
* Ứng dụng xem message, bảo đảm attribute `from` được chỉ định là người dùng hiện tại (chúng ta không thể tin tưởng client).
* Sau đó, ứng dụng gửi message tới người nhận bằng cách sử dụng `SimpMessageSendingOperations.convertAndSendToUser("toUser", "/queue/messages", message)`.
* Message được chuyển thành destination `/queue/user/messages-<sessionid>`.

Với ứng dụng chat này, chúng ta muốn cho phép client lắng nghe `/user/queue`, vốn được chuyển thành `/queue/user/messages-<sessionid>`.
Tuy nhiên, chúng ta không muốn client có thể lắng nghe `/queue/*`, vì điều đó sẽ cho phép client xem message của mọi người dùng.

Nhìn chung, các ứng dụng thường từ chối mọi `SUBSCRIBE` tới một destination bắt đầu bằng {spring-framework-reference-url}web/websocket/stomp.html[tiền tố broker] (`/topic/` hoặc `/queue/`).
Chúng ta có thể cung cấp các ngoại lệ để xử lý những trường hợp như
//FIXME: Chẳng hạn như gì?

[[websocket-authorization-notes-outbound]]
=== Message gửi ra

Tài liệu tham khảo Spring Framework có một phần với tiêu đề {spring-framework-reference-url}web/websocket/stomp/message-flow.html["`Luồng message`"] mô tả cách message đi qua hệ thống.
Lưu ý rằng Spring Security chỉ bảo mật `clientInboundChannel`.
Spring Security không cố gắng bảo mật `clientOutboundChannel`.

Lý do quan trọng nhất là hiệu năng.
Với mỗi message đi vào, thông thường sẽ có nhiều message đi ra hơn.
Thay vì bảo mật các message gửi ra, chúng tôi khuyến khích bảo mật việc subscription tới các endpoint.

[[websocket-sameorigin]]
== Thực thi Chính sách Same Origin

Lưu ý rằng trình duyệt không thực thi https://en.wikipedia.org/wiki/Same-origin_policy[Chính sách Same Origin] cho các kết nối WebSocket.
Đây là một yếu tố cực kỳ quan trọng cần cân nhắc.

[[websocket-sameorigin-why]]
=== Tại sao Same Origin?

Hãy xét kịch bản sau.
Một người dùng truy cập `bank.com` và thực hiện authentication với tài khoản của họ.
Người dùng đó mở một tab khác trong trình duyệt và truy cập `evil.com`.
Chính sách Same Origin bảo đảm `evil.com` không thể đọc dữ liệu từ hoặc ghi dữ liệu vào `bank.com`.

Với WebSocket, Chính sách Same Origin không được áp dụng.
Trên thực tế, trừ khi `bank.com` chủ động cấm, `evil.com` có thể đọc và ghi dữ liệu thay mặt người dùng.
Điều này có nghĩa là bất kỳ việc gì người dùng có thể thực hiện qua WebSocket (chẳng hạn chuyển tiền), `evil.com` đều có thể thực hiện thay mặt người dùng đó.

Vì SockJS cố gắng mô phỏng WebSocket nên nó cũng vượt qua Chính sách Same Origin.
Điều này có nghĩa là các developer cần chủ động bảo vệ ứng dụng của mình khỏi các domain bên ngoài khi sử dụng SockJS.

[[websocket-sameorigin-spring]]
=== Origin được Spring WebSocket cho phép

May mắn là kể từ Spring 4.1.5, hỗ trợ WebSocket và SockJS của Spring hạn chế quyền truy cập vào {spring-framework-reference-url}web/websocket/server.html#websocket-server-allowed-origins[domain hiện tại].
Spring Security bổ sung một lớp bảo vệ khác để cung cấp https://en.wikipedia.org/wiki/Defence_in_depth_(non-military)#Information_security[phòng thủ theo chiều sâu].

[[websocket-sameorigin-csrf]]
=== Thêm CSRF vào các header STOMP

Theo mặc định, Spring Security yêu cầu xref:features/exploits/csrf.adoc#csrf[CSRF token] trong mọi message kiểu `CONNECT`.
Điều này bảo đảm chỉ một site có quyền truy cập CSRF token mới có thể kết nối.
Vì chỉ các site ở *cùng origin* mới có thể truy cập CSRF token, các domain bên ngoài không được phép tạo kết nối.

Thông thường, chúng ta cần đưa CSRF token vào HTTP header hoặc HTTP parameter.
Tuy nhiên, SockJS không cho phép các tùy chọn này.
Thay vào đó, chúng ta phải đưa token vào các header STOMP.

Ứng dụng có thể xref:servlet/exploits/csrf.adoc#csrf-integration[lấy CSRF token] bằng cách truy cập request attribute có tên `_csrf`.
Ví dụ sau cho phép truy cập `CsrfToken` trong JSP:

[source,javascript]
----
var headerName = "${_csrf.headerName}";
var token = "${_csrf.token}";
----

Nếu sử dụng HTML tĩnh, bạn có thể công khai `CsrfToken` trên một REST endpoint.
Ví dụ sau công khai `CsrfToken` trên URL `/csrf`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@RestController
public class CsrfController {

    @RequestMapping("/csrf")
    public CsrfToken csrf(CsrfToken token) {
        return token;
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@RestController
class CsrfController {

    @RequestMapping("/csrf")
    fun csrf(token: CsrfToken): CsrfToken {
        return token
    }
}
----
======

JavaScript có thể thực hiện lệnh gọi REST tới endpoint và sử dụng response để điền `headerName` và token.

Bây giờ chúng ta có thể đưa token vào STOMP client:

[source,javascript]
----
...
var headers = {};
headers[headerName] = token;
stompClient.connect(headers, function(frame) {
  ...

})
----

[[websocket-sameorigin-disable]]
=== Vô hiệu hóa CSRF trong WebSocket
NOTE: Hiện tại, CSRF không thể cấu hình khi sử dụng `@EnableWebSocketSecurity`, dù khả năng này có thể được bổ sung trong một bản phát hành tương lai.

Để vô hiệu hóa CSRF, thay vì sử dụng `@EnableWebSocketSecurity`, bạn có thể sử dụng hỗ trợ XML hoặc tự thêm các thành phần Spring Security, như sau:

include-code::./WebSocketSecurityConfig[tag=snippet,indent=0]

[[websocket-expression-handler]]
=== Expression Handler tùy chỉnh

Đôi khi, việc tùy chỉnh cách xử lý các biểu thức `access` được định nghĩa trong các phần tử XML `intercept-message` có thể hữu ích.
Để thực hiện việc này, bạn có thể tạo một class kiểu `SecurityExpressionHandler<MessageAuthorizationContext<?>>` và tham chiếu nó trong định nghĩa XML như sau:

[source,xml]
----
<websocket-message-broker use-authorization-manager="true">
    <expression-handler ref="myRef"/>
    ...
</websocket-message-broker>

<b:bean ref="myRef" class="org.springframework.security.messaging.access.expression.MessageAuthorizationContextSecurityExpressionHandler"/>
----

Nếu bạn đang di chuyển từ cách sử dụng cũ của `websocket-message-broker`, vốn triển khai `SecurityExpressionHandler<Message<?>>`, bạn có thể:
 1. Triển khai bổ sung method `createEvaluationContext(Supplier, Message)` rồi
 2. Bọc giá trị đó trong một `MessageAuthorizationContextSecurityExpressionHandler` như sau:

[source,xml]
----
<websocket-message-broker use-authorization-manager="true">
    <expression-handler ref="myRef"/>
    ...
</websocket-message-broker>

<b:bean ref="myRef" class="org.springframework.security.messaging.access.expression.MessageAuthorizationContextSecurityExpressionHandler">
    <b:constructor-arg>
        <b:bean class="org.example.MyLegacyExpressionHandler"/>
    </b:constructor-arg>
</b:bean>
----

[[websocket-sockjs]]
== Làm việc với SockJS

{spring-framework-reference-url}web/websocket/fallback.html[SockJS] cung cấp các transport dự phòng để hỗ trợ những trình duyệt cũ hơn.
Khi sử dụng các tùy chọn dự phòng, chúng ta cần nới lỏng một vài ràng buộc bảo mật để SockJS hoạt động với Spring Security.

[[websocket-sockjs-sameorigin]]
=== SockJS và frame-options

SockJS có thể sử dụng một https://github.com/sockjs/sockjs-client/tree/v0.3.4[transport tận dụng iframe].
Theo mặc định, Spring Security xref:features/exploits/headers.adoc#headers-frame-options[từ chối] việc nhúng site bằng frame để ngăn chặn các cuộc tấn công clickjacking.
Để các transport dựa trên frame của SockJS hoạt động, chúng ta cần cấu hình Spring Security cho phép site ở cùng origin nhúng nội dung bằng frame.

Bạn có thể tùy chỉnh `X-Frame-Options` bằng phần tử xref:servlet/appendix/namespace/http.adoc#nsa-frame-options[frame-options].
Ví dụ sau chỉ dẫn Spring Security sử dụng `X-Frame-Options: SAMEORIGIN`, cho phép iframe trong cùng domain:

[source,xml]
----
<http>
    <!-- ... -->

    <headers>
        <frame-options
          policy="SAMEORIGIN" />
    </headers>
</http>
----

Tương tự, bạn có thể tùy chỉnh frame options để sử dụng cùng origin trong Java Configuration bằng cách sau:

include-code::./WebSecurityConfig[tag=snippet,indent=0]

[[websocket-sockjs-csrf]]
=== SockJS và nới lỏng CSRF

SockJS sử dụng POST cho các message `CONNECT` trên mọi transport dựa trên HTTP.
Thông thường, chúng ta cần đưa CSRF token vào HTTP header hoặc HTTP parameter.
Tuy nhiên, SockJS không cho phép các tùy chọn này.
Thay vào đó, chúng ta phải đưa token vào các header STOMP như mô tả trong <<websocket-sameorigin-csrf>>.

Điều này cũng có nghĩa là chúng ta cần nới lỏng cơ chế bảo vệ CSRF ở lớp web.
Cụ thể, chúng ta muốn vô hiệu hóa bảo vệ CSRF cho các URL connect.
Chúng ta KHÔNG muốn vô hiệu hóa bảo vệ CSRF cho mọi URL.
Nếu không, site của chúng ta sẽ dễ bị tấn công CSRF.

Chúng ta có thể dễ dàng đạt được điều này bằng cách cung cấp một CSRF `RequestMatcher`.
Cấu hình Java giúp việc này trở nên dễ dàng.
Ví dụ, nếu STOMP endpoint của chúng ta là `/chat`, chúng ta chỉ có thể vô hiệu hóa bảo vệ CSRF cho các URL bắt đầu bằng `/chat/` bằng cách sử dụng cấu hình sau:

include-code::./WebSecurityConfig[tag=snippet,indent=0]

Nếu sử dụng cấu hình dựa trên XML, chúng ta có thể sử dụng xref:servlet/appendix/namespace/http.adoc#nsa-csrf-request-matcher-ref[csrf@request-matcher-ref].

include-code::./WebSocketSecurityConfig[tag=snippet,indent=0]

[[legacy-websocket-configuration]]
== Cấu hình WebSocket cũ

`AbstractSecurityWebSocketMessageBrokerConfigurer` và `MessageSecurityMetadataSourceRegistry` đã bị xóa kể từ Spring Security 7.
Vui lòng xem {site-url}/5.8/migration/servlet/authorization.html#_use_authorizationmanager_for_message_security[hướng dẫn di chuyển 5.8] để biết hướng dẫn.
