= OAuth2

Spring Security cung cấp hỗ trợ OAuth 2.0 toàn diện.
Phần này trình bày cách tích hợp OAuth 2.0 vào ứng dụng dựa trên Servlet.

[[oauth2-overview]]
== Tổng quan

Hỗ trợ OAuth 2.0 của Spring Security gồm ba nhóm tính năng chính:

* <<oauth2-resource-server>>
* <<oauth2-client>>
* xref:servlet/oauth2/authorization-server/index.adoc[Authorization Server OAuth2]

[NOTE]
====
<<oauth2-client-log-users-in,OAuth2 Login>> là một tính năng OAuth2 Client rất mạnh, xứng đáng có một phần riêng trong tài liệu tham khảo.
Tuy nhiên, tính năng này không tồn tại độc lập và cần OAuth2 Client để hoạt động.
====

Các nhóm tính năng này bao quát các vai trò _resource server_, _client_ và _authorization server_ được định nghĩa trong https://tools.ietf.org/html/rfc6749#section-1.1[OAuth 2.0 Authorization Framework].

Các vai trò _resource server_ và _client_ trong OAuth2 thường được đại diện bởi một hoặc nhiều ứng dụng phía server.
Ngoài ra, vai trò _authorization server_ có thể được đại diện bởi một hoặc nhiều bên thứ ba (như khi tập trung việc quản lý identity và/hoặc authentication trong một tổ chức) *-hoặc-* có thể được đại diện bởi một ứng dụng (như với tính năng _authorization server_).

Ví dụ, một kiến trúc microservices dựa trên OAuth2 điển hình có thể gồm một ứng dụng client hướng người dùng, một số resource server backend cung cấp REST API và một authorization server bên thứ ba để quản lý người dùng cùng các vấn đề authentication.
Cũng thường gặp trường hợp một ứng dụng chỉ đại diện cho một trong các vai trò này và cần tích hợp với một hoặc nhiều bên thứ ba cung cấp các vai trò còn lại.

Spring Security xử lý các tình huống này và nhiều tình huống khác.
Các phần sau trình bày những vai trò được Spring Security cung cấp và chứa các ví dụ cho những tình huống phổ biến.

[[oauth2-resource-server]]
== OAuth2 Resource Server

[NOTE]
====
Phần này tóm tắt các tính năng OAuth2 Resource Server kèm ví dụ.
Xem xref:servlet/oauth2/resource-server/index.adoc[OAuth 2.0 Resource Server] để đọc tài liệu tham khảo đầy đủ.
====

Để bắt đầu, hãy thêm dependency `spring-security-oauth2-resource-server` vào project.
Khi sử dụng Spring Boot, hãy thêm starter sau:

.OAuth2 Resource Server với Spring Boot
[tabs]
======
Gradle::
+
[source,gradle,role="primary"]
----
implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
----

Maven::
+
[source,maven,role="secondary"]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>
----
======

[TIP]
====
Xem xref:getting-spring-security.adoc[] để biết các lựa chọn bổ sung khi không sử dụng Spring Boot.
====

Hãy xem xét các trường hợp sử dụng sau của OAuth2 Resource Server:

* Tôi muốn <<oauth2-resource-server-access-token,bảo vệ quyền truy cập API bằng OAuth2>> (authorization server cung cấp JWT hoặc opaque access token)
* Tôi muốn <<oauth2-resource-server-custom-jwt,bảo vệ quyền truy cập API bằng JWT>> (custom token)

[[oauth2-resource-server-access-token]]
=== Bảo vệ quyền truy cập bằng OAuth2 Access Token

Việc bảo vệ quyền truy cập API bằng OAuth2 access token rất phổ biến.
Trong hầu hết trường hợp, Spring Security chỉ yêu cầu cấu hình tối thiểu để bảo vệ một ứng dụng bằng OAuth2.

Spring Security hỗ trợ hai loại token `Bearer`, mỗi loại sử dụng một component khác nhau để validation:

* <<oauth2-resource-server-access-token-jwt,Hỗ trợ JWT>> sử dụng bean `JwtDecoder` để validation chữ ký và decode token
* <<oauth2-resource-server-access-token-opaque,Hỗ trợ opaque token>> sử dụng bean `OpaqueTokenIntrospector` để introspect token

[[oauth2-resource-server-access-token-jwt]]
==== Hỗ trợ JWT

Ví dụ sau cấu hình bean `JwtDecoder` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://my-auth-server.com
----

Khi sử dụng Spring Boot, như vậy là đủ.
Cấu hình mặc định do Spring Boot cung cấp tương đương với cấu hình sau:

.Cấu hình Resource Server với JWT
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2ResourceServer((oauth2) -> oauth2
				.jwt(Customizer.withDefaults())
			);
		return http.build();
	}

	@Bean
	public JwtDecoder jwtDecoder() {
		return JwtDecoders.fromIssuerLocation("https://my-auth-server.com");
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			authorizeHttpRequests {
				authorize(anyRequest, authenticated)
			}
			oauth2ResourceServer {
				jwt { }
			}
		}

		return http.build()
	}

	@Bean
	fun jwtDecoder(): JwtDecoder {
		return JwtDecoders.fromIssuerLocation("https://my-auth-server.com")
	}

}
----
=====

[[oauth2-resource-server-access-token-opaque]]
==== Hỗ trợ Opaque Token

Ví dụ sau cấu hình bean `OpaqueTokenIntrospector` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://my-auth-server.com/oauth2/introspect
          client-id: my-client-id
          client-secret: my-client-secret
----

Khi sử dụng Spring Boot, như vậy là đủ.
Cấu hình mặc định do Spring Boot cung cấp tương đương với cấu hình sau:

.Cấu hình Resource Server với Opaque Token
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2ResourceServer((oauth2) -> oauth2
				.opaqueToken(Customizer.withDefaults())
			);
		return http.build();
	}

	@Bean
	public OpaqueTokenIntrospector opaqueTokenIntrospector() {
		return new SpringOpaqueTokenIntrospector(
			"https://my-auth-server.com/oauth2/introspect", "my-client-id", "my-client-secret");
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			authorizeHttpRequests {
				authorize(anyRequest, authenticated)
			}
			oauth2ResourceServer {
				opaqueToken { }
			}
		}

		return http.build()
	}

	@Bean
	fun opaqueTokenIntrospector(): OpaqueTokenIntrospector {
		return SpringOpaqueTokenIntrospector(
			"https://my-auth-server.com/oauth2/introspect", "my-client-id", "my-client-secret"
		)
	}

}
----
=====

[[oauth2-resource-server-custom-jwt]]
=== Bảo vệ quyền truy cập bằng custom JWT

Bảo vệ quyền truy cập API bằng JWT là một nhu cầu khá phổ biến, đặc biệt khi frontend được phát triển dưới dạng single-page application.
Hỗ trợ OAuth2 Resource Server trong Spring Security có thể được sử dụng cho mọi loại token `Bearer`, bao gồm custom JWT.

Để bảo vệ API bằng JWT, chỉ cần một bean `JwtDecoder`, được dùng để validation chữ ký và decode token.
Spring Security sẽ tự động sử dụng bean được cung cấp để cấu hình việc bảo vệ trong `SecurityFilterChain`.

Ví dụ sau cấu hình bean `JwtDecoder` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:my-public-key.pub
----

[NOTE]
====
Bạn có thể cung cấp public key dưới dạng classpath resource (trong ví dụ này có tên `my-public-key.pub`).
====

Khi sử dụng Spring Boot, như vậy là đủ.
Cấu hình mặc định do Spring Boot cung cấp tương đương với cấu hình sau:

.Cấu hình Resource Server với Custom JWT
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2ResourceServer((oauth2) -> oauth2
				.jwt(Customizer.withDefaults())
			);
		return http.build();
	}

	@Bean
	public JwtDecoder jwtDecoder() {
		return NimbusJwtDecoder.withPublicKey(publicKey()).build();
	}

	private RSAPublicKey publicKey() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			authorizeHttpRequests {
				authorize(anyRequest, authenticated)
			}
			oauth2ResourceServer {
				jwt { }
			}
		}

		return http.build()
	}

	@Bean
	fun jwtDecoder(): JwtDecoder {
		return NimbusJwtDecoder.withPublicKey(publicKey()).build()
	}

	private fun publicKey(): RSAPublicKey {
		// ...
	}

}
----
=====

[NOTE]
====
Spring Security không cung cấp endpoint để mint token.
Tuy nhiên, Spring Security cung cấp interface `JwtEncoder` cùng một implementation là `NimbusJwtEncoder`.
====

[[oauth2-client]]
== OAuth2 Client

[NOTE]
====
Phần này tóm tắt các tính năng OAuth2 Client kèm ví dụ.
Xem xref:servlet/oauth2/client/index.adoc[OAuth 2.0 Client] và xref:servlet/oauth2/login/index.adoc[OAuth 2.0 Login] để đọc tài liệu tham khảo đầy đủ.
====

Để bắt đầu, hãy thêm dependency `spring-security-oauth2-client` vào project.
Khi sử dụng Spring Boot, hãy thêm starter sau:

.OAuth2 Client với Spring Boot
[tabs]
======
Gradle::
+
[source,gradle,role="primary"]
----
implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
----

Maven::
+
[source,maven,role="secondary"]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-oauth2-client</artifactId>
</dependency>
----
======

[TIP]
====
Xem xref:getting-spring-security.adoc[] để biết các lựa chọn bổ sung khi không sử dụng Spring Boot.
====

Hãy xem xét các trường hợp sử dụng sau của OAuth2 Client:

* Tôi muốn <<oauth2-client-log-users-in,đăng nhập người dùng bằng OAuth 2.0 hoặc OpenID Connect 1.0>>
* Tôi muốn <<oauth2-client-access-protected-resources,dùng `RestClient` để lấy access token cho người dùng>> nhằm truy cập API bên thứ ba
* Tôi muốn <<oauth2-client-access-protected-resources-webclient,dùng `WebClient` để lấy access token cho người dùng>> nhằm truy cập API bên thứ ba
* Tôi muốn <<oauth2-client-access-protected-resources-current-user,làm cả hai việc>> (đăng nhập người dùng _và_ truy cập API bên thứ ba)
* Tôi muốn <<oauth2-client-client-credentials,dùng grant type `client_credentials`>> để lấy một token cho mỗi ứng dụng
* Tôi muốn <<oauth2-client-enable-extension-grant-type,bật một extension grant type>>
* Tôi muốn <<oauth2-client-customize-existing-grant-type,tùy chỉnh một grant type hiện có>>
* Tôi muốn <<oauth2-client-customize-request-parameters,tùy chỉnh các tham số yêu cầu token>>
* Tôi muốn <<oauth2-client-customize-rest-client,tùy chỉnh `RestClient` được các component OAuth2 Client sử dụng>>

[[oauth2-client-log-users-in]]
=== Đăng nhập người dùng bằng OAuth2

Việc yêu cầu người dùng đăng nhập qua OAuth2 rất phổ biến.
https://openid.net/specs/openid-connect-core-1_0.html[OpenID Connect 1.0] cung cấp một token đặc biệt gọi là `id_token`, được thiết kế để cung cấp cho OAuth2 Client khả năng xác minh identity của người dùng và đăng nhập người dùng.
Trong một số trường hợp, OAuth2 có thể được dùng trực tiếp để đăng nhập người dùng (như với các provider social login phổ biến không triển khai OpenID Connect, chẳng hạn GitHub và Facebook).

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có khả năng đăng nhập người dùng bằng OAuth2 hoặc OpenID Connect:

.Cấu hình OAuth2 Login
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			// ...
			.oauth2Login(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			// ...
			oauth2Login { }
		}

		return http.build()
	}

}
----
=====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryClientRegistrationRepository` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc-client:
            provider: my-oidc-provider
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          my-oidc-provider:
            issuer-uri: https://my-oidc-provider.com
----

Với cấu hình trên, ứng dụng hiện hỗ trợ thêm hai endpoint:

1. Login endpoint (ví dụ `/oauth2/authorization/my-oidc-client`) được dùng để bắt đầu đăng nhập và thực hiện redirect đến authorization server bên thứ ba.
2. Redirection endpoint (ví dụ `/login/oauth2/code/my-oidc-client`) được authorization server dùng để redirect trở lại ứng dụng client và sẽ chứa tham số `code`, được dùng để lấy `id_token` và/hoặc `access_token` thông qua access token request.

[NOTE]
====
Sự hiện diện của scope `openid` trong cấu hình trên cho biết cần sử dụng OpenID Connect 1.0.
Điều này yêu cầu Spring Security sử dụng các component đặc thù của OIDC (chẳng hạn `OidcUserService`) trong quá trình xử lý request.
Nếu không có scope này, Spring Security sẽ sử dụng các component đặc thù của OAuth2 (chẳng hạn `DefaultOAuth2UserService`).
====

[[oauth2-client-access-protected-resources]]
=== Truy cập protected resource

Gửi request đến API bên thứ ba được bảo vệ bởi OAuth2 là một trường hợp sử dụng cốt lõi của OAuth2 Client.
Việc này được thực hiện bằng cách authorize một client (được đại diện bởi class `OAuth2AuthorizedClient` trong Spring Security) và truy cập protected resource bằng cách đặt token `Bearer` vào header `Authorization` của request outbound.

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có khả năng yêu cầu protected resource từ API bên thứ ba:

.Cấu hình OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			// ...
			.oauth2Client(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			// ...
			oauth2Client { }
		}

		return http.build()
	}

}
----
=====

[NOTE]
====
Ví dụ trên không cung cấp cách đăng nhập người dùng.
Bạn có thể sử dụng bất kỳ cơ chế đăng nhập nào khác (chẳng hạn `formLogin()`).
Xem <<oauth2-client-access-protected-resources-current-user,phần tiếp theo>> để biết ví dụ kết hợp `oauth2Client()` với `oauth2Login()`.
====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryClientRegistrationRepository` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth2-client:
            provider: my-auth-server
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: message.read,message.write
        provider:
          my-auth-server:
            issuer-uri: https://my-auth-server.com
----

Ngoài việc cấu hình Spring Security để hỗ trợ các tính năng OAuth2 Client, bạn cũng cần quyết định cách truy cập protected resource và cấu hình ứng dụng tương ứng.
Spring Security cung cấp các implementation của `OAuth2AuthorizedClientManager` để lấy access token có thể dùng truy cập protected resource.

[TIP]
====
Spring Security đăng ký bean `OAuth2AuthorizedClientManager` mặc định cho bạn khi chưa có bean nào tồn tại.
====

Cách dễ nhất để sử dụng `OAuth2AuthorizedClientManager` là thông qua `ClientHttpRequestInterceptor`, interceptor các request đi qua `RestClient`; `RestClient` đã sẵn có khi `spring-web` nằm trên classpath.

Ví dụ sau sử dụng `OAuth2AuthorizedClientManager` mặc định để cấu hình `RestClient` có khả năng truy cập protected resource bằng cách đặt token `Bearer` vào header `Authorization` của mỗi request:

.Cấu hình `RestClient` với `ClientHttpRequestInterceptor`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager): RestClient {
		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)
		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

}
----
=====

`RestClient` đã cấu hình này có thể được sử dụng như trong ví dụ sau:

[[oauth2-client-accessing-protected-resources-example]]
.Sử dụng `RestClient` để truy cập protected resource
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId;

@RestController
public class MessagesController {

	private final RestClient restClient;

	public MessagesController(RestClient restClient) {
		this.restClient = restClient;
	}

	@GetMapping("/messages")
	public ResponseEntity<List<Message>> messages() {
		Message[] messages = this.restClient.get()
				.uri("http://localhost:8090/messages")
				.attributes(clientRegistrationId("my-oauth2-client"))
				.retrieve()
				.body(Message[].class);
		return ResponseEntity.ok(Arrays.asList(messages));
	}

	public record Message(String message) {
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId
import org.springframework.web.client.body

@RestController
class MessagesController(private val restClient: RestClient) {

	@GetMapping("/messages")
	fun messages(): ResponseEntity<List<Message>> {
		val messages = restClient.get()
			.uri("http://localhost:8090/messages")
			.attributes(clientRegistrationId("my-oauth2-client"))
			.retrieve()
			.body<Array<Message>>()!!
			.toList()
		return ResponseEntity.ok(messages)
	}

	data class Message(val message: String)

}
----
=====

[[oauth2-client-access-protected-resources-webclient]]
=== Truy cập protected resource bằng `WebClient`

Gửi request đến API bên thứ ba được bảo vệ bởi OAuth2 là một trường hợp sử dụng cốt lõi của OAuth2 Client.
Việc này được thực hiện bằng cách authorize một client (được đại diện bởi class `OAuth2AuthorizedClient` trong Spring Security) và truy cập protected resource bằng cách đặt token `Bearer` vào header `Authorization` của request outbound.

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có khả năng yêu cầu protected resource từ API bên thứ ba:

.Cấu hình OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			// ...
			.oauth2Client(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			// ...
			oauth2Client { }
		}

		return http.build()
	}

}
----
=====

[NOTE]
====
Ví dụ trên không cung cấp cách đăng nhập người dùng.
Bạn có thể sử dụng bất kỳ cơ chế đăng nhập nào khác (chẳng hạn `formLogin()`).
Xem <<oauth2-client-access-protected-resources-current-user,phần trước>> để biết ví dụ kết hợp `oauth2Client()` với `oauth2Login()`.
====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryClientRegistrationRepository` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth2-client:
            provider: my-auth-server
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: message.read,message.write
        provider:
          my-auth-server:
            issuer-uri: https://my-auth-server.com
----

Ngoài việc cấu hình Spring Security để hỗ trợ các tính năng OAuth2 Client, bạn cũng cần quyết định cách truy cập protected resource và cấu hình ứng dụng tương ứng.
Spring Security cung cấp các implementation của `OAuth2AuthorizedClientManager` để lấy access token có thể dùng truy cập protected resource.

[TIP]
====
Spring Security đăng ký bean `OAuth2AuthorizedClientManager` mặc định cho bạn khi chưa có bean nào tồn tại.
====

<<oauth2-client-access-protected-resources,Thay vì cấu hình `RestClient`>>, một cách khác để sử dụng `OAuth2AuthorizedClientManager` là thông qua `ExchangeFilterFunction`, interceptor các request đi qua `WebClient`.
Để sử dụng `WebClient`, bạn cần thêm dependency `spring-webflux` cùng một reactive client implementation:

.Thêm dependency Spring WebFlux
[tabs]
======
Gradle::
+
[source,gradle,role="primary"]
----
implementation 'org.springframework:spring-webflux'
implementation 'io.projectreactor.netty:reactor-netty'
----

Maven::
+
[source,maven,role="secondary"]
----
<dependency>
	<groupId>org.springframework</groupId>
	<artifactId>spring-webflux</artifactId>
</dependency>
<dependency>
	<groupId>io.projectreactor.netty</groupId>
	<artifactId>reactor-netty</artifactId>
</dependency>
----
======

Ví dụ sau sử dụng `OAuth2AuthorizedClientManager` mặc định để cấu hình `WebClient` có khả năng truy cập protected resource bằng cách đặt token `Bearer` vào header `Authorization` của mỗi request:

.Cấu hình `WebClient` với `ExchangeFilterFunction`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class WebClientConfig {

	@Bean
	public WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		ServletOAuth2AuthorizedClientExchangeFilterFunction filter =
				new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
		return WebClient.builder()
				.apply(filter.oauth2Configuration())
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class WebClientConfig {

	@Bean
	fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager): WebClient {
		val filter = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
		return WebClient.builder()
			.apply(filter.oauth2Configuration())
			.build()
	}

}
----
=====

`WebClient` đã cấu hình này có thể được sử dụng như trong ví dụ sau:

.Sử dụng `WebClient` để truy cập protected resource
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.client.web.reactive.function.client.ServletOAuth2AuthorizedClientExchangeFilterFunction.clientRegistrationId;

@RestController
public class MessagesController {

	private final WebClient webClient;

	public MessagesController(WebClient webClient) {
		this.webClient = webClient;
	}

	@GetMapping("/messages")
	public ResponseEntity<List<Message>> messages() {
		return this.webClient.get()
				.uri("http://localhost:8090/messages")
				.attributes(clientRegistrationId("my-oauth2-client"))
				.retrieve()
				.toEntityList(Message.class)
				.block();
	}

	public record Message(String message) {
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.client.web.reactive.function.client.ServletOAuth2AuthorizedClientExchangeFilterFunction.clientRegistrationId

@RestController
class MessagesController(private val webClient: WebClient) {

	@GetMapping("/messages")
	fun messages(): ResponseEntity<List<Message>> {
		return webClient.get()
			.uri("http://localhost:8090/messages")
			.attributes(clientRegistrationId("my-oauth2-client"))
			.retrieve()
			.toEntityList<Message>()
			.block()!!
	}

	data class Message(val message: String)

}
----
=====

[[oauth2-client-access-protected-resources-current-user]]
=== Truy cập protected resource cho user hiện tại

Khi người dùng đăng nhập qua OAuth2 hoặc OpenID Connect, authorization server có thể cung cấp access token để trực tiếp truy cập protected resource.
Điều này thuận tiện vì chỉ cần cấu hình một `ClientRegistration` cho đồng thời cả hai trường hợp sử dụng.

[NOTE]
====
Phần này kết hợp <<oauth2-client-log-users-in>> và <<oauth2-client-access-protected-resources>> vào một cấu hình duy nhất.
Có những tình huống nâng cao khác, chẳng hạn cấu hình một `ClientRegistration` cho đăng nhập và một `ClientRegistration` khác để truy cập protected resource.
Tất cả tình huống như vậy đều sử dụng cùng cấu hình cơ bản.
====

Ví dụ sau cấu hình ứng dụng hoạt động như một OAuth2 Client có khả năng đăng nhập người dùng _và_ yêu cầu protected resource từ API bên thứ ba:

.Cấu hình OAuth2 Login và OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			// ...
			.oauth2Login(Customizer.withDefaults())
			.oauth2Client(Customizer.withDefaults());
		return http.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		http {
			// ...
			oauth2Login { }
			oauth2Client { }
		}

		return http.build()
	}

}
----
=====

Ngoài cấu hình trên, ứng dụng cần cấu hình ít nhất một `ClientRegistration` thông qua bean `ClientRegistrationRepository`.
Ví dụ sau cấu hình bean `InMemoryClientRegistrationRepository` bằng các configuration properties của Spring Boot:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-combined-client:
            provider: my-auth-server
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: authorization_code
            scope: openid,profile,message.read,message.write
        provider:
          my-auth-server:
            issuer-uri: https://my-auth-server.com
----

[NOTE]
====
Khác biệt chính giữa các ví dụ trước (<<oauth2-client-log-users-in>>,  <<oauth2-client-access-protected-resources>>) và ví dụ này nằm ở cấu hình thông qua property `scope`, trong đó kết hợp các scope chuẩn `openid` và `profile` với các scope tùy chỉnh `message.read` và `message.write`.
====

Ngoài việc cấu hình Spring Security để hỗ trợ các tính năng OAuth2 Client, bạn cũng cần quyết định cách truy cập protected resource và cấu hình ứng dụng tương ứng.
Spring Security cung cấp các implementation của `OAuth2AuthorizedClientManager` để lấy access token có thể dùng truy cập protected resource.

[TIP]
====
Spring Security đăng ký bean `OAuth2AuthorizedClientManager` mặc định cho bạn khi chưa có bean nào tồn tại.
====

Cách dễ nhất để sử dụng `OAuth2AuthorizedClientManager` là thông qua `ClientHttpRequestInterceptor`, interceptor các request đi qua `RestClient`; `RestClient` đã sẵn có khi `spring-web` nằm trên classpath.

Ví dụ sau sử dụng `OAuth2AuthorizedClientManager` mặc định để cấu hình `RestClient` có khả năng truy cập protected resource bằng cách đặt token `Bearer` vào header `Authorization` của mỗi request:

.Cấu hình `RestClient` với `ClientHttpRequestInterceptor`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
		requestInterceptor.setClientRegistrationIdResolver(clientRegistrationIdResolver());

		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

	private static ClientRegistrationIdResolver clientRegistrationIdResolver() {
		return (request) -> {
			Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
			return (authentication instanceof OAuth2AuthenticationToken principal)
				? principal.getAuthorizedClientRegistrationId()
				: null;
		};
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager): RestClient {
		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)
		requestInterceptor.setClientRegistrationIdResolver(clientRegistrationIdResolver())

		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

	private fun clientRegistrationIdResolver(): OAuth2ClientHttpRequestInterceptor.ClientRegistrationIdResolver {
		return OAuth2ClientHttpRequestInterceptor.ClientRegistrationIdResolver { request ->
			val authentication = SecurityContextHolder.getContext().authentication
			if (authentication is OAuth2AuthenticationToken) {
				authentication.authorizedClientRegistrationId
			} else {
				null
			}
		}
	}

}
----
=====

`RestClient` đã cấu hình này có thể được sử dụng như trong ví dụ sau:

[[oauth2-client-accessing-protected-resources-current-user-example]]
.Sử dụng `RestClient` để truy cập protected resource (user hiện tại)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@RestController
public class MessagesController {

	private final RestClient restClient;

	public MessagesController(RestClient restClient) {
		this.restClient = restClient;
	}

	@GetMapping("/messages")
	public ResponseEntity<List<Message>> messages() {
		Message[] messages = this.restClient.get()
				.uri("http://localhost:8090/messages")
				.retrieve()
				.body(Message[].class);
		return ResponseEntity.ok(Arrays.asList(messages));
	}

	public record Message(String message) {
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.web.client.body

@RestController
class MessagesController(private val restClient: RestClient) {

	@GetMapping("/messages")
	fun messages(): ResponseEntity<List<Message>> {
		val messages = restClient.get()
			.uri("http://localhost:8090/messages")
			.retrieve()
			.body<Array<Message>>()!!
			.toList()
		return ResponseEntity.ok(messages)
	}

	data class Message(val message: String)

}
----
=====

[NOTE]
====
Không giống <<oauth2-client-accessing-protected-resources-example,ví dụ trước>>, hãy lưu ý rằng chúng ta không cần cho Spring Security biết `clientRegistrationId` muốn sử dụng.
Đó là vì giá trị này có thể được suy ra từ người dùng đang đăng nhập.
====

[[oauth2-client-client-credentials]]
=== Sử dụng Client Credentials Grant

[NOTE]
====
Phần này tập trung vào những điều cần cân nhắc thêm đối với grant type client credentials.
Xem <<oauth2-client-access-protected-resources>> để biết cách thiết lập và sử dụng chung với mọi grant type.
====

https://tools.ietf.org/html/rfc6749#section-1.3.4[client credentials grant] cho phép client lấy `access_token` thay mặt cho chính nó.
Client credentials grant là một flow đơn giản, không liên quan đến resource owner (tức là người dùng).

[WARNING]
====
Điều quan trọng cần lưu ý là việc sử dụng client credentials grant theo cách thông thường ngụ ý rằng bất kỳ request (hoặc người dùng) nào cũng có thể lấy access token và gửi request đến protected resource của resource server.
Hãy thận trọng khi thiết kế ứng dụng để bảo đảm người dùng không thể gửi request trái phép, vì mọi request đều có thể lấy access token.
====

Khi lấy access token trong một web application nơi người dùng có thể đăng nhập, hành vi mặc định của Spring Security là lấy một access token cho mỗi người dùng.

[NOTE]
====
Theo mặc định, access token được scope theo tên principal của người dùng hiện tại, nghĩa là mỗi người dùng sẽ nhận một access token riêng.
====

Client sử dụng client credentials grant thường yêu cầu access token được scope theo ứng dụng thay vì từng người dùng, để mỗi ứng dụng chỉ có một access token.
Để scope access token theo ứng dụng, bạn cần thiết lập strategy để resolve tên principal tùy chỉnh.
Ví dụ sau thực hiện việc này bằng cách cấu hình `RestClient` với `RequestAttributePrincipalResolver`:

.Cấu hình `RestClient` cho `client_credentials`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class RestClientConfig {

	@Bean
	public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager) {
		OAuth2ClientHttpRequestInterceptor requestInterceptor =
				new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
		requestInterceptor.setPrincipalResolver(new RequestAttributePrincipalResolver());
		return RestClient.builder()
				.requestInterceptor(requestInterceptor)
				.build();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class RestClientConfig {

	@Bean
	fun restClient(authorizedClientManager: OAuth2AuthorizedClientManager): RestClient {
		val requestInterceptor = OAuth2ClientHttpRequestInterceptor(authorizedClientManager)
		requestInterceptor.setPrincipalResolver(RequestAttributePrincipalResolver())
		return RestClient.builder()
			.requestInterceptor(requestInterceptor)
			.build()
	}

}
----
=====

Với cấu hình trên, có thể chỉ định tên principal cho mỗi request.
Ví dụ sau minh họa cách scope access token theo ứng dụng bằng cách chỉ định tên principal:

.Scope access token theo ứng dụng
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId;
import static org.springframework.security.oauth2.client.web.client.RequestAttributePrincipalResolver.principal;

@RestController
public class MessagesController {

	private final RestClient restClient;

	public MessagesController(RestClient restClient) {
		this.restClient = restClient;
	}

	@GetMapping("/messages")
	public ResponseEntity<List<Message>> messages() {
		Message[] messages = this.restClient.get()
				.uri("http://localhost:8090/messages")
				.attributes(clientRegistrationId("my-oauth2-client"))
				.attributes(principal("my-application"))
				.retrieve()
				.body(Message[].class);
		return ResponseEntity.ok(Arrays.asList(messages));
	}

	public record Message(String message) {
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId
import org.springframework.security.oauth2.client.web.client.RequestAttributePrincipalResolver.principal
import org.springframework.web.client.body

@RestController
class MessagesController(private val restClient: RestClient) {

	@GetMapping("/messages")
	fun messages(): ResponseEntity<List<Message>> {
		val messages = restClient.get()
			.uri("http://localhost:8090/messages")
			.attributes(clientRegistrationId("my-oauth2-client"))
			.attributes(principal("my-application"))
			.retrieve()
			.body<Array<Message>>()!!
			.toList()
		return ResponseEntity.ok(messages)
	}

	data class Message(val message: String)

}
----
=====

[NOTE]
====
Khi chỉ định tên principal thông qua attributes như trong ví dụ trên, sẽ chỉ có một access token duy nhất và token này được dùng cho mọi request.
====

[[oauth2-client-enable-extension-grant-type]]
=== Bật Extension Grant Type

Một trường hợp sử dụng phổ biến là bật và/hoặc cấu hình extension grant type.
Ví dụ, Spring Security hỗ trợ các grant type `jwt-bearer` và `token-exchange`, nhưng không bật chúng theo mặc định vì chúng không thuộc đặc tả OAuth 2.0 cốt lõi.

Với Spring Security 6.2 trở lên, chúng ta chỉ cần publish bean cho một hoặc nhiều `OAuth2AuthorizedClientProvider` và chúng sẽ được tự động phát hiện.
Ví dụ sau chỉ bật grant type `jwt-bearer`:

.Bật Grant Type `jwt-bearer`
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public OAuth2AuthorizedClientProvider jwtBearer() {
		return new JwtBearerOAuth2AuthorizedClientProvider();
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun jwtBearer(): OAuth2AuthorizedClientProvider {
		return JwtBearerOAuth2AuthorizedClientProvider()
	}

}
----
=====

Spring Security sẽ tự động publish `OAuth2AuthorizedClientManager` mặc định khi chưa có bean nào được cung cấp.

[TIP]
====
Bất kỳ bean `OAuth2AuthorizedClientProvider` tùy chỉnh nào cũng sẽ được tự động phát hiện và áp dụng cho `OAuth2AuthorizedClientManager` đã cung cấp, sau các grant type mặc định.
====

Để đạt được cấu hình trên trước Spring Security 6.2, chúng ta phải tự publish bean này và đồng thời bảo đảm bật lại các grant type mặc định.
Để hiểu những gì được cấu hình phía sau, cấu hình có thể đã có dạng như sau:

.Bật Grant Type `jwt-bearer` (trước 6.2)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public OAuth2AuthorizedClientManager authorizedClientManager(
			ClientRegistrationRepository clientRegistrationRepository,
			OAuth2AuthorizedClientRepository authorizedClientRepository) {

		OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken()
				.clientCredentials()
				.provider(new JwtBearerOAuth2AuthorizedClientProvider())
				.build();

		DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
				clientRegistrationRepository, authorizedClientRepository);
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

		return authorizedClientManager;
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun authorizedClientManager(
		clientRegistrationRepository: ClientRegistrationRepository,
		authorizedClientRepository: OAuth2AuthorizedClientRepository
	): OAuth2AuthorizedClientManager {
		val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
			.authorizationCode()
			.refreshToken()
			.clientCredentials()
			.provider(JwtBearerOAuth2AuthorizedClientProvider())
			.build()

		val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
			clientRegistrationRepository, authorizedClientRepository
		)
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

		return authorizedClientManager
	}

}
----
=====

[[oauth2-client-customize-existing-grant-type]]
=== Tùy chỉnh Grant Type hiện có

Khả năng <<oauth2-client-enable-extension-grant-type,bật extension grant type>> bằng cách publish bean cũng cho phép tùy chỉnh grant type hiện có mà không cần định nghĩa lại các giá trị mặc định.
Ví dụ, nếu muốn tùy chỉnh clock skew của `OAuth2AuthorizedClientProvider` cho grant `client_credentials`, chúng ta chỉ cần publish bean như sau:

.Tùy chỉnh Client Credentials Grant Type
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public OAuth2AuthorizedClientProvider clientCredentials() {
		ClientCredentialsOAuth2AuthorizedClientProvider authorizedClientProvider =
				new ClientCredentialsOAuth2AuthorizedClientProvider();
		authorizedClientProvider.setClockSkew(Duration.ofMinutes(5));

		return authorizedClientProvider;
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun clientCredentials(): OAuth2AuthorizedClientProvider {
		val authorizedClientProvider = ClientCredentialsOAuth2AuthorizedClientProvider()
		authorizedClientProvider.setClockSkew(Duration.ofMinutes(5))
		return authorizedClientProvider
	}

}
----
=====

[[oauth2-client-customize-request-parameters]]
=== Tùy chỉnh tham số Token Request

Nhu cầu tùy chỉnh các tham số request khi lấy access token khá phổ biến.
Ví dụ, giả sử chúng ta muốn thêm tham số tùy chỉnh `audience` vào token request vì provider yêu cầu tham số này cho grant `authorization_code`.

Với Spring Security 6.2 trở lên, chúng ta chỉ cần publish bean có type `OAuth2AccessTokenResponseClient` với generic type `OAuth2AuthorizationCodeGrantRequest`; bean này sẽ được Spring Security dùng để cấu hình các component OAuth2 Client.

Ví dụ sau tùy chỉnh các tham số token request cho grant `authorization_code` mà không dùng DSL:

.Tùy chỉnh tham số Token Request cho Authorization Code Grant
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> authorizationCodeAccessTokenResponseClient() {
		RestClientAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new RestClientAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.addParametersConverter(parametersConverter());

		return accessTokenResponseClient;
	}

	private static Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> parametersConverter() {
		return (grantRequest) -> {
			MultiValueMap<String, String> parameters = new LinkedMultiValueMap<>();
			parameters.set("audience", "xyz_value");

			return parameters;
		};
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun authorizationCodeAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> {
		val accessTokenResponseClient = RestClientAuthorizationCodeTokenResponseClient()
		accessTokenResponseClient.addParametersConverter(parametersConverter())

		return accessTokenResponseClient
	}

	private fun parametersConverter(): Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> {
		return Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> { grantRequest ->
			LinkedMultiValueMap<String, String>().also { parameters ->
				parameters["audience"] = "xyz_value"
			}
		}
	}

}
----
=====

[TIP]
====
Lưu ý rằng trong trường hợp này chúng ta không cần tùy chỉnh bean `SecurityFilterChain` và có thể dùng các giá trị mặc định.
Nếu sử dụng Spring Boot mà không có tùy chỉnh bổ sung, thực tế chúng ta có thể bỏ hoàn toàn bean `SecurityFilterChain`.
====

Trước Spring Security 6.2, chúng ta phải bảo đảm tùy chỉnh này được áp dụng cho cả OAuth2 Login (nếu sử dụng tính năng này) và các component OAuth2 Client bằng Spring Security DSL.
Để hiểu những gì được cấu hình phía sau, cấu hình có thể đã có dạng như sau:

.Tùy chỉnh tham số Token Request cho Authorization Code Grant (trước 6.2)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		RestClientAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new RestClientAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.addParametersConverter(parametersConverter());

		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login((oauth2Login) -> oauth2Login
				.tokenEndpoint((tokenEndpoint) -> tokenEndpoint
					.accessTokenResponseClient(accessTokenResponseClient)
				)
			)
			.oauth2Client((oauth2Client) -> oauth2Client
				.authorizationCodeGrant((authorizationCode) -> authorizationCode
					.accessTokenResponseClient(accessTokenResponseClient)
				)
			);

		return http.build();
	}

	private static Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> parametersConverter() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		val tokenResponseClient = RestClientAuthorizationCodeTokenResponseClient()
		tokenResponseClient.addParametersConverter(parametersConverter())

		http {
			authorizeHttpRequests {
				authorize(anyRequest, authenticated)
			}
			oauth2Login {
				tokenEndpoint {
					accessTokenResponseClient = tokenResponseClient
				}
			}
			oauth2Client {
				authorizationCodeGrant {
					accessTokenResponseClient = tokenResponseClient
				}
			}
		}

		return http.build()
	}

	private fun parametersConverter(): Converter<OAuth2AuthorizationCodeGrantRequest, MultiValueMap<String, String>> {
		// ...
	}

}
----
=====

Với các grant type khác, chúng ta có thể publish thêm các bean `OAuth2AccessTokenResponseClient` để ghi đè giá trị mặc định.
Ví dụ, để tùy chỉnh token request cho grant `client_credentials`, chúng ta có thể publish bean sau:

.Tùy chỉnh tham số Token Request cho Client Credentials Grant
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsAccessTokenResponseClient() {
		RestClientClientCredentialsTokenResponseClient accessTokenResponseClient =
				new RestClientClientCredentialsTokenResponseClient();
		accessTokenResponseClient.addParametersConverter(parametersConverter());

		return accessTokenResponseClient;
	}

	private static Converter<OAuth2ClientCredentialsGrantRequest, MultiValueMap<String, String>> parametersConverter() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun clientCredentialsAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> {
		val accessTokenResponseClient = RestClientClientCredentialsTokenResponseClient()
		accessTokenResponseClient.addParametersConverter(parametersConverter())

		return accessTokenResponseClient
	}

	private fun parametersConverter(): Converter<OAuth2ClientCredentialsGrantRequest, MultiValueMap<String, String>> {
		// ...
	}

}
----
=====

Spring Security tự động resolve các generic type sau của bean `OAuth2AccessTokenResponseClient`:

* `OAuth2AuthorizationCodeGrantRequest` (xem `RestClientAuthorizationCodeTokenResponseClient`)
* `OAuth2RefreshTokenGrantRequest` (xem `RestClientRefreshTokenTokenResponseClient`)
* `OAuth2ClientCredentialsGrantRequest` (xem `RestClientClientCredentialsTokenResponseClient`)
* `JwtBearerGrantRequest` (xem `RestClientJwtBearerTokenResponseClient`)
* `TokenExchangeGrantRequest` (xem `RestClientTokenExchangeTokenResponseClient`)

[TIP]
====
Publish bean có type `OAuth2AccessTokenResponseClient<JwtBearerGrantRequest>` sẽ tự động bật grant type `jwt-bearer` mà không cần <<oauth2-client-enable-extension-grant-type,cấu hình riêng>>.
====

[TIP]
====
Publish bean có type `OAuth2AccessTokenResponseClient<TokenExchangeGrantRequest>` sẽ tự động bật grant type `token-exchange` mà không cần <<oauth2-client-enable-extension-grant-type,cấu hình riêng>>.
====

[[oauth2-client-customize-rest-client]]
=== Tùy chỉnh `RestClient` được OAuth2 Client Component sử dụng

Một trường hợp sử dụng phổ biến khác là cần tùy chỉnh `RestClient` được dùng khi lấy access token.
Chúng ta có thể cần làm vậy để tùy chỉnh việc xử lý response (thông qua `HttpMessageConverter` tùy chỉnh) hoặc áp dụng thiết lập proxy cho network doanh nghiệp (thông qua `ClientHttpRequestFactory` tùy chỉnh).

Với Spring Security 6.2 trở lên, chúng ta chỉ cần publish các bean có type `OAuth2AccessTokenResponseClient`, Spring Security sẽ cấu hình và publish bean `OAuth2AuthorizedClientManager` thay cho chúng ta.

Ví dụ sau tùy chỉnh `RestClient` cho tất cả grant type được hỗ trợ:

.Tùy chỉnh `RestClient` cho OAuth2 Client
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
public class SecurityConfig {

	@Bean
	public OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> authorizationCodeAccessTokenResponseClient() {
		RestClientAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new RestClientAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.setRestClient(restClient());

		return accessTokenResponseClient;
	}

	@Bean
	public OAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> refreshTokenAccessTokenResponseClient() {
		RestClientRefreshTokenTokenResponseClient accessTokenResponseClient =
			new RestClientRefreshTokenTokenResponseClient();
		accessTokenResponseClient.setRestClient(restClient());

		return accessTokenResponseClient;
	}

	@Bean
	public OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsAccessTokenResponseClient() {
		RestClientClientCredentialsTokenResponseClient accessTokenResponseClient =
			new RestClientClientCredentialsTokenResponseClient();
		accessTokenResponseClient.setRestClient(restClient());

		return accessTokenResponseClient;
	}

	@Bean
	public OAuth2AccessTokenResponseClient<JwtBearerGrantRequest> jwtBearerAccessTokenResponseClient() {
		RestClientJwtBearerTokenResponseClient accessTokenResponseClient =
			new RestClientJwtBearerTokenResponseClient();
		accessTokenResponseClient.setRestClient(restClient());

		return accessTokenResponseClient;
	}

	@Bean
	public OAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> tokenExchangeAccessTokenResponseClient() {
		RestClientTokenExchangeTokenResponseClient accessTokenResponseClient =
			new RestClientTokenExchangeTokenResponseClient();
		accessTokenResponseClient.setRestClient(restClient());

		return accessTokenResponseClient;
	}

	@Bean
	public RestClient restClient() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
class SecurityConfig {

	@Bean
	fun authorizationCodeAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> {
		val accessTokenResponseClient = RestClientAuthorizationCodeTokenResponseClient()
		accessTokenResponseClient.setRestClient(restClient())

		return accessTokenResponseClient
	}

	@Bean
	fun refreshTokenAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> {
		val accessTokenResponseClient = RestClientRefreshTokenTokenResponseClient()
		accessTokenResponseClient.setRestClient(restClient())

		return accessTokenResponseClient
	}

	@Bean
	fun clientCredentialsAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> {
		val accessTokenResponseClient = RestClientClientCredentialsTokenResponseClient()
		accessTokenResponseClient.setRestClient(restClient())

		return accessTokenResponseClient
	}

	@Bean
	fun jwtBearerAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<JwtBearerGrantRequest> {
		val accessTokenResponseClient = RestClientJwtBearerTokenResponseClient()
		accessTokenResponseClient.setRestClient(restClient())

		return accessTokenResponseClient
	}

	@Bean
	fun tokenExchangeAccessTokenResponseClient(): OAuth2AccessTokenResponseClient<TokenExchangeGrantRequest> {
		val accessTokenResponseClient = RestClientTokenExchangeTokenResponseClient()
		accessTokenResponseClient.setRestClient(restClient())

		return accessTokenResponseClient
	}

	@Bean
	fun restClient(): RestClient {
		// ...
	}

}
----
=====

Spring Security sẽ tự động publish `OAuth2AuthorizedClientManager` mặc định khi chưa có bean nào được cung cấp.

[TIP]
====
Lưu ý rằng trong trường hợp này chúng ta không cần tùy chỉnh bean `SecurityFilterChain` và có thể dùng các giá trị mặc định.
Nếu sử dụng Spring Boot mà không có tùy chỉnh bổ sung, thực tế chúng ta có thể bỏ hoàn toàn bean `SecurityFilterChain`.
====

Trước Spring Security 6.2, chúng ta phải bảo đảm tùy chỉnh này được áp dụng cho cả OAuth2 Login (nếu sử dụng tính năng này) và các component OAuth2 Client.
Chúng ta phải dùng cả Spring Security DSL (cho grant `authorization_code`) và publish bean có type `OAuth2AuthorizedClientManager` cho các grant type khác.
Để hiểu những gì được cấu hình phía sau, cấu hình có thể đã có dạng như sau:

.Tùy chỉnh `RestClient` cho OAuth2 Client (trước 6.2)
[tabs]
=====
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		RestClientAuthorizationCodeTokenResponseClient accessTokenResponseClient =
			new RestClientAuthorizationCodeTokenResponseClient();
		accessTokenResponseClient.setRestClient(restClient());

		http
			// ...
			.oauth2Login((oauth2Login) -> oauth2Login
				.tokenEndpoint((tokenEndpoint) -> tokenEndpoint
					.accessTokenResponseClient(accessTokenResponseClient)
				)
			)
			.oauth2Client((oauth2Client) -> oauth2Client
				.authorizationCodeGrant((authorizationCode) -> authorizationCode
					.accessTokenResponseClient(accessTokenResponseClient)
				)
			);

		return http.build();
	}

	@Bean
	public OAuth2AuthorizedClientManager authorizedClientManager(
			ClientRegistrationRepository clientRegistrationRepository,
			OAuth2AuthorizedClientRepository authorizedClientRepository) {

		RestClientRefreshTokenTokenResponseClient refreshTokenAccessTokenResponseClient =
			new RestClientRefreshTokenTokenResponseClient();
		refreshTokenAccessTokenResponseClient.setRestClient(restClient());

		RestClientClientCredentialsTokenResponseClient clientCredentialsAccessTokenResponseClient =
			new RestClientClientCredentialsTokenResponseClient();
		clientCredentialsAccessTokenResponseClient.setRestClient(restClient());

		RestClientJwtBearerTokenResponseClient jwtBearerAccessTokenResponseClient =
			new RestClientJwtBearerTokenResponseClient();
		jwtBearerAccessTokenResponseClient.setRestClient(restClient());

		JwtBearerOAuth2AuthorizedClientProvider jwtBearerAuthorizedClientProvider =
			new JwtBearerOAuth2AuthorizedClientProvider();
		jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerAccessTokenResponseClient);

		RestClientTokenExchangeTokenResponseClient tokenExchangeAccessTokenResponseClient =
			new RestClientTokenExchangeTokenResponseClient();
		tokenExchangeAccessTokenResponseClient.setRestClient(restClient());

		TokenExchangeOAuth2AuthorizedClientProvider tokenExchangeAuthorizedClientProvider =
			new TokenExchangeOAuth2AuthorizedClientProvider();
		tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeAccessTokenResponseClient);

		OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken((refreshToken) -> refreshToken
					.accessTokenResponseClient(refreshTokenAccessTokenResponseClient)
				)
				.clientCredentials((clientCredentials) -> clientCredentials
					.accessTokenResponseClient(clientCredentialsAccessTokenResponseClient)
				)
				.provider(jwtBearerAuthorizedClientProvider)
				.provider(tokenExchangeAuthorizedClientProvider)
				.build();

		DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
				clientRegistrationRepository, authorizedClientRepository);
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

		return authorizedClientManager;
	}

	@Bean
	public RestClient restClient() {
		// ...
	}

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
import org.springframework.security.config.annotation.web.invoke

@Configuration
@EnableWebSecurity
class SecurityConfig {

	@Bean
	fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
		val tokenResponseClient = RestClientAuthorizationCodeTokenResponseClient()
		tokenResponseClient.setRestClient(restClient())

		http {
			// ...
			oauth2Login {
				tokenEndpoint {
					accessTokenResponseClient = tokenResponseClient
				}
			}
			oauth2Client {
				authorizationCodeGrant {
					accessTokenResponseClient = tokenResponseClient
				}
			}
		}

		return http.build()
	}

	@Bean
	fun authorizedClientManager(
		clientRegistrationRepository: ClientRegistrationRepository?,
		authorizedClientRepository: OAuth2AuthorizedClientRepository?
	): OAuth2AuthorizedClientManager {
		val refreshTokenAccessTokenResponseClient = RestClientRefreshTokenTokenResponseClient()
		refreshTokenAccessTokenResponseClient.setRestClient(restClient())

		val clientCredentialsAccessTokenResponseClient = RestClientClientCredentialsTokenResponseClient()
		clientCredentialsAccessTokenResponseClient.setRestClient(restClient())

		val jwtBearerAccessTokenResponseClient = RestClientJwtBearerTokenResponseClient()
		jwtBearerAccessTokenResponseClient.setRestClient(restClient())

		val jwtBearerAuthorizedClientProvider = JwtBearerOAuth2AuthorizedClientProvider()
		jwtBearerAuthorizedClientProvider.setAccessTokenResponseClient(jwtBearerAccessTokenResponseClient)

		val tokenExchangeAccessTokenResponseClient = RestClientTokenExchangeTokenResponseClient()
		tokenExchangeAccessTokenResponseClient.setRestClient(restClient())

		val tokenExchangeAuthorizedClientProvider = TokenExchangeOAuth2AuthorizedClientProvider()
		tokenExchangeAuthorizedClientProvider.setAccessTokenResponseClient(tokenExchangeAccessTokenResponseClient)

		val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
			.authorizationCode()
			.refreshToken { refreshToken ->
				refreshToken.accessTokenResponseClient(refreshTokenAccessTokenResponseClient)
			}
			.clientCredentials { clientCredentials ->
				clientCredentials.accessTokenResponseClient(clientCredentialsAccessTokenResponseClient)
			}
			.provider(jwtBearerAuthorizedClientProvider)
			.provider(tokenExchangeAuthorizedClientProvider)
			.build()

		val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
			clientRegistrationRepository, authorizedClientRepository
		)
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

		return authorizedClientManager
	}

	@Bean
	fun restClient(): RestClient {
		// ...
	}

}
----
=====


[[further-reading]]
== Đọc thêm

Các phần trước đã giới thiệu hỗ trợ OAuth2 của Spring Security cùng những ví dụ cho các tình huống phổ biến.
Bạn có thể đọc thêm về OAuth2 Client, Resource Server và Authorization Server trong các phần sau của tài liệu tham khảo:

* xref:servlet/oauth2/login/index.adoc[]
* xref:servlet/oauth2/client/index.adoc[]
* xref:servlet/oauth2/resource-server/index.adoc[]
* xref:servlet/oauth2/authorization-server/index.adoc[]
