[[servlet-authorization-authorizationfilter]]
= Ủy quyền ServerHttpRequest

Spring Security cung cấp hỗ trợ cho việc ủy quyền các HTTP request gửi đến.
Theo mặc định, authorization của Spring Security yêu cầu mọi request phải được authenticated.
Cấu hình tường minh như sau:

.Mọi request đều yêu cầu user phải được authenticated
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
    http
        .authorizeExchange((authorize) -> authorize
            .anyExchange().authenticated()
        )
        .httpBasic(withDefaults())
        .formLogin(withDefaults());
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        formLogin { }
        httpBasic { }
    }
}
----
======


Chúng ta có thể cấu hình Spring Security với các rule khác nhau bằng cách thêm các rule theo thứ tự ưu tiên.

.Nhiều rule ủy quyền request
[tabs]
======
Java::
+
[source,java,role="primary"]
----
import static org.springframework.security.authorization.AuthorityReactiveAuthorizationManager.hasRole;
// ...
@Bean
SecurityWebFilterChain springWebFilterChain(ServerHttpSecurity http) {
	// @formatter:off
	http
		// ...
		.authorizeExchange((authorize) -> authorize                          // <1>
			.pathMatchers("/resources/**", "/signup", "/about").permitAll()  // <2>
			.pathMatchers("/admin/**").hasRole("ADMIN")                      // <3>
			.pathMatchers("/db/**").access((authentication, context) ->      // <4>
				hasRole("ADMIN").check(authentication, context)
					.filter(decision -> !decision.isGranted())
					.switchIfEmpty(hasRole("DBA").check(authentication, context))
			)
			.anyExchange().denyAll()                                         // <5>
		);
	// @formatter:on
	return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {                                                           // <1>
            authorize(pathMatchers("/resources/**", "/signup", "/about"), permitAll)  // <2>
            authorize("/admin/**", hasRole("ADMIN"))                                  // <3>
            authorize("/db/**", { authentication, context ->                          // <4>
                hasRole("ADMIN").check(authentication, context)
                    .filter({ decision -> !decision.isGranted() })
                    .switchIfEmpty(hasRole("DBA").check(authentication, context))
            })
            authorize(anyExchange, denyAll)                                           // <5>
        }
        // ...
    }
}
----
======

<1> Có nhiều rule authorization được chỉ định.
Mỗi rule được xem xét theo thứ tự khai báo.
<2> Chúng ta đã chỉ định nhiều URL pattern mà mọi user đều có thể truy cập.
Cụ thể, mọi user có thể truy cập request nếu URL bắt đầu bằng "/resources/", bằng "/signup" hoặc bằng "/about".
<3> Mọi URL bắt đầu bằng "/admin/" sẽ bị giới hạn cho user có authority "ROLE_ADMIN".
Bạn sẽ thấy rằng vì gọi method `hasRole`, không cần chỉ định prefix "ROLE_".
<4> Mọi URL bắt đầu bằng "/db/" yêu cầu user có cả "ROLE_ADMIN" và "ROLE_DBA".
Điều này minh họa tính linh hoạt của việc cung cấp một `ReactiveAuthorizationManager` tùy chỉnh, cho phép triển khai logic authorization bất kỳ.
Để đơn giản, sample sử dụng lambda và delegate việc xử lý cho implementation hiện có của `AuthorityReactiveAuthorizationManager.hasRole`.
Tuy nhiên, trong tình huống thực tế, application nhiều khả năng sẽ triển khai logic trong một class riêng triển khai `ReactiveAuthorizationManager`.
<5> Mọi URL chưa được match trước đó đều bị từ chối access.
Đây là một chiến lược tốt nếu bạn không muốn vô tình quên cập nhật các rule authorization.
