[[jc-erms]]
= EnableReactiveMethodSecurity

Spring Security hỗ trợ method security bằng cách sử dụng https://projectreactor.io/docs/core/release/reference/advancedFeatures/context.html[Reactor's Context], được thiết lập bởi `ReactiveSecurityContextHolder`.
Ví dụ sau cho thấy cách truy xuất message của user hiện đã đăng nhập:

[NOTE]
====
Để ví dụ này hoạt động, kiểu trả về của method phải là `org.reactivestreams.Publisher` (tức là `Mono` hoặc `Flux`).
Điều này cần thiết để tích hợp với `Context` của Reactor.
====

[[jc-enable-reactive-method-security-authorization-manager]]
== EnableReactiveMethodSecurity với AuthorizationManager

Trong Spring Security 5.8, chúng ta có thể bật security dựa trên annotation bằng annotation `@EnableReactiveMethodSecurity(useAuthorizationManager=true)` trên bất kỳ instance `@Configuration` nào.

Điều này cải thiện `@EnableReactiveMethodSecurity` theo một số cách. `@EnableReactiveMethodSecurity(useAuthorizationManager=true)`:

1. Sử dụng API `AuthorizationManager` được đơn giản hóa thay vì metadata sources, config attributes, decision managers và voters.
Điều này giúp đơn giản hóa việc tái sử dụng và tùy chỉnh.
2. Hỗ trợ các kiểu trả về reactive, bao gồm Kotlin coroutines.
3. Được xây dựng bằng Spring AOP native, loại bỏ các abstraction và cho phép bạn sử dụng các building block của Spring AOP để tùy chỉnh.
4. Kiểm tra các annotation xung đột để đảm bảo cấu hình security không mơ hồ.
5. Tuân thủ JSR-250.

[NOTE]
====
Với các version cũ hơn, hãy đọc về hỗ trợ tương tự bằng <<jc-enable-reactive-method-security, @EnableReactiveMethodSecurity>>.
====

Ví dụ sau sẽ bật annotation `@PreAuthorize` của Spring Security:

.Cấu hình method security
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@EnableReactiveMethodSecurity(useAuthorizationManager=true)
public class MethodSecurityConfig {
	// ...
}
----
======

Sau đó, việc thêm annotation vào một method (trên class hoặc interface) sẽ giới hạn quyền truy cập vào method đó tương ứng.
Hỗ trợ annotation native của Spring Security xác định một tập attribute cho method.
Các attribute này sẽ được truyền tới nhiều method interceptor khác nhau, chẳng hạn như `AuthorizationManagerBeforeReactiveMethodInterceptor`, để interceptor đưa ra quyết định thực tế:

.Cách sử dụng annotation cho method security
[tabs]
======
Java::
+
[source,java,role="primary"]
----
public interface BankService {
	@PreAuthorize("hasRole('USER')")
	Mono<Account> readAccount(Long id);

	@PreAuthorize("hasRole('USER')")
	Flux<Account> findAccounts();

	@PreAuthorize("@func.apply(#account)")
	Mono<Account> post(Account account, Double amount);
}
----
======

Trong trường hợp này, `hasRole` tham chiếu tới method trong `SecurityExpressionRoot` được SpEL evaluation engine gọi.

`@bean` tham chiếu tới một component tùy chỉnh do bạn định nghĩa, trong đó `apply` có thể trả về `Boolean` hoặc `Mono<Boolean>` để biểu thị quyết định authorization.
Một bean như vậy có thể trông như sau:

.Expression Boolean reactive cho method security
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public Function<Account, Mono<Boolean>> func() {
    return (account) -> Mono.defer(() -> Mono.just(account.getId().equals(12)));
}
----
======

Authorization cho method là sự kết hợp giữa authorization trước method và sau method.

[NOTE]
====
Authorization trước method được thực hiện trước khi method được gọi.
Nếu authorization đó từ chối quyền truy cập, method sẽ không được gọi và một `AccessDeniedException` sẽ được ném ra.
Authorization sau method được thực hiện sau khi method được gọi nhưng trước khi method trả về cho caller.
Nếu authorization đó từ chối quyền truy cập, value sẽ không được trả về và một `AccessDeniedException` sẽ được ném ra.
====

Để tái tạo hành vi mặc định của việc thêm `@EnableReactiveMethodSecurity(useAuthorizationManager=true)`, bạn sẽ publish cấu hình sau:

.Cấu hình method security pre-post đầy đủ
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
class MethodSecurityConfig {
	@Bean
	BeanDefinitionRegistryPostProcessor aopConfig() {
		return AopConfigUtils::registerAutoProxyCreatorIfNecessary;
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	PreFilterAuthorizationReactiveMethodInterceptor preFilterInterceptor() {
		return new PreFilterAuthorizationReactiveMethodInterceptor();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	AuthorizationManagerBeforeReactiveMethodInterceptor preAuthorizeInterceptor() {
		return AuthorizationManagerBeforeReactiveMethodInterceptor.preAuthorize();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	AuthorizationManagerAfterReactiveMethodInterceptor postAuthorizeInterceptor() {
		return AuthorizationManagerAfterReactiveMethodInterceptor.postAuthorize();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	PostFilterAuthorizationReactiveMethodInterceptor postFilterInterceptor() {
		return new PostFilterAuthorizationReactiveMethodInterceptor();
	}
}
----
======

Lưu ý rằng method security của Spring Security được xây dựng bằng Spring AOP.

=== Tùy chỉnh authorization

`@PreAuthorize`, `@PostAuthorize`, `@PreFilter` và `@PostFilter` của Spring Security được cung cấp kèm hỗ trợ dựa trên expression phong phú.


[[jc-reactive-method-security-custom-granted-authority-defaults]]
Ngoài ra, đối với authorization dựa trên role, Spring Security thêm prefix `ROLE_` mặc định, được sử dụng khi đánh giá các expression như `hasRole`.
Bạn có thể cấu hình các quy tắc authorization để sử dụng prefix khác bằng cách expose một bean `GrantedAuthorityDefaults`, như sau:

.GrantedAuthorityDefaults tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
static GrantedAuthorityDefaults grantedAuthorityDefaults() {
	return new GrantedAuthorityDefaults("MYPREFIX_");
}
----
======

[TIP]
====
Chúng ta expose `GrantedAuthorityDefaults` bằng một method `static` để đảm bảo Spring publish nó trước khi khởi tạo các class `@Configuration` cho method security của Spring Security.
Vì bean `GrantedAuthorityDefaults` là một phần trong hoạt động nội bộ của Spring Security, chúng ta cũng nên expose nó dưới dạng infrastructural bean để tránh một số cảnh báo liên quan đến bean post-processing (xem https://github.com/spring-projects/spring-security/issues/14751[gh-14751]).
====

[[use-programmatic-authorization]]
== Thực hiện authorization cho method bằng lập trình

Như đã thấy, có một số cách để bạn chỉ định các quy tắc authorization phức tạp bằng cách sử dụng xref:servlet/authorization/method-security.adoc#authorization-expressions[SpEL expression cho method security].

Thay vào đó, có một số cách để bạn triển khai logic bằng Java thay vì bằng SpEL.
Điều này cho phép bạn sử dụng toàn bộ ngôn ngữ Java để tăng khả năng test và kiểm soát flow.

=== Sử dụng bean tùy chỉnh trong SpEL

Cách đầu tiên để thực hiện authorization cho method bằng lập trình là một quy trình gồm hai bước.

Trước tiên, khai báo một bean có method nhận một instance `MethodSecurityExpressionOperations` như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component("authz")
public class AuthorizationLogic {
    public decide(MethodSecurityExpressionOperations operations): Mono<Boolean> {
        // ... logic authorization
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component("authz")
open class AuthorizationLogic {
    fun decide(val operations: MethodSecurityExpressionOperations): Mono<Boolean> {
        // ... logic authorization
    }
}
----
======

Sau đó, tham chiếu bean đó trong các annotation của bạn như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Controller
public class MyController {
    @PreAuthorize("@authz.decide(#root)")
    @GetMapping("/endpoint")
    public Mono<String> endpoint() {
        // ...
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Controller
open class MyController {
    @PreAuthorize("@authz.decide(#root)")
    @GetMapping("/endpoint")
    fun endpoint(): Mono<String> {
        // ...
    }
}
----
======

Spring Security sẽ gọi method được chỉ định trên bean đó cho mỗi lần gọi method.

Ưu điểm của cách này là toàn bộ logic authorization của bạn nằm trong một class riêng, có thể được unit test độc lập và kiểm tra tính chính xác.
Logic đó cũng có quyền truy cập vào toàn bộ ngôn ngữ Java.

[TIP]
Ngoài việc trả về `Mono<Boolean>`, bạn cũng có thể trả về `Mono.empty()` để cho biết code không đưa ra quyết định.

Nếu muốn đưa thêm thông tin về bản chất của quyết định, thay vào đó bạn có thể trả về một `AuthorizationDecision` tùy chỉnh như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component("authz")
public class AuthorizationLogic {
    public Mono<AuthorizationDecision> decide(MethodSecurityExpressionOperations operations) {
        // ... logic authorization
        return Mono.just(new MyAuthorizationDecision(false, details));
    }
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component("authz")
open class AuthorizationLogic {
    fun decide(val operations: MethodSecurityExpressionOperations): Mono<AuthorizationDecision> {
        // ... logic authorization
        return Mono.just(MyAuthorizationDecision(false, details))
    }
}
----
======

Hoặc ném một instance `AuthorizationDeniedException` tùy chỉnh.
Tuy nhiên, nên trả về một object hơn vì cách này không phát sinh chi phí tạo stacktrace.

Sau đó, bạn có thể truy cập các detail tùy chỉnh khi xref:servlet/authorization/method-security.adoc#fallback-values-authorization-denied[tùy chỉnh cách xử lý kết quả authorization].

[[jc-reactive-method-security-custom-authorization-manager]]
[[custom-authorization-managers]]
=== Sử dụng AuthorizationManager tùy chỉnh

Cách thứ hai để thực hiện authorization cho method bằng lập trình là tạo một xref:servlet/authorization/architecture.adoc#_the_authorizationmanager[`AuthorizationManager`] tùy chỉnh.

Trước tiên, khai báo một instance authorization manager, chẳng hạn như instance sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class MyPreAuthorizeAuthorizationManager implements ReactiveAuthorizationManager<MethodInvocation> {
    @Override
    public Mono<AuthorizationResult> authorize(Supplier<Authentication> authentication, MethodInvocation invocation) {
        // ... logic authorization
    }

}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class MyPreAuthorizeAuthorizationManager : ReactiveAuthorizationManager<MethodInvocation> {
    override fun authorize(authentication: Supplier<Authentication>, invocation: MethodInvocation): Mono<AuthorizationResult> {
        // ... logic authorization
    }

}
----
======

Sau đó, publish method interceptor với một pointcut tương ứng với thời điểm bạn muốn `ReactiveAuthorizationManager` đó chạy.
Ví dụ, bạn có thể thay thế cách hoạt động của `@PreAuthorize` và `@PostAuthorize` như sau:

.Cấu hình chỉ cho @PreAuthorize và @PostAuthorize
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
    @Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor preAuthorize(MyPreAuthorizeAuthorizationManager manager) {
		return AuthorizationManagerBeforeReactiveMethodInterceptor.preAuthorize(manager);
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor postAuthorize(MyPostAuthorizeAuthorizationManager manager) {
		return AuthorizationManagerAfterReactiveMethodInterceptor.postAuthorize(manager);
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
   	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun preAuthorize(val manager: MyPreAuthorizeAuthorizationManager) : Advisor {
		return AuthorizationManagerBeforeReactiveMethodInterceptor.preAuthorize(manager)
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun postAuthorize(val manager: MyPostAuthorizeAuthorizationManager) : Advisor {
		return AuthorizationManagerAfterReactiveMethodInterceptor.postAuthorize(manager)
	}
}
----
======

[TIP]
====
Bạn có thể đặt interceptor của mình giữa các method interceptor của Spring Security bằng cách sử dụng các hằng số order được chỉ định trong `AuthorizationInterceptorsOrder`.
====

[[customizing-expression-handling]]
=== Tùy chỉnh xử lý expression

Hoặc, cách thứ ba là bạn có thể tùy chỉnh cách xử lý từng SpEL expression.
Để làm vậy, bạn có thể expose một `MethodSecurityExpressionHandler` tùy chỉnh như sau:

.MethodSecurityExpressionHandler tùy chỉnh
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
static MethodSecurityExpressionHandler methodSecurityExpressionHandler(RoleHierarchy roleHierarchy) {
	DefaultMethodSecurityExpressionHandler handler = new DefaultMethodSecurityExpressionHandler();
	handler.setRoleHierarchy(roleHierarchy);
	return handler;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
companion object {
	@Bean
	fun methodSecurityExpressionHandler(val roleHierarchy: RoleHierarchy) : MethodSecurityExpressionHandler {
		val handler = DefaultMethodSecurityExpressionHandler()
		handler.setRoleHierarchy(roleHierarchy)
		return handler
	}
}
----
======

[TIP]
====
Chúng ta expose `MethodSecurityExpressionHandler` bằng một method `static` để đảm bảo Spring publish nó trước khi khởi tạo các class `@Configuration` cho method security của Spring Security.
====

Bạn cũng có thể subclass xref:servlet/authorization/method-security.adoc#subclass-defaultmethodsecurityexpressionhandler[`DefaultMessageSecurityExpressionHandler`] để thêm các authorization expression tùy chỉnh của riêng mình ngoài những expression mặc định.

== EnableReactiveMethodSecurity

[tabs]
======
Java::
+
[source,java,role="primary"]
----
Authentication authentication = new TestingAuthenticationToken("user", "password", "ROLE_USER");

Mono<String> messageByUsername = ReactiveSecurityContextHolder.getContext()
	.map(SecurityContext::getAuthentication)
	.map(Authentication::getName)
	.flatMap(this::findMessageByUsername)
	// Trong một ứng dụng WebFlux, subscriberContext được tự động thiết lập bằng ReactorContextWebFilter
	.contextWrite(ReactiveSecurityContextHolder.withAuthentication(authentication));

StepVerifier.create(messageByUsername)
	.expectNext("Hi user")
	.verifyComplete();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val authentication: Authentication = TestingAuthenticationToken("user", "password", "ROLE_USER")

val messageByUsername: Mono<String> = ReactiveSecurityContextHolder.getContext()
	.map(SecurityContext::getAuthentication)
	.map(Authentication::getName)
	.flatMap(this::findMessageByUsername) // Trong một ứng dụng WebFlux, subscriberContext được tự động thiết lập bằng ReactorContextWebFilter
	.contextWrite(ReactiveSecurityContextHolder.withAuthentication(authentication))

StepVerifier.create(messageByUsername)
	.expectNext("Hi user")
	.verifyComplete()
----
======

Trong đó `this::findMessageByUsername` được định nghĩa như sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
Mono<String> findMessageByUsername(String username) {
	return Mono.just("Hi " + username);
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
fun findMessageByUsername(username: String): Mono<String> {
	return Mono.just("Hi $username")
}
----
======

Cấu hình method security tối thiểu sau đây cấu hình method security trong các ứng dụng reactive:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableReactiveMethodSecurity
public class SecurityConfig {
	@Bean
	public MapReactiveUserDetailsService userDetailsService() {
		User.UserBuilder userBuilder = User.withDefaultPasswordEncoder();
		UserDetails rob = userBuilder.username("rob")
			.password("rob")
			.roles("USER")
			.build();
		UserDetails admin = userBuilder.username("admin")
			.password("admin")
			.roles("USER","ADMIN")
			.build();
		return new MapReactiveUserDetailsService(rob, admin);
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableReactiveMethodSecurity
class SecurityConfig {
	@Bean
	fun userDetailsService(): MapReactiveUserDetailsService {
		val userBuilder: User.UserBuilder = User.withDefaultPasswordEncoder()
		val rob = userBuilder.username("rob")
			.password("rob")
			.roles("USER")
			.build()
		val admin = userBuilder.username("admin")
			.password("admin")
			.roles("USER", "ADMIN")
			.build()
		return MapReactiveUserDetailsService(rob, admin)
	}
}
----
======

Xét class sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Component
public class HelloWorldMessageService {
	@PreAuthorize("hasRole('ADMIN')")
	public Mono<String> findMessage() {
		return Mono.just("Hello World!");
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Component
class HelloWorldMessageService {
	@PreAuthorize("hasRole('ADMIN')")
	fun findMessage(): Mono<String> {
		return Mono.just("Hello World!")
	}
}
----
======

Ngoài ra, class sau sử dụng Kotlin coroutines:

[tabs]
======
Kotlin::
+
[source,kotlin,role="primary"]
----
@Component
class HelloWorldMessageService {
    @PreAuthorize("hasRole('ADMIN')")
    suspend fun findMessage(): String {
        delay(10)
        return "Hello World!"
    }
}
----
======


Kết hợp với cấu hình ở trên, `@PreAuthorize("hasRole('ADMIN')")` đảm bảo `findByMessage` chỉ được gọi bởi user có role `ADMIN`.
Lưu ý rằng mọi expression trong method security tiêu chuẩn đều hoạt động với `@EnableReactiveMethodSecurity`.
Tuy nhiên, hiện tại chúng ta chỉ hỗ trợ kiểu trả về `Boolean` hoặc `boolean` cho expression.
Điều này có nghĩa là expression không được block.

Khi tích hợp với xref:reactive/configuration/webflux.adoc#jc-webflux[WebFlux Security], Reactor Context sẽ được Spring Security tự động thiết lập theo user đã được authenticate:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
public class SecurityConfig {

	@Bean
	SecurityWebFilterChain springWebFilterChain(ServerHttpSecurity http) throws Exception {
		return http
			// Minh họa rằng method security hoạt động
			// Thực hành tốt nhất là sử dụng cả hai để defense in depth
			.authorizeExchange((authorize) -> authorize
				.anyExchange().permitAll()
			)
			.httpBasic(withDefaults())
			.build();
	}

	@Bean
	MapReactiveUserDetailsService userDetailsService() {
		User.UserBuilder userBuilder = User.withDefaultPasswordEncoder();
		UserDetails rob = userBuilder.username("rob")
			.password("rob")
			.roles("USER")
			.build();
		UserDetails admin = userBuilder.username("admin")
			.password("admin")
			.roles("USER","ADMIN")
			.build();
		return new MapReactiveUserDetailsService(rob, admin);
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
class SecurityConfig {
	@Bean
	open fun springWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
		return http {
			authorizeExchange {
				authorize(anyExchange, permitAll)
			}
			httpBasic { }
		}
	}

	@Bean
	fun userDetailsService(): MapReactiveUserDetailsService {
		val userBuilder: User.UserBuilder = User.withDefaultPasswordEncoder()
		val rob = userBuilder.username("rob")
			.password("rob")
			.roles("USER")
			.build()
		val admin = userBuilder.username("admin")
			.password("admin")
			.roles("USER", "ADMIN")
			.build()
		return MapReactiveUserDetailsService(rob, admin)
	}
}
----
======

Bạn có thể tìm thấy sample hoàn chỉnh tại {gh-samples-url}/reactive/webflux/java/method[hellowebflux-method].
