[[webflux-oauth2-login-advanced]]
= Cấu hình nâng cao

OAuth 2.0 Authorization Framework định nghĩa các https://tools.ietf.org/html/rfc6749#section-3[Protocol Endpoints] như sau:

Quy trình authorization sử dụng hai endpoint của authorization server (HTTP resource):

* Authorization Endpoint: Được client sử dụng để lấy authorization từ resource owner thông qua chuyển hướng user-agent.
* Token Endpoint: Được client sử dụng để đổi authorization grant lấy access token, thường kèm theo client authentication.

Cũng như một endpoint của client:

* Redirection Endpoint: Được authorization server sử dụng để trả về các response chứa authorization credential cho client thông qua user-agent của resource owner.

OpenID Connect Core 1.0 specification định nghĩa https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] như sau:

UserInfo Endpoint là một OAuth 2.0 Protected Resource trả về các claim về end-user đã được authenticated.
Để lấy các claim được yêu cầu về end-user, client gửi request đến UserInfo Endpoint bằng access token nhận được qua OpenID Connect Authentication.
Các claim này thường được biểu diễn dưới dạng một JSON object chứa một tập hợp các cặp name-value của claim.

`ServerHttpSecurity.oauth2Login()` cung cấp một số tùy chọn cấu hình để customize OAuth 2.0 Login.

Đoạn code sau hiển thị đầy đủ các tùy chọn cấu hình có sẵn cho DSL `oauth2Login()`:

.Các tùy chọn cấu hình OAuth 2.0 Login
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
		http
			.oauth2Login((oauth2) -> oauth2
				.authenticationConverter(this.authenticationConverter())
				.authenticationMatcher(this.authenticationMatcher())
				.authenticationManager(this.authenticationManager())
				.authenticationSuccessHandler(this.authenticationSuccessHandler())
				.authenticationFailureHandler(this.authenticationFailureHandler())
				.clientRegistrationRepository(this.clientRegistrationRepository())
				.authorizedClientRepository(this.authorizedClientRepository())
				.authorizedClientService(this.authorizedClientService())
				.authorizationRequestResolver(this.authorizationRequestResolver())
				.authorizationRequestRepository(this.authorizationRequestRepository())
				.securityContextRepository(this.securityContextRepository())
			);

		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Login {
                authenticationConverter = authenticationConverter()
                authenticationMatcher = authenticationMatcher()
                authenticationManager = authenticationManager()
                authenticationSuccessHandler = authenticationSuccessHandler()
                authenticationFailureHandler = authenticationFailureHandler()
                clientRegistrationRepository = clientRegistrationRepository()
                authorizedClientRepository = authorizedClientRepository()
                authorizedClientService = authorizedClientService()
                authorizationRequestResolver = authorizationRequestResolver()
                authorizationRequestRepository = authorizationRequestRepository()
                securityContextRepository = securityContextRepository()
            }
        }

        return http.build()
    }
}
----
======

Các section sau trình bày chi tiết hơn về từng tùy chọn cấu hình có sẵn:

* <<webflux-oauth2-login-advanced-login-page, Trang OAuth 2.0 Login>>
* <<webflux-oauth2-login-advanced-redirection-endpoint, Endpoint chuyển hướng>>
* <<webflux-oauth2-login-advanced-userinfo-endpoint, UserInfo Endpoint>>
* <<webflux-oauth2-login-advanced-idtoken-verify, Xác minh chữ ký ID Token>>
* <<webflux-oauth2-login-advanced-oidc-logout, Logout OpenID Connect 1.0>>


[[webflux-oauth2-login-advanced-login-page]]
== Trang OAuth 2.0 Login

Theo mặc định, trang OAuth 2.0 Login được tự động tạo bởi `LoginPageGeneratingWebFilter`.
Trang login mặc định hiển thị mỗi OAuth Client đã cấu hình với `ClientRegistration.clientName` dưới dạng một link có thể khởi tạo Authorization Request (hoặc OAuth 2.0 Login).

[NOTE]
Để `LoginPageGeneratingWebFilter` hiển thị các link cho những OAuth Client đã cấu hình, `ReactiveClientRegistrationRepository` đã đăng ký cũng phải implement `Iterable<ClientRegistration>`.
Xem `InMemoryReactiveClientRegistrationRepository` để tham khảo.

Đích của link cho mỗi OAuth Client mặc định là:

`+"/oauth2/authorization/{registrationId}"+`

Dòng sau minh họa một ví dụ:

[source,html]
----
<a href="/oauth2/authorization/google">Google</a>
----

Để override trang login mặc định, hãy cấu hình `exceptionHandling().authenticationEntryPoint()` và (tùy chọn) `oauth2Login().authorizationRequestResolver()`.

Ví dụ sau minh họa cách cấu hình:

.Cấu hình trang OAuth 2.0 Login
[tabs]
======
Java::
+
[source,java,role="primary",subs="-attributes"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.exceptionHandling((exceptionHandling) -> exceptionHandling
				.authenticationEntryPoint(new RedirectServerAuthenticationEntryPoint("/login/oauth2"))
			)
			.oauth2Login((oauth2) -> oauth2
				.authorizationRequestResolver(this.authorizationRequestResolver())
			);

		return http.build();
	}

	private ServerOAuth2AuthorizationRequestResolver authorizationRequestResolver() {
		ServerWebExchangeMatcher authorizationRequestMatcher =
				new PathPatternParserServerWebExchangeMatcher(
						"/login/oauth2/authorization/{registrationId}");

		return new DefaultServerOAuth2AuthorizationRequestResolver(
				this.clientRegistrationRepository(), authorizationRequestMatcher);
	}

	...
}
----

Kotlin::
+
[source,kotlin,role="secondary",subs="-attributes"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            exceptionHandling {
                authenticationEntryPoint = RedirectServerAuthenticationEntryPoint("/login/oauth2")
            }
            oauth2Login {
                authorizationRequestResolver = authorizationRequestResolver()
            }
        }

        return http.build()
    }

    private fun authorizationRequestResolver(): ServerOAuth2AuthorizationRequestResolver {
        val authorizationRequestMatcher: ServerWebExchangeMatcher = PathPatternParserServerWebExchangeMatcher(
            "/login/oauth2/authorization/{registrationId}"
        )

        return DefaultServerOAuth2AuthorizationRequestResolver(
            clientRegistrationRepository(), authorizationRequestMatcher
        )
    }

    ...
}
----
======

[IMPORTANT]
Bạn cần cung cấp một `@Controller` với `@RequestMapping("/login/oauth2")` có khả năng render trang login tùy chỉnh.

[TIP]
====
Như đã nêu trước đó, việc cấu hình `oauth2Login().authorizationRequestResolver()` là tùy chọn.
Tuy nhiên, nếu chọn customize nó, hãy đảm bảo link đến mỗi OAuth Client khớp với pattern được cung cấp thông qua `ServerWebExchangeMatcher`.

Dòng sau minh họa một ví dụ:

[source,html]
----
<a href="/login/oauth2/authorization/google">Google</a>
----
====


[[webflux-oauth2-login-advanced-redirection-endpoint]]
== Endpoint chuyển hướng

Redirection Endpoint được Authorization Server sử dụng để trả Authorization Response (chứa authorization credential) về client thông qua user-agent của Resource Owner.

[TIP]
OAuth 2.0 Login sử dụng Authorization Code Grant.
Do đó, authorization credential là authorization code.

Redirection Endpoint mặc định của Authorization Response là `+/login/oauth2/code/{registrationId}+`.

Nếu muốn customize Redirection Endpoint của Authorization Response, hãy cấu hình như trong ví dụ sau:

.Cấu hình Redirection Endpoint
[tabs]
======
Java::
+
[source,java,role="primary",subs="-attributes"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.oauth2Login((oauth2) -> oauth2
				.authenticationMatcher(new PathPatternParserServerWebExchangeMatcher("/login/oauth2/callback/{registrationId}"))
			);

		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary",subs="-attributes"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Login {
                authenticationMatcher = PathPatternParserServerWebExchangeMatcher("/login/oauth2/callback/{registrationId}")
            }
        }

        return http.build()
    }
}
----
======

[IMPORTANT]
====
Bạn cũng cần đảm bảo `ClientRegistration.redirectUri` khớp với Redirection Endpoint tùy chỉnh của Authorization Response.

Ví dụ sau minh họa cách cấu hình:

[tabs]
======
Java::
+
[source,java,role="primary",subs="-attributes"]
----
return CommonOAuth2Provider.GOOGLE.getBuilder("google")
	.clientId("google-client-id")
	.clientSecret("google-client-secret")
	.redirectUri("{baseUrl}/login/oauth2/callback/{registrationId}")
	.build();
----

Kotlin::
+
[source,kotlin,role="secondary",subs="-attributes"]
----
return CommonOAuth2Provider.GOOGLE.getBuilder("google")
    .clientId("google-client-id")
    .clientSecret("google-client-secret")
    .redirectUri("{baseUrl}/login/oauth2/callback/{registrationId}")
    .build()
----
======
====


[[webflux-oauth2-login-advanced-userinfo-endpoint]]
== UserInfo Endpoint

UserInfo Endpoint bao gồm một số tùy chọn cấu hình, được mô tả trong các subsection sau:

* <<webflux-oauth2-login-advanced-map-authorities, Ánh xạ authority của user>>
* <<webflux-oauth2-login-advanced-oauth2-user-service, UserService OAuth 2.0>>
* <<webflux-oauth2-login-advanced-oidc-user-service, UserService OpenID Connect 1.0>>


[[webflux-oauth2-login-advanced-map-authorities]]
=== Ánh xạ authority của user

Sau khi user authenticated thành công với OAuth 2.0 Provider, `OAuth2User.getAuthorities()` (hoặc `OidcUser.getAuthorities()`) chứa một danh sách granted authority được lấy từ `OAuth2UserRequest.getAccessToken().getScopes()` và có prefix `SCOPE_`.
Các granted authority này có thể được map thành một tập hợp các instance `GrantedAuthority` mới, tập hợp này sẽ được cung cấp cho `OAuth2AuthenticationToken` khi hoàn tất authentication.

[TIP]
`OAuth2AuthenticationToken.getAuthorities()` được sử dụng để authorize các request, chẳng hạn trong `hasRole('USER')` hoặc `hasRole('ADMIN')`.

Có một vài tùy chọn để lựa chọn khi map authority của user:

* <<webflux-oauth2-login-advanced-map-authorities-grantedauthoritiesmapper, Sử dụng GrantedAuthoritiesMapper>>
* <<webflux-oauth2-login-advanced-map-authorities-reactiveoauth2userservice, Delegation-based strategy với ReactiveOAuth2UserService>>


[[webflux-oauth2-login-advanced-map-authorities-grantedauthoritiesmapper]]
==== Sử dụng GrantedAuthoritiesMapper

`GrantedAuthoritiesMapper` nhận một danh sách granted authority chứa một authority đặc biệt có kiểu `OAuth2UserAuthority` và authority string `OAUTH2_USER` (hoặc `OidcUserAuthority` và authority string `OIDC_USER`).

Đăng ký `@Bean` `GrantedAuthoritiesMapper` để nó được tự động áp dụng vào cấu hình, như trong ví dụ sau:

.Cấu hình Granted Authorities Mapper
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			...
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public GrantedAuthoritiesMapper userAuthoritiesMapper() {
		return (authorities) -> {
			Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

			authorities.forEach(authority -> {
				if (OidcUserAuthority.class.isInstance(authority)) {
					OidcUserAuthority oidcUserAuthority = (OidcUserAuthority)authority;

					OidcIdToken idToken = oidcUserAuthority.getIdToken();
					OidcUserInfo userInfo = oidcUserAuthority.getUserInfo();

					// Ánh xạ các claim tìm thấy trong idToken và/hoặc userInfo
					// thành một hoặc nhiều GrantedAuthority rồi thêm vào mappedAuthorities

				} else if (OAuth2UserAuthority.class.isInstance(authority)) {
					OAuth2UserAuthority oauth2UserAuthority = (OAuth2UserAuthority)authority;

					Map<String, Object> userAttributes = oauth2UserAuthority.getAttributes();

					// Ánh xạ các attribute tìm thấy trong userAttributes
					// thành một hoặc nhiều GrantedAuthority rồi thêm vào mappedAuthorities

				}
			});

			return mappedAuthorities;
		};
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Login { }
        }

        return http.build()
    }

    @Bean
    fun userAuthoritiesMapper(): GrantedAuthoritiesMapper = GrantedAuthoritiesMapper { authorities: Collection<GrantedAuthority> ->
        val mappedAuthorities = emptySet<GrantedAuthority>()

        authorities.forEach { authority ->
            if (authority is OidcUserAuthority) {
                val idToken = authority.idToken
                val userInfo = authority.userInfo
                // Ánh xạ các claim tìm thấy trong idToken và/hoặc userInfo
                // thành một hoặc nhiều GrantedAuthority rồi thêm vào mappedAuthorities
            } else if (authority is OAuth2UserAuthority) {
                val userAttributes = authority.attributes
                // Ánh xạ các attribute tìm thấy trong userAttributes
                // thành một hoặc nhiều GrantedAuthority rồi thêm vào mappedAuthorities
            }
        }

        mappedAuthorities
    }
}
----
======

[[webflux-oauth2-login-advanced-map-authorities-reactiveoauth2userservice]]
==== Delegation-based strategy với ReactiveOAuth2UserService

Strategy này nâng cao hơn so với việc sử dụng `GrantedAuthoritiesMapper`, nhưng cũng flexible hơn vì cho phép truy cập `OAuth2UserRequest` và `OAuth2User` (khi sử dụng OAuth 2.0 UserService) hoặc `OidcUserRequest` và `OidcUser` (khi sử dụng OpenID Connect 1.0 UserService).

`OAuth2UserRequest` (và `OidcUserRequest`) cung cấp quyền truy cập vào `OAuth2AccessToken` liên kết, rất hữu ích trong trường hợp _delegator_ cần fetch thông tin authority từ một protected resource trước khi có thể map các authority custom cho user.

Ví dụ sau cho thấy cách implement và configure một delegation-based strategy bằng OpenID Connect 1.0 UserService:

.Cấu hình ReactiveOAuth2UserService
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			...
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveOAuth2UserService<OidcUserRequest, OidcUser> oidcUserService() {
		final OidcReactiveOAuth2UserService delegate = new OidcReactiveOAuth2UserService();

		return (userRequest) -> {
			// Ủy quyền cho implementation mặc định để load user
			return delegate.loadUser(userRequest)
					.flatMap((oidcUser) -> {
						OAuth2AccessToken accessToken = userRequest.getAccessToken();
						Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

						// TODO
						// 1) Lấy thông tin authority từ protected resource bằng accessToken
						// 2) Ánh xạ thông tin authority thành một hoặc nhiều GrantedAuthority rồi thêm vào mappedAuthorities

						// 3) Tạo một bản sao của oidcUser nhưng sử dụng mappedAuthorities thay thế
						ProviderDetails providerDetails = userRequest.getClientRegistration().getProviderDetails();
						String userNameAttributeName = providerDetails.getUserInfoEndpoint().getUserNameAttributeName();
						if (StringUtils.hasText(userNameAttributeName)) {
							oidcUser = new DefaultOidcUser(mappedAuthorities, oidcUser.getIdToken(), oidcUser.getUserInfo(), userNameAttributeName);
						} else {
							oidcUser = new DefaultOidcUser(mappedAuthorities, oidcUser.getIdToken(), oidcUser.getUserInfo());
						}

						return Mono.just(oidcUser);
					});
		};
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Login { }
        }

        return http.build()
    }

    @Bean
    fun oidcUserService(): ReactiveOAuth2UserService<OidcUserRequest, OidcUser> {
        val delegate = OidcReactiveOAuth2UserService()

        return ReactiveOAuth2UserService { userRequest ->
            // Ủy quyền cho implementation mặc định để load user
            delegate.loadUser(userRequest)
                .flatMap { oidcUser ->
                    val accessToken = userRequest.accessToken
                    val mappedAuthorities = mutableSetOf<GrantedAuthority>()

                    // TODO
                    // 1) Lấy thông tin authority từ protected resource bằng accessToken
                    // 2) Ánh xạ thông tin authority thành một hoặc nhiều GrantedAuthority rồi thêm vào mappedAuthorities
                    // 3) Tạo một bản sao của oidcUser nhưng sử dụng mappedAuthorities thay thế
                    val providerDetails = userRequest.getClientRegistration().getProviderDetails()
                    val userNameAttributeName = providerDetails.getUserInfoEndpoint().getUserNameAttributeName()
                    val mappedOidcUser = if (StringUtils.hasText(userNameAttributeName)) {
                        DefaultOidcUser(mappedAuthorities, oidcUser.idToken, oidcUser.userInfo, userNameAttributeName)
                    } else {
                        DefaultOidcUser(mappedAuthorities, oidcUser.idToken, oidcUser.userInfo)
                    }

                    Mono.just(mappedOidcUser)
                }
        }
    }
}
----
======


[[webflux-oauth2-login-advanced-oauth2-user-service]]
=== OAuth 2.0 UserService

`DefaultReactiveOAuth2UserService` là một implementation của `ReactiveOAuth2UserService`, hỗ trợ các OAuth 2.0 Provider tiêu chuẩn.

[NOTE]
`ReactiveOAuth2UserService` lấy các user attribute của end-user (resource owner) từ UserInfo Endpoint (bằng access token được cấp cho client trong authorization flow) và trả về một `AuthenticatedPrincipal` dưới dạng `OAuth2User`.

`DefaultReactiveOAuth2UserService` sử dụng `WebClient` khi request các user attribute tại UserInfo Endpoint.

Nếu cần tùy chỉnh pre-processing của UserInfo Request và/hoặc post-handling của UserInfo Response, bạn cần cung cấp cho `DefaultReactiveOAuth2UserService.setWebClient()` một `WebClient` đã được cấu hình tùy chỉnh.

Dù tùy chỉnh `DefaultReactiveOAuth2UserService` hay cung cấp implementation riêng của `ReactiveOAuth2UserService`, bạn cần cấu hình nó như trong ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			...
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveOAuth2UserService<OAuth2UserRequest, OAuth2User> oauth2UserService() {
		...
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Login { }
        }

        return http.build()
    }

    @Bean
    fun oauth2UserService(): ReactiveOAuth2UserService<OAuth2UserRequest, OAuth2User> {
        // ...
    }
}
----
======


[[webflux-oauth2-login-advanced-oidc-user-service]]
=== OpenID Connect 1.0 UserService

`OidcReactiveOAuth2UserService` là một implementation của `ReactiveOAuth2UserService`, hỗ trợ các OpenID Connect 1.0 Provider.

`OidcReactiveOAuth2UserService` sử dụng `DefaultReactiveOAuth2UserService` khi request các user attribute tại UserInfo Endpoint.

Nếu cần tùy chỉnh pre-processing của UserInfo Request và/hoặc post-handling của UserInfo Response, bạn cần cung cấp cho `OidcReactiveOAuth2UserService.setOauth2UserService()` một `ReactiveOAuth2UserService` đã được cấu hình tùy chỉnh.

Dù tùy chỉnh `OidcReactiveOAuth2UserService` hay cung cấp implementation riêng của `ReactiveOAuth2UserService` cho OpenID Connect 1.0 Provider, bạn cần cấu hình nó như trong ví dụ sau:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			...
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveOAuth2UserService<OidcUserRequest, OidcUser> oidcUserService() {
		...
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            oauth2Login { }
        }

        return http.build()
    }

    @Bean
    fun oidcUserService(): ReactiveOAuth2UserService<OidcUserRequest, OidcUser> {
        // ...
    }
}
----
======


[[webflux-oauth2-login-advanced-idtoken-verify]]
== Xác minh chữ ký ID Token

OpenID Connect 1.0 Authentication giới thiệu https://openid.net/specs/openid-connect-core-1_0.html#IDToken[ID Token], một security token chứa các Claim về Authentication của End-User do Authorization Server cung cấp khi được Client sử dụng.

ID Token được biểu diễn dưới dạng https://tools.ietf.org/html/rfc7519[JSON Web Token] (JWT) và MUST được ký bằng https://tools.ietf.org/html/rfc7515[JSON Web Signature] (JWS).

`ReactiveOidcIdTokenDecoderFactory` cung cấp một `ReactiveJwtDecoder` được sử dụng để xác minh chữ ký `OidcIdToken`. Algorithm mặc định là `RS256` nhưng có thể khác khi được chỉ định trong quá trình đăng ký client.
Trong các trường hợp này, có thể cấu hình một resolver để trả về JWS algorithm dự kiến được chỉ định cho một client cụ thể.

JWS algorithm resolver là một `Function` nhận `ClientRegistration` và trả về `JwsAlgorithm` dự kiến cho client, chẳng hạn `SignatureAlgorithm.RS256` hoặc `MacAlgorithm.HS256`.

Đoạn code sau cho thấy cách cấu hình `@Bean` `OidcIdTokenDecoderFactory` để mặc định dùng `MacAlgorithm.HS256` cho mọi `ClientRegistration`:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoderFactory<ClientRegistration> idTokenDecoderFactory() {
	ReactiveOidcIdTokenDecoderFactory idTokenDecoderFactory = new ReactiveOidcIdTokenDecoderFactory();
	idTokenDecoderFactory.setJwsAlgorithmResolver((clientRegistration) -> clientRegistration.HS256);
	return idTokenDecoderFactory;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun idTokenDecoderFactory(): ReactiveJwtDecoderFactory<ClientRegistration> {
    val idTokenDecoderFactory = ReactiveOidcIdTokenDecoderFactory()
    idTokenDecoderFactory.setJwsAlgorithmResolver { MacAlgorithm.HS256 }
    return idTokenDecoderFactory
}
----
======

[NOTE]
Đối với các algorithm dựa trên MAC như `HS256`, `HS384` hoặc `HS512`, `client-secret` tương ứng với `client-id` được sử dụng làm symmetric key để xác minh chữ ký.

[TIP]
Nếu có nhiều hơn một `ClientRegistration` được cấu hình cho OpenID Connect 1.0 Authentication, JWS algorithm resolver có thể đánh giá `ClientRegistration` được cung cấp để xác định algorithm nào cần trả về.

[[webflux-oauth2-login-advanced-oidc-logout]]
Sau đó, bạn có thể tiếp tục cấu hình xref:reactive/oauth2/login/logout.adoc[logout].
