= Cấu hình cốt lõi

[[webflux-oauth2-login-sample]]
== Ví dụ Spring Boot

Spring Boot cung cấp đầy đủ khả năng auto-configuration cho OAuth 2.0 Login.

Phần này trình bày cách cấu hình {gh-samples-url}/boot/oauth2login-webflux[*ví dụ OAuth 2.0 Login WebFlux*] bằng cách sử dụng _Google_ làm _Authentication Provider_ và bao quát các chủ đề sau:

* <<webflux-oauth2-login-sample-setup>>
* <<webflux-oauth2-login-sample-redirect>>
* <<webflux-oauth2-login-sample-config>>
* <<webflux-oauth2-login-sample-start>>


[[webflux-oauth2-login-sample-setup]]
=== Thiết lập ban đầu

Để sử dụng hệ thống authentication OAuth 2.0 của Google cho việc đăng nhập, bạn phải thiết lập một dự án trong Google API Console để lấy credential OAuth 2.0.

[NOTE]
====
https://developers.google.com/identity/protocols/OpenIDConnect[Triển khai OAuth 2.0 của Google] cho authentication tuân thủ đặc tả https://openid.net/connect/[OpenID Connect 1.0] và được https://openid.net/certification/[chứng nhận OpenID].
====

Làm theo hướng dẫn trên trang https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect], bắt đầu từ phần "`Thiết lập OAuth 2.0`".

Sau khi hoàn tất hướng dẫn "`Lấy credential OAuth 2.0`", bạn sẽ có một OAuth Client mới với credential gồm Client ID và Client Secret.


[[webflux-oauth2-login-sample-redirect]]
=== Thiết lập redirect URI

redirect URI là path trong application mà user-agent của người dùng cuối được chuyển hướng trở lại sau khi họ đã authentication với Google và cấp quyền truy cập cho OAuth Client (<<webflux-oauth2-login-sample-setup,được tạo ở bước trước>>) trên trang Consent.

Trong phần "`Thiết lập redirect URI`", đảm bảo trường *Authorized redirect URIs* được đặt thành `http://localhost:8080/login/oauth2/code/google`.

[TIP]
====
Mẫu redirect URI mặc định là `+{baseUrl}/login/oauth2/code/{registrationId}+`.
*_registrationId_* là identifier duy nhất cho xref:reactive/oauth2/client/core.adoc#oauth2Client-client-registration[ClientRegistration].
Trong ví dụ này, `registrationId` là `google`.
====

[IMPORTANT]
====
Nếu OAuth Client chạy phía sau một proxy server, bạn nên kiểm tra xref:features/exploits/http.adoc#http-proxy-server[Cấu hình máy chủ proxy] để đảm bảo application được cấu hình đúng.
Ngoài ra, xem các xref:reactive/oauth2/client/authorization-grants.adoc#oauth2Client-auth-code-redirect-uri[biến template `URI`] được hỗ trợ cho `redirect-uri`.
====

[[webflux-oauth2-login-sample-config]]
=== Cấu hình `application.yml`

Bây giờ bạn đã có OAuth Client mới với Google, bạn cần cấu hình application để sử dụng OAuth Client cho _authentication flow_.
Để thực hiện việc đó:

. Đi đến `application.yml` và đặt cấu hình sau:
+
.Thuộc tính OAuth Client
====
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----

<1> `spring.security.oauth2.client.registration` là tiền tố thuộc tính cơ sở cho các thuộc tính OAuth Client.
<2> Sau tiền tố thuộc tính cơ sở là ID của xref:reactive/oauth2/client/core.adoc#oauth2Client-client-registration[`ClientRegistration`], chẳng hạn như google.
====

. Thay thế các giá trị trong thuộc tính `client-id` và `client-secret` bằng credential OAuth 2.0 bạn đã tạo trước đó.


[[webflux-oauth2-login-sample-start]]
=== Khởi động ứng dụng

Khởi chạy ví dụ Spring Boot và truy cập `http://localhost:8080`.
Sau đó, bạn được chuyển hướng đến trang login _auto-generated_ mặc định, trang này hiển thị một liên kết tới Google.

Nhấp vào liên kết Google, sau đó bạn được chuyển hướng đến Google để authentication.

Sau khi authentication bằng credential tài khoản Google, bạn sẽ thấy màn hình Consent.
Màn hình Consent yêu cầu bạn cho phép hoặc từ chối quyền truy cập của OAuth Client đã tạo trước đó.
Nhấp *Allow* để ủy quyền cho OAuth Client truy cập địa chỉ email và thông tin profile cơ bản của bạn.

Tại thời điểm này, OAuth Client truy xuất địa chỉ email và thông tin profile cơ bản của bạn từ https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] và thiết lập một session đã authentication.


[[oauth2login-boot-property-mappings]]
== Ánh xạ thuộc tính Spring Boot

Bảng sau phác thảo ánh xạ các thuộc tính OAuth Client của Spring Boot tới các thuộc tính xref:reactive/oauth2/client/core.adoc#oauth2Client-client-registration[ClientRegistration].

|===
|Spring Boot |ClientRegistration

|`spring.security.oauth2.client.registration._[registrationId]_`
|`registrationId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-id`
|`clientId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-secret`
|`clientSecret`

|`spring.security.oauth2.client.registration._[registrationId]_.client-authentication-method`
|`clientAuthenticationMethod`

|`spring.security.oauth2.client.registration._[registrationId]_.authorization-grant-type`
|`authorizationGrantType`

|`spring.security.oauth2.client.registration._[registrationId]_.redirect-uri`
|`redirectUri`

|`spring.security.oauth2.client.registration._[registrationId]_.scope`
|`scopes`

|`spring.security.oauth2.client.registration._[registrationId]_.client-name`
|`clientName`

|`spring.security.oauth2.client.provider._[providerId]_.authorization-uri`
|`providerDetails.authorizationUri`

|`spring.security.oauth2.client.provider._[providerId]_.token-uri`
|`providerDetails.tokenUri`

|`spring.security.oauth2.client.provider._[providerId]_.jwk-set-uri`
|`providerDetails.jwkSetUri`

|`spring.security.oauth2.client.provider._[providerId]_.issuer-uri`
|`providerDetails.issuerUri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-uri`
|`providerDetails.userInfoEndpoint.uri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-authentication-method`
|`providerDetails.userInfoEndpoint.authenticationMethod`

|`spring.security.oauth2.client.provider._[providerId]_.user-name-attribute`
|`providerDetails.userInfoEndpoint.userNameAttributeName`
|===

[TIP]
Bạn có thể cấu hình ban đầu một `ClientRegistration` bằng cách sử dụng discovery của https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] của OpenID Connect Provider hoặc https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] của Authorization Server, bằng cách chỉ định thuộc tính `spring.security.oauth2.client.provider._[providerId]_.issuer-uri`.


[[webflux-oauth2-login-common-oauth2-provider]]
== CommonOAuth2Provider

`CommonOAuth2Provider` định nghĩa sẵn một tập các thuộc tính client mặc định cho một số provider phổ biến: Google, GitHub, Facebook, X và Okta.

Ví dụ, `authorization-uri`, `token-uri` và `user-info-uri` thường không thay đổi đối với một provider.
Vì vậy, cung cấp các giá trị mặc định là hợp lý, giúp giảm cấu hình cần thiết.

Như đã trình bày trước đó, khi chúng ta <<webflux-oauth2-login-sample-config,đã cấu hình một client Google>>, chỉ cần các thuộc tính `client-id` và `client-secret`.

Danh sách sau đây cho thấy một ví dụ:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
----

[TIP]
Việc tự động áp dụng giá trị mặc định cho các thuộc tính client hoạt động liền mạch ở đây vì `registrationId` (`google`) khớp với `enum` `GOOGLE` (không phân biệt hoa thường) trong `CommonOAuth2Provider`.

Trong trường hợp bạn muốn chỉ định một `registrationId` khác, chẳng hạn như `google-login`, bạn vẫn có thể tận dụng việc tự động áp dụng giá trị mặc định cho các thuộc tính client bằng cách cấu hình thuộc tính `provider`.

Danh sách sau đây cho thấy một ví dụ:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google-login:	<1>
            provider: google	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
<1> `registrationId` được đặt thành `google-login`.
<2> Thuộc tính `provider` được đặt thành `google`, thuộc tính này sẽ tận dụng việc tự động áp dụng giá trị mặc định cho các thuộc tính client được thiết lập trong `CommonOAuth2Provider.GOOGLE.getBuilder()`.


[[webflux-oauth2-login-custom-provider-properties]]
== Cấu hình thuộc tính Provider tùy chỉnh

Có một số Provider OAuth 2.0 hỗ trợ multi-tenancy, dẫn đến các endpoint protocol khác nhau cho mỗi tenant (hoặc sub-domain).

Ví dụ, một OAuth Client được đăng ký với Okta được gán cho một sub-domain cụ thể và có các endpoint protocol riêng.

Trong các trường hợp này, Spring Boot cung cấp thuộc tính cơ sở sau để cấu hình các thuộc tính provider tùy chỉnh: `spring.security.oauth2.client.provider._[providerId]_`.

Danh sách sau đây cho thấy một ví dụ:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          okta:	<1>
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
----

<1> Thuộc tính cơ sở (`spring.security.oauth2.client.provider.okta`) cho phép cấu hình tùy chỉnh các vị trí endpoint protocol.


[[webflux-oauth2-login-override-boot-autoconfig]]
== Ghi đè auto-configuration của Spring Boot

Class auto-configuration của Spring Boot cho hỗ trợ OAuth Client là `ReactiveOAuth2ClientAutoConfiguration`.

Nó thực hiện các tác vụ sau:

* Đăng ký một `ReactiveClientRegistrationRepository` `@Bean` được tạo từ các `ClientRegistration`(s) của các thuộc tính OAuth Client đã cấu hình.
* Đăng ký một `SecurityWebFilterChain` `@Bean` và bật OAuth 2.0 Login thông qua `serverHttpSecurity.oauth2Login()`.

Nếu cần ghi đè auto-configuration dựa trên các yêu cầu cụ thể, bạn có thể thực hiện theo các cách sau:

* <<webflux-oauth2-login-register-reactiveclientregistrationrepository-bean,Đăng ký một ReactiveClientRegistrationRepository @Bean>>
* <<webflux-oauth2-login-register-securitywebfilterchain-bean,Đăng ký một SecurityWebFilterChain @Bean>>
* <<webflux-oauth2-login-completely-override-autoconfiguration,Ghi đè hoàn toàn auto-configuration>>


[[webflux-oauth2-login-register-reactiveclientregistrationrepository-bean]]
=== Đăng ký `ReactiveClientRegistrationRepository` @Bean

Ví dụ sau đây cho thấy cách đăng ký một `ReactiveClientRegistrationRepository` `@Bean`:

[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
public class OAuth2LoginConfig {

	@Bean
	public ReactiveClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryReactiveClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
				.clientId("google-client-id")
				.clientSecret("google-client-secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
				.scope("openid", "profile", "email", "address", "phone")
				.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
				.tokenUri("https://www.googleapis.com/oauth2/v4/token")
				.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
				.userNameAttributeName(IdTokenClaimNames.SUB)
				.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
				.clientName("Google")
				.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
class OAuth2LoginConfig {

    @Bean
    fun clientRegistrationRepository(): ReactiveClientRegistrationRepository {
        return InMemoryReactiveClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
======


[[webflux-oauth2-login-register-securitywebfilterchain-bean]]
=== Đăng ký `SecurityWebFilterChain` @Bean

Ví dụ sau đây cho thấy cách đăng ký một `SecurityWebFilterChain` `@Bean` với `@EnableWebFluxSecurity` và bật OAuth 2.0 Login thông qua `serverHttpSecurity.oauth2Login()`:

.Cấu hình OAuth2 Login
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login(withDefaults());

		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login { }
        }

        return http.build()
    }
}
----
======


[[webflux-oauth2-login-completely-override-autoconfiguration]]
=== Ghi đè hoàn toàn auto-configuration

Ví dụ sau đây cho thấy cách ghi đè hoàn toàn auto-configuration bằng cách đăng ký một `ReactiveClientRegistrationRepository` `@Bean` và một `SecurityWebFilterChain` `@Bean`.

.Ghi đè auto-configuration
[tabs]
======
Java::
+
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryReactiveClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
				.clientId("google-client-id")
				.clientSecret("google-client-secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
				.scope("openid", "profile", "email", "address", "phone")
				.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
				.tokenUri("https://www.googleapis.com/oauth2/v4/token")
				.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
				.userNameAttributeName(IdTokenClaimNames.SUB)
				.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
				.clientName("Google")
				.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login { }
        }

        return http.build()
    }

    @Bean
    fun clientRegistrationRepository(): ReactiveClientRegistrationRepository {
        return InMemoryReactiveClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
======


[[webflux-oauth2-login-javaconfig-wo-boot]]
== Cấu hình Java không có Spring Boot

Nếu bạn không thể sử dụng Spring Boot và muốn cấu hình một trong các provider được định nghĩa sẵn trong `CommonOAuth2Provider` (ví dụ Google), hãy áp dụng cấu hình sau:

.Cấu hình OAuth2 Login
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebFluxSecurity
public class OAuth2LoginConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange((authorize) -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryReactiveClientRegistrationRepository(this.googleClientRegistration());
	}

	@Bean
	public ReactiveOAuth2AuthorizedClientService authorizedClientService(
			ReactiveClientRegistrationRepository clientRegistrationRepository) {
		return new InMemoryReactiveOAuth2AuthorizedClientService(clientRegistrationRepository);
	}

	@Bean
	public ServerOAuth2AuthorizedClientRepository authorizedClientRepository(
			ReactiveOAuth2AuthorizedClientService authorizedClientService) {
		return new AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository(authorizedClientService);
	}

	private ClientRegistration googleClientRegistration() {
		return CommonOAuth2Provider.GOOGLE.getBuilder("google")
				.clientId("google-client-id")
				.clientSecret("google-client-secret")
				.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebFluxSecurity
class OAuth2LoginConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login { }
        }

        return http.build()
    }

    @Bean
    fun clientRegistrationRepository(): ReactiveClientRegistrationRepository {
        return InMemoryReactiveClientRegistrationRepository(googleClientRegistration())
    }

    @Bean
    fun authorizedClientService(
        clientRegistrationRepository: ReactiveClientRegistrationRepository
    ): ReactiveOAuth2AuthorizedClientService {
        return InMemoryReactiveOAuth2AuthorizedClientService(clientRegistrationRepository)
    }

    @Bean
    fun authorizedClientRepository(
        authorizedClientService: ReactiveOAuth2AuthorizedClientService
    ): ServerOAuth2AuthorizedClientRepository {
        return AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository(authorizedClientService)
    }

    private fun googleClientRegistration(): ClientRegistration {
        return CommonOAuth2Provider.GOOGLE.getBuilder("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .build()
    }
}
----
======
