[[reactive-concurrent-sessions-control]]
= Kiểm soát session đồng thời

Tương tự như xref:servlet/authentication/session-management.adoc#ns-concurrent-sessions[Kiểm soát session đồng thời của Servlet], Spring Security cũng hỗ trợ giới hạn số session đồng thời mà một người dùng có thể có trong một ứng dụng Reactive.

Khi thiết lập Kiểm soát session đồng thời trong Spring Security, tính năng này theo dõi các authentication được thực hiện thông qua Form Login, xref:reactive/oauth2/login/index.adoc[Đăng nhập OAuth 2.0] và HTTP Basic authentication bằng cách móc vào cách các cơ chế authentication đó xử lý việc authentication thành công.
Cụ thể hơn, DSL quản lý session sẽ thêm javadoc:org.springframework.security.web.server.authentication.ConcurrentSessionControlServerAuthenticationSuccessHandler[] và javadoc:org.springframework.security.web.server.authentication.RegisterSessionServerAuthenticationSuccessHandler[] vào danh sách `ServerAuthenticationSuccessHandler` được authentication filter sử dụng.

Các phần sau chứa những ví dụ về cách cấu hình Kiểm soát session đồng thời.

* <<reactive-concurrent-sessions-control-limit,Tôi muốn giới hạn số session đồng thời mà một người dùng có thể có>>
* <<concurrent-sessions-control-custom-strategy,Tôi muốn tùy chỉnh strategy được sử dụng khi vượt quá số session tối đa>>
* <<reactive-concurrent-sessions-control-specify-session-registry,Tôi muốn biết cách chỉ định một `ReactiveSessionRegistry`>>
* <<concurrent-sessions-control-sample,Tôi muốn xem một ứng dụng mẫu sử dụng Kiểm soát session đồng thời>>
* <<disabling-for-authentication-filters,Tôi muốn biết cách vô hiệu hóa tính năng này cho một authentication filter>>

[[reactive-concurrent-sessions-control-limit]]
== Giới hạn session đồng thời

Theo mặc định, Spring Security cho phép một người dùng có số session đồng thời bất kỳ.
Để giới hạn số session đồng thời, bạn có thể sử dụng DSL method `maximumSessions`:

.Cấu hình một session cho mọi người dùng
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
            )
        );
    return http.build();
}

@Bean
ReactiveSessionRegistry reactiveSessionRegistry() {
    return new InMemoryReactiveSessionRegistry();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        sessionManagement {
            sessionConcurrency {
                maximumSessions = SessionLimit.of(1)
            }
        }
    }
}
@Bean
open fun reactiveSessionRegistry(): ReactiveSessionRegistry {
    return InMemoryReactiveSessionRegistry()
}
----
======

Cấu hình trên cho phép mỗi người dùng có một session.
Tương tự, bạn cũng có thể cho phép số session không giới hạn bằng cách sử dụng constant `SessionLimit#UNLIMITED`:

.Cấu hình session không giới hạn
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.UNLIMITED))
        );
    return http.build();
}

@Bean
ReactiveSessionRegistry reactiveSessionRegistry() {
    return new InMemoryReactiveSessionRegistry();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        sessionManagement {
            sessionConcurrency {
                maximumSessions = SessionLimit.UNLIMITED
            }
        }
    }
}
@Bean
open fun reactiveSessionRegistry(webSessionManager: WebSessionManager): ReactiveSessionRegistry {
    return InMemoryReactiveSessionRegistry()
}
----
======

Vì method `maximumSessions` chấp nhận interface `SessionLimit`, mà interface này mở rộng `Function<Authentication, Mono<Integer>>`, bạn có thể sử dụng logic phức tạp hơn để xác định số session tối đa dựa trên authentication của người dùng:

.Cấu hình maximumSessions dựa trên `Authentication`
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(maxSessions()))
        );
    return http.build();
}

private SessionLimit maxSessions() {
    return (authentication) -> {
        if (authentication.getAuthorities().contains(new SimpleGrantedAuthority("ROLE_UNLIMITED_SESSIONS"))) {
            return Mono.empty(); // allow unlimited sessions for users with ROLE_UNLIMITED_SESSIONS
        }
        if (authentication.getAuthorities().contains(new SimpleGrantedAuthority("ROLE_ADMIN"))) {
            return Mono.just(2); // allow two sessions for admins
        }
        return Mono.just(1); // allow one session for every other user
    };
}

@Bean
ReactiveSessionRegistry reactiveSessionRegistry() {
    return new InMemoryReactiveSessionRegistry();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        sessionManagement {
            sessionConcurrency {
                maximumSessions = maxSessions()
            }
        }
    }
}

fun maxSessions(): SessionLimit {
    return { authentication ->
        if (authentication.authorities.contains(SimpleGrantedAuthority("ROLE_UNLIMITED_SESSIONS"))) Mono.empty
        if (authentication.authorities.contains(SimpleGrantedAuthority("ROLE_ADMIN"))) Mono.just(2)
        Mono.just(1)
    }
}

@Bean
open fun reactiveSessionRegistry(): ReactiveSessionRegistry {
    return InMemoryReactiveSessionRegistry()
}
----
======

Khi vượt quá số session tối đa, theo mặc định, các session ít được sử dụng gần đây nhất sẽ hết hạn.
Nếu muốn thay đổi hành vi đó, bạn có thể <<concurrent-sessions-control-custom-strategy,tùy chỉnh strategy được sử dụng khi vượt quá số session tối đa>>.

[IMPORTANT]
====
Concurrent Session Management không biết liệu có một session khác trong một Identity Provider nào đó mà bạn có thể sử dụng, chẳng hạn thông qua xref:reactive/oauth2/login/index.adoc[OAuth 2 Login].
Nếu cũng cần invalidate session trên Identity Provider, bạn phải <<concurrent-sessions-control-custom-strategy,đưa vào implementation riêng của mình cho `ServerMaximumSessionsExceededHandler`>>.
====

[[concurrent-sessions-control-custom-strategy]]
== Xử lý khi vượt quá số session tối đa

Theo mặc định, khi vượt quá số session tối đa, các session ít được sử dụng gần đây nhất sẽ hết hạn bằng cách sử dụng javadoc:org.springframework.security.web.server.authentication.InvalidateLeastUsedServerMaximumSessionsExceededHandler[].
Spring Security cũng cung cấp một implementation khác để ngăn người dùng tạo session mới bằng cách sử dụng javadoc:org.springframework.security.web.server.authentication.PreventLoginServerMaximumSessionsExceededHandler[].
Nếu muốn sử dụng strategy riêng, bạn có thể cung cấp một implementation khác của javadoc:org.springframework.security.web.server.authentication.ServerMaximumSessionsExceededHandler[].

.Cấu hình maximumSessionsExceededHandler
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
                .maximumSessionsExceededHandler(new PreventLoginMaximumSessionsExceededHandler())
            )
        );
    return http.build();
}

@Bean
ReactiveSessionRegistry reactiveSessionRegistry() {
    return new InMemoryReactiveSessionRegistry();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        sessionManagement {
            sessionConcurrency {
                maximumSessions = SessionLimit.of(1)
                maximumSessionsExceededHandler = PreventLoginMaximumSessionsExceededHandler()
            }
        }
    }
}

@Bean
open fun reactiveSessionRegistry(): ReactiveSessionRegistry {
    return InMemoryReactiveSessionRegistry()
}
----
======

[[reactive-concurrent-sessions-control-specify-session-registry]]
== Chỉ định một `ReactiveSessionRegistry`

Để theo dõi các session của người dùng, Spring Security sử dụng javadoc:org.springframework.security.core.session.ReactiveSessionRegistry[], và mỗi khi người dùng đăng nhập, thông tin session của họ sẽ được lưu lại.

Spring Security cung cấp implementation javadoc:org.springframework.security.core.session.InMemoryReactiveSessionRegistry[] của `ReactiveSessionRegistry`.

Để chỉ định một implementation của `ReactiveSessionRegistry`, bạn có thể khai báo nó dưới dạng bean:

.ReactiveSessionRegistry dưới dạng Bean
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
            )
        );
    return http.build();
}

@Bean
ReactiveSessionRegistry reactiveSessionRegistry() {
    return new MyReactiveSessionRegistry();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        sessionManagement {
            sessionConcurrency {
                maximumSessions = SessionLimit.of(1)
            }
        }
    }
}

@Bean
open fun reactiveSessionRegistry(): ReactiveSessionRegistry {
    return MyReactiveSessionRegistry()
}
----
======

hoặc bạn có thể sử dụng DSL method `sessionRegistry`:

.ReactiveSessionRegistry sử dụng DSL method sessionRegistry
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
                .sessionRegistry(new MyReactiveSessionRegistry())
            )
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        sessionManagement {
            sessionConcurrency {
                maximumSessions = SessionLimit.of(1)
                sessionRegistry = MyReactiveSessionRegistry()
            }
        }
    }
}
----
======

[[reactive-concurrent-sessions-control-manually-invalidating-sessions]]
== Invalidate session của người dùng đã đăng ký

Đôi khi, việc có thể invalidate tất cả hoặc một số session của người dùng sẽ rất hữu ích.
Ví dụ, khi người dùng thay đổi password, bạn có thể muốn invalidate tất cả session của họ để buộc họ đăng nhập lại.
Để thực hiện việc đó, bạn có thể sử dụng bean `ReactiveSessionRegistry` để lấy tất cả session của người dùng, invalidate chúng, rồi xóa chúng khỏi `WebSessionStore`:

.Sử dụng ReactiveSessionRegistry để invalidate session thủ công
[tabs]
======
Java::
+
[source,java,role="primary"]
----
public class SessionControl {
    private final ReactiveSessionRegistry reactiveSessionRegistry;

    private final WebSessionStore webSessionStore;

    public Mono<Void> invalidateSessions(String username) {
        return this.reactiveSessionRegistry.getAllSessions(username)
            .flatMap((session) -> session.invalidate().thenReturn(session))
            .flatMap((session) -> this.webSessionStore.removeSession(session.getSessionId()))
            .then();
    }
}
----
======

[[disabling-for-authentication-filters]]
== Vô hiệu hóa tính năng này cho một số authentication filter

Theo mặc định, Kiểm soát session đồng thời sẽ được tự động cấu hình cho Form Login, OAuth 2.0 Login và HTTP Basic authentication miễn là chúng không tự chỉ định một `ServerAuthenticationSuccessHandler`.
Ví dụ, cấu hình sau sẽ vô hiệu hóa Kiểm soát session đồng thời cho Form Login:

.Vô hiệu hóa Kiểm soát session đồng thời cho Form Login
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .formLogin((login) -> login
            .authenticationSuccessHandler(new RedirectServerAuthenticationSuccessHandler("/"))
        )
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
            )
        );
    return http.build();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
open fun springSecurity(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        // ...
        formLogin {
            authenticationSuccessHandler = RedirectServerAuthenticationSuccessHandler("/")
        }
        sessionManagement {
            sessionConcurrency {
                maximumSessions = SessionLimit.of(1)
            }
        }
    }
}
----
======

=== Thêm success handler bổ sung mà không vô hiệu hóa Kiểm soát session đồng thời

Bạn cũng có thể thêm các instance `ServerAuthenticationSuccessHandler` bổ sung vào danh sách handler được authentication filter sử dụng mà không vô hiệu hóa Kiểm soát session đồng thời.
Để thực hiện việc đó, bạn có thể sử dụng method `authenticationSuccessHandler(Consumer<List<ServerAuthenticationSuccessHandler>>)`:

.Thêm handler bổ sung
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .formLogin((login) -> login
            .authenticationSuccessHandler((handlers) -> handlers.add(new MyAuthenticationSuccessHandler()))
        )
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
            )
        );
    return http.build();
}
----
======

[[concurrent-sessions-control-sample]]
== Kiểm tra ứng dụng mẫu

Bạn có thể xem {gh-samples-url}/reactive/webflux/java/session-management/maximum-sessions[ứng dụng mẫu tại đây].
