[[one-time-token-login]]
= Đăng nhập bằng One-Time Token

Spring Security hỗ trợ authentication bằng One-Time Token (OTT) thông qua DSL `oneTimeTokenLogin()`.
Trước khi đi vào chi tiết triển khai, cần làm rõ phạm vi của tính năng OTT trong framework, bao gồm những gì được hỗ trợ và những gì không được hỗ trợ.

== Tìm hiểu sự khác nhau giữa One-Time Token và One-Time Password

One-Time Token (OTT) thường bị nhầm với https://en.wikipedia.org/wiki/One-time_password[One-Time Password] (OTP), nhưng trong Spring Security, hai concept này khác nhau ở một số điểm quan trọng.
Để rõ ràng, trong tài liệu này, OTP được hiểu là https://en.wikipedia.org/wiki/Time-based_one-time_password[TOTP] (Time-Based One-Time Password) hoặc https://en.wikipedia.org/wiki/HMAC-based_one-time_password[HOTP] (HMAC-Based One-Time Password).

=== Yêu cầu setup

- OTT: Không yêu cầu setup ban đầu. User không cần cấu hình trước bất kỳ thứ gì.
- OTP: Thường yêu cầu setup, chẳng hạn như generate và chia sẻ secret key với một external tool để tạo one-time password.

=== Gửi token

- OTT: Thông thường cần implement một javadoc:org.springframework.security.web.server.authentication.ott.ServerOneTimeTokenGenerationSuccessHandler[] custom, chịu trách nhiệm deliver token đến end user.
- OTP: Token thường được generate bởi một external tool, vì vậy application không cần gửi token đến user.

=== Generate token

- OTT: Method javadoc:org.springframework.security.authentication.ott.reactive.ReactiveOneTimeTokenService#generate(org.springframework.security.authentication.ott.GenerateOneTimeTokenRequest)[] yêu cầu trả về một javadoc:org.springframework.security.authentication.ott.OneTimeToken[] được wrap trong Mono, nhấn mạnh việc generate ở server-side.
- OTP: Token không nhất thiết được generate ở server-side; token thường được client tạo bằng shared secret.

Tóm lại, One-Time Token (OTT) cung cấp cách authenticate user mà không cần setup account bổ sung, khác với One-Time Password (OTP), vốn thường yêu cầu quy trình setup phức tạp hơn và phụ thuộc vào external tool để generate token.

One-Time Token Login hoạt động theo hai bước chính.

1. User yêu cầu token bằng cách submit user identifier, thường là username, và token được deliver đến user, thường dưới dạng Magic Link, qua e-mail, SMS, v.v.
2. User submit token đến one-time token login endpoint; nếu token hợp lệ, user sẽ được login.

Các section sau sẽ trình bày cách cấu hình OTT Login theo nhu cầu của bạn.

- <<default-pages,Tìm hiểu integration với login page được generate mặc định>>
- <<sending-token-to-user,Gửi token đến user>>
- <<changing-submit-page-url,Cấu hình submit page của One-Time Token>>
- <<changing-generate-url,Thay đổi URL generate One-Time Token>>
- <<customize-generate-consume-token,Tùy chỉnh cách generate và consume token>>
- <<validating-account-status,Validate account status>>

[[default-pages]]
== Login page mặc định và submit page One-Time Token mặc định

DSL `oneTimeTokenLogin()` có thể được sử dụng cùng với `formLogin()`, tạo thêm One-Time Token Request Form trong xref:servlet/authentication/passwords/form.adoc[login page được generate mặc định].
DSL này cũng setup javadoc:org.springframework.security.web.server.ui.OneTimeTokenSubmitPageGeneratingWebFilter[] để generate submit page One-Time Token mặc định.

[[sending-token-to-user]]
== Gửi token đến user

Spring Security không thể xác định một cách hợp lý token nên được deliver đến user của bạn như thế nào.
Do đó, cần cung cấp một javadoc:org.springframework.security.web.server.authentication.ott.ServerOneTimeTokenGenerationSuccessHandler[] custom để deliver token đến user theo nhu cầu của bạn.
Một trong những strategy deliver phổ biến nhất là Magic Link, qua e-mail, SMS, v.v.
Trong ví dụ sau, chúng ta sẽ tạo một magic link và gửi link đó đến email của user.

include-code::./SecurityConfig[tag=config,indent=0]
include-code::./MagicLinkOneTimeTokenGenerationSuccessHandler[tag=snippet,indent=0]
<1> Đăng ký `MagicLinkOneTimeTokenGenerationSuccessHandler` dưới dạng Spring bean
<2> Tạo login processing URL với `token` làm query param
<3> Lấy email của user dựa trên username
<4> Dùng API `MailSender` để gửi email cùng magic link cho user
<5> Dùng `ServerOneTimeTokenGenerationSuccessHandler` để thực hiện redirect đến URL bạn muốn

Nội dung email sẽ có dạng tương tự:

> Dùng link sau để đăng nhập vào application: \http://localhost:8080/login/ott?token=a830c444-29d8-4d98-9b46-6aba7b22fe5b

Default submit page sẽ detect URL có query param `token` và tự động điền form field bằng giá trị token.

[[changing-generate-url]]
== Thay đổi URL generate One-Time Token

Mặc định, javadoc:org.springframework.security.web.server.authentication.ott.GenerateOneTimeTokenWebFilter[] lắng nghe các request `POST /ott/generate`.
Có thể thay đổi URL đó bằng DSL method `tokenGeneratingUrl(String)`:

include-code::./SecurityConfig[tag=config,indent=0]
include-code::./MagicLinkOneTimeTokenGenerationSuccessHandler[tag=snippet,indent=0]

[[changing-submit-page-url]]
== Thay đổi URL submit page mặc định

Submit page One-Time Token mặc định được generate bởi javadoc:org.springframework.security.web.server.ui.OneTimeTokenSubmitPageGeneratingWebFilter[] và lắng nghe `GET /login/ott`.
URL cũng có thể được thay đổi như sau:

include-code::./SecurityConfig[tag=config,indent=0]
include-code::./MagicLinkOneTimeTokenGenerationSuccessHandler[tag=snippet,indent=0]

[[disabling-default-submit-page]]
== Disable submit page mặc định

Nếu muốn sử dụng submit page One-Time Token riêng, bạn có thể disable default page rồi cung cấp endpoint riêng.

include-code::./SecurityConfig[tag=config,indent=0]
include-code::./MagicLinkOneTimeTokenGenerationSuccessHandler[tag=snippet,indent=0]
include-code::./MyController[tag=snippet,indent=0]

[[customize-generate-consume-token]]
== Tùy chỉnh cách generate và consume One-Time Token

Interface định nghĩa các operation chung để generate và consume one-time token là javadoc:org.springframework.security.authentication.ott.reactive.ReactiveOneTimeTokenService[].
Spring Security sử dụng javadoc:org.springframework.security.authentication.ott.reactive.InMemoryReactiveOneTimeTokenService[] làm implementation mặc định của interface đó nếu không có implementation nào được cung cấp.

Một số lý do phổ biến nhất để customize `ReactiveOneTimeTokenService` bao gồm, nhưng không giới hạn ở:

- Thay đổi thời gian expire của one-time token
- Lưu thêm thông tin từ generate token request
- Thay đổi cách tạo giá trị token
- Bổ sung validation khi consume one-time token

Có hai option để customize `ReactiveOneTimeTokenService`.
Một option là cung cấp service này dưới dạng bean để DSL `oneTimeTokenLogin()` có thể tự động pick up:

include-code::./OneTimeTokenServiceBeanSecurityConfig[tag=config,indent=0]
include-code::./MagicLinkOneTimeTokenGenerationSuccessHandler[tag=snippet,indent=0]

Option thứ hai là truyền instance `ReactiveOneTimeTokenService` vào DSL. Cách này hữu ích khi có nhiều ``SecurityWebFilterChain`` và mỗi chain cần một ``ReactiveOneTimeTokenService`` khác nhau.

include-code::./OneTimeTokenServiceDSLSecurityConfig[tag=config,indent=0]
include-code::./MagicLinkOneTimeTokenGenerationSuccessHandler[tag=snippet,indent=0]

[[customize-generate-token-request]]
== Tùy chỉnh instance GenerateOneTimeTokenRequest
Có một số lý do khiến bạn muốn điều chỉnh một GenerateOneTimeTokenRequest. Ví dụ, bạn có thể muốn đặt expiresIn thành 10 phút, trong khi Spring Security mặc định đặt giá trị này thành 5 phút.

Bạn có thể customize các element của GenerateOneTimeTokenRequest bằng cách publish một ServerGenerateOneTimeTokenRequestResolver dưới dạng `@Bean`, như sau:

include-code::./SecurityConfig[tag=config,indent=0]

[[validating-account-status]]
== Validate account status

Theo mặc định, javadoc:org.springframework.security.authentication.ott.reactive.OneTimeTokenReactiveAuthenticationManager[] không validate status của account đã authenticated -- ví dụ account có bị locked, disabled hoặc expired hay không.
Điều này giữ cho behavior của manager nhất quán với các version trước của Spring Security; default này có thể thay đổi trong các version tương lai của Spring Security.

Nếu muốn `OneTimeTokenReactiveAuthenticationManager` reject authentication bằng One-Time Token đối với những account như vậy, hãy cung cấp cho nó một javadoc:org.springframework.security.core.userdetails.UserDetailsChecker[], chẳng hạn như javadoc:org.springframework.security.authentication.AccountStatusUserDetailsChecker[], cùng với `setUserDetailsChecker`:

include-code::./OneTimeTokenAccountStatusExample[tag=userDetailsChecker,indent=0]
