= Tích hợp HTTP Service Clients

Hỗ trợ OAuth của Spring Security có thể tích hợp với `RestClient` và `WebClient` {spring-framework-reference-url}integration/rest-clients.html#rest-http-service-client[HTTP Service Clients].


[[configuration]]
== Cấu hình
Sau cấu hình riêng cho xref:features/integrations/rest/http-service-client.adoc#configuration-restclient[RestClient] hoặc xref:features/integrations/rest/http-service-client.adoc#configuration-webclient[WebClient], việc sử dụng xref:features/integrations/rest/http-service-client.adoc[] chỉ yêu cầu thêm xref:features/integrations/rest/http-service-client.adoc#client-registration-id[`@ClientRegistrationId`] vào các method yêu cầu OAuth hoặc vào HTTP interface khai báo các method đó.

Vì sự hiện diện của xref:features/integrations/rest/http-service-client.adoc#client-registration-id[`@ClientRegistrationId`] xác định việc OAuth token có được phân giải hay không và được phân giải như thế nào, bạn có thể an toàn thêm hỗ trợ OAuth của Spring Security vào bất kỳ cấu hình nào.

[[configuration-restclient]]
=== Cấu hình RestClient

Hỗ trợ OAuth của Spring Security có thể tích hợp với {spring-framework-reference-url}integration/rest-clients.html#rest-http-service-client[HTTP Service Clients] được hỗ trợ bởi `RestClient`.
Bước đầu tiên là xref:servlet/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[tạo một Bean `OAuthAuthorizedClientManager`].

Tiếp theo, bạn phải cấu hình `HttpServiceProxyFactory` và `RestClient` để nhận biết xref:./http-service-client.adoc#client-registration-id[@ClientRegistrationId]
Để đơn giản hóa cấu hình này, hãy sử dụng javadoc:org.springframework.security.oauth2.client.web.client.support.OAuth2RestClientHttpServiceGroupConfigurer[].

include-code::./RestClientHttpInterfaceIntegrationConfiguration[tag=config,indent=0]

Cấu hình này:

- Thêm xref:features/integrations/rest/http-service-client.adoc#client-registration-id-processor[`ClientRegistrationIdProcessor`] vào {spring-framework-reference-url}integration/rest-clients.html#rest-http-service-client[`HttpServiceProxyFactory`]
- Thêm xref:servlet/oauth2/client/authorized-clients.adoc#oauth2-client-rest-client[`OAuth2ClientHttpRequestInterceptor`] vào `RestClient`

[[configuration-webclient]]
=== Cấu hình WebClient

Hỗ trợ OAuth của Spring Security có thể tích hợp với {spring-framework-reference-url}integration/rest-clients.html#rest-http-service-client[HTTP Service Clients] được hỗ trợ bởi `WebClient`.
Bước đầu tiên là xref:reactive/oauth2/client/core.adoc#oauth2Client-authorized-manager-provider[tạo một Bean `ReactiveOAuthAuthorizedClientManager`].

Tiếp theo, bạn phải cấu hình `HttpServiceProxyFactory` và `WebRestClient` để nhận biết xref:./http-service-client.adoc#client-registration-id[@ClientRegistrationId]
Để đơn giản hóa cấu hình này, hãy sử dụng javadoc:org.springframework.security.oauth2.client.web.reactive.function.client.support.OAuth2WebClientHttpServiceGroupConfigurer[].

include-code::./ServerWebClientHttpInterfaceIntegrationConfiguration[tag=config,indent=0]

Cấu hình này:

- Thêm xref:features/integrations/rest/http-service-client.adoc#client-registration-id-processor[`ClientRegistrationIdProcessor`] vào {spring-framework-reference-url}/integration/rest-clients.html#rest-http-service-client[`HttpServiceProxyFactory`]
- Thêm xref:reactive/oauth2/client/authorized-clients.adoc#oauth2-client-web-client[`ServerOAuth2AuthorizedClientExchangeFilterFunction`] vào `WebClient`


[[client-registration-id]]
== @ClientRegistrationId

Bạn có thể thêm javadoc:org.springframework.security.oauth2.client.annotation.ClientRegistrationId[] vào HTTP Service để chỉ định javadoc:org.springframework.security.oauth2.client.registration.ClientRegistration[] nào sẽ được sử dụng.

include-code::./UserService[tag=getAuthenticatedUser]

xref:features/integrations/rest/http-service-client.adoc#client-registration-id[`@ClientRegistrationId`] sẽ được xử lý bởi xref:features/integrations/rest/http-service-client.adoc#client-registration-id-processor[`ClientRegistrationIdProcessor`]

[[type]]
=== Khai báo ở cấp kiểu

`@ClientRegistrationId` cũng có thể được thêm ở cấp kiểu để tránh lặp lại khai báo trên từng method.

include-code::./UserService[tag=type]

[[client-registration-id-processor]]
== `ClientRegistrationIdProcessor`

xref:features/integrations/rest/http-service-client.adoc#configuration[Thành phần được cấu hình] javadoc:org.springframework.security.oauth2.client.web.client.ClientRegistrationIdProcessor[] sẽ:

- Tự động gọi javadoc:org.springframework.security.oauth2.client.web.ClientAttributes#clientRegistrationId(java.lang.String)[] cho mỗi xref:features/integrations/rest/http-service-client.adoc#client-registration-id[`@ClientRegistrationId`].
- Thao tác này thêm javadoc:org.springframework.security.oauth2.client.registration.ClientRegistration#getId()[] vào các thuộc tính

Sau đó, `id` được xử lý bởi:

- `OAuth2ClientHttpRequestInterceptor` cho xref:servlet/oauth2/client/authorized-clients.adoc#oauth2-client-rest-client[Tích hợp RestClient]
- xref:servlet/oauth2/client/authorized-clients.adoc#oauth2-client-web-client[`ServletOAuth2AuthorizedClientExchangeFilterFunction`] (môi trường Servlet) hoặc xref:servlet/oauth2/client/authorized-clients.adoc#oauth2-client-web-client[`ServerOAuth2AuthorizedClientExchangeFilterFunction`] (môi trường Reactive) cho `WebClient`.
