[[oauth2AuthorizationServer-configuration-model]]
= Mô hình cấu hình

[[oauth2AuthorizationServer-default-configuration]]
== Cấu hình mặc định

`OAuth2AuthorizationServerConfiguration` là một `@Configuration` cung cấp cấu hình mặc định tối thiểu cho một OAuth2 authorization server.

`OAuth2AuthorizationServerConfiguration` sử dụng xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-customizing-the-configuration[`OAuth2AuthorizationServerConfigurer`] để áp dụng cấu hình mặc định và đăng ký một `SecurityFilterChain` `@Bean` được tạo thành từ tất cả infrastructure component hỗ trợ một OAuth2 authorization server.

`SecurityFilterChain` `@Bean` của OAuth2 authorization server được cấu hình với các protocol endpoint mặc định sau:

* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-authorization-endpoint[OAuth2 Authorization endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-endpoint[OAuth2 Token endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-introspection-endpoint[OAuth2 Token Introspection endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-revocation-endpoint[OAuth2 Token Revocation endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-authorization-server-metadata-endpoint[OAuth2 Authorization Server Metadata endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-jwk-set-endpoint[JWK Set endpoint]

[NOTE]
JWK Set endpoint chỉ được cấu hình *nếu* một `JWKSource<SecurityContext>` `@Bean` được đăng ký.

[NOTE]
====
Các protocol endpoint sau bị disabled theo mặc định:

* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-device-authorization-endpoint[OAuth2 Device Authorization Endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-device-verification-endpoint[OAuth2 Device Verification Endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-client-registration-endpoint[OAuth2 Client Registration endpoint]
====

Ví dụ sau cho thấy cách dùng `OAuth2AuthorizationServerConfiguration` để áp dụng cấu hình mặc định tối thiểu:

[source,java]
----
@Configuration
@Import(OAuth2AuthorizationServerConfiguration.class)
public class AuthorizationServerConfig {

	@Bean
	public RegisteredClientRepository registeredClientRepository() {
		List<RegisteredClient> registrations = ...
		return new InMemoryRegisteredClientRepository(registrations);
	}

	@Bean
	public JWKSource<SecurityContext> jwkSource() {
		RSAKey rsaKey = ...
		JWKSet jwkSet = new JWKSet(rsaKey);
		return (jwkSelector, securityContext) -> jwkSelector.select(jwkSet);
	}

}
----

[IMPORTANT]
https://datatracker.ietf.org/doc/html/rfc6749#section-4.1[authorization_code grant] yêu cầu resource owner phải được authenticated. Vì vậy, một user authentication mechanism *phải* được cấu hình bổ sung bên cạnh cấu hình OAuth2 security mặc định.

https://openid.net/specs/openid-connect-core-1_0.html[OpenID Connect 1.0] bị disabled trong cấu hình mặc định. Ví dụ sau cho thấy cách enable OpenID Connect 1.0 bằng cách khởi tạo `OidcConfigurer`:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.oidc(Customizer.withDefaults())	// Initialize `OidcConfigurer`
		);
	return http.build();
}
----

Ngoài các protocol endpoint mặc định, `SecurityFilterChain` `@Bean` của OAuth2 authorization server được cấu hình với các OpenID Connect 1.0 protocol endpoint sau:

* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-provider-configuration-endpoint[OpenID Connect 1.0 Provider Configuration endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-logout-endpoint[OpenID Connect 1.0 Logout endpoint]
* xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-user-info-endpoint[OpenID Connect 1.0 UserInfo endpoint]

[NOTE]
xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-client-registration-endpoint[OpenID Connect 1.0 Client Registration endpoint] bị disabled theo mặc định.

[TIP]
`OAuth2AuthorizationServerConfiguration.jwtDecoder(JWKSource<SecurityContext>)` là một utility (`static`) method tiện dụng có thể dùng để đăng ký `JwtDecoder` `@Bean`, thành phần *REQUIRED* đối với xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-user-info-endpoint[OpenID Connect 1.0 UserInfo endpoint] và xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-client-registration-endpoint[OpenID Connect 1.0 Client Registration endpoint].

Ví dụ sau cho thấy cách đăng ký `JwtDecoder` `@Bean`:

[source,java]
----
@Bean
public JwtDecoder jwtDecoder(JWKSource<SecurityContext> jwkSource) {
	return OAuth2AuthorizationServerConfiguration.jwtDecoder(jwkSource);
}
----

Mục đích chính của `OAuth2AuthorizationServerConfiguration` là cung cấp một method tiện dụng để áp dụng cấu hình mặc định tối thiểu cho một OAuth2 authorization server. Tuy nhiên, trong hầu hết trường hợp, vẫn cần customize cấu hình.

[[oauth2AuthorizationServer-customizing-the-configuration]]
== Tùy chỉnh cấu hình

`OAuth2AuthorizationServerConfigurer` cung cấp khả năng customize đầy đủ security configuration cho một OAuth2 authorization server.
Nó cho phép bạn chỉ định các core component cần sử dụng, chẳng hạn như xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client-repository[`RegisteredClientRepository`], xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-authorization-service[`OAuth2AuthorizationService`], xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-generator[`OAuth2TokenGenerator`] và các component khác.
Ngoài ra, nó cho phép bạn customize request processing logic cho các protocol endpoint, chẳng hạn như xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-authorization-endpoint[authorization endpoint], xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-device-authorization-endpoint[device authorization endpoint], xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-device-verification-endpoint[device verification endpoint], xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-endpoint[token endpoint], xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-introspection-endpoint[token introspection endpoint] và các endpoint khác.

`OAuth2AuthorizationServerConfigurer` cung cấp các tùy chọn cấu hình sau:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.registeredClientRepository(registeredClientRepository)	<1>
				.authorizationService(authorizationService)	<2>
				.authorizationConsentService(authorizationConsentService)	<3>
				.authorizationServerSettings(authorizationServerSettings)	<4>
				.tokenGenerator(tokenGenerator)	<5>
				.clientAuthentication(clientAuthentication -> { })	<6>
				.authorizationEndpoint(authorizationEndpoint -> { })	<7>
				.pushedAuthorizationRequestEndpoint(pushedAuthorizationRequestEndpoint -> { })  <8>
				.deviceAuthorizationEndpoint(deviceAuthorizationEndpoint -> { })	<9>
				.deviceVerificationEndpoint(deviceVerificationEndpoint -> { })	<10>
				.tokenEndpoint(tokenEndpoint -> { })	<11>
				.tokenIntrospectionEndpoint(tokenIntrospectionEndpoint -> { })	<12>
				.tokenRevocationEndpoint(tokenRevocationEndpoint -> { })	<13>
				.clientRegistrationEndpoint(clientRegistrationEndpoint -> { })  <14>
				.authorizationServerMetadataEndpoint(authorizationServerMetadataEndpoint -> { })	<15>
				.oidc(oidc -> oidc
					.providerConfigurationEndpoint(providerConfigurationEndpoint -> { })	<16>
					.logoutEndpoint(logoutEndpoint -> { })	<17>
					.userInfoEndpoint(userInfoEndpoint -> { })	<18>
					.clientRegistrationEndpoint(clientRegistrationEndpoint -> { })	<19>
				)
		);

	return http.build();
}
----
<1> `registeredClientRepository()`: xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client-repository[`RegisteredClientRepository`] (*REQUIRED*) để quản lý client mới và hiện có.
<2> `authorizationService()`: xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-authorization-service[`OAuth2AuthorizationService`] để quản lý authorization mới và hiện có.
<3> `authorizationConsentService()`: xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-authorization-consent-service[`OAuth2AuthorizationConsentService`] để quản lý authorization consent mới và hiện có.
<4> `authorizationServerSettings()`: xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-configuring-authorization-server-settings[`AuthorizationServerSettings`] (*REQUIRED*) để tùy chỉnh các setting cấu hình cho OAuth2 authorization server.
<5> `tokenGenerator()`: xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-generator[`OAuth2TokenGenerator`] để tạo các token được OAuth2 authorization server hỗ trợ.
<6> `clientAuthentication()`: configurer cho xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-configuring-client-authentication[OAuth2 Client Authentication].
<7> `authorizationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-authorization-endpoint[OAuth2 Authorization endpoint].
<8> `pushedAuthorizationRequestEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-pushed-authorization-request-endpoint[OAuth2 Pushed Authorization Request endpoint].
<9> `deviceAuthorizationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-device-authorization-endpoint[OAuth2 Device Authorization endpoint].
<10> `deviceVerificationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-device-verification-endpoint[OAuth2 Device Verification endpoint].
<11> `tokenEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-endpoint[OAuth2 Token endpoint].
<12> `tokenIntrospectionEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-introspection-endpoint[OAuth2 Token Introspection endpoint].
<13> `tokenRevocationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-revocation-endpoint[OAuth2 Token Revocation endpoint].
<14> `clientRegistrationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-client-registration-endpoint[OAuth2 Client Registration endpoint].
<15> `authorizationServerMetadataEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-authorization-server-metadata-endpoint[OAuth2 Authorization Server Metadata endpoint].
<16> `providerConfigurationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-provider-configuration-endpoint[OpenID Connect 1.0 Provider Configuration endpoint].
<17> `logoutEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-logout-endpoint[OpenID Connect 1.0 Logout endpoint].
<18> `userInfoEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-user-info-endpoint[OpenID Connect 1.0 UserInfo endpoint].
<19> `clientRegistrationEndpoint()`: configurer cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-client-registration-endpoint[OpenID Connect 1.0 Client Registration endpoint].

[[oauth2AuthorizationServer-configuring-authorization-server-settings]]
== Cấu hình các setting của Authorization Server

`AuthorizationServerSettings` chứa các setting cấu hình cho OAuth2 authorization server.
Nó chỉ định `URI` cho các protocol endpoint cũng như https://datatracker.ietf.org/doc/html/rfc8414#section-2[issuer identifier].
`URI` mặc định cho các protocol endpoint như sau:

[source,java]
----
public final class AuthorizationServerSettings extends AbstractSettings {

	...

	public static Builder builder() {
		return new Builder()
			.authorizationEndpoint("/oauth2/authorize")
			.pushedAuthorizationRequestEndpoint("/oauth2/par")
			.deviceAuthorizationEndpoint("/oauth2/device_authorization")
			.deviceVerificationEndpoint("/oauth2/device_verification")
			.tokenEndpoint("/oauth2/token")
			.tokenIntrospectionEndpoint("/oauth2/introspect")
			.tokenRevocationEndpoint("/oauth2/revoke")
			.clientRegistrationEndpoint("/oauth2/register")
			.jwkSetEndpoint("/oauth2/jwks")
			.oidcLogoutEndpoint("/connect/logout")
			.oidcUserInfoEndpoint("/userinfo")
			.oidcClientRegistrationEndpoint("/connect/register");
	}

	...

}
----

[NOTE]
`AuthorizationServerSettings` là component *REQUIRED*.

[TIP]
xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-default-configuration[`@Import(OAuth2AuthorizationServerConfiguration.class)`] tự động đăng ký một `AuthorizationServerSettings` `@Bean` nếu chưa được cung cấp.

Ví dụ sau cho thấy cách tùy chỉnh các setting cấu hình và đăng ký một `AuthorizationServerSettings` `@Bean`:

[source,java]
----
@Bean
public AuthorizationServerSettings authorizationServerSettings() {
	return AuthorizationServerSettings.builder()
		.issuer("https://example.com")
		.authorizationEndpoint("/oauth2/v1/authorize")
		.pushedAuthorizationRequestEndpoint("/oauth2/v1/par")
		.deviceAuthorizationEndpoint("/oauth2/v1/device_authorization")
		.deviceVerificationEndpoint("/oauth2/v1/device_verification")
		.tokenEndpoint("/oauth2/v1/token")
		.tokenIntrospectionEndpoint("/oauth2/v1/introspect")
		.tokenRevocationEndpoint("/oauth2/v1/revoke")
		.clientRegistrationEndpoint("/oauth2/v1/register")
		.jwkSetEndpoint("/oauth2/v1/jwks")
		.oidcLogoutEndpoint("/connect/v1/logout")
		.oidcUserInfoEndpoint("/connect/v1/userinfo")
		.oidcClientRegistrationEndpoint("/connect/v1/register")
		.build();
}
----

`AuthorizationServerContext` là một context object chứa thông tin về runtime environment của Authorization Server.
Nó cung cấp quyền truy cập tới `AuthorizationServerSettings` và issuer identifier "`current`".

[NOTE]
Nếu issuer identifier không được cấu hình trong `AuthorizationServerSettings.builder().issuer(String)`, nó sẽ được resolve từ request hiện tại.

[NOTE]
Có thể truy cập `AuthorizationServerContext` thông qua `AuthorizationServerContextHolder`, đối tượng liên kết nó với thread của request hiện tại bằng `ThreadLocal`.

[[oauth2AuthorizationServer-configuring-client-authentication]]
== Cấu hình Client Authentication

`OAuth2ClientAuthenticationConfigurer` cung cấp khả năng tùy chỉnh https://datatracker.ietf.org/doc/html/rfc6749#section-2.3[OAuth2 client authentication].
Nó định nghĩa các extension point cho phép bạn tùy chỉnh logic pre-processing, main processing và post-processing cho các client authentication request.

`OAuth2ClientAuthenticationConfigurer` cung cấp các tùy chọn cấu hình sau:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.clientAuthentication(clientAuthentication ->
					clientAuthentication
						.authenticationConverter(authenticationConverter)	<1>
						.authenticationConverters(authenticationConvertersConsumer)	<2>
						.authenticationProvider(authenticationProvider)	<3>
						.authenticationProviders(authenticationProvidersConsumer)	<4>
						.authenticationSuccessHandler(authenticationSuccessHandler)	<5>
						.errorResponseHandler(errorResponseHandler)	<6>
				)
		);

	return http.build();
}
----
<1> `authenticationConverter()`: Thêm một `AuthenticationConverter` (_pre-processor_) được sử dụng khi cố gắng trích xuất client credential từ `HttpServletRequest` thành một instance của `OAuth2ClientAuthenticationToken`.
<2> `authenticationConverters()`: Thiết lập một `Consumer` cung cấp quyền truy cập tới `List` mặc định và các ``AuthenticationConverter`` được thêm vào (tùy chọn), cho phép thêm, xóa hoặc tùy chỉnh một `AuthenticationConverter` cụ thể.
<3> `authenticationProvider()`: Thêm một `AuthenticationProvider` (_main processor_) được sử dụng để authenticate `OAuth2ClientAuthenticationToken`.
<4> `authenticationProviders()`: Thiết lập một `Consumer` cung cấp quyền truy cập tới `List` mặc định và các ``AuthenticationProvider`` được thêm vào (tùy chọn), cho phép thêm, xóa hoặc tùy chỉnh một `AuthenticationProvider` cụ thể.
<5> `authenticationSuccessHandler()`: `AuthenticationSuccessHandler` (_post-processor_) được sử dụng để xử lý client authentication thành công và gắn `OAuth2ClientAuthenticationToken` vào `SecurityContext`.
<6> `errorResponseHandler()`: `AuthenticationFailureHandler` (_post-processor_) được sử dụng để xử lý client authentication thất bại và trả về https://datatracker.ietf.org/doc/html/rfc6749#section-5.2[`OAuth2Error` response].

`OAuth2ClientAuthenticationConfigurer` cấu hình `OAuth2ClientAuthenticationFilter` và đăng ký nó với `SecurityFilterChain` `@Bean` của OAuth2 authorization server.
`OAuth2ClientAuthenticationFilter` là `Filter` xử lý các client authentication request.

Theo mặc định, client authentication là bắt buộc đối với xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-endpoint[OAuth2 Token endpoint], xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-introspection-endpoint[OAuth2 Token Introspection endpoint] và xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-token-revocation-endpoint[OAuth2 Token Revocation endpoint].
Các client authentication method được hỗ trợ là `client_secret_basic`, `client_secret_post`, `private_key_jwt`, `client_secret_jwt`, `tls_client_auth`, `self_signed_tls_client_auth` và `none` (public clients).

`OAuth2ClientAuthenticationFilter` được cấu hình với các giá trị mặc định sau:

* `*AuthenticationConverter*` -- Một `DelegatingAuthenticationConverter` gồm `JwtClientAssertionAuthenticationConverter`, `X509ClientCertificateAuthenticationConverter`, `ClientSecretBasicAuthenticationConverter`, `ClientSecretPostAuthenticationConverter` và `PublicClientAuthenticationConverter`.
* `*AuthenticationManager*` -- Một `AuthenticationManager` gồm `JwtClientAssertionAuthenticationProvider`, `X509ClientCertificateAuthenticationProvider`, `ClientSecretAuthenticationProvider` và `PublicClientAuthenticationProvider`.
* `*AuthenticationSuccessHandler*` -- Một implementation nội bộ dùng để gắn `OAuth2ClientAuthenticationToken` đã "`authenticated`" (`Authentication` hiện tại) vào `SecurityContext`.
* `*AuthenticationFailureHandler*` -- Một implementation nội bộ sử dụng `OAuth2Error` liên kết với `OAuth2AuthenticationException` để trả về OAuth2 error response.

[[oauth2AuthorizationServer-customizing-jwt-client-assertion-validation]]
=== Tùy chỉnh Jwt Client Assertion Validation

`JwtClientAssertionDecoderFactory.DEFAULT_JWT_VALIDATOR_FACTORY` là factory mặc định cung cấp một `OAuth2TokenValidator<Jwt>` cho `RegisteredClient` được chỉ định và được sử dụng để validate các claim `iss`, `sub`, `aud`, `exp` và `nbf` của Jwt client assertion.

`JwtClientAssertionDecoderFactory` cung cấp khả năng override việc validate Jwt client assertion mặc định bằng cách cung cấp một custom factory có kiểu `Function<RegisteredClient, OAuth2TokenValidator<Jwt>>` cho `setJwtValidatorFactory()`.

[NOTE]
`JwtClientAssertionDecoderFactory` là `JwtDecoderFactory` mặc định được `JwtClientAssertionAuthenticationProvider` sử dụng, cung cấp một `JwtDecoder` cho `RegisteredClient` được chỉ định và được dùng để authenticate một `Jwt` Bearer Token trong quá trình OAuth2 client authentication.

Một use case phổ biến khi customize `JwtClientAssertionDecoderFactory` là validate các claim bổ sung trong Jwt client assertion.

Ví dụ sau cho thấy cách cấu hình `JwtClientAssertionAuthenticationProvider` với một `JwtClientAssertionDecoderFactory` đã được customize để validate một claim bổ sung trong Jwt client assertion:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.clientAuthentication(clientAuthentication ->
					clientAuthentication
						.authenticationProviders(configureJwtClientAssertionValidator())
				)
		);

	return http.build();
}

private Consumer<List<AuthenticationProvider>> configureJwtClientAssertionValidator() {
	return (authenticationProviders) ->
		authenticationProviders.forEach((authenticationProvider) -> {
			if (authenticationProvider instanceof JwtClientAssertionAuthenticationProvider) {
				// Customize JwtClientAssertionDecoderFactory
				JwtClientAssertionDecoderFactory jwtDecoderFactory = new JwtClientAssertionDecoderFactory();
				Function<RegisteredClient, OAuth2TokenValidator<Jwt>> jwtValidatorFactory = (registeredClient) ->
					new DelegatingOAuth2TokenValidator<>(
						// Use default validators
						JwtClientAssertionDecoderFactory.DEFAULT_JWT_VALIDATOR_FACTORY.apply(registeredClient),
						// Add custom validator
						new JwtClaimValidator<>("claim", "value"::equals));
				jwtDecoderFactory.setJwtValidatorFactory(jwtValidatorFactory);

				((JwtClientAssertionAuthenticationProvider) authenticationProvider)
					.setJwtDecoderFactory(jwtDecoderFactory);
			}
		});
}
----

[[oauth2AuthorizationServer-customizing-mutual-tls-client-authentication]]
=== Tùy chỉnh Mutual-TLS Client Authentication

`X509ClientCertificateAuthenticationProvider` được sử dụng để authenticate `X509Certificate` chain của client nhận được khi method `ClientAuthenticationMethod.TLS_CLIENT_AUTH` hoặc `ClientAuthenticationMethod.SELF_SIGNED_TLS_CLIENT_AUTH` được sử dụng trong quá trình OAuth2 client authentication.
Nó cũng được kết hợp với một _"Certificate Verifier"_, được sử dụng để verify nội dung của `X509Certificate` của client sau khi TLS handshake hoàn tất thành công.

[[oauth2AuthorizationServer-customizing-mutual-tls-client-authentication-pki-mutual-tls-method]]
==== PKI Mutual-TLS Method

Đối với PKI Mutual-TLS method (`ClientAuthenticationMethod.TLS_CLIENT_AUTH`), default certificate verifier implementation verify subject distinguished name của client `X509Certificate` dựa trên setting `RegisteredClient.getClientSettings.getX509CertificateSubjectDN()`.

Nếu cần verify một attribute khác của client `X509Certificate`, chẳng hạn một Subject Alternative Name (SAN) entry, ví dụ sau cho thấy cách cấu hình `X509ClientCertificateAuthenticationProvider` với một custom certificate verifier implementation:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.clientAuthentication(clientAuthentication ->
					clientAuthentication
						.authenticationProviders(configureX509ClientCertificateVerifier())
				)
		);

	return http.build();
}

private Consumer<List<AuthenticationProvider>> configureX509ClientCertificateVerifier() {
	return (authenticationProviders) ->
			authenticationProviders.forEach((authenticationProvider) -> {
				if (authenticationProvider instanceof X509ClientCertificateAuthenticationProvider) {
					Consumer<OAuth2ClientAuthenticationContext> certificateVerifier = (clientAuthenticationContext) -> {
						OAuth2ClientAuthenticationToken clientAuthentication = clientAuthenticationContext.getAuthentication();
						RegisteredClient registeredClient = clientAuthenticationContext.getRegisteredClient();
						X509Certificate[] clientCertificateChain = (X509Certificate[]) clientAuthentication.getCredentials();
						X509Certificate clientCertificate = clientCertificateChain[0];

						// TODO Verify Subject Alternative Name (SAN) entry

					};

					((X509ClientCertificateAuthenticationProvider) authenticationProvider)
							.setCertificateVerifier(certificateVerifier);
				}
			});
}
----

[[oauth2AuthorizationServer-customizing-mutual-tls-client-authentication-self-signed-certificate-mutual-tls-method]]
==== Self-Signed Certificate Mutual-TLS Method

Đối với Self-Signed Certificate Mutual-TLS method (`ClientAuthenticationMethod.SELF_SIGNED_TLS_CLIENT_AUTH`), default certificate verifier implementation sẽ retrieve JSON Web Key Set của client bằng setting `RegisteredClient.getClientSettings.getJwkSetUrl()` và mong đợi tìm thấy một match với client `X509Certificate` nhận được trong TLS handshake.

[NOTE]
Setting `RegisteredClient.getClientSettings.getJwkSetUrl()` được sử dụng để retrieve các certificate của client thông qua một JSON Web Key (JWK) Set.
Một certificate được biểu diễn bằng parameter `x5c` của một JWK riêng lẻ trong set.

[[oauth2AuthorizationServer-customizing-mutual-tls-client-authentication-client-certificate-bound-access-tokens]]
==== Client Certificate-Bound Access Tokens

Khi Mutual-TLS client authentication được sử dụng tại token endpoint, authorization server có thể bind access token đã cấp với `X509Certificate` của client.
Việc bind được thực hiện bằng cách tính SHA-256 thumbprint của client `X509Certificate` và associate thumbprint đó với access token.
Ví dụ, một JWT access token sẽ bao gồm claim `x5t#S256` chứa thumbprint của `X509Certificate` bên trong top-level `cnf` (confirmation method) claim.

Việc bind access token với `X509Certificate` của client cho phép triển khai proof-of-possession mechanism trong quá trình truy cập protected resource.
Ví dụ, protected resource sẽ lấy `X509Certificate` của client được sử dụng trong Mutual-TLS authentication, sau đó verify certificate thumbprint có khớp với claim `x5t#S256` được associate với access token hay không.

Ví dụ sau cho thấy cách enable certificate-bound access token cho một client:

[source,java]
----
RegisteredClient mtlsClient = RegisteredClient.withId(UUID.randomUUID().toString())
		.clientId("mtls-client")
		.clientAuthenticationMethod(ClientAuthenticationMethod.TLS_CLIENT_AUTH)
		.authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
		.scope("scope-a")
		.clientSettings(
				ClientSettings.builder()
						.x509CertificateSubjectDN("CN=mtls-client,OU=Spring Samples,O=Spring,C=US")
						.build()
		)
		.tokenSettings(
				TokenSettings.builder()
						.x509CertificateBoundAccessTokens(true)
						.build()
		)
		.build();
----
