[[oauth2AuthorizationServer-core-model-components]]
= Mô hình cốt lõi / Các thành phần

[[oauth2AuthorizationServer-registered-client]]
== RegisteredClient

`RegisteredClient` là biểu diễn của một client đã được https://datatracker.ietf.org/doc/html/rfc6749#section-2[đăng ký] với Authorization Server.
Client phải được đăng ký với Authorization Server trước khi có thể khởi tạo một authorization grant flow, chẳng hạn như `authorization_code` hoặc `client_credentials`.

Trong quá trình đăng ký client, client được cấp một https://datatracker.ietf.org/doc/html/rfc6749#section-2.2[định danh client] duy nhất, một client secret (tùy chọn, phụ thuộc vào https://datatracker.ietf.org/doc/html/rfc6749#section-2.1[loại client]), cùng metadata gắn với định danh client duy nhất đó.
Metadata của client có thể bao gồm các chuỗi hiển thị dành cho người dùng (chẳng hạn tên client) cho đến các mục cụ thể của một protocol flow (chẳng hạn danh sách redirect URI hợp lệ).

[TIP]
Mô hình đăng ký client tương ứng trong phần hỗ trợ OAuth2 Client của Spring Security là xref:servlet/oauth2/client/core.adoc#oauth2Client-client-registration[ClientRegistration].

Mục đích chính của client là yêu cầu quyền truy cập vào các protected resource.
Trước tiên, client yêu cầu một access token bằng cách authentication với Authorization Server và cung cấp authorization grant.
Authorization Server thực hiện authentication cho client và authorization grant; nếu chúng hợp lệ, server sẽ cấp một access token.
Sau đó client có thể yêu cầu protected resource từ Resource Server bằng cách cung cấp access token.

Ví dụ sau minh họa cách cấu hình một `RegisteredClient` được phép thực hiện flow https://datatracker.ietf.org/doc/html/rfc6749#section-4.1[grant authorization_code] để yêu cầu một access token:

[source,java]
----
RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
	.clientId("client-a")
	.clientSecret("{noop}secret")   <1>
	.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
	.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
	.redirectUri("http://127.0.0.1:8080/authorized")
	.scope("scope-a")
	.clientSettings(ClientSettings.builder().requireAuthorizationConsent(true).build())
	.build();
----
<1> `\{noop\}` biểu thị id `PasswordEncoder` cho xref:features/authentication/password-storage.adoc#authentication-password-storage-dpe[NoOpPasswordEncoder] của Spring Security.

Cấu hình tương ứng trong xref:servlet/oauth2/client/index.adoc[phần hỗ trợ OAuth2 Client] của Spring Security là:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          client-a:
            provider: spring
            client-id: client-a
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: scope-a
        provider:
          spring:
            issuer-uri: http://localhost:9000
----

Một `RegisteredClient` có metadata (các thuộc tính) gắn với Client Identifier duy nhất của nó và được định nghĩa như sau:

[source,java]
----
public class RegisteredClient implements Serializable {
	private String id;  <1>
	private String clientId;    <2>
	private Instant clientIdIssuedAt;   <3>
	private String clientSecret;    <4>
	private Instant clientSecretExpiresAt;  <5>
	private String clientName;  <6>
	private Set<ClientAuthenticationMethod> clientAuthenticationMethods;    <7>
	private Set<AuthorizationGrantType> authorizationGrantTypes;    <8>
	private Set<String> redirectUris;   <9>
	private Set<String> postLogoutRedirectUris; <10>
	private Set<String> scopes; <11>
	private ClientSettings clientSettings;  <12>
	private TokenSettings tokenSettings;    <13>

	...

}
----
<1> `id`: ID định danh duy nhất `RegisteredClient`.
<2> `clientId`: Định danh client.
<3> `clientIdIssuedAt`: Thời điểm định danh client được cấp.
<4> `clientSecret`: Secret của client. Giá trị này nên được mã hóa bằng xref:features/authentication/password-storage.adoc#authentication-password-storage-dpe[PasswordEncoder] của Spring Security.
<5> `clientSecretExpiresAt`: Thời điểm client secret hết hạn.
<6> `clientName`: Tên mô tả được sử dụng cho client. Tên này có thể được sử dụng trong một số tình huống, chẳng hạn khi hiển thị tên client trên trang consent.
<7> `clientAuthenticationMethods`: Các phương thức authentication mà client có thể sử dụng. Các giá trị được hỗ trợ là `client_secret_basic`, `client_secret_post`, https://datatracker.ietf.org/doc/html/rfc7523[`private_key_jwt`], `client_secret_jwt` và `none` https://datatracker.ietf.org/doc/html/rfc7636[(public client)].
<8> `authorizationGrantTypes`: Các https://datatracker.ietf.org/doc/html/rfc6749#section-1.3[loại authorization grant] mà client có thể sử dụng. Các giá trị được hỗ trợ là `authorization_code`, `client_credentials`, `refresh_token`, `urn:ietf:params:oauth:grant-type:device_code` và `urn:ietf:params:oauth:grant-type:token-exchange`.
<9> `redirectUris`: Các https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2[redirect URI] đã đăng ký mà client có thể sử dụng trong các flow dựa trên redirect, ví dụ grant `authorization_code`.
<10> `postLogoutRedirectUris`: Các redirect URI sau logout mà client có thể sử dụng cho logout.
<11> `scopes`: Các scope mà client được phép yêu cầu.
<12> `clientSettings`: Các thiết lập tùy chỉnh cho client, chẳng hạn yêu cầu https://datatracker.ietf.org/doc/html/rfc7636[PKCE], yêu cầu authorization consent và các thiết lập khác.
<13> `tokenSettings`: Các thiết lập tùy chỉnh cho OAuth2 token được cấp cho client, chẳng hạn thời gian tồn tại của access/refresh token, tái sử dụng refresh token và các thiết lập khác.

[[oauth2AuthorizationServer-client-settings]]
== ClientSettings

`ClientSettings` chứa các thiết lập cấu hình gắn với một `RegisteredClient`.

`ClientSettings` cung cấp các accessor sau:

[source,java]
----
public final class ClientSettings extends AbstractSettings {

    public boolean isRequireProofKey() ...  <1>

    public boolean isRequireAuthorizationConsent() ...  <2>

    public String getJwkSetUrl() ...    <3>

    public JwsAlgorithm getTokenEndpointAuthenticationSigningAlgorithm() ...    <4>

    public String getX509CertificateSubjectDN() ... <5>

	...

}
----
<1> `isRequireProofKey()`: Nếu là `true`, client bắt buộc phải cung cấp proof key challenge và verifier khi thực hiện flow Authorization Code Grant (PKCE). Giá trị mặc định là `true`.
<2> `isRequireAuthorizationConsent()`: Nếu là `true`, authorization consent là bắt buộc khi client yêu cầu quyền truy cập. Giá trị mặc định là `false`.
<3> `getJwkSetUrl()`: `URL` của JSON Web Key Set của client. Được sử dụng cho các phương thức client authentication `private_key_jwt`, `self_signed_tls_client_auth` và `client_secret_jwt`.
<4> `getTokenEndpointAuthenticationSigningAlgorithm()`: `JwsAlgorithm` phải được sử dụng để ký JWT dùng để authentication client tại Token Endpoint cho các phương thức authentication `private_key_jwt` và `client_secret_jwt`.
<5> `getX509CertificateSubjectDN()`: Subject distinguished name dự kiến gắn với `X509Certificate` của client nhận được trong quá trình client authentication khi sử dụng phương thức `tls_client_auth`.

[NOTE]
https://datatracker.ietf.org/doc/html/rfc7636[Proof Key for Code Exchange (PKCE)] được bật theo mặc định cho mọi client sử dụng Authorization Code grant. Để tắt PKCE, đặt `requireProofKey` thành `false`.

[[oauth2AuthorizationServer-registered-client-repository]]
== RegisteredClientRepository

`RegisteredClientRepository` là thành phần trung tâm nơi client mới có thể được đăng ký và các client hiện có có thể được truy vấn.
Nó được các thành phần khác sử dụng khi thực hiện một protocol flow cụ thể, chẳng hạn client authentication, xử lý authorization grant, token introspection, dynamic client registration và các flow khác.

Các implementation được cung cấp của `RegisteredClientRepository` là `InMemoryRegisteredClientRepository` và `JdbcRegisteredClientRepository`.
Implementation `InMemoryRegisteredClientRepository` lưu các instance `RegisteredClient` trong bộ nhớ và *CHỈ* được khuyến nghị sử dụng trong quá trình phát triển và kiểm thử.
`JdbcRegisteredClientRepository` là implementation JDBC lưu bền vững các instance `RegisteredClient` bằng `JdbcOperations`.

[NOTE]
`RegisteredClientRepository` là một thành phần *BẮT BUỘC*.

Ví dụ sau minh họa cách đăng ký `RegisteredClientRepository` `@Bean`:

[source,java]
----
@Bean
public RegisteredClientRepository registeredClientRepository() {
	List<RegisteredClient> registrations = ...
	return new InMemoryRegisteredClientRepository(registrations);
}
----

Ngoài ra, bạn có thể cấu hình `RegisteredClientRepository` thông qua xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-customizing-the-configuration[`OAuth2AuthorizationServerConfigurer`]:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.registeredClientRepository(registeredClientRepository)
		)
	    ...

	return http.build();
}
----

[NOTE]
`OAuth2AuthorizationServerConfigurer` hữu ích khi áp dụng đồng thời nhiều tùy chọn cấu hình.

[[oauth2AuthorizationServer-oauth2-authorization]]
== OAuth2Authorization

Một `OAuth2Authorization` là biểu diễn của một OAuth2 authorization, lưu trạng thái liên quan đến authorization được cấp cho xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client[client] bởi resource owner, hoặc bởi chính client trong trường hợp authorization grant type `client_credentials`.

[TIP]
Mô hình authorization tương ứng trong phần hỗ trợ OAuth2 Client của Spring Security là xref:servlet/oauth2/client/core.adoc#oauth2Client-authorized-client[OAuth2AuthorizedClient].

Sau khi một authorization grant flow hoàn tất thành công, một `OAuth2Authorization` được tạo và gắn với một javadoc:org.springframework.security.oauth2.core.OAuth2AccessToken[], một javadoc:org.springframework.security.oauth2.core.OAuth2RefreshToken[] (tùy chọn), cùng trạng thái bổ sung dành riêng cho authorization grant type đã thực thi.

Các instance javadoc:org.springframework.security.oauth2.core.OAuth2Token[] gắn với một `OAuth2Authorization` thay đổi tùy theo authorization grant type.

Đối với OAuth2 https://datatracker.ietf.org/doc/html/rfc6749#section-4.1[grant authorization_code], một `OAuth2AuthorizationCode`, một `OAuth2AccessToken` và một `OAuth2RefreshToken` (tùy chọn) được gắn với nó.

Đối với OpenID Connect 1.0 https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[grant authorization_code], một `OAuth2AuthorizationCode`, một javadoc:org.springframework.security.oauth2.core.oidc.OidcIdToken[], một `OAuth2AccessToken` và một `OAuth2RefreshToken` (tùy chọn) được gắn với nó.

Đối với OAuth2 https://datatracker.ietf.org/doc/html/rfc6749#section-4.4[grant client_credentials], chỉ một `OAuth2AccessToken` được gắn với nó.

`OAuth2Authorization` và các thuộc tính của nó được định nghĩa như sau:

[source,java]
----
public class OAuth2Authorization implements Serializable {
	private String id;  <1>
	private String registeredClientId;  <2>
	private String principalName;   <3>
	private AuthorizationGrantType authorizationGrantType;  <4>
	private Set<String> authorizedScopes;   <5>
	private Map<Class<? extends OAuth2Token>, Token<?>> tokens; <6>
	private Map<String, Object> attributes; <7>

	...

}
----
<1> `id`: ID định danh duy nhất `OAuth2Authorization`.
<2> `registeredClientId`: ID định danh duy nhất xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client[RegisteredClient].
<3> `principalName`: Tên principal của resource owner (hoặc client).
<4> `authorizationGrantType`: `AuthorizationGrantType` được sử dụng.
<5> `authorizedScopes`: `Set` các scope được authorization cho client.
<6> `tokens`: Các instance `OAuth2Token` (và metadata gắn với chúng) dành riêng cho authorization grant type đã thực thi.
<7> `attributes`: Các thuộc tính bổ sung dành riêng cho authorization grant type đã thực thi, chẳng hạn `Principal` đã authentication, `OAuth2AuthorizationRequest` và các thuộc tính khác.

`OAuth2Authorization` và các instance `OAuth2Token` gắn với nó có một vòng đời xác định.
Một `OAuth2Token` mới được cấp ở trạng thái active và trở thành inactive khi hết hạn hoặc bị vô hiệu hóa (revoked).
`OAuth2Authorization` (ngầm định) ở trạng thái inactive khi mọi instance `OAuth2Token` gắn với nó đều inactive.
Mỗi `OAuth2Token` được lưu trong một `OAuth2Authorization.Token`, cung cấp các accessor `isExpired()`, `isInvalidated()` và `isActive()`.

`OAuth2Authorization.Token` cũng cung cấp `getClaims()`, trả về các claim (nếu có) gắn với `OAuth2Token`.

[[oauth2AuthorizationServer-oauth2-authorization-service]]
== OAuth2AuthorizationService

`OAuth2AuthorizationService` là thành phần trung tâm nơi các authorization mới được lưu trữ và các authorization hiện có được truy vấn.
Nó được các thành phần khác sử dụng khi thực hiện một protocol flow cụ thể, chẳng hạn client authentication, xử lý authorization grant, token introspection, token revocation, dynamic client registration và các flow khác.

Các implementation được cung cấp của `OAuth2AuthorizationService` là `InMemoryOAuth2AuthorizationService` và `JdbcOAuth2AuthorizationService`.
Implementation `InMemoryOAuth2AuthorizationService` lưu các instance `OAuth2Authorization` trong bộ nhớ và *CHỈ* được khuyến nghị sử dụng trong quá trình phát triển và kiểm thử.
`JdbcOAuth2AuthorizationService` là implementation JDBC lưu bền vững các instance `OAuth2Authorization` bằng `JdbcOperations`.

[NOTE]
`OAuth2AuthorizationService` là một thành phần *TÙY CHỌN* và mặc định là `InMemoryOAuth2AuthorizationService`.

Ví dụ sau minh họa cách đăng ký `OAuth2AuthorizationService` `@Bean`:

[source,java]
----
@Bean
public OAuth2AuthorizationService authorizationService() {
	return new InMemoryOAuth2AuthorizationService();
}
----

Ngoài ra, bạn có thể cấu hình `OAuth2AuthorizationService` thông qua xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-customizing-the-configuration[`OAuth2AuthorizationServerConfigurer`]:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.authorizationService(authorizationService)
		)
	    ...

	return http.build();
}
----

[NOTE]
`OAuth2AuthorizationServerConfigurer` hữu ích khi áp dụng đồng thời nhiều tùy chọn cấu hình.

[[oauth2AuthorizationServer-oauth2-authorization-consent]]
== OAuth2AuthorizationConsent

Một `OAuth2AuthorizationConsent` là biểu diễn của "consent" (quyết định) authorization từ một https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1[OAuth2 authorization request flow], chẳng hạn grant `authorization_code`, lưu các authority được resource owner cấp cho xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client[client].

Khi authorization quyền truy cập cho một client, resource owner có thể chỉ cấp một tập con các authority mà client yêu cầu.
Trường hợp sử dụng điển hình là flow grant `authorization_code`, trong đó client yêu cầu các scope và resource owner cấp (hoặc từ chối) quyền truy cập vào các scope được yêu cầu.

Sau khi một OAuth2 authorization request flow hoàn tất, một `OAuth2AuthorizationConsent` được tạo (hoặc cập nhật) và gắn các authority đã cấp với client và resource owner.

`OAuth2AuthorizationConsent` và các thuộc tính của nó được định nghĩa như sau:

[source,java]
----
public final class OAuth2AuthorizationConsent implements Serializable {
	private final String registeredClientId;    <1>
	private final String principalName; <2>
	private final Set<GrantedAuthority> authorities;    <3>

	...

}
----
<1> `registeredClientId`: ID định danh duy nhất xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client[RegisteredClient].
<2> `principalName`: Tên principal của resource owner.
<3> `authorities`: Các authority được resource owner cấp cho client. Một authority có thể biểu thị một scope, claim, permission, role và các khái niệm khác.

[[oauth2AuthorizationServer-oauth2-authorization-consent-service]]
== OAuth2AuthorizationConsentService

`OAuth2AuthorizationConsentService` là thành phần trung tâm nơi các authorization consent mới được lưu trữ và các authorization consent hiện có được truy vấn.
Nó chủ yếu được các thành phần triển khai OAuth2 authorization request flow sử dụng, chẳng hạn grant `authorization_code`.

Các implementation được cung cấp của `OAuth2AuthorizationConsentService` là `InMemoryOAuth2AuthorizationConsentService` và `JdbcOAuth2AuthorizationConsentService`.
Implementation `InMemoryOAuth2AuthorizationConsentService` lưu các instance `OAuth2AuthorizationConsent` trong bộ nhớ và *CHỈ* được khuyến nghị sử dụng cho phát triển và kiểm thử.
`JdbcOAuth2AuthorizationConsentService` là implementation JDBC lưu bền vững các instance `OAuth2AuthorizationConsent` bằng `JdbcOperations`.

[NOTE]
`OAuth2AuthorizationConsentService` là một thành phần *TÙY CHỌN* và mặc định là `InMemoryOAuth2AuthorizationConsentService`.

Ví dụ sau minh họa cách đăng ký `OAuth2AuthorizationConsentService` `@Bean`:

[source,java]
----
@Bean
public OAuth2AuthorizationConsentService authorizationConsentService() {
	return new InMemoryOAuth2AuthorizationConsentService();
}
----

Ngoài ra, bạn có thể cấu hình `OAuth2AuthorizationConsentService` thông qua xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-customizing-the-configuration[`OAuth2AuthorizationServerConfigurer`]:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.authorizationConsentService(authorizationConsentService)
		)
	    ...

	return http.build();
}
----

[NOTE]
`OAuth2AuthorizationServerConfigurer` hữu ích khi áp dụng đồng thời nhiều tùy chọn cấu hình.

[[oauth2AuthorizationServer-oauth2-token-context]]
== OAuth2TokenContext

Một `OAuth2TokenContext` là đối tượng context lưu thông tin gắn với một `OAuth2Token` và được xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-generator[OAuth2TokenGenerator] cùng xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-customizer[OAuth2TokenCustomizer] sử dụng.

`OAuth2TokenContext` cung cấp các accessor sau:

[source,java]
----
public interface OAuth2TokenContext extends Context {

	default RegisteredClient getRegisteredClient() ...  <1>

	default <T extends Authentication> T getPrincipal() ... <2>

	default AuthorizationServerContext getAuthorizationServerContext() ...    <3>

	@Nullable
	default OAuth2Authorization getAuthorization() ...  <4>

	default Set<String> getAuthorizedScopes() ...   <5>

	default OAuth2TokenType getTokenType() ...  <6>

	default AuthorizationGrantType getAuthorizationGrantType() ...  <7>

	default <T extends Authentication> T getAuthorizationGrant() ...    <8>

	...

}
----
<1> `getRegisteredClient()`: xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client[RegisteredClient] gắn với authorization grant.
<2> `getPrincipal()`: Instance `Authentication` của resource owner (hoặc client).
<3> `getAuthorizationServerContext()`: Đối tượng xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-configuring-authorization-server-settings[`AuthorizationServerContext`] lưu thông tin về môi trường runtime của Authorization Server.
<4> `getAuthorization()`: xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-authorization[OAuth2Authorization] gắn với authorization grant.
<5> `getAuthorizedScopes()`: Các scope được authorization cho client.
<6> `getTokenType()`: `OAuth2TokenType` cần tạo. Các giá trị được hỗ trợ là `code`, `access_token`, `refresh_token` và `id_token`.
<7> `getAuthorizationGrantType()`: `AuthorizationGrantType` gắn với authorization grant.
<8> `getAuthorizationGrant()`: Instance `Authentication` được `AuthenticationProvider` xử lý authorization grant sử dụng.

[[oauth2AuthorizationServer-oauth2-token-generator]]
== OAuth2TokenGenerator

Một `OAuth2TokenGenerator` chịu trách nhiệm tạo `OAuth2Token` từ thông tin chứa trong xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-context[OAuth2TokenContext] được cung cấp.

`OAuth2Token` được tạo chủ yếu phụ thuộc vào kiểu `OAuth2TokenType` được chỉ định trong `OAuth2TokenContext`.

Ví dụ, khi `value` của `OAuth2TokenType` là:

* `code`, thì `OAuth2AuthorizationCode` được tạo.
* `access_token`, thì `OAuth2AccessToken` được tạo.
* `refresh_token`, thì `OAuth2RefreshToken` được tạo.
* `id_token`, thì `OidcIdToken` được tạo.

Ngoài ra, format của `OAuth2AccessToken` được tạo thay đổi tùy theo `TokenSettings.getAccessTokenFormat()` được cấu hình cho xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client[RegisteredClient].
Nếu format là `OAuth2TokenFormat.SELF_CONTAINED` (mặc định), thì một `Jwt` được tạo.
Nếu format là `OAuth2TokenFormat.REFERENCE`, thì một token "opaque" được tạo.

Cuối cùng, nếu `OAuth2Token` được tạo có một tập claim và triển khai `ClaimAccessor`, các claim có thể được truy cập từ xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-authorization[OAuth2Authorization.Token.getClaims()].

`OAuth2TokenGenerator` chủ yếu được các thành phần triển khai xử lý authorization grant sử dụng, chẳng hạn `authorization_code`, `client_credentials` và `refresh_token`.

Các implementation được cung cấp là `OAuth2AccessTokenGenerator`, `OAuth2RefreshTokenGenerator` và `JwtGenerator`.
`OAuth2AccessTokenGenerator` tạo một access token "opaque" (`OAuth2TokenFormat.REFERENCE`), còn `JwtGenerator` tạo một `Jwt` (`OAuth2TokenFormat.SELF_CONTAINED`).

[NOTE]
`OAuth2TokenGenerator` là một thành phần *TÙY CHỌN* và mặc định là `DelegatingOAuth2TokenGenerator` được cấu thành từ `OAuth2AccessTokenGenerator` và `OAuth2RefreshTokenGenerator`.

[NOTE]
Nếu một `JwtEncoder` `@Bean` hoặc `JWKSource<SecurityContext>` `@Bean` được đăng ký, một `JwtGenerator` cũng được thêm vào `DelegatingOAuth2TokenGenerator`.

`OAuth2TokenGenerator` cung cấp tính linh hoạt cao vì có thể hỗ trợ mọi token format tùy chỉnh cho `access_token` và `refresh_token`.

Ví dụ sau minh họa cách đăng ký `OAuth2TokenGenerator` `@Bean`:

[source,java]
----
@Bean
public OAuth2TokenGenerator<?> tokenGenerator() {
	JwtEncoder jwtEncoder = ...
	JwtGenerator jwtGenerator = new JwtGenerator(jwtEncoder);
	OAuth2AccessTokenGenerator accessTokenGenerator = new OAuth2AccessTokenGenerator();
	OAuth2RefreshTokenGenerator refreshTokenGenerator = new OAuth2RefreshTokenGenerator();
	return new DelegatingOAuth2TokenGenerator(
			jwtGenerator, accessTokenGenerator, refreshTokenGenerator);
}
----

Ngoài ra, bạn có thể cấu hình `OAuth2TokenGenerator` thông qua xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-customizing-the-configuration[`OAuth2AuthorizationServerConfigurer`]:

[source,java]
----
@Bean
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
	http
		.oauth2AuthorizationServer((authorizationServer) ->
			authorizationServer
				.tokenGenerator(tokenGenerator)
		)
	    ...

	return http.build();
}
----

[NOTE]
`OAuth2AuthorizationServerConfigurer` hữu ích khi áp dụng đồng thời nhiều tùy chọn cấu hình.

[[oauth2AuthorizationServer-oauth2-token-customizer]]
== OAuth2TokenCustomizer

Một `OAuth2TokenCustomizer` cung cấp khả năng tùy chỉnh các thuộc tính của một `OAuth2Token`, những thuộc tính này có thể được truy cập trong xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-context[OAuth2TokenContext] được cung cấp.
Nó được xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-oauth2-token-generator[OAuth2TokenGenerator] sử dụng để tùy chỉnh các thuộc tính của `OAuth2Token` trước khi token được tạo.

Một `OAuth2TokenCustomizer<OAuth2TokenClaimsContext>` được khai báo với kiểu generic `OAuth2TokenClaimsContext` (`implements OAuth2TokenContext`) cung cấp khả năng tùy chỉnh các claim của một `OAuth2AccessToken` "opaque".
`OAuth2TokenClaimsContext.getClaims()` cung cấp quyền truy cập vào `OAuth2TokenClaimsSet.Builder`, cho phép thêm, thay thế và xóa claim.

Ví dụ sau minh họa cách triển khai một `OAuth2TokenCustomizer<OAuth2TokenClaimsContext>` và cấu hình nó với một `OAuth2AccessTokenGenerator`:

[source,java]
----
@Bean
public OAuth2TokenGenerator<?> tokenGenerator() {
	JwtEncoder jwtEncoder = ...
	JwtGenerator jwtGenerator = new JwtGenerator(jwtEncoder);
	OAuth2AccessTokenGenerator accessTokenGenerator = new OAuth2AccessTokenGenerator();
	accessTokenGenerator.setAccessTokenCustomizer(accessTokenCustomizer());
	OAuth2RefreshTokenGenerator refreshTokenGenerator = new OAuth2RefreshTokenGenerator();
	return new DelegatingOAuth2TokenGenerator(
			jwtGenerator, accessTokenGenerator, refreshTokenGenerator);
}

@Bean
public OAuth2TokenCustomizer<OAuth2TokenClaimsContext> accessTokenCustomizer() {
	return context -> {
		OAuth2TokenClaimsSet.Builder claims = context.getClaims();
		// Customize claims

	};
}
----

[NOTE]
Nếu `OAuth2TokenGenerator` không được cung cấp dưới dạng `@Bean` hoặc không được cấu hình thông qua `OAuth2AuthorizationServerConfigurer`, một `OAuth2TokenCustomizer<OAuth2TokenClaimsContext>` `@Bean` sẽ tự động được cấu hình với một `OAuth2AccessTokenGenerator`.

Một `OAuth2TokenCustomizer<JwtEncodingContext>` được khai báo với kiểu generic `JwtEncodingContext` (`implements OAuth2TokenContext`) cung cấp khả năng tùy chỉnh header và claim của một `Jwt`.
`JwtEncodingContext.getJwsHeader()` cung cấp quyền truy cập vào `JwsHeader.Builder`, cho phép thêm, thay thế và xóa header.
`JwtEncodingContext.getClaims()` cung cấp quyền truy cập vào `JwtClaimsSet.Builder`, cho phép thêm, thay thế và xóa claim.

Ví dụ sau minh họa cách triển khai một `OAuth2TokenCustomizer<JwtEncodingContext>` và cấu hình nó với một `JwtGenerator`:

[source,java]
----
@Bean
public OAuth2TokenGenerator<?> tokenGenerator() {
	JwtEncoder jwtEncoder = ...
	JwtGenerator jwtGenerator = new JwtGenerator(jwtEncoder);
	jwtGenerator.setJwtCustomizer(jwtCustomizer());
	OAuth2AccessTokenGenerator accessTokenGenerator = new OAuth2AccessTokenGenerator();
	OAuth2RefreshTokenGenerator refreshTokenGenerator = new OAuth2RefreshTokenGenerator();
	return new DelegatingOAuth2TokenGenerator(
			jwtGenerator, accessTokenGenerator, refreshTokenGenerator);
}

@Bean
public OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer() {
	return context -> {
		JwsHeader.Builder headers = context.getJwsHeader();
		JwtClaimsSet.Builder claims = context.getClaims();
		if (context.getTokenType().equals(OAuth2TokenType.ACCESS_TOKEN)) {
			// Customize headers/claims for access_token

		} else if (context.getTokenType().getValue().equals(OidcParameterNames.ID_TOKEN)) {
			// Customize headers/claims for id_token

		}
	};
}
----

[NOTE]
Nếu `OAuth2TokenGenerator` không được cung cấp dưới dạng `@Bean` hoặc không được cấu hình thông qua `OAuth2AuthorizationServerConfigurer`, một `OAuth2TokenCustomizer<JwtEncodingContext>` `@Bean` sẽ tự động được cấu hình với một `JwtGenerator`.

[[oauth2AuthorizationServer-session-registry]]
== SessionRegistry

Nếu OpenID Connect 1.0 được bật, một instance `SessionRegistry` được sử dụng để theo dõi các session đã authentication.
`SessionRegistry` được implementation mặc định của `SessionAuthenticationStrategy` gắn với xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oauth2-authorization-endpoint[OAuth2 Authorization Endpoint] sử dụng để đăng ký các session đã authentication mới.

[NOTE]
Nếu một `SessionRegistry` `@Bean` chưa được đăng ký, implementation mặc định `SessionRegistryImpl` sẽ được sử dụng.

[IMPORTANT]
Nếu một `SessionRegistry` `@Bean` được đăng ký và là một instance của `SessionRegistryImpl`, một `HttpSessionEventPublisher` `@Bean` cũng *NÊN* được đăng ký vì nó chịu trách nhiệm thông báo cho `SessionRegistryImpl` về các sự kiện vòng đời session, chẳng hạn `SessionDestroyedEvent`, để có thể xóa instance `SessionInformation`.

Khi End-User yêu cầu logout, xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc#oauth2AuthorizationServer-oidc-logout-endpoint[OpenID Connect 1.0 Logout Endpoint] sử dụng `SessionRegistry` để tra cứu `SessionInformation` gắn với End-User đã authentication nhằm thực hiện logout.

Nếu tính năng xref:servlet/authentication/session-management.adoc#ns-concurrent-sessions[Concurrent Session Control] của Spring Security đang được sử dụng, *KHUYẾN NGHỊ* đăng ký một `SessionRegistry` `@Bean` để bảo đảm nó được dùng chung giữa Concurrent Session Control của Spring Security và tính năng Logout của Spring Security Authorization Server.

Ví dụ sau minh họa cách đăng ký `SessionRegistry` `@Bean` và `HttpSessionEventPublisher` `@Bean` (bắt buộc đối với `SessionRegistryImpl`):

[source,java]
----
@Bean
public SessionRegistry sessionRegistry() {
	return new SessionRegistryImpl();
}

@Bean
public HttpSessionEventPublisher httpSessionEventPublisher() {
	return new HttpSessionEventPublisher();
}
----
