
[[oauth2AuthorizationServer-getting-started]]
= Bắt đầu

Nếu bạn mới bắt đầu với Spring Security Authorization Server, các phần sau sẽ hướng dẫn bạn tạo ứng dụng đầu tiên.

[[oauth2AuthorizationServer-system-requirements]]
== Yêu cầu hệ thống

Spring Security Authorization Server yêu cầu môi trường runtime Java 17 trở lên.

[[oauth2AuthorizationServer-installing-spring-security-authorization-server]]
== Cài đặt Spring Security Authorization Server

Cách dễ nhất để bắt đầu sử dụng Spring Security Authorization Server là tạo một ứng dụng dựa trên https://spring.io/projects/spring-boot[Spring Boot].
Bạn có thể sử dụng https://start.spring.io[start.spring.io] để tạo một dự án cơ bản hoặc dùng https://github.com/spring-projects/spring-authorization-server/tree/main/samples/default-authorizationserver[mẫu Authorization Server mặc định] làm hướng dẫn.
Sau đó thêm starter của Spring Boot cho Spring Security Authorization Server dưới dạng dependency:

[tabs]
======
Maven::
+
[[oauth2AuthorizationServer-spring-boot-maven-dependency]]
[source,xml,role="primary",subs="attributes,verbatim"]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-authorization-server</artifactId>
</dependency>
----

Gradle::
+
[[oauth2AuthorizationServer-spring-boot-gradle-dependency]]
[source,gradle,role="secondary",subs="attributes,verbatim"]
----
implementation "org.springframework.boot:spring-boot-starter-oauth2-authorization-server"
----
======

TIP: Xem {spring-boot-reference-url}installing.html[Cài đặt Spring Boot] để biết thêm thông tin về cách sử dụng Spring Boot với Maven hoặc Gradle.

Ngoài ra, bạn có thể thêm Spring Security Authorization Server mà không cần Spring Boot như trong ví dụ sau:

[tabs]
======
Maven::
+
[[oauth2AuthorizationServer-maven-dependency]]
[source,xml,role="primary",subs="attributes,verbatim"]
----
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-oauth2-authorization-server</artifactId>
    <version>{spring-security-version}</version>
</dependency>
----

Gradle::
+
[[oauth2AuthorizationServer-gradle-dependency]]
[source,gradle,role="secondary",subs="attributes,verbatim"]
----
implementation "org.springframework.security:spring-security-oauth2-authorization-server:{spring-security-version}"
----
======

[[oauth2AuthorizationServer-developing-your-first-application]]
== Phát triển ứng dụng đầu tiên

Để bắt đầu, bạn cần định nghĩa các component tối thiểu cần thiết dưới dạng một `@Bean`. Khi sử dụng dependency `spring-boot-starter-oauth2-authorization-server`, hãy định nghĩa các property sau và Spring Boot sẽ cung cấp các định nghĩa `@Bean` cần thiết cho bạn:

[[oauth2AuthorizationServer-application-yml]]
.application.yml
[source,yaml]
----
server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
----

Nếu muốn tùy chỉnh cấu hình `HttpSecurity` mặc định, bạn có thể ghi đè auto-configuration của Spring Boot như trong ví dụ sau:

[[oauth2AuthorizationServer-minimal-sample-gettingstarted]]
.SecurityConfig.java
[source,java]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) {
		http
			.authorizeHttpRequests((authorize) ->
				authorize
					.anyRequest().authenticated()
			)
			.formLogin(Customizer.withDefaults())
			.oauth2AuthorizationServer((authorizationServer) ->
				authorizationServer
					.oidc(Customizer.withDefaults())	// Bật OpenID Connect 1.0
			);
		return http.build();
	}

}
----

TIP: Ngoài phần Bắt đầu, hầu hết người dùng sẽ muốn tùy chỉnh cấu hình mặc định. xref:servlet/oauth2/authorization-server/getting-started.adoc#oauth2AuthorizationServer-defining-required-components[Phần tiếp theo] minh họa cách tự cung cấp tất cả các bean cần thiết.

[[oauth2AuthorizationServer-defining-required-components]]
== Định nghĩa các component bắt buộc

Nếu muốn tùy chỉnh cấu hình mặc định (bất kể bạn có sử dụng Spring Boot hay không), bạn có thể định nghĩa các component tối thiểu cần thiết dưới dạng một `@Bean` trong một Spring `@Configuration`.

Bạn có thể định nghĩa các component này như sau:

[[oauth2AuthorizationServer-sample-gettingstarted]]
.SecurityConfig.java
[source,java]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean // <1>
	@Order(1)
	public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http)
			throws Exception {

		// @formatter:off
		http
			.oauth2AuthorizationServer((authorizationServer) -> {
				http.securityMatcher(authorizationServer.getEndpointsMatcher());
				authorizationServer
					.oidc(Customizer.withDefaults());	// Bật OpenID Connect 1.0
			})
			.authorizeHttpRequests((authorize) ->
				authorize
					.anyRequest().authenticated()
			)
			// Chuyển hướng đến trang đăng nhập khi request từ authorization endpoint
			// chưa được authenticate
			.exceptionHandling((exceptions) -> exceptions
				.defaultAuthenticationEntryPointFor(
					new LoginUrlAuthenticationEntryPoint("/login"),
					new MediaTypeRequestMatcher(MediaType.TEXT_HTML)
				)
			);
		// @formatter:on

		return http.build();
	}

	@Bean // <2>
	@Order(2)
	public SecurityFilterChain defaultSecurityFilterChain(HttpSecurity http)
			throws Exception {
		// @formatter:off
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			// Form login xử lý việc chuyển hướng đến trang đăng nhập từ
			// authorization server filter chain
			.formLogin(Customizer.withDefaults());
		// @formatter:on

		return http.build();
	}

	@Bean // <3>
	public UserDetailsService userDetailsService() {
		// @formatter:off
		UserDetails userDetails = User.withDefaultPasswordEncoder()
				.username("user")
				.password("password")
				.roles("USER")
				.build();
		// @formatter:on

		return new InMemoryUserDetailsManager(userDetails);
	}

	@Bean // <4>
	public RegisteredClientRepository registeredClientRepository() {
		// @formatter:off
		RegisteredClient oidcClient = RegisteredClient.withId(UUID.randomUUID().toString())
				.clientId("oidc-client")
				.clientSecret("{noop}secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
				.redirectUri("http://127.0.0.1:8080/login/oauth2/code/oidc-client")
				.postLogoutRedirectUri("http://127.0.0.1:8080/")
				.scope(OidcScopes.OPENID)
				.scope(OidcScopes.PROFILE)
				.clientSettings(ClientSettings.builder().requireAuthorizationConsent(true).build())
				.build();
		// @formatter:on

		return new InMemoryRegisteredClientRepository(oidcClient);
	}

	@Bean // <5>
	public JWKSource<SecurityContext> jwkSource() {
		KeyPair keyPair = generateRsaKey();
		RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();
		RSAPrivateKey privateKey = (RSAPrivateKey) keyPair.getPrivate();
		// @formatter:off
		RSAKey rsaKey = new RSAKey.Builder(publicKey)
				.privateKey(privateKey)
				.keyID(UUID.randomUUID().toString())
				.build();
		// @formatter:on
		JWKSet jwkSet = new JWKSet(rsaKey);
		return new ImmutableJWKSet<>(jwkSet);
	}

	private static KeyPair generateRsaKey() { // <6>
		KeyPair keyPair;
		try {
			KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
			keyPairGenerator.initialize(2048);
			keyPair = keyPairGenerator.generateKeyPair();
		}
		catch (Exception ex) {
			throw new IllegalStateException(ex);
		}
		return keyPair;
	}

	@Bean // <7>
	public JwtDecoder jwtDecoder(JWKSource<SecurityContext> jwkSource) {
		return OAuth2AuthorizationServerConfiguration.jwtDecoder(jwkSource);
	}

	@Bean // <8>
	public AuthorizationServerSettings authorizationServerSettings() {
		return AuthorizationServerSettings.builder().build();
	}

}
----

Đây là cấu hình tối thiểu để nhanh chóng bắt đầu. Để hiểu mỗi component được dùng để làm gì, hãy xem các mô tả sau:

<1> Một Spring Security filter chain dành cho xref:servlet/oauth2/authorization-server/protocol-endpoints.adoc[các endpoint giao thức].
<2> Một Spring Security filter chain dành cho xref:servlet/authentication/index.adoc#servlet-authentication[authentication].
<3> Một instance của javadoc:org.springframework.security.core.userdetails.UserDetailsService[] để truy xuất các user cần được authenticate.
<4> Một instance của xref:servlet/oauth2/authorization-server/core-model-components.adoc#oauth2AuthorizationServer-registered-client-repository[`RegisteredClientRepository`] để quản lý các client.
<5> Một instance của `com.nimbusds.jose.jwk.source.JWKSource` để ký access token.
<6> Một instance của `java.security.KeyPair` với các key được tạo khi startup, dùng để tạo `JWKSource` nêu trên.
<7> Một instance của javadoc:org.springframework.security.oauth2.jwt.JwtDecoder[] để giải mã access token đã ký.
<8> Một instance của xref:servlet/oauth2/authorization-server/configuration-model.adoc#oauth2AuthorizationServer-configuring-authorization-server-settings[`AuthorizationServerSettings`] để cấu hình Spring Security Authorization Server.
